### PR TITLE
KOReader - Better Russian Keyboard Layout (with Kazakh)

### PR DESCRIPTION
**Pull request by mergen3107**
Dear KOReader Dev Community!
Here is a suggestion coming from [this](https://github.com/koreader/koreader/issues/2023) thread.

The file virtualkeyboard.lua is atteched in a ZIP archive:
[koreader-KZ-Keyboard.zip](https://github.com/koreader/koreader/files/266119/koreader-KZ-Keyboard.zip)

Thank you!

### CODE REVIEW

**Comment by NiLuJe** [comment]
I think you mixep up something in the source -> target of your PR, didn't you? ;).

**Comment by mergen3107** [comment]
@NiLuJe 
yeah, I still don't get how to properly add a new Pull Request. It asks to choose one of the comparisons, so I got totally confused.
If there something I missed to read carefully?

**Comment by NiLuJe** [comment]
@mergen3107: [GH's Help](https://help.github.com/) has some human-readable intro to git & GH.

If you want to delve into a specific issue, the go to place is the [Git Book](https://git-scm.com/book/en/v2) ;).

Basically, you want to make sure your fork is up to date with the "master" repo (usually you setup an "upstream" remote to point to it), so the PR will only pickup *your* commit.

**Comment by mergen3107** [comment]
Thank you! I'll read that on my spare time :)

**Comment by houqp** [comment]
I will take sometime to manually apply the patch in the zip file tonight. Thanks @mergen3107 for the work.

**Comment by mergen3107** [comment]
Thank you too for your enthusiastic hard work! I am happy to contribute :)

**Pull request closed without merging**
