### PR TITLE
[Kobo] Don't send a flood a FrontlightStateChanged events during the FL ramps

### PR DESCRIPTION
**Pull request by NiLuJe**
This made the ReaderFooter refresh go super-wonky...

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/6667)

### CODE REVIEW

**Comment by Frenzie** [comment]
Wonky how? The force pushed v2020.09 tag with https://github.com/koreader/koreader/pull/6665 has just finished building. :-P

**Review by poire-z — APPROVED** [review]
No need to send an event for the last one of the ramp ?

**Review by Frenzie — APPROVED** [review]

**Comment by NiLuJe** [comment]
@Frenzie: It basically either failed to refresh, or refresh a bunch of times on top of each other, which basically made the footer (and only the footer) unreadable until the next refresh.

@poire-z: Nope, it's a toggle, so we basically only want to know about the final state (i.e., on/off).

**Comment by Frenzie** [comment]
@NiLuJe Sounds harmless enough. ;-)

**Pull request merged**
