### PR TITLE
[Kindle] Hide the status bar on current FW, too.

### PR DESCRIPTION
**Pull request by NiLuJe**
That was probably not a great idea, since we live inside a stock-UI controlled window? I dunno, I don't use KPVBooklet ;p.

Also comment on an unsuccessful experiment re: https://www.mobileread.com/forums/showthread.php?t=328015

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/5943)

### CODE REVIEW

**Comment by NiLuJe** [comment]
That said, if we're all amenable to shipping a pre-compiled 34KB binary (it depends on X11, would be slightly hellish to build), I can fix it "properly" by telling the WM to basically make the status bar go sit in a corner.

**Comment by NiLuJe** [comment]
Hmm, it's (wmctrl) not perfect either, it makes the WM timeout when it attempts to refresh... Which happens on exit, or on suspend/resume on SO devices :/.

**Comment by yparitcher** [comment]
> That said, if we're all amenable to shipping a pre-compiled 34KB binary (it depends on X11, would be slightly hellish to build), I can fix it "properly" by telling the WM to basically make the status bar go sit in a corner.

Would this fix the clock bleeding issue on later firmware >= 5.11?
if so could i just build it against the x11 libs on my device?

**Comment by Frenzie** [comment]
> would be slightly hellish to build

PS Obviously maintainability is a much larger concern than 30 kB more or less. ^_^

**Comment by NiLuJe** [comment]
@yparitcher: When does it happen, exactly? (And I assume your *not* using a Special Offers device?).

(I've got a binary, that's not the issue, but thanks ;)).

@Frenzie: It's unlikely to ever be updated again, anyway ^^.

**Comment by yparitcher** [comment]
> @yparitcher: When does it happen, exactly? (And I assume your _not_ using a Special Offers device?).

mostly once in a while when changing/refreshing pages, the clock or wifi icon from kindle bleed into koreader as reported in #5022 and others. (the device is technically SO, but never connected to amazon so it does not know it, so it runs like a regular device.)

> (I've got a binary, that's not the issue, but thanks ;)).

thanks, I just managed to build it, after finding the right libs and headers from my kindle.

the "wmctrl -r L:C_N:titleBar_ID:system -b toggle,hidden" command works on 5.11
in a few days i can let you know if it stops the clocks bleeding

**Comment by NiLuJe** [comment]
@yparitcher: Does it get detected as such by KOReader (i.e., do you get the stock screensavers, or ours?).

Just for kicks, because twobob's binary is a wee bit old, I'm currently running a BR build of it, because I'm lazy, and it supports crosstool-ng toolchains ;p.

**Comment by yparitcher** [comment]
> @yparitcher: Does it get detected as such by KOReader (i.e., do you get the stock screensavers, or ours?).

the SS hack works fine, i can also get koreader SS. I happen to have them set to "do nothing" and running my own screensavers with https://github.com/yparitcher/kindle-zmanim

> Just for kicks, because twobob's binary is a wee bit old, I'm currently running a BR build of it, because I'm lazy, and it supports crosstool-ng toolchains ;p.

i downloaded wmctrl from http://tripie.sweb.cz/utils/wmctrl/ and built it against the X libraries from my kindle, with headers from the kindle sources and old ubuntu packages.

**Comment by yparitcher** [comment]
If you dont want to maintain a build, Maybe add a check in the startup script, if the user has wmctrl in the PATH then run it, and leave it up to the user to get it.

**Comment by NiLuJe** [comment]
It's 30KB, I'm just going to ship a K5 binary everywhere ;).

**Comment by yparitcher** [comment]
mine is 26KB after stripping ;)

**Comment by NiLuJe** [comment]
Indeed it is, twobob's binary probably wasn't stripped ;).

**Comment by NiLuJe** [comment]
I'd simplify all the mess and just use wmctrl everywhere, but I'm too lazy to check how it behaves on older FWs :D.

**Comment by NiLuJe** [comment]
Note that as I said last night, I went with a hard resize instead of the minimize, because otherwise it was tripping a timeout when ligl couldn't find the titlebar, which was triggering an unsightly stalls and extra flash on suspend/resume (at least).

**Comment by yparitcher** [comment]
Your branch works on my KT4 5.11.

resizing instead of hiding the status bar has the side effect of the stock UI shifting up while koreader loads :)

**Comment by NiLuJe** [comment]
Yep. I don't actually remember how it behaved back when the pillow command worked ;).

I suppose it did the same thing, because the winmgr visibility event (which I cannot manage to fire manually outside of winmgr) appears to be doing that? Eh.

At least it makes the refresh very visible, which should take care of the "oh, no, I left wifi on" concern ;).

**Comment by hius07** [comment]
PW2, nightly v2020.03.2-9
Upon exit from KOReader status bar always displays correct state of Aeroplane mode.
Perfectly, thanks a lot.

**Comment by yparitcher** [comment]
just want to say that this doe fix the stock clock from showing.

a month later and i have not seen the clock once.
Thanks :+1:

**Pull request merged**
