### PR TITLE
Revert "TouchMenu: menu search (#9884, #9876)"

### PR DESCRIPTION
**Pull request by Frenzie**
This reverts commit e026598f728196cd2747d255e0cdc6194d0340ce.

This reverts commit e58a12ba049cf575b3c87cce7105a4b9e20b4c7b.

@poire-z If we do this we have to be fairly quick about it because a couple of translations have already been done. I'll sleep on it for a night (or at least wait another hour).

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9886)

### CODE REVIEW

**Comment by NiLuJe** [comment]
I haven't looked at the actual implementation, but if the main issue is the dupes, that *should* be fairly easy to deal with: keep a hash of matches (indexed by ref or leaf text, depending on whether the refs are already unique or not), and check against it first (e.g., fake a set data type).

**Comment by Frenzie** [comment]
Afaik they're not duplicates, just indistinguishable. :-)

**Comment by melyux** [comment]
Maybe a minimal breadcrumb trail. Problem is all those gesture options that are the same, right? Rest seems fine

**Comment by Frenzie** [comment]
There are other issues (the biggest of which being we'd have to maintain it): https://github.com/koreader/koreader/pull/9876#issuecomment-1340035055

**Comment by poire-z** [comment]
Still working on it.
For the duplicates, I think I can avoid all of them by just adding `ignored_by_menu_search = true` in readerfont, dispatcher and gestures.koplugin.
There were many other issues (refreshes competition and glitches on eInk, wrong page sometimes, no up navigation possible when no animation, subitems before parent items in the list), that I tried to fix on the existing code - but it was hard to grasp and adapt, so I had rewritten the animation code.
The hardest part is to get it smooth on eInk... It's challenging and fun, but this "feature" was surely not worth the time @zwim and I have put into this...

**Comment by Frenzie** [comment]
I'll close this one then. It's easily replicated or reopened if desired.

**Pull request closed without merging**
