### PR TITLE
Disable the legacy ReaderRotation module

### PR DESCRIPTION
**Pull request by NiLuJe**
AFAICT, this has never worked since the KPV -> KOReader refactor, as it relies on a weird little DrawContext "feature", while the actually in-use rotation framework is handled via BlitBuffer.

That kludge pollutes *a lot* of both the backend and frontend code, so I plan to annihilate that in a followup PR.

See #12303 for more context

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12309)

### CODE REVIEW

**Comment by Frenzie** [comment]
> That kludge pollutes a lot of both the backend and frontend code, so I plan to annihilate that in a followup PR.

Is there much point to this PR then? Or do you mean sometime in the next decade or so. xD

**Comment by NiLuJe** [comment]
Yes, the full annihilation will require touching a lot of crap in base, so it'll take some time, and this actually fixes the fact that J/K currently *do* break rendering, so that's a "fix" ^^.

**Comment by Frenzie** [comment]
Even so it seems you could just remove those lines and that file? Ah well, whatever you prefer.

**Review by Frenzie — APPROVED** [review]

**Comment by NiLuJe** [comment]
Yeah, that'll come with the full excision of the "feature" ;).

**Comment by mergen3107** [comment]
Sorry guys, what's J/K?

**Comment by Frenzie** [comment]
The keys on the keyboard.

**Comment by NiLuJe** [comment]
With the hilarity coming from [colloquial English](https://www.urbandictionary.com/define.php?term=JK) ;).

**Pull request merged**
