### PR TITLE
Fdroid changes

### PR DESCRIPTION
**Pull request by pazos**
Change app id: `org.koreader.launcher.fdroid`.
Change icon color to blue. This affects only the launcher icon and it is useful to differenciate between flavors if both of them are installed.

Add metadata directly in this repo, so it can be parsed automatically by fdroid on each new release.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7856)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Should this be merged before or after .06?

**Review by Frenzie — CHANGES_REQUESTED** [review]
Hold on, I just noticed the screenshot's outdated (icons).

**Comment by pazos** [comment]
> Should this be merged before or after .06?

Before, please.

> Hold on, I just noticed the screenshot's outdated (icons).

Good point!. Will fix it tonight!. What's the book in the screenshots?

**Review by Frenzie — APPROVED** [review]

**Comment by poire-z** [comment]
No nightly builds for most platforms (except two) since this was merged. I have no idea if it's related to this PR (the metadata submodule removal ? I had to manually remove my emulator koreader/metadata/ so git pull could work when I updated to master some days ago) or not - gitlab logs just mention `ERROR: Job failed: exit code 137` - so just mentionning it :/

**Comment by Frenzie** [comment]
Almost certainly not related. That's effectively an OOM from Docker afaict. That is, the container exceeds whatever it's supposed not to exceed.

Not that this makes a lick of sense for the after_script action, let alone one that's been running fine for months…

https://gitlab.com/koreader/nightly-builds/-/blob/804a1750adf4b03307c085058cdbddee445112b0/.gitlab-ci.yml#L5-9

**Pull request merged**
