### PR TITLE
News downloader: wifi off prompt after download

### PR DESCRIPTION
**Pull request by mwoz123**
Prompt to turn off wifi after download.
Extracted from #3388

### CODE REVIEW

**Comment by mwoz123** [comment]
Can I trigger rebuild (without doning blank commit)?

**Comment by Frenzie** [comment]
There's no need to rush this into a PR if there is no working code imo. We still have a couple of days of design process to go through.

My initial proposal is pretty simple:

* A function named, e.g., `afterWifiAction`.
* That function then handles what happens. Default: nothing.
* Network menu: setting for prompt, timeout, whatever. We could start by only making prompt an option but we'll have to create a forward-thinking setting. Pinging @poire-z about that timeout stuff.

Writing this is not something you have to do, but you did kind of volunteer by opening this PR. :-P

With a proposal written down, I'll ping a few other people (e.g., @KenMaltby,  @gerroon, @bahusoid) to ask what they think of it.

**Comment by Frenzie** [comment]
> Can I trigger rebuild (without doning blank commit)?

It will fail until you do a `git pull -r upstream master` followed by a `git push -f`. These are destructive actions, but a temporary placeholder commit like this is the perfect time to familiarize yourself with it.

See the docs for that upstream master thing: http://koreader.rocks/doc/topics/Collaborating.html

**Comment by KenMaltby** [comment]
For those of us still paranoid about power consumption, the idea of having a way to be reminded that you are done with a function that used the WiFi and can insure it is turned off when it's not needed, is a great idea.  Would there be an issue if the plug-in is checking periodically for news to download, doesn't it then turn itself on and off?

**Comment by mwoz123** [comment]
> (..) the idea of having a way to be reminded that you are done with a function that used the WiFi and can insure it is turned off when it's not needed, is a great idea

Agree. That's exactly what this commit is about: Popup asking if wifi should be turn off when downloading news is finished.

>Would there be an issue if the plug-in is checking periodically for news to download, doesn't it then turn itself, and WiFi on and off?

This should be a new, separate topic. It would require a lot more changes - new configuration to turn auto-downloading on/off. It could check wifi state before downloading and leave it in the same as before download (if was off, turn it on & leave it off after download), auto wifi enabling, etc. 
The major problem I see here is the notification user that new news are available. 

But if really needed/requested the discussion should be continued in a separate thread.

**Comment by mwoz123** [comment]
How about latest comit? 

Ask to turn off wifi only if it was off before downloading news.

**Comment by Frenzie** [comment]
It's an interesting idea for one of the settings, but like I said in https://github.com/koreader/koreader/pull/3388#discussion_r146109006 I mean a `NetworkMgr:afterWifiAction()`.

I would structure it the same as the `Save document` menu.

Network → After Wi-Fi action

* `Do nothing` (the default)
* `Prompt when previously off` (interesting idea)
* `Always prompt`
* (`Timeout`) (potential future enhancement)

**Comment by mwoz123** [comment]
I think `prompt when previously off ` provides the best U. X. 
Why it cannot be default ? 
What other guys think? @KenMaltby? 

@Frenzie I might implement your proposal in next PR if I had time. 
Let's merge this for now.

**Comment by KenMaltby** [comment]
I guess "do nothing" would mean leave on?  Why not just return it to what ever state it was in prior to the action that required WiFi?  If WiFi was already on (no turn on prompt was required), then leave it on.  If it was off (and a turn on Wifi prompt was used) then turn the Wifi back off.

**Comment by mwoz123** [comment]
What you described is nearly the same what we've after that merge ;) 

The only difference is that if it was off before action it prompt user to disable wifi instead of silent turn off.

I thought about that and think that silent turn off might be sometime a surprise, when  user planned to use internet afterwards. That's why I think that prompt off is better.

**Comment by mwoz123** [comment]
Anyway silent off is also on for me. If you guys think it's better than prompt I'd be able to change it quickly

**Comment by KenMaltby** [comment]
If the user was having his WiFi on all the time it would have been on to start and would remain on.  My guess would be if a user was using the Wifi a lot, they would eventually learn to turn it on thru the Network option and it would never give them the prompt when going to different WiFi features.

**Comment by poire-z** [comment]
Answering https://github.com/koreader/koreader/pull/3482#discussion_r161610262 here, as this topic is the most complete with idea and proposals.

To me, I would replace all these (@robert00s did the work of making them all consistent this way):
```lua
            if NetworkMgr:isOnline() then
                self:lookupInput() -- do some wikiepdia queries
            else
                NetworkMgr:promptWifiOn()
            end
```
with something like
```lua
if NetworkMgr:beforeWifiAction(needs_internet) then
    self:lookupInput()
    NetworkMgr:afterWifiAction()
end
```
We could find better names, but these give the idea.

```lua
function NetworkMgr:beforeWifiAction(needs_internet)
  if isWifiEnabled() then -- quickly check if wifi is enabled (cat /proc/modules)
    if needs_internet == true and isOnline() then
        _startOrResetAutoWifiOffTimer()
        return true
    end
    if needs_internet == false and isConnected() then
        _startOrResetAutoWifiOffTimer()
        return true
    end
    disableWifi() -- current connexion is not valid
  end
  needs_wifi_action = G_reader_settings.readSetting("needs_wifi_action")
  if needs_wifi_action == "prompt" then
    NetworkMgr:promptWifiOn()
  elseif needs_wifi_action == "script" then
    -- execute a script (that could use a homemade wpa_supplicant.conf to connect to known network without prompting)
  else ...
  end
  -- do the same stuff we did at start
  return false -- if we still fail them
end
```
and what you suggested above for:
```lua
function NetworkMgr:afterWifiAction(needs_internet)
  done_with_wifi_action= G_reader_settings.readSetting("done_with_wifi_action")
  if done_with_wifi_action== "go_off" then
    disableWifi()
  elseif done_with_wifi_action== "prompt" then
  elseif done_with_wifi_action== "previous_state" then
  elseif done_with_wifi_action== "timer" then
    _startOrResetAutoWifiOffTimer()
  end
end
```

I have done my own private hacking (https://github.com/koreader/koreader/pull/3388#discussion_r146109940), kobo specific, using script/timer (inspired by the old autoSuspend code for kobo that was formerly in UIManager). Sharing it in case it can give some ideas. It comes down to this added to UIManager:
```lua
-- we don't want to suspend if wifi modules are inserted, otherwise crash
function UIManager:isWifiEnabled()
    local wifi = false
    local fd =  io.open("/proc/modules", "r")
    if fd then
        local modules = fd:read("*all")
        fd:close()
        -- lsmod is usually empty, unless wifi or usb enabled
        --     dhd 240713 0 - Live 0x7f19c000   (= directory /proc/sys/net/ipv4/conf/eth0 present)
        --     sdio_wifi_pwr 486 0 - Live 0x7f198000
        -- we could alternatively check if lfs.attributes("/proc/sys/net/ipv4/conf/eth0", "mode") == "directory"
        if modules:len() > 0 then
            if modules:find("dhd ") or modules:find("sdio_wifi_pwr ") then
                wifi = true
            end
        end
    end
    return wifi
end

-- enable our personal wifi without the need for NetworkMaanger widgets
function UIManager:quickEnableWifi(noautowifioff)
    if self.auto_wifi_off_sec == nil then
        -- On first call, load this setting and create the functions
        local sec = G_reader_settings:readSetting("auto_wifi_off_seconds")
        if sec > 0 then
            self.auto_wifi_off_sec = sec
            self.wifi_off_action = function()
                -- For safety, cancel scheduled stuff
                self:unschedule(self.wifi_off_action)
                self:quickDisableWifi(false) -- no Infomessage
            end
            function UIManager:_startOrResetAutoWifiOffTimer()
                -- do simple, just unschedule/scheduleIn
                self:unschedule(self.wifi_off_action)
                self:scheduleIn(self.auto_wifi_off_sec, self.wifi_off_action)
            end
            function UIManager:_stopAutoWifiOffTimer()
                self:unschedule(self.wifi_off_action)
            end
        else
            self.auto_wifi_off_sec = 0   -- default = 0 => not enabled
            self._startOrResetAutoWifiOffTimer = noop
            self._stopAutoWifiOffTimer = noop
        end
    end
    local connected = true
    if not self:isWifiEnabled() then
        local InfoMessage = require("ui/widget/infomessage")
        local info = InfoMessage:new{
            text = "Connecting to friendly WIFI...",
        }
        local sleep_and_discard_sec
        self:show(info)
        self:forceRePaint()
        ret = os.execute("../my_enable-wifi.sh")
        self:close(info)
        if ret == 0 then
            local ssid = "???" -- shouldn't happen
            local fd =  io.open("/tmp/mykossid", "r") -- i put my connected SSID here
            if fd then
                ssid = fd:read("*all")
                fd:close()
            end
            self.connected_ssid = ssid
            info = InfoMessage:new{
                text = "Connected to "..ssid,
            }
            -- block for display and cleanup (avoid InfoMessage being masked
            -- by a quickdictlookup for example)
            sleep_and_discard_sec = 1
        else
            self.connected_ssid = nil
            info = InfoMessage:new{
                text = "No friendly WIFI available",
                timeout=4,
            }
            -- disable wifi, so we don't have to do it manually if we want to re-enable it
            UIManager:scheduleIn(0.1, function() self:quickDisableWifi(false) end)
            connected = false
        end
        self:broadcastEvent(Event:new("UpdateFooter"))
        self:show(info)
        self:forceRePaint()
        if sleep_and_discard_sec then
            util.sleep(sleep_and_discard_sec)
            self:close(info)
            self:forceRePaint()
        end
    end
    if connected then
        if noautowifioff then
            self:_stopAutoWifiOffTimer()
        else
            self:_startOrResetAutoWifiOffTimer()
        end
    end
    return connected
end

-- Disable wifi if it was enabled
function UIManager:quickDisableWifi(showmsg)
    -- We can touch this file to keep wifi on and allow restarting koreader
    if lfs.attributes("/tmp/keep_wifi_on", "mode") == "file" then
        return
    end
    if self:isWifiEnabled() then
        local InfoMessage = require("ui/widget/infomessage")
        local info = nil
        if showmsg then
            info = InfoMessage:new{
                text = "Shutting down WIFI...",
            }
            self:show(info)
            self:forceRePaint()
        end
        local network_manager = require("ui/network/manager")
        network_manager:releaseIP()
        network_manager:turnOffWifi()
        self.connected_ssid = nil
        UIManager:broadcastEvent(Event:new("UpdateFooter"))
        if info then
            self:close(info)
            self:forceRePaint()
        end
    end
    if self._stopAutoWifiOffTimer then -- may not yet be defined
        self:_stopAutoWifiOffTimer()
    end
end
```
I had replaced all the isOnline()/promptWifiOn() with:
```lua
    local UIManager = require("ui/uimanager")
    if not UIManager:quickEnableWifi() then
        return -- abort wikipedia lookup if not connected
    end
```
(I personally don't care about isOnline() or isConnected(), my isEnabled() is enough for the action to go on and fail in its own way of failing if no network or no internet).
I also added at various place (suspend, koreader exit):
```lua
        -- my own check for turning off wifi
        UIManager:quickDisableWifi(true)
        logger.dbg("Suspending...")
```

**Comment by Frenzie** [comment]
```lua
if NetworkMgr:beforeWifiAction(needs_internet) then
    self:lookupInput()
    NetworkMgr:afterWifiAction()
end
```

I like that a lot, although I doubt we can keep the `afterWifi`(Action) positioning that neat. Perhaps especially in this particular example. In Wikipedia you can easily look around in a few entries and it wouldn't be very helpful to kill the wifi connection before you close the dialog directly after you've looked up one term.

**Comment by poire-z** [comment]
Yes, it would depend on the `done_with_wifi_action` setting. May be the code could give hint to afterWifiAction about whether it may do some other network stuff soon, so the action could be tweaked (I get NewsDownloaded needs just : go online, fetch rss, go offline)
For wikipedia, it works great with a timer: connect, get page, stays connected for 2mn in case we need to fetch more stuff (images soon), go offline if user is reading/idling too long. If he looks up other thing after that, just reconnect, reset timer, goes offline in 2mn...
It works like this nicely for me for months, but I am just not familiar enough with the other use cases - I'm not even sure how it works for you all (do you really go thru prompt and tap on your access point each time? or just have wifi on all the time? having wifi on eats battery like crazy on my kobo...)

**Comment by Frenzie** [comment]
Like I probably said somewhere around here, I disable that new "turn wifi back on" default which I don't like and I just kill the wifi when I want it with a quick "standby". I thought my battery was starting to show its age when I realized the wifi now automatically turns itself back on after standby. On my phone three years might be starting to have an effect, but that poor thing recharges every few days.

Like I definitely said, I think the timeout idea is great. A default of a few minutes[1] with the option to tweak it.

[1] For the timeout. I'm less sure about making the timeout itself the default.

**Pull request merged**
