### PR TITLE
czmq & libzmq: update to 4.2.1 & 4.3.5 respectively

### PR DESCRIPTION
**Pull request by benoit-pierre**
Tested:
- calibre wireless connection with the emulator and Android ARM / ARM64
- HTTP inspector (patched to use `streammessagequeueserver`) with the emulator

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12350)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by benoit-pierre** [comment]
Regarding this comment:
```lua
    -- Using a simple LuaSocket based TCP server instead of a ZeroMQ based one
    -- seems to solve strange issues with Chrome.
    -- local ServerClass = require("ui/message/streammessagequeueserver")
    local ServerClass = require("ui/message/simpletcpserver")
```
@poire-z: do you remember what the issue with Chrome was?

**Comment by poire-z** [comment]
> do you remember what the issue with Chrome was?

Not really, but I see we discussed some issues in the original PR #11457, search for "Chrome" in it.

**Comment by poire-z** [comment]
Just a note: pulled everything and build (mupdf, crengine, some zmq stuff), and now whenever I kodev run, I see mentions of czmq - is this normal ? (I previously only saw only crengine always).
```
make TARGET= KODEBUG=1 VERBOSE=
â¸  0% | Building 'crengine'
ninja: no work to do.
â¸ 16% | Building 'czmq'
ninja: no work to do.
â¸ 50% | Building 'koreader'
ninja: no work to do.
â¸100% | Installing 'czmq'
[*] install front spec only for the emulator
```

**Comment by benoit-pierre** [comment]
Yes and no: it's the same issue as zlib, a file (`src/platform.h`) is removed during configure, since it's part of the build depfile, this trigger the build step (that does nothing) and the install step (no other projects depend on czmq, so no other unnecessary build steps are triggered) every time. Will patch it similarly.

**Pull request merged**
