### PR TITLE
ScrollableContainer: fix 'argc'

### PR DESCRIPTION
**Pull request by hius07**
The bug reported in https://github.com/koreader/koreader/pull/9659#issuecomment-1286359688 (`argc` eliminated in https://github.com/koreader/koreader/pull/9624).

+minor cleanups discovered while investigating the bug.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9680)

### CODE REVIEW

**Comment by hius07** [comment]
More `argc` leftovers in uimanager_bench.lua and uimanager_spec.lua. May be of @zwim's interest.

**Comment by NiLuJe** [comment]
What happened to poor `RadioButton`? ;o)

**Comment by hius07** [comment]
ChecButton includes both checkmark and radiomark.

**Comment by NiLuJe** [comment]
Didn't `RadioButton` have some fancy text width alignment thingy?

**Comment by hius07** [comment]
> Didn't `RadioButton` have some fancy text width alignment thingy?


Nothing special comparing to the usual checkbutton. CheckMark and RadioMark take care of this.

Besides, the radiomark has vertical alignment https://github.com/koreader/koreader/pull/8083.
RadioButton module is not used anywhere.

**Review by poire-z — APPROVED** [review]

**Review by NiLuJe — APPROVED** [review]

**Pull request merged**
