### PR TITLE
Paste to shortcuts

### LINKED ISSUE #5046: FR: move current article to favourites (general/wallabag/newsdownloader/send2ebook)
* KOReader version: 2019.05
* Device: 

#### Issue

Often reading a article downloaded from internet (via wallbag/news downloader or send2ebook) I wish there were a function to move current reading article from this folder to a "favourites" folder (so I wont' lose it e.g. with "delete all readed" function). 

There could be a setting to choose one folder and mark it as 'favourite', and then a option "move current article to favourites" folder on current reading book .

It mostly usefull for above metioned plugins but could be an koreader menu option (or even separate plugin to move it if you don't agree to have it in main code).

### PR DESCRIPTION
**Pull request by Frenzie**
Adds a new paste action to folder shortcuts.

Fixes #5046.

Screenshot_2019-05-28_15-17-52

### CODE REVIEW

**Comment by poire-z** [comment]
> Although perhaps that's actually intended and only cut should get rid of it to prevent errors?

No real opinion. Looks like Windows allows single copy & multiple pastes. I don't think it matters much on our devices where we can only copy books (or possibly, an image to the screensaver directory).

So, lgtm.

**Comment by Frenzie** [comment]
The problem I noticed was that if you cut & paste, you can then paste again and you'll get an error message.

Do you think it should be "Paste file" instead to make it clear what we're talking about here?

**Comment by poire-z** [comment]
> The problem I noticed was that if you cut & paste, you can then paste again and you'll get an error message.

Yeah, I got that. So you should indeed set it to nil when Paste after Cut. And if you can't detect Cut vs Copy at Paste time, fine to set it to nil in both cases (if you can detect that, well, no real opinion).

> Do you think it should be "Paste file" instead to make it clear what we're talking about here?

Not especially. We don't add "file" to Cut/Copy/Paste/Delete in the file manager, and we're in a files context in this Shorcuts thingy, so I don't mind just seeing "Paste". And it would make the buttons a bit larger. An other option is to just show the large button with "Paste file" here (in a 2 rows buttondialog)  only if you have something in the clipboard (instead of always showing it either enabled or disabled).

**Comment by Frenzie** [comment]
> and we're in a files context in this Shorcuts thingy

The difference with the file manager is that "edit" and "delete" refer to folder shortcuts, not to performing actions with real files or folders.

**Comment by poire-z** [comment]
So go with "Paste file" to kill any ambiguity. Possibly in a 2-rows buttondialog.

**Comment by Frenzie** [comment]
Alright, I'll probably do that tomorrow. :-)

**Pull request merged**
