### PR TITLE
Get rid of the old PB TC

### PR DESCRIPTION
**Pull request by NiLuJe**
c.f. https://github.com/koreader/koreader-base/pull/1048 & https://github.com/koreader/koxtoolchain/pull/22

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/5860)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Sure, I just remembered that I wanted to tweak a few things anyway ;).

**Comment by NiLuJe** [comment]
As mentioned in https://github.com/koreader/virdevenv/pull/49, not bumping base right now (to hopefully only break PB tonight until the new bot is in place). ;).

**Comment by cugumpac52** [comment]
This commit breaks the build on Pocketbook 623.

**Comment by Frenzie** [comment]
Could you please open a new issue with all the pertinent information?

**Pull request merged**
