### PR TITLE
style tweaks - ignore publisher hyphenate

### PR DESCRIPTION
**Pull request by robert00s**
I'm not sure if this is a good place :)

### CODE REVIEW

**Comment by poire-z** [comment]
@cramoisi was having a go at that I guess, we had some talk about it in https://github.com/koreader/crengine/pull/209#issuecomment-401378885

I guess I'd prefer a single `body * { all properties; }` , and the id named "`hyphenate_all_auto`".

**Comment by cramoisi** [comment]
@robert00s the `hyphenate` property doesn't exist but in koreader :) (it's not valid css but keep it anyway). Can you add the `hyphens` property too for future compatibility with the future support of it by crengine ?

@poire-z I was trying to do the reverse (enabling when disabled) and it won't work with body or * if the publisher disable them on p so, i made a thingy to re-enable them on p

**Comment by poire-z** [comment]
So, I guess both your tweaks could go into a `Hyphenation >` just below `Text alignment >`, as you're both more forcing some hyphenation setting than ignoring the publisher one.

But mhh, aren't you both doing _enabling when disabled by publisher_ ? (if there's only one, tweak, we obviously don't need a submenu).

**Comment by cramoisi** [comment]
@poire-z  Yup, it's the same thing.

**Comment by robert00s** [comment]
@poire-z 
Do you mean:
`body * { adobe-hyphenate: auto !important; hyphenate: auto !important; -webkit-hyphens: auto !important; }`
?

**Comment by cramoisi** [comment]
@poire-z I guess I could say I don't want to cut the h1, h2, etc tags. But the fact is I didn't think about using body * :)

**Comment by cramoisi** [comment]
And there is also the fact that using only * didn't work when I tried it.

**Comment by robert00s** [comment]
So maybe:

```
body, p {
    adobe-hyphenate: auto !important;
    hyphenate: auto !important;
    -webkit-hyphens: auto !important;
    hyphens: auto !important;
}
```
?

**Comment by poire-z** [comment]
How would that one work ?
```css
* { hyphenate: inherit !important; }
h1, h2, h3, h4, h5, h6 { hyphenate: none !important; }
```
The root document has `s->hyphenate = css_hyph_auto;` and hyphenate is inherited.
I think we do not need to put all the 4 properties: once one is set with !important, it flags the style so it won't be replaced, no matter what's used from there 4 names in the publisher stylesheet.

**Comment by cramoisi** [comment]
@robert00s 
> body, p 

body p (without the comma)

**Comment by robert00s** [comment]
> \* { hyphenate: inherit !important; }
> h1, h2, h3, h4, h5, h6 { hyphenate: none !important; }

Works :)

**Comment by poire-z** [comment]
Ok :)
Thinking about it, this should work the same and is clearer (`inherit `mplies one knows the root value), and conforms to the `id` you set :)
```
* { hyphenate: auto !important; }
h1, h2, h3, h4, h5, h6 { hyphenate: none !important; }
```
Does that work too ? (then, title should he "Hyphenate all text" - and the description "Allow hyphenation in all text (except headings)" or something.
@cramoisi : any comment? Does that work for you too?

**Comment by cramoisi** [comment]
yup ! (it's too hot, i only remember now it doesn't work when I test because I used the correct css hyphens property which is not supported :) so yup, it's good !

@robert00s could you use this PR to update https://github.com/koreader/koreader/blob/71ff69ec4f6fb5d0fe146af8147d447a0109b8a2/frontend/ui/data/css_tweaks.lua#L100 to sub ? it's better than middle (roughly the same but it's better to have sub to be sub) ?

**Comment by robert00s** [comment]
@poire-z works :)
@cramoisi sorry, but I don't understand :) What should I change exactly?

**Comment by poire-z** [comment]
Can you update the `title` and `description` too?:
```
title = _("Allow hyphenation on all text"),
description = _("Allow hyphenation to happen on all text (except headings), in case the publisher has disabled it."),
```
I think @cramoisi wants you to change the line he mentionned to:
`sub { font-size: 50% !important; vertical-align: sub !important; } `

**Comment by cramoisi** [comment]
@poire-z @robert00s 

> I think @cramoisi wants you to change the line he mentionned to:
sub { font-size: 50% !important; vertical-align: sub !important; }

**Comment by poire-z** [comment]
> I'm not sure if this is a good place :)

Oups, didnt checked that. I moved it a bit down with #4050.

**Pull request merged**
