### PR TITLE
[UX] Add CheckMark and use in TouchMenu checkable indicator

### PR DESCRIPTION
**Pull request by Frenzie**
Cherry-picked out of #3088.

# Before
screenshot_2017-08-15_20-06-45

# After
screenshot_2017-08-15_09-27-17

### CODE REVIEW

**Comment by KenMaltby** [comment]
I hope the others can be updated to this approach as well.  There are a number in the reader menus.

**Comment by Frenzie** [comment]
This automatically takes care of all checkable items. :-)

**Comment by Hzj-jie** [comment]
I think this change is ready to merge. (Though I am not a fan of the rectangle, it makes me remember the "unprintable characters in Chinese" back in 1990s. https://www.codeproject.com/KB/string/FontGlyphSet/FontGlyphSet1.png)
Any concern?

**Comment by Frenzie** [comment]
Just looks like a box to me. *shrugs* The specifics would be simple enough to change but I did pick something I was satisfied with. ;-)

screenshot_2017-08-17_19-16-16

**Comment by poire-z** [comment]
Other possible candidates from https://www.compart.com/en/unicode/block/U+25A0 that looks available in NotoSans:
white square with rounder corners ▢ ▣ (not much rounded in NotoSans, but may help not being considered a replacement char)
White Diamond ◇ ◈
Fisheye ◉ (but other circles don't have the same diameter...)

**Comment by Frenzie** [comment]
> ▢ ▣

Drat, I missed those. I suppose a separate CheckMark widget might still be good to reuse the thing but that would've saved me the effort. :-P

# All checked
screenshot_2017-08-17_20-36-52

# Overlapped is a bit odd but I didn't bother to change the code
screenshot_2017-08-17_20-33-07

# The checkmark actually works quite well with this box
screenshot_2017-08-17_20-34-34

# But square root not so much
screenshot_2017-08-17_20-34-49

**Comment by Frenzie** [comment]
I'm happy with the square with rounded corners, particularly `▢` together with `✓` but there's nothing wrong with `▣` either.

Some of the other look nice but I'm less sure about their suitability for this particular job. For the sake of completeness I'll attach these screenshots though.

# Dotted circle and fisheye (meh)
screenshot_2017-08-17_20-41-03

# Diamonds (looks nice but a bit non-standard)
screenshot_2017-08-17_20-40-13

# Large circle and fisheye (looks great, maybe we also need some kind of radiobox? :-P)
screenshot_2017-08-17_20-41-33

**Comment by poire-z** [comment]
I like the "The checkmark actually works quite well with this box" one too.

**Comment by KenMaltby** [comment]
They all look nice and convey the situation correctly.  I do think that a checkmark or an X in a box would be the most easily recognized, for those used to filling out forms or taking tests.

**Comment by Frenzie** [comment]
I hadn't even thought to try. Here's the ballot box and the rounded square with a regular `x` superimposed. There are probably better ways to achieve that particular look.

screenshot_2017-08-17_23-03-54
screenshot_2017-08-17_23-04-52

**Comment by poire-z** [comment]
Looking nice on kobo.
I think we can get the checkmark even more centered if we use NARROW NO-BREAK SPACE (http://www.fileformat.info/info/unicode/char/202f/index.htm , 0xE2 0x80 0xAF in utf8) instead of the standard leading space in https://github.com/koreader/koreader/blob/master/frontend/ui/widget/checkmark.lua#L32

**Comment by Frenzie** [comment]
True, or just a regular thin space. But which look is off-center is debatable. When you center it more (shown here with thin space) the weight of the entire box shifts to the left, which I was less fond of when I tried it previously. I also quite like the boundary-breaking behavior of the square root on the smaller box, even if I'm much less fond of the smaller box and the square root individually.

(You could probably also center it perfectly by adding a few more widgets into the mix, but I thought the results were already quite satisfactory without introducing more complexity. Of course one could also do some trickery with font size.)

# Thin space
screenshot_2017-08-19_11-57-57

# Regular space (current)
screenshot_2017-08-19_12-04-04

**Pull request merged**
