### PR TITLE
clean ReaderDictionary:cleanSelection

### PR DESCRIPTION
**Pull request by poire-z**
crengine now does a much better job at finding word boundaries, so there's no more need for much cleanup.

I let in commented some code to remove some diacritical marks, see discussion in #1649 . But as i have no way to check if that works (no diacritical marks in the languages, texts and dictionaries i understand/read/have), I let people who can try that and tell us.

### CODE REVIEW

**Comment by poire-z** [comment]
Well, I forgot that crengine is not the only rendering engine from which we get selected stuff...
Looks like some of the cleaning may still be useful with pdf (french qu'il , l'a, punctuation at end of selected word... - but quotations marks around quotes seem left out fine)
So better not merge yet.
What do you think ? Let the whole thing in ? Or try to check what's really needed ?

**Comment by Frenzie** [comment]
It would be neat if you could come up with a few unit tests to protect against regressions in this area.

https://github.com/koreader/koreader/blob/e5bcdee85e78424b844386d2fcf4d719ee8762c9/spec/unit/readerdictionary_spec.lua

Then it'd also need to check some of the other test document formats (most notably PDF and DjVu). A good unit test would also automatically answer the question for us. ;-)

**Comment by poire-z** [comment]
> A good unit test would also automatically answer the question for us. ;-)

Well, I'd like that answer, but I don't see how unit tests would give it :)
For unit tests, we need to know the input we may get, and what we want out.
If the engine evolves, and feeds some different selection, and you want different stuff out, and you change the cleanSelection, you need to change the unit tests...
(Like before my crengine fix, it would give `qu'autrefois`, so i needed to remove `qu'` - now it gives only `autrefois` - if we now get `qu'autrefois`, it's that the user choose to select both words, so we shouldn't do the cleaning - so unit tests do not answer :)

**Comment by Frenzie** [comment]
Good point, but that basically just means I pointed to the wrong location for testing: https://github.com/koreader/koreader/blob/e5bcdee85e78424b844386d2fcf4d719ee8762c9/spec/unit/readerhighlight_spec.lua

After all, you don't want to accidentally break the hard work from #2413 or one of the other brilliant fixes. :-)

**Comment by poire-z** [comment]
(No I don't want that :) , thanks).
But, not (yet) thinking about unit tests, doing the right (and brilliant) thing in this cleanSelection() depends on a combination of many things:
- the engine (how many do we have ? crengine, djvu, 2 for pdf ? text-based pdf, bitmaped/kopt'ed + ocr engine) and the quality of the highlighted stuff they give back
- the text quality and typography (quotes, right quotes, quotations marks, space between quotation mark and word or not)...
- the language (like space between word and quotation mark in french, not in english, valuable quotes (aujourd'hui) vs unvaluable ones (qu'autrefois))
- the dictionary engine and the various dictionaries themselves, and how they cope with bad input.

The current code seems to be a no-op for crengine now, and may be useful with the few text based pdf I tested with.
I don't have any djvu, and selection on my scanned pdf only gives a full line.
So, as I haven't seen any issue lately about text selection (except for crengine, that is now better), we may let the whole code as is ? I'll just update the comments, and let the commented stuff about diacritical marks.

**Comment by Frenzie** [comment]
I haven't noticed any issues myself, but I don't use highlight very actively.

But yeah, ignore anything i said about dictionary unit tests. On closer reflection I mean selection/highlight ones, unrelated to this PR really.

**Comment by houqp** [comment]
> So, as I haven't seen any issue lately about text selection (except for crengine, that is now better), we may let the whole code as is ? I'll just update the comments, and let the commented stuff about diacritical marks.

:+1: let's do this. if we are not sure whether it's really needed, then it's probably safe to remove. i prefer to add it back when we got reports from the users. then we can better document the reason.

**Comment by poire-z** [comment]
I'm a bit confused about your comment :| what is thumb-up'ed ? and what do you suggest to remove ? (the existing gsubs that I thought first i could remove, but that may be needed for pdf ? or the commented diacritical stuff that was requested in an other issue ?)

**Comment by houqp** [comment]
I meant I support removing the existing gsubs and keep the commented diacritical stuff that was requested in an other issue. I am a fan of deleting code so there is less thing to maintain ;)

But if any bug report come up because of this change, we need to make sure those use-cases are captured in a unit test to prevent regression in the future.

**Comment by poire-z** [comment]
OK, so I removed some and kept some, and I checked on a few pdf and the sample djvu that it gives me good results.
I added the stripping of the english possessive `'s`, which is quite similiar to what I did for french constructs.

**Comment by houqp** [comment]
Thanks!

**Pull request merged**
