### PR TITLE
QuickMenu: anchor to gesture position

### PR DESCRIPTION
**Pull request by yparitcher**
Fixes: #10631

Lightly tested

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10636)

### CODE REVIEW

**Comment by poire-z** [comment]
Simple :) I'm fine with the code, but not using QuickMenu, I don't have any opinion on the behaviour with the different type of gesture. Is it always convenient?
Pinging @jonnyl2 if he wants to test it.

**Comment by jonnyl2** [comment]
Tested and it works well, thank you. Very convenient for short gestures. However, is it possible to make the position dependent on the end point of the gesture, rather than the starting point? For longer gestures across the whole screen, the QuickMenu otherwise appears on the opposite end of the screen after completing the gesture.

**Comment by NiLuJe** [comment]
Technically, yes, although GestureDetector doesn't currently forward that information (and *every* gesture would have to be handled, and the data may not always make sense for all of them?).

As an example, here's how the swipe data is exported:

https://github.com/koreader/koreader/blob/dee1c902ec25cfea19c44836816b40261c408404/frontend/device/gesturedetector.lua#L894-L902

(See earlier for how start_pos is computed, and how to get at the end contact instead via `self.current_tev`).

**Comment by jonnyl2** [comment]
Thanks @NiLuJe. If someone would like to write the code I'm happy to test it, otherwise it also works fine with the current changes (most gestures are usually performed on a small area on the screen anyway).

**Comment by yparitcher** [comment]
I don't use quickmenu so this is done on my end, not going to rework gesturedetector to find the gesture end, just this as it was quick and easy.

**Review by Frenzie — APPROVED** [review]

**Comment by NiLuJe** [comment]
> I don't use quickmenu

Ditto ;).

Fairly low hanging branch for interested parties, though ;).

**Comment by hius07** [comment]
Doesn't work with Profiles.
I will fix it (and maybe will make it optional, I used to the centered QMs).

The design question regarding the width, which one is better?

Current width factor 0.8



Width factor 0.7 (the last long item is shrinked)



Adaptive width based on the buttons width (a long item is in the list)



No long items in the list

**Comment by Frenzie** [comment]
Probably adaptive provided it doesn't adapt out of bounds?

**Comment by hius07** [comment]
And truncated if longer

**Comment by poire-z** [comment]
No strong opinion. May be Adaptative with a min width of 0.5 or 0.6 or 0.7.

**Pull request merged**
