### PR TITLE
CloudStorage (FTP): Do not buffer entire download in memory

### LINKED ISSUE #6390: KOReader crash while downloading large files in kobo clara hd
* KOReader version: v2020.06
* Device: kobo clara hd

#### Issue
I'm downloading some books through ftp function in koreader. Some books are small, some are large, approximately 100 ~ 200 MB. Small files are fine, but when I tried to download the large file. The koreader will crash every time. I dumped the crash.log. It seem there's not enough memory. However, I think it's better to display some error message about low memory than just crash.

#### Steps to reproduce
1. Open the cloud storage functionality in the menu and connect to some ftp server
2. Download large file from the ftp server
3. KOReader crash after several seconds of stuck

##### `crash.log` (if applicable)
udhcpc (v1.22.0.kobo) started
Sending discover...
Sending discover...
Sending select for 192.168.50.188...
Lease of 192.168.50.188 obtained, lease time 86400
adding dns 192.168.50.1
PING 192.168.50.1 (192.168.50.1): 56 data bytes
64 bytes from 192.168.50.1: seq=0 ttl=64 time=3.046 ms

--- 192.168.50.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 3.046/3.046/3.046 ms
PING 192.168.50.1 (192.168.50.1): 56 data bytes
64 bytes from 192.168.50.1: seq=0 ttl=64 time=6.213 ms

--- 192.168.50.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 6.213/6.213/6.213 ms
PING 192.168.50.1 (192.168.50.1): 56 data bytes
64 bytes from 192.168.50.1: seq=0 ttl=64 time=24.635 ms

--- 192.168.50.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 24.635/24.635/24.635 ms
PING 192.168.50.1 (192.168.50.1): 56 data bytes
64 bytes from 192.168.50.1: seq=0 ttl=64 time=1.678 ms

--- 192.168.50.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 1.678/1.678/1.678 ms
PING 192.168.50.1 (192.168.50.1): 56 data bytes
64 bytes from 192.168.50.1: seq=0 ttl=64 time=6.440 ms

--- 192.168.50.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 6.440/6.440/6.440 ms
./luajit: not enough memory
!!!!
Uh oh, something went awry... (Crash n°1: 06/21/20 @ 00:24:15)
Running FW 4.21.15015 on Linux 4.1.15-00089-ga2737fc02713 (#34 SMP PREEMPT Fri Dec 27 17:47:13 CST 2019)
Attempting to restart KOReader . . .
!!!!

### PR DESCRIPTION
**Pull request by null-dev**
Fixes #6390

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7597)

### CODE REVIEW

**Comment by NiLuJe** [comment]
FWIW, pretty much every other user of the file sink uses the idiomatic `ltn12.sink.file(io.open(path, "w"))` syntax, so I'm not entirely convinced the extra care around file creation is entirely warranted here, but that's admittedly not directly related to this PR, since that was here before ;).

**Review by NiLuJe — APPROVED** [review]
:lgtm:, thanks!

**Comment by null-dev** [comment]
> FWIW, pretty much every other user of the file sink uses the idiomatic `ltn12.sink.file(io.open(path, "w"))` syntax, so I'm not entirely convinced the extra care around file creation is completely warranted here, but that's admittedly not directly related to this PR, since that was here before ;).

I think it was put in afterwards to fix this: https://github.com/koreader/koreader/issues/6636

**Comment by NiLuJe** [comment]
> > FWIW, pretty much every other user of the file sink uses the idiomatic `ltn12.sink.file(io.open(path, "w"))` syntax, so I'm not entirely convinced the extra care around file creation is completely warranted here, but that's admittedly not directly related to this PR, since that was here before ;).
> 
> I think the check wasn't there originally but was put in afterwards to fix this: #6636

I was afraid it was going to be because of some Android bullshit when I mentioned it, yeah ;). Thanks for double-checking!

**Pull request merged**
