### PR TITLE
Improve several outputs

### PR DESCRIPTION
**Pull request by Hzj-jie**

### CODE REVIEW

**Comment by retrue** [comment]
I am a simple user, not a developer and this is just my opinion, but I don't like this commit.
"Sort by date of modification" sounds a lot better than "Sort by date modified".
"Sort by date of last read" and "Sort by date of adding" don't sound too well, but "Sort by date added" and "Sort by date modified" don't sound well either. I don't know what expressions are used in Windows or Linux because my system is not in English.
And I don't like either the change in Storage statistics.
 /mnt/onboard gives more information and is more precise than "Internal storage", but "Internal storage" is more user-friendly and easier to understand for common users.
Of course, "Available" and "Used" (and "Interal storage" if it returns) should be translatable.
Just my humble opinion.

**Comment by Frenzie** [comment]
These are the standard conventions across all operating systems. Not being a developer is a good thing; not being an English speaker less so. ;-)

**Comment by retrue** [comment]
I don't speak English (my pronounciation is terrible) but I can write it and read it quite well.
What about /mnt/onboard versus "Internal storage"?

**Comment by Frenzie** [comment]
I'd suggest a compromise, something like `Internal storage (/mnt/whatever)`. But the whole thing would need to be better integrated into Lua for proper translation and stuff first.

**Comment by houqp** [comment]
If we really want to go with the user friendly design, I think a better one would be:

* if path == `/mnt/onboard` then `Internal storage`
* if path == `SD PATH` then `External storage`
* ohterwise `Storage (PATH)`

And each platform needs to implement the path comparison logic since paths are different.

**Comment by Frenzie** [comment]
I'm not entirely sure hiding the path completely is user-friendly though.
Only that giving the path just like that is less friendly than it could be.

**Comment by houqp** [comment]
I am coming from the thinking that non-technical users (for example my mom) really don't care about what's the actual path since they don't deal with the system from a shell. All they really care is which is external and which is internal. So giving more information than that is giving them extra information to digest, which is extra burden. In short, from a UX point of view, I am more in favor of hiding as much technical detail as possible.

**Comment by Frenzie** [comment]
We're users too though. I despise the fact that Windows hides file extensions by default (not really the same thing but somewhat similar principle) and UNetbootin is [practically useless due to user-friendliness](http://fransdejonge.com/2016/11/unetbootin-custom-drive-selection/). But I'm not really objecting to going with just "Internal storage."

**Comment by Hzj-jie** [comment]
If a user has a Kobo with 4g SD card, the storage statistics becomes almost useless for him. :)

**Pull request merged**
