### PR TITLE
NewsDownloader: Compatibility for uses with previous configuration files

### PR DESCRIPTION
**Pull request by mwoz123**
Compatibilty for existing NewsDownloader users. There would be no need to adapt their configuration files to changes in N.D.

+ fix sample feed configuration (pc world was not working for download_full_article)

As my `./kod run` doesn't work (after pull?) [neither clean nor build works] I wasn't able to test it:(

### CODE REVIEW

**Comment by mwoz123** [comment]
Tested in real device works fine

**Comment by Frenzie** [comment]
I thought we agreed to change the default to the regular norm? :-) But anyway, that empty string seems kind of ugly and unnecessary.

> As my ./kod run doesn't work (after pull?) [neither clean nor build works] I wasn't able to test it:(

Setting aside the obvious typo, don't forget you might need to `git submodule update --recursive`, assuming you don't purposefully want submodules at different commits.

**Comment by mwoz123** [comment]
Right, should be 'kodev'. 

This is for existing news downloader users that already have its own configuration. 
I'd be a little bit angry if I had to manually update all of my feeds configuration to remain what I had just because it was plugin is updated. 

It's just for existing users (they don't have that new tag in their configuration). 
I don't want them to be mad at me ;) 
All new users will have this new tag out of the box in every entry. 

And so download full article will work only for null value (preexisting users with configs)  or equal 'true'. 
Every other value (including false) will cause file will be created only with that couple (or sometimes only first) sentence (news description). 

I'll remove check for empty string

**Comment by mwoz123** [comment]
Thanks

**Pull request merged**
