### PR TITLE
Ship the STL if need be

### PR DESCRIPTION
**Pull request by NiLuJe**
Depends on https://github.com/koreader/koreader-base/pull/1513

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9470)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by NiLuJe** [comment]
And made sure we strip the shipped STL, as that may not be the case in the TC.

@Frenzie: This'll probably make the OTA balloon a tiny bit; to offset that, you can safely drop the prstux assets from (at the very least) the OTA server, as @tux-linux tried to replicate this summer, and, apparently, you can't, and the original author doesn't have all the required files/tools anymore, so it prooobably won't be missed ;).

**Comment by tux-linux** [comment]
Hm, well, the thing is Android-based, making it very... different from other readers I've dealt with before. So I tried to understand the boot process, thought I did but then nothing worked, so, needs a bit more work ;)
I guess you can drop support for that, if I make it work someday I may open some pull request so that other owners could run it from InkBox OS as an user app or a standalone OS.

**Comment by NiLuJe** [comment]
It's not even dropping support, it's just harmlessly  saving space on the OTA server by not storing the binaries there anymore ;).

**Comment by Frenzie** [comment]
@NiLuJe You're saying build it but don't put it on that server or quit building it?

**Comment by NiLuJe** [comment]
Your call, really, as I don't think there Ara actual users ;).

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/9470)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NiLuJe)

**Comment by Frenzie** [comment]
Okay, we won't build it then: https://gitlab.com/koreader/nightly-builds/-/commit/cf225de75107a9a21c78e21461e6726959790e89

But at least for the moment we'll keep it in base. If it's not built at all it'll likely break. ;-)

**Comment by yparitcher** [comment]
Breaks my local build
```
arm-kindlepw2-linux-gnueabi-strip --strip-unneeded koreader-kindlepw2-arm-kindlepw2-linux-gnueabi/koreader/libs/libstdc++.so.6
arm-kindlepw2-linux-gnueabi-strip: unable to copy file 'koreader-kindlepw2-arm-kindlepw2-linux-gnueabi/koreader/libs/libstdc++.so.6'; reason: Permission denied
```

Our TC is shipped with RO permissions so when copied we do not have permissions to strip it, probably needs a `chmod` somewhere.

**Comment by Frenzie** [comment]
Er, so should I revert that then? lol

**Comment by NiLuJe** [comment]
Nah, I was just pleasantly surprised ;o).

**Pull request merged**
