### PR TITLE
kodev: Avoid catchsegv via -S, --no-catchsegv

### PR DESCRIPTION
**Pull request by NiLuJe**
This works around #7036 on my end (so far).

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7044)

### CODE REVIEW

**Review by Frenzie — COMMENTED** [review]
Missing a file?

**Review by Frenzie — APPROVED** [review]
I see, already part of https://github.com/koreader/koreader/pull/6976

**Comment by Frenzie** [comment]
Before you merge this, have you tried the rather significantly simpler `os.exit(ret, true)`?

**Comment by Frenzie** [comment]
It's Lua 5.2, but it's been supported in LuaJIT for a decade https://github.com/LuaJIT/LuaJIT/commit/73384567962fa8ec7759dc460e1abbb1d388d77d

**Comment by Frenzie** [comment]
And get rid of that fugly mess. >_>

**Comment by NiLuJe** [comment]
@Frenzie: That is indeed much better, thanks ;).

**Comment by Frenzie** [comment]
Much nicer. ^_^

**Pull request merged**
