### PR TITLE
hold to lookup word in dict window

### LINKED ISSUE #1541: Requested feature - select search in dictionary window
This might be a good idea.
When dictionary popup is open, sometimes we want to look further in words, eg:
I'm selecting word "pass" in text, my dictionary found it. Inside dictionary popup I see word "enter" and want look in dictionary for it, so it would be nice to select it in dictionary popup, and get answer for it.

### PR DESCRIPTION
**Pull request by chrox**
This should close #1541.

### CODE REVIEW

**Comment by Frenzie** [comment]
Very nice!

**Comment by lenisko** [comment]
q.q :beer: for chrox.
Good job!

**Comment by lenisko** [comment]
haha, one thing @chrox , can you make closing window kill all other?:)

**Comment by chrox** [comment]
I think it's a feature to stack up the definition windows so that when you close one window you can trace back one frame of the stack. It's a natural process in our mind as well as in the software.

**Comment by Frenzie** [comment]
Agreed. They either need to stack or have proper "back" functionality.

**Comment by lenisko** [comment]
so maybe hold close for closing all? or close all button?
just an idea, nothing serious :smile:

**Comment by Frenzie** [comment]
Not a bad one!

On October 19, 2015 7:05:42 PM GMT+02:00, Jacob <notifications@github.com> wrote:
>so maybe hold close for closing all? or close all button?
>just an idea, nothing serious :smile: 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/koreader/koreader/pull/1678#issuecomment-149283174

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lenisko** [comment]
Oh thank you ~

Lately support of KOreader grow a loot, I'm happy to see that :)
Been using weird Chinese software so far, never ever again.

**Comment by chrox** [comment]
A hold on the close button and a confirm dialog to close all dict windows is cool. I will implement that if I have some spare time.

**Comment by lenisko** [comment]
>A hold on the close button and a confirm dialog to close all dict windows is cool. I will implement that if I have some spare time.

just please, give users way to disable it in settings. After seeing something for... many times it's annoying.

Sure, no rush : )

**Pull request merged**
