### PR TITLE
Archive viewer: correct parsing unzip output

### PR DESCRIPTION
**Pull request by hius07**
More generic template: https://github.com/koreader/koreader/pull/10584#issuecomment-1614408339.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10625)

### CODE REVIEW

**Comment by Frenzie** [comment]
If you're invoking the shell anyway can't you just pipe it to for example `cut -d' ' -f1` and such? But I thought we included a zip library.

**Comment by hius07** [comment]
> But I thought we included a zip library.

Can it unzip?
https://github.com/koreader/koreader/blob/b8af326836374b82cccdadafef869d1d5decac69/frontend/ui/wikipedia.lua#L829

**Review by poire-z — APPROVED** [review]

**Comment by poire-z** [comment]
> Can it unzip?

Nope, I just made stuff to write/zip EPUBs.
But someone interested could write a ffi/zipreader :)
Although, because there may be many strange zip made by strange tools in the world, I think it's safer to use a _apriori_ robust existing `unzip`, than to make our own simple-per-specs that will be hurt and failed on strange zips.

> can't you just pipe it to for example `cut -d' ' -f1` and such?

That's another process to exec. Safer to parse in Lua, and we need 2 fields, so we would need to also parse the output from `cut`. 

> But I thought we included a zip library.

We just have a libz and a libzstd. Dunno if these or any other lib exports some unzip functions.

**Comment by Frenzie** [comment]
> That's another process to exec. Safer to parse in Lua, and we need 2 fields, so we would need to also parse the output from cut.

Implicitly I meant more the thought than the implementation.

`util.gsplit(output, " ")` instead of some convoluted pattern.

**Comment by benoit-pierre** [comment]
Try `unzip -Z1`.

**Comment by Frenzie** [comment]
I thought the point was to detect the filesize and modified date, otherwise I'd have said that long ago? :-)

**Comment by benoit-pierre** [comment]
Sorry. ¯\\_(ツ)_/¯

**Pull request merged**
