### PR TITLE
[i18n] Add context to various non/auto/small/medium/large

### PR DESCRIPTION
**Pull request by Frenzie**
Needed for Greek and possibly other languages.

Closes #8478.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8489)

### CODE REVIEW

**Review by poire-z — APPROVED** [review]
Feels a bit noisy - and we'll have to think about C_() new ones (or just wait for requests?).
But ok :)
(I wonder how much this is really required by Greek and if it couldn't go with just `S M L XXL` like on t-shirts :) , or if it's just @ichnilatis-gr 's greek perfectionism and wanting to have buttons read as sentences :) but I guess that's the point with having nice translations :)

**Comment by ichnilatis-gr** [comment]
Dear @poire-z, maybe you're right. I really don't want to be a nuisance. But... I'm a bit of a perfectionist... :-)
I don't insist on these changes.

P.S.: I think an e has been omitted from the title. "... various non**e**/auto..."

**Comment by Frenzie** [comment]
I already fixed it for the commit itself. ;-)

**Comment by ichnilatis-gr** [comment]
> I already fixed it for the commit itself. ;-)

Thank you very much!

**Comment by ichnilatis-gr** [comment]
Dear @Frenzie, Sorry to be a nuisance again. Could you also please do two instances of translation for the word "Style", one for the upper menu (text menu) and one for the highlights popup? Is it possible?

Thank you!

**Comment by hius07** [comment]
It's here
https://github.com/koreader/koreader/blob/d9730cf0fc15647c637c6ba4661cabd60c084733/frontend/apps/reader/modules/readertypeset.lua#L16
https://github.com/koreader/koreader/blob/d9730cf0fc15647c637c6ba4661cabd60c084733/frontend/apps/reader/modules/readerhighlight.lua#L666

**Comment by ichnilatis-gr** [comment]
It would be more convenient if it was done in Weblate. To make it permanent.

**Comment by Frenzie** [comment]
That's the only way to put it in Weblate. :-)

**Comment by ichnilatis-gr** [comment]
> That's the only way to put it in Weblate. :-)

I'm afraid of making a mistake. I don't know how it works and what I need to change.
Thank you for all and mostly for your tolerance. :-)

**Comment by Frenzie** [comment]
Nothing besides what you're doing. But if you're ever feeling adventurous and would like to try what I did in https://github.com/koreader/koreader/pull/8510, on the right in Weblate it shows direct links to the lines where the text occurs, and you can propose similar changes straight through GH.

**Comment by ichnilatis-gr** [comment]
> and you can propose similar changes straight through GH.

How can I propose changes through GH?

**Comment by Frenzie** [comment]
Exactly. In pictures:

### String location(s) on Weblate


### This leads to the string in the source on GH
Screenshot_2021-12-04_14-36-28

### Scroll up and find the edit button
Screenshot_2021-12-04_14-36-51

There's no need at all of course! This is only a small effort for me. Just in case you'd like to try something else besides translating into Greek. ;-)

**Comment by ichnilatis-gr** [comment]
> There's no need at all of course! This is only a small effort for me and I'm glad to do it. This is exactly why I bothered to implement context, which we didn't support yet a few years ago. I'm mentioning this just in case you'd like to try something else besides translating into Greek. ;-)

Dear @Frenzie, your help really touches me. And I speak sincerely. Unfortunately I have no programming knowledge and most importantly no time. That's why even the translation into Greek is going so slowly. But it's true that I feel so indebted to you, as you all take the time and effort to improve an application for the benefit of many others, while I just make suggestions and requests.
Thank you once again!

**Pull request merged**
