### PR TITLE
Order keys in settings.reader.lua

### PR DESCRIPTION
**Pull request by jperon**
All is in the title.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/6868)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Seems harmless enough.

**Review by poire-z — APPROVED** [review]
Good idea.

**Review by Frenzie — COMMENTED** [review]
Btw, there's no need to put a period at the end of the commit message.

**Comment by poire-z** [comment]
Should this also be done with DocSettings, so we get nice looking and more human readable metadata.epub.lua ?
```diff
--- a/frontend/docsettings.lua
+++ b/frontend/docsettings.lua
@@ -195,3 +195,3 @@ function DocSettings:flush()
     self:ensureSidecar(self.sidecar)
-    local s_out = dump(self.data)
+    local s_out = dump(self.data, nil, true)
     os.setlocale('C', 'numeric')
```

**Comment by Frenzie** [comment]
It might be good to double check how performance works out on a bookmark-heavy file.

**Comment by poire-z** [comment]
On my Kobo, switching between a zero bookmarks book (small durations below) and the 275 bookmarks book from #5766 (larger durations) :

Currently:
```
WARN    docsettngs dump orig took 0.050 seconds
WARN    docsettngs dump orig took 0.003 seconds
WARN    docsettngs dump orig took 0.077 seconds
WARN    docsettngs dump orig took 0.001 seconds
WARN    docsettngs dump orig took 0.050 seconds
```
With sorting:
```
WARN    docsettngs dump sorted took 0.077 seconds
WARN    docsettngs dump sorted took 0.009 seconds
WARN    docsettngs dump sorted took 0.090 seconds
WARN    docsettngs dump sorted took 0.006 seconds
WARN    docsettngs dump sorted took 0.070 seconds
WARN    docsettngs dump sorted took 0.008 seconds
WARN    docsettngs dump sorted took 0.066 seconds
```

So, yes, takes a bit more time - but I'm not sure how to appreciate the differences :)

**Comment by Frenzie** [comment]
I suppose that means the interaction with FAT32 takes the bulk of the effort, unless it's more of a theoretical concern?

**Comment by poire-z** [comment]
I don't think anything FAT32 is at play here: whether sorted or not, the amount written should be the same - so, I guess it's purely the sorting (and the little temporary table added to each table with sorted keys).
Even if my test samples are small, the worst conclusion would be:
Small metadata: 3ms > 9ms
Larger metadata: 50ms > 90ms

**Comment by Frenzie** [comment]
> I don't think anything FAT32 is at play here: whether sorted or not, the amount written should be the same

Yes, and people say it gets slow to close books. I wouldn't know because I'm a very light bookmark/highlight user. :) But given the minute differences in what you posted above, any slowness would therefore have to come from the writing stage.

**Pull request merged**
