### PR TITLE
Remarkable port

### LINKED ISSUE #5822: Cervantes (and probably others) crash on latest nightly
Updated from 2019.12 to latest nightly. OTA update went without problems but the program is unable to start.

Log:

```
Tweaking LuaJIT's max loop unroll factor (15 -> 45)
FB: computed size: 6782976
FB: id           : mxc_epdc_fb
FB: smem_len     : 6782976
FB: line_length  : 2944
FB: xres         : 1448
FB: xres_virtual : 1472
FB: yres         : 1072
FB: yres_virtual : 2304
FB: bpp          : 16
./luajit: ./ffi/framebuffer_mxcfb.lua:707: attempt to call method 'isRemarkable' (a nil value)
stack traceback:
	./ffi/framebuffer_mxcfb.lua:707: in function 'init'
	./ffi/framebuffer.lua:70: in function 'new'
	frontend/device/cervantes/device.lua:155: in function 'init'
	frontend/device.lua:49: in main chunk
	[C]: in function 'require'
	./reader.lua:119: in main chunk
	[C]: at 0x00013f05
```

Probably unnoticed because both Kobo, Kindle and Pocketbook went first than remarkable and just sony & cervantes go after it.

### PR DESCRIPTION
**Pull request by pazos**
#5697 rebased to master without conflicts. All the work done by @tcrs

Fixes #5822 

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/5828)

### CODE REVIEW

**Comment by pazos** [comment]
Ok, I'm not sure how to deal with the warning

```
Warning: it looks like you might be using unscaled sizes.
It is almost always preferable to defer to one of the predefined sizes in ui.size in the following files:
frontend/device/remarkable/device.lua:28:local mt_width = 767
frontend/device/remarkable/device.lua:29:local mt_height = 1023
```

**Comment by NiLuJe** [comment]
@pazos: There's an ignore syntax for LuaCheck (IIRC).

I don't recall the proper syntax, but the warning is definitely bogus here, so safe to ignore ;).

**Comment by Frenzie** [comment]
It's our home-grown `-- unscaled_size_check: ignore`. I'll add it.

**Comment by tcrs** [comment]
Thanks for sorting this out, I was busy the last few days.

**Pull request merged**
