### PR TITLE
VocabBuilder.koplugin: support batch operations in book filtering

### PR DESCRIPTION
**Pull request by weijiuqiao**
Added support
1. Select only this book
2. Select all books
3. Select all books on this page
4. Deselect all books on this page 

when filtering.

Ref. #11471

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11475)

### CODE REVIEW

**Comment by Frenzie** [comment]
Thanks!

**Comment by weijiuqiao** [comment]
No worries!

**Comment by poire-z** [comment]
(If this closes #11471, do close it :))

**Comment by Frenzie** [comment]
We generally write "fix" or "close" when it does that (or "addresses" etc. but that's not an automatic GH keyword) while we normally use "references" to mean it somehow relates to or does only part of it.

Also don't write "partially fixes" because GH only reads the "fixes". ;-)

**Comment by weijiuqiao** [comment]
Got it :)

**Pull request merged**
