### PR TITLE
Disable show chapter markers when progress bar is hidden in footer

### PR DESCRIPTION
**Pull request by robert00s**

### CODE REVIEW

**Comment by Biep** [comment]
The progress bar no longer has the option to shrink to the available space.  On my Kobo Aura One, in portrait mode, when showing everything (in default order), memory usage drops off the bar at the far end.  If the bar would shrink ever so little, it would all fit, as it used to.

**Comment by NiLuJe** [comment]
@Biep: Could you open a new, dedicated issue for thazt?

(With a xref top here, if that's indeed where the regression came from).

**Comment by poire-z** [comment]
Possibly #5757 enforcing a 20% min width.

**Comment by Biep** [comment]
@NiLuJe: done (#5778).

**Pull request merged**
