### PR TITLE
Keyboard: add Ukrainian virtual keyboard

### PR DESCRIPTION
**Pull request by Mnkach**
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10037)

### CODE REVIEW

**Comment by hius07** [comment]
Thank you!
(1) "i" and "г" keys: the "ї" and "ґ" grey supersripts are shown in the upper rigth corner. Maybe place the respective popup keys in the "east" and "north-east" positions?
(2) "й" key: the popup "ы" keys must be placed in the "east" and "north-east" positions .
(3) Symbol layout "'", "ї" and "ґ" keys: I understand your intention but the solution is not logical. Do we have any other options/symbols?

**Comment by Mnkach** [comment]
(1) Fixed
(2) "и" and "ы" have the same pronunciation, so "ы" popup was moved to "и"
(3) There are some archaic Cyrillic characters, but they are not used. What about some Greek letters?

**Comment by Kelamir** [comment]
This is great! Thank you for putting in the effort, Truly appreciate it. 

A bit feedback: there is no need for "ы"(it is not a Ukrainian letter) and "Ў", which is related to Ukrainian language just barely(some dictionaries use it as a phonetic symbol, according to Wikipedia). I'm Ukrainian and I have _never_  seen Ў being used.

**Comment by hius07** [comment]
> so "ы" popup was moved to "и"

(1) Upper and lower "ы" are switched in the popup.

(2) I do not think we need "ў" in the popup of "у" (it's from Belarussian, isn't it?).

(3) Minor CircleCI warning:
frontend/ui/data/keyboardlayouts/keypopup/uk_popup.lua:166:1: line contains only whitespace

(4) Symbol layer: sorry, no idea, I'm fine with any but the old-slavic chars.

**Comment by hius07** [comment]
> there is no need for "ы"(it is not a Ukrainian letter)

Sure, but we have other russian chars in popups (э, ё, ъ), let them be (hidden).

**Comment by Kelamir** [comment]
I checked other keyboards, such as English. On Y there's a pop up with about 10 characters! That's something. Initially I find it strange, but thinking about it, perhaps this is done because on e-ink devices this is the only way to enter text, so widest variety of options is preferred? I'm new to the ecosystem, would welcome an explanation :)

**Comment by Frenzie** [comment]
The "English" keyboard is a (Western?) European QWERTY keyboard, similar to US International and EurKEY. If you don't look for it you can use it as a basic US ASCII keyboard. In practical terms that means the diaeresis (ë), grave accent (è) and acute accent (é) are needed on most letters, plus a few related extras like ß for German. On y specifically those diacritics are there mostly for the sake of consistency with other letters like a, e, i, and u and less for practicality. As an aside, the popup indicates how you can type them with a quick swipe, so if you become more familiar with the layout you can type quite quickly.

Besides that there are some frequently used Greek characters and some basic IPA, often not easily accessible by swipe but only by long-press.

As to what makes sense for a Ukrainian keyboard I leave it to you guys. If a few small extensions in popups allow for typing a more international Cyrillic that would be in line with the design philosophy for the "English" keyboard.

**Comment by Mnkach** [comment]
> > so "ы" popup was moved to "и"
> 
> (1) Upper and lower "ы" are switched in the popup.
> 
> (2) I do not think we need "ў" in the popup of "у" (it's from Belarussian, isn't it?).
> 
> (3) Minor CircleCI warning: frontend/ui/data/keyboardlayouts/keypopup/uk_popup.lua:166:1: line contains only whitespace
> 
> (4) Symbol layer: sorry, no idea, I'm fine with any but the old-slavic chars.

(1) Fixed

(2) This letter provides full support for the Belarusian alphabet

(3) Fixed

**Comment by hius07** [comment]
> (2) This letter provides full support for the Belarusian alphabet

Okay

**Comment by poire-z** [comment]
Good to go ?

**Comment by hius07** [comment]
There are 3 chars in the symbol layer that are not necessary but I have no good idea for replacement. So maybe let it be as is.

**Pull request merged**
