### PR TITLE
UIManager: A small livestock also makes crap

### PR DESCRIPTION
**Pull request by zwim**
A mini improvement in speed, saves one arithmetic operation

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9576)

### CODE REVIEW

**Comment by NiLuJe** [comment]
I'm... not sure I grok that?

I'd naively assume that `e` would *always* be > `s` (or at the very least == if the list only has a single element)?

**Comment by zwim** [comment]
That improvement is no big deal:
Logically if `a + 1 == b` then  `a - b == 1`.

A small testsuite shows for 
```
x = 0

for i = 1,1000 do
    for j = 1, 1000 do
        for k = 1,1000 do
            if k - j  == 1 then
                x = x + 1
            end
        end
    end
end
```
a time of 1.24 secs 

and for
```
x = 0

for i = 1,1000 do
    for j = 1, 1000 do
        for k = 1,1000 do
            if k + 1   == j then
                x = x + 1
            end
        end
    end
end
```

a time of 1,47s.

So this PR seems to save a nit.

**Comment by NiLuJe** [comment]
> Logically if `a + 1 == b` then `a - b == 1`.

Unless I'm very tired, no? (Unless you meant `a - b == -1`?)

On the other hand, if `a + 1 == b` then `b - a == 1`?

**Comment by NiLuJe** [comment]
i.e., I'm not even concerned with performance right now, but correctness ;).

**Comment by zwim** [comment]
F*** me and myself!!!, is it time to retire? Thanks for your attention. The equivalent forming was wrong. See next commit. 

But the timing will stay the same -> So it IS an improvement :)

**Comment by zwim** [comment]
> > Logically if `a + 1 == b` then `a - b == 1`.
> 
> Unless I'm very tired, no? (Unless you meant `a - b == -1`?)
> 
> On the other hand, if `a + 1 == b` then `b - a == 1` (but that changes nothing ;p)?

Yes it changes nothing logically, but luajit can optimize the things better.

**Comment by NiLuJe** [comment]
> Yes it changes nothing logically, but luajit can optimize the things better.

I'm getting strictly identical timings on both x86_64 & armv7 here :?

**Comment by zwim** [comment]
Strange, I get an improvement form 1.4x to 1.2x seconds for the testbench above.
But anyway I will close this, as it is not worth the time to talk about it. 

In fact, I would rather investigate to replace the binary insertion with an ordinary `table.insert`, `table.sort`.

**Comment by NiLuJe** [comment]
> In fact, I would rather investigate to replace the binary insertion with an ordinary `table.insert`, `table.sort`.

Hmm. It's a small array, that's not necessarily a bad idea, yeah ;).

(FWIW, I wouldn't necessarily trust such a simplistic bench, but I didn't have an emu build to run the actual uimanager schedule test bench, which should at least reflect our real world use-cases slightly more accurately ;). And it's a bitch to run outside of busted to test it on-device :/).

**Pull request closed without merging**
