### PR TITLE
Bump base (sdcv 0.5.2; fix *buntu 17.10 build & segfault)

### LINKED ISSUE #3302: dictionary: sdcv segfault on firmware 4.6.9960
Hello,I'm using the latest release koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-1293-g34ad91c on kobo aura one.

I have tried several dictionaries (for example,search for definition for apple) but none worked. They all said no definition found.  

Also,i noticed a Segmentation fault in the crash.log. Does it have anything to do with my problem?

Thanks in advance.

### PR DESCRIPTION
**Pull request by Frenzie**
Fixes #3302. Fixes #3071.

### CODE REVIEW

**Comment by poire-z** [comment]
Can you check on your device how sdcv works with today's nightly?
For me, on kobo glo hd, it is slower: 20 to 30 s when it usually took 5 to 10 seconds with 10 dicts.
And disabling some dicts (`-u` option used), with some non-ascii dict name still enabled, fails (like seen when locale is not utf8).

**Comment by Frenzie** [comment]
I'll check the nightly but I noticed no slowdowns testing my own builds.

**Comment by Frenzie** [comment]
Hard to judge; would need objective measurements to tell.

**Comment by poire-z** [comment]
Well, it seems now quite ok :|. I'll check after a reboot.
How does it do when you add Académie Française dict, and disable an other one?
locale is already `LANG=en_US.UTF-8`, and adding it or a variation of it to sdcv command line (a trick that worked on my latin1 linux) does not make things work.
Additionally, but I must be the only one using that feature, whe, you have dicts in `dict_ext/`, and you give `-u` for dicts that do not exist in the `dict/` or `dict_ext/` that is used for the sdcv invocation, it fails (older version didn't mind having `-u "non existant dict"`...

**Comment by Frenzie** [comment]
> Additionally, but I must be the only one using that feature

Doesn't matter if you add unit tests. :-P But I thought you already said you were going to submit a patch for that upstream? Btw, one of the big improvements in upstream sdcv is that it now also has unit tests and CI, so it makes more sense to add them there.

Rerunning the test from https://github.com/koreader/koreader/pull/2934#issuecomment-306746794 I do indeed see substantially worse values. My hypothesis based on the few quick tests below is that the worse results seem to be related to synonyms and fuzzy search. I ran these tests on my H2O.

## Regular (with synonyms)

### 0.4 KOReader sdcv fork
```
# for w in `echo "épuisant épuisante épuisantes pleurésie caparaçonnée pre-consonantal peche
resse pécheresse"`; do echo $w ; time ./sdcv-0.4-koreader-fork --utf8-input --data-dir data/dict -nj $w 1>/dev/nul
l; done
épuisant
real	0m 0.10s
user	0m 0.02s
sys	0m 0.06s
épuisante
real	0m 0.78s
user	0m 0.71s
sys	0m 0.07s
épuisantes
real	0m 0.77s
user	0m 0.72s
sys	0m 0.05s
pleurésie
real	0m 0.04s
user	0m 0.01s
sys	0m 0.03s
caparaçonnée
real	0m 0.69s
user	0m 0.62s
sys	0m 0.06s
pre-consonantal
real	0m 0.49s
user	0m 0.43s
sys	0m 0.06s
pecheresse
real	0m 0.79s
user	0m 0.70s
sys	0m 0.08s
pécheresse
real	0m 0.04s
user	0m 0.01s
sys	0m 0.03s
```

### 0.5.2 nightly
```
# for w in `echo "épuisant épuisante épuisantes pleurésie caparaçonnée pre-consonantal peche
resse pécheresse"`; do echo $w ; time ./sdcv --utf8-input --data-dir data/dict -nj $w 1>/dev/null; done
épuisant
real	0m 1.12s
user	0m 1.06s
sys	0m 0.05s
épuisante
real	0m 1.06s
user	0m 1.00s
sys	0m 0.06s
épuisantes
real	0m 2.59s
user	0m 2.47s
sys	0m 0.11s
pleurésie
real	0m 1.07s
user	0m 0.98s
sys	0m 0.08s
caparaçonnée
real	0m 2.42s
user	0m 2.31s
sys	0m 0.10s
pre-consonantal
real	0m 2.04s
user	0m 1.94s
sys	0m 0.09s
pecheresse
real	0m 2.63s
user	0m 2.54s
sys	0m 0.07s
pécheresse
real	0m 1.27s
user	0m 1.21s
sys	0m 0.05s
```

Oddly enough it's consistently ever so slightly faster with the one I built myself, but still with the significant slowdown compared to older sdcv.

### 0.5.2 compiled on my PC
```
# for w in `echo "épuisant épuisante épuisantes pleurésie caparaçonnée pre-consonantal peche
resse pécheresse"`; do echo $w ; time ./sdcv --utf8-input --data-dir data/dict -nj $w 1>/dev/null; done
épuisant
real	0m 1.10s
user	0m 0.99s
sys	0m 0.10s
épuisante
real	0m 1.06s
user	0m 1.02s
sys	0m 0.03s
épuisantes
real	0m 2.46s
user	0m 2.31s
sys	0m 0.14s
pleurésie
real	0m 1.06s
user	0m 1.00s
sys	0m 0.05s
caparaçonnée
real	0m 2.29s
user	0m 2.20s
sys	0m 0.08s
pre-consonantal
real	0m 1.91s
user	0m 1.79s
sys	0m 0.12s
pecheresse
real	0m 2.49s
user	0m 2.37s
sys	0m 0.11s
pécheresse
real	0m 1.06s
user	0m 1.02s
sys	0m 0.03s
```

I haven't tested this and I'm probably slightly less motivated than your exceptional situation, but note that support for synonyms was added quite recently upstream in https://github.com/Dushistov/sdcv/pull/20

One of my dictionaries has a 2 MB syn file. Moving it out of the way, but keeping one with a 100 KiB syn file results in this:

## Without 2 MB syn file

It looks like this helps a great deal.

### KOReader 0.4.x fork
```
# for w in `echo "épuisant épuisante épuisantes pleurésie caparaçonnée pre-consonantal peche
resse pécheresse"`; do echo $w ; time ./sdcv-0.4-koreader-fork --utf8-input --data-dir data/dict -nj $w 1>/dev/nul
l; done
épuisant
real	0m 0.09s
user	0m 0.03s
sys	0m 0.04s
épuisante
real	0m 0.67s
user	0m 0.62s
sys	0m 0.05s
épuisantes
real	0m 0.67s
user	0m 0.63s
sys	0m 0.03s
pleurésie
real	0m 0.04s
user	0m 0.00s
sys	0m 0.03s
caparaçonnée
real	0m 0.59s
user	0m 0.55s
sys	0m 0.04s
pre-consonantal
real	0m 0.41s
user	0m 0.38s
sys	0m 0.03s
pecheresse
real	0m 0.67s
user	0m 0.64s
sys	0m 0.03s
pécheresse
real	0m 0.04s
user	0m 0.01s
sys	0m 0.02s
```

### 0.5.2
```
# for w in `echo "épuisant épuisante épuisantes pleurésie caparaçonnée pre-consonantal peche
resse pécheresse"`; do echo $w ; time ./sdcv --utf8-input --data-dir data/dict -nj $w 1>/dev/null; done
épuisant
real	0m 0.23s
user	0m 0.16s
sys	0m 0.07s
épuisante
real	0m 0.18s
user	0m 0.13s
sys	0m 0.05s
épuisantes
real	0m 1.39s
user	0m 1.32s
sys	0m 0.06s
pleurésie
real	0m 0.18s
user	0m 0.15s
sys	0m 0.03s
caparaçonnée
real	0m 1.24s
user	0m 1.14s
sys	0m 0.09s
pre-consonantal
real	0m 0.91s
user	0m 0.82s
sys	0m 0.09s
pecheresse
real	0m 1.41s
user	0m 1.30s
sys	0m 0.10s
pécheresse
real	0m 0.18s
user	0m 0.14s
sys	0m 0.04s
```

## No syn file

Finally, getting rid of the last syn-file containing dictionary. Note how the 0.5.2 times are actually significantly worse when it can't find anything.

### KOReader 0.4.x sdcv fork
```
# for w in `echo "épuisant épuisante épuisantes pleurésie caparaçonnée pre-consonantal peche
resse pécheresse"`; do echo $w ; time ./sdcv-0.4-koreader-fork --utf8-input --data-dir data/dict -nj $w 1>/dev/nul
l; done
épuisant
real	0m 0.59s
user	0m 0.52s
sys	0m 0.05s
épuisante
Nothing similar to \u00e9puisante, sorry :(
real	0m 0.55s
user	0m 0.52s
sys	0m 0.03s
épuisantes
Nothing similar to \u00e9puisantes, sorry :(
real	0m 0.56s
user	0m 0.51s
sys	0m 0.04s
pleurésie
Nothing similar to pleur\u00e9sie, sorry :(
real	0m 0.55s
user	0m 0.50s
sys	0m 0.05s
caparaçonnée
Nothing similar to capara\u00e7onn\u00e9e, sorry :(
real	0m 0.51s
user	0m 0.42s
sys	0m 0.08s
pre-consonantal
real	0m 0.37s
user	0m 0.34s
sys	0m 0.03s
pecheresse
Nothing similar to pecheresse, sorry :(
real	0m 0.56s
user	0m 0.53s
sys	0m 0.02s
pécheresse
Nothing similar to p\u00e9cheresse, sorry :(
real	0m 0.55s
user	0m 0.51s
sys	0m 0.04s
```

### 0.5.2
(the `Nothing similar to` message apparently switched from stderr to stdout? it's still there if you just search for a word)
```
# for w in `echo "épuisant épuisante épuisantes pleurésie caparaçonnée pre-consonantal peche
resse pécheresse"`; do echo $w ; time ./sdcv --utf8-input --data-dir data/dict -nj $w 1>/dev/null; done
épuisant
real	0m 1.07s
user	0m 0.98s
sys	0m 0.09s
épuisante
real	0m 1.06s
user	0m 1.03s
sys	0m 0.02s
épuisantes
real	0m 1.06s
user	0m 1.00s
sys	0m 0.05s
pleurésie
real	0m 1.07s
user	0m 1.03s
sys	0m 0.03s
caparaçonnée
real	0m 0.95s
user	0m 0.85s
sys	0m 0.10s
pre-consonantal
real	0m 0.71s
user	0m 0.63s
sys	0m 0.06s
pecheresse
real	0m 1.07s
user	0m 1.00s
sys	0m 0.07s
pécheresse
real	0m 1.05s
user	0m 0.96s
sys	0m 0.08s
```

I (or someone else) will need to repeat these tests on a desktop PC to see if it's "only" some compilation flag or if it's a serious upstream performance degradation.

**Comment by poire-z** [comment]
> But I thought you already said you were going to submit a patch for that upstream? 

Never said and never even thought about that :) It didn't need any patch, `-u "non existant dict"` caused no problem with previous version.

Anyway, 0.5.2 would accept french and chinese dicts names in `-u` with a simple patch:
```c
--- a/src/sdcv.cpp
+++ b/src/sdcv.cpp
@@ -62,7 +62,7 @@ using StrArr = ResourceWrapper<gchar *, gchar *, free_str_array>;
 static void list_dicts(const std::list<std::string> &dicts_dir_list, bool use_json);

 int main(int argc, char *argv[]) try {
-    setlocale(LC_ALL, "");
+    setlocale(LC_ALL, "en_US.UTF-8");
 #if ENABLE_NLS
     bindtextdomain("sdcv",
                    //"./locale"//< for testing

```
I don't get why it would need to erase LC_ALL, when later it uses glib stuff to parse command line, and this glib stuff must surely look at locale to convert command line arguments, and output `Invalid byte sequence in conversion input` when it finds UTF8, cause I guess with LC_ALL empty, it thinks it is in the C ASCII locale...

**Comment by Frenzie** [comment]
*ahem* /whistles
https://github.com/koreader/koreader-base/pull/550#issuecomment-336728542
> I'll check tomorrow if I have time if a small patch can solve that.

**Comment by poire-z** [comment]
oh, right  :) forgot about that as setting a correct locale solved the problem ... some days ago, with the sdcv build you provided, and seem to still do on the emulator.
Could be because I set it in LANG=, and there's a whole locale stuff on my linux,  so may be glib found its way with that, while there's no locale stuff on Kobo.
The problem with french or chinese dict name also happen on android...
(Anyway, I would patch here before thinking about upstream.)

**Comment by Frenzie** [comment]
We can apply patches before they're accepted upstream in some cases, but I strongly dislike the wasted effort in backporting patches let alone features. ;-)

**Comment by Frenzie** [comment]
I've attached x86_64 desktop builds of 0.4.2 (KOReader fork) and 0.5.2 (upstream).

[sdcv-x86_64-linux-gnu.zip](https://github.com/koreader/koreader/files/1404159/sdcv-x86_64-linux-gnu.zip)

**Comment by Frenzie** [comment]
Ah yes, this is an issue to be reported upstream. I'll quickly try some earlier upstream commits from around July before I do.

### KOReader 0.4.2
```
$ for w in `echo "épuisant épuisante épuisantes pleurésie caparaçonnée pre-consonantal pecheresse pécheresse"`; do echo $w ; time ./sdcv-0.4.2 --utf8-input --data-dir data/dict -nj $w 1>/dev/null; done
épuisant

real	0m0.046s
user	0m0.040s
sys	0m0.000s
épuisante

real	0m0.041s
user	0m0.036s
sys	0m0.004s
épuisantes
Nothing similar to épuisantes, sorry :(

real	0m0.040s
user	0m0.036s
sys	0m0.000s
pleurésie

real	0m0.003s
user	0m0.000s
sys	0m0.000s
caparaçonnée

real	0m0.036s
user	0m0.028s
sys	0m0.004s
pre-consonantal
Nothing similar to pre-consonantal, sorry :(

real	0m0.029s
user	0m0.024s
sys	0m0.004s
pecheresse

real	0m0.041s
user	0m0.036s
sys	0m0.000s
pécheresse

real	0m0.001s
user	0m0.000s
sys	0m0.000s
```

### KOReader 0.5.2
```
$ for w in `echo "épuisant épuisante épuisantes pleurésie caparaçonnée pre-consonantal pecheresse pécheresse"`; do echo $w ; time ./sdcv-0.5.2 --utf8-input --data-dir data/dict -nj $w 1>/dev/null; done
épuisant

real	0m0.387s
user	0m0.384s
sys	0m0.000s
épuisante

real	0m0.459s
user	0m0.448s
sys	0m0.008s
épuisantes

real	0m0.462s
user	0m0.448s
sys	0m0.012s
pleurésie

real	0m0.387s
user	0m0.384s
sys	0m0.000s
caparaçonnée

real	0m0.452s
user	0m0.440s
sys	0m0.012s
pre-consonantal

real	0m0.442s
user	0m0.436s
sys	0m0.004s
pecheresse

real	0m0.458s
user	0m0.452s
sys	0m0.004s
pécheresse

real	0m0.387s
user	0m0.384s
sys	0m0.000s
```

### Individual sdcv 0.5.2 (just `mkdir build && cd build && cmake .. && make`)
```
$ for w in `echo "épuisant épuisante épuisantes pleurésie caparaçonnée pre-consonantal pecheresse pécheresse"`; do echo $w ; time ./sdcv --utf8-input --data-dir data/dict -nj $w 1>/dev/null; done
épuisant

real	0m0.397s
user	0m0.400s
sys	0m0.000s
épuisante

real	0m0.468s
user	0m0.464s
sys	0m0.000s
épuisantes

real	0m0.465s
user	0m0.452s
sys	0m0.012s
pleurésie

real	0m0.399s
user	0m0.392s
sys	0m0.004s
caparaçonnée

real	0m0.460s
user	0m0.456s
sys	0m0.000s
pre-consonantal

real	0m0.445s
user	0m0.420s
sys	0m0.024s
pecheresse

real	0m0.465s
user	0m0.460s
sys	0m0.004s
pécheresse

real	0m0.395s
user	0m0.384s
sys	0m0.008s
```

**Comment by poire-z** [comment]
And this one solves the crash with non existent (because of encoding or because of alternate dict_ext) dict name:
```c
--- a/src/sdcv.cpp
+++ b/src/sdcv.cpp
@@ -182,7 +182,9 @@ int main(int argc, char *argv[]) try {
         // add bookname to list
         gchar **p = get_impl(use_dict_list);
         while (*p) {
-            order_list.push_back(bookname_to_ifo.at(*p));
+            if (bookname_to_ifo.count(*p) > 0) {
+                order_list.push_back(bookname_to_ifo.at(*p));
+            }
             ++p;
         }
     } else {

```

**Comment by Frenzie** [comment]
I'll leave analyzing the difference between my non-performance degrading JSON patch from May 2016 and upstream commit https://github.com/Dushistov/sdcv/commit/3105823e8bd66b3276bca41c2975e8756da478c5 to @ecraven but sounds like it's time for one or two PRs on your side. ;-)

**Comment by Dushistov** [comment]
@poire-z 

>I don't get why it would need to erase LC_ALL

It doesn't `erase`, you can read in `man setlocale`:

>If  locale  is an empty string, "", each part of the locale that should
>be modified is set according to the environment variables.

You can find similar code in many GNU projects.

**Comment by poire-z** [comment]
@Dushistov : any idea why then, launching:
`LANG.en_US.UTF-8 LC_ALL=en_US.UTF-8 ./sdcv -u "Dictionnaire de l’Académie Française, 8ème édition (1935)." test` (or a variation with `en_US.utf8`) would fail on our Kobo with:
`Invalid command line arguments: Invalid byte sequence in conversion input`
On our Kobo, we have:
```
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
```
I don't know anything about how locale stuff work, and I don't know how glib goes from that.

But it does work on a debian linux if I set `LANG=en_US.UTF-8` where I previsouly had `en_US` (latin1).
On my linux, I have a `/usr/share/i18n/charmaps/UTF-8.gz`, but I don't see any such file on my kobo. Dunno if that matters.

**Comment by poire-z** [comment]
Unfortunatly, the `setlocale(LC_ALL, "en_US.UTF-8");` part of my patch does not help, neither on Kobo nor Android :( We still get: `Invalid command line arguments: Invalid byte sequence in conversion input`

**Comment by poire-z** [comment]
OK, what I can conclude so far:
sdcv 0.5.2 uses glib's g_option stuff (https://developer.gnome.org/glib/stable/glib-Commandline-option-parser.html) to parse command line arguments.
This g_option_stuff insists on converting string arguments to utf8 according to current locale, and can't be made (except maybe with a trick, see below) to not do that and let the bytestring as is (https://developer.gnome.org/glib/stable/glib-running.html#setlocale).
If LC_ALL=en_US.UTF-8, it should however let the string as is, as it is utf8. But we saw this morning that didnt work.
The reason, I think, is that, for that, glib needs some locale infrastructure on the system, which our Kobo (and I guess Android) do not ship one. (Dunno if in the glib build, there are some option to make it embed that infrastructure...)
If I copy /usr/lib/locale (containing only a C.UTF-8/ subdir) from my linux to my kobo (./sdcv.orig being the one from yesterday, not today's patched one):
```
/mnt/onboard/.adds/koreader # LANG=C.UTF-8 LC_ALL=C.UTF-8 ./sdcv.orig  -nj -u "toto" test
Internal error: map::at (= good, no problem)
/mnt/onboard/.adds/koreader # LANG=C.UTF-8 LC_ALL=C.UTF-8 ./sdcv.orig  -nj -u "adÃ©mie" test
Invalid command line arguments: Invalid byte sequence in conversion input

/mnt/onboard/.adds/koreader # LOCPATH=/mnt/onboard/.adds/locale LANG=C.UTF-8 LC_ALL=C.UTF-8 ./sdcv.orig  -nj -u "toto" test
Internal error: map::at (= good, no problem)
/mnt/onboard/.adds/koreader # LOCPATH=/mnt/onboard/.adds/locale LANG=C.UTF-8 LC_ALL=C.UTF-8 ./sdcv.orig  -nj -u "adÃ©mie" test
Internal error: map::at (= good, no problem)
```
So, it seems to need some locale infrastructure, and/or LOCPATH= pointing to where there is one.

A trick (somehow tested on my linux, that seems like it could work on our device), is to patch sdcv.cpp so that it does not consider these options as STRING, but as FILENAME (where the above doc, and https://github.com/GNOME/glib/blob/9814898df6a2ea3006d5cbb457bd8419d8e815d4/glib/goption.c#L1305-L1347 says that on unix, the string will be used as is with no conversion, a simple strdup()). I'll update our patch so we can try that on next nightly.

Obviously, this trick may be OK for our devices, probably not for upstream sdcv, unless there's another option that trigger one behaviour or the other.

**Comment by poire-z** [comment]
Btw, had/could you try your benchmark tests with just the `-j` (json output) removed?

**Comment by Frenzie** [comment]
Makes no difference but I suppose it's potentially misleading the way I shared the log.

**Comment by poire-z** [comment]
2nd sdcv patch makes it work on Kobo.
But not on Android. On my android phone, I have `LANG `and `LC_ALL `empty, so I guess Glib thinks it is `C` and is still trying to convert to utf8 and outputs `Invalid byte sequence...`

**Comment by Frenzie** [comment]
Note that you can run the Android x86 binary on your regular PC.

**Comment by poire-z** [comment]
Some tests on Android:
```
/data/data/org.koreader.launcher/files # ./sdcv -nj -u "toto" test
Invalid command line arguments: Conversion from character set âen_USâ to âUTF-8â is not supported
(that was because my ssh was setting LANG=en_US, so it was still trying to convert to utf8)

/data/data/org.koreader.launcher/files # LANG= LC_ALL= ./sdcv -nj -u "toto" test
g_mkdir failed: Read-only file system (= GOOD)
/data/data/org.koreader.launcher/files # LANG= LC_ALL= ./sdcv --data-dir /sdcard/koreader/data/dict  -nj -u "toto" test
g_mkdir failed: Read-only file system
/data/data/org.koreader.launcher/files # LANG= LC_ALL= ./sdcv --data-dir /sdcard/koreader/data/dict  -nj test -u "toto" --utf8-input --utf8-output
g_mkdir failed: Read-only file system
/data/data/org.koreader.launcher/files # LANG= LC_ALL= ./sdcv --data-dir /sdcard/koreader/data/dict  -nj test -u "adÃ©mie" --utf8-input --utf8-output
Invalid command line arguments: Invalid byte sequence in conversion input
/data/data/org.koreader.launcher/files # LANG= LC_ALL=en_US.UTF-8 ./sdcv --data-dir /sdcard/koreader/data/dict  -nj test -u "adÃ©mie" --utf8-input --utf8-output
g_mkdir failed: Read-only file system
```
There's no obvious way to set environment variables in the android version of io.popen (A.stdout), so I guess I'll have to put back in our sdcv patch what was in my 1st try:
```
-    setlocale(LC_ALL, "");
+    setlocale(LC_ALL, "en_US.UTF-8");
```

**Comment by Frenzie** [comment]
It's funny, isn't it. Android is not really Linux and Android is not really Java either. Both of which cause much frustration.

**Comment by poire-z** [comment]
Still not working on Android :|
```
/data/data/org.koreader.launcher/files # ./sdcv --data-dir /sdcard/koreader/data/dict  -nj test -u "adÃ©mie" --utf8-input --utf8-output
Invalid command line arguments: Conversion from character set âen_USâ to âUTF-8â is not supported
  (ok, my ssh environment LANG was en_US)
/data/data/org.koreader.launcher/files # LANG= ./sdcv --data-dir /sdcard/koreader/data/dict  -nj test -u "adÃ©mie" --utf8-input --utf8-output
Invalid command line arguments: Invalid byte sequence in conversion input
/data/data/org.koreader.launcher/files # LANG=en_US.UTF-8  ./sdcv --data-dir /sdcard/koreader/data/dict  -nj test -u "adÃ©mie" --utf8-input --utf8-output
g_mkdir failed: Read-only file system
```
So, I guess we need to also `setlocale(LANG, "en_US.UTF-8");` ...

**Comment by Frenzie** [comment]
Incidentally, the glib mailing list contained a brief and incomplete overview of some ways in which Android is actively hostile.

https://mail.gnome.org/archives/gtk-devel-list/2011-March/msg00096.html
> General
>=======
>In a POSIXer's view, Android system is CRIPPLED: thus the porting of existing
>libraries onto it is TOUGH. Please have this in mind.
>The basic obstacles in porting:
>1.Android does not have or offers less/no access in its
>trimmed bionic C lib :
>1>No SYS V shm.h/sem.h
>2>Not standard pwd.h and getpwuid_r(),etc. methods
>3>No locale.h
>4>Not standard IP/IPV6 headers/support such as arpa/*.h ones
>5>Not standard pthread.                            
>6>No iconv  funcs.
>7>No intl/gettext funcs
>8>No i18n support and wchar_t.

**Comment by poire-z** [comment]
Hostile, that's the word :|
And we can't even use `setlocale(LANG, "en_US.UTF-8")`, it only accepts the LC_* constants.
I'd be tempted to try:
```
    g_setenv("LANG", "en_US.UTF-8", true);
    setlocale(LC_ALL, "en_US.UTF-8");
```
but I'm not even sure setting env variable from inside the program affetcts the program itself, only subprocesses.
Any chance you can reproduce this problem on your android emulator and try that kind of things?

**Comment by Frenzie** [comment]
I can probably give it a try tonight. All I need is a dictionary containing something like Académie?

Btw, it's simple enough to set up. All you need is way too many GB. I have a full 256 GB SSD dedicated to my Linux, not even for storage (except for some stuff like Dropbox), and I have a mere 6 GB free after creating one or two extra emulators and moving some 20 GB of recently ripped music over to storage. Android stuff in particular eats into it like crazy.

screenshot_2017-10-24_13-38-30

**Comment by poire-z** [comment]
Btw, about the slowness:
I did some quick timing with just one word on the emulator "epuisante":
80ms on our old sdcv fork fro june:
190ms on new scv0.5.2

When tweaking this in CMakeCache.txt:
```
//Choose the type of build, options are: None(CMAKE_CXX_FLAGS or
// CMAKE_C_FLAGS used) Debug Release RelWithDebInfo MinSizeRel.
CMAKE_BUILD_TYPE:STRING=
```
empty, as it is: 190ms
Debug: 190ms
Release: 90ms

So it may be that by default, a Debug build is made.
Dunno how to pass `Release` to the cmake build process, but I guess you may know :)
(Can you check how your benchmarks do with it?)

**Comment by Frenzie** [comment]
On the emulator I changed the default to a build with debugging symbols enabled in #3379. That doesn't affect anything else.

(But I'll double-check if it makes any difference to vanilla sdcv.)

**Comment by poire-z** [comment]
You'd need 3 dicts: 2 normal with ascii names, and 1 with a non-ascii name (the Académie one, or any chinese one). And in Installed dictionaries:
- enable 2, disable the one with non-ascii name: everything works, you get results from the 2 with ascii names
- enable 2, disable one of the 2 with ascii name: you get no result at all, because the -u "Académie" makes sdcv failt at startup while parsing command lines arguments

(not sure I want to dig much into android sdk world :)

**Comment by Frenzie** [comment]
> So it may be that by default, a Debug build is made.

On vanilla sdcv debug is indeed basically twice as slow. I would expect a no-debug build (`./kodev run --no-debug`; requires clearing out the sdcv executable and build first of course) to show the same kind of difference.

**Comment by poire-z** [comment]
But I worry this requires explicitely to write "`Release`" somewhere in the CMake stuff so it finds its way into CMakeCache.txt, otherwise, some slow build is made - on the build server.
Or is that all cmake business and is already dealt with by the build scripts or your `--no-debug` ?!

**Comment by Frenzie** [comment]
"None" and "Release" are the same on vanilla.

For us they're not the same because we pass our own CXX_FLAGS, which are our own versions of "Release" and "None" just without CMake messing it all up by passing random flags.

If you believe CMake-brainwashed people, the Right Way™ is to somehow "influence" CMake to do this or that. @#% that.

**Comment by poire-z** [comment]
OK, I trust you on this :)

It seems putting or not `g_setenv("LANG", "en_US.UTF-8", true)` in sdcv.cpp **does** change the behaviour on my linux when messing with LANG and LC_ALL. It's not a no-op as I expected, so I may give it a try for next nightly... _try4_ ...

**Comment by poire-z** [comment]
Confirming it's finally working on Android, and still is on Kobo.

**Comment by Frenzie** [comment]
Alright, cool.

I don't know what the right solution is on Kobo but perhaps @Dushistov would be open to the possibility of an `#ifdef __ANDROID__` around 

```C
    g_setenv("LANG", "en_US.UTF-8", true);
    setlocale(LC_ALL, "en_US.UTF-8");
```

(In fact I wouldn't mind that in our patch, ugly Android hack polluting behavior on every other platform. =P)

**Comment by Frenzie** [comment]
On the Lua side we default to LANG=C if nothing else is around in e.g. gettext. But I'm sure there were good reasons to pick glib.

In any case, there's a big difference between more or less sensibly limited (Kobo, Kindle, PocketBook too?) and lobotomized Android. :-)

**Pull request merged**
