### PR TITLE
bump cre: allow non-word chars in text selection

### LINKED ISSUE #4134: Highlighting doesn't include final punctuation mark
* KOReader version: `v2015.11-1803-ge37c345_2018-07-29`, but also in previous versions for as long as I remember
* Device: Kobo H2O

#### Issue
Highlighting doesn't include final punctuation mark

#### Steps to reproduce
Attempt to highlight a selection that ends with a full stop (period) or question mark.

#### Expected behaviour
The highlight should include the final punctuation mark.

#### Observed behaviour
The highlight stops short of the final mark, only encompassing the final word. To include the punctuation mark, you have to include the first word of the following sentence in the highlight. (This behaviour was also observed by someone else [here](https://www.mobileread.com/forums/showpost.php?s=28ac23836b9e09f8a54fc89af57585d1&p=3689677&postcount=12).)

### PR DESCRIPTION
**Pull request by poire-z**
By starting or ending text selection on a punctuation char, a quote or a paren..., these will now be included in the text selection and the higlighted text. Details and screenshots in https://github.com/koreader/koreader/issues/4134#issuecomment-428617973. Closes #4134.

bump crengine, which includes:
- Avoid wrap on a space before or after some specific chars https://github.com/koreader/crengine/pull/237

### CODE REVIEW

**Comment by ptrm** [comment]
This is so much what I wished to happen :D

The only thing that would make me even happier is an option to snap highlight to include punctuation at the end of words (like dots) - so on smaller fonts it would be easier to highlight the period marking the end of sentence inside a paragraph.

**Comment by poire-z** [comment]
> snap highlight to include punctuation at the end of words (like dots) 

That would be good if you are used to highlight sentences. But when you highlight just a few words, at end of a sentence (some expression, some person name to lookup later), you would not want that last dot.
So, dot. But no sense with commas/virgules :) so that's not all punctuations.
(And a dot would mess with dict lookup, so we'd need to remove it in that dict lookup code - I fixed text selection to not include punctuation at all 1 year ago, to get rid of that dict lookup filtering.)
Quite not obvious...

So, easier to read your fingers than read your mind :)
(I don't highlight much, but I see it's difficult to include the dot with a small font.)

**Comment by poire-z** [comment]
Just stumbed on #975: we could add buttons to push the selection one char left of right, one set for start, one set for end. In the "easier to read your fingers" spirit :)

**Comment by Frenzie** [comment]
I believe the suggestion there might be taken from Nickel.

**Comment by quowarranto** [comment]
Is anyone else still seeing this as a problem? Non-trailing punctuation still isn't captured by text-selection. Adjusting the editing buttons only allows you to select the next word, not the trailing punctuation.

**Comment by ptrm** [comment]
In the meantime, a change was implemented so that long press on the highlight edit buttons moves the highlight by a single char (incl. whitespace) :)
tempFileForShare_20210531-084212

**Comment by Frenzie** [comment]
@quowarranto 
> Is anyone else still seeing this as a problem?

You'd have to be a bit more specific than that. See the bug report template.

Peek 2021-05-31 08-48

**Comment by poire-z** [comment]
And for why punctuation is not auto-selected in highlights: https://github.com/koreader/koreader/issues/6217#issuecomment-636513399. Also https://github.com/koreader/koreader/issues/6473#issuecomment-668606042

**Pull request merged**
