### PR TITLE
Fix overlap in scroll mode for cre documents

### PR DESCRIPTION
**Pull request by poire-z**
Uses a setting `["copt_overlap_lines"] = N,` (default to `1`) for the number of text lines from previous page to show on next page (instead of a hardcoded and unscaled 20).
Takes footer height into account for overlap calculation and dim area.
Shows overlap only when changing pages (not when panning: it was changing at each pan step and it was real ugly).

It may help a bit with #3813 by just being more accurate, but there's still the misconfort of text lines being cut or dim'ed in the middle. But we can't do much more in scroll mode, when we have no knowledge of text rendering: we just cut slices of the whole document height.
(Doing overlap and dim in page mode would be a far more complex work!)

Also fix `ReaderFooter:getHeight()` which was returning a higher height than the real one since footer refactoring over the years.
**This may have some effect on PDF documents too.** (logically, it's better, but as I don't read much of them, I'm not sure if it has ever been noticed): when going to next page, a bit more of the previous page content was shown on the next page.
Taking footer size into account for PDF has been added by https://github.com/koreader/koreader/pull/2079. It may have been or not accurate at the time, I don't know. Since then, there's been many works on ReaderFooter, including a massive rework by @houqp. And it seems that now, the returned value is no more accurate.
With:
https://github.com/koreader/koreader/blob/c16cfa0e59c4207f50e9a62991edbc4d6274a9aa/defaults.lua#L133-L137
on my emulator (with a `scaleBySize()` factor of 1), we got `22` from `ReaderFooter:getHeight()`.
With this change, we get the expected (and accurate for overlap and dim area display for credocument) `14`.
The 22 comes from the DMINIBAR_FONT_SIZE = 14 , which probably makes the TextWidget have a real height of 22. This text is then put into a RightContainer of height 14, which must center it in the final container of height 14, so there was no visible problem.
But using this 22 for footer height is just wrong.

(Still to be tested by me on my device this evening.)

### CODE REVIEW

**Comment by Frenzie** [comment]
> I personally can't bear seeing the last line of previous page on the next page

I don't really want that either on PDF/DjVu. What's the effect of this exactly?

**Comment by poire-z** [comment]
I was going to say: the same as how overlap works with PDF ... but it seems to suck even more with PDF, got some pages with half the screen grayed out, some pages not (needs scroll mode + fit to content width to have the Overlap menu enabled).

So, with screenshots, for crengine with the default of copt_overlap_lines=1

Bottom of previous page:
<kbd>image</kbd>
Top of next page:
<kbd>image</kbd>

But it can also be ugly like that:
Bottom of previous page:
<kbd>image</kbd>
Top of next page:
<kbd>image</kbd>

**Comment by Frenzie** [comment]
But what's the difference with the current behavior? This footer_height thing is a good addition, but what's this opaque formula based on UI fonts? :-P

```lua
Screen:scaleBySize(self.ui.font.font_size * 1.1 * self.ui.font.line_space_percent/100.0) * self.overlap_lines
```

**Comment by poire-z** [comment]
The current behaviour uses a ridiculously low 20px (nearly invisible gray area on my kobo).
This formula is the same I used for the little marker on the side showling link target vertical position when following links.
And `self.ui.font` is actually `ReaderFont` :) and holds the credocument current font size and interline space. That formula was the best I got with these to get a default line height that works quite well (except on `<h1>` & friends, but well, we don't know if a line is a `<h1>` or else...)

**Comment by Frenzie** [comment]
So what about PDFs and DjVus that don't have a ReaderFont?

**Comment by poire-z** [comment]
When I wrote **This may have some effect on PDF documents too**, i meant that the `ReaderFooter:getHeight()` I changed is also used by ReaderPaging via:
https://github.com/koreader/koreader/blob/46a2571d3fba84793a7403227ec2dc7639fa8650/frontend/apps/reader/modules/readerzooming.lua#L249-L254
So my little change to getHeight making it returns 14 instead of 22 will have a small effect here on zoom_h.
Which should be the right thing. As I don't use ReaderPaging much, I don't know if this will have some visual effect, that could make people react.

**Comment by Frenzie** [comment]
Hm, the overlap is already too small on PDF but I guess that's talking about something else.

**Comment by poire-z** [comment]
Yes. On PDF, there is no hint about font size or line height to guess an overlap height adequate to the document content. It could only use a % of page or screen height.
(What i thought sucked with overlap on PDF is may be that it uses a % of page height, and when a page spans multiple screen, it feel strange as the overlap is there on the top part of page, and not there when the bottom of page is displayed on the next screen.. Strange for a newcomer, but may be it has some purpose).

**Pull request merged**
