### PR TITLE
ImageViewer: "best fit" to "scaled for best fit"

### PR DESCRIPTION
**Pull request by Frenzie**

### CODE REVIEW

**Comment by poire-z** [comment]
Fine with me.
Although it's a bit long and makes this button more dense than the 2 others ("rotate", "close").
"Scaled" ? "Scaled size" ? "Scaled to fit" ?
But as it's not the default, we won't see that often.

**Comment by retrue** [comment]
It is a bit offtopic and outside the scope of this PR. And I love the new image feature, but would it be possible to add scrolling bars to view images at scale 1:1 or zoomed that are bigger than the resolution of the screen?
I have a Kobo Mini, and even with this new feature, looking at maps in fantasy books is all but impossible.

**Comment by houqp** [comment]
+1 on scaled to fit . @retrue, please open an issue for this feature request :) If you comment it here, it will be very hard for us to track.

**Comment by Frenzie** [comment]
How about just scaled?

**Comment by poire-z** [comment]
Fine with me.

**Comment by poire-z** [comment]
Or just "Scale", as an action for the button ? ("Scaled" looks like it is saying the current image is scaled)

**Pull request merged**
