### PR TITLE
Base bump

### PR DESCRIPTION
**Pull request by NiLuJe**
Lotsa build-system tweaks, and the Wi-Fi scan rework

https://github.com/koreader/koreader-base/pull/1861
https://github.com/koreader/koreader-base/pull/1864
https://github.com/koreader/koreader-base/pull/1869
https://github.com/koreader/koreader-base/pull/1866
https://github.com/koreader/koreader-base/pull/1877
https://github.com/koreader/koreader-base/pull/1876
https://github.com/koreader/koreader-base/pull/1875
https://github.com/koreader/koreader-base/pull/1874
https://github.com/koreader/koreader-base/pull/1878
https://github.com/koreader/koreader-base/pull/1871
https://github.com/koreader/koreader-base/pull/1879 (Make Wi-Fi scanning reliable, re: #12236)
https://github.com/koreader/koreader-base/pull/1880
https://github.com/koreader/koreader-base/pull/1872
https://github.com/koreader/koreader-base/pull/1882
https://github.com/koreader/koreader-base/pull/1884
https://github.com/koreader/koreader-base/pull/1883

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12265)

### CODE REVIEW

**Comment by Frenzie** [comment]
Mac failure?

**Comment by benoit-pierre** [comment]
Yep, need to install meson, I'll make a PR.

**Comment by benoit-pierre** [comment]
This need to be part of this PR (for the `bincheck -> bininfo` change), @NiLuJe: can you add those 2 changes: https://github.com/koreader/koreader/commit/1576e9a8eb8aa1dc3ab6ec5964bc17e258ec6c47 & https://github.com/koreader/koreader/commit/e40a9babc015a872bc5cc9c2397f02f5d8826409.

**Comment by NiLuJe** [comment]
Progress: it built!

Bad news: libchekc is unhappy about SDL2 for.... weird ObjC reasons? o_O

**Comment by Frenzie** [comment]
See the base PR I just merged. Another base bump should do the trick.

**Pull request merged**
