### PR TITLE
Change skim mode dialog title

### PR DESCRIPTION
**Pull request by robert00s**
See: https://github.com/koreader/koreader/issues/3526#issuecomment-420940012
After changes:

### CODE REVIEW

**Comment by poire-z** [comment]
`Skim mode` doesn't sound right to me for a window title. (neither did the previous `Go to location`)
`Skim` alone may be better, or `Skim around`.
(But I didn't even know that word _skim_ before seeing it used in koreader :) so, I guess @Frenzie or @NiLuJe will come up with the right title for it)

**Comment by Frenzie** [comment]
Just skim would already be better.

**Comment by NiLuJe** [comment]
Yeah, probably, because `Skim To` doesn't sound right either ;).

**Comment by Frenzie** [comment]
Skim along
Skim document

**Comment by KenMaltby** [comment]
Since it is being delineated in pages, it makes sense to use that for the title and button.  It maybe because I need to update from 1836, but my current "Go to" and "Skim to" menu options have no long press action/info.  (I never had figured out what the "Location" button was to do, as opposed to a page number.  I thought it might be an attempt to have things like "Last page" or "TOC" or maybe "Map") The relative page jump options are neat, but I can't see it as very useful, especially with the Skim mode available.  Just my opinion.

**Comment by robert00s** [comment]
Ok, 
dialog title => Skim
Menu => Skim document

**Pull request merged**
