### PR TITLE
[chore] Proper plurals in CoverBrowser processing

### PR DESCRIPTION
**Pull request by Frenzie**
As reported by @lescheck on Weblate

> I think this should be in plural form (because of second line)

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/6483)

### CODE REVIEW

**Comment by Frenzie** [comment]
@poire-z I didn't really know how to trigger the message for testing. Still don't. ;-)

**Comment by poire-z** [comment]
I mean: is that normal ?:
`T(N_("One extracted successfully.", "%1 extracted successfully."), nb_success)`
to impose the 1/many distinction from english to all languages - and limit that to this 2 variant?
Will they be able to get "Uno extracted successfully", "Deuces extractodino successfully" and "%1 extradomultidino successfullo" ?

**Comment by Frenzie** [comment]
Yes, English is just taken as the default. The function selects the right plural from the options. In practice that ranges from… 0 to 5, possibly?

**Comment by poire-z** [comment]
> I didn't really know how to trigger the message for testing. Still don't. ;-)

File browser's "plus" menu I think, and "Extract and cache book information".

**Comment by poire-z** [comment]
So, "One extracted successfully." won't be proposed as-is to be translated ?
Only "%1 extracted successfully." will, where the translator can decide about the variations he needs?

**Comment by Frenzie** [comment]
It's presented in a language-appropriate manner, with the relevant number of fields for possible plurals.

Screenshot_2020-08-07_20-57-45

Screenshot_2020-08-07_20-59-19

**Comment by Frenzie** [comment]
Chinese doesn't have any, so for better or worse translators aren't bothered with the singular option at all:

Screenshot_2020-08-07_21-02-45

**Comment by Frenzie** [comment]
(German/English/Dutch/Spanish/French are the languages I've set up to be displayed simultaneously since they can inform my translation if they got around to it before me.)

**Pull request merged**
