### PR TITLE
[UX] Introduce Taps & Gestures menu

### PR DESCRIPTION
**Pull request by Frenzie**
This more logically groups together various settings related to taps and gestures.

Cf. <https://github.com/koreader/koreader/pull/4655#issuecomment-466808273>.

### CODE REVIEW

**Comment by poire-z** [comment]
Looks ok. (And as long there are only 9 items in gear and I can bring back Links> to it as the 10th via menusorter, I'm fine :)
Navigation to be renamed `Key navigation`, if it's all dependant of the device having keys?

**Comment by poire-z** [comment]
And I would move `Document>` (are it's mostly useless) below Taps&Gestures and Navigation, so Tap & Gestures is nearer Screen, as ... it's about screen too :)

**Comment by Frenzie** [comment]
Not just physical keys though. Besides, I don't think any of that stuff should be hiding out anymore. Instead of "back key" we can make it "back action" and we can bind the whole shebang to something like `left, down` by default.

**Comment by poire-z** [comment]
"Disable double tap" appears twice in the Taps & gestures menu, when in File Browser (but not when in Reader).

**Comment by Frenzie** [comment]
Not for me. Custom menu order issue perhaps? :-)

**Comment by Frenzie** [comment]
Oh, never mind. But you need to open a book and then the filemanager for it.

**Pull request merged**
