### PR TITLE
CI improvements

### PR DESCRIPTION
**Pull request by benoit-pierre**
Pendent of https://github.com/koreader/koreader-base/pull/1783.

Example CI runs:
- miss on both caches: [CircleCI](https://app.circleci.com/pipelines/github/benoit-pierre/koreader/208/workflows/9edc833b-50ad-4fab-bc62-d2b3beaf69d8/jobs/181) / [macOS](https://github.com/benoit-pierre/koreader/actions/runs/9069053825/job/24917755160)
- primary hit on ccache: [macOS](https://github.com/benoit-pierre/koreader/actions/runs/9069534031/job/24919290445)
- primary hit: [CircleCI](https://app.circleci.com/pipelines/github/benoit-pierre/koreader/209/workflows/5e213985-6a97-4a8d-9a51-83c26edeebea/jobs/183) / [macOS](https://github.com/benoit-pierre/koreader/actions/runs/9069534031/job/24920092051)

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11815)

### CODE REVIEW

**Comment by benoit-pierre** [comment]
Cf. https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token.

**Comment by yparitcher** [comment]
Pull requests default to read/write

**Comment by yparitcher** [comment]
See further down in that link

**Comment by benoit-pierre** [comment]
You mean `pull_request_target` events? Not `pull_request`. We don't have the former enabled.

**Comment by yparitcher** [comment]
Sorry for the noise :)

**Pull request merged**
