### PR TITLE
Backup bookmarks/highlights in incompatible engines

### PR DESCRIPTION
**Pull request by hius07**
Bookmark/highlight formats in crengine and mupdf are incompatible.
This backups bookmarks and highlights when opening the document with an incompatible engine.
Fix crash when opening a document with highlights with different engine.
Closes https://github.com/koreader/koreader/issues/8451.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8455)

### CODE REVIEW

**Review by poire-z — APPROVED** [review]

**Comment by poire-z** [comment]
I preferred the initial version (`bookmarks_rolling/paging` instead of `bookmarks_backup`), it may help to understand/recover in case of mess.

**Comment by hius07** [comment]
Even having the duplicated code?

**Comment by poire-z** [comment]
I don't mind it in this case (it's just 4 lines, and it's not strictly duplicated if one branch has `bookmark_paging` and the other `bookmark_rolling` :)
You could have a single branch and compute the bookmark backup name inside - but your initial code would probably still be more readable.

**Comment by hius07** [comment]
Okay, let it be.

**Comment by poire-z** [comment]
Oups, little conflict (with the just merged "inverse reading order" PR) in this one.
I let you resolve it via the "Resolve conflicts" button.

**Comment by poire-z** [comment]
I get a crash when switching EPUB with one cre highlight > Open with: MuPDF, make one highlight > Open normally with crengine:

```
./luajit: frontend/apps/reader/modules/readerview.lua:523: bad argument #1 to 'getPosFromXPointer' (string expected, got table)
stack traceback:
    [C]: in function 'getPosFromXPointer'
    frontend/apps/reader/modules/readerview.lua:523: in function 'drawXPointerSavedHighlight'
    frontend/apps/reader/modules/readerview.lua:473: in function 'drawSavedHighlight'
    frontend/apps/reader/modules/readerview.lua:196: in function 'paintTo'
    frontend/ui/widget/container/inputcontainer.lua:85: in function 'paintTo'
```
(Had to disable "cre call cache" in dev options to get this proper stack trace.)

My metadata.epub.lua, after closing MuPDF, ends up having:

```lua
    ["bookmarks_rolling"] = {
        [1] = {
            ["pos0"] = "/body/DocFragment/body/div/p[7]/text()[7].78",
            ["pos1"] = "/body/DocFragment/body/div/p[7]/text()[7].103",
            ["notes"] = "diffÃ©rents intermÃ©diaires",
            ["datetime"] = "2021-11-22 13:56:28",
            ["page"] = "/body/DocFragment/body/div/p[7]/text()[7].78",
            ["highlighted"] = true,
            ["chapter"] = "2 Histoire",
        },
    },
    ["bookmarks"] = {
        [1] = {
            ["pos0"] = {
                ["rotation"] = 0,
                ["zoom"] = 1,
                ["page"] = 6,
                ["y"] = 805,
                ["x"] = 542,
            },
            ["pos1"] = {
                ["rotation"] = 0,
                ["zoom"] = 1,
                ["page"] = 6,
                ["y"] = 823,
                ["x"] = 705,
            },
            ["notes"] = "Cette organisation",
            ["datetime"] = "2021-11-22 13:57:38",
            ["page"] = 6,
            ["highlighted"] = true,
            ["chapter"] = "2 Histoire",
        },
    },
    ["highlight"] = {
        [7] = {
            [1] = {
                ["pos0"] = "/body/DocFragment/body/div/p[7]/text()[7].78",
                ["pos1"] = "/body/DocFragment/body/div/p[7]/text()[7].103",
                ["datetime"] = "2021-11-22 13:56:28",
                ["text"] = "diffÃ©rents intermÃ©diaires",
                ["drawer"] = "lighten",
                ["chapter"] = "2 Histoire",
            },
        },
        [6] = {
            [1] = {
                ["pos0"] = {
                    ["rotation"] = 0,
                    ["zoom"] = 1,
                    ["page"] = 6,
                    ["y"] = 805,
                    ["x"] = 542,
                },
                ["pos1"] = {
                    ["rotation"] = 0,
                    ["zoom"] = 1,
                    ["page"] = 6,
                    ["y"] = 823,
                    ["x"] = 705,
                },
                ["pboxes"] = {
                    [1] = {
                        ["h"] = 43.583984375,
                        ["y"] = 797.98223876953,
                        ["w"] = 233.76000976563,
                        ["x"] = 534.11199951172,
                    },
                },
                ["datetime"] = "2021-11-22 13:57:38",
                ["text"] = "Cette organisation",
                ["chapter"] = "2 Histoire",
                ["drawer"] = "lighten",
            },
        },
    },
```
If feels that in:
https://github.com/koreader/koreader/blob/dcd34d409e6e3c3c73ced9dbf5d6996e66c657ec/frontend/apps/reader/modules/readerview.lua#L795-L807
`type(self.highlight.saved[`**1**`][1].pos0) == "table" ` the first `[1]` may not exist, and I made my first highlight on page 7 (may be you tested with making your highlights on page 1 :)
So, may be you should use `next()` to iterate and pick the first item, and may be also for the 2nd one ?

**Comment by hius07** [comment]
My bad! Sure, the first index is a page number, not just index. I'll fix it soonest, thank you.

**Pull request merged**
