### PR TITLE
OPDS catalog, Cloud storage: return from the deep

### PR DESCRIPTION
**Pull request by hius07**
When we are deep inside the OPDS catalog, we need to press return arrow many times to get to the first page.
Propose to hold the return arrow to get this.
Requires a small addition to the Menu.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7845)

### CODE REVIEW

**Comment by hius07** [comment]
If this is approved, the same can be added to Cloud storage.

**Comment by NiLuJe** [comment]
By "first page", you mean the first page of the current view, right, *not* the OPDS "root" (e.g., you lust of catalog).

Because if you do, that (e.g., jumping to the second oldest entry) only works if you have a *single* "view" in the path history, AFAICT.

**Comment by NiLuJe** [comment]
i.e., I don't think you can really do that in a consistent manner.

But you *can* easily and consistently jump back to the root, with a simple `while table.remove(self.paths)` loop, on the other hand ;).

**Comment by NiLuJe** [comment]
On the other hand (thinking out loud), *can* we actually have multiple views in the path history?

**Comment by NiLuJe** [comment]
(I haven't slept much, take all of that with a grain of salt ^^)

**Comment by hius07** [comment]
First page, I mean, is the main start page of the catalog.

**Pull request merged**
