### PR TITLE
Bump base

### PR DESCRIPTION
**Pull request by NiLuJe**
https://github.com/koreader/koreader-base/pull/1209

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/6758)

### CODE REVIEW

**Comment by poire-z** [comment]
Some unit test failing since this PR is merged (which looks totally unrelated...):
```
[ RUN      ] spec/front/unit/readerview_spec.lua @ 104: Readerview module should return and restore view context in scroll mode
10/06/20-04:18:17 INFO  setting zoom mode to page
10/06/20-04:18:17 INFO  setting zoom mode to pagewidth
10/06/20-04:18:17 INFO  setting zoom mode to page
ffi/blitbuffer.lua:987: bad argument #1 to 'sethook' (function expected, got number)

stack traceback:
        ffi/blitbuffer.lua:987: in function <ffi/blitbuffer.lua:974>
        ffi/blitbuffer.lua:1068: in function 'blitFrom'
        ffi/blitbuffer.lua:1176: in function 'colorblitFrom'
        frontend/ui/widget/textboxwidget.lua:800: in function '_renderText'
        frontend/ui/widget/textboxwidget.lua:170: in function 'init'
        frontend/ui/widget/widget.lua:48: in function 'new'
        frontend/ui/widget/infomessage.lua:128: in function 'init'
        frontend/ui/widget/widget.lua:48: in function 'new'
        ...
        /home/ko/.luarocks/share/lua/5.1/busted/block.lua:155: in function 'execute'
        /home/ko/.luarocks/share/lua/5.1/busted/init.lua:7: in function 'executor'
        /home/ko/.luarocks/share/lua/5.1/busted/core.lua:312: in function </home/ko/.luarocks/share/lua/5.1/busted/core.lua:312>

[  ERROR   ] spec/front/unit/readerview_spec.lua @ 104: Readerview module should return and restore view context in scroll mode (227.95 ms)
[----------] 3 tests from spec/front/unit/readerview_spec.lua (1847.47 ms total)
```

**Comment by NiLuJe** [comment]
@poire-z: Locally or in the CI?

**Comment by NiLuJe** [comment]
Probably yet another random test failure, it passes locally.

lj-sqlite3 is still hilariously broken in busted, though, so any test that touches it is completely unreliable.

**Comment by poire-z** [comment]
In the CI, when checking a proposed PR, and in the commit list after merge.

**Comment by NiLuJe** [comment]
Yep, saw that after my message.

Still passes locally, though ^^.

```[       OK ] ./spec/front/unit/readerview_spec.lua @ 104: Readerview module should return and restore view context in scroll mode (15.16 ms)
[----------] 3 tests from ./spec/front/unit/readerview_spec.lua (156.37 ms total)

[----------] Global test environment teardown.
[==========] 3 tests from 1 test file ran. (156.43 ms total)
[  PASSED  ] 3 tests.
```

**Comment by Frenzie** [comment]
> Probably yet another random test failure, it passes locally.

Dunno what you mean by random exactly, but it looks like the past few commits have been consistently broken.

**Comment by NiLuJe** [comment]
I vaguely remember seeing this one erratically faceplant on the CI in the past. But, yeah, seems consistant since the LuaJIT bump.

Cannot reproduce it locally, the the traceback makes no goddamn sense.

**Comment by Frenzie** [comment]
I can confirm it works for me too. grmbl

**Pull request merged**
