### PR TITLE
fix statistics translation

### PR DESCRIPTION
**Pull request by chrox**

### CODE REVIEW

**Comment by Frenzie** [comment]
Btw, should https://github.com/koreader/koreader/blob/9fd4ee8eaca73541583be7e59aba547a3a9682c2/plugins/statistics.koplugin/main.lua#L294 be translatable?

**Comment by houqp** [comment]
Nop, and we should be using a proper ui widget for separation line instead since hard coded text is not responsive to different device size.

**Comment by Frenzie** [comment]
I hadn't even thought of that yet. It just raised my eyebrows to see it show up on Transifex. :)

**Comment by Frenzie** [comment]
@apletnev Since you're working on this (or at least related stuff) right now, would you mind looking into using e.g. LineWidget there?

**Comment by apletnev** [comment]
@Frenzie yep, will look at it

**Comment by Frenzie** [comment]
Neat. :-)

**Pull request merged**
