### PR TITLE
keyvaluepage: fix corner-case alignment bug

### PR DESCRIPTION
**Pull request by weijiuqiao**
Corner(or edge?) case: https://github.com/koreader/koreader/pull/9672#issuecomment-1494867499

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10326)

### CODE REVIEW

**Comment by poire-z** [comment]
It solves the sample case I managed to reproduce on the emulator and gave info about in that post.
But it does not solve the issue with that same book on my Kobo :/ It still looks like the screenshot I put at [that comment](https://github.com/koreader/koreader/pull/9672#issuecomment-1494867499).
If I can put some additional logging to help understanding what happens, you can give me some patch with them.

**Comment by poire-z** [comment]
> I have the new commit starting from values and work through keys. It should solve the problem

It indeed does solve it on my Kobo ! :)

> but I'm not sure if it will introduce other strange behavior.

No idea :/ Looking at Book information for a dozen of books, and nothing looks odd nor bad.

> Another solution is to compute all "cuts" and use the smallest one, but it seems less interesting...?

I really have no idea - I'm happy you're still around and that I never had to become familiar with your KVPage algorithm :) And I still don't want to :) so trusting you on all this.

**Comment by poire-z** [comment]
Things looks a bit odd in Dictionary lookup history when browsing pages, with the values positionning being different on each page.
But it is already behaving this way without this PR.
Only one thing different I noticed with this PR, is that on 1 of the 20 pages I browsed, values are/look right aligned ! (On a page with multiple kv-spanning book titles, some of them being long and truncated. But this does not happen on all pages with such "multiple kv-spanning long book titles"...)
Is there an edge situation where the alignment may switch to right?

**Comment by weijiuqiao** [comment]
It looks the current algorithm will miss some edge cases. Maybe we should just use the less fun but theoretically robuster method. Let me make a commit and you can help check if the edge case's been dealt with.

**Comment by weijiuqiao** [comment]
Also I took the liberty to ignore any pairs where the value is `""` when computing the alignment, since they seem to be intended more as a title and should not interfere here? (Saw some not-the-best-looking cases in `Download  dictionaries >`)

**Comment by poire-z** [comment]
Thanks!
Tested, and it looks ok to me now - both Dict lookup history and my Book info issue - as well as other kvpages I looked at.

**Pull request merged**
