### PR TITLE
CoverBrowser: list mode: limit font size of components

### PR DESCRIPTION
**Pull request by poire-z**
Should trigger when per-page <= 6/7, avoids authors and titles to become too big.

Discussed in #7278, a so-called "discussion" that this can't close. Trying it: Closes #7278.
Screenshots before/after in #7278 (good luck finding them in that useless piece of shitcussion).
(Changes the max for file info on the right from 16 to 18 as requested in there - we'll see if that feels too big.)

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7324)

### CODE REVIEW

**Review by NiLuJe — APPROVED** [review]

**Comment by poire-z** [comment]
https://github.com/koreader/koreader/discussions/7278#discussioncomment-391050
> Finally, I will agree with you. I tried the info size 14, 18 and I realized what you said, that it will take valuable space from title/ authors. 

Waiting for more feedback before changing 18 to 16.

**Comment by NiLuJe** [comment]
@poire-z: FWIW, I think the only platform where I tweak the defaults are on Android (tall phone), and nothing jumped out at me (but I'm still at something like 12 items per page, though).

**Comment by poire-z** [comment]
Yes, it should trigger only on 4-6 items per page. Try it on your tall phone and say if, pretending you like that view, you'd be fine with the font size of the size/format/progress (and so, smaller width for author titles, and so, possible really smaller font size for them), or if you'd wish it smaller.
Just tried it on my (not tall, small) phone, and I'm somehow OK with the 18 (should give the same size as the "path" in the top title).

**Comment by NiLuJe** [comment]
Yep, looks fine at 6 (in detailed list view), the date font size essentially matches the one for the author/series lines.

I mean, there's, obviously, a lot of vertical space left blank, but it works, I think?

**Comment by NiLuJe** [comment]
Slightly more marked difference at 4, but still works.

(Note that I possibly already have smaller font sizes, because I have the Series on a dedicated line).

**Pull request merged**
