### PR TITLE
fix continued mode, goto statistics page crashed

### PR DESCRIPTION
**Pull request by greatyingzi**
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11279)

### CODE REVIEW

**Comment by greatyingzi** [comment]
crash log
`
12/27/23-13:14:17 DEBUG AutoSuspend: onInputEvent
12/27/23-13:14:17 DEBUG AutoTurn: onInputEvent
12/27/23-13:14:18 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: -1, time: 1703654058.019338
12/27/23-13:14:18 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1703654058.019338
12/27/23-13:14:18 DEBUG slot 0 in tap state...
12/27/23-13:14:18 DEBUG Contact:handleDoubleTap: single tap detected @ 856 950
12/27/23-13:14:18 DEBUG AutoSuspend: onInputEvent
12/27/23-13:14:18 DEBUG AutoTurn: onInputEvent
./luajit: plugins/statistics.koplugin/main.lua:1634: attempt to perform arithmetic on local 'current_page' (a nil value)
stack traceback:
        plugins/statistics.koplugin/main.lua:1634: in function 'getCurrentStat'
        plugins/statistics.koplugin/main.lua:1308: in function 'callback'
        frontend/ui/widget/touchmenu.lua:921: in function 'onMenuSelect'
        frontend/ui/widget/touchmenu.lua:188: in function 'handleEvent'
        frontend/ui/widget/container/inputcontainer.lua:262: in function 'handleEvent'
        frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
        frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
        frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
        frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
        frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
        frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
        frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
        frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
        frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
        frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
        frontend/ui/uimanager.lua:907: in function 'sendEvent'
        frontend/ui/uimanager.lua:53: in function '__default__'
        frontend/ui/uimanager.lua:1436: in function 'handleInputEvent'
        frontend/ui/uimanager.lua:1534: in function 'handleInput'
        frontend/ui/uimanager.lua:1578: in function 'run'
        ./reader.lua:289: in main chunk
        [C]: at 0x00013ebd
`

**Comment by mergen3107** [comment]
When does this happen?
Do you have a related issue?
What's the device? :D

**Review by hius07 — APPROVED** [review]

**Comment by greatyingzi** [comment]
> When does this happen? 什么时候会发生这种情况？ Do you have a related issue? 您有相关问题吗？ What's the device? :D 设备是什么？ ：D
kpw4, koreader version is v2023.10-73-gb949d07f4_2023-12-25
image

**Comment by mergen3107** [comment]
Thanks! What was the action you did that made KOReader crash?

**Comment by greatyingzi** [comment]
> Thanks! What was the action you did that made KOReader crash?谢谢！您执行了什么操作导致 KOReader 崩溃？

read epub book in continue mode, than open statistics page, it crashed. and if found there are some closed issue like this, I fixed by same way.

**Comment by greatyingzi** [comment]
> When does this happen? 什么时候会发生这种情况？ Do you have a related issue? 您有相关问题吗？ What's the device? :D 设备是什么？ ：D



> Thanks! What was the action you did that made KOReader crash?谢谢！您执行了什么操作导致 KOReader 崩溃？

read ebook in continue mode, than enter statistics page, it crashed. I found some closed issue like this, I fixed it by the same way.

**Comment by mergen3107** [comment]
Thank you

**Pull request merged**
