### PR TITLE
[feat] Make touch work on the H2O2

### PR DESCRIPTION
**Pull request by cairnsh**

### CODE REVIEW

**Comment by Frenzie** [comment]
@poire-z Any further comments?

**Comment by Frenzie** [comment]
@cairnsh Well, this is interesting.

> cairnsh committed a minute from now 

screenshot_2018-03-04_18-55-30

My time is good, check https://time.is/ :-P

**Comment by poire-z** [comment]
Looks fine.
I have never really looked at this part of the code :) and I don't really want to :)
Just asking to be sure as you read and undserstant it: this new function `table.insert()` stuff, are we sure it's always reset at some point, and that we don't go inserting many stuff that would not be consumed on other devices without snow_protocol ?

**Comment by Frenzie** [comment]
It's just some refactoring, not a new function as such.

**Comment by Frenzie** [comment]
Thanks @cairnsh! You're cola from the forum I presume? :-)

**Comment by cairnsh** [comment]
This code should do the exact same thing as before if snow_protocol is not set. Whether that's the right thing, I don't know! It's bothering me that cur_slot doesn't get reset.

self.MTSlots gets reset on line 433 every time there's an event with ev.type == EV_SYN and ev.code == SYN_REPORT. (And if snow_protocol is set, then it also gets reset on line 422 right before we put all the slots in it.) I think there's always an event like that at the end of each group of events, and if so then it is getting reset at least once per call to this function.

**Comment by poire-z** [comment]
Thanks for the explanation.
I just had a quick check on my gloHD with these 2 commits, and everything works perfectly as before :)

**Comment by Frenzie** [comment]
> I think there's always an event like that at the end of each group of events, and if so then it is getting reset at least once per call to this function.

Yes, if a (multi)touch driver didn't emit EV_SYN it'd be quite simply broken. All of our current Kobo workarounds are… special but they're more like an oddly individual take on driver behavior than something fundamentally different. Whether you drive on the left or right side of the road makes no difference in principle, but making a car without breaks is just broken. :-P

**Pull request merged**
