### PR TITLE
MuPDF 1.12

### LINKED ISSUE #3519: Updating MuPDF
What would it involve to update MuPDF to the latest version?

The current version fails to load HTMLs because the pdf_lookup_builtin_font call in the fz_load_html_font function does not set the size and freetype fails to load the font.

I started expirementing with MuPDF to display HTML dictionaries.

This is related to #1776.

### PR DESCRIPTION
**Pull request by TnS-hun**
Needed for https://github.com/koreader/koreader-base/pull/577.
Closes #3519.

### CODE REVIEW

**Comment by TnS-hun** [comment]
The koreader-base submodule now points to the latest version.

**Comment by Frenzie** [comment]
Thanks!

**Comment by poire-z** [comment]
I hadn't updated my kobo since MuPDF 1.12 went in, I just tried it now and installed latest nightly, and things were quite bad:
Some locks up when opening a fully colored pdf.
Some blank page instead of a colored first page (but following b&w pages were ok).
All blank pages when re-opening a previously opened document that was ok (with or without clearing readers's cache).
Locks up when coverbrowser pluging is indexing (getting cover image) some pdf.
(These locks up needing a long power button press to reboot).

(Do other Kobo / Kindle users experience this too? Or is it just me?)

All with this kind of stacktraces:
```
warning: lcms error: Couldn't link the profiles
error: cmsCreateTransform failed
warning: unrecoverable error; ignoring rest of page
warning: lcms error: Couldn't link the profiles
error: cmsCreateTransform failed
./luajit: ./ffi/mupdf.lua:65: could not run page: cmsCreateTransform failed (2)
stack traceback:
        [C]: in function 'error'
        ./ffi/mupdf.lua:65: in function 'merror'
        ./ffi/mupdf.lua:518: in function 'run_page'
        ./ffi/mupdf.lua:557: in function 'draw_new'
        ./ffi/mupdf.lua:526: in function 'draw'
        frontend/document/document.lua:365: in function 'renderPage'
        frontend/document/koptinterface.lua:264: in function 'getCoverPageImage'
        plugins/coverbrowser.koplugin/bookinfomanager.lua:404: in function 'extractBookInfo'
----
warning: lcms error: Couldn't link the profiles
error: cmsCreateTransform failed
./luajit: ./ffi/mupdf.lua:65: could not run page: cmsCreateTransform failed (2)
stack traceback:
        [C]: in function 'error'
        ./ffi/mupdf.lua:65: in function 'merror'
        ./ffi/mupdf.lua:518: in function 'run_page'
        ./ffi/mupdf.lua:557: in function 'draw_new'
        ./ffi/mupdf.lua:526: in function 'draw'
        frontend/document/document.lua:365: in function 'renderPage'
        frontend/document/document.lua:389: in function 'drawPage'
        frontend/document/koptinterface.lua:401: in function 'drawPage'
        frontend/apps/reader/modules/readerview.lua:301: in function 'drawScrollPages'
        frontend/apps/reader/modules/readerview.lua:168: in function 'paintTo'
```

If I add `hasColorScreen = yes` in `frontend/device/kobo/device.lua`:
```lua
 local Kobo = Generic:new{
     model = "Kobo",
     isKobo = yes,
     isTouchDevice = yes, -- all of them are
+    hasColorScreen = yes,
```
the above problems seemed to have disappeared... edit: for some time, still getting these problems after a restart or reboot... :(

No problem on the emulator if I comment `hasColorScreen = yes`, but framebuffer_SDL2_0.lua always uses a RGB32 bb anyway.
 
Looks like mupdf does not like greyscale blitbuffer/devices, or it needs some other works (color profiles?!).
@TnS-hun : did you see that kind of stacktraces while developping it? Any idea?

(Not enabling hasColorScreen for greyscale eInk devices was more a matter of saving memory by using smaller blitbuffer, so it can still be part of a solution to enable it for all devices, but it looks like not sufficient...)

**Comment by Frenzie** [comment]
The few PDFs I tried seemed fine, odd.

**Comment by TnS-hun** [comment]
> The few PDFs I tried seemed fine, odd.

Same here but I only tested with the emulator. Is there any way to reproduce this with the emulator by somehow forcing the blitbuffer to be 8-bit grayscale?

**Comment by poire-z** [comment]
I didn't manage to make the emulator work in greyscale, and I couldn't get any of the cms/lcms warning/error outputs.
@Frenzie : you don't have these warnings at all in your crash log when opening colored pdfs (comics...) ?

And i'm not even sure it's related to greyscale/color, i get all the above strange behaviours with color enabled or not, and none of them is 100% reproducible (meaning: bad things happen all the time, but not always the same one before another one).

I tried to remove these files in my kobo root's /lib/
```
/lib/liblcms.so -> liblcms.so.1.0.18
/lib/liblcms.so.1 -> liblcms.so.1.0.18
135932 May  1  2013 lib/liblcms.so.1.0.18
```
in case mupdf would use these system libs and there would be incompatibliites, but it changed nothing...

I tried my 3 colored pdfs with [plato](https://github.com/baskerville/plato/), which uses mupdf 1.12, and they load fine. I tried putting its libmupdf.so into koreader/libs/, but koreader does not like it :)

But i see 3 weeks ago, @baskerville updated its [patch/build of mupdf ](https://github.com/baskerville/plato/tree/master/thirdparty/mupdf) with:
- `-DNO_ICC` added to `CFLAGS`
- explicite non-inclusion of `color-lcms.o` into libmupdf.so , but still keeping `-L../lcms2/src/.libs -llcms2`

@baskerville : could you tell us why you did that? Did you get the kind of errors i mentionned a few posts above?

May be we could try to just add **-DNO_ICC** to `CFLAGS` , but I don't know what feature/accuracy we would really lose.

That [color management ](http://git.ghostscript.com/?p=mupdf.git;h=dd58ea5e2ff7e6b61cc5a5b6fd950fb62e92b8be)has been added this year to mupdf, it was not there in our mupdf 1.8.
It was for this [bug report](https://bugs.ghostscript.com/show_bug.cgi?id=697501), which is about color (I remember @TnS-hun mentionned some color differences some weeks ago, but I don't know much about color stuff).

**Comment by Frenzie** [comment]
@poire-z I haven't been able to look at my error.log yet but I mean that stuff seems to just open. Anyway, I'm back home now so I might check it out tomorrow.

**Comment by baskerville** [comment]
*mupdf* requires a [custom fork](https://github.com/ArtifexSoftware/thirdparty-lcms2/blob/lcms2-art/doc/WhyThisFork.txt) of lcms2!

- I wanted to build *mupdf* as a dynamic library and the build process was failing because of _lcms2_.
- I discovered, by chance, that the *lcms2* dependency could by disabled with `-DNO_ICC`.
- I don't think that color management makes any sense with 16 levels of gray.

`-L../lcms2/src/.libs -llcms2` is a leftover and shouldn't be there.

**Comment by poire-z** [comment]
Thanks for your answer.

I rebuilt mupdf on the emulator, with (testing with `$(if $(SDL)` before making a PR with `$(if $(KOBO)` instead) this addition to base/Makefile.third:
-DXCFLAGS="$(CFLAGS) -DNOBUILTINFONT **$(if $(SDL),-DNO_ICC,)** -I$(JPEG_DIR)/include -I$(FREETYPE_DIR)/include/freetype2 -I$(ZLIB_DIR) -I$(MINIZIP_DIR)" \

It seems to work fine, but I have no real eye for color changes, so...
BUT my surprise was that the corrupted image I mentionned in https://github.com/koreader/koreader-base/pull/579 is now gone, and this image displays OK !
So, I'm not sure `-DNO_ICC` should be set only for Kobo, as it may workaround bugs for all platforms (dunno if that lcms2 is still experimental).

Should I quickly make a PR with an unconditional `-DNO_ICC` ?

**Comment by poire-z** [comment]
Confirming that everything seems to work fine now on my Kobo after #3569 !
No more freeze/crash/blank page, no error/warning logged when opening these colored PDF.

The only logs are when viewing that formerly corrupted image, which is now displayed correctly:
```
error: ICC Profiles not supported in NO_ICC build
warning: could not load ICC profile in JPEG image
```

**Pull request merged**
