### PR TITLE
add square svg with more padding

### PR DESCRIPTION
**Pull request by pazos**
To be used in flathub, following their guidelines: https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines/#app-icon

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11848)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by Frenzie** [comment]
True, cutting it off a bit would probably be nicer.

**Comment by pazos** [comment]
I've stretched all layers together to fill the square template provided by flathub.

Maybe this is any better?

original, streched: 


streched, tweaked (no longer follows original):


square-3

vs:

**Comment by benoit-pierre** [comment]
My vote: `square-2.svg`.

**Comment by Frenzie** [comment]
Agreed on 2. It'd be great if the top and bottom of the letters could match the straight line but not the biggest deal for now if that's hard to do. (Or if you have some patience I can check in Inkscape.)

**Comment by pazos** [comment]
> Agreed on 2. It'd be great if the top and bottom of the letters could match the straight line but not the biggest deal for now if that's hard to do. (Or if you have some patience I can check in Inkscape.)

I'm bad at maths and I'm bad at graphics, which makes me terrible at vector graphics :)

But I'm very good at patience :). Here's the stretched image overlapped with flathub square/round guide:

koreader-square

**Comment by Frenzie** [comment]
> But I'm very good at patience :).

Turns out it won't be today, so a little more patience. :-P

**Comment by Frenzie** [comment]
@pazos Here's a quick attempt, if I understood what's desired correctly.

In short, I selected the top four nodes for each object and pressed the down key a few times. Then I dragged the letters down a bit.
koreader-logo-square

koreader

**Comment by Frenzie** [comment]
koreader-logo-square-more-k

**Comment by Frenzie** [comment]
Yeah, it's better. No squishing and legible K. It seems good to me.

**Comment by pazos** [comment]
I'm sorry. The last image doesn't work. Letters don't fit in the square. You can see the K above the background and the rest of the O  below

**Comment by pazos** [comment]
Maybe we just don't need another icon. Our current one doesn't follow guidelines but look pretty ok

**Comment by pazos** [comment]
Here's another quick one, trying to fit in the square:

ko

**Comment by Frenzie** [comment]
> Maybe we just don't need another icon. Our current one doesn't follow guidelines but look pretty ok

I prefer some individuality in icon shapes really. Something that deals in books or phones or whatever shouldn't look like a square.

> I'm sorry. The last image doesn't work. Letters don't fit in the square. You can see the K above the background and the rest of the O below

I'll add a mask if desired.

**Comment by Frenzie** [comment]
Also see https://inkscape-manuals.readthedocs.io/en/latest/clipping-and-masking.html since I probably won't have time tonight anyway.

**Comment by pazos** [comment]
@Frenzie: Still not in a hurry. I'm going to close this PR, feel free to push a change if https://github.com/flathub/rocks.koreader.KOReader/issues/34#issuecomment-2105203105 bothers you enough.

I think I'm fine with the current icon :)

**Pull request closed without merging**
