### PR TITLE
Update AutoWarmth state on resume

### LINKED ISSUE #4895: Natural light: previous session's light for half a second when starting device
* KOReader version: v2019.04-5-g69e3830_2019-04-09/  
* Device: KA1

#### Issue
It has been like this since some days (or maybe weeks).

I use the auto warmth feature. 

When I start the device nowadays, it seems like it has the previous session's level of natural light for maybe a half second before it finds the correct light.

So for example: if I put the device to sleep in the evening when I have a high level of warmth light, and then start the device in the morning (when the warmth should be 0), it has yesterdays light for like half a second before it jumps to the correct non-warmth light.

### PR DESCRIPTION
**Pull request by NiLuJe**
Regression since #4871
Fix #4895

### CODE REVIEW

**Comment by NiLuJe** [comment]
Hmm, potentially incomplete, because sysfs_light isn't in sync w/ powerd

**Comment by NiLuJe** [comment]
I don't use the feature, so I can't definitely say if this actually fixes the bug, but at least it doesn't crash ;p.

**Comment by NiLuJe** [comment]
That final commit is a bit hackish, but I really didn't feel like adding yet another has* field to device. Thoughts?

**Comment by Frenzie** [comment]
Yeah, I've faced the same dilemma a few times. This one seems reasonable enough.

**Comment by NiLuJe** [comment]
I might actually need it somewhere else to properly fix this on devices with a mixe,r though, so, stay tuned... :).

**Comment by NiLuJe** [comment]
There, that should do it ;).

**Pull request merged**
