### PR TITLE
Annotations: pageno honors reference pages and hidden flows

### PR DESCRIPTION
**Pull request by hius07**
Closes https://github.com/koreader/koreader/issues/12209.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12214)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by hius07** [comment]
@noembryo excuse me, I forgot to ask you about this change.
The `pageno` annotation field now can contain a usual page number, or a reference page, or a page number in a non-linear flow (that is not a number actually), depending on a user's settings.
So it can be either of a "number", or of a "string" type.
Does it break anything in KOHighlights?
If yes, I will consider other solution, to allow users to see their preferable format in the KOReader Exporting plugin.

**Comment by noembryo** [comment]
Hmm.. I remember something about this was discussed some time ago.

From what I see here , I expect the `pageno` to be a "string" type but convertable to "int", because I use this to roughly calculate the annotation's position in the book in case of different total pages for the same book (from different devices).

Perhaps it would be more convenient to have another key for `ref_pegeno` along the standard `pageno`, and use whenever is needed?

**Comment by hius07** [comment]
> Perhaps it would be more convenient to have another key for `ref_pegeno` along the standard `pageno`, and use what ever is needed?

Yes, that's what I'm thinking of. I will revert the `pageno`, no worry on your side.

**Comment by noembryo** [comment]
Thank you.. 👍

**Comment by noembryo** [comment]
@hius07 Sorry to bother you again about the page numbers 😩, but there is a [feature request](https://github.com/noembryo/KoHighlights/issues/38) for KOHighlights, about the newly added (with a user patch) synthetic (logical?) pages.
From what I was able to understand, it uses the CREngine to calculate the position based on the text of the epubs' files.
KOHighlights can't make this calculation, so I was wondering if there is a way, if someone already made this calculation, to have a key with this number in the annotation's info.
I know that it gets bloated with all those different page numbers, but I can't think of any other way to do it.

Of course, I can understand if this is too much to ask, but I had to try.. 😉
🙏

**Comment by hius07** [comment]
The answer is in the https://github.com/koreader/koreader/issues/9020#issuecomment-2045865939.
Is it the time to have this feature in the core already? Interested users may comment and vote there.
(Once it's in the core, we shall keep the `pageno` field always actual)

**Comment by hius07** [comment]
BTW, you may look at the `pageref` field. Maybe it can help somehow.
https://github.com/koreader/koreader/blob/6de2a59bd88ec67511e269191addda5e1af2c588/frontend/apps/reader/modules/readerannotation.lua#L59
https://github.com/koreader/koreader/blob/6de2a59bd88ec67511e269191addda5e1af2c588/frontend/apps/reader/modules/readerannotation.lua#L410-L413

**Comment by noembryo** [comment]
From what I see, `pageref` has the reference numbers if a book has already calculated them.
But not with the calculated "synthetic" pages (from the user patch), right?

**Comment by hius07** [comment]
I haven't tried the patch myself. If a user with the patch sees the correct (synthetic) page numbers in the Bookmark list, I think they are available in `pageref`.
He can check the page numbers in Exporter plugin (to any format). The plugin uses `pageref` if it exists.

**Comment by noembryo** [comment]
> If a user with the patch sees the correct (synthetic) page numbers in the Bookmark list, I think they are available in pageref.

You're right, there are, so I can support them too.. 🍾 
Not if there're not convertible to `int` of course, but I think, most of the time will be.
I wonder if it needs to be selectable or not.. 🤔

**Comment by edo-jan** [comment]
> I haven't tried the patch myself. If a user with the patch sees the correct (synthetic) page numbers in the Bookmark list, I think they are available in `pageref`. He can check the page numbers in Exporter plugin (to any format). The plugin uses `pageref` if it exists.

@hius07 I have  the "logical page numbers" user patch installed in version 2024.07 Unfortunately, the `pageref` keys are only present in metadata if the epub in question has **publisher page numbers** embedded. The books without the publisher page numbers correctly show the "synthetic" pages with the user patch, when "Use reference page numbers" is checked.  However, for such books the `pageref` is not in the metadata file. It would be really useful if the pageref could be used to store the logical pages if the publisher pages are not provided.

**Comment by hius07** [comment]
> installed in version 2024.07 Unfortunately, the `pageref` keys are only present in metadata if the epub in question has **publisher page numbers** embedded.

Try the recent nightly build.

**Comment by edo-jan** [comment]
> > installed in version 2024.07 Unfortunately, the `pageref` keys are only present in metadata if the epub in question has **publisher page numbers** embedded.
> 
> Try the recent nightly build.

Version 2024.07-123 now uses `pageref` for logical page numbers! 🤩🤩🤩 Thank you very, very much!

**Pull request merged**
