### PR TITLE
Simplify isWifiOn on Kobo

### PR DESCRIPTION
**Pull request by NiLuJe**
Don't fork for lsmod + grep, we can perfectly well parse /proc/modules
ourselves ;).

c.f., https://github.com/koreader/koreader/pull/5203#issuecomment-521277628

### CODE REVIEW

**Comment by Frenzie** [comment]
And I'm not really sure when we gained this function, but this means the icon can also be shown on Kobo.

**Comment by NiLuJe** [comment]
Yeah, I vaguely checked other patforms:

Kindle: lipc via dbus or fork(), meh :/
Cervantes: sysfs, but only true if the *interface* is up. Sill, probably okay for the icon ;).
PB: InkView. Possibly perfectly fine, too, but here be dragons.
Sony: double fork(), meh :/

**Comment by pazos** [comment]
> Cervantes: sysfs, but only true if the interface is up. Sill, probably okay for the icon ;)

Yep, on cervantes we report isWifiOn as true [based on 2nd layer](https://en.wikipedia.org/wiki/Data_link_layer) according to IEEE 802.11 wireless LAN protocol.

This way wifi is on even on networks where we cannot ping remote locations but can still access to LAN services.

The reason we don't care about modules is that having them loaded doesn't mean that the interface is associated with an AP. For instance isWifiOn will return false if the interface is up but wpa_supplicant failed to associate.

**Comment by NiLuJe** [comment]
Yep, whereas I needed isWifiOn as-is on Kindle to deal with crappy launchers that left WiFi in a broken/dangerous/crashy state ;).

**Pull request merged**
