### PR TITLE
Update Greek keyboard

### PR DESCRIPTION
**Pull request by ichnilatis-gr**
Update the Greek keyboard to the new keyboard layout.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10734)

### CODE REVIEW

**Comment by ichnilatis-gr** [comment]
> No update to el_popup.lua, or you forgot to add it ?

I've done it, but I didn't managed to add it to this one. How can it been done? I made a separate PR.

**Comment by poire-z** [comment]
Not using github web.
Pinging @hius07 for advices if there's a trick adding other files.

**Comment by hius07** [comment]
Just go to
https://github.com/ichnilatis-gr/koreader/tree/patch-2
choose another file and press the Pen button to edit it.

**Comment by ichnilatis-gr** [comment]
Thank you. Should I do it now and delete the other PR or this is for another time?

**Comment by ichnilatis-gr** [comment]
Done!

**Comment by poire-z** [comment]
I just had a quick check before merging - no problem noticed.

I'm not that familiar with Greek letters, but looking at the popups on the lowercase letters, I see that there are often a latin letter equivalent to that greek letter, in the popup north west key - but not always, sometimes it's the north key. Any reason ?

image
image image
but:
image image image image

Any other specific rules you had in mind and followed when making that keyboard ?
(ie. we have one on the EN or FR keyboard that é and è are such that your finger swipe gesture has to follow the accent direction image :) Dunno if that makes sense with Greek.

If yes, please detail them here, so our 3 or 4 other Greek users can know them and figure out why your layout is at it is :)

**Comment by ichnilatis-gr** [comment]
Thank you for your check.
Regarding the Latin letters in popups, I put them to correspond to the English keyboard where there are Greek letters in popups. And, to be honest, I didn't always make sure that I put them in the same position, which is also true for the Greek letters in the English keyboard.
As you might have guessed, I also like consistency, so I will put all the English letters in the popup north key.

Regarding the letters with accents, yes, it makes sense with Greek to follow the direction of the accents, and that's what I did when I first arranged the poppups to meet the needs of polytonic Greek. But in use, I found that it was more convenient to have the letter with the acute accent (tonos) on the right key, as it's a short gesture that we can make without waiting for the popup to open. After all, it's the only accent mark used in the monotonic Greek , which is mostly used today. So I've put the letters with grave and acute accent in the left and right popup keys respectively and the letters with breathings (which are used in the polytonic Greek) in the north left and north right popup keys. In the rest keys I've put some other combinations. However there are more combinations possible that can be made with the help of the combinations characters that can be found in the number 6 popup.
Where I've used all the popup keys with the combinations for polytonic Greek, I've put the Latin letters of that key in the Greek letter χ popup, as is done for the Greek letters on the English keyboard.

In the dot popup I've added the upper dot and the middle dot. I've also put the upper dot, which is used in Greek, to the W key (the Greek ς key).

Where you read "polytonic Greek" you can understand ancient Greek, but this is not absolute, since the breathings and various tones are used even with modern Greek by some.

**Comment by ichnilatis-gr** [comment]
> So, you're allowed to get rid of all the odd chars in the dot and the comma popups, and put there any punctuation that makes more sense for your language.

At one point I considered not including the English characters at all. Then I saw that there was room on most keys, so I included them. However, as you say, I think it's more convenient to switch to the English keyboard to use English characters, just as with the physical keyboard.

In Greek we use the upper dot (·) like the semicolon in English (;). The use the sign of English semicolon as a question mark :-). I've also put the middle dot because sometimes there are text that may have used the middle dot as an upper dot.

> In the English and most other keyboards, the north key is usually the uppercase variant of that key (and on the uppercase keyboard, the lowercase variant): it allows easily starting a word uppercase with a swipe north, without having to switch layouts.
> So, if Greek also starts sentences with an uppercase (does it ? :) , you could follow that rule, and put the latin/english letter as north-east or north-west.

The truth is that I hadn't noticed that. Of course, sentences in Greek also start with an uppercase letter. So I'll follow your suggestion.

**Comment by poire-z** [comment]
I already have a hard time trying to read (just to pronounce words and try to guess the meaning) lowercase greek letters, and I realized that I don't even know the uppercase letters (except for Omega and Sigma that I've seen in math class :)
Was surprised to see that many of them look more like our Latin/English uppercase, so I wondered if you messed up :/ But no, Google/Wikipedia confirms you seem to have it right:
image

So, the spirit of the popups looks ok to me :)

**Comment by ichnilatis-gr** [comment]
Great, that's the start of learning Greek. :-)

Let me add that I have put in the popup of letter "ς" some Greek numeral symbols. They are useful when one wants to [write a number with Greek letters](https://en.wikipedia.org/wiki/Greek_numerals).
These are some mostly archaic letters, such as "digamma" (Ϝ) and "stigma" (ϛ) for 6, "koppa" (Ϙ or ϟ) for 90 and "sampi" (ϡ) for 900.

**Comment by Frenzie** [comment]
> Great, that's the start of learning Greek. :-)

Even those of us who don't learn Greek all learn Greek letters and counting in physics and chemistry. xD

**Comment by ichnilatis-gr** [comment]
> Was surprised to see that many of them look more like our Latin/English uppercase

Of course as the Latin alphabet is mostly  derived from the Greek alphabet... ;-)

**Pull request merged**
