### PR TITLE
swithItemTable -> switchItemTable

### PR DESCRIPTION
**Pull request by Hzj-jie**
This is a trivial change to fix a typo in the source code, i.e. swithItemTable -> switchItemTable.
Except for the removing of the comment line, other changes are done by a bash script,
cd frontend; for file in $(find . -name '*.lua'); do sed 's/swithItemTable/switchItemTable/g' "$file" > "$file.changed"; mv "$file.changed" "$file" ; done  ; cd ..

The side effect is the changing of file mode, 755 -> 644, which is still a reasonable change. So I leave them in the same change. If you have some serious concern, I will remove them.

### CODE REVIEW

**Comment by Frenzie** [comment]
That's been bothering me forever, but just under the threshold of actually fixing it.

**Comment by Hzj-jie** [comment]
I am looking at the check failure. Well, the network is too laggy.

**Comment by Frenzie** [comment]
Not the network (probably), GitLab is having some issues: https://docs.google.com/document/d/1GCK53YDcBWQveod9kfzW-VCxIABGiryG7_z_6jHdVik/pub

**Comment by Hzj-jie** [comment]
I mean, my network is too laggy :(

**Pull request merged**
