### PR TITLE
Setting contrast on non-touch devices

### PR DESCRIPTION
**Pull request by robert00s**
Similar to toggleswitch widget.
Close: #4218

### CODE REVIEW

**Comment by poire-z** [comment]
It works nicely (with keyboard on the emulator), but there is now a border around the contrast bar (question of taste, but I prefer how it was before - if we'd wish to keep that border, there is a small vertical mis-centering to fix):

<kbd>image</kbd>

Before:
<kbd>image</kbd>

**Comment by robert00s** [comment]
Done :)

**Comment by poire-z** [comment]
The container is shown (and it should be) when selected and used on a device with keys, and the mis-centering is visible:
<kbd>image</kbd>
(That shadow could be a stylistic choice, but we don't get it on other toggles:)
<kbd>image</kbd>


If you remove these 2 lines (usually not needed with FrameContainer, which adapts to its content):
https://github.com/koreader/koreader/blob/a706fde2d740f42597fe38d4641d4e4c986647be/frontend/ui/widget/buttonprogresswidget.lua#L31-L32
you get something that look more like the others:
<kbd>image</kbd>

**Comment by robert00s** [comment]
Thanks :)
I'll do that.

**Pull request merged**
