### PR TITLE
[CoverImage] Add Grayscale BMP in 8 bit

### PR DESCRIPTION
**Pull request by zwim**
This should solve https://github.com/koreader/koreader/issues/8046.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8054)

### CODE REVIEW

**Comment by poire-z** [comment]
Not much able to review this - but there's a probably unrelated CircleCI failure: can you re-run it (I can't, not sure why). Then, can it be merged?

**Comment by NiLuJe** [comment]
Yep, OPDS timeout :/.

**Comment by zwim** [comment]
Have triggered a CircleCi rerun now. Now problems this time.

Not able to be merged, as this depends on https://github.com/koreader/koreader-base/pull/1396.

**Comment by poire-z** [comment]
You can go on with a base bump.

**Pull request merged**
