### PR TITLE
Update nerdfonts symbol codepoints for the updated version with no PUA

### PR DESCRIPTION
**Pull request by NiLuJe**
conflicts

### CODE REVIEW

**Comment by NiLuJe** [comment]
Requires https://github.com/koreader/koreader-fonts/pull/8

**Comment by NiLuJe** [comment]
Still needs to be above Free*, as they also use the PUA.

**Comment by poire-z** [comment]
Still not interested in saving some lines with a trick like the one I mentionned at the bottom of https://github.com/koreader/koreader/pull/5537#issuecomment-548252363 ?
Or alt, put them ordered in a table
`battery_icons = { "codepoint for 0%", "codepoint for 10%"...}` and use then `prefix = battery_icons[batt_lvl%10 + 1]` ?

**Comment by NiLuJe** [comment]
Looked into it: an if ladder is likely faster than the bunch of divs & modulos involved in that function ;).

It's also mildly annoying in practice because they're in reverse order, and crit & charging are non contiguous

**Comment by NiLuJe** [comment]
Conflicting ranges in question:

https://en.wikipedia.org/wiki/CJK_Compatibility_Ideographs
https://en.wikipedia.org/wiki/Alphabetic_Presentation_Forms
https://en.wikipedia.org/wiki/Arabic_Presentation_Forms-A

**Comment by poire-z** [comment]
Thank you for getting rid of that massive black battery icon ! But you went a bit too far :)

<kbd>image</kbd>

Joking. All is fine after I had run kodev build to copy the new font in koreader-emulator... :)

**Comment by NiLuJe** [comment]
Incidentally, FreeSerif also has something in the PUA at that codepoint (both the previous one and the current) ;p.

**Comment by Frenzie** [comment]
@NiLuJe I'm getting a crash even after updating the submodules?

```
./luajit: frontend/ui/rendertext.lua:87: attempt to index local 'face' (a nil value)
stack traceback:
	frontend/ui/rendertext.lua:87: in function 'getGlyph'
	frontend/ui/rendertext.lua:176: in function 'sizeUtf8Text'
	frontend/ui/widget/textwidget.lua:59: in function 'updateSize'
	frontend/ui/widget/textwidget.lua:108: in function 'getSize'
	frontend/ui/widget/menu.lua:265: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/ui/widget/menu.lua:1044: in function 'updateItems'
	frontend/ui/widget/filechooser.lua:279: in function 'updateItems'
	frontend/ui/widget/menu.lua:1127: in function 'switchItemTable'
	frontend/ui/widget/filechooser.lua:297: in function 'refreshPath'
	frontend/ui/widget/menu.lua:962: in function 'init'
	frontend/ui/widget/filechooser.lua:118: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/filemanager/filemanager.lua:150: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/filemanager/filemanager.lua:973: in function 'showFiles'
	./reader.lua:242: in function 'action'
	frontend/ui/uimanager.lua:750: in function '_checkTasks'
	frontend/ui/uimanager.lua:1033: in function 'handleInput'
	frontend/ui/uimanager.lua:1119: in function 'run'
	./reader.lua:260: in main chunk
	[C]: at 0x556b4e7be771
```

**Comment by NiLuJe** [comment]
@Frenzie: That's weird. Anywhere in particular?

**Comment by Frenzie** [comment]
@NiLuJe Yeah, startup. :-P

**Comment by Frenzie** [comment]
Oh sorry, there seems to be more right above it:

```
11/16/19-07:16:01 ERROR #! Font  infont  ( DroidSansMono.ttf ) not supported:  ./ffi/freetype.lua:96: Failed to load font './fonts/DroidSansMono.ttf', freetype error code: 1
11/16/19-07:16:01 ERROR #! Font  infont  ( DroidSansMono.ttf ) not supported:  ./ffi/freetype.lua:96: Failed to load font './fonts/DroidSansMono.ttf', freetype error code: 1
./luajit: frontend/ui/rendertext.lua:87: attempt to index local 'face' (a nil value)
stack traceback:
```

**Comment by Frenzie** [comment]
Okay, wtf, they were deleted? O_o I did no such thing…

```
D	droid/DroidSansMono.ttf
D	droid/NOTICE
D	freefont/COPYING
D	noto/LICENSE
D	urw/COPYING
D	urw/Dingbats.cff
D	urw/LICENSE
D	urw/NimbusMono-Bold.cff
D	urw/NimbusMono-BoldOblique.cff
D	urw/NimbusMono-Oblique.cff
D	urw/NimbusMono-Regular.cff
D	urw/NimbusRomNo9L-Med.cff
D	urw/NimbusRomNo9L-MedIta.cff
D	urw/NimbusRomNo9L-Reg.cff
D	urw/NimbusRomNo9L-RegIta.cff
D	urw/NimbusSanL-Bol.cff
D	urw/NimbusSanL-BolIta.cff
D	urw/NimbusSanL-Reg.cff
D	urw/NimbusSanL-RegIta.cff
D	urw/StandardSymL.cff
```

**Pull request merged**
