### PR TITLE
Ensure we flush everything to disk after an update.

### PR DESCRIPTION
**Pull request by NiLuJe**
Will stall for longer, but with a visible message (vs. less stalling on
a white screen during the startup and a laggy FM for a while).

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/5685)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Only done one devices where we have visual feedback during an OTA, otherwise it's a random weird stall with no visible warning ;).

**Comment by NiLuJe** [comment]
Let's see how annoying this is in practice ;).

**Comment by ptrm** [comment]
wow, so this lack of sync might explain why I had most of koreader files 0b in size when hard rebooting just after an upgrade :D

Just wonder if it would work in a way of creating empty files and writing the contents later on sync, or would there be no files at all.

**Comment by NiLuJe** [comment]
That's probably entering the territory of "undefined behavior", so, who knows ^^.

**Pull request merged**
