### PR TITLE
Add space condensing setting to bottom config panel

### PR DESCRIPTION
**Pull request by robert00s**
See: https://github.com/koreader/koreader/pull/4023#issuecomment-400612233 and https://github.com/koreader/koreader/pull/4023#issuecomment-400616572

### CODE REVIEW

**Comment by poire-z** [comment]
There must be something missing: when you select 75% or 100%, it is applied. Exit koreader and restart: although the value is still shown as you last set it, it is not applied: the text looks like 50% is still used.

Possibly something missing in `ReaderFont:onReadSettings()`.
Also possibly, and may be that should be done anyway, the need to remove that global setting check I did (which looks no more necessary with this PR, so it would be confusing to keep it):
https://github.com/koreader/koreader/blob/6877ade4fd567072292ef676ca0fe410cd11fc46/frontend/document/credocument.lua#L135-L140

**Comment by robert00s** [comment]
@poire-z Thanks for testing. Now should be better.

**Comment by KenMaltby** [comment]
Why is "min" needed in the description?  I am assuming that 100% would mean no spaces between words, if needed to fit line.  Does this get applied evenly to all the spaces in a line? (I know I should be asking the CR3 developers).  Is it functional for a justified text alignment? Would 0% mean that a normal space width would be used? 33% mean a third of a normal space or that the space width would be reduced by a third?    Just trying to see how this would work for a user.

**Comment by poire-z** [comment]
The min was in my comment of a section that is now removed, trying to explain a bit how that works.
This stuff was already present in the crengine code, and with a setting in cr3.ini named `crengine.style.space.condensing.percent`, and in the code, it's called space condensing.
The default value is 50%, and that's what was used behind the scenes for years.

Answering your questions and explaining what it means (with the current naming and percentage values as used by crengine - I'm not saying this is the best choice or best way to present that to the user):

> Does this get applied evenly to all the spaces in a line?
> Is it functional for a justified text alignment?

Yes, I think it's only used when text is justified (whether hyphenation is used ot not).
Yes, the effects it has on spaces is applied evenly to all the spaces in a line.

> I am assuming that 100% would mean no spaces between words, if needed to fit line.
> Would 0% mean that a normal space width would be used?

No, the reverse actually.

> 33% mean a third of a normal space or that the space width would be reduced by a third? 

33% means we're allowed to make space width recuded to a third of a normal space

The percentage defines how much of a regular space width (100%) we can reduce/condense it to make more other non-spaces charaters fit on a line. That is used in the process deciding how to split a paragraph into lines, taking the best hyphenation position to cut a word if needed.

With 100%, a space is never reduced from its regular width (I'm not really sure then how justification is made, may be some pixels are added to spaces to make them a bit larger, so may be we'll get lines with spaces having widths like 100%, 103%, 101% of a regular space width).
With 50% (the default, what we've been experiencing), a space can be reduced to half its regular width. So, multiple lines will have different space widths, 50, 62, 100, 77, 89%... depending on how split decisions were made.
With 25%, a space can be 1/4 of its regular size (so, reduced by 75%), and you would get words nearly stuck to each others, probably very hard to read.
Even with 50%, I sometimes find (not very often) some lines with words quite stuck together, so I think using 75% could be better, and I think it is after a few days.

It's indeed a bit not obvious to comprehend and explain :)
I don't know if we should keep these values so we fit crengine values, or if we should put an other name and other labels in the toggle switches so it became clearer how it works.

**Comment by robert00s** [comment]
Maybe we'll call it "Word Gap" (like in pdfs) with 3 options:
small (50%)
normal (75%)
large (100%)

or narrow, normal, wide

**Comment by cramoisi** [comment]
@robert00s @poire-z : there is a value (i forgot it) which is defined as the standard value (in typography) of the space between words. Do you use it ?

**Comment by cramoisi** [comment]
(ok, it's related to the font used and debated : 1) the thickness of a "i" or 2) the thickness of a "o")
In css 1 the default for word-spacing is  0.25em

**Comment by poire-z** [comment]
> Maybe we'll call it "Word Gap" (like in pdfs) with 3 options: small (50%) normal (75%) large (100%) or narrow, normal, wide

Sounds nicer indeed :) (No real preference between small/large vs narrow/wide thus.)
I guess you and I prefer 75%, so I think it makes sense to increase the default/normal from 50% to 75%.
What's your preference @cramoisi (I may be remember you prefered less spacing between words) ? Would you go with 50% (what we currently have), or would you go even lower to 25% ?

I thought the default word spacing when not using justification must be the width of a space in the current font and that setting would only be used to distribute space when justification is used.
But it seems I thought wrong: if via Style tweaks, you chose Text align all left, and then use that toggle, spacing changes !
The code in crengine/src/lvtextfm.cpp is quite tedious, and looking at it right now, it's now really obvious when and why this space reducing stuff is used...

**Comment by cramoisi** [comment]
@poire-z I hate big gaps but I'm more encline to consider something not too big and not too small as an acceptable gap, so it's to me all a matter adjusting word gaps between two values and cut words if necessary to keep these values in an acceptable range. The max value is something near the double space size. For the min value I need to check (I won't have enough time to focus on this before saturday and I didn't even update yet as I was waiting for the bump-merging of soft-hyphen (and had no time, anyway).

RT, what is the intend use of floating punctuation ? I like it as it renders the hyphen more compact and different for a classic hyphen (and with some font, it's essential (like with this [one](https://www.dyslexiefont.com)) but using it make all gaps wider than without using it.

 So, question : did you enable it when you set your values ? because a 100% is not the same here and there. Another question would be about the real use of this feature (I would love to have a rendering of all hyphen but those which are part of a word rendered like when this option in turned on for all the system and get rid of this puzzling thing).

**Comment by robert00s** [comment]
@poire-z 
Defalut value should be 50% (small) - as it is now or 75% (medium)?

**Comment by poire-z** [comment]
I prefer 75%, so, if you prefer 75% too, let's decide together the default is now 75% :)
(If you prefer 50%, let's keep the default of 50%.)

**Comment by robert00s** [comment]
I also prefer 75% :)

**Comment by poire-z** [comment]
The joy of unit tests failures whenever one changes some rendering stuff :(
(As the default is now larger, there are more pages in the book, and some expected results are wrong. The most annoying to fix is the readerlink stuff, as you have to guess where taping on a link should now be done...)
(or we could pretend we never decided to choose a new default of 75%, and keep 50% as the default :)

**Comment by robert00s** [comment]
Should I try modify the tests or restore the default value?

**Comment by poire-z** [comment]
Depends on how much time and courage you have :) You decide. (Would be nice though.)

The `spec/front/unit/readerfooter_spec.lua @ 284 `is just a widget length, so it should be fine to replace 183 by 191.
The `R:0%` to replace to/from `R:1%` are ok (I switched them when the nb of pages went below 200, now it must be again above 200).
The `spec/front/unit/readerlink_spec.lua @ 15 `and `spec/front/unit/readerlink_spec.lua @ 52 `are the more tedious to fix, as you need to find new x/y.
The `spec/front/unit/readertoc_spec.lua:71 `should be a matter of changing 100 to 101 or 102 or 103 in `assert.truthy(toc:getChapterPagesLeft(100, 0) > 10) `so you get on a page after a chapter start that must be a few page later, and you'll get more than 10 pages in this chapter.

(I didn't have the unit tests infrastructure to test on my computer, so I needed to push commits so they can be tester on CI... Should be easier for you if you have it.)

**Comment by poire-z** [comment]
Well done ! :)
May I ask how you proceeded to find correct x/y ? local unit tests, trial and errors... ?

**Comment by robert00s** [comment]
Yes, local unit tests and trials :)

**Comment by cramoisi** [comment]
so, just to be sure small : 50, medium : 75, large: 100 ?

**Comment by cramoisi** [comment]
@robert00s : do you think it's possible to add the three values in defaults.persistent (or default) for easier change ? (like it is for the margin value).

**Comment by cramoisi** [comment]
whatever, 75 is totally perfect.

**Comment by poire-z** [comment]
>>    I don't use floating punctuation (and I feel like it should be disabled by default for new users).

> Good to know, I think disabled by default is the way it should be, the rendering is better with it is off (at least for "latin1" languages)

Many times I had been fighting different rendering glitches (because I had Floating punctuation enabled, which is the default, and I didn't disable it on my emulator) that disappear when I disable Floating punctuation (text right-aligned is not really right aligned with it on, all fine with it off).
So, should we have it disabled by default (and let our CJK users think about enabling it if they really want it - and everybody will avoid bad rendering by default)?
@frankyifei : any opinion?

**Comment by NiLuJe** [comment]
It's the default virtually everywhere else, and the setting is hard to miss, +1.

**Pull request merged**
