### PR TITLE
Readerlink: add methods for adding buttons

### PR DESCRIPTION
**Pull request by roygbyte**
I'm intending to use this functionality for adding a "download to EPUB" button...

EDIT: realizing now that I need to add some kind of conditional function to the buttons? Because some of them should only work for, say, external links. So... I could revise the PR somehow. Maybe add an additional entry to each button's table, like:

``` lua
{
   text = _("button label"),
   callback = ...
   condition = function(url) -- could also be called "show_if"
         if some_condition then
            return true
         end
         return false
      end
}
```

And then evaluate the condition in the `ReaderLink:getButtonsForDialog` function, using the selected link as the value to pass to the condition. And if the button table doesn't have a condition then that would indicate buttons should be added to every link. 

This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9416)

### CODE REVIEW

**Comment by poire-z** [comment]
Dunno if you had a look at readerhighlight.lua, which also has something to add buttons and managing ordering (even if no plugin use it yet).
`self:addToHighlightDialog("08_share_text"...)`
I have no preference between readerhighlight and your readerlink way of doing it - but it would be nice if the way of doing it was identical (if possible, if it makes sense).

> realizing now that I need to add some kind of conditional function to the buttons? 

Probably :)

**Comment by Frenzie** [comment]
Sidenote, grep for _func to see some examples.

**Comment by roygbyte** [comment]
I see that ReaderHighlight uses a bit of a different way of adding buttons. IDs are assigned explicitly when the button is added. The conditional display function is given the entire scope of the ReaderHighlight to determine if the show state of the button. 

``` lua 
    self:addToHighlightDialog("10_user_dict", function(this)
        return {
            text= _("Hyphenate"),
            show_in_highlight_dialog_func = function()
                return this.ui.userhyph and this.ui.userhyph:isAvailable()
                    and not this.selected_text.text:find("[ ,;-%.\n]")
            end,
            callback = function()
                this.ui.userhyph:modifyUserEntry(this.selected_text.text)
                this:onClose()
            end,
        }
    end)
```

In the context of a reader link, where the link will determine what buttons should be shown, I think it makes more sense to only give the conditional function the link string, and not the entire ReaderLink object.

As for the IDs.... I can't say I see the reasoning of explicitly setting them with text strings. But I can be enlightened to see it, I suppose.

**Comment by poire-z** [comment]
> As for the IDs.... I can't say I see the reasoning of explicitly setting them with text strings.

I guess it's for plugins to just use 14_something to be inserted after 13_corefeature - or after 12_otherfeature if 13_corefeature is disabled and is not inserted - the final ordering being an alphanumerical sort of all the IDs I guess.
With explicite insert indices like you had, if one of the previous feature is absent, the final ordering might be messed up.

**Comment by roygbyte** [comment]
Feck. I should have listened to the voice in my head. "Don't force push" :(

**Pull request closed without merging**
