### PR TITLE
Dispatcher: use translated labels for Zoom Mode actions

### PR DESCRIPTION
**Pull request by hius07**
- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10269)

### CODE REVIEW

**Comment by poire-z** [comment]
Will/can this break/lose (or crash when using) previously related things associated to gestures/profiles ?

**Comment by hius07** [comment]
No, it's just displaying (translatable) labels instead if the setting itself in the list of Dispatcher actions.

**Comment by poire-z** [comment]
Oh ok, I was looking in my action list and was only focusing on `Fit>` and `Zoom to>` on the second page, and thought you had merged them - but there is indeed a `Zoom mode>` on the first page, far away from those other two :) :/

**Comment by hius07** [comment]
Agree, it requires some reordering.

**Review by yparitcher — APPROVED** [review]

**Review by Frenzie — APPROVED** [review]
I'm not sure if "translate" would be the clearest commit message though, maybe "use translated names" or something like that?

**Pull request merged**
