### PR TITLE
Increase saturation for color Pocketbooks

### PR DESCRIPTION
**Pull request by dmalinovsky**
This improves color display and matches it to builtin PBReader saturation levels, at least visually.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10267)

### CODE REVIEW

**Comment by dmalinovsky** [comment]
I tested this on Pocketbook 741, but updated the settings for the other color devices as well to match this one.

**Comment by Frenzie** [comment]
Cross-ref to #9756, more discussion in #8872.

@rjd22 any thoughts?

**Comment by rjd22** [comment]
Personally I found 2.0 too over saturated on the PocketBook Inkpad Color. I was unable to test other devices.

I made a comparison with the original picture viewer and matched that but every color ink display behaves differently so it's impossible to accommodate every device.

**Comment by dmalinovsky** [comment]
I see. I wish I could change it in my local settings then, so the new release won't overwrite it.

**Comment by dmalinovsky** [comment]
I also tested it on Pocketbook Inkpad Color. 🤷‍♂️

**Comment by rjd22** [comment]
@dmalinovsky Feel free to make a PR that allow you to adjust it with a slider or some other way. It would be a great feature. ;)

**Comment by dmalinovsky** [comment]
@rjd22, I'm too lazy to set up a Pocketbook emulator on macos. :) I'll close the PR then.

**Comment by dmalinovsky** [comment]
Actually, it looks like it's easier to set up an emulator than I expected. I'll think about your idea, @rjd22.

**Comment by poire-z** [comment]
> I wish I could change it in my local settings then, so the new release won't overwrite it.

[User patches](https://github.com/koreader/koreader/wiki/User-patches) to the user rescue!
ie. https://gist.github.com/zwim/e5f9a12922f645fdf390faaadfeb5ac7 , so this might be enough:
```lua
local Device = require("device")
Device.color_saturation = 2.0
```

**Pull request closed without merging**
