### PR TITLE
Minor: don't turn off wifi on exit

### LINKED ISSUE #2379: Turn off wifi on exit
* KOReader version:  koreader-nightly-20161120
* Device: Kindle PW3

#### Issue
When I exit from KO to Kindle native system wifi is always switched off.
#### Steps to reproduce
Turn on wifi -> Exit from KO to Kindle native system -> wifi is off

This line should be removed?
https://github.com/koreader/koreader/blob/master/reader.lua#L192

### PR DESCRIPTION
**Pull request by Frenzie**
This fixes #2379 and #2511.

### CODE REVIEW

**Comment by asampal** [comment]
Is having wifi on -> Nickel still a problem on Kobo's with latest FW and latest KSM patch (4c, presently)?

**Comment by Frenzie** [comment]
I wouldn't know, but that's fairly irrelevant in principle. Not upgrading Nickel is always recommended imho, because it may very well break things and it's extremely unlikely to solve any issues of this sort. However, I'm 100% on board with purging this line. I see no logical relationship between exiting KOReader and turning off wifi.

**Comment by houqp** [comment]
Let's purge this line. We should just advise users upgrade to the latest KSM. The latest KSM on my A1 prompted me a new option to turn off wifi before starting nickel. And I was able to launch nickel fine even with wifi on.

**Comment by houqp** [comment]
Thanks!

**Comment by retrue** [comment]
Would it be possible to add an option to turn off wifi on exit?
It could be a tickeable menu entry in Network or a line in settings.reader.lua
I barely use Wi-Fi, only to update OTA.

**Comment by Frenzie** [comment]
I think this is more KSM's purview. Actually there seems to be a `clean_up_after_koreader_in_any_case` variable to do just that already, but at a quick glance I'm not sure where to set up your environment variables.

**Comment by houqp** [comment]
@retrue when you exit koreader, you should get a prompt from KSM to ask you whether you want to turn off wifi or not. I assume you don't exit to KSM that often?

**Comment by retrue** [comment]
@houqp Thanks. I have just seen that prompt from KSM. I exit to KSM always but I hadn't seen the prompt before because KOReader always turned off WiFi before closing or I turned WiFi off myself in KOReader as soon as I finished using it.
Anyway, starting KOReader with KSM, if I forget to turn off WiFi, I will be prompted by KSM when I exit KOReader. And if I turn off KOReader pushing the physical power button, next time I start KOReader WiFi is off, so it is great for me.
I don't use fmon anymore, so I don't know what happens if I use it to start KOReader, and i exit it with WiFi turned on. I don't know if WiFI will stay on or it will get turned off.

**Comment by houqp** [comment]
with fmon, you can just turn it wifi off from nickel. I think fmon users actually prefer keeping the wifi on exit because they usually manage the wifi using nickel itself.

**Pull request merged**
