### PR TITLE
Spinwidget: default width

### PR DESCRIPTION
**Pull request by hius07**
Of about 25 modules using Spinwidget about 20 set width=0.6 and others set width=0.75.
No one uses default 0.95 (hope I haven't missed anything).
Changing the default will allow step by step optimize code removing width initializing.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8182)

### CODE REVIEW

**Review by Frenzie — COMMENTED** [review]
Fine by me, but did you forget to remove the custom with = 0.6 occurrences or did you want to wait for opinions first?

**Comment by hius07** [comment]
> did you forget to remove the custom with = 0.6 occurrences

There are too many of them.
Same as in https://github.com/koreader/koreader/issues/8171, let's control the new ones, as well as occurrences in the modules that are edited in future PRs.
So, step by step all will be optimized.

**Comment by hius07** [comment]
Is there a difference how to init a property, eg width?
https://github.com/koreader/koreader/blob/0283c44ff7b0904b02f29ab74574930c76f9d1a4/frontend/ui/widget/spinwidget.lua#L25-L29
or
https://github.com/koreader/koreader/blob/0283c44ff7b0904b02f29ab74574930c76f9d1a4/frontend/ui/widget/doublespinwidget.lua#L26-L30
and then
https://github.com/koreader/koreader/blob/0283c44ff7b0904b02f29ab74574930c76f9d1a4/frontend/ui/widget/doublespinwidget.lua#L56-L60

**Comment by poire-z** [comment]
Yep, the DoubleSpinWidget is better: the SpinWidget will be wrong after you switch to landscape mode (or if you start in landscape, it will be too large in portrait).
The things in `:new()` are run once at load time, so should be real constants, or properties listed for documentation purpose.
The things in `:init()` for each instantiation, so all the dynamic stuff must go there.

**Comment by hius07** [comment]
Thank you, these nuances are very important to understand and comply with.

**Comment by hius07** [comment]
Do we need so wide SpinWidget in landscape mode?
Can it be in init something like
`self.width = self.width or math.floor(math.min(self.screen_width, self.screen_height) * 0.6)`

**Pull request merged**
