### PR TITLE
[fix] GestureDetector: fix multiswipe direction detection code

### PR DESCRIPTION
**Pull request by Frenzie**
Unfortunately a mistake snuck into the final steps of refactoring <https://github.com/koreader/koreader/pull/4607>.

Thanks to @poire-z for pointing it out [here](https://github.com/koreader/koreader/pull/4607#issuecomment-464856789).

### CODE REVIEW

**Comment by poire-z** [comment]
On the emulator, it now works, with small or quick multiswipe.
But if you make long swipe segments, or slow ones, it often just ends up being a pan_release.
I'll have to check on a device, where it may work better.

**Comment by Frenzie** [comment]
Panning is a difficult case. Could you try something like this?

```diff
diff --git a/frontend/device/gesturedetector.lua b/frontend/device/gesturedetector.lua
index d8b23a68..672e8506 100644
--- a/frontend/device/gesturedetector.lua
+++ b/frontend/device/gesturedetector.lua
@@ -196,6 +196,12 @@ end
 function GestureDetector:isSwipe(slot)
     if not self.first_tevs[slot] or not self.last_tevs[slot] then return end
     local tv_diff = self.first_tevs[slot].timev - self.last_tevs[slot].timev
+    local msd_cnt = #self.multiswipe_directions
+
+    if msd_cnt > 1 then
+        tv_diff = self.multiswipe_directions[msd_cnt][2].time - self.last_tevs[slot].timev
+    end
+
     if (tv_diff.sec == 0) and (tv_diff.usec < self.SWIPE_INTERVAL) then
         local x_diff = self.last_tevs[slot].x - self.first_tevs[slot].x
         local y_diff = self.last_tevs[slot].y - self.first_tevs[slot].y
```

**Comment by poire-z** [comment]
Tried it, but it does not seem to reduce my failures rate on the emulator.

**Comment by Frenzie** [comment]
How are you trying it exactly?

**Comment by poire-z** [comment]
south-east and east-south bound to TOC and bookmarks.
I just hold my mouse left click, and draw the two segments, and release the click. There may be 100ms-pauses at various moments in this flow :)
(I'm currently trying it over ssh tunnel - so may be that plays with the timings... I'll check later on local lan).

**Comment by Frenzie** [comment]
I suspect that tunnel aspect must be it. I'm having no trouble at all — or at least, not with that. I did, however, accidentally break registering the gesture without realizing it due to my local leftover settings.

**Comment by poire-z** [comment]
Still high failure rate on my emulator (X11 on lan). But note that I do quite large swipes on a 600x610 emulator, so swipes of 150 to 250 px. Doing small ones like 50 px works ok.)

Tested on my GloHD: doing swipes one handed, so short swipes, works very well (doing larger swipes, 4-6cm each; still often fails).

**Comment by Frenzie** [comment]
And the change I suggested makes no difference?

**Comment by poire-z** [comment]
Nope.
But ok, I tracked it down to my same initial issue: if on my big swipes, the first one (south) is larger than the second one (east), it fails to be detected. 4cm south followed by a 5cm east works.
Same with shorter ones, but I guess when doing these small, it is easier to get the 2nd one larger. Drawing them large on a portrait mode screen, you end up having the first south one larger than the 2nd east one.
Same behaviour on the emulator, so I guess you can reproduce this?

**Comment by Frenzie** [comment]
Yes, I think so. It feels very unnatural to me. :-)

**Comment by poire-z** [comment]
Another issue with this detecting code: the small diagonal swipe (to trigger full screen refresh) now works only occasionally:
- a very small diagonal swipe works
- a longer or slower one (so, probably causing multiple touch events) is no more a `swipe northeast` but becomes a `multiswipe north east` (even if I try to make it really diagonal :)
- somehow, a long diagonal swipe to take a screenshot works

**Comment by Frenzie** [comment]
> Another issue with this detecting code: the small diagonal swipe (to trigger full screen refresh) now works only occasionally:

I disagree, I see no problem with diagonal swipes. It was definitely a bug that it used to trigger "diagonal" swipes at random just because you could draw a diagonal-ish line between point A and B if you ignored the actual path.




> a longer or slower one

Interesting. There indeed seems to be a point where you can swipe oddly slowly in a way that triggers a multiswipe instead of a diagonal swipe but not yet a pan. It doesn't feel like a problem due to the artificiality of the movement but we can experiment with an angular threshold as well.

**Comment by poire-z** [comment]
Mhhh, this diagonal swipe not happening is a also frustrating in the ImageViewer, where, after zooming, I often make long swipes to move the map on a long diagonal distance.

I guess the thing you declared "not diagonal" , or the (in)sensitivity of multiswipe code, is what makes the multiswipe work so well (even drawing your 4 swipe for full refresh like a near circle works :).
We could add some handler for multiswipe everywhere. But I wonder if there could be a trick to "downgrade" a multiswipe to the nearest swipe in contexts where it would explicitely be stated that we don't want multiswipe.

But that would not help in the reader (where it is frustrating that my usual small diagonal but-not diagonal-enough triggers my `↥ ↦` gesture - which i may end up mapping to full refresh :| )

**Comment by Frenzie** [comment]
> I guess the thing you declared "not diagonal" , or the (in)sensitivity of multiswipe code, is what makes the multiswipe work so well

Precisely. By not having that trigger-happy "diagonal" in the way, swipes would be more dependable. I would remove it.

> But I wonder if there could be a trick to "downgrade" a multiswipe to the nearest swipe in contexts where it would explicitely be stated that we don't want multiswipe.

I already built that trick in. A multiswipe gesture also comes with a classic swipe direction.

**Comment by Frenzie** [comment]
Like so:

text827

**Comment by poire-z** [comment]
> By not having that trigger-happy "diagonal" in the way, swipes would be more dependable. I would remove it.

I'd rather not lose it (it's useful in a few places, and a habit to me on my ghosting GloHD).
Also if you do, I guess any long diagonal swipe becomes either a north-east or east-north, with different behaviour whether my finger went 44° or 46°.
It may be worth testing that thing you mentionned about angle, and see if that's a good variable for sensitivity, that could we could tweak from 30° to 40° : if less it's ok to be considered vertical or horizontal candidate for multiswipe - if higher go with diagonal single swipe.

> The default of a screen refresh isn't too different from just a deadzone, so it's mostly harmless. I think the deadzone could be smaller though.

Not getting what you mean with deadzone. (Or is that a deadzone for the angle ? 40° > 50° could be a deadzone)
(And there is long diagonal swipe to move image in ImageViewer, no deadzone for that:)

**Comment by poire-z** [comment]
And even just the first swipe would need that angle constraint. Once you made the first swipe nearly horizontal or vertical, you're then free to go full circle on the next ones to make a multiswipe.

**Comment by Frenzie** [comment]
> Also if you do, I guess any long diagonal swipe becomes either a north-east or east-north, with different behaviour whether my finger went 44° or 46°.

No, I'll leave well enough alone. But that would be the dead zone, not the random zone. What you're describing is the problem with the *current* behavior.

**Comment by poire-z** [comment]
Mhhh, for multiswipes, I think we're happy and safer with 4 directions. 8 directions would make the thing messy and more random, and not working as well, I think. And uneeded :)

**Comment by poire-z** [comment]
Any plan of some sort for this now half working diagonal swipe for screen refresh before next release?
- 8 directrions swipes (which would blend it into a single diagonal swipe - but I feel it would be messy for others)?
- condition that first swipe to be in some restricted angle to trigger multiswipe?

You may not use that swipe, but I'm really bothered by this problem (I've been losing my current page a few times, wondering why - and just realized now I had set east-north to forward 10 pages... - so these are mapped to "nothing" for now)
There's no reason some other users won't be bothered too (and will trigger unwilllingly one of the 4x2 horiz+vert or vert+horiz 2-swipes gestures).

**Comment by Frenzie** [comment]
> condition that first swipe to be in some restricted angle to trigger multiswipe?

I guess this might be another one I accidentally lost in some reshuffling, but that's actually how I wrote/intended it. (I.e., only north/south/east/west can *start* a multiswipe. No need to be complex about it.)

**Comment by poire-z** [comment]
^ That would be perfect I think.

**Pull request merged**
