### PR TITLE
Some uppercase fixes

### PR DESCRIPTION
**Pull request by retrue**
Use uppercase for some menu entries that appear in lowercase in some menus.

OTA channel -- **S**table / **D**evelop
Set render style -- **C**lear all external styles
Tools -- **C**alibre wireless connection

Message error when opening bookmarks list when there is not any bookmarked pages in the book:
**N**o choices available

### CODE REVIEW

**Comment by retrue** [comment]
Changed to Development.
About Calibre or calibre, I didn't know. I prefer Calibre for stylistic coherence, but that is not my decision. So, if any of you decide to keep it as calibre, please delete that commit in this PR yourselves. I don't know how to do it  myself ^^;

**Comment by houqp** [comment]
Thanks!

**Comment by KenMaltby** [comment]
If you are capitalizing the first word, of such phrases and calibre just happens to be the first word of the phrase, it might be capitalized for that reason.

**Comment by Frenzie** [comment]
Behold, fallout :-P

> calibre should be in lowercase

https://www.transifex.com/signin/?next=/houqp/koreader/translate/#sv/koreader/102794539/

**Pull request merged**
