### PR TITLE
Added Date along with time in touchmenu

### PR DESCRIPTION
**Pull request by deepakonwww**
Added Date along with existing time, display in touchmenu.lua file, so user can always see the date also while pulling down the settings.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8337)

### CODE REVIEW

**Comment by poire-z** [comment]
image

Might feel a bit crowded and unbalanced - and I'm not really sure it matters to always see the date - when we have a [wonderful Calendar view](https://github.com/koreader/koreader/pull/5854) from our Reading statistics, than we can invoke from a gesture.
(Might be just me, but seeing 2021-10-17 does not talk to me much - seeing a real calendar and getting from visual which week day it is talks to me more.)

**Comment by deepakonwww** [comment]
@poire-z and @hius07, Agreed with your comments.
Could you please let me know, how can I get this build which you guys are running?

**Comment by poire-z** [comment]
As everybody: https://github.com/koreader/koreader/releases/tag/v2021.10
The question then is: which build might you be running ? What do you miss ? If you don't see it as large or small as us, it may depends on your screen size, and your `Gear > Screen > Screen DPI` setting.
(And for the calendar, you need the Reading statistics plugin enabled, and it's available from the Tools menu.)

**Comment by deepakonwww** [comment]
@poire-z I was actually talking about the build in your screenshots where you have got the date.

**Comment by poire-z** [comment]
Oh, no, we just added your 1-line patch manually in the code (@hius07 on his Kindle, me on the emulator): we can do that, KOReader is mainly Lua plain text files, that you can edit directly and restart (you can even edit it from KOReader itself with its own Text Editor plugin) - no need to re-build anything. (Except on Android, where it's quite more complicated.)

**Comment by deepakonwww** [comment]
Ohh, I didn't know that! Thank you so much @poire-z for this amazing tip.
Now onwards I will also test my changes this way. Thanks again. Cheers.

**Comment by deepakonwww** [comment]
That's really good. I was just going through the repo for the first time today and I thought I can make this addition to it. Somehow I didn't thought about it much. But you guys are such cool people. Thank you so much for taking all the trouble to guide me. Really appreciate it. KOReader is such an awesome project with awesome people :)

**Pull request closed without merging**
