### PR TITLE
bump crengine: text formatting: fix leading spaces issues

### PR DESCRIPTION
**Pull request by poire-z**
Includes:
- text formatting: fix leading spaces issues https://github.com/koreader/crengine/pull/204
- new English US & GB hyph patterns https://github.com/koreader/crengine/pull/206

(small bump to have nightly builds with individual changes in case we need to bissect some side effects with the recent and coming rendering fixes)

### CODE REVIEW

**Comment by poire-z** [comment]
OK, 1 page less in juliet.epub. I dunno if it's because of my leading spaces fix or the changes of english hyph dict... Hope it's fine.

**Comment by poire-z** [comment]
There may be some fix needed in the script that cleans up nightlys :) keeping only those from the last 15 days could be a problem when we don't commit in 15 days... There are only 4 nightly left :)

**Comment by Frenzie** [comment]
If you have time, you could comment out the cron job (sudo crontab -e). I won't have time till tomorrow at the earliest.

**Comment by poire-z** [comment]
OK, commented out.
Please have a look at `proposed_purge_old_artifacts.sh` , for a possible alternative script to purge old nightlys and ota.

**Comment by Frenzie** [comment]
Is it based on counting? The date thing always seemed a bit overcomplicated to me anyway. I'll hopefully take a look tomorrow.

**Comment by poire-z** [comment]
> Is it based on counting?

Yes, in the limits of my bash skills :)

**Comment by NiLuJe** [comment]
Where is this? I could take a look tomorrow, too ;).

**Comment by poire-z** [comment]
It's on some koreader.rocks server, where @Frenzie created once an account for me - so not lookable until he creates one for you :)

**Comment by Frenzie** [comment]
Do I have your e-mail?

**Comment by NiLuJe** [comment]
I thought this was available somewhere on GitHub, but apparently not directly, so: ninuje@gmail.com ;).

**Comment by Frenzie** [comment]
Some of those scripts should maybe go in misc. They're pretty basic though.

**Comment by NiLuJe** [comment]
I added my two cents to the mix alongside @poire-z's script.

The bashiest mess I could come up with, yay! :D. (At a quick glance, sort -V works just as well as -M might, but since we're actually sorting versions, that felt relevant, and a quick test with a major version bump showed the expected behavior :)).

**Comment by Frenzie** [comment]
Btw, I haven't really taken a look besides quickly creating an account, but this new script isn't deleting recent nightlies by any chance? >_>

**Comment by poire-z** [comment]
Too many bashisms and pipes and `read` and options for me to be able to say _lgtm_, but I trust @NiLuJe on this :)

**Comment by Frenzie** [comment]
Or were there just no changes in the repo? Sorry, been a bit busy. ;-)

**Comment by NiLuJe** [comment]
Yeah, there was an actual lull between 1744 and 1745 ;).

**Comment by poire-z** [comment]
Feel free to put one in cron (we're at 83% with 15 nightlys, so it's time and there's candidates to deletion for testing).

**Comment by NiLuJe** [comment]
Done :).

**Comment by Frenzie** [comment]
Nah, that'd be moving 'em all into "archive" (i.e., more than a couple of months old). ;-)

**Comment by NiLuJe** [comment]
Managed to catch the first two cron runs, it appears to behave just fine.

First run sheared one OTA, second run none, we're at 15 each :).

**Pull request merged**
