### PR TITLE
Persist: Add the new native LuaJIT serializer to the list of supported codecs

### PR DESCRIPTION
**Pull request by NiLuJe**
And swap the Calibre metadata cache to it.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7543)

### CODE REVIEW

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/7543)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NiLuJe)

**Review by Frenzie — APPROVED** [review]
Cool. The calibre thingy switches between "codecs" elegantly?

**Comment by NiLuJe** [comment]
Well, it should fail to load the old format, delete it, and then rebuild it in the new one.

**Comment by NiLuJe** [comment]
Actually, `bitser` -> `luajit` works, but the inverse blows up in fun and interesting way, so I'll force a cache invalidation, just to be safe...

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/7543)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NiLuJe)

**Pull request merged**
