### PR TITLE
Bookmarks: fix compare invalid xpointers

### PR DESCRIPTION
**Pull request by hius07**
Thanks https://github.com/koreader/koreader/pull/8616#issuecomment-1015443117

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8690)

### CODE REVIEW

**Comment by poire-z** [comment]
No easy fix to include in there for the issue with different datetime we discussed around https://github.com/koreader/koreader/pull/8616#issuecomment-1008254988 ?

**Review by poire-z — APPROVED** [review]

**Comment by hius07** [comment]
Currently we search corresponding bookmark with datetime and page only
https://github.com/koreader/koreader/blob/0216493c438425f6ca130b1dddc22fbb653eeaa8/frontend/apps/reader/modules/readerbookmark.lua#L1002
If not comparing datetime, we can check pos0 and pos1 (which are tables for pdf, so a little bit more expensive to compare).
But we can have two highlights with equal start and end (rare but possible case), so the only difference would be the datetime stamp. Do not know how to automate that.
General solution can be a button "Highlights and bookmarks fix", to scan both lists, find orphans, and ask a user to manually fix them (delete or add corresponding pair).

**Comment by poire-z** [comment]
^ I don't think we need any button or user facing stuff to "fix bookmarks". I don't care much about past errors and invalid bookmarks/highlights misassociated, as long as it does not crash and cause no other issue.

Thought we could just fix future issues , avoiding these two os.date() calls in the same action and the super rare bad luck of crossing a second between the 2 calls - now that we know this can be an issue.

**Comment by hius07** [comment]
> we just have to make sure we have them identical when creating a single bookmark/highlight pair

Agree, I'll think of it.

**Comment by hius07** [comment]
Is is easy to create orphaned highlight.
Select text, choose Highlight. Select the same text, choose Highlight.
Tap the highlighted text, choose Delete.
Got it: highlight without bookmark, not displayed in the bookmark list, cannot add a note.
It is because of 
https://github.com/koreader/koreader/blob/7783d9c8e37099fa2e138d660dc76ed4ec5257ca/frontend/apps/reader/modules/readerbookmark.lua#L884-L887

**Pull request merged**
