### PR TITLE
Code style: spaces around operators

### PR DESCRIPTION
**Pull request by zwim**
Removing a lot of nits. (I love and hate regex.)

(Maybe for 2023.1)

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9969)

### CODE REVIEW

**Comment by Frenzie** [comment]
I don't necessarily agree that `,` and `..` are the same. For example, I find `mandatory = mandatory and ""..mandatory or ""` clearer than `mandatory = mandatory and "" .. mandatory or ""`. (Something similar applies to the usage of `for n=1` but that's quite rare.)

We currently use an eye of the beholder system where I think many of us agree that for short things no spaces are clearer or nicer to look at but that they become a necessity once it starts getting longer.

Just throwing it out there to see if it's just me. ;-)

**Comment by NiLuJe** [comment]
> Just throwing it out there to see if it's just me. ;-)

I tend to treat the concat operator as every other operator (so, yeah, not a fan of sticky concats, even against an empty string) ;p.

**Comment by Frenzie** [comment]
@NiLuJe As I said I'm not necessarily in favor of spaces around = either (particularly the ones in this PR) so yeah, I'm not saying anything inconsistent. Other than that , is a special case.

**Comment by poire-z** [comment]
> For example, I find `mandatory = mandatory and ""..mandatory or ""` clearer than `mandatory = mandatory and "" .. mandatory or ""`. 

Sharing this feeling.
I'm not consistent on this, I may add spaces when they are standalone - but if there are among `and` `or`, I would not add spaces to get them stuck, so the `and` and `or` stand out.

> (Something similar applies to the usage of `for n=1` but that's quite rare.)

I also write `for n=1, 10, 2` as it makes the 3 blocks stand out (`n=1` `10` `2`) which makes it more readable.
But adding the spaces could make that be read as `for n =` `1, 10, 2`, which is another way to look at it, and rather ok.

But in general, I would let that to the appreciation of the code writer and the reviewers at the time it was added :) - it is only a nit when it is reviewed and commented as such ;) - and I really don't like these super big commits touching many things for no real reasons.

But I'm more worried about @zwim than about the above :/ You're just back from your needed away-from-KOReader holidays ("too much time, too much work, too much arguing"), and you already have 4 opened PRs... to all of which i would have to say something about :/
So, I will not oppose to _this_ PR :)

**Review by Frenzie — APPROVED** [review]
What @poire-z said.

**Comment by zwim** [comment]
@poire-z Thank's I am fine again. Let's postpone the work on this PR for some time.

**Comment by zwim** [comment]
Are there any reservations about closing/dropping this PR?

**Comment by Frenzie** [comment]
No objections, consistent spaces behind the comma are good but not important.

**Pull request closed without merging**
