### PR TITLE
ReaderFooter: Refresh the footer on frontlight state changes issued by the frontlight widget

### PR DESCRIPTION
**Pull request by NiLuJe**
c.f, https://www.mobileread.com/forums/showpost.php?p=4220159&postcount=7

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9084)

### CODE REVIEW

**Comment by Frenzie** [comment]
Given the nature of the beast it might be best to limit how often it updates? E.g., some kind of scheduleIn/unschedule  spiel. Or is that overthinking it?

**Comment by NiLuJe** [comment]
That did not appear to be necessary, stuff was still reliable on a H2O over here (even when swiping the intensity bar) ;).

**Comment by Frenzie** [comment]
But the H2O is where everything's perfect. That doesn't mean anything. ;-)

**Comment by NiLuJe** [comment]
No issues on a Sage, either ;).

**Comment by Frenzie** [comment]
I wash my hands off it. ;-P

**Pull request merged**
