### PR TITLE
Add OPDS catalog for Library Genesis

### PR DESCRIPTION
**Pull request by avsej**
Library Genesis (libgen) is pretty popular library. Unfortunately it does not have its own OPDS server, but I generated static XML files and hosted them on S3 behind CDN, so they can be accessed pretty fast. I have script to regenerate and update tree from the official SQL dumps of libgen. Right now my tree covers fiction and main libraries of libgen.

I hope koreader users will find it useful.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7349)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Dubious legal status of the source probably makes this a Bad Idea(TM) ;).

**Comment by avsej** [comment]
oh, wow. I didn't know that koreader cares about this matter. You have flibusta already, which is the same kind of library (in terms of legal status)

**Comment by avsej** [comment]
Feel free to close the PR if it does not fit koreader's standards.

**Comment by Frenzie** [comment]
I'll close this one then. But thanks for the PR! ;-)

**Comment by NiLuJe** [comment]
I don't know who added it, but we probably failed to check because we're unfamiliar with the Eastern European internet landscape.

I just happened to have heard about libgen somehow, so it very vaguely rung a bell.

**Comment by Frenzie** [comment]
It snuck in through #4515. It looks to me like a Russian Gutenberg/Archive.org type situation but indeed I'm otherwise unfamiliar with it.

**Comment by avsej** [comment]
@Frenzie, I removed flibusta in #7352

**Pull request closed without merging**
