### PR TITLE
StorageStat: Improve Output (#2486)

### PR DESCRIPTION
**Pull request by NickSavage**
Improves the output of StorageStat to make it more intuitive and user-friendly.

### CODE REVIEW

**Comment by Frenzie** [comment]
I don't know if there was a rationale behind the original format, but I like the new form. Could you squash those two into one commit? You would do that by rebasing in the relevant branch, in this case on the last two commits.

```
git rebase -i HEAD~2
```

In general I think people are too rebase-y, basically getting rid of what I sometimes consider relevant process along the way, but simple whitespace is a touch different. :-)

**Comment by NickSavage** [comment]
There, fixed. I am still a novice at git and I didn't even realize I could do that!

**Comment by houqp** [comment]
This is turning into a shell scripting contest. We could have at least done the space split in Lua and construct the message with `_()` to make the string translatable. This feature also needs to be extended to support external storage in the future.

**Comment by Frenzie** [comment]
Quite true, but at least now it's obvious what we're looking at. I'll admit I've never seen any of this from KOReader's GUI yet, but U, F and P are beyond opaque. ;-)

On a related note, I find it sad/funny how afraid people sometimes seem to be of language features, trying to do *everything* in regular expressions.

**Comment by Hzj-jie** [comment]
The 6th field of sed was the device type I remember.
So now on Kobo with SD card, you will have two internal storages.

**Comment by KenMaltby** [comment]
Right, it is showing as two "internal" storage locations, on my Kobo AuraHD, as well.

**Comment by houqp** [comment]
@Hzj-jie @NickSavage can you help fix the device type? Would be nice if we can rewrite it in Lua and assign each field with a variable name so it's less likely for future contributors to miss a field.

**Comment by Hzj-jie** [comment]
Sure.

**Pull request merged**
