### PR TITLE
FontList: skip Kindle blacklisted fonts

### PR DESCRIPTION
**Pull request by hius07**
Closes https://github.com/koreader/koreader/issues/11927.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11932)

### CODE REVIEW

**Comment by hius07** [comment]
https://github.com/koreader/koreader/blob/2388efdbd26fa3f9bd219ca4407743a67185679f/frontend/fontlist.lua#L1
https://github.com/koreader/koreader/pull/4580#issuecomment-462659161

Has this story been developed?
I do not see any extensive usage of `CanvasContext`, except unit tests.

**Review by poire-z — APPROVED** [review]

**Comment by Frenzie** [comment]
> Has this story been developed?

It should still work as described there if that's what you're asking.

**Comment by hius07** [comment]
Yes it works but in the current state without further development as was planned it doesn't give much benefit comparing to usual `Device`.

**Comment by poire-z** [comment]
I think it was for external development (@houqp doing some stuff on his own with parts of KOReader) that we shouldn't need to know about :) May be it happened, may be not, may be nobody uses this indirection layer.
But it's a big too much to remove, and strangely, it hasn't really ever come in my way when developping stuff.

**Pull request merged**
