### PR TITLE
ci/macos: add arm64 job

### PR DESCRIPTION
**Pull request by benoit-pierre**
Untested, someone with access to a real machine will have to test the bundle.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11945)

### CODE REVIEW

**Comment by Frenzie** [comment]
I can't find the artifact link on macOS?

**Comment by Frenzie** [comment]
Bad news.
image

**Comment by Frenzie** [comment]
I can't seem to find a way to get anything out of macOS.

**Comment by Frenzie** [comment]
The x86_64 build also doesn't want to open, but with an error message that possibly explains the arm64 failure as well.

image

**Comment by benoit-pierre** [comment]
So just to be clear, the x86_64 build starts once you work around the "scary" security warning popup?

**Comment by benoit-pierre** [comment]
Starting from a terminal should give more info.

**Comment by Frenzie** [comment]
> So just to be clear, the x86_64 build starts once you work around the "scary" security warning popup?

Yes.

> Starting from a terminal should give more info.

Full and complete instructions since obviously that's the very first thing I tried. ;-) The only way I could find to start from terminal is with `open`, which doesn't provide any logs.

**Comment by benoit-pierre** [comment]
It looks like the rules for arm64 and x86_64 are different: https://wiki.lazarus.freepascal.org/macOS_Big_Sur_changes_for_developers#Code_signing_-_Intel_vs_M1

Let's see if signing (ad hoc) the application bundle changes anything.

> Full and complete instructions since obviously that's the very first thing I tried. ;-) The only way I could find to start from terminal is with open, which doesn't provide any logs nor does it have some kind of -v or --verbose option, at least if you go by --help. It might have something hidden.

I think you should be able to run `./KOReader.app/Contents/MacOS/koreader` directly.

**Comment by Frenzie** [comment]
Pinging @ryanwwest 

(or ping me in a week if I forget)

**Comment by kmkipta** [comment]
@Frenzie I am actually using KOReader with moderate success (I have never used this app before) on M1 right now without any cli intervention. It does crash on maximize I noticed so far.

Screenshot 2024-06-02 at 4 45 21 PM

**Comment by benoit-pierre** [comment]
@kmkipta: which version? Can you get a log for that crash?

**Comment by Frenzie** [comment]
@kmkipta The arm64 build you mean? The x86_64 build runs on everything.

**Comment by Frenzie** [comment]
@benoit-pierre Your codesign experiment seems to have worked. The steps are now the same as for x86_64 (i.e., use right click or ctrl+click → open), even if the exact messages are slightly different.

**Comment by Frenzie** [comment]
Minor correction, it's macOS itself that changed the error messages.

**Comment by Frenzie** [comment]
Could you remove the "Hopefully" from that commit message for completion's sake? ^_^

**Comment by benoit-pierre** [comment]
Out of curiosity, what's the new scary warning? :P

**Comment by Frenzie** [comment]
> I think you should be able to run `./KOReader.app/Contents/MacOS/koreader` directly.

This might work (as in it doesn't obviously fail out of the gate) but it's missing a way to get at the ctrl+click variety of the dialog.

> Out of curiosity, what's the new scary warning? :P

Hold on, I'll have to look up the Apple screenshot shortcut. It's something like shift+command+s except that's not it.

**Comment by Frenzie** [comment]
shift+command+4

regular open
Screenshot 2024-06-11 at 21 40 32

right click/ctrl+click open
Screenshot 2024-06-11 at 21 40 48

**Comment by Frenzie** [comment]
> This might work (as in it doesn't obviously fail out of the gate) but it's missing a way to get at the ctrl+click variety of the dialog.

Aha, got it.

```sh
xattr -r -d com.apple.quarantine ./KOReader.app
./KOReader.app/Contents/MacOS/koreader
```

Courtesy of https://apple.stackexchange.com/a/240610

**Comment by kmkipta** [comment]
> @kmkipta: which version? Can you get a log for that crash?

I know it's been a minute, but I have the log for that crash. Here's the bad access exception:

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [62906]
```

I can post the entire report somewhere, but I can reproduce this on 2 different ARM m1 macs using the most recent mac arm build from action #10831

**Comment by benoit-pierre** [comment]
@kmkipta: please create a dedicated issue.

**Pull request merged**
