### PR TITLE
[UX] Gesture manager: add action - show dictionary/Wikipedia

### PR DESCRIPTION
**Pull request by Frenzie**
References #4687.

### CODE REVIEW

**Comment by poire-z** [comment]
Looks OK, but I tested it (the lookups, not the gestures) and strangely, the keyboard is a lot less responsive with this patch than without...
I can't really see why, so may be it's something with my emulator (but patch -p1 and patch -R -p1 repeatedly show the same differences...)

**Comment by Frenzie** [comment]
You mean the onscreen keyboard?

**Comment by poire-z** [comment]
Yes, our on-screen keyboard.

**Comment by Frenzie** [comment]
I'll give it a try on my H2O this weekend. I don't think I notice anything. Is there a particular way to demonstrate the problem?

**Comment by poire-z** [comment]
Put the mouse cursor on a virtual keyboard key, and hit your mouse left click like mad
And ... **have "Disable double tap" unchecked** :) (I had unchecked earlier today to check some of your stuff I guess).
So, no problem when double tap is disabled (10 mad clicks = 10 letters). But there's a difference when it is not disabled (10 mad clicks = 1 or 2 letters)

**Comment by Frenzie** [comment]
Ah, so then it's probably not a performance thing (which would be bothersome) but simply a case of  (un)intended double tap delay. I still can't reproduce it though, neither in file manager nor reader.

**Comment by poire-z** [comment]
Most probably a property that can be set to a widget to have double tap disabled for this widget (even if it's not disabled globally) - that went missing (or was not set anymore) after your small refactoring.

```
frontend/apps/reader/modules/readerpaging.lua:    Input.disable_double_tap = false
frontend/apps/reader/modules/readerpaging.lua:    Input.disable_double_tap = true
frontend/ui/uimanager.lua:    if widget.disable_double_tap == false then
frontend/ui/uimanager.lua:        Input.disable_double_tap = false
frontend/ui/uimanager.lua:        Input.disable_double_tap = true
frontend/ui/uimanager.lua:    Input.disable_double_tap = true
frontend/ui/uimanager.lua:            if self._window_stack[i].widget.disable_double_tap == false then
frontend/ui/uimanager.lua:                Input.disable_double_tap = false
frontend/ui/widget/virtualkeyboard.lua:    disable_double_tap = true,
frontend/device/input.lua:    disable_double_tap = true,
```

**Comment by Frenzie** [comment]
So then is it in only of dictionary or Wikipedia or in both?

**Comment by poire-z** [comment]
With "Disable double tap" not disabled:

Without this PR / with this PR

**Dictionnary lookup: OK / SLOW**
Wikipedia lookup: **SLOW / SLOW**
Fullteaxt search: OK / OK
Reading statistics > Settings : OK / OK
Text editor: OK / OK
Rename bookmark: **SLOW / SLOW**

So, it's a more general issue when double tap is not disabled, that is taken care of in various places with keyboard input, but not all - and you broke only Dictionary lookup with this PR (so, once unbroken, that trick should be put into these other places).

**Comment by Frenzie** [comment]
I don't really understand why I'm failing to spot the problem but that makes sense. The dictionary lookup is something I actually changed (concretely, by copying it from Wikipedia) so it's a rewrite that (seemingly) functions the same.

Wikipedia was just a tiny reshuffling of the exact same code.

What's not clear to me is why this should be an issue, because the VirtualKeyboard uses `disable_double_tap = true,`.

As a quick workaround you could see if adding `disable_double_tap = true,` to the InputDialog widget resolves the problem.

**Comment by Frenzie** [comment]
@poire-z Instead of using InputDialog directly we should be able to use the InputContainer's onInput event (just like in the menu, which apparently worked well with double tap). It'd make for slightly less code but I don't really see how it should make a difference in actual functionality. :-/

https://github.com/koreader/koreader/blob/779909343c80501fc223376f4b9e0d46f183c9fd/frontend/ui/widget/container/inputcontainer.lua#L263-L291

**Comment by poire-z** [comment]
> As a quick workaround you could see if adding disable_double_tap = true, to the InputDialog widget resolves the problem.

Nope, this does not solve it:
```diff
local InputDialog = InputContainer:new{
+    disable_double_tap = true,
    is_always_active = true,
```

**Comment by Frenzie** [comment]
Hm, curious. Anyway, shall we merge this as is, seeing how the problem is unrelated, or strip out the dictionary part (since Wikipedia is already borked)?

**Comment by poire-z** [comment]
Go ahead. We'll have that into master to fix them all when we find the culprit.

**Comment by poire-z** [comment]
Might be dependant of readerrollin being used.
There's this on widget show:
https://github.com/koreader/koreader/blob/57ce8dc5742a024cd334e9be63d6a7531ab92120/frontend/ui/uimanager.lua#L292-L297
and this on widget close:
https://github.com/koreader/koreader/blob/57ce8dc5742a024cd334e9be63d6a7531ab92120/frontend/ui/uimanager.lua#L321-L340

So, any widget on the stack that didn't disable double tap will enable it, and all the others that did disable it are screwed (#2155).
So, readerui sets disable_double_tap = false (for readerrolling double tap to go to prev/next chapter), so I guess any input/virtualkeyboard that is stacked over it don't get double tap disabled as they requested.
(Why no issue when Input invoked from menu, no idea :)

**Comment by poire-z** [comment]
This seems to solve the issue (but as it's uimanager wild territory, I won't go there alone :) so pinging @NiLuJe - or we might want to wait after release to fix that):

```diff
--- a/frontend/ui/uimanager.lua
+++ b/frontend/ui/uimanager.lua
@@ -318,8 +318,9 @@ function UIManager:close(widget, refreshtype, refreshregion, refreshdither)
     widget:handleEvent(Event:new("FlushSettings"))
     -- first send close event to widget
     widget:handleEvent(Event:new("CloseWidget"))
-    -- make it disabled by default and check any widget that enables it
+    -- make it disabled by default and check if any widget wants it disabled or enabled
     Input.disable_double_tap = true
+    local requested_disable_double_tap = nil
     -- then remove all references to that widget on stack and refresh
     for i = #self._window_stack, 1, -1 do
         if self._window_stack[i].widget == widget then
@@ -333,11 +334,15 @@ function UIManager:close(widget, refreshtype, refreshregion, refreshdither)
                 logger.dbg("Lower widget", self._window_stack[i].widget.name or self._window_stack[i].widget.id or tostring(self._window_stack[i].widget), "was dithered, honoring the dithering hint")
             end

-            if self._window_stack[i].widget.disable_double_tap == false then
-                Input.disable_double_tap = false
+            -- Set double tap to how the topest that specified how it wants it want it
+            if requested_disable_double_tap == nil and self._window_stack[i].widget.disable_double_tap ~= nil then
+                requested_disable_double_tap = self._window_stack[i].widget.disable_double_tap
             end
         end
     end
+    if requested_disable_double_tap ~= nil then
+        Input.disable_double_tap = requested_disable_double_tap
+    end
     if dirty and not widget.invisible then
         -- schedule remaining widgets to be painted
         for i = 1, #self._window_stack do
```

**Comment by Frenzie** [comment]
I actually solved a similar issue with the screensaver a couple of years ago (except in that case properly resolving which widget was the topmost for drawing purposes). We'll need at least a few more days prior to release so this might just be on the safe enough side of risky.

**Comment by Frenzie** [comment]
Besides some more finishing touches on the multiswipes (mainly defaults & some actions) #4708 is a prerequisite. I'd also like to have #4667 finished to ensure an optimal F-Droid first impression.

**Comment by poire-z** [comment]
Another thing would be to disable double tap by default, or altogether.
It seems only used by readerolling to double tap in the 1/4 top left & right corners to go to prev/next chapters.
Otherwise, it will just make tap'ing feels slow to new users (that have not yet disabled it).

**Comment by NiLuJe** [comment]
Yeah, that seems a more sensible default if it's barely used anywhere.

**Comment by Frenzie** [comment]
But double tap *is* disabled by default, isn't it?

**Comment by poire-z** [comment]
Oh, looks like it is :) sorry. And good for me to not have to look at that!

**Pull request merged**
