### PR TITLE
remove autofrontlight + backgroundrunner

### PR DESCRIPTION
**Pull request by pazos**
The plugin cannot be moved to contrib as is. It relies on the backgroundrunner plugin, no longer available. It needs to be updated to execute their tasks based on events or similar.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12809)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by Frenzie** [comment]
There's also the spec file (see CI).

**Comment by pazos** [comment]
> There's also the spec file (see CI).

Thanks! Done!

Also removed the backgrounrunner plugin.

**Review by Frenzie — APPROVED** [review]

**Comment by Hzj-jie** [comment]
As I have mentioned in one of the previous change, this is one of the very important reason I chose a voyage. It seems a very poor decision to remove a working fine feature because I do not use it. The statement of `It relies on the backgroundrunner plugin, no longer available` is very confusion. Why doesn't it work?

**Comment by pazos** [comment]
@Hzj-jie: Please try to enable "some" github notifications. I've tried to warn you in advance: https://github.com/koreader/koreader/issues/12854#issuecomment-2524021118

The reason for removal of the backgroundrunner is in https://github.com/koreader/koreader/issues/12637 and was agreed between current maintainers.

The reason for removal of the autofrontlight is: it seems a trivial plugin that can be reimplemented standalone (without relying on the backgroundrunner). It is also enabled by default, which causes troubles with new users trying to understand why the program doesn't abide to the settings they setup.

A good place for the plugin (as-is sans the backgroundrunner dependencies) is `contrib`. I think nobody here will opose to have the plugin back this repo as long as its behaviour its opt-in.

**Comment by Frenzie** [comment]
It goes back to https://github.com/koreader/koreader/issues/12567#issuecomment-2383558633 and https://github.com/koreader/koreader/issues/12567#issuecomment-2388782466

(though I don't necessarily agree with the it should be disabled by default pov)

Apologies for not pinging you at the time.

I don't think anyone's against reintroducing it slightly updated.

**Comment by pazos** [comment]
Just closed some related tickets. If/when the plugin is reintroduced I will open them again. Nothing is final here.

**Pull request merged**
