### PR TITLE
Terminal emulator: satisfy CI doc

### PR DESCRIPTION
**Pull request by zwim**
Locally make doc works with this, maybe CI will also work?

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8742)

### CODE REVIEW

**Comment by Frenzie** [comment]
As in locally first it didn't work and with this change it did?

**Comment by zwim** [comment]
With this change `make doc` works at least locally, before it dit not. 
So I assume it will work on CI. Anyway it is just a change in comments. Let's try.

**Comment by zwim** [comment]
Shall I merge it and see what happens?

**Comment by Frenzie** [comment]
I was just double checking because you made it sound like you were trying something at random. But if that's the way to interpret what you wrote then there's no "see what happens"; it'll just work. ;-)

**Comment by zwim** [comment]
Thanks for checking, but if I'd really try something an random, I will warn Warn WARN your :) :-)

**Pull request merged**
