### PR TITLE
A bunch of trivial tweaks

### PR DESCRIPTION
**Pull request by NiLuJe**
Followups to #8739 & a "fix" for #10134 (I don't recall how we're supposed to handle HTTP -> HTTPS redirects the "right" way).

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10135)

### CODE REVIEW

**Comment by Frenzie** [comment]
> (I don't recall how we're supposed to handle HTTP -> HTTPS redirects the "right" way).

That's permitted; only the opposite isn't.

**Comment by NiLuJe** [comment]
Does `http.request` magically handles the swap to `https.request` then? Or does that only work if we *start* by calling `https.request` (even if the URL is technically still HTTP at that point)?

**Comment by Frenzie** [comment]
The latter should probably work, the former logically can't. ;-)

**Comment by NiLuJe** [comment]
> The latter should probably work, the former logically can't. ;-)

Then a proper fix would be to switch to `https.request` in there ;).

**Comment by Frenzie** [comment]
Eh, I don't know, it's been a few years since I implemented that stuff. My relevant PR should link to the info.

https://github.com/koreader/koreader/pull/6307

> To be clear, LuaSocket automatically calls LuaSec when appropriate. That way it also provides redirect support to LuaSec. LuaSec itself is still very much required.

https://github.com/koreader/koreader-base/issues/594#issuecomment-484233915

**Comment by Frenzie** [comment]
It's possible it doesn't actually support 308 even though it should? I have no desire to investigate at this time though.

```
$ curl -I http://www.dicionario-aberto.net/resources/stardict-DicAberto.tar.bz2
HTTP/1.1 308 Permanent Redirect
Location: https://www.dicionario-aberto.net/resources/stardict-DicAberto.tar.bz2
Date: Sat, 18 Feb 2023 17:23:23 GMT
Content-Length: 18
Content-Type: text/plain; charset=utf-8
```

**Pull request merged**
