### PR TITLE
reMarkable 2 clean wakeup from sleep

### PR DESCRIPTION
**Pull request by snelg**
Solution for #7139 
Also requires a small update to the [Installation on ReMarkable](https://github.com/koreader/koreader/wiki/Installation-on-ReMarkable) wiki page. I don't know if there's a fancy way to coordinate wiki changes with PRs or Releases.
The required wiki change is inserting this after step 3 in the "Manual installation" section:

```
4. **reMarkable 2** only, copy the "wake input" workaround script to systemd:
    ```
    cp -v koreader/rm2-wake-input.sh /lib/systemd/system-sleep/
    ```
```
and then incrementing the remaining existing steps.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7345)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Not sure if it's worth going down that road, but I just realized that by bundling the script in the platform folder, it actually ends up in the release package... which means you could arguably install it in the KOReader launch script (we do run as root on rM, right?).

**Comment by snelg** [comment]
Just ran a simple test, and that idea works. Systemd didn't need a reboot/reload/whatever, it just went ahead and ran the `rm2-wake-input.sh` script that my tweaked launch script copied into `/lib/systemd/system-sleep/`

But I'm also not sure if copying scripts into systemd folders during launch is a road we want to go down. I know the scope of hacks/workarounds varies greatly between the different types of devices; are any of the others doing something like this?

**Comment by NiLuJe** [comment]
> But I'm also not sure if copying scripts into systemd folders during launch is a road we want to go down. I know the scope of hacks/workarounds varies greatly between the different types of devices; are any of the others doing something like that during launch?

Nope, none., that's usually bundled with the prerequisites/launcher situation.
At most we bundle configuration (or equivalent) files for launchers to register ourselves with, but that's it.

**Comment by Eeems** [comment]
This likely wont play well with other things in the reMarkable ecosystem. For sure it wont play well with Xochitl if you don't grab key events and it's somehow listening. It might be better to just listen to systemd's resume event through dbus.

**Comment by snelg** [comment]
> For sure it wont play well with Xochitl if you don't grab key events and it's somehow listening.

I tested it and xochitl seemed unaffected (to my surprise)
https://github.com/koreader/koreader/issues/7139#issuecomment-785379777
But yeah, this definitely feels like an ugly hack that probably won't play well with *something* else that people use.

> It might be better to just listen to systemd's resume event through dbus.

I'm happy to keep hacking at this if someone will point me in the right direction. I have no idea how to listen to systemd's resume event through dbus :)

**Comment by Eeems** [comment]
https://github.com/Eeems/oxide/blob/master/applications/system-service/systemapi.h#L66
If you are using Qt you'd do something similar to that.

Likely you'll want to use dbus-monitor and dbus-send instead.

**Comment by NiLuJe** [comment]
c.f., https://github.com/koreader/koreader-base/blob/master/input/input-kindle.h for a similar approach (except with Amazon's slightly-less-insane DBus wrapper).

**Comment by snelg** [comment]
Welp [cracks knuckles], guess I'll have to actually set up a toolchain. So far the tweaks I've done have all been in the .lua files, or direct CLI stuff like this. I haven't had to compile C code yet for this project...

**Comment by snelg** [comment]
Alternate solution: https://github.com/koreader/koreader-base/pull/1318
If that gets approved and merged, then I'll update this PR to completely *remove* the LUA code workaround

**Comment by snelg** [comment]
`koreader-base` version bump, and corresponding rm2 workaround removed from `frontend/device/remarkable/device.lua`

**Review by NiLuJe — APPROVED** [review]

**Pull request merged**
