### PR TITLE
Allow any device with networkmanager enabled to have wifi status in the footer

### PR DESCRIPTION
**Pull request by BrainDamage**
Tested on my Kobo H2O2 and gave a read at the code, should work on other platforms as well.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/5511)

### CODE REVIEW

**Comment by Frenzie** [comment]
Not on Android, where kernel modules aren't involved.

The reason Android is hard-coded is that it's the only platform that can currently do it async. The #3078 type stuff is a bit in limbo.

**Comment by NiLuJe** [comment]
Hard veto. It's blocking on most devices, which is why we don't do it ;).

**Comment by Frenzie** [comment]
Basically blocking for about 10-20 ms is the best case scenario.

**Comment by NiLuJe** [comment]
And even if it weren't blocking, on most devices, the check implies *at least* a fork(), which would be enough to warrant a veto for the footer IMHO ;).

**Comment by BrainDamage** [comment]
on embedded devices, can we assume we're the only managers of the wifi connection?
if yes, it could just be checked at startup/wakeup, and save the state, then it'd be as fast as reading a variable

**Comment by Frenzie** [comment]
That's how it should function from the footer's perspective regardless (not with a fork *for the footer* ;-) ), and as a simple on/off indicator (as opposed to connected) I figure something like that would do the trick.

**Comment by NiLuJe** [comment]
That might not always hold true.

On Kobo, we inherit whatever the state was on startup (unless it happened
to be very broken, In which case we kill wifi).

On Kindle, we defer to the system.

As do we on PB I think.

So that would require some finaggling on startup to get an accurate idea of
the actual state. But, yeah, that would definitely make more sense ;).

**Comment by NiLuJe** [comment]
There's the `NetworkConnected` event. It might not cover all bases, but it's probably a good start ;).

**Comment by pazos** [comment]
I'm closing this one.

**Comment by Frenzie** [comment]
Basically good visual change in theory, unfortunately unworkable in practice for the moment. :-)

**Pull request closed without merging**
