### PR TITLE
Update OTA mirrors

### PR DESCRIPTION
**Pull request by NiLuJe**
Drop outdated mirror
Relocate mine, and give them actually accurate names given their location

### CODE REVIEW

**Comment by NiLuJe** [comment]
I don't know who was handling the dropped mirror to give 'em a line, sorry :x.

I also can't access the CN mirror, so I can't tell if it's still up to date ;).

I kept the legacy subdomains around for backward compat (they should now both point to -fr, which happens to actually be the old -af [don't ask me why/how I chose that suffix, I don't know, but at least it's made it obvious that it was terrible, since I don't even remember what it was supposed to mean ^^].

**Comment by NiLuJe** [comment]
Side remark: I'm not seeing any kindle build making it to the nightly/OTA master since 1667, any ideas?

**Comment by Frenzie** [comment]
Oh, that must be the change from kindle to kindle5. (And by sheer coincidence the legacy Kindle build failed today.)

The builds themselves can always be obtained from https://gitlab.com/koreader/nightly-builds/-/jobs before koreader.rocks grabs 'em (but the Android build won't be signed properly).

Regarding the mirrors I know I asked @houqp about it somewhere and I was planning to act on it but forgot all about it. :blush:

**Comment by Frenzie** [comment]
@NiLuJe Kindle builds should be up soon. (Of course I forgot to add the AppImage while I was at it.)

**Comment by NiLuJe** [comment]
:+1:

**Pull request merged**
