### PR TITLE
always directly reference advanced status bar settings

### PR DESCRIPTION
**Pull request by derungs**
fix for #5411

### CODE REVIEW

**Comment by poire-z** [comment]
In your issue, you meant that there are not picked up instantly - but they work when you restart KOReader, right?

So, yes, I guess it's bothering that these updated global variables are not picked up instantly by the ReaderFooter instance - expecially when testing and trying to find the right value.
But I guess it's the same for all these advanced/global variables.
And as we tried to get rid of these global variables (keeping them to still allow some tuning for past users), it's a bit bothering too to see them reintroduced that much :)

**Comment by derungs** [comment]
Actually, they weren't picked up after restart. After restart I'd see the old values again.
Other advanced settings, like DMINIBAR_TOC_MARKER_WIDTH, get picked up immediately.

**Comment by derungs** [comment]
Are you suggesting to add these tweaks to the status bar settings? If yes, I'd be willing to add these to the settings. I would appreciate a hint as to which classes to start with, since I'm new to the project.

**Comment by poire-z** [comment]
>  Other advanced settings, like DMINIBAR_TOC_MARKER_WIDTH, get picked up immediately.

Does it survive a restart?
Because testing on the emulator, nothing gets saved :| I always see the previous values.
Anyway, I guess what people do usually is manually add the ones they wish to change, by copying them from [defaults.lua](https://github.com/koreader/koreader/blob/master/defaults.lua) to a new file named `defaults.persistent.lua` - see https://github.com/koreader/koreader/wiki/Change-defaults

> Are you suggesting to add these tweaks to the status bar settings?

Well, I don't know. These might be "niche" settings. Could you post a screenshot of what kind of footer you're trying to achieve?
And there might be combinations and inter-relations to ensure, so they might be merged into 1 or 2 settings that would influence the sizing that used these 3 variables.
The idea is that if we make them into settings, they become stuff stored inside G_reader_settings (settings.reader.lua) and the global variables will be killed.

> If yes, I'd be willing to add these to the settings. I would appreciate a hint as to which classes to start with, since I'm new to the project.

Well, see some of the [latest commits by @robert00s](https://github.com/koreader/koreader/commits?author=robert00s) who added recently many new footer menu items/settings.

**Comment by Frenzie** [comment]
As written this is a definite no-go I'm afraid.

> Actually, they weren't picked up after restart. After restart I'd see the old values again.

Then it sounds like the issue is that they aren't in fact saved. That should be unaffected by the changes in this PR.

**Comment by derungs** [comment]
Mainly, I need the font bigger so I can read it, and the progress bar a bit higher, again for visibility. I agree that 1 setting for everything makes sense, especially since the container makes most sense at the same height as the font, and the progress bar can be tailored to look ok-ish in comparison, e.g. 2/3 or 1/2 of the font height.

**Comment by poire-z** [comment]
> Then it sounds like the issue is that they aren't in fact saved

OK, found out how to have them saved (not intuitive, but I guess that's a hint these should not be used :)
Once you have edited some of them, you need to quit the settings list, and go back to the menu, and HOLD on the menu item "Advanced settings": then, a confirm box appears and only then defaults.persistent.lua is created.

**Comment by Frenzie** [comment]
@poire-z Settings are saved on exit. See https://github.com/koreader/koreader/issues/5411#issuecomment-533909130

Why not immediately I'm not sure…

**Comment by poire-z** [comment]
^ Oh, right :)

**Comment by Frenzie** [comment]
@poire-z I can't reproduce the issue though; perhaps I'm actually thinking of something subtly different or I fixed it. It asks me before exiting.

Screenshot_2019-09-22_21-26-59

**Comment by poire-z** [comment]
Yes, it was me who exited the emulator with the Esc/Backspace key, so not via the regular Exit menu item (which calls setDefault:saveSettings() indeed). Not really an issue then.

**Comment by Frenzie** [comment]
Right, I meant I couldn't reproduce it by pressing Alt+F4/X. I can indeed reproduce by pressing Escape.

**Comment by NiLuJe** [comment]
From what I recall, *every* **sane** exit/reboot codepath we have should be wrapped in that check, so, yeah, that would leave "unexpected" exits ;).

**Comment by Frenzie** [comment]
@NiLuJe @poire-z I think I was actually more directly thinking of this issue rather than the Escape thing: https://github.com/koreader/koreader/issues/4225#issuecomment-472177043

**Pull request closed without merging**
