### PR TITLE
Vocabbuilder.koplugin: make db migration allow starting from intermediate stage

### PR DESCRIPTION
**Pull request by weijiuqiao**
Use pcalls to protect each migration step.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9702)

### CODE REVIEW

**Comment by NiLuJe** [comment]
We might want to log the errors, though, because I think they're swallowed by pcall right now ;).

**Comment by weijiuqiao** [comment]
Added logging, should be alright now.

**Comment by NiLuJe** [comment]
Assuming there's no sane way to have SQL do the work for us, :lgtm: ;).

**Comment by Frenzie** [comment]
Without the pcall the program crashes?

**Comment by NiLuJe** [comment]
I apparently managed to break it on my Forma, somehow, apparently, yeah: https://github.com/koreader/koreader/issues/9678#issuecomment-1293005056

**Comment by poire-z** [comment]
> I haven't looked at how ugly that would make the code, but it probably makes sense regardless ;).

It looks quite a bit ugly indeed :/ vs. the original code we can have indented and commented.
I wonder if we should really handle such edge cases (and how it could have happened to @NiLuJe...).
Or we would have to revisit all our past (and not forget for the future) DB updates to make them ugly too with individual pcalls :/
But as it's just for this plugin, well, ok if you think it's worth it.

**Comment by weijiuqiao** [comment]
It must be two PRs added them separately. Let me fire another PR to solve it :)

**Comment by Frenzie** [comment]
That's also part of why we normally just stick the `local logger = require("logger")` at the top.

**Comment by weijiuqiao** [comment]
At the time, logger was only needed in migration, so I figured maybe have it inside the method is better. However, the sync function brought logger too, so when both are merged, the issue came out...

**Pull request merged**
