### PR TITLE
[plugin:text-editor] Fix potential crash when opening a file with the text-editor

### PR DESCRIPTION
**Pull request by ghost**
Fix a potential crash when trying to open a file with the text-editor (and with debug info on).

The bug only hits us if the text editor wants to open/show a path, which does not exit (because it was deleted by hand...).

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11448)

### CODE REVIEW

**Comment by poire-z** [comment]
Probably not really/only TextEditor related, as you touch only CoverBrowser :)
Letting @hius07 confirm it's the right fix, if a similar thing shouldn't happen also in mosaicmenu.lua, and if there's no bigger issue underneath.

**Comment by hius07** [comment]
Can you tell how to reproduce.
We have
https://github.com/koreader/koreader/blob/b8090c641c64471c514fba4aaac2cff066118cd1/plugins/texteditor.koplugin/main.lua#L418-L429

**Comment by hius07** [comment]
I still get the ConfirmBox with "This file does not exist anymore".
Can you show your crash.log.

**Comment by hius07** [comment]
Thank you. I propose more generic fix for the issue, a check of the target folder existance:
```Lua
function FileChooser:init()
    self.path_items = {}
    if lfs.attributes(self.path, "mode") ~= "directory" then
        self.path = lfs.currentdir()
    end
    self.item_table = self:genItemTableFromPath(self.path)
    Menu.init(self) -- call parent's init()
end
```
instead of
https://github.com/koreader/koreader/blob/b8090c641c64471c514fba4aaac2cff066118cd1/frontend/ui/widget/filechooser.lua#L233-L237

**Pull request closed without merging**
