### PR TITLE
Chinese keyboard: accept kanji stroke order too

### PR DESCRIPTION
**Pull request by weijiuqiao**
This PR will make the stroke-based chinese character keyboard compatible with japanese kanji stroke order, with an increase of the data file by about 80kb. 

This could be a temperary solution for japanese users to type kanji before better methods are implemented.

The stroke order data are extracted from this repo: https://github.com/KanjiVG/kanjivg. @cyphar It would be great if you could help check some common ones.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11620)

### CODE REVIEW

**Comment by Frenzie** [comment]
I'll bump this to the next release hoping for someone who knows more about Japanese to provide feedback, unless you're sufficiently confident?

**Comment by cyphar** [comment]
I'll test this over the weekend, though since the source is KanjiVG I would expect the stroke order information to be accurate for Japanese (as long as it was parsed correctly).

**Comment by Frenzie** [comment]
Thanks! I decided to simply merge it. ;-) Btw, how did you extract the data?

**Comment by weijiuqiao** [comment]
I based on code from this repo https://github.com/pankeiki/strokes2kanji and made some adjustments :)

**Pull request merged**
