### PR TITLE
Update el_keyboard.lua

### PR DESCRIPTION
**Pull request by ichnilatis-gr**
Adding of variable acu for Greek acute key and creation of a new popup menu on the Greek acute key for Greek numeral signs.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8319)

### CODE REVIEW

**Comment by ichnilatis-gr** [comment]
Did I fix it?

**Comment by ichnilatis-gr** [comment]
I can't understand. It looks like it's aligned, like you want it to be.
https://github.com/ichnilatis-gr/koreader/blob/2bcd548ecab8f3c67941da678bd563dfba0a909a/frontend/ui/data/keyboardlayouts/keypopup/el_popup.lua#L12-L17

**Comment by Frenzie** [comment]
We want it aligned with 4 spaces per indentation, no tabs. ;-)

**Comment by ichnilatis-gr** [comment]
Is it OK now?

**Comment by ichnilatis-gr** [comment]
Is everything OK with this or do I need to do something else to close this issue? I expect the maintainers to do this.

**Comment by ichnilatis-gr** [comment]
You're right. I understand that it's annoying to constantly create separate issues for each change. But unfortunately I have limited time... Next time (if there is a next time) I will try to compile all the changes together.
For the time being, I'm committed to making no more changes, so that the October release is not delayed in closing because of me.

**Pull request merged**
