### PR TITLE
TimeSync: Double-check that ntpd is busybox

### PR DESCRIPTION
**Pull request by NiLuJe**
Kindle ships another implementation, with incompatible syntax...

Regression since #10935
Thanks to @yparitcher ;).

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10992)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
lol

**Review by yparitcher — APPROVED** [review]

**Comment by yparitcher** [comment]
Kindles `ntpd` is not in `/usr/sbin` it is in `/usr/bin`

**Comment by NiLuJe** [comment]
> Kindles `ntpd` is not in `/usr/sbin` it is in `/usr/bin` so it doesn't even need a symlink check

Yeah, that was a very convoluted way to say "Device:isKobo()" ^^.

I didn't really want to do the PATH searching myself to find where `ntpd` is, and busybox *will* always symlink it there, so it sorta does the job, and hopefully it *will* actually match somewhere that isn't Kobo (possibly rM?) ^^.

**Comment by NiLuJe** [comment]
Eh, PATH searching was way more trivial after a good night's sleep ;p.

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/10992)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by hius07** [comment]
https://github.com/koreader/koreader/blob/38a14ff3a070d0d31d9d7d369863d0af5390ae16/plugins/timesync.koplugin/main.lua#L14
On my Voyage with firmware 5.9.6 this line causes `sh: command: not found` in crash.log, and the plugin is disabled.

**Comment by Frenzie** [comment]
`command` is POSIX (and normally built into the shell, compare `command -v command` with `command -v grep` in… probably all shells?)
https://pubs.opengroup.org/onlinepubs/9699919799/

I suppose skipping the `command -v` wouldn't do much harm, though on the flip side I wouldn't expect anything to work in such an environment.

I'm curious what @NiLuJe will say. ;-)

**Comment by NiLuJe** [comment]
Yeah, it's harmless, and we don't really have a better way to handle PATH resolution ourselves without reinventing the wheel ;).

**Pull request merged**
