### PR TITLE
bump android-luajit-launcher

### LINKED ISSUE #12098: (Android) Unable to open PDFs after update
* KOReader version: 2024.04.209-g617618d58_2024-06-25
* Device: Huawei Mate 20 (hma-l29)
* OS: Android Q, api 29 on arm 
* Build flavor: rocks

#### Issue

After just updating OTA to the latest nightly, KOReader won't open any PDF files anymore and reports "No reader engine for this file or invalid file."

#### Steps to reproduce

Try to open any PDF/DJVU file with KOReader. 

<details>
  <summary>crash.log</summary>

```
--------- beginning of main
06-26 13:12:24.775 E/reader.launche( 9811): LoadAppImageStartupCache enabled : 1
06-26 13:12:24.781 E/reader.launche( 9811): Not starting debugger since process cannot load the jdwp agent.
06-26 13:12:24.816 E/BehaviorCollectManager( 9811): Fail to acquire dataAnalyzerService...
06-26 13:12:24.900 E/iGraphics( 9811): can not load local debug xml
06-26 13:13:30.977 E/reader.launche(10320): LoadAppImageStartupCache enabled : 1
06-26 13:13:30.981 E/reader.launche(10320): Not starting debugger since process cannot load the jdwp agent.
06-26 13:13:31.045 E/BehaviorCollectManager(10320): Fail to acquire dataAnalyzerService...
06-26 13:13:31.097 E/iGraphics(10320): can not load local debug xml
06-26 13:13:54.868 E/dlopen  (10320): error dlopen'ing /data/user/0/org.koreader.launcher/files/libs/libk2pdfopt.so.2: dlopen failed: cannot locate symbol "android_getCpuFamily" referenced by "/data/data/org.koreader.launcher/files/libs/libk2pdfopt.so.2"...
06-26 13:13:54.868 E/KOReader(10320): error: [string "dl.lua"]:73: error dlopen'ing /data/user/0/org.koreader.launcher/files/libs/libk2pdfopt.so.2: dlopen failed: cannot locate symbol "android_getCpuFamily" referenced by "/data/data/org.koreader.launcher/files/libs/libk2pdfopt.so.2"...
06-26 13:13:54.868 E/KOReader(10320): error: [string "dl.lua"]:167: could not find library /data/user/0/org.koreader.launcher/files/libs/libkoreader-djvu.so

```
</details>

Thank you.

### PR DESCRIPTION
**Pull request by pazos**
* prune old assets before uncompressing new ones.
* move Poke5 to OnyxAdb driver

Fixes #12098

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12147)

### CODE REVIEW

**Comment by benoit-pierre** [comment]
AFAIK, #12098 was not due to old assets, but missing symbols (due to https://github.com/koreader/koreader-base/pull/1837, fixed in https://github.com/koreader/koreader-base/pull/1841).

**Comment by Frenzie** [comment]
Indeed, but on Android it's not a bad idea regardless.

**Comment by benoit-pierre** [comment]
Agreed.

**Comment by pazos** [comment]
Ah, ok. Sorry about the confussion :p

**Pull request merged**
