### PR TITLE
Fix connection bug with non-ASCII SSIDs in wpa_supplicant

### PR DESCRIPTION
**Pull request by wfdewith**
Connecting to non-ASCII SSIDs does not work, and I did not actually if #10864 fixed it. It turns out that it didn't, so here is a PR that actually fixes it.

The UTF-8 decoding of SSIDs is specific to wpa_supplicant. In this patch, we move all of this decoding logic to the wpa_supplicant module. We expose the raw bytes of the SSID to the NetworkMgr code, and make sure to always fix bad UTF-8 before we display the SSID to the user.

Within the wpa_supplicant module, we replace the call to the wpa_passphrase binary to get the PSK with a direct function call to OpenSSL. This allows us to calculate the PSK over any arbitrary bytes, including UTF-8. In the same vein, we use the hex-encoded SSID to communicate with wpa_supplicant when setting up the network to support arbitrary bytes in the SSID.

Unfortunately, we also remove the tests, as there is no way to unit test local functions.

This PR depends on koreader/koreader-base#1693 and cannot be merged before base has been updated to reflect those changes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11089)

### CODE REVIEW

**Review by NiLuJe — APPROVED** [review]
Sounds sensible ;).

(I assume the "WIP" tag is because of the base PR not being merged yet, and not that you're not entirely done with code changes?)

**Comment by wfdewith** [comment]
> (I assume the "WIP" tag is because of the base PR not being merged yet, and not that you're not entirely done with code changes?)

That's correct. How do you deal with these kind of dependencies?

**Comment by NiLuJe** [comment]
> That's correct. How do you deal with these kind of dependencies?

Either with a comment in the first post, a title tag like you did, or marking the PR as draft until it actually includes the bump. Dealer's choice ;).

(The base PR has now been merged, so you're now free to bump base in this one).

**Comment by NiLuJe** [comment]
For ref, includes:

https://github.com/koreader/koreader-base/pull/1691
https://github.com/koreader/koreader-base/pull/1692
https://github.com/koreader/koreader-base/pull/1689
https://github.com/koreader/koreader-base/pull/1690
https://github.com/koreader/koreader-base/pull/1693

**Pull request merged**
