### PR TITLE
[Android] Update icon to new logo

### PR DESCRIPTION
**Pull request by Frenzie**
Includes
https://github.com/koreader/android-luajit-launcher/pull/83

References
koreader/koreader-icons#1
koreader/koreader#3881
koreader/koreader#3858
koreader/koreader#2000

### CODE REVIEW

**Comment by NiLuJe** [comment]
FWIW, I just pushed a resize that fits the Kobo thumbnails perfectly for KFMon [here](https://github.com/NiLuJe/kfmon/commit/b9cd507f7b59646c89a7d8154925474d8bdc6501).

I *think* that's the only platform we use resources/koreader.png, so let me know if you want a PR for that, sicne that needed an aspect ratio switch (1 -> 0.75).

**Comment by NiLuJe** [comment]
It's probably not *bad*, nickel just prefers stuff a little bit more portait-y than square (that worked pretty well with the old logo, it probably won't as well with this one).

This doesn't actually answer your question, but here's how my version looks ;p.

ko_library
ko_home

**Comment by Frenzie** [comment]
@NiLuJe Okay, I merged my PR so that it's done before I go to bed (and don't have time tomorrow). The image can be moved without changes if desired so it won't bulk up the Git repo.

**Comment by Frenzie** [comment]
Heh, I hadn't looked at your actual screenshot beyond glancing at the logo. I read La Guerre de Troie n'aura pas lieu about five years ago. Wasn't bad. ;-)

**Comment by NiLuJe** [comment]
I have *no* idea by which miraculous algorithm it ended on my homepage, because I literally haven't touched it in I don't know how long :D.

**Pull request merged**
