### PR TITLE
[UX] Add left to close to ConfigDialog for hasFewKeys

### PR DESCRIPTION
**Pull request by Frenzie**
Follow-up to <https://github.com/koreader/koreader/pull/6195>.

Part of <https://github.com/koreader/koreader/issues/4029>.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/6318)

### CODE REVIEW

**Comment by Frenzie** [comment]
@roshavagarga This combined with https://github.com/koreader/koreader/pull/6315 should take care of the worst.

**Comment by roshavagarga** [comment]
Thanks for the heads up and for the hard work! :)

**Comment by Frenzie** [comment]
Btw, besides manually replacing the files you can always grab the latest nightly from http://build.koreader.rocks/download/nightly/

That's the same as running update from within the program (after selecting the "development" channel) but that may be problematic without the horizontal wrap around in place.

**Comment by roshavagarga** [comment]
@Frenzie Installed 20.07.1 (hadn't checked the device since these merges) - left as close works for most windows, but does not work for the statistics window. Getting out of that one requires a full-blow shutdown and restarting the device, since no buttons help.

**Comment by Frenzie** [comment]
@roshavagarga It's supposed to close on any keypress whatsoever, but the problem is that it's only on hasKeys() and not on hasDPad. It's probably an issue just with statistics and not with the overall logic behind these things but I'm not 100% sure. :-)

https://github.com/koreader/koreader/blob/b4d5cfccb79cf749bee83311b9b54899c1052c19/plugins/statistics.koplugin/readerprogress.lua#L60-L66

**Comment by Frenzie** [comment]
Could you check if this works satisfactorily?

```diff
diff --git a/plugins/statistics.koplugin/readerprogress.lua b/plugins/statistics.koplugin/readerprogress.lua
index 84c3650a..527a712c 100644
--- a/plugins/statistics.koplugin/readerprogress.lua
+++ b/plugins/statistics.koplugin/readerprogress.lua
@@ -57,7 +57,7 @@ function ReaderProgress:init()
     UIManager:setDirty(self, function()
         return "ui", self.dimen
     end)
-    if Device:hasKeys() then
+    if Device:hasDPad or Device:hasKeys() then
         self.key_events = {
             --don't get locked in on non touch devices
             AnyKeyPressed = { { Device.input.group.Any },
```

**Comment by roshavagarga** [comment]
@Frenzie Nope, it does not.
Tried your line, also tried:
1. `if Device:hasDPad or Device:hasFewKeys or Device:HasKeys() then`
2. `if Device:hasDPad() or Device:hasFewKeys() or Device:HasKeys() then` 

None of the above worked. The left and right buttons weirdly enough let me scroll through the 3 stats pages, but the DPad does nothing.

**Comment by Frenzie** [comment]
@roshavagarga That's combined with the relevant device definitions? It works for me.

**Comment by roshavagarga** [comment]
@Frenzie 2020.07.1 stable on a PocketBook 614W, which already had a proper definition - changing that plugin file does nothing for me when I open device stats, issue persists sadly.

**Pull request merged**
