### PR TITLE
[CI] Upgrade to new Docker image

### PR DESCRIPTION
**Pull request by Frenzie**
Cf. https://github.com/koreader/koreader-base/pull/1375 (no dependency).

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7775)

### CODE REVIEW

**Comment by NiLuJe** [comment]
(Busted < 2.0.0-1 is horribly broken. Hell, even *that* is broken, too. Ideally, we should be running scm-2 (scm-1 is broken, too), but it's not on Luarocks, only in the upstream repo).

**Comment by Frenzie** [comment]
@NiLuJe 
> (Busted < 2.0.0-1 is horribly broken. Hell, even that is broken, too. Ideally, we should be running scm-2 (scm-1 is broken, too), but it's not on Luarocks, only in the upstream repo).

We use(d) 2.0.0-1. It works for me locally and it's always worked. Could you expand a bit on what you think the problem is?

**Comment by Frenzie** [comment]
Actually I just realized the Docker images comes with busted preinstalled and 2.0.0-0 at that. So this is both a wasted effort and possibly futile if there's a slight hiccup somewhere.

**Comment by NiLuJe** [comment]
We basically need https://github.com/Olivine-Labs/busted/commit/2dfff99bda01fd3da56fd23415aba5a2a4cc0ffd not to horribly blow up because of our use of ffi.metatype & ffi.gc.

That isn't in anything else other than scm-2, which isn't on Luarocks.

**Comment by Frenzie** [comment]
> We basically need Olivine-Labs/busted@2dfff99 not to horribly blow up because of our use of ffi.metatype & ffi.gc.

That doesn't help though.

**Comment by NiLuJe** [comment]
Then it's something else ;/. A backtrace might help.

(FWIW, I'm running scm-2 here and everything passes).

**Comment by Frenzie** [comment]
> (FWIW, I'm running scm-2 here and everything passes).

As I said, everything passes regardless of the version here. ;-)

It's on CircleCI that it segfaults.

**Pull request closed without merging**
