### PR TITLE
View HTML: adds Prettify button to CSS viewer, other fixes

### PR DESCRIPTION
**Pull request by poire-z**
- Cleanup onSetStatusLine() 
- ReaderDictionary:dismissLookupInfo(): avoid forceRePaint()
- View HTML: adds Prettify button to CSS viewer

Details in the commit messages.

The CSS Prettify turns this:
<kbd>image</kbd>
into:
<kbd>image</kbd>

### CODE REVIEW

**Comment by Frenzie** [comment]
It looks like it might mess things up in some cases.

**Comment by poire-z** [comment]
> Is there a reason for the style sheet to be displayed "UnPretty"/ without the formatting? 

Mostly because I like to see the original state of things (and what's fed to crengine): the original CSS content of the book may be minified and unreadable in some books, but it may as well already be pretty in other books, with some other defaults for spacing, indentation, some comments, multiple line feeds to separate sections...

And because the prettification is a bit quick and rough (a few regexps, no real css grammar rules), and it may mess with the original CSS code (I hope not, but for example, any comma in a comment will make a new line, so `/* Deal with paragraphs, lists, tables */` will make 3 lines once prettified.

And there are some "choices" I made in the prettification that help reading some CSS, but that does not look super nice in others.
Eg, our original Wikipedia EPUB CSS looks like:
<kbd>image</kbd>
But once prettified:
<kbd>image</kbd>

So, it's more like an alternative view :)

**Comment by cramoisi** [comment]
@poire-z : am I blind ? I can't find the option to view html / css aymore

**Comment by cramoisi** [comment]
(boah, ok, it's only available if document > highlight action is "ask with popup dialog"  :) )

**Pull request merged**
