### PR TITLE
Set Rendering Style, and Comments

### PR DESCRIPTION
**Pull request by comradekingu**
As reported by https://www.transifex.com/user/profile/slow_mo/ :)

### CODE REVIEW

**Comment by Frenzie** [comment]
The comment was referring to the Italian translation `cambia modalità di rendering`.

> it_IT
First letter should be uppercase
by slow_mo, 2 months ago 

Screenshot of 'Set render style' in menu context


Regarding the phrase itself, I have no trouble with `render style` vs. `rendering style` (cf., [Microsoft](https://msdn.microsoft.com/en-us/library/aa650536(v=vs.71).aspx), [2](https://msdn.microsoft.com/en-us/library/system.web.ui.mobilecontrols.command.format(v=vs.110).aspx), [3](https://msdn.microsoft.com/en-us/library/cc294766.aspx), [4](https://msdn.microsoft.com/en-us/library/aa711700(v=vs.71).aspx); [pCon.planner](http://help.pcon-planner.com/en/help/index.html?render_styles.htm)). However, I would just get rid of the useless `render(ing)`.

Could you please change the phrase to simply `Set style`?

**Comment by comradekingu** [comment]
@Frenzie Ok, in line with why that makes sense:
Style:
Highlighting:
Floating punctuation:
Font:
Hyphenation:
?

**Comment by Frenzie** [comment]
Go for it. :-)

**Comment by Frenzie** [comment]
@comradekingu Is there anything you need assistance with? I'd like to include your proposed changes.

**Pull request merged**
