### PR TITLE
Bump base & android

### PR DESCRIPTION
**Pull request by NiLuJe**
There's also a CRe update in there ;).

(Rebase me)

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12434)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Right, the CI failure is because `dimRect` was renamed, c.f., #11044 ;).

**Comment by Frenzie** [comment]
What does that mean in practice? To merge that right after?

**Comment by NiLuJe** [comment]
Yup!

**Comment by poire-z** [comment]
For info (@benoit-pierre I guess), when git pull in front to get this:
```
From https://github.com/koreader/koreader
   d51179690..60e0e3ef4  master     -> origin/master
Fetching submodule base
From https://github.com/koreader/koreader-base
   93cf3e0e..af76de4f  master     -> origin/master
fatal: exec 'rev-list': cd to 'thirdparty/kpvcrlib/crengine' failed: No such file or directory
    ^^^^  is this expected?
Fetching submodule base/thirdparty/kpvcrlib/crengine
Fetching submodule platform/android/luajit-launcher
From https://github.com/koreader/android-luajit-launcher
   981e9c8..a3836f0  master     -> origin/master
Updating d51179690..60e0e3ef4
```

**Comment by Frenzie** [comment]
Same, but it seemed to be a singular occurrence.

**Comment by benoit-pierre** [comment]
Looks like a git bug: https://lore.kernel.org/git/1647006095912.1308641200.2893260369@vivaldi.com/, which git versions?

**Comment by benoit-pierre** [comment]
No issues there with 2.46.0.

**Comment by poire-z** [comment]
Debian's git 1:2.39.2-1.1

**Comment by Frenzie** [comment]
2.39.2 (Debian 12/bookworm) and 2.43.0 (Kubuntu 24.04)

> No issues there with 2.46.0.

Like I said though, singular.

**Pull request merged**
