### PR TITLE
[hotfix] Version: empty pattern match is an empty string, not nil!

### LINKED ISSUE #4298: koreader-appimage crashes on start
* KOReader version: koreader-appimage-x86_64-linux-gnu-v2018.11.AppImage
* Device: Arch 

crash log:

It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 11/01/18-11:08:33
 [*] Version: v2018.11

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load (assisted searchpath): ./libs/libSDL2.so
ffi.load: SDL
ffi.load: SDL
11/01/18-11:08:33 INFO  initializing for device SDL
11/01/18-11:08:33 INFO  framebuffer resolution: {
    ["h"] = 800,
    ["w"] = 600
}
ffi.load: libs/libfreetype.so.6
./luajit: frontend/version.lua:33: attempt to perform arithmetic on a string value
stack traceback:
	frontend/version.lua:33: in function 'getNormalizedVersion'
	frontend/version.lua:42: in function 'getNormalizedCurrentVersion'
	frontend/ui/quickstart.lua:17: in main chunk
	[C]: in function 'require'
	./reader.lua:99: in main chunk
	[C]: at 0x00404960

### PR DESCRIPTION
**Pull request by Frenzie**
Fixes #4298.

### CODE REVIEW

**Comment by Frenzie** [comment]
This also fixes OTA updates, but updating from an older version to v2018.11 (or any future stable) will unfortunately not be possible due to this very issue. I'll add a unit test for it.

But, there's also good news! OTA updating to the next nightly will work just fine, which will automatically include this fix.

**Comment by Frenzie** [comment]
@NiLuJe It occurs to me that the current nightly/ota cleaning script would start kicking out the stable OTA in its current form.

Currently we have these files:

```
koreader-pocketbook-arm-obreey-linux-gnueabi-v2018.11.1.targz
koreader-pocketbook-latest-nightly.zsync
```

Now technically I think the zsync is all we need and the targz is just there to potentially regenerate it? Nevertheless, I don't think we'd want `koreader-pocketbook-arm-obreey-linux-gnueabi-v2018.11.1.targz` to be kicked out by a couple of weeks of nightlies.

Of course this is really just a missing part of nightswatcher with the shellscript as a quick hack, and since OTA updating to a stable has been accidentally broken by yours truly for about two years (?) it won't bother us too soon yet, but it _is_ an impending infrastructure issue. ;-)

**Comment by NiLuJe** [comment]
Indeed... I think we can fairly easily exclude those tags from the cleanup, but that then leaves another question of how to clean those tags themselves, because we possibly won't have space to keep a bajillion of them either ;).

Also, about the original issue: tought of it too late, sorry :/. It made it to my TODO list, but the one for "bright ideas for tomorrow" when already in bed... :D.

**Comment by Frenzie** [comment]
Maybe we should cron `apt autoremove` (as root)? I just ran that manually and it cleaned up 5 GB worth of old Linux kernels.

Also see this pre-KOReader blogpost ;-) https://fransdejonge.com/2013/11/on-upgrading-xubuntu/

**Comment by NiLuJe** [comment]
That gives us a bit more space, yeah ;).

I'll check tomorrow when we have a long tag in there again, but I can probably re-jig the script to treat stable & OTA separately, keeping N of them each ;).

**Comment by Frenzie** [comment]
I just manually cleaned out the OTA dir and copied the current zsync files for the stable branch. (I was going to look into the nightswatcher Python script to automate that but I should probably call it a day instead.) In theory that means that versions from before April 13, 2017 (https://github.com/koreader/koreader/pull/2761) should now be able to OTA update to the latest stable. With the additional caveat that versions from before November 8, 2016 (https://github.com/koreader/koreader/commit/d6aa3b9c8cce3179bb9eb674b0e096a820882d37) aren't configured with `ota.koreader.rocks`.

**Comment by NiLuJe** [comment]
:1:

Thanks again for the last few days of boring maintenance work! :)

**Comment by Frenzie** [comment]
> That gives us a bit more space, yeah ;).

Btw, I also removed 500+ MB worth of Java, Ant, x11-common and all the libraries that entails. I guess those either came installed by default or there was some pre-Docker experimentation lurking around, but those were very much redundant. See https://github.com/koreader/koreader-misc/blob/14c2bf91e35099a41b32d7c01d3df34c8307b788/nightswatcher/Dockerfile#L7

> Thanks again for the last few days of boring maintenance work! :)

Same on the TC stuff. ;-) I just stick to the default Debian/Ubuntu ARM stuff and call it a day.

**Pull request merged**
