### PR TITLE
UI fonts customization menu

### PR DESCRIPTION
**Pull request by charrarr**
Demo video:

https://github.com/user-attachments/assets/52e24f4c-da21-4d27-8210-8cec9b942846

Also, long-pressing on "Custom UI Fonts" shows some help text explaining what the font categories are for. "Choose file" is not shown in the demo because it doesn't work on the emulator (the working directory is not koreader/), but it is working on my Kobo. It lets you select variants other than bold (In case you want KOReader to look more like Nickel, for example).

A less visible part of this PR is that it modifies some basic widgets like buttons to deal with less predictable font sizes. A common strategy in the widgets is to create Text(Box)Widgets or face objects with decreasing font sizes until the result fits a certain UI element. This logic could use some optimization to deal with the now potentially bigger font sizes (==> more iterations to find a fit). The only slowdown I've noticed on my device is a delay in initially opening the top and bottom menus after a restart, while all the iterated font face-size pairs get cached.

If you have fonts hardcoded in an old font.lua file, you can keep using it :) The menu just won't do anything.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12635)

### CODE REVIEW

**Comment by pazos** [comment]
Thanks for the contribution!

When doing non trivial changes on the UI it is always preferred to open a ticket first and get some feedback there. I'm a kind of a weirdo here that doesn't have an opinion on most things UI wise. But plenty of people care and some might have strong opinions for their own very good reasons. It is usually easier to argue when there's no work yet attached and it is always a pity to ditch a PR because the lack of consensus.

Please consider it for the next time :)

> Now no-one can say KOReader is ugly ✨

Are you really, really sure? 😄

**Comment by charrarr** [comment]
@pazos Oops - thanks for explaining it to me.
> Are you really, really sure? 😄
Well, it's a step in that direction :)

**Comment by mergen3107** [comment]
As of now, I still use a user patch to replace the main UI font my liking :D 
https://github.com/koreader/koreader/issues/9951#issuecomment-1367915946

**Comment by poire-z** [comment]
> Now no-one can say KOReader is ugly ✨

You're saying it :)
I know some people find it ugly, but it's not really the best entrance to come here saying it to the face of the people who made the beautiful applicationt _they think_ it is :)
(I always thought Kobo Nickel may look better to some people because it uses a Serif font fot its UI, which obviously appeals to book readers.)

Anyway, not fond of it:
- there's a bit of some jargon ("primary", ...) and some new UI technical stuff (a filemanager to select font files outside of the ones KOReader knows about? that we never needed) that makes it a bit too hacky/complex for the normal user - and a bit out scope (it does not enhance the reading experience)
- there's some use of cre.engineInit() (not sure why, vs. the filemanger allowing selection of font files outside of cre realm), that I think we avoid doing it until really needed (ie. reading an EPUB or viewing some SVG file, or browsing book for covers & metadata). Which might be why it felt slow ?
- there is a little added complexity to font.lua - that we were fine without, and that we will never test (except @mergen3107 our font freak :)) when making some changes
- there may be some possible sizes & baselines mismatch when using fallback fonts (ie. to display book title in Hebrew or Chinese), that we avoid by using the NotoSans family. Using another main font may increase the risk. Ok, people who do read non-classic scripts just don't have to use the feature - but still, if we ship a feature, we'd like it to be 100% quality.
- using/enforcing our NotoSans font brings some consistency
- I'm really not sure (from your video) that another font makes it nicer :) Yes, it may be fun playing with it, but I'm not certain one will find something better.

> When doing non trivial changes on the UI it is always preferred to open a ticket first and get some feedback there.[...] it is always a pity to ditch a PR because the lack of consensus.

I guess @pazos somehow got the same (or imagined my) feeling when writing this.
Indeed, if you have asked, I would have said this is best left to user patch: let people play & hack & find out what works for them: we don't need a UI to make it easier (with the side effects I mentionned above).

If really wanting to make it more than a user patch, with a font selection filemanager UI and a more complex menu, I'd rather see it as a (contrib) plugin, that could plugin-user-patch font.lua if needed.

**Comment by charrarr** [comment]
@poire-z Thanks for writing up a reply. I didn't mean to come in here insulting anyone - I've removed that line. The point was that it's nice for less technical or patient users who aren't a fan of Noto Sans.

> jargon ("primary", ...)

Making the help tooltip more visible would clear it up.

> filemanager [...] too hacky/complex for the normal user - and a bit out scope (it does not enhance the reading experience)

This feature needs more explanation. It opens to the system fonts or koreader/fonts, both of which KOReader knows about. If you select from a different directory, there's an error message telling you about koreader/fonts. The purpose of the file selection is to pick X-Italic, X-BoldItalic, etc. that KOReader *knows* about, but does not present to the user normally, though they could be queried by CRE. Anyway, I'm inclined to agree it's out-of-scope from the reading experience perspective.

> there's some use of cre.engineInit()

That's how the reader font selector does it. I think the garbage collector will scoop it up?

> there is a little added complexity to font.lua - that we were fine without, and that we will never test (except @mergen3107 our font freak :)) when making some changes

In that case, I'm perfectly happy with making this PR a user patch or plugin as you said.

> there may be some possible sizes & baselines mismatch when using fallback fonts (ie. to display book title in Hebrew or Chinese), that we avoid by using the NotoSans family.

You could choose a Hebrew or Chinese font as easily as any other.

> using/enforcing our NotoSans font brings some consistency

Of course.

> I'm really not sure (from your video) that another font makes it nicer :) Yes, it may be fun playing with it, but I'm not certain one will find something better.

I'm not sure what you mean. There aren't enough font freaks in the world? Or too many categories?

> if you have asked, I would have said this is best left to user patch
> If really wanting to make it more than a user patch, with a font selection filemanager UI and a more complex menu, I'd rather see it as a (contrib) plugin, that could plugin-user-patch font.lua if needed.

I'll look into those plugin-user-patches.

**Pull request closed without merging**
