### PR TITLE
Make luacheck >= 0.26 happy

### PR DESCRIPTION
**Pull request by NiLuJe**
Re: https://github.com/koreader/koreader-base/pull/1487

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9174)

### CODE REVIEW

**Comment by Frenzie** [comment]
I'm afraid I don't like this PR much. I definitely appreciate the effort though. :-)

With regard to the _ stuff, I haven't found the time to submit a patch to upstream luacheck to make the specifics configurable, but I don't think changing what's `pos` everywhere to `coords` is helpful when reading in the way `_pos` is. Perhaps `coords` is a better name, but then logically it should be `_coords` or `coords_` because `pos` will also have been changed to `coords`.

And I'm not at all fond of the logic changes either. The dumb algorithm that should keep its stupid mouth shut about which way we decide the logic is most expressive and comprehensible about its intent.

Related: `https://github.com/awesomeWM/awesome/issues/3627`

**Comment by Frenzie** [comment]
I take back what I said about the logic changed. I think those look like improvements, meaning I think luacheck makes sense there and no global override is necessary in my eyes, only (theoretically) local ones.

**Comment by poire-z** [comment]
Well, when reading first @Frenzie 's comment, I was fearing there would be lots of changes in many of (my) places :)
But it's very limited, so I won't mind.
(I still prefer reading `_self` than `this` - with `_self`, you know it refers to some lua object that might not be the current `self`. With `this`, I feel like having a journey into some other language like Javascript or Java :)
May be a one line comment just in readerhighlight.lua above the first use of `this` saying `this` will be actually our `self` here - might help future readers of this bit of code (more popuular than CreDocument)

**Comment by Frenzie** [comment]
I'd rather use `self_` iff [sic] we decide we want to use that type of _ prefixed to mark unused.

**Comment by NiLuJe** [comment]
> I'd rather use `self_` iff [sic] we decide we want to use the `_self` style prefix to mark unused.

That would have been my choice if I hadn't already peppered a few `this` across the codebase ;p.

**Pull request merged**
