### PR TITLE
Create a keybinding to access the hold-item menu

### PR DESCRIPTION
**Pull request by onde2rock**
Quick edit to be able to open the hold menu on non touch devices.

The naviguation in the hold menu need a bit of getting used to, but it's fully useable.

### CODE REVIEW

**Comment by poire-z** [comment]
Tested on the emulator, and it solves https://github.com/koreader/koreader/pull/3745#issuecomment-373179443
It's a bit different than how it did before, but it allows selecting all the buttons, so it's fine.

Just mentionning the differences (if I remember correctly):
Before, if on the 3rd column, when going down to a line with only 2 buttons, you went to the 2nd button.
With this, you're stuck on the line with 3 buttons, you need to go left to the the 2nd button to be able to go down. But you can still reach them all :)

**Comment by onde2rock** [comment]
Yes, the naviguation is a bit weird. I'm starting to run into the limitations of the focusmanager, same with the reader.

I don't really see a better way to support complex layout with the focusmanager remaining generic.

I didn't even know this menu existed until recently reading the code, so this was a nice surprise.

**Comment by Frenzie** [comment]
While generally preferable, there's no requirement that it remain generic. Or more concretely, generic FocusManager should stay but if something specific is required you can make a FocusManagerSomeSpecialCase. Of course that'll be eyed with much scrutiny. :-P

**Comment by poire-z** [comment]
I can merge this if you consider it done, so you can start from fresh with your next PR?

**Comment by onde2rock** [comment]
Hum ok, I will try to make fixes to the naviguation weirdness in another PR

**Pull request merged**
