### PR TITLE
Show OTA channel info when package is unavailable

### PR DESCRIPTION
**Pull request by chrox**

### CODE REVIEW

**Comment by chrox** [comment]
@NiLuJe Our framebuffer driver reports the width resolution to be 1072. Is this x resolution different from the resolution in fbinfo?

**Comment by NiLuJe** [comment]
@chrox: No, that's perfectly right ;).

I was simply referring to the eips bug/feature in which it's actually relying on the *virtual* xres, not the actual effective one, for some strange reason.

Which happens to be 1088 on the KV ;). Unfortunately, I can't quite remember where the eips -i log I got that from is right now... Possibly somewhere on MR in one of the initial teardown threads.

**Comment by chrox** [comment]
Yes, the virtual xres of framebuffer on KV is 1088.
```
/mnt/us/koreader # /usr/sbin/eips -i

Fixed framebuffer info
    id:              mxc_epdc_fb    smem_start:       0x81000000
    smem_len:            6782976    type:          PACKED_PIXELS
    type_aux:                  0    visual:   STATIC_PSEUDOCOLOR
    xpanstep:                  1    ypanstep:                  1
    ywrapstep:                 0    line_length:            1088
    mmio_start:       0x00000000    mmio_len:                  0
    accel:                     0

Variable framebuffer info
    xres:                   1072    yres:                   1448
    xres_virtual:           1088    yres_virtual:           6144
    xoffset:                   0    yoffset:                   0
    bits_per_pixel:            8    grayscale:                 1
    red.offset:                0    green.offset:              0
    red.length:                8    green.length:              8
    red.msb_right:             0    green.msb_right:           0
    blue.offset:               0    transp.offset:             0
    blue.length:               8    transp.length:             0
    blue.msb_right:            0    transp.msb_right:          0
    nonstd:                    0    activate:                128
    width:                    91    height:                  122
    accel_flags:               0    pixclock:           83333333
    left_margin:              16    right_margin:            104
    upper_margin:              4    lower_margin:              4
    hsync_len:                26    vsync_len:                 2
    sync:                      0    vmode:                     0
    rotate:                    3
```

**Comment by NiLuJe** [comment]
Right, thanks! Now I dimly remember asking someone for a screenshot and checking if the dimensions of one eips block of character matched the PW, and it does, so apart from that weird xres thing, the rest should be accurate ;).

**Pull request merged**
