### PR TITLE
Icons: CRe partial rendering icons

### PR DESCRIPTION
**Pull request by NiLuJe**
Re: https://github.com/koreader/koreader/issues/9087#issuecomment-1416743867

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10086)

### CODE REVIEW

**Comment by NiLuJe** [comment]
240px composite on white bg:

CRe_partial_r1

**Comment by NiLuJe** [comment]
I ditched the "two documents" approach because it looked way too cluttered (and, also, I suck at masking stuff properly ;p).

This, admittedly, makes the reload icon slightly weird. (Would perhaps make sense to base it on the "pristine" document instead of the glitched one).

Also, might have to unify the stroke width for the gear/reload.

**Comment by NiLuJe** [comment]
Also: [repeat](https://github.com/Templarian/MaterialDesignLight/blob/master/svg/repeat.svg) instead of refresh might work better for the reload icon.

(I stayed away from it because the design *very much* screams music player, but...).

**Comment by mergen3107** [comment]
Gear and arrow being “stuck” between the document border lines is bad for readability, IMO. Can you make white/black round cutout in these corners? So, like, the top right corners have round “cut placeholders” where the gear and arrow are located.

**Comment by NiLuJe** [comment]
There's already a white outline in place for that, thickness may have to be adjusted depending on how it looks on device :).

**Comment by poire-z** [comment]
Thanks!

<kbd>icons1</kbd>

Looks a bit better on my Kobo.

> This, admittedly, makes the reload icon slightly weird. (Would perhaps make more sense to base it on the "pristine" document instead of the glitched one).

Sure, no reason to get the sliced one after the "ready".
(I really like the "pristine" shinny one :))

> Also, might have to use a greater stroke width for the gear/reload.

Yes, really greater :) Hardly noticable in there.
Also, may be in the bottom right if it does not look too ugly (in the top right, it may be a bit masked by the bezel or its shadow.


> Also: [repeat](https://github.com/Templarian/MaterialDesignLight/blob/master/svg/repeat.svg) instead of refresh might work better for the reload icon.

Yes, better something with a shape different than the processing one (squared rather than round, for easier distinction.
Or just a reload circle bigger and over/centered ?
We're blocked when this is shown, so anything in the way/different is good :)

Also, appbar.typeset.svg image as the base (for the slicing, and the pristine too?) may look cleaner/ less chargé (with the uneven segments, which once shifted, make it less look like it's the same object) than appbar.pageview.svg image, dunno.

**Comment by poire-z** [comment]
>  So, like, the top right corners have round “cut placeholders” where the gear and arrow are located.

Can't make round cuts with mspaint :) but do you mean something like this ?

image

**Comment by NiLuJe** [comment]
> > So, like, the top right corners have round “cut placeholders” where the gear and arrow are located.
> 
> Can't make round cuts with mspaint :) but do you mean something like this ?
> 
> image

Right now, it's the other way around because I put the gear *behind*, but the thichkness can be adjusted (I just need to start from scratch because I suck at this, right now the outline eats into the actual stroke width, so I'd need to start from a thicker stroke to have a thicker outline without making the stroke too thin ;p)

I could also put the gear on *top* (while still keeping an outline), like in your example?

**Comment by NiLuJe** [comment]
Oh, hey, forgot to attach the screenshot, rofl.

Screenshot_20230206_020827

**Comment by NiLuJe** [comment]
(Said screenshot kinda reveals why I started with such a thin outline: it was mainly for that *chef's kiss' alignment between the gear's spoke and the glitch'ed side stroke ;p).

**Comment by NiLuJe** [comment]
> Also, appbar.typeset.svg image as the base (for the slicing, and the pristine too?) may look cleaner/ less chargé (with the uneven segments, which once shifted, make it less look like it's the same object) than appbar.pageview.svg image, dunno.

Yeah, I didn't try with the straight one, because I thought the unevenness would emphasize the glitch effect, but it's a valid concern ;).

**Comment by NiLuJe** [comment]
> I could also put the gear on _top_ (while still keeping an outline), like in your example?

Yeah, that'll probably look better, or at the very least make the thing more obvious (and it will *definitely* help for the repat icon, because that one looks very bad if behind).

**Comment by NiLuJe** [comment]
> (I really like the "pristine" shinny one :))

I'm glad I barely managed to avoid the "hey, look, I'm a page with stick figure legs" feeling :D.

**Comment by NiLuJe** [comment]
Okay, the gear one indeed looks much better this way.

Not entirely happy with the refresh one, though; I'll see how it looks with the refresh...

**Comment by NiLuJe** [comment]
There, better (slight caveat, it's a filled circle, so less alpha).

**Comment by NiLuJe** [comment]
> There, better (slight caveat, it's a filled circle, so less alpha).

We probably lose a lot of clarity, especially at small sizes, if we get rid of the cutout, though:

Screenshot_20230206_030940

**Comment by poire-z** [comment]
Quite neat ! (with the non-alpha under the gear/reload part, I guess):
<kbd>icons2</kbd>

(but my list item markers get sometimes too near the text, once partially rerendered... :( )

**Comment by NiLuJe** [comment]
> Had quick try with removing the "text lines" to make it less crowded, but not as obvious it is a document icon:

One other option would be to fill the "page" background in white (while keeping the "outside" transparent)?

**Comment by poire-z** [comment]
It would look as on my left screenshot above, still not obvious.
But the set is really fine and consistent: thin, non-obtrusive or eye catching, though still apprehendable, and the changes are noticable if you focus your eyes on it - but if you read the book, you're not distracted. So, really nice !
So we'll go with that. People with other ideas can propose some alternate set (I think we can override icons by putting some with the same name in a dir under koreader/).
Needs a few more days of polishing on my side.

**Comment by poire-z** [comment]
Dunno if this was on purpose, but 2 of these icons are not fully transparent:
image image
Only noticable when not on a white background, which is rare - and it's transient and not ugly - so not a big deal :)

**Pull request merged**
