### PR TITLE
Fix regression (introduced in #9657)

### LINKED ISSUE #9741: Crashes after Power off gesture
* KOReader version: 2022.10-50
* Device: Pocketbook 628

#### Issue
When I make the gesture I have set for powering off the device, a crash occurs. I set another gesture for this action but I had the same result.

##### `crash.log` (if applicable)
[crash 3-11-2022.txt](https://github.com/koreader/koreader/files/9930676/crash.3-11-2022.txt)

### PR DESCRIPTION
**Pull request by zwim**
This should fix #9741.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9759)

### CODE REVIEW

**Review by poire-z — APPROVED** [review]

**Comment by Frenzie** [comment]
Might also fix #9748, depending on whether I simply never noticed in two years (not impossible, we're talking about power off after all) or whether it's actually a fairly new issue.

**Comment by NiLuJe** [comment]
@Frenzie: Nah, that's an earlier fix of mine ;).

**Review by NiLuJe — APPROVED** [review]

**Comment by zwim** [comment]
After a quick look, I would bet that #9748 should be fixed, too. (Tthe code cited in https://github.com/koreader/koreader/issues/9748#issuecomment-1304576586 should not be reached as we are doing a `os.execute("sleep 1 && poweroff -f &")` in `device.lua`

**Comment by NiLuJe** [comment]
@zwim: The sleep and backgrounding are *especially* there so that we *do* reach the exit codepaths after an UIManager:quit ;).

**Comment by NiLuJe** [comment]
It is surprisingly... weird. I originally caught it because the previous brokenness was actually attempting to restart Nickel *during* the poweroff, and that's pretty obvious because of the boot animation (especially when it's KFMon's).

**Comment by Frenzie** [comment]
Confirmed that the behavior remains the same. Wrt my statement that it was a few seconds, I was probably counting thirds of a second. Seconds are surprisingly long really. :-)

**Pull request merged**
