### PR TITLE
[feat] Add ReaderBack

### LINKED ISSUE #3816: Hardware back button does not work on Android
Hardware buttons used to work, like pressing back would go back or exit koreader. Now it does not work. It does nothing.

I tested it with v2015.11-1606-g3ead3f0_2018-03-28 on Lollipop.

thanks

### PR DESCRIPTION
**Pull request by Frenzie**
This implements a reasonable facsimile of going back on Android.

The back button first goes back in a history of visited pages.
When there's no history left, it closes the app.

Fixes #3816.

### CODE REVIEW

**Comment by onde2rock** [comment]
Nice, that was quick! Add a quick test and now the back key need to revert every page turned before exiting, is it supposed to do that ?

Page4 `Back` Page3 `Back` Page2 `Back` Page1 `Back` finally exit

**Comment by Frenzie** [comment]
Yes, it's the described Android way. :)

**Comment by onde2rock** [comment]
Hum, sorry to bring that up again but it bother me a litlle. Wouldn't it be more intuitive to revert only the 'jump' in naviguation ?
I don't consider normal page turning to need a revert option. Only when using goto, or footnote, in which case this behavior is expected and usefull.

Is this even possible to do ? I will try to look at the code just in case it's an easy fix.

**Comment by Frenzie** [comment]
That wouldn't have required the least bit of effort. :-(

**Comment by poire-z** [comment]
Where did my _backspace to close the emulator_ go ?! :|

I see this PR makes somehow that be do'able with the <kbd>ESC</kbd> key. And I too find it quite ridiculous to have to hit it 20 times to quit :)
But well, it's the <kbd>ESC</kbd> key, that is on the other side of the keyboard from where the other arrow keys are, so I won't be using it much :)

But how do I get my backspace back?
Was it removed on purpose, or is it just a side effect of #3815 and it being renamed from `Back` to `Backspace` ?
Should I add it back? With a G_reader_settings conditional? Or can I use a custom even map as #3822 offers (but then, I could only remap <kbd>ESC</kbd> to <kbd>backspace</kbd>) ?
Any other suggestion?

**Comment by Frenzie** [comment]
Just stick `[42] = "Back"` in a custom event map.

> Was it removed on purpose

Yes, definitely. The behavior is still terrible but I haven't quite come up with a good plan to fix it yet.

Parts of the ideas floating around:

* To sensibly implement the Android behavior might just mean a different default setting on Android but the ability to switch it off on Android and on on other platforms.
* Esc = Up and something else (maybe even backspace) = Back.
* The Close event asks for permission first!
* Multiple actions per key — simple in principle, but in practice it might need to be more like "back *OR* up" instead of "back *AND ALSO* up"

**Comment by onde2rock** [comment]
> The Close event asks for permission first!

That's pretty good. That would be a good default settings so people can discover this functionality, and if they want to modify this behavior, maybe a setting with onExit: {close,ask,ignore}

There's only two places in koreader where it can exit, so shouldn't be too complicated.

**Comment by Frenzie** [comment]
Sure, you could go ahead and add that. It might be a touch more complicated because when "do you want to save X or Y" is triggered you probably don't want an extra "do you want to quit" on top of that. And there's the Android default situation to take into account.

So `back_is_quit` would be something like 
```lua
if g_settings:has("back_is_quit") then
  back_is_quit = isTrue
elseif isAndroid then true
else false
```

Then there's also back_is_up which would adjust the event but that can wait.

**Comment by onde2rock** [comment]
Sure, will look into it.

**Comment by poire-z** [comment]
> Just stick [42] = "Back" in a custom event map.

Thanks, that works (to move ESC to backspace).

I was thinking about adding something like:
```lua
 function ReaderBack:onBack()
     local location_stack = self.location_stack

-    if #location_stack > 1 then
+    if G_reader_settings:nilOrTrue("back_history_enable") and #location_stack > 1 then
         local saved_location = table.remove(location_stack)

         if saved_location then
```
(with this, backspace quits immediately as I like it :)
But I guess something like that will be available with the above `back_is_quit` suggestion ?

Also, may be readerback (or only some methods) should be a no-op on devices that don't currently allow onBack() (touch-only devices) - so we don't go adding some stuff to location_stack that will never be used (I know it doesn't use much memory - but well :)

**Comment by Frenzie** [comment]
> But I guess something like that will be available with the above back_is_quit suggestion ?

It's been long since I've been so frustrated with the program as the constant quitting I've experienced for the past two weeks. It's like a crash, but for some reason on purpose! :-(

I was still gestating the ideas until a later date, but basically:

* back_is_quit is an Android thing generalized as an option for people who for some reason really like quitting the program *and* seem to think it should be done differently from other programs on their computer. :-P Android has system-wide temporal back so that's how it should (try to) behave there. I don't think it should throw up an annoying prompt as a general principle either, but that can be one of the options.
* back_is_up (or something like that) goes up instead of back. Not quite sure how to go about that yet but it might suffice to just ignore the back history.

> Also, may be readerback (or only some methods) should be a no-op on devices that don't currently allow onBack() (touch-only devices) - so we don't go adding some stuff to location_stack that will never be used (I know it doesn't use much memory - but well :)

Or a "Go back" menu item.

**Comment by poire-z** [comment]
> It's been long since I've been so frustrated with the program as the constant quitting I've experienced for the past two weeks.

I have no real opinion about how it _should_ behave according to specs, common UI behaviour, ... so, I'm not stopping you on implementing a correct behaviour :)
I just want, even with a hidden setting, the exact previous behaviour that was there for years (and that did not bother you before two weeks ago? - and even if it did, it's been a feature, for _me_ :) : launch the emulator (to develop!), see how things look, a few arrow key strokes, quit with the near backspace, all with my right hand - repeat many times.
(If I don't get that back, it's me who will be frustrated developping :) and I don't want to add that back as a custom koreader patch - I want a clean git of it - adding stuff in `settings/event_map.lua` or `settings.reader.lua` would be ok thus).

On Android, I don't really mind how it should behave. I (personally, me only?) have another problem: I use (well I'm not really using it for reading) it fullscreen, so the bottom android buttons are not shown. And when I swipe up from the bottom to make it appear, the swipe up registers also as a document swipe, and It moves to next page. So I don't use that menu, even for switching apps or going to home screen :| . I quit with koreader's menu Exit...
You wrote somewhere else that other android reading apps don't implement _back goes back_, but may be their authors realize that it's a bit annoying with a reading app that you have a 50 pages back stack, and that _back goes up_ makes more sense (which I would agree with - but I'm not a heavy android apps user, so no real conviction on that - but _back is up, and if nothing is up, quits_ looks natural to me - the android specs are not the Word of Go~~ogle~~d that we should follow blindly).



> Or a "Go back" menu item.

On touch devices, I think we don't really need this, we can just tap. And it would just add confusion with _Go back to previous location_.

**Comment by Frenzie** [comment]
> that did not bother you before two weeks ago?

It did in a vague corner of my mind, but using keyboard or gamepad on our touch app wasn't usable anyway. Thanks to @onde2rock that's different now.

> You wrote somewhere else that other android reading apps don't implement back goes back

Some do, some don't. But they all implement up (from the reader meaning "history" or "file browser"). Many, perhaps most notably various Google apps such as Google Play Newsstand, implement it incorrectly. They go up even when it should be quit (because you directly opened a document/video without ever going through the home screen).

Others (notably Dropbox for a while) implemented it wrong in the opposite direction, meaning you could never reach the home screen. It's better to err in the other direction.

>  it's a bit annoying with a reading app that you have a 50 pages back stack, and that back goes up makes more sense

That means you lose the ability to actually go back like you're supposed to. At the very least go to link and go to page (also through bookmark/toc) should be part of the history stack by default (which they also are in Document Viewer and Lithium).

ReadEra does this weird thing where by default it only quits the app if you double tap back. The weird part being that it only does so if you opened the app directly, without a document. So you still get booted out of the document, including when you opened a file directly through a file manager, just not out of the app. I don't really understand why they went through the trouble of protecting the least destructive exit.

> On touch devices, I think we don't really need this, we can just tap. And it would just add confusion with Go back to previous location.

The only reason I wrote this is because I thought it could be a decent compromise, but I'm not sure if "nobody likes it" is really the best compromise. :-P Maybe it'd be better to (partially) remove this then?

**Pull request merged**
