### PR TITLE
Mixed file and folder sorting

### PR DESCRIPTION
**Pull request by robert00s**
Close: #4068
Details: https://github.com/koreader/koreader/issues/4068#issuecomment-408516062 and
the final solution: https://github.com/koreader/koreader/issues/4068#issuecomment-409724111

### CODE REVIEW

**Comment by poire-z** [comment]
Sorry for the merge conflicts (due to #4133).

**Comment by robert00s** [comment]
Please check but should be fine.

**Comment by poire-z** [comment]
Looks fine.
(I would suggest to move the new item higher, just below its brother "Sort by title" - but then #4067 which aimed at renaming it to _Sort by filename_ would have a conflict :)

**Comment by robert00s** [comment]
I will move now item higher after merging this and #4067 as separate PR.

**Comment by poire-z** [comment]
Merging? Or you want to move up and remane `Sort by title - mixed files and folders` to... mhhh... `Sort by filename - mixed files and folders` (strange?), or `Sort by name- mixed files and folders` ?

**Comment by robert00s** [comment]
`Sort by name - mixed files and folders` is much better.

**Comment by poire-z** [comment]
Merging ? Or you want to change the name and/or move it up?

**Comment by robert00s** [comment]
Ok, I think it's ready to merge.

**Comment by Frenzie** [comment]
I missed this, but generally speaking en-dashes (`–`) are preferable and this is no exception.

**Pull request merged**
