### PR TITLE
Don't shadow gettext

### PR DESCRIPTION
**Pull request by NiLuJe**
Fixes the "current book" stats page.

(Regression in #6796)

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/6799)

### CODE REVIEW

**Comment by ezdiy** [comment]
Oops, force of habit (and rather unfortunate of GT to collide with lua convention). Still, use `-- luacheck: ignore 211` to retain the original intent.

**Comment by NiLuJe** [comment]
Random related comment: where the hell is the ID-to-error mapping hidden for LuaCheck? Every time I wonder where those magic number come from, i just give up and use a global plain ignore ;).

**Comment by NiLuJe** [comment]
https://luacheck.readthedocs.io/en/stable/warnings.html

Well, that wasn't so hard :D

**Comment by poire-z** [comment]
> Add a hint that we do want to ingore the first arg 

Isn't this already taken care of by:
https://github.com/koreader/koreader/blob/893909146d6e406ca36c5f2d95b82526a4ed6167/.luacheckrc#L143-L152

**Pull request merged**
