### PR TITLE
util: Add removePath

### PR DESCRIPTION
**Pull request by NiLuJe**
Will attempt to prune empty directories from the given path, going as far back up as possible.

Re: #10074

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10129)

### CODE REVIEW

**Comment by NiLuJe** [comment]
It's 4AM and I've been hunting for a PSU all night, so, err, review carefully ;p.

(Ran a few tests locally, looks sounds, though).

**Comment by NiLuJe** [comment]
```
> print(removePath("/"))
true    nil
```

I'll take that as a win ;p.

**Comment by hius07** [comment]
Can I propose something like
```Lua
function util.removePath(path)
    local function doRemove(dirpath)
        local upper_path = BaseUtil.dirname(dirpath)
        if os.remove(dirpath) then
            doRemove(upper_path)
        end
    end
    doRemove(path)
end

```

**Review by Frenzie — APPROVED** [review]

**Comment by NiLuJe** [comment]
c.f., https://git.musl-libc.org/cgit/musl/tree/src/misc/dirname.c

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/10129)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NiLuJe)

**Pull request merged**
