### PR TITLE
russian keyboard layout improvement from mergen3107

### PR DESCRIPTION
**Pull request by houqp**
This is the new keyboard layout proposed by mergen3107 in https://github.com/koreader/koreader/pull/2029. Let's discuss it here.

### CODE REVIEW

**Comment by Frenzie** [comment]
I don't know anything about Cyrillic layouts. The current layout appears to be the "YaZHert" (яЖерт) variety. See http://web.archive.org/web/20160310035217/http://winrus.com/print_e.htm

**Comment by mergen3107** [comment]
Russian layout
So this is the most used Russian layout - I intentionally found a picture with both English and Russian layouts together. You can clearly notice that letters (х,ъ), (ж,э), (б, ю) on the right and ё to left from number 1 in the corner are outside English-substitutes (by substitutes I mean the keys, where I put Russian letters).

So what I did: 
1) For keys from 26-letter matrix I just copied Russian layout as it is;
reader_2016-may-17_174955

2) For those 7 outside letters I put them into Sym on the right, so that they could found very easily and quickly;
reader_2016-may-17_175003

3) Numeric keypad in Sym I changed from linear to block type for the sake of step (2)
4) The rest of space was filled by 9 Kazakh letters (the magically fitted exactly all left space between numeric block and Russian letters.
5) For shifted symbol in Sym I used some characters on places of numbers and shifted letters.
reader_2016-may-17_175021

Hope you like it!
Thank you!

**Comment by Frenzie** [comment]
It definitely seems more sensible to default to the most common layout.

**Comment by houqp** [comment]
Alright, I factor out the keyboard layout into a loadable file so it's easier to turn it into a configurable option in the future.

I only suggestion so far is to make the number to symbol mapping in shift mode more consistent with what's on the physical keyboard. I.e. `1 -> !`, `2 -> @`, ..., etc. Any objection?

@mergen3107 , how did you come up with the current symbol mapping layout?

**Comment by mergen3107** [comment]
@houqp 
good suggestion! Actually I was trying to  fit the most used symbols randomly
I'll think on that on the weekend

**Comment by houqp** [comment]
OK, I have changed the layout so that it matches with the number to symbol mapping on standard US keyboards. Please review :)

**Comment by mergen3107** [comment]
@houqp 
I'll check this out soon :)

**Comment by mergen3107** [comment]
@houqp
I installed the latest 431 nightly with Virtual Keyboard layouts moved to data/modules, but I can't find your iterations. Keyboard symbols underneath the numbers look like the same as I left them before.
Is there any file I missed from you?

**Comment by houqp** [comment]
The sym layout had a overhaul based on yours, can you paste your original layout here to verify?

**Comment by mergen3107** [comment]
Here it is!
[virtualkeyboard.zip](https://github.com/koreader/koreader/files/325310/virtualkeyboard.zip)
Compared with 431 nightly, mine is the same.

**Comment by houqp** [comment]
My change is different from yours, see:

```+    {  --  1           2       3       4       5       6       7       8       9       10      11      12
 +        { "Q",        "q",    "!",    "1",    "Я",    "я",    "1",    "!",    "Ä",    "ä",    "1",    "ª", },
 +        { "W",        "w",    "?",    "2",    "Ж",    "ж",    "2",    "?",    "Ö",    "ö",    "2",    "º", },
 +        { "E",        "e",    "|",    "3",    "Е",    "е",    "3",    "«",    "Ü",    "ü",    "3",    "¡", },
 +        { "R",        "r",    "#",    "4",    "Р",    "р",    "4",    "»",    "ß",    "ß",    "4",    "¿", },
 +        { "T",        "t",    "@",    "5",    "Т",    "т",    "5",    ":",    "À",    "à",    "5",    "¼", },
 +        { "Y",        "y",    "‰",    "6",    "Ы",    "ы",    "6",    ";",    "Â",    "â",    "6",    "½", },
 +        { "U",        "u",    "'",    "7",    "У",    "у",    "7",    "~",    "Æ",    "æ",    "7",    "¾", },
 +        { "I",        "i",    "`",    "8",    "И",    "и",    "8",    "(",    "Ç",    "ç",    "8",    "©", },
 +        { "O",        "o",    ":",    "9",    "О",    "о",    "9",    ")",    "È",    "è",    "9",    "®", },
 +        { "P",        "p",    ";",    "0",    "П",    "п",    "0",    "=",    "É",    "é",    "0",    "™", },
 +    },```

**Pull request merged**
