### PR TITLE
TitleBar: new options, dedicated close button

### PR DESCRIPTION
**Pull request by poire-z**
Discussions and screenshots about this in #8625 and #8627.

#### TitleBar: new options, dedicated close button

- Fix hold callback name
- Add options to handle long titles (truncated by default): "title_multines" and "title_shrink_font_to_fit" (allowing setTitle() with them makes the code a bit more complex).
- Add options to set bottom line color and horizontal padding.
- Use an added title.close.svg (based on exit.svg, tweaked to have similar size and baseline as other icons) for close button.

IconButton:
- handle hold/hold_release similar to Button.
- new option allow_flash to allow disabling flashing

#### DictQuickLookup: update to TitleBar widget

Also tweak ReaderHighlight:onHoldRelease() to avoid doing its stuff when onHold() is clearing highlight (previous CheckButton was closing/clearing on hold release, new TitleBar close button does that on hold).

#### KeyValuePage: update to TitleBar widget

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8629)

### CODE REVIEW

**Comment by poire-z** [comment]
@hius07 : if you can review this, we can quickly merge it so you can go on with your other PRs.
Please also add `show_parent = self` to your TitleBar instances.
You can then test if any of "title_multines" and "title_shrink_font_to_fit" pleases you as a default - but I think we should may be wait a bit before changeing them, may be after next release.

**Comment by poire-z** [comment]
About the tap on close button refresh glitches https://github.com/koreader/koreader/pull/8613#issuecomment-1005929845:

Previously, the CloseButton was not handling flashing, so no flash when tap on it.
Now, it's an IconButton which does flash. I added an option to allow it to not flash, so it looks and behaves as previously.

If we have it flashing (which I initially did not mind :), there are a few issues:
- we can have the DictQuickLookup disapear, while its close button is still flashing black to white, so you can witness a black cross button on top of book content, which is ugly.

- There is also the (more serious?) fact that most :onClose() rely on UIManager to repaint what's below.
Some logs when flash_ui disabled:
```
01/08/22-11:28:55 DEBUG adjusted ges: tap
01/08/22-11:28:55 DEBUG AutoTurn: onInputEvent
01/08/22-11:28:55 DEBUG close widget: table: 0x7f74cd130098
01/08/22-11:28:55 DEBUG Lower widget ReaderUI covers the full screen

01/08/22-11:28:55 DEBUG setDirty nil from widget ReaderUI w/ NO region
01/08/22-11:28:55 DEBUG painting widget: ReaderUI
01/08/22-11:28:55 DEBUG CreDocument: goto page 146 flow 0
01/08/22-11:28:55 DEBUG no refresh got enqueued. Will do a partial full screen refresh, which might be inefficient
  ^ this handles mostly all the refreshes after most of our :onClose()
01/08/22-11:28:55 DEBUG _refresh: Enqueued partial update for region 0 0 600 610
01/08/22-11:28:55 DEBUG refresh on physical rectangle 0 0 600 610
01/08/22-11:29:01 DEBUG update battery state
01/08/22-11:29:01 DEBUG CreDocument: set battery state 0
01/08/22-11:29:01 DEBUG _refresh: Enqueued ui update for region 0 0 600 26
01/08/22-11:29:01 DEBUG setDirty ui from widget ReaderUI w/ region 0 0 600 26
01/08/22-11:29:01 DEBUG ReaderCoptListener.headerRefresh scheduled
01/08/22-11:29:01 DEBUG painting widget: ReaderUI
01/08/22-11:29:01 DEBUG CreDocument: goto page 146 flow 0
01/08/22-11:29:01 DEBUG refresh on physical rectangle 0 0 600 26
```
When flash_ui is enabled and I allow close IconButton to flash:
```
01/08/22-11:29:40 DEBUG adjusted ges: tap
01/08/22-11:29:40 DEBUG AutoTurn: onInputEvent
    01/08/22-11:29:40 DEBUG Explicit widgetInvert: table: 0x7f74c9d86318 @ ( 569 , 10 )
    01/08/22-11:29:40 DEBUG _refresh: Enqueued fast update for region 527 0 73 52
    01/08/22-11:29:40 DEBUG setDirty fast from widget nil w/ region 527 0 73 52
    01/08/22-11:29:40 DEBUG not painting 1 covered widget(s)
    01/08/22-11:29:40 DEBUG refresh on physical rectangle 527 0 73 52
    01/08/22-11:29:40 DEBUG Explicit widgetInvert: table: 0x7f74c9d86318 @ ( 569 , 10 )
01/08/22-11:29:40 DEBUG close widget: table: 0x7f74c9d7ac08
01/08/22-11:29:40 DEBUG Lower widget ReaderUI covers the full screen

01/08/22-11:29:40 DEBUG setDirty nil from widget ReaderUI w/ NO region
01/08/22-11:29:40 DEBUG _refresh: Enqueued fast update for region 527 0 73 52
01/08/22-11:29:40 DEBUG setDirty fast from widget nil w/ region 527 0 73 52
01/08/22-11:29:40 DEBUG painting widget: ReaderUI
01/08/22-11:29:40 DEBUG CreDocument: goto page 146 flow 0
01/08/22-11:29:40 DEBUG refresh on physical rectangle 527 0 73 52
```
There is no fullscreen refresh, as UIManager saw some mini region refreshes (the flashing), and did not care about doing a "partial full screen refresh" as some other one was issued.

So, by disabling flashing in my new TitleBar close button, I allow UIManager to handle this on behalf on most of our widgets.
Otherwise, we would need to go thru all :onClose() and add in each of them that doesn't have it something like `UIManager:setDirty(self.show_parent, "ui")`.

@NiLuJe : any thought ? Does my understanding of how these things happen sound right ? And me disabling flashing on close button a good enough solution/workaround?

**Comment by hius07** [comment]
TitleBar is okay (began reading yesterday).

TextViewer long title







b

**Comment by poire-z** [comment]
image
I made this one look like this when mostly thinking about DictQuickLookup and dynamic title update (when switching dict result, one most often gets small titles, so best to have small ones look fine, and only longer looks like this a bit odd - but baseline aligned, to keep title height stable).

For a fixed title, it looks a bit odd :) But it is baseline aligned. Logically, we would add more padding below so it looks centered in the title bar. We could add a `title_static=true` to change the behaviour.
(But well, I'm a bit fed up of tweaking TitleBar :)

**Comment by poire-z** [comment]
For title_multilines, you can tweak this 0.2 (a bit random choice of mine, default is 0.3) to your liking:
https://github.com/koreader/koreader/pull/8629/files#diff-bfe86eac6944931d4d6d6e0195695d119a7f222028b820ea70cffdc3d71e22f8R110

**Comment by poire-z** [comment]
> image I made this one look like this when mostly thinking about DictQuickLookup and dynamic title update (when switching dict result, one most often gets small titles, so best to have small ones look fine, and only longer looks like this a bit odd - but baseline aligned, to keep title height stable).
> 
> For a fixed title, it looks a bit odd :) But it is baseline aligned. Logically, we would add more padding below so it looks centered in the title bar. We could add a `title_static=true` to change the behaviour. (But well, I'm a bit fed up of tweaking TitleBar :)

How would you expect this one ? Not baseline aligned but centered vs the icon ? (ie. a bit upper, on this screenshot)

**Comment by hius07** [comment]
02, 0.3 (0.3 looks better on the device)

**Comment by hius07** [comment]
> Not baseline aligned but centered vs the icon ?

Yes, vertically centered would be better (text and icon would be centered within the title frame).

**Comment by poire-z** [comment]
OK, will have a look.

KeyValuePage updated : Previous | New
image
Looks better (font size bigger because I gained some available height I guess), I'll add it to this PR.

**Comment by poire-z** [comment]
> Yes, vertically centered would be better (text and icon would be centered within the title frame).

OK, done, as good as I could (we don't have the notion of what's the middle of lowercase x, so I went with half of the difference between the original baseline and the smaller text baseline).
Added KeyValuePage.

**Comment by hius07** [comment]
In https://github.com/koreader/koreader/pull/8627 I've enlarged icons (check and appbar.menu).
Sorry, no more `title.smth` icons. Maybe return back `close.svg`?

**Comment by poire-z** [comment]
> Maybe return back close.svg?

Done.

**Comment by hius07** [comment]
Good centering

**Comment by hius07** [comment]
KVP perfectly

**Comment by poire-z** [comment]
So, remaining old CloseButton users:
```
frontend/ui/widget/frontlightwidget.lua
frontend/ui/widget/bookstatuswidget.lua
plugins/statistics.koplugin/readerprogress.lua
frontend/ui/widget/imageviewer.lua
```
I'll be doing ImageViewer (not sure it can switch to TitleBar, or may be I can use subtitle - have to be tested with click on images in Wikipedia full results).

**Comment by poire-z** [comment]
Should we merge these 3 PRs, so we can continue with a clean slate?

**Comment by hius07** [comment]
Let's go!

**Comment by NiLuJe** [comment]
@poire-z: Without checking anything, yeah, the reasoning looks sound, and I'm perfectly fine with the workaround ;).

**Pull request merged**
