### PR TITLE
[chore] Add translations to repo

### PR DESCRIPTION
**Pull request by Frenzie**
Apparently Weblate needs the translations in the repo before it can be set up.

References <https://github.com/koreader/koreader/issues/3754>.

Also see <https://github.com/koreader/koreader/issues/2040#issuecomment-485154051>.

### CODE REVIEW

**Comment by poire-z** [comment]
Just for setup? Or will they stay in the main koreader repo?
And how that will work?
Will we get a bunch of commits each time someone translates something :( ?
Or you'll pull the updated translations only when you're about to release? And how about/if people update translations directly on github/via PR?

**Comment by Frenzie** [comment]
It lives in the repo, yes, but it does [lazy commits](https://docs.weblate.org/en/latest/admin/continuous.html#lazy-commit). That looks like this:

* Small adjustment: https://github.com/phpmyadmin/phpmyadmin/commit/b73733f7a7526023db426f79d5423b99f37a76ca
* Big translation session: https://github.com/phpmyadmin/phpmyadmin/commit/70281956bbb5459c01c9d483409e30035e33fe9a

If you feel strongly about it we could consider a submodule instead, but the Git tracking in and of itself is a definite advantage.

> And how about/if people update translations directly on github/via PR?

I may very well switch to doing exactly that. ;-)

**Comment by poire-z** [comment]
> If you feel strongly about it

I do :|
If I add a string in some dev commit, I'll be seeing dozens of small adjustment commits (one per author/language) following it, and it will be a pain to follow github commits page (1 or 2 real dev commit per page, and 28 translation commits) or use `git log -p` to see what really happened over a period of time (to look for cause of regressions, and for me to look about what's new when adjusting my own patch once a week).

> we could consider a submodule instead

But you'll be bumping it every day into the main repo to build a nightly?
If no, that's fine with me :)
If yes, well, only 1 translation commit per day among 2 to 5 real dev commits. That's better, but still :)

> but the Git tracking in and of itself is a definite advantage.

OK for git tracking in its own repo, but what advantage linking it to the main repo?

**Comment by Frenzie** [comment]
> edit: oh, I already hate that last merged commit :(

We could force push master; apologies I thought we'd basically discussed this about a year and a half ago. Force push to replace this commit with a submodule okay by you @NiLuJe @pazos?

**Comment by NiLuJe** [comment]
No objections to either approach here ;).

I would marginally prefer if the commits came from a bot account instead of a real one, but that's basically cosmetics to me ;).

**Comment by poire-z** [comment]
(OK for me ! and thanks for considering that :)
Given no activity/chat happened since that commit 5 hours ago, go for it before people wake up and git pull :)

**Comment by Frenzie** [comment]
I created https://github.com/koreader/koreader-translations

> But you'll be bumping it every day into the main repo to build a nightly?

The nightly build should pull in the latest translations but it doesn't need to be bumped (daily) for that.

@NiLuJe 
> I would marginally prefer if the commits came from a bot account instead of a real one, but that's basically cosmetics to me ;).

It comes from the weblate bot?

**Comment by Frenzie** [comment]
Okay, it's done.

**Comment by poire-z** [comment]
Thanks.
(No pb with that: not sure why, but all our opened PRs got their last update time updated.)

**Comment by poire-z** [comment]
https://gitlab.com/koreader/koreader has updated in between. Will it be ok with the force push, or does it need manual tweaking? (Is it what is used for building nightlies?)

**Comment by Frenzie** [comment]
We'll see, I have no idea. But yeah, that's why you shouldn't force push. ^_^

master is protected from accidental force pushes by GH btw. I disabled that protection to do it, or rather I temporarily switched the protection to the imaginary `masterr` branch instead.

**Comment by Frenzie** [comment]
The nightly uses GH: https://gitlab.com/koreader/nightly-builds/blob/29ed1f3f781434827cc18849431852d41ea2eb41/build_release.sh#L18

It used to be GitLab but apparently there was a mirroring issue at some point: https://gitlab.com/koreader/nightly-builds/commit/9cc1fec7d9bfbf928c950f422ad3cd365590e140

**Comment by Frenzie** [comment]
Yep, that broke the mirroring. I'm not sure if there's an easy way to fix that besides manually force pushing or deleting the repo and starting the mirror from scratch.

**Pull request merged**
