### PR TITLE
capitalize KOR to make the name sounds less like korea ;p

### PR DESCRIPTION
**Pull request by houqp**

### CODE REVIEW

**Comment by neilswann80** [comment]
Pronounced co-reader or core-reader?  Or neither?

**Comment by mergen3107** [comment]
If I remember correctly, it is read as “co-reader”, KO stands for Knock-Out :D

**Comment by neilswann80** [comment]
Thanks.  I'd heard the "KOR" was from Kindle (or Kobo) Open Reader.  Knock-Out is far more fun though.

**Comment by chrox** [comment]
@neilswann80 @mergen3107 Correct. Here are some historical discussions. https://github.com/koreader/kindlepdfviewer/issues/705
https://github.com/koreader/kindlepdfviewer/issues/782

**Pull request merged**
