### PR TITLE
Add author option for alt status bar (koreader/crengine#575)

### PR DESCRIPTION
**Pull request by trash-pandy**
Adds alt status bar option to hide the author and title separately. Frontend implementation for koreader/crengine#575.

book-author-option-alt-statusbar

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12196)

### CODE REVIEW

**Comment by hius07** [comment]
Looks like you've missed https://github.com/koreader/koreader/pull/12002.

**Comment by trash-pandy** [comment]
I do perhaps see how that could be relevant. Regardless, the functionality is now available in crengine itself, and this seems to me the easier path, if not the most modular approach.

**Comment by hius07** [comment]
I mean you have not synced the fork.

**Comment by trash-pandy** [comment]
I'm a bit early, I guess.

**Comment by poire-z** [comment]
No, you're not early - you can make a PR now so it's ready when I bump crengine.
And your fork looks synced.
So I guess it's just that the readercoptlistener.lua file you were working with is older than the latest in koreader master - so by adding it as it was some days/weeks ago, you're reverting the changes that happened since. You need to restart doing your changes over the latest version.

**Comment by trash-pandy** [comment]
Ah. I realize now what I had done- sorry for the confusion and bad commit. That's embarrassing. I'll open another PR with a fixed branch.

**Pull request closed without merging**
