### PR TITLE
Reset to one core

### PR DESCRIPTION
**Pull request by zwim**
Reset to one running core.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8579)

### CODE REVIEW

**Comment by NiLuJe** [comment]
IIRC, I left it on purpose (hinting, maybe?).

Did you actually notice circumstances where it was stuck?

**Comment by zwim** [comment]
No I did not notice anything. I just noticed that it is not tirmes off in this branch.

**Review by Frenzie — APPROVED** [review]
Seems to make logical sense to me, merge @NiLuJe?

**Review by poire-z — APPROVED** [review]

**Comment by NiLuJe** [comment]
Will need time to check (maybe this WE).

**Comment by NiLuJe** [comment]
(i.e., I vaguely remember making it unbalanced for a *reason*, but I can't quite remember it right now ^^).

**Comment by poire-z** [comment]
Btw @NiLuJe , does this kopt hinting page in a background thread really work/happen (have you checked there's really another thread running and not blocking the main thread ? I haven't checked, so just asking :)

It seems it's only done for reflow mode - and there, may be turning pages feels a bit more smooth.

But in non-reflow mode, with zoom and page crop, whenever I go on a new page, I'm usually blocked (while it renders the page after) for some noticable time. So, it feels there are a lot of places where you added Device:enableCPUCores(2) that won't benefit of it.

Is this background thread running in the background really a kopt thing only for this specific reflow mode - or could it be done for any other classic Document:renderPage() ? (which I guess is running in our public Lua world, while kopt reflow stuff is running in its own private library world.
(May be some trick of rendering the next page via a subprocess like I'm doing for Page browser could one day be done to avoid this blocking for everything not-reflow.)

**Comment by poire-z** [comment]
Looking again, it seems we never go in this `Document:renderPage()` when PdfDocument renders with KOpt - so all these enableCPUCores(2) feel useless :)
PDFDocument:renderPage/hintPage => KOPTDocument:renderPage/hintPage which falls back to Document:renderPage() only when no kopt needed - so no CPUCores(2) needed.

Might need some revisit - and if one does, please move Device:enableCPUCores(2) and Device generally outside of document/*, have it done via a hook or something else, see https://github.com/koreader/koreader/pull/8501#issuecomment-986033469.

**Comment by NiLuJe** [comment]
There's a pure C mupdf thread involved somewhere, and I recall checking that it indeed popped up, because it broke at one point due to ffi and implementation details shenanigans...

Will check again whenever I actually have free time again ;p.

**Comment by NiLuJe** [comment]
Note also that, on sunxi, the eink threads are *hilariously* CPU-hungry, so extra breathing room for the kernel threads is not necessarily wasted, even on single thread workflows ;).

**Comment by NiLuJe** [comment]
I don't have any bright ideas on how to move that away from Document, though :s.

**Review by NiLuJe — APPROVED** [review]
I clearly missed the early return here, :lgtm: ;).

**Comment by poire-z** [comment]
> I don't have any bright ideas on how to move that away from Document, though :s.

By having in document.lua:
```
local Document = {
     request_cpu_cores = function(nb) end
```
and replacing that on devices multicore or all, somewhere, possible in frontend/document/canvascontext.lua which was made to abstract device ?
`require("document").request_cpu_cores = function(nb) Device.enableCPUCores(nb) end`

**Comment by poire-z** [comment]
I'm just fine with your `Stash enableCPUCores in CanvasContext`.

There is still the thing that we must enable 2 cores in places where it is not needed, cf https://github.com/koreader/koreader/pull/8579#issuecomment-1005129078 - but it might need a bit more available brain power to follow all the codepaths :)

**Comment by NiLuJe** [comment]
FWIW, the 2-cores thing even outside of mupdf threads was by design (c.f., my comments above about the driver being truly awful).

**Comment by poire-z** [comment]
I suppose you mean:
> Note also that, on sunxi, the eink threads are hilariously CPU-hungry, so extra breathing room for the kernel threads is not necessarily wasted, even on single thread workflows ;).

But if that's true, you enabling it only in around single threaded mupdf paths feels limiting: why not for cre, images rendering in wiki results or cover browsing ? And when single threaded mupdf runs, nothing eInk is happening. So, enabling on startup (or in your future Kobo Sage works when you'll be sleeping cpu/hardware when we're idling :) feels more logical.
(I don't mind how it is, having a single cpu kobo :) just making sure I understand, a few comments could help - because I'm sure in a year or two, when I'll have forgotten this thread, I'll be wondering the same things :)

**Comment by zwim** [comment]
Shouldn 't we then enable/online at least 2 cpus per default?

Am 16. Januar 2022 22:58:21 MEZ schrieb NiLuJe ***@***.***>:
>FWIW, the 2-cores thing even outside of mupdf threads was by design (c.f., my comments above about the driver being truly awful).
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/koreader/koreader/pull/8579#issuecomment-1013960256
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by NiLuJe** [comment]
Not worth it for CRe, because CRe page turns are barely a blip on the CPU load ;).

2 cores yb default happened to be the launch setup, but it's mostly a waste of energy, and that's already fairly scarce given the terrible power efficiency on sunxi :s.

Thumbnail generation is already taken care of, and Wiki would make sense, but I couldn't find a good way to handle it (and I didn't look long, because that's not part of my usual workflows ;)).

**Pull request merged**
