### PR TITLE
Optimize cache for cover-image

### PR DESCRIPTION
**Pull request by zwim**
A better strategy for cleaning the cache.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7610)

### CODE REVIEW

**Comment by NiLuJe** [comment]
That kinda feels super over-engineered for no real good reason, but, ho hum.

**Comment by zwim** [comment]
The reason would be: If there are different sized jpg's or if someone mixes bmp with jpg ... on a cache cleanup a lot of cached files get deleted.
This could also happen if someone decreases the cache size.
Here I try too keep the cache filled as max as possible and just delete what is really necessary. (Keeping in mind to delete the at least the oldest file). 

But if you think KISS is better ...

**Comment by NiLuJe** [comment]
I get why you went to the trouble, I'm just not entirely sure it's worth it in terms of maintenance burden *and* actual real-world use cases.

As a somewhat similar reference, the ScreenSavers hack on Kindle essentially does this in Cover mode, and it *never* clears the cache on its own (instead, there's a button that lets the user choose to do so if need be).

**Comment by zwim** [comment]
Is it OK to convert this PR to draft (maybe someone finds it usefull ;) )?

**Comment by NiLuJe** [comment]
I mean, it's a plugin, you're actually the one maintaining it, so, this is just me telling *I* wouldn't do that.

I'd actually be vetoing it if it were in core, but this is a Plugin, so, this is just a friendly comment ;).

**Comment by zwim** [comment]
I will convert it to draft and think about it. Thank you for your comment.

**Comment by Frenzie** [comment]
> I'd actually be vetoing it if it were in core, but this is a Plugin, so, this is just a friendly comment ;).

We do have to be careful with that though — people tend to take some random plugin as their jumping off point.

**Comment by Frenzie** [comment]
I'm on board with this seems awful complicated and therefore more error prone to the simple existing method.

**Comment by Galunid** [comment]
From a Onyx Nova 2 perspective, I don't really think cache is needed in this plugin. Images are generated fast enough that I don't notice any performance issues. I'm not sure as to how fast it works on Pocketbooks/Tolinos. I believe that keeping *n* most recent covers should be more than enough. Is the new algorithm better performance wise? Probably yes, is it worth it at the cost of readability? Probably not. To understand the previous code I needed a glance, it was extremely simple and straightforward, while I spend a few minutes and still don't understand what exactly happens in the revised version. If you were to abandon the plugin, someone would have to spend much more time to understand what happens if they wanted to change it. If you still want to go ahead with it, perhaps making a few helper functions would improve readability

**Comment by Galunid** [comment]
Also it seems to duplicate https://github.com/koreader/koreader/pull/7611, not sure if it's intended

**Comment by zwim** [comment]
Thank you all for your comments. I will close this now.

@galunid: #7611 will be the survivor of this PR. :))
At least on Tolino the cover creation is slow, a cache noticeable speeds up consecutive book openings. If someone has a faster device, the cache does no harm (and can be disabled).

@frenzie @niluje: You are right, this method is more complicated than the original one. In terms of maintainability over the years the older one is prefferable.

**Pull request closed without merging**
