### PR TITLE
WIP: Add global declaration of hasStandaloneWarmth for Onyx devices

### PR DESCRIPTION
**Pull request by mergen3107**
Depends on https://github.com/koreader/android-luajit-launcher/pull/426

@pazos 
These are the changes I did (https://github.com/koreader/koreader/pull/8120#issuecomment-1636970460)

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10700)

### CODE REVIEW

**Comment by mergen3107** [comment]
Do not merge yet please, needs testing.

**Comment by mergen3107** [comment]
I am stuck in my current progress. Thanks to pazos' help, I was able to declare this new method `hasStandaloneWarmth()` for all `OnyxWarmthController.kt` devices. (Should I also enable this for `OnyxColorController.kt`? I don't have a color device to test though, if someone can chime in, I would appreciate).

1) At this point, I am able to turn off the frontlight (cold + warm) via a gesture in KOReader.
2) However, When turning it on, two things happen:
- cold goes on, and sets to the same nominal value somewhere after the middle of the frontlight slider.
- warm does not turn on, no value is set.

How do I check what raw values are being used for calculations (namely, `fl_intensity` and fl_warmth` and the `max`/`min` counterparts)? By adding `logger.dbg something something`? I am able to see the final product of these actionsin `pidcat org.koreader.launcher` where it revelead that cold goes to value of 114, and warm goes to ... 17235 or something close (yes, this is seventeen thousand!).

I would like to do these:
1B) Save all current values in a variable before turning it off.
2B) restore these values, apply them to turn on cold and warm and then clear them.

I would appreciate any help!
Sorry for being such a novice, I am trying my best :D

Thanks!

**Comment by Frenzie** [comment]
> By addinglogger.dbg something something

Pretty much, you can just write `logger.dbg("value I want to know:", value, "other value:", other_value)` since it even concatenates all by itself.

**Comment by mergen3107** [comment]
My findings so far:
```
    if standalone_warmth then
        -- restore warmth levels
        android.setScreenWarmth(math.floor(self.fl_warmth * self.warm_diff / self.fl_warmth_max))
    end
```
this part has the extra `self.warm_diff`(= 255 in powerd.lua for Android on my device at least) multiplier that makes very large numbers. I didn't use logger yet, just pidcat that said:
```
set screen brightness 145
Setting brightness to 145
set screen warmth 36975
warmth value of of range: 36975
```
If you divide 36975 by 255 you get whole number of 145. I removed the extra variable and now it turn on the warmth too upon toggle!

(by the way, there is a typo in `warmth value of of range: `, should be `out of range`)

However, I still don't understand how that works. Upon gesture toggle of the frontlight:
- when turning off both cold and warm go to 0s.
- when turning on, cold goes to 147, warm to 145. Both are ever no the middle, the middle in the [0-255] is 127. I verified this middle but aligning the sliders with the vertical separation line between `Cancel` and `OK` buttons :D

Any suggestions would be appreciated!

Although, these two PRs might not hurt, I think now I really need to dig and find where these 145 and 147 are coming from, and why there needs to be a difference in their normalization.

**Comment by pazos** [comment]
> Any suggestions would be appreciated!

Please update the commits with the changes that produce the results above.

Also, please log `self.fl_warmth` just before setting `self.fl_warmth_min`

> this part has the extra self.warm_diff(= 255 in powerd.lua for Android on my device at least)

the diff should be the difference between max and min as reported by the driver.

Each driver provides its own min and max for brightness and warmth. So turning off means setting min, turn on to the max means setting max, and restoring previous means scaled `current`

**Comment by mergen3107** [comment]
> Please update the commits with the changes that produce the results above.

I think I did? Or is something missing?

**Comment by pazos** [comment]
> > Please update the commits with the changes that produce the results above.
> 
> I think I did? Or is something missing?

everything  /s.

Mostly the log statements that produce the results above :)

**Comment by mergen3107** [comment]
Ah, OK :D 

I need to reproduce them again in the old build, since I was just watching them live. 

Will do a little later.

**Comment by mergen3107** [comment]
Switched devices.

**Pull request closed without merging**
