### PR TITLE
bump base/crengine: stylesheet handling improvements

### PR DESCRIPTION
**Pull request by poire-z**
Includes:
- Fix a few CSS selector issues https://github.com/koreader/crengine/pull/178
- CSS: add support for some pseudo-classes https://github.com/koreader/crengine/pull/180
- Hyphenation: update fr & de patterns https://github.com/koreader/crengine/pull/182
- CSS: Fix non-lowercasing of specific elements names https://github.com/koreader/crengine/pull/183
- Revert parts of recent BR handling fixes https://github.com/koreader/crengine/pull/184

### CODE REVIEW

**Comment by poire-z** [comment]
There's something strange with juliet.epub (and a few other books I checked with): page breaks before chapters seem no more there (even if I disable Embedded styles).
If I remove this line from epub.css, page braks are ok again:
`div { display: block;margin:1px; }`

I can't get to understand why :|
I guess I'll have to check with reverting bits from https://github.com/koreader/crengine/pull/178 ...

**Comment by poire-z** [comment]
Pffff. It was the lowercasing of elements IDs.
Guess what is the only one that is not lowercased? `DocFragment` which does not come from the HTMLParser but is added explictely...

**Comment by poire-z** [comment]
There is still a thing with this :|
On first load of juliet.epub, the number of page is like ~254 (and there are some new lines between some lines. If you toggle Embedded fonts, or quit and restart, it become ~202 is it used to.
Happens to unit test, and a vanilla emulator....
But logs old vs new don't show that different things are happening or not in one case or the other.

**Comment by poire-z** [comment]
Mhhhok.
This problem is caused by the combination of 2 things:
- the `br + br { margin-top: 1em; }` that has been added to epub.css (and all the other css) by https://github.com/koreader/crengine/pull/172
- the _fix E+F selector, that should ignore immediate preceding text nodes, and consider the first met element node_  that has been added by https://github.com/koreader/crengine/pull/178

If you revert one or the other: it's fine.

What's happening:
With this original HTML fragment:
```html
<h3 class="section_title">Prologue</h3>
<div class="text">
<blockquote>
<p>Two households, both alike in dignity,<br />
In fair Verona, where we lay our scene,<br />
From ancient grudge break to new mutiny,<br />
Where civil blood makes civil hands unclean.<br />
From forth the fatal loins of these two foes<br />
A pair of star-cross'd lovers take their life;<br />
Whole misadventured piteous overthrows<br />
Do with their death bury their parents' strife.<br />
The fearful passage of their death-mark'd love,<br />
And the continuance of their parents' rage,<br />
Which, but their children's end, nought could remove,<br />
Is now the two hours' traffic of our stage;<br />
The which if you with patient ears attend,<br />
What here shall miss, our toil shall strive to mend.</p>
</blockquote>
</div>
```

It is parsed by the HTMLparser and DOM writer.
Then styles are applied, and the `br + br { margin-top: 1em; }` matches (now with this PR that makes E+F ignoring text nodes) the second and next `<br/>` (but not the first - and previously none of them because of the text between the `<br/>`s), so it displays as:
<kbd>image</kbd>

So, this is the main problem.

Then, after applying styles, crengine proceeds to rendering (it has to be after styles to know if nodes are to be rendered inline or as block). In this process, there is something called autoBoxing to make block elements around mixed inline and block _node potage_ (that's _tag soup_ at the next level :) - very unclear to me why/how that is needed/works). After this process, the DOM (serialized back to HTML) looks like this:
```html
<h3 class="section_title">Prologue</h3>
<div class="text">
  <blockquote>
    <p>
      <autoBoxing>Two households, both alike in dignity,</autoBoxing>
      <br/>
      <autoBoxing> In fair Verona, where we lay our scene,</autoBoxing>
      <br/>
      <autoBoxing> From ancient grudge break to new mutiny,</autoBoxing>
      <br/>
      <autoBoxing> Where civil blood makes civil hands unclean.</autoBoxing>
      <br/>
      <autoBoxing> From forth the fatal loins of these two foes</autoBoxing>
      <br/>
      <autoBoxing> A pair of star-cross'd lovers take their life;</autoBoxing>
      <br/>
      <autoBoxing> Whole misadventured piteous overthrows</autoBoxing>
      <br/>
      <autoBoxing> Do with their death bury their parents' strife.</autoBoxing>
      <br/>
      <autoBoxing> The fearful passage of their death-mark'd love,</autoBoxing>
      <br/>
      <autoBoxing> And the continuance of their parents' rage,</autoBoxing>
      <br/>
      <autoBoxing> Which, but their children's end, nought could remove,</autoBoxing>
      <br/>
      <autoBoxing> Is now the two hours' traffic of our stage;</autoBoxing>
      <br/>
      <autoBoxing> The which if you with patient ears attend,</autoBoxing>
      <br/>
      <autoBoxing> What here shall miss, our toil shall strive to mend.</autoBoxing>
    </p>
  </blockquote>
</div>
```
(and that's what would be saved to cache if cache was to be saved).
Then, if you toggle a re-rendering (by changing layout, fonts, or toggling Embedded styles or fonts off then on), the  `br + br { margin-top: 1em; }` no more match anything! because there are now the `<autoBoxing>` nodes between them, and it would render fine:
<kbd>image</kbd>

Not sure where to go from there...
Most obvious fix seems that we should remove these  `br + br { margin-top: 1em; }` which are obviously wrong if text nodes in between should not be taken into account by the `+` selector.

**Comment by poire-z** [comment]
They are, but HR have a height made by a colored border. BR have none (except when I add some with BR+BR margin-top).
With:
```html
<p class="tagada">
  <span class=truc>span tagada truc</span>
</p>
<hr/><hr/>
<p class="tagada">
  <span class=truc>span tagada truc</span>
</p>
<br/><br/>
<p class="tagada">
  <span class=tsouin>span tagada tsouin</span>
</p>
```
the DOM looks like:
```html
    <p class="tagada">
      <span class="truc">span tagada truc</span>
    </p>
    <hr/> <!-- displays as a thin border -->
    <hr/> <!-- displays as a thin border -->
    <p class="tagada">
      <span class="truc">span tagada truc</span>
    </p>
    <br/> <!-- displays as a 0 height block element -->
    <br/> <!-- displays as a 0 height block element -->
    <p class="tagada">
      <span class="tsouin">span tagada tsouin</span>
    </p>
```
Un-funny-ly enough, if you remove the autoclosing / to the 2 BR and the 2 HR, the DOM becomes:
```html
    <p class="tagada">
      <span class="truc">span tagada truc</span>
    </p>
    <hr>
      <hr/> <!-- displays a a think border -->
    </hr>
    <p class="tagada">
      <span class="truc">span tagada truc</span>
    </p>
    <br>
      <br/>
      <p class="tagada">
        <span class="tsouin">span tagada tsouin</span>
      </p>
    </br>
```
The autoclose stuff seems to behave differently for HR and BR ... but that's unrelated to this PR.

It's when there are BR in a DIV or a P, mixed with inline text, that the autoBoxing stuff comes into play.

**Comment by poire-z** [comment]
I see 2 simple things to do to get back the original behaviour (without the need to go into the rendering code):
- remove all `br + br { margin-top: 1em; }` , as it seems having consecutive BR adds some height is not something that is to be fixed by CSS (can't figure out what selector could be used), but may be more by the rendering code.
- ignore autoBoxing elements in the lvstsheet.cpp code (those I modified or added recently) when navigating siblings or parents (that is: ignore them whereever we ignore text nodes as sibling, and getParent() would need a loop to reach the first non-autoBoxing parent) - that would make `E + F` still work the same between the first addStyle>render step and subsequents ones I think (so, if we were to keep BR+BR, the display bug would not disappear and stick when toggling something).

**Comment by Frenzie** [comment]
> ignore autoBoxing elements in the lvstsheet.cpp code

Sounds like a good idea regardless.

**Comment by poire-z** [comment]
> `br{border-top:solid transparent 1em}`

That would work the same as `br{padding-top: 1em}` or `br{margin-top: 1em}`, and it would add 1em of vertical blank space for a single `BR`, which it should not. We'd want that for >=2 consecutive BR, without any non-space-only text node in between.

> remove all br + br { margin-top: 1em; } 

Do you agree with that being absolutely wrong and will never be the right way to fix consecutive BR, so I should just remove them all? That should be enought for the unit tests to be happy just like before.

> ignore autoBoxing elements in the lvstsheet.cpp code

It's easy and the right thing to do for just finding the immediate real parent.

But when you are navigating your siblings, it gets a lot more complicated:
If you are in a `autoBoxing`, you may have siblings in there, but also in your real parent above, but also in this real parent other children `autoBoxing`s !  And you'd have to navigate them all in the correct order to get a grasp of you real original index in your real parent, and your relation to the other real siblings...
It's similar when yourself are not in a `autoBoxing`, but if you have some `autoBoxing` as siblings: you'd need to go down into them to count correctly.
Not obvious to code (in C, for me :)...

This make the `E + F`, `E ~ F` and all the pseudo-classes I added yesterday prone to give wrong decisions...
The only thing I could do quickly is just, for these siblings checks: if my parent is an `autoBoxing`, or if I meet a `autoBoxing` as sibling when walking in the direction i look at, I just stop the check and `return false`. Rather say no match that wrong match?

**Comment by poire-z** [comment]
I also wonder if I should revert https://github.com/koreader/crengine/pull/172#issuecomment-386215579.

Before, BR were inline and handled as a `\n` by the text rendering code (and the spaces around the `<br/> `where then rendered as space by this rendering code...). But consecutive <br> were rendered correctly as multiple `\n`.

Making them block elements solved the space problem (because spaces are stripped from the start of block elements - but this feels hacky, and cause other problem like highlights being a bit shifted when there is such a space), but so now adds a lot more autoBoxing block elements (which is OK, but I guess this can make cache size and memory usage bigger), and cause the consecutive BR problem I was trying to solve...

This still would not solve the generic problem with CSS selector and siblings, that could happen with autoBoxing, that could still be inserted by crengine, just less often.

**Comment by Frenzie** [comment]
> Do you agree with that being absolutely wrong and will never be the right way to fix consecutive BR, so I should just remove them all? That should be enought for the unit tests to be happy just like before.

I do. The spec says the following, after all:

https://drafts.csswg.org/selectors-3/#sibling-combinators
> There are two different sibling combinators: the next-sibling combinator and the subsequent-sibling combinator. In both cases, non-element nodes (e.g. text between elements) are ignored when considering adjacency of elements. 

>  handled as a \n

That behavior sounds correct. Where do the spaces come from?

**Comment by poire-z** [comment]
From the HTMLParser, which tries to keep at most one single space on both side of a text node if there were one or more space or `\n` or `\t` after or before a tag.

I guess that's for `<b>super</b>important` to be displayed as "super**important**",
and for `<b>super</b> (one or more space here) important` to be displayed as "**super** important".

So, `super<br/>important` would be displayed as:
```
super
important
```
But `super<br/> important` or (as peole often do for readability):
```html
super<br/>
important
```
would be rendered as:
```
super
 important
```

And there is some link in lvtextfm.cpp code between the DOM text node, and the plain text it is fed, that is used (or not) for various purpose, like drawing highlights, getting the correct XPointer from a drawn coordinate... This is real ugly, but somehow works well (except for this space, and the shift in highlight position we can see in https://github.com/koreader/crengine/pull/172#issuecomment-386397600 that I still can't pinpoint).

**Comment by poire-z** [comment]
With a crengine from 10 days ago (and so, probably since many years), what is screenshoted above is rendered as:
With `XS_TAG1I( br )` (inline BR):
<kbd>image</kbd>
con: a space at the beginning of each line, except the first one
pro: unshifted highlights (in that specific BR case - they can still be shifted in other cases)
pro: less autoBoxing, and more chances for CSS selectors to work correctly

.

With these last days change (in current nightly, and since last saturday):
With `XS_TAG1( br )` (block BR):
<kbd>image</kbd>
pro: no space at the beginning of each line
con: shifted highlights
con: more autoBoxing, and less chances for CSS selectors to work correctly
**con: possible past highlights not showing (because 1 space char was removed and the xpointer offsets are wrong I guess).**

I have no quick solution to solve the beginiing space / shifted highlights, but I shall look at it when I have more time and courage.
What to keep for the interim (and tomorrow's nightly)?

**Comment by Frenzie** [comment]
The second one that looks good has the issue that `<br><br>` only does one line?

**Comment by poire-z** [comment]
The 2nd one that looks good has the following issues:
con: `<br><br>` does one line (indeed, forgot that one)
con: shifted highlights when text starts with a space (because they are all treated like the first line of a block element - and they all have this issue)
con: more autoBoxing, and less chances for CSS selectors to work correctly
**con: possible past highlights not showing (because 1 space char was removed and the xpointer offsets are wrong I guess).**

I decided it's safer to revert because of the bolded issue.
I'll think later about a proper solving of the space/shifts issue, which is happening because of [this quick hack/solution to the leading space problem](https://github.com/koreader/crengine/blob/fdf0290b5ee6fa3992cb74b9497aaba0ca7c2e33/crengine/src/lvrend.cpp#L1349-L1363)

**Pull request merged**
