### PR TITLE
FocusManager: enable more keyboard shortcuts by default

### PR DESCRIPTION
**Pull request by Frenzie**
Also add ContextMenu for hold.

@comphilip I don't see much of a reason not to enable these, unless there's a specific reason not to?

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11871)

### CODE REVIEW

**Comment by comphilip** [comment]
@Frenzie Disable these to void breaking compatibility without testing. Letting advanced user to turn it on via `settings.reader.lua`. I posted Kindle DX and PC keyboard example setting in #8859

**Comment by Frenzie** [comment]
I think at the very least tab/shift+tab and a means to hold should just be there by default. They're not used for anything. :-)

**Comment by Frenzie** [comment]
Sym+AA potentially sounds a little weird since they're both modifiers? The rest all works great and isn't used anywhere for anything else, except for tab/shift+tab for selecting links, but that doesn't conflict with any widgets that come on top.

Also pinging @Commodore64user for thoughts on Sym+AA.

**Comment by Frenzie** [comment]
I thought I saw AA in the list when you added ScreenKB to modifiers but it doesn't seem to be there.

> i would have "Shift+Press" or "Alt+Press" instead (or both).

Those are available on both types of device?

> Tab keys don't exist on kindle so that would not apply here.

Curious, Sym+Tab is an explicitly supported keyboard shortcut as equivalent to Shift+Tab. I wonder what that's for.

> i am not sure it's worth going out of one's way to fix them.

What's good for keyboard Kindle is good for PC keyboard is good for gamepad is good for Bluetooth keyboard is good for TV remote.

**Comment by Commodore64user** [comment]
> I thought I saw AA in the list when you added ScreenKB to modifiers but it doesn't seem to be there.

I think "Sym" shouldn't even be one. Sym should just call the virtual keyboard when one needs weird symbols and that sort of thing.

> > i would have "Shift+Press" or "Alt+Press" instead (or both).
> 
> Those are available on both types of device?

They [Shift and Alt keys] are both available on kindles with keyboards, not on K4 (that's why i went with ScreenKB+Press there). Currently not assigned to anything according to my tests.

> Curious, Sym+Tab is an explicitly supported keyboard shortcut as equivalent to Shift+Tab. I wonder what that's for.

I am just as curious now, i thought maybe the older K2s and DX models maybe had one [Tab key] but a quick search proves otherwise https://duckduckgo.com/?q=kindle+2&iar=images&iax=images&ia=images&iai=http%3A%2F%2Fwww.gearlive.com%2Fimages%2Fgearlive-gallery%2F020-kindle-2-unboxing.jpg so not sure what that's about

> What's good for keyboard Kindle is good for PC keyboard is good for gamepad is good for Bluetooth keyboard is good for TV remote.

Besides @pazos who else is reading on a TV? Crazy.

**Comment by Frenzie** [comment]
> I am just as curious now

Right shift is defined as Sym in SDL, probably to be able to test it. Emulator and normal usage might be at odds for that one… but Sym + Tab is also literally the only place it's used for anything at all.

**Comment by Commodore64user** [comment]
Can you add long press on kk's here with shift + press (so i don't have to)?

**Comment by comphilip** [comment]
@Frenzie 
> Sym+AA potentially sounds a little weird since they're both modifiers?

Tested in Kindle DX, `Sym` is modifier while `AA` is not.

**Comment by Commodore64user** [comment]
excellent point. best to keep both then `Sym+Aa` and `Shift+Press`

**Pull request merged**
