### PR TITLE
Actions for Go to first/last bookmark

### PR DESCRIPTION
**Pull request by hius07**
For cases like https://github.com/koreader/koreader/discussions/10881.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10899)

### CODE REVIEW

**Review by poire-z — APPROVED** [review]

**Comment by Frenzie** [comment]
Incidentally, is it correct that we don't have an action for "next" (not as in next page but next section of page)? See https://www.mobileread.com/forums/showthread.php?p=4356097#post4356097

**Review by Frenzie — APPROVED** [review]

**Comment by hius07** [comment]
_turn pages, which when set to 1 is not the same thing as tapping on the right side of the screen_

Looks like the same
https://github.com/koreader/koreader/blob/1f03e76aea5d444a731672e7a593416599d71efb/frontend/dispatcher.lua#L133
https://github.com/koreader/koreader/blob/1f03e76aea5d444a731672e7a593416599d71efb/frontend/apps/reader/modules/readerpaging.lua#L143-L150

**Comment by Frenzie** [comment]
In that case the UI string is deceptive, but possibly only to someone who's acutely aware of the distinction?

**Comment by ryanwwest** [comment]
Oh cool! Thanks for doing this, no need for profiling this anymore.

**Pull request merged**
