### PR TITLE
calibre 'series' metadata fixes

### LINKED ISSUE #3347: Series metadata: '&' and decimal aren't displayed correctly
* KOReader version: v2015.11-1287-g5a2c8e4
* Device: Kobo Aura One

#### Issue

&:
For example series name 'Zigic & Ferreira' becomes 'Zigic `&amp;` Ferreira'

decimal: 
For example series number 2.5 becomes 2

#### Steps to reproduce

1. Transfer a book to your e-reader with series name 'X & Y' and series number '1.5'

2. Choose "List with image and metadata" and "Append Series metadata to Title"

3. Look at the result in file manager

### PR DESCRIPTION
**Pull request by poire-z**
Decode XML entities in series metadata and display decimal in series number if any.
See https://github.com/koreader/koreader/issues/3347#issuecomment-336268606. Closes #3347.

### CODE REVIEW

**Comment by Frenzie** [comment]
Feel free to merge when the tests pass (um, I guess I'm up too late). Just one critical remark that you probably already considered: doesn't it make more sense to do it while saving instead?

**Comment by poire-z** [comment]
We discussed it about description metadata: better to save the raw possibly-html metadata, and do the htmlToPlainTextIfHtml() when displaying, so that if we have a bug in the html detection or conversion function, or some new case of twisted html, we don't have to invalidate the saved data (in bookinfo, and in doc_props in .sdr/metadata.lua).
Guess this approach makes sense also for this series metadata, in case we meet some unexpected other format for these series.

**Comment by Frenzie** [comment]
Makes sense. But I do wonder if perhaps we should also save some kind of metadata source info? 

```lua
if source == calibre then
-- we've got some weird stuff, capt'n
else
-- beautiful PDF metadata (as if, but you get my point =P)
```

**Comment by poire-z** [comment]
With the current crengine, we don't know the source (could be calibre in epub, something else in fb2): so, they come from crengine :) But not much need to know for now, till someone reports a case when we should know :)
note about me mentionning raw metadata above: it's not all raw, crengine already concatenated `series names .. "#" .. number`, but well, no real need do distinguished on our side.

**Pull request merged**
