### PR TITLE
OPDS Catalog: Improve server connection dialog

### PR DESCRIPTION
**Pull request by 1npo**
## Changes

* Updated the "Local calibre library" → "Edit" dialog to allow the user to provide a path to the OPDS service (default value is set to the originally hardcoded "opds")
* Updated the field and dialog names from "calibre" specifically to "OPDS" generally, to align with the "OPDS catalog" name in the magnifying glass menu, and to express support for other OPDS implementations besides Calibre Content Server

## Comparisons

Old                        |  New
:-------------------------:|:-------------------------:
FileManager_2023-06-29_200454 |  FileManager_2023-06-29_195953
FileManager_2023-06-29_200432 |  FileManager_2023-06-29_200007

## Reasoning

The OPDS plugin seemed to only work when connecting to Calibre Content Server. It turns out `opdsbrowser.lua` was hardcoding the OPDS URL path to `/opds`, which is what Calibre Content Server advertises on. But Ubooquity advertises OPDS catalogs on `/opds-books` and `/opds-comics`, and Kavita advertises them on `/api/opds/<long-hash>`. This change allows users to specify a path, which makes it work with other OPDS server implementations now. (I only tested Ubooquity.)

## My Use Case

I have a large collection of PDFs and ePUBs on a NAS that's frequently updated. I wanted to advertise a local OPDS catalog of that collection that's refreshed daily, but I could only get KOReader to connect to Calibre, and I wasn't able to make Calibre work with my setup. I made this change so I could use Ubooquity to advertise a new catalog each day, and download files onto my Kobo over WiFi. It's working great for me now, so hopefully it will help other people who were having a similar issue.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10623)

### CODE REVIEW

**Comment by hius07** [comment]
Are there any issues when adding a local server via the Plus sign?

**Comment by NiLuJe** [comment]
> Are there any issues when adding a local server via the Plus sign?

What do you mean? In terms of whether the rest of the plugin handles non-calibre servers properly, or something simpler related to the changes?

**Comment by hius07** [comment]
If local servers can be added in a usual way via the Plus sign, what are the benefits of these changes?

**Comment by 1npo** [comment]
Nope, I was able to add the server from the plus sign dialog by using the full URL (http://192.168.1.3:2202/opds-books). I didn't realize that was an option - the OPDS plugin Wiki page only mentions the "LOCAL CALIBRE LIBRARY" button. Thanks for pointing it out!

**Comment by NiLuJe** [comment]
Oh, yeah, right, the first entry doesn't really have anything specific about it besides the slightly custom-ish data entry...

On the other hand, this feels harmless enough, but this raises the question of whether we could simply not make that first entry magical and rely on the standard data entry for everything?

**Comment by Frenzie** [comment]
I hadn't thought of that when I first saw this, but that's a good point.

**Comment by hius07** [comment]
I'm good with removing a special entry for calibre, but this will require one time migration, its settings are in the `calibre_opds` key in settings.reader.lua.

**Comment by hius07** [comment]
Closing in favour of https://github.com/koreader/koreader/pull/10657.

**Pull request closed without merging**
