### PR TITLE
move setDirty call from TextWidget:setText to FileManager

### PR DESCRIPTION
**Pull request by houqp**

### CODE REVIEW

**Comment by houqp** [comment]
@Hzj-jie , could you test this to see if it fixes https://github.com/koreader/koreader/issues/2145?

**Comment by chrox** [comment]
It does not work on Kindle Voyage. The text widget seems not refreshed after changing directory.

**Comment by houqp** [comment]
Weird, can you try changing `ui` to `partial`?

**Comment by chrox** [comment]
The problem is `VerticalGroup` has no `dimen` property. We have to wrap it in a `FrameContainer` which will get its `dimen` after it is drawn. I'm doing a major refactoring of the widget framework. After that we will not use `VerticalGroup` directly but those layout constraints will be automatically generated according to the new `anchor` property.

**Comment by houqp** [comment]
Good catch. Not sure why it works for my kobo then >_<

djvulibre's official repo is down, let's switch to our mirror: https://gitlab.com/koreader/djvulibre

**Comment by houqp** [comment]
Can't wait to test the new widget design :)

**Pull request merged**
