### PR TITLE
ReaderPaging: show page overlap menu in reflow

### PR DESCRIPTION
**Pull request by Frenzie**
Cf. <https://www.mobileread.com/forums/showthread.php?t=339912>.

I'll have to check why this doesn't work in continuous. Cf. https://github.com/koreader/koreader/issues/3932#issuecomment-395354006

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7820)

### CODE REVIEW

**Comment by oavaldezi** [comment]
Page overlap menu isn't shown on page or continous view modes.

**Comment by Frenzie** [comment]
A pull request (PR) contains proposed changes. If this one's merged in its current form, it will also show the menu in page + reflow but not in continuous + reflow, to better reflect the actual behavior of the settings involved.

**Comment by oavaldezi** [comment]
> 
> 
> A pull request (PR) contains proposed changes. If this one's merged in its current form, it will also show the menu in page + reflow but not in continuous + reflow, to better reflect the actual behavior of the settings involved.

I can't really comment on that, because the page overlap menu is always greyed out in my app.

**Comment by Frenzie** [comment]
It won't be grayed out if you disable reflow. Then you can

**Comment by Frenzie** [comment]
I'll merge this given the lack of response. I haven't had the time to come up with something better in the meantime.

**Pull request merged**
