### PR TITLE
Fix crash on highlight in some situations

### LINKED ISSUE #3305: Crashed when highlight 2 words using dictionary
* KOReader version: Newest
* Device:Kobo Glo

#### Issue
Crashed when highlight 2 words using dictionary 
#### Steps to reproduce
1. Select 2 words and press dictionary.
2.Press highlight.
3.Crashed.
##### `crash.log` (if applicable)
stack traceback:
	frontend/apps/reader/modules/readerhighlight.lua:505: in function 'saveHighlight'
	frontend/apps/reader/modules/readerhighlight.lua:452: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:87: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:105: in function 'handleEvent'
	frontend/ui/widget/dictquicklookup.lua:340: in function 'callback'
	frontend/ui/widget/button.lua:198: in function 'action'
	frontend/ui/uimanager.lua:518: in function '_checkTasks'
	frontend/ui/uimanager.lua:669: in function 'handleInput'
	frontend/ui/uimanager.lua:765: in function 'run'
	./reader.lua:190: in main chunk
	[C]: at 0x00013fc5

### PR DESCRIPTION
**Pull request by poire-z**
Closes #3305. Solution 1) in https://github.com/koreader/koreader/issues/3305#issuecomment-334732632

### CODE REVIEW

**Comment by poire-z** [comment]
```
[ 75%] Performing build step for 'mupdf'
    GEN include/mupdf/pdf/name-table.h
Illegal instruction (core dumped)
```
Random build failure, or else?

**Comment by Frenzie** [comment]
I've seen that occasionally the past few days. I think it's just a Travis issue.

**Comment by Frenzie** [comment]
A quick search suggests it's the Travis OOM killer kicking in. I'm not entirely sure why this should happen in the first place or why Clang seems to be more susceptible to it.

I noticed something curious btw:

`${PROCESSORS}` (only here)
https://github.com/koreader/koreader-base/blob/3e9b63f5cafc12335e18ea8ed313aa01c004b745/thirdparty/libffi/CMakeLists.txt#L27-L28

vs `${PARALLEL_JOBS}` (everywhere else)
https://github.com/koreader/koreader-base/blob/3e9b63f5cafc12335e18ea8ed313aa01c004b745/thirdparty/libiconv/CMakeLists.txt#L26-L27

`$PROCESSORS` is defined here:
https://github.com/koreader/koreader-base/blob/0d7ba992e3c12a6fd08c46c1e96d3d88142b5488/Makefile.defs#L135-L140

`$PARALLEL_JOBS` is that +1:
https://github.com/koreader/koreader-base/blob/3e9b63f5cafc12335e18ea8ed313aa01c004b745/thirdparty/cmake_modules/koreader_thirdparty_common.cmake#L30-L32

I'm guessing the remaining `$PROCESSORS` in libffi is just a leftover fluke. Anyway, I think Travis is supposed to have `~2 cores`, although I don't know how that translates to `/proc/cpuinfo|wc -l` terms. Whatever the case, we could consider adding something like ifdef $TRAVIS then PROCESSORS = 1. It'd probably slow down compilation (sigh) but it'd also reduce peak memory use.

**Comment by Frenzie** [comment]
But before we do anything like that, I should point out that @houqp has prepared a port of the frontend tests to CircleCI.

**Comment by poire-z** [comment]
For now, it happens unfrequently, and it's easy to retrigger the build (with close PR and re-open it), so I would do nothing to keep our 7-10 minutes check duration.

**Comment by Frenzie** [comment]
I just noticed looking at your log that it's always triggering a luajit rebuild thanks to my clever KODEBUG variable. Should be easy enough to fix by adding a little file exists check in there. (`cat whatever >/dev/null || nothing`… hm, actually how do you do that? Just echo ""?)

**Comment by poire-z** [comment]
`test -f whateverfile && ... || ...` ?

**Comment by Frenzie** [comment]
If you think that's clearer.

https://github.com/koreader/koreader-base/pull/536

I was only referring to the empty part, but of course cat empty-file is already the same as echo ""

For that matter just `cat kodebug-$(TARGET) 2>/dev/null` would also do the trick. No need for that echo business at all.

So… `test -f && cat` or `cat 2>/dev/null`?

**Comment by poire-z** [comment]
`cat kodebug-$(TARGET) 2>/dev/null` feels just fine

**Pull request merged**
