### PR TITLE
Slightly prettier virtual keyboard

### PR DESCRIPTION
**Pull request by NiLuJe**
Square keys with a thin border, and changed the flash from an invert to a temporary thick inner border, as discussed on Gitter (àla Kindle).

Depends on https://github.com/koreader/koreader-base/pull/846

### CODE REVIEW

**Comment by NiLuJe** [comment]
Obligatory screenshot ;).

vkeyb

**Comment by NiLuJe** [comment]
Hmm, moving a refresh of the full board on key release yields slightly different behavior:

Instead of disappearing keys, you have massive shreds of keyboard disappearing, but only temporarily.
It's potentially more distracting, and probably tanks the reactivity a tiny bit more, so, leaving this here for science...

```diff
diff --git a/frontend/ui/widget/virtualkeyboard.lua b/frontend/ui/widget/virtualkeyboard.lua
index 6cc173a2..02a7a8c0 100644
--- a/frontend/ui/widget/virtualkeyboard.lua
+++ b/frontend/ui/widget/virtualkeyboard.lua
@@ -137,10 +137,17 @@ function VirtualKey:update_keyboard(want_flash, want_fast)
         end
         -- Only repaint the key itself, not the full board...
         UIManager:widgetRepaint(self[1], self[1].dimen.x, self[1].dimen.y)
-        UIManager:setDirty(nil, function()
-            logger.dbg("update key region", self[1].dimen)
-            return refresh_type, self[1].dimen
-        end)
+        -- Refresh the full board on key release, to alleviate the disappearing key syndrom...
+        if want_fast then
+            UIManager:setDirty(nil, function()
+                logger.dbg("update key region", self[1].dimen)
+                return refresh_type, self[1].dimen
+            end)
+        else
+            UIManager:setDirty(self.keyboard, function()
+                return refresh_type, self.keyboard[1][1].dimen
+            end)
+        end
     end
 end
```

**Comment by avsej** [comment]
Cool stuff, I think once merged, it could close #4590

**Comment by Frenzie** [comment]
@NiLuJe 
> It's potentially more distracting, and probably tanks the reactivity a tiny bit more, so, leaving this here for science/discussion...

I haven't tested it, but iirc the keyboard used to do something along those lines for a while and it was awful.

**Comment by NiLuJe** [comment]
Hmm, yeah, I think the current behavior is the least annoying.

I could only mostly really get rid of eInk shenanigans by delaying the callback *a lot* (500ms), and the unhighlight a bit (150ms).

Also, managed to find out many new weird things about how broken A2 is on Kobo :D.

**Comment by Frenzie** [comment]
Darn Framagit. :-)

**Comment by NiLuJe** [comment]
Thanks for the xref @avsej , i'd forgotten that we had an FR open about it ;).

**Pull request merged**
