### PR TITLE
Notification menu entries: Drop "No notifications" as discussed in #7734

### PR DESCRIPTION
**Pull request by zwim**
This is the PR for the menu entry selection like discussed in #7743.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7736)

### CODE REVIEW

**Comment by Frenzie** [comment]
For clarity when reading the commit log in the future/in git blame I'd suggest something slightly more descriptive than menu UI as the commit/PR title. ^_^

For example:
```
Menu: remove "no notifications" option

As discussed in #1234
```

**Comment by poire-z** [comment]
`Conflicting files: frontend/ui/elements/screen_notification_menu_table.lua`
(Be sure you have master updated before starting some work, to avoid having to re-do it :/ was mostly just some indentation changes by https://github.com/koreader/koreader/commit/dac6fb400832e072f7c34d47e7ad9614443005a2)

**Comment by poire-z** [comment]
Btw, I have a gesture I used for testing with 5 actions :) After unchecking "... gestures", 4 notification are no longer shonw, but there is one that still gets a notification displayed: "Default highlight action changed to 'something'".

**Review by poire-z — APPROVED** [review]
Works as expected.

**Comment by poire-z** [comment]
> Btw, I have a gesture I used for testing with 5 actions :) After unchecking "... gestures", 4 notification are no longer shonw, but there is one that still gets a notification displayed: "Default highlight action changed to 'something'".

Given that it's from onCycleHighlightAction(), and it shows some info, I guess it's ok to have it still displayed.
The other ones that may still get shown are:
```
text = _("Location history cleared."),
text = _("Location history is empty."),
text = _("Default highlight action changed to 'highlight'."),
text = T(_("Default highlight action changed to '%1'."), (next_action or "default")),
text = T(_("Default highlight style changed to '%1'."), self.view.highlight.saved_drawer),
text = is_rtl and _("RTL page turning.") or _("LTR page turning."),
text = is_rtl and _("RTL page turning.") or _("LTR page turning."),
```
which, well, I think they give some feedback that I don't see anyone not wanting them :)

**Comment by zwim** [comment]
@poire-z  Thanks for the highlight hint. In readerhighlight there is `onCycleHighligtAction` wicht has no `notify` but a `UIManager:show(Notification:new{`.

I will change that in the next round of fixes.

**Comment by poire-z** [comment]
@Frenzie : any idea why image but image ?!

**Comment by Frenzie** [comment]
I assume @zwim hasn't authorized CircleCI?

**Pull request merged**
