### PR TITLE
frontend/device/kindle: KOA3: allow rotation-lock

### PR DESCRIPTION
**Pull request by a-m-joseph**
I have not tested this yet.  Still need to figure out how to build
koreader locally, and test things without bricking my
has-no-serial-console KOA3.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9138)

### CODE REVIEW

**Comment by Frenzie** [comment]
You can just change the file on your device and test it. There's no need to build anything for Lua, only if you change something in C.

**Comment by hius07** [comment]
You've changed the PW4 section, right?

**Comment by Frenzie** [comment]
@hius07 Heh, good catch, I only glanced at it for a split second.

But yes, the KOA3 already has that line:
https://github.com/koreader/koreader/blob/a0795f8286eb2bc9de2b95fe2a6d997ce60ae47d/frontend/device/kindle/device.lua#L420-L431

**Comment by a-m-joseph** [comment]
> But yes, the KOA3 already has that line:

Now I'm even more puzzled.

I will come back to this when I have a spare kindle with ssh that I am not afraid of bricking.

**Comment by NiLuJe** [comment]
FWIW, you have a near absolute zero chance of bricking anything by just tweaking Lua KOReader files live.

I do 99.9% of my testing by hot-swapping dirty commits via git diff + scp and a KOReader restart.

**Pull request closed without merging**
