### PR TITLE
WIP: forced_ocr-debug

### PR DESCRIPTION
**Pull request by mergen3107**
Supposed to help debug #11263. I just added `looger.dbg` here and there.
Stashing it all here - I needed a clean rebase for a new build.
In case someone needs to see what I tried :D 

Not supposed to be merge yet (unless we find a bug and fix it here).

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11315)

### CODE REVIEW

**Comment by mergen3107** [comment]
Side note: not sure why, but `l10n` folder always acts up in my clean build dev environments - I am not doing anything to it. How can I fix it?

These "changed" files showed up here as well.

**Comment by mergen3107** [comment]
How do I update this branch to master while keeping these two commits?
Possible at all?

**Comment by benoit-pierre** [comment]
Rebase.

Regarding `l10n`: the submodule gets forcefully updated to the latest revision when using `./kodev release …`. You can use the `-i` flag to prevent that: `./kodev release -i …`.

**Comment by mergen3107** [comment]
Thanks!
I just wanted to refresh this branch to continue debugging :D 
I did
```
git checkout Forced_OCR_boxes
git rebase upstream/master
```
but I don't think it worked. So I just force updated it via web interface to 2024.04-191 and then added these loggers by hand again.

**Comment by mergen3107** [comment]
Superseded by https://github.com/koreader/koreader/pull/12041

**Pull request closed without merging**
