### PR TITLE
Log zsync2's output, too.

### PR DESCRIPTION
**Pull request by NiLuJe**
Thanks to our good friend tee ;).

As suggested by @Frenzie on gitter ;).

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/5842)

### CODE REVIEW

**Comment by NiLuJe** [comment]
While the `tee` applet happens to be present on kindle-legacy (at least it was on a K3), I, err, don't quite feel like mangling the pipefail workaround to add another filter in the middle... ^^.

So this only applies to platforms where we can use pipefail ;).

Pinging @pazos to double-check that Cervantes ships with the tee applet, because we've had mishaps with their busybox builds before (sleep/usleep) ;).

**Comment by NiLuJe** [comment]
Fun fact: tee is a good little soldier, and managed to honor the CR, so we don't get a log full of spammy progressbar updates, but only the final state :).

**Comment by avsej** [comment]
```

**Comment by NiLuJe** [comment]
Ooh, real coreutils, cool! Thanks :).

**Pull request merged**
