### PR TITLE
[UX] Allow following links though hold/highlight dialog

### PR DESCRIPTION
**Pull request by Frenzie**
I realized I've got too many ideas just sitting around on my hard drive. The idea behind this one is that you can disable "follow links" on single tap yet still follow links.

### After

 

Of course if you just hold on some regular text it's disabled.

It actually takes you to one page prior to where the chapter actually starts, but that's not caused by this change.

### CODE REVIEW

**Comment by Frenzie** [comment]
Regarding the failing PDF tests: that must be why I never stuck it in a PR before. /smacks forehead

**Comment by poire-z** [comment]
Looking good.

Tap on links bothered me for 2 things: link to foonotes like `[2]` are too small, so i needed a few tries - and when changing pages with tap on Wikipedia epubs, where there are so many links it's hard to not hit one.
I mostly use "swipe to follow first link" (with an added "swipe to follow nearest link") to follow footnotes links.
So, I'll probably see how it does with tap disabled.

But to be able to disable only tap, and allow swipe to follow link, we may need to remove the test on isFollowLinksOn() in:
https://github.com/koreader/koreader/blob/75b7c4b524993b0d2e87664e88783ae628171a6d/frontend/apps/reader/modules/readerlink.lua#L219-L220

And rename "Follow links" top submenu item (Enable/Disable) to "Follow links with tap".
I'll do that in another PR after yours is merged if you don't do it :)

Only bothering thing with hold is that it will launch a dict lookup on `[2]` or parts of the link text, which may delay things in case of fuzzy lookup.

**Comment by Frenzie** [comment]
I just realized I messed up my second after screenshot. It was supposed to show this.



More important, you made me realize the menu should be changed in accordance with our UX menu guidelines.

### Before

 


### After

**Comment by poire-z** [comment]
(I don't see the diff in your first screenshot)
For documentation thru menu, we could add "Swipe **right/east** to go back" and "Swipe **left/west** to follow first link". Left/right or East/west, i dunno which is more obvious.

**Comment by Frenzie** [comment]
I suspect the Enable/Disable in this submenu might've predated the existence of the square root checkmark.

And yeah, the screenshots were fine. I was just glancing at them too quickly. :blush: 

I'd say left and right are much clearer than west and east. But I think if anything the problem with that option is the unstated "when you've followed a link", which is a bit long too include.

**Comment by poire-z** [comment]
I've never been sure and always ponder when i read it:
_swiping left_ (to go back, as you wrote it) is going to see what is virtually at left, and for that, you _move your finger to the right_?

You could move all the "go back" options at bottom (with or without a separator), so one now it's what happen after the follow links. And "Go back" at bottom, so it's easier to access with one hand.

**Comment by Frenzie** [comment]
Um, what? You swipe your finger to the left to *drag* the document to the right. If that's what you mean. :-P

**Comment by Frenzie** [comment]
Doesn't it make more sense for the actions to be higher than the options menu-wise?

**Comment by Frenzie** [comment]
Oh, now I understand. Swiping left (west) follows the first link and swiping right (east) goes back. That feels wrong to me.

**Comment by poire-z** [comment]
I wrote "Swipe right/east to go back".
You wrote "Swipe left to go back" in the code.
As I'm not sure about what swiping a direction means, I just wanted to make sure it wasn't a typo from you.

> You swipe your finger to the left to drag the document to the right

Uh, I hold and move my finger to the `right `to drag the current view to the `right` and show the previous view that was on its left (go back from link).
Is that swiping left or swiping right ? (again, my understanding of swiping may suck!)

**Comment by poire-z** [comment]
> Doesn't it make more sense for the actions to be higher than the options menu-wise?

I have no opinion on that. Just thought that, as some people use that Go back action (read that in some issue), it would be easier to access. With swipe down (uh! do we swipe down or up?) to activate top menu, it could be done one hand if the Go back is low enough.

**Comment by Frenzie** [comment]
You swipe your finger left to go back, right to go forward, down to open the top menu and up to open the bottom menu.

For these special link swipes, apparently you currently swipe left to go extra far forward and right to go extra far back. Besides being odd it also seems rather inconsistent. 

> Uh, I hold and move my finger to the rightto drag the current view to the right and show the previous view that was on its left (go back from link).

That was just a stupid example on my end as it doesn't apply in KOReader. You can only drag up and down, by swiping up and down respectively . For some reason, in Windows I have to swipe down to drag the document up. Very disorienting. Regardless, how you swipe with your finger is always the same and unrelated to what kind of action the software decides to attach to it. ;-)

**Comment by poire-z** [comment]
> For these special link swipes, apparently you currently swipe left to go extra far forward and right to go extra far back. Besides being odd it also seems rather inconsistent.

Mhhh. I hope you won't change the current behaviour, it's hardcoded in my fingers.
And, I don't have many experience with various tablet/phone navigation, but I'm pretty sure that in most android apps and MetroIE on windows tablets, you go back by holding and moving you finger to the right, dragging the current view to the right to make the previous virtually on the left appear. That feels totally natural to me.

> For some reason, in Windows I have to swipe down to drag the document up

Well, on windows tablet, I hold and move my finger up to drag the current view up and make what's below appears. That's natural to me, and to my little nephews :)

Well, may be we should just not mention left/right in the menu, and let people assume what's natural :)

**Comment by Frenzie** [comment]
> Well, on windows tablet, I hold and move my finger up to drag the current view up and make what's below appears. That's natural to me, and to little kids. edit: and it's exactly how koreader's scroll mode behave !

I was talking about on the touchpad. In Linux the multitouch is a marvel of usability. In Windows it's oddly jittery and counterintuitive. It's probably down more to drivers than anything. On my touchpad I'm not directly dragging the document. I'm executing a gesture to interact with the document.

> you go back by holding and moving you finger to the right, dragging the current view to the right to make the previous virtually on the left appear. That feels totally natural to me.

That's a completely different mode of interaction. You drag the document and once you cross a threshold it pops over. But I suppose when you put it like that it makes sense. But these are pretty traditional gestures, see this graphical explanation from Vivaldi: [back-gesture-vivaldi.ogv.zip](https://github.com/koreader/koreader/files/1289717/back-gesture-vivaldi.ogv.zip)

The real solution here is to have a left/right switch like the so-called left-handed/right-handed mouseclick option that's been on every windowing GUI since forever, or at least since Windows 3.1. Here is it in my Xfce.

screenshot_2017-09-09_13-04-04

(As a left-handed person I don't believe in that setting. If anything I think flipping it makes using the right hand more user friendly because clicking with your middle finger is nicer than clicking with your index finger, but that aside.)

**Comment by poire-z** [comment]
OK, I see, on a touchpad, it does not seem odd, gesture left looks fine as a way to go back.
On a touch screen, where there is a document below your finger, it feels more like I'm dragging the document that doing a gesture, so current behaviour, with this "dragging document" point of view, seems ok.

**Comment by poire-z** [comment]
2 little things noticed:
- when using Follow Link dict button, current location seems not added to the location stack, and "Go back to previous location" stays grey
- when Follow link closes the dictquicklookup window, the highlighted text is not unhighlighted (hold on a word on a wikipedia link > Follow link > Cancel), till a new word is hold and highlighted.

(I'll look at it later today if you don't beat me to it.)

**Comment by Frenzie** [comment]
In that case there might be something lacking about the `ReaderLink.ui = self.ui` I used. It's supposed to add the current location to the stack in`onGotoLink()`.

Anyway, I wouldn't look at it until tonight, if at all, so have at it! :-)

**Comment by Frenzie** [comment]
Never mind. I should've simply used `self.ui.link`. I'll push a fix later today.

**Comment by poire-z** [comment]
Just mentionning something I changed after a few hours reading with "Tap to follow links" disabled (which I prefer):
```lua
 function ReaderHighlight:onHoldRelease()
     if self.selected_word then
+        if self.selected_link then -- and G_reader_settings:isFalse("tap_to_follow_links") ?
+           self:clear()
+           self.ui.link:onGotoLink(self.selected_link)
+           return true
+        end
         self:lookup(self.selected_word, self.selected_link)
         self.selected_word = nil
     elseif self.selected_text then
```
Then, if I hold on a word part of a link, I follow the link. I can still access dict with long hold, but it happened I most often wanted the link.
Probably not candidate for a PR, as it would make documentation of tap & hold quite twisted :) but it felt convenient in my usage.

**Comment by Frenzie** [comment]
I like it, but I don't really see a sensible way to integrate it. (Even as an advanced setting, which would increase code complexity after all.)

**Comment by poire-z** [comment]
Just noticed that when no dict is installed, because of #2817, this Follow Link button is not available.

**Comment by Frenzie** [comment]
Adding a `link` into the early exit `self:showDict(word, final_results, box)` should do the trick. Don't forget though. :-P

**Pull request merged**
