### PR TITLE
Reversing commit 2348cd, changes to warmth values

### PR DESCRIPTION
**Pull request by rexkerr**
Somewhat urgent PR, please merge before the next stable build -- the changes I made somehow made the warm light hours even worse, so I'm reverting them.

Even though I've plotted the output of the algorithm multiple times in both a spreadsheet, and copied the algorithm into Python and made the minimal changes necessary to make it work in Python and plotted the output using numpy and the algorithm is absolutely correct -- there's something VERY weird about the warm-light code.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7296)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Could be tonight.

**Comment by NiLuJe** [comment]
On the off-chance someone has a bright (ha!) idea, what were the differences between the expected results and what actually happened?

**Comment by rexkerr** [comment]
@NiLuJe  For a bit of context -- the behavior was very strange -- the peak brightness time changed to 6:00 pm when set to 10:00 pm, which is exactly what my window variable was (coincidence?).  And then instead of dropping slowly it dropped even faster than before.

**Comment by NiLuJe** [comment]
Wild guess (only from the visible context in the diff, moght apply elsewhere in the logic): make sure everything is truncated to an int (e.g., math.floor()).

Lua numbers are `double`, and we've seen *very* weird shit happening in the past when stuff was fed a decimal when it didn't really expect to ever see one.

**Pull request merged**
