### PR TITLE
[WIP] Pocketbook-suspend plugin

### PR DESCRIPTION
**Pull request by mk-f**
Plugin which controls auto-suspending on PB-devices. 

Depends on https://github.com/koreader/koreader-base/pull/576

- Re-enable suspension as soon as possible after initial loading of the application has finished
- Disable suspension while in menues to smoothen user-experience.

For this to work i had to modify event-handling in ``readerconfig.lua`` and ``readermenu.lua`` slightly - i am not quite sure if this is the way to go, suggestions welcome.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/3540)

### CODE REVIEW

**Comment by Frenzie** [comment]
I don't think you've included the base bump yet? :-)

**Comment by mk-f** [comment]
I recently discovered that this will just partially resolve the issue: It just works if opening a file directly (from the PB-Library) instead of using koreaders build-in file-browser. This is because [this](https://github.com/koreader/koreader-base/blob/145e18a33e4c5c6ade6959329195776aea470959/input/input-pocketbook.h#L157-L162) Failsafe kicks in if ``ReaderReady`` is not called soon enough from the plugin. So i'll have to work some more on this.

**Comment by Frenzie** [comment]
Oh, I didn't mean merging master (unless you'd like me to bump base seperately?) but to checkout the right commit from within the base subdir. Usually just run `git pull origin master` from within the submodule. Then you can `git commit base` in the pocketbook-suspend branch.

**Comment by mk-f** [comment]
Yeah, i figured it out a ``git push`` too late ;).

**Comment by Frenzie** [comment]
See the comment above: https://github.com/koreader/koreader/pull/3540#issuecomment-352104749

**Comment by Horosenkov** [comment]
Frenzei) ok, by the https://github.com/koreader/koreader/pull/3540#issuecomment-352105696 you said to mk-f that you waited to not merge into master... )) so I can see that some not resovled conlifcts in this pull request
conflict

**Comment by Horosenkov** [comment]
And , Frenzie, you didnt answer -, does this plugin help with pdf file problems: forever waiting opening file , no response when turn pages ?

**Comment by Homaks** [comment]
@Frenzie , ok, I had misundestood. 
@mk-f , thank you for your answer, I hope you would solve this problem soon.
Maybe, do you need a help ? Much more logging information ? or any programming assist?))

**Comment by pazos** [comment]
@Frenzie @NiLuJe: I did look at this PR (and one merged on base) and my conclusions are:

- There's no need to set the timeout so low (2s). Probably can be made configurable from 30 seconds to a few minutes, like in Android.
- If we remove [these lines](https://github.com/koreader/koreader-base/blob/master/input/input-pocketbook.h#L158-L164) and set the timeout, based on user preferences, on device init we can skip the need of a plugin.

**Comment by Frenzie** [comment]
@pazos I've wondered the same thing (i.e., why not something between ~30 s to ~5 m). :-) Do you have a PB to test with now or something?

**Comment by pazos** [comment]
Superseded by #6559

**Pull request closed without merging**
