### PR TITLE
Kobo: Deal with some more frontlight edge cases on devices with the AW99703 PWM controller

### LINKED ISSUE #10970: Front-light delay when turned off
* KOReader version: 2023.08
* Device: Kobo Clara 2E
#### Issue
When turning off the front-light there is a noticeable delay of maybe 1 second or so, there is no delay when turning it on. This did not occur on older versions of koreader.
#### Steps to reproduce
Turn front-light on and off be it with a gesture, settings menu or putting the device to sleep.

### PR DESCRIPTION
**Pull request by NiLuJe**
Namely, skip ramping when going to/from <= 2% frontlight, otherwise we just eat the delay for no good reason (1%), or it just stutters and looks bad (2%).

Fix #10970

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10971)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Includes a minor OCD fix, in that the final step of a ramp up would not be delayed. Unlikely to change much because said delay is 25ms, but, oh, well ;p.

**Review by Frenzie — APPROVED** [review]
I'd be inclined to skip the ramp all the way up to 20% or so, heh.

**Comment by NiLuJe** [comment]
I was also mildly surprised, but it works surprisingly well, even at 3%!

(FWIW, most of my initial testing was done in the 12 to 25% range).

**Comment by Frenzie** [comment]
> I was also mildly surprised, but it works surprisingly well, even at 3%!

That's a slightly different statement. :-P I'm not really sure why there's a ramp at all really, but I understand it does some weird flicker on some devices without?

**Comment by NiLuJe** [comment]
> I'm not really sure why there's a ramp at all really

Because it looks cooler! :sunglasses: 

(No, really, that's it ;p)

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/10971)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pazos and @poire-z)

**Pull request merged**
