### PR TITLE
[AutoWarmth] use CheckButton for night mode toggle

### PR DESCRIPTION
**Pull request by ghost**
As promised in https://github.com/koreader/koreader/pull/10733#issuecomment-1646937303

Get rid of "Toggle night mode" button, not by renaming it, but changing it to a checkbox. Looks way better so.

grafik

Additionally, there are some minor optimizations in keeping the warmth value, when toggling night mode on/off.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10762)

### CODE REVIEW

**Comment by Frenzie** [comment]
I marked it as "not the upcoming release" for obvious reasons I think. ;-)

image

**Review by Frenzie — APPROVED** [review]

**Comment by hius07** [comment]
Excuse me, I've missed this PR at the time.

Do you really need to backup the added widget? I do not see any re-init in there.
Please look at the `ConfirmBox:addWidget()`, no re-init, no backups.

**Comment by hius07** [comment]
Okay, thanks.

**Comment by hius07** [comment]
I do not have the warmth light (Kindle Voyage).
Respectively, I see "Auto night mode" in the Screen settings menu.
https://github.com/koreader/koreader/blob/517731dbbbc41131bbcbd3309c8925732d0e93cb/plugins/autowarmth.koplugin/main.lua#L514
But I see "Auto warmth off" and "Auto warmth cycle..." actions in the Dispatcher.

**Pull request merged**
