### PR TITLE
Underline thickness increased

### LINKED ISSUE #11581: FR: [Make the quote highlight line thicker]
I really like the highlight line, unlike other options. 

But there is a minus: it is too thin and therefore too hard to see.

Can you make it bolder and more contrasting?  Can you make it customizable?

(1) I would highlight it in gray, but I don’t like the fact that there is no empty space between the lines, like in the Kindle. (2) And it’s a pity that there is no color highlighting... These two options are very necessary ;(((

### PR DESCRIPTION
**Pull request by Commodore64user**
fixes #11581

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11586)

### CODE REVIEW

**Comment by hius07** [comment]
I agree that the original line is rather thin



but your thick line overlaps with the lower highlight that is not good.

**Comment by Frenzie** [comment]
Also note it could be less gray and more black.

Incidentally, is it entirely intentional to make the height variable?

**Comment by poire-z** [comment]
Dunno if it should really be a factor of the crengine final line (our rectangles) height: if you have some text with taller headings or smaller text, the underline could be really variable between different sections of text. But it would at least be consistent in how it overlap or not with the text.
It could also be a factor of the user set font-size for something consistent (but if some text use font-size: 50% or 200%, it could be too large or too thin).

Also, use math.floor/ceil or Math.round() to make the resulting decimal value an integer nb of pixels, when setting/adding to x/y/w/h.

**Comment by Commodore64user** [comment]
It currently sits at `y + h - 1` which I suppose could be adjusted to `y + h - (h/8)`, however even with the current implementation, the underline already overlaps the descenders on some letters (i.e the part of a letter that descends below baseline, like in g’s and p’s), making it thicker means larger overlap, but raising it *might* under some circumstances make the whole think more unreadable or overlap with the baseline (i’m thinking worse case scenario here). So i guess my question is, how important is avoiding an overlap with a hypothetical highlight in the bottom line?

What is greyer than grey? Not being facetious, I remember @poire-z had a list with the 50 shades of grey (sorry i jest again, 16).

will `math.floor` it then.

**Comment by poire-z** [comment]
Where the baseline is, and the extend of the ascender or descender, all depends on the font, and there can be quite some variations (that can already be noticed with our rectangles, with some fonts you'll find the text obviously not centered in the rectangle, sometimes touching the top, sometimes the bottom).
The safest is to just split the line thickness half above, half below.

As for the thickness/ratio/ratio-to-what and color, I let the appreciation to @hius07 who implemented the current style (I'm not using it, so won't really care).

**Comment by hius07** [comment]
> Also note it could be less gray and more black.

Yes, what if we keep the height of 2 and make it just black?

**Comment by Commodore64user** [comment]
> > Also note it could be less gray and more black.
> 
> Yes, what if we keep the height of 2 and make it just black?

Black on black might give the impression of a strikethrough, maybe one or two steps below black, but again, what is greyer than grey and less than black?

by height of two, do you mean split it among the two lines like poire said? i.e `y + h - (h/16)`

**Comment by Frenzie** [comment]
https://github.com/koreader/koreader-base/blob/0b8442062c0c3b78ebd6088d0dbab082778cef89/ffi/blitbuffer.lua#L2300-L2316 if you want to play with any values.

**Comment by Commodore64user** [comment]
what about now, gents?

**Comment by Commodore64user** [comment]
One more thing, I just realised that KOReader calls `strikethrough` a `strikeout`, but a strike out is something to do with baseball, what's going on? Can I change that too?, to the actual name `Strikethrough`

**Comment by poire-z** [comment]
> but a strike out is something to do with baseball,

You're so American... There are other cultures you know, and in Europe, especially in France, _strike out_ as a verb means _refusing to work and going_ out _in the street protesting_. It's our national sport, and what this style of highlighting is all about :)

**Comment by Commodore64user** [comment]
> > but a strike out is something to do with baseball,
> 
> You're so American... There are other cultures you know, and in Europe, especially in France, _strike out_ as a verb means _refusing to work and going_ out _in the street protesting_. It's our national sport, and what this style of highlighting is all about :)

But I am in Europe… the UK is in Europe. I have never heard anyone refer to ~~this~~ as a strikeout. Cross out, yes, strike through also yes, never strike out though.

**Comment by Frenzie** [comment]
> what about now, gents?

How does that compare to the non-dynamic thick option you proposed?

> One more thing, I just realised that KOReader calls `strikethrough` a `strikeout`, but a strike out is something to do with baseball, what's going on? Can I change that too?, to the actual name `Strikethrough`

I assume that's a contamination between cross out and strike through. But preferably don't do that in this PR so it can be merged immediately. ^_^

**Comment by Commodore64user** [comment]
I believe this works a lot better. 

IMG_5404

It looks clean and neat, although…

IMG_5405

much like poire predicted, under some very specific circumstances, you do get some thicker/thinner underlines. But i think i am happy to make that sacrifice.

**Comment by hius07** [comment]
I vote for the fixed thickness.

**Comment by poire-z** [comment]
image

That looks more like a bug than like a sacrifice :) There's no real visual clue explaining why the underline on the first line is larger, so it feels like a bug. (I guess the reason is that the few works in some kind of smallcaps bring a larger line-height?)

Elsewhere, for the jump marker in the margin, we use:
https://github.com/koreader/koreader/blob/ca8e9352ba962e48843cd1d86812e42bdade7708/frontend/apps/reader/modules/readerrolling.lua#L842
so a fraction of that would give something constant.
BUT this is only available with CREDocument, not with PDF - where we have no idea of any font size, we just get rectangles.

So I think I agree, a fixed thickness like medium or thick is probably better. What if you just keep the medium and make it plain black ?

**Comment by jonnyl2** [comment]
> One more thing, I just realised that KOReader calls `strikethrough` a `strikeout`, but a strike out is something to do with baseball, what's going on? Can I change that too?, to the actual name `Strikethrough`

If you search [Archive.org](https://archive.org/search?query=+%22strike+out%22+&sin=TXT) for "strike out" and hover over the titles, you can find countless examples ranging from several hundred years old to current times that use "strike out" in the sense of removing a passage from a text, or similar.

**Comment by Frenzie** [comment]
> If you search [Archive.org](https://archive.org/search?query=+%22strike+out%22+&sin=TXT) for "strike out" and hover over the titles, you can find countless examples ranging from several hundred years old to current times that use "strike out" in the sense of removing a passage from a text, or similar.

I also doubt anyone would be confused by it regardless, but it is called strikethrough in the likes of MS Word fwiw.

**Comment by Commodore64user** [comment]
Yes, @Frenzie drop caps will increase the size of the box. I wanted to find an example with one of those gigantic ones but apparently I don’t have an ebook that has them… at least not in that kindle. Would be an interesting experiment to see what that would look like, if anyone has one at hand, please share a pic. 

As for @poire-z’s comment: I thought this was exactly what you were referring to when you said some boxes might have different dimensions. I was originally just going to go with `Size.line.thick` but you made me consider this idea. Regardless, i might try `marker_h` otherwise will just use thick instead. How many pixels does ‘thick’ use?

Does it need to be black BLACK? That level of grey not contrasting enough?

@jonnyl2 fair, i just checked the OED and they list strike out as ‘ cancel or erase by or as by a stroke of a pen’ among TEN more definitions for it. Strike through just the one, ‘To cancel (writing) by drawing a line through it.’

**Comment by poire-z** [comment]
> I thought this was exactly what you were referring to when you said some boxes might have different dimensions.

I was just thinking about headings, like your `BOOK I: THE STORY...` vs. the text. Didn't think it could indeed happen inside a same paragraph (thank you for your honesty :) you wouldn't have shown that 2nd screenshot and I would have approved :))

> How many pixels does ‘thick’ use?

https://github.com/koreader/koreader/blob/ca8e9352ba962e48843cd1d86812e42bdade7708/frontend/ui/size.lua#L63-L68

So, it's these abstract numbers scaled by some [magic formulae](https://github.com/koreader/koreader-base/blob/0b8442062c0c3b78ebd6088d0dbab082778cef89/ffi/framebuffer.lua#L412-L424) according to your screen size/user DPI (on my Kobo, it's `x 1.8`)

> Does it need to be black BLACK? That level of grey not contrasting enough?

It's for you to say :) The blacker it is, the less thick it can be I guess. The less thick it is, the less side effects (overlaps, ...)
So, the idea is to compare medium+BLACK vs. medium+DARK_GRAY vs. thick+DARK_GRAY.

**Comment by Frenzie** [comment]
@Commodore64user 

> Yes, @Frenzie drop caps will increase the size of the box.

While drop caps would be an implicit part of [my first reply here](https://github.com/koreader/koreader/pull/11586#issuecomment-2016539586) I'm not entirely sure what you're responding to.

In any case, my vote would be for an invariable thick in the current gray or a darker gray. For black I'd prefer medium.

Quoting to @poire-z to add to it a bit.
> So, it's these abstract numbers scaled by some [magic formulae](https://github.com/koreader/koreader-base/blob/0b8442062c0c3b78ebd6088d0dbab082778cef89/ffi/framebuffer.lua#L412-L424) according to your screen size/user DPI (on my Kobo, it's `x 1.8`)

Basically, thin will be 1 px on lower *and* higher density screens (more on extremely high density of course), medium will be 1 px on lower density and 2 px on higher density, while thick will always be at least 2 px on any device, 3 on higher density.

Also, while we haven't ever done it yet, it's conceivable to set different values depending on DPI in edge cases. That is to say, one value for low DPI (<250ish, maybe <200) and another for the look we're actually going for.

**Comment by Commodore64user** [comment]
Curiosity got the best of me: 

IMG_5408

IMG_5411

IMG_5409

IMG_5410

I suppose that settles the matter then, fixed thickness.

**Review by Frenzie — APPROVED** [review]
Fine by me.

**Comment by Commodore64user** [comment]
> I'm not entirely sure what you're responding to.

just realised I was actually replying to poire, not you. I must have confused the whole thing.

it does look a bit thin and flimsy with larger font sizes but...

**Comment by Frenzie** [comment]
That's how I like it to look. Well, not "thin and flimsy" but "like a confident straight pencil line".

**Pull request merged**
