### PR TITLE
ReaderHandmade: support for custom TOC and hidden flows. BookMap and PageBrowser tweaks

### LINKED ISSUE #3553: Customize the total pages for reading statistics
Many books have several parts like notes and glossary which we usually don't read them using the same way we read the rest of the book. So it's not accurate to account them while calculating "Time to read".

Is that possible to let the reader customize the total pages for each book?

Thanks!

### LINKED ISSUE #5604: (FR). Allow the percentage read calculation to be recalculated in cases with a long bibliography
Use case.  

I'm finishing up a book with a very long bibliography of more than 10 percent of the overall Koreader rendered pages.

It would be useful to be able to set An arbitrary end point for such books so that I know what the percentage read actually is.  I usually don't read the whole bibliography after finishing the book.  Also would be useful if pages left could be adjusted to the end of the actual book and not the end of available pages counting all parts of the book.

### LINKED ISSUE #7729: FR: Set "end book at" page in place of last page
I'd like to be able to set an "end book at" page in place of the last page, for books that e.g. contain footnotes (I'm looking at you, Anna Karenina) and "read an excerpt from the author's next book".

My thought is that this would replace the last page number in "pages left/remaining/etc" in the footer and perhaps elsewhere.

I've had a few thoughts on how to implement this, including:

1. Letting the user choose an "end chapter", so "end book at" would be set at the last page of the chapter
2. Letting the user directly enter a last page. This could be converted to a percentage, and recalculated when a book is reflowed.
3. Letting the user set a bookmark, and have "end book at" be set to "next bookmark"

Is there any interest in this sort of thing? If so, I would appreciate any thoughts on how to best implement it.

### LINKED ISSUE #8254: Progress Tracking in Academic Books
This is not exactly a feature request but more like a probe to see if other people would prefer a solution to this (smallish) problem.

In KOReader we have: 
- Progress bar
- Progress percentage
- Pages left in book
- Book time to read

to help a user see how much left in a book.

**But there is a problem with non-fiction, especially academic books:** 
After the last chapter there are many extra sections like acknowledgements, appendixes, chapter notes, keywords index, bibliography etc. These sections are not read linearly in the usual sense, they are more like references. But they add to the book page count (of course). This makes progress tracking features useless.

**For example:** 
I am currently reading a book which is **355** pages. But last chapter actually ends at page **243**. 
When my progress percentage shows **50%**, I am at **72%** actually. 
Currently I have **186** pages left according to the status bar. But it is actually **74** pages.

Of course there is nothing wrong with how KOReader is calculating these stats, but with these kind of books these stats become meaningless.

**Solution I thought:**
Maybe ability to mark a chapter as **EXTRA** (or something like that) so KOReader pretends book ends there.

**Example:**
...
CONCLUSIONS...184
APPENDIX...243
NOTES...284

In the example above, user can mark **APPENDIX** chapter as **EXTRA** so KOReader calculates all stats like the book is 243 pages.

### LINKED ISSUE #8512: FR: Better support for self-made ToC
I read a lot of PDF files that have no built-in table of content — often they are scanned text with an OCR layer. Many scientific papers are in that form. For them, I can generate a simple ToC by highlighting some or all section and chapter titles and navigate via the bookmarks menu. This works quite well, especially since now the bookmarks are in the right order. But it could be better.

I think of the following improvements:

-  A menu item with which one can move a bookmark or highlighted text to the ToC, where it appears as a chapter title. By default, the text in the ToC should be the highlighted text, but it needs to be editable because OCR sometimes fails.
- As an addition, I would like to see  a possibility to modify the indention level of a ToC entry, to display sections and subsections correctly. This modification would also be useful on its own, since there are a number of ebooks around with errors in the sectioning.

### LINKED ISSUE #10209: FR: Option for removing endnote section from progress bar
**Does your feature request involve difficulty completing a task? Please describe.**
In books with lots of notes, the *Notes* chapter can use more than 50% of the progress bar, making it less useful.

**Describe the solution you'd like**
A simple checkmark option under `Gear -> Status bar -> Progress bar` that ignores the *Notes* chapter when displaying it.

**Describe alternatives you've considered**
I am not sure if it's possible to do, or if there is no way of knowing what the *Notes* chapter is. I tried searching but I could not find anything related to this, maybe I can fix it by editing a file or some styles.

**Additional context**

Screenshot_20230315-101416

### LINKED ISSUE #10253: FR: Exclude index, bibliography pages, etc. from reading statistics
Many non-fiction books have several dozens of pages of bibliography, indexes, notes, etc. at the end that are not meant to be read page by page. As a result, a book may be read to the end but the reading progress says that only 80% has been read. It also skews with the information on estimated time to finish the book, and makes the number of pages to finish unreliable. 

Let's consider the following generic book structure:

Page no; Contents

1; Cover page
2-4; Copyright, dedication
5-6; ToC
7-8; Acknowledgments
9-11; Preface
12-13; Foreword
14-17; Introduction
18-159; Chapters 1-9
160-165; Conclusion
166-180; Appendix
181-195; Notes and Bibliography
196-199; Index
200-202; Empty pages and back cover

Now if you're at say page 140, it'll say you you're at 69% (140/202) and still have 62 pages to read until finished (and it will measure the remaining time estimate based on 62 pages), even though page 165 will be the last page you read. (Or page 180, if the Appendix is read-worthy, which will depend on the book and the reader.)

I have thought of 2 potential solutions to this issue; one simpler and one slightly more complex one:
__
**Suggestion 1:**

The user can manually set the final page to read in the book. This would depend on preference, but in the given example most likely be either 165 or 180 (I'll pick 165 now).

On page 140, reading progress will say 140/165 (85%), and 15 pages left to read.
Time spent on pages 166+ will not count toward read pages and be disregarded by statistics.
If you're on, say, page 190, reading progress could say 190/165 (115%) or just stay at 100% (which might make more sense to some users). No. of pages left to read will say 0.

**Suggestion 2:**

User can specify a **range** of pages to be read in the book, e.g. [9-165]. The advantage would be that one could also exclude title pages, ToC, and other immaterial pages that skew reading statistics. Again, only pages within the specified range would be considered for the reading statistics and any time spent on pages outside that range would not be counted. 

In the status bar, the actual page number would be shown (e.g. 5 / 202), but the reading progress would only start at page 9 (so 0%). While on page 30, page no. would show as 30 / 202, but progress would show as 13% (21/156), and so on.

While this solution would be a bit more elegant, it would probably take more work and the pages to exclude at the beginning are usually much fewer than the ones at the end of a book. Also, once they are skipped, they don't skew the number of pages and time remaining to read anymore.
__

I'd be interested to know your opinion on this suggestion. This is by no means anything I'd consider essential; just an idea I wanted to share. Thanks for reading.

### LINKED ISSUE #10436: FR: "Book time to read" depending on the actually read pages
I've noticed that the "book time to read" in the book statistics depends on the current page. Given that some pages or chapters/articles may have been skipped during reading, or may have been scheduled to be read later, I think it would be more accurate if the "book time to read" depended on the number of actually read pages.

What do you think?

### LINKED ISSUE #10811: FR: Page Browser Preload Thumbnails
In page browser UI, a certain grid of MxN previous and next 'page thumbnails' of a PDF or ePUB are shown relative to the current reading page, and by swiping right or left (or up or down), the user can reveal the previous or next set of pages' preview thumbnails. This is very helpful for quick navigation to identify, e.g., section headings.

**Problem:** 90% of the time when I open Page browser, I intend to swipe left or right, and there is some delay that occurs as the preview thumbnails of each next/previous page are generated after swiping. On my Boox Max Lumi, a 3x3 grid of PDF pages took ~5.1 seconds to completely load. Once a set of pages is rendered, it seems to be cached as future swiping between set of pages is near instantaneous. 

**FR:** It would be nice to _pre-load_ the previous and next MxN grids of pages that are to be shown when the user swipes on Page browser. A balance must exist between caching for performance and memory usage, so I propose only preloading 1 MxN grid immediately before and 1 grid immediately after the currently-viewed grid of pages, and only start these pre-loading of thumbnails after the currently-viewing MxN grid is finished loading. If the user swipes and reveals one of these (potentially partially) pre-loaded grids, then once that grid is completely loaded, start preloading the next 1-distance neighbor MxN grids around that cell after.

I hope this would improve user-perceived load times, improving the usefulness of Page browser with hopefully negligible performance impact. Apologies if this has been done already—there has been a lot of work done on page browser lately but I didn't see anything specific to this.

### PR DESCRIPTION
**Pull request by poire-z**
Discussed & screenshots all along https://github.com/koreader/koreader/issues/10193#issuecomment-1685376756 and followups.
Thanks to @jonnyl2 for the tests, discussions and hard negotiations :)

#### FrameContainer: allow for hatched background or overlay

Bump base for `BlitBuffer:hatchRect()` https://github.com/koreader/koreader-base/pull/1661 .
Also includes:
TODO, BUMP koreader-base if not yet done BEFORE MERGE

#### InputDialog: add param to `setInputText()` to set cursor pos

When not provided, the cursor stays at its initial position, which might not be the best if replacing the whole content, where we would prefer to have it at start or end.

#### ReaderPaging: use `document:getNext/PrevPage()`

instead of doing arithmetic (ie. `new_page=cur_page+1`).
This makes it ready to work with custom hidden flows where these `document:getNextPage()/getPrevPage()` will be overloaded to skip pages in hidden flows.
Also fix some odd issues (page truncated or with parts duplicated) with scrolling/page turning when at start or end of the document (ie. when scrolling back to the first page, the second page, if shown, would shrink as you scroll back into the wall).

#### ReaderToc: rework `getChapterPageCount/Left/Done()`

Rework the way they are computed, fixing issues with hidden flows when they don't coincide with chapter starts.
See https://github.com/koreader/koreader/pull/6847#issuecomment-1697856521.
@Jellby : pinging you for a quick review as this was your code.

#### ReaderThumbnail: fix slow thumbnails when in scroll mode

If originally with two-columns in page mode, and switching to scroll mode, thumbnails generation would be slow as the document would be rerendered for each thumbnail.

#### BookMap/PageBrowser: allow mousewheel scrolling

Also fix SDL to use `sendEvent()` instead of `broadcastEvent()`, so such BookMap scrolling doesn't also scroll pages in the book below :). See https://github.com/koreader/koreader/pull/3826#pullrequestreview-1629560829.

#### PageBrowser: add option to preload next/prev page thumbnails

Closes #10811.

#### PageBrowser: taller vertical marks for thumbnail rows in viewfinder

Instead of a small markers below the baseline, use translucent vertical lines over most of the ribbon's height to mark thumbnail rows, so we can more easily relate chapter spans to thumbnail rows.

#### PageBrowser: allow tap/hold on thumbnail before it is loaded

There was no real reason for having to wait.
Also avoid possible crash when a background generated thumbnail would be displayed after other things happened.

#### BookMap/PageBrowser: update upper instance when leaving lower one

BookMap and PageBrowser instances can be stacked; when toggling a bookmark in a lower PageBrowser and closing it, make sure the bookmark is shown in the BookMap we get back to.
Also consider TOC and hidden flows as a thing that can be edited and needs refreshing, so we're ready for next commits about custom TOC and custom hidden flows.
Also update Reader footer when closing the last BookMap or PageBrowser.

#### BookMap: add option Alternative theme

When enabled in BookMap, both BookMap and PageBrowser get:
- alternating gray background on chapter spans
- hatched background instead of uni-gray on hidden flows.
Also, with both normal look and this alternative theme, show some hatched overlay on thumbnails part of hidden flows.

ReaderToc: for each TOC item, have it carry its sequence/number in that level (we do this in `validateAndFixToc()` where we are already iterating all the items).

#### Add ReaderHandmade: support for custom TOC and hidden flows

Checkboxes under `TOC>Settings>` allows enabling Custom TOC and Custom hidden flows (similar to `Hide non-linear fragments` available with some EPUBs).
Handled by a new ReaderHandmade module.
Adding and removing TOC chapters is done in PageBrowser with long-press on a page thumbnail, and for chapters also in the popup dialog after selecting some text in a page.

ReaderToc: add a symbol in title when the TOC is the alternative TOC or a custom TOC.

The custom hidden flows stuff re-uses all the things put in place for support of EPUB non-linear fragments in #6847 #6809. So, this PR brings no change to how things currently look/behave (except for the small fixes described above and making this supported with other formats than EPUB).

This is available with all document formats (PDF, EPUBs...), whether or not they already have a TOC or non-linear fragments. Enabling Custom TOC or hidden flows just hides the originals (without touching them), that we can meet again by disabling them (toggling each of them has been added to Dispatcher, so they can be associated to a gesture).

Linking all related issues (whether closed or not yet) for cross-reference:
Closes #8512.
Closes #7729.
Closes #8254.
(Supercedes previous attempts #8265 #10900.)
Closes #10209.
Closes #10253.
(Original ideas for the popup in PageBrowser with these at https://github.com/koreader/koreader/pull/10230#issuecomment-1476810313)
Closes #5604.
Closes #3553.
Closes #10436.

Note: if we one day implements "custom page numbers" (to add/update offsets for page numbers so we can have have KOReader add them to internal page numbers to get displayed page numbers match the original PDF page numbers), it should be done in ReaderHandmade. #10848 #9212.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10982)

### CODE REVIEW

**Comment by poire-z** [comment]
Thanks :)

> As I can get, original document hidden flows are overwritten, not extended, with the handmade ones?

Right. It's either the publisher hidden non-linear fragments, or the user custom hidden flows (which are initially empty, we don't start them with a copy - or transparently include - the publisher non-linear fragments). It feels complicated if we'd want to have some kind of merge, and I can't really see a use case.
But one can toggle between the 2 with the menu or a gesture.

**Comment by poire-z** [comment]
For our stupid/unit tests specialists:
45be86a0b makes one fails:
```
[ RUN      ] ./spec/front/unit/readertoc_spec.lua @ 76: Readertoc module should get page left of chapter
/usr/share/lua/5.1/luassert/assertions.lua:126: the 'same' function requires a minimum of 2 arguments, got: 1

stack traceback:
    ./spec/front/unit/readertoc_spec.lua:80: in function <./spec/front/unit/readertoc_spec.lua:76>
```

```lua
    it("should get page left of chapter", function()
        assert.truthy(toc:getChapterPagesLeft(10) > 10)
        assert.truthy(toc:getChapterPagesLeft(95) > 10)
        -- assert.are.same(nil, toc:getChapterPagesLeft(290)) -- fails as above        
        require("logger").warn(type(toc:getChapterPagesLeft(290)), toc:getChapterPagesLeft(290)) -- fails with  bad argument #1 to 'type' (value expected)

   -- if I do it that way, it works
        local left = toc:getChapterPagesLeft(290)
        require("logger").warn(type(left), left)
        assert.are.same(nil, left)
    end)
```

So, my fix in readertoc.lua could be an ugly (because we tell new contributors about Lua that "no need to `return nil`, just `return`"
```diff
    local next_chapter = self:getNextChapter(pageno)
    if not next_chapter then
        -- (ReaderFooter deals itself with nil and pageno in last chapter)
-       return
+       return nil
    end
```

Is there something I don't get ?!

**Comment by NiLuJe** [comment]
> Is there something I don't get ?!

That seems harmless enough ;).

(And, yes, technically, returning "nothing" *is* different than returning `nil`, it's usually harmless because they're all falsy, but there is a technical distinction between the two).

**Comment by Frenzie** [comment]
Very impressive!

**Comment by hius07** [comment]
Side question, sorry.
https://github.com/koreader/koreader/blob/6ccf19b99f5fa1d6280f643b71c48a7318c790f0/frontend/apps/reader/modules/readerrolling.lua#L11
What module is loaded here (and in tens other modules)?
Isn't `bit` built-in?
utils.lua and device.lua use it without declaration.

**Comment by NiLuJe** [comment]
It's indeed redundant for LuaJIT, where BitOp is a builtin.

That's useful for other Lua implementations to pull the BitOp module in; it also happens to be completely harmless on LuaJIT, where it'll just do nothing ;).

**Pull request merged**
