### PR TITLE
HW rotation causing PB632 inversion state issues

### PR DESCRIPTION
**Pull request by JasperE84**
More details here:
https://github.com/koreader/koreader/issues/7017

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7022)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by NiLuJe** [comment]
Err, arguably, the inversion flag issue is an actual KOReader bug, not a PB quirk, so I'd rather *that* were fixed in base ;).

(e.g., That's kind of a NACK to merge this, because it just hides the issue on *this* specific device).

**Comment by NiLuJe** [comment]
Given that your device shouldn't be using a B288 chip (or this would already have been disabled), it might actually still be necessary...

So, new round of tests (*without* this PR applied):

* Given your earlier tests, you should be able to reproduce the issue after disabling the C BB: (In the FM): Tools > More Tools > Developer options > Disable C blitter

What about with *this* applied?

```
diff --git a/ffi/framebuffer_linux.lua b/ffi/framebuffer_linux.lua
index d93e4392..7491b32c 100644
--- a/ffi/framebuffer_linux.lua
+++ b/ffi/framebuffer_linux.lua
@@ -180,7 +180,10 @@ function framebuffer:setRotationMode(mode)
         -- as well as prod the driver via new mmap() as some do tie down rotation modes to each mapping.
         self.cur_rotation_mode = mode
         self:setHWRotation(mode)
+        -- Remember the screen bb's invert flag, too
+        local inverse = self.bb:getInverse()
         self:reinit()
+        self.bb:setInverse(inverse)
         assert(self.forced_rotation, "reinit/fb hooks shouldn't flip hw rotation flags")
         if self.forced_rotation.restore then
             self:setHWRotation(self.native_rotation_mode)
```

It *should* fix it with the CBB disabled, but it *might* not with it enabled. So, try both ;).

**Comment by NiLuJe** [comment]
> Given that your device shouldn't be using a B288 chip (or this would already have been disabled), it might actually still be necessary...

Actually, no, HW rota is only disabled on B288 iff the waveform presets are set to "fast".

So, new new question: I'd like to see a debug log to confirm that it's indeed not a B288. (In the same "Developer options" menu, "Enable debug logging". Restart KOReader after toggling it).

**Comment by JasperE84** [comment]
Here you go. https://www.dropbox.com/s/umt0dilless7rr7/crash.log?dl=0

BTW, c blitter was already disabled in dev options

**Comment by NiLuJe** [comment]
Ha!

```
DEBUG mxcfb: Disabling hwinvert on B288 chipset
```

So, at least stuff is starting to make a tiny bit of sense.

Does the patch in https://github.com/koreader/koreader/pull/7022#issuecomment-749112978 help?

**Comment by JasperE84** [comment]
Yep! That fixes it with the PR reverted!

**Comment by NiLuJe** [comment]
Cool, thanks :).

----

I can't really help with the rotation stuff, because that way lies madness, but it's been touched upon before, IIRC ;).

**Comment by NiLuJe** [comment]
Closing in favor of https://github.com/koreader/koreader-base/pull/1264 (which will hit front Soon(TM) ;)).

Unless there are actually other HW-rotation induced issues (besides the aforementioned rotation switch between the InfoMessage and the Reader)? (Which wouldn't be surprising, it's a B288 after all...).

**Pull request closed without merging**
