### PR TITLE
Make sure InputText has a consistent API, regardless of hasDPad

### LINKED ISSUE #8967: Crash when saving a comment
* KOReader version: 2022.03.1-5
* Device: Kobo Aura One

#### Issue
KOReader crashes when saving a comment on the book status page.

#### Steps to reproduce
1. Open *Book status* (e.g. from the menu, or by paging past the last page).
2. Click in the comments section to open the input pop-up.
3. Click on *Save* on that pop-up.

##### `crash.log` (if applicable)
The crash log is from 2022.03-1.3, but the problem persists.
[Crash.txt](https://github.com/koreader/koreader/files/8409285/Crash.txt)

### PR DESCRIPTION
**Pull request by NiLuJe**
Fix #8967
Regression since #8859

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8968)

### CODE REVIEW

**Comment by NiLuJe** [comment]
(Refactored to keep it DRY).

**Comment by Biep** [comment]
Does this mean it is solved?

**Comment by Frenzie** [comment]
It should be in the latest nightly, yes.

**Comment by Biep** [comment]
Thanks!

**Pull request merged**
