### PR TITLE
Remove onSetFullScreen()

### PR DESCRIPTION
**Pull request by hius07**
Not used.

This
https://github.com/koreader/koreader/blob/0386e2619eb5c11367980741af062d3865ea4e8c/frontend/ui/data/koptoptions.lua#L379

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12871)

### CODE REVIEW

**Comment by Frenzie** [comment]
Alright.
https://github.com/koreader/koreader/commit/1d292f16a9d6884046a957301cd8a7af9a3b42be

**Review by Frenzie — APPROVED** [review]

**Comment by poire-z** [comment]
Looks ok, but not familiar with kopt, readerview, and toggling off our footer, so no idea how just tap on footer is equivalent to this setting if it would be enabled.

**Review by NiLuJe — APPROVED** [review]
*should* be fine at a quick glance ;).

**Comment by poire-z** [comment]
This PR caused a crash when starting koreader with `KO_RTL=y`.

```
./luajit: frontend/ui/data/koptoptions.lua:652: attempt to index local 'j' (a nil value)
stack traceback:
  frontend/ui/data/koptoptions.lua:652: in main chunk
  [C]: in function 'require'
  frontend/apps/reader/modules/readerconfig.lua:7: in main chunk
  [C]: in function 'require'
  frontend/apps/reader/readerui.lua:31: in main chunk
  [C]: in function 'require'
```

Probably because after the `full_screen` kopt option item was removed by this PR, some hardcoded index(es) in there should be updated:
https://github.com/koreader/koreader/blob/42fd1e86bf720f1e6ff329678fe65fed187ceff4/frontend/ui/data/koptoptions.lua#L646-L666

**Comment by hius07** [comment]
After 6 years, do you think it should be fixed by updating the hardcoded indexes?
Or is it better to cycle over all options to find the target ones by `name`?

**Comment by poire-z** [comment]
As you prefer (no pb with iterating as it's done only once on the initial require()).

**Pull request merged**
