### PR TITLE
Third-party bumps

### PR DESCRIPTION
**Pull request by NiLuJe**
* https://github.com/koreader/koreader-base/pull/1631
* https://github.com/koreader/android-luajit-launcher/pull/422

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10681)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Oh, joy, a busted implosion. Has been a while -_-".

**Comment by NiLuJe** [comment]
Yeah, usual busted + luajit flakiness with the lj-sqlite3 finalizers.

**Comment by NiLuJe** [comment]
Or... not ;D.

**Comment by benoit-pierre** [comment]
I can reproduce with the meson branch, but only when not running each test (spec file) in its own process.

**Comment by benoit-pierre** [comment]
So it might be related to that (busted crappy isolation).

**Comment by benoit-pierre** [comment]
I've done a round of third-party bumps too, so I don't know if it's because of that. We'll let you know.

**Comment by NiLuJe** [comment]
> Or... not ;D.

I started actually running the emu, and I'm getting segfaults really quickly in the FM with a stack that appears completely trashed...

(So, I'm going to guess LuaJIT? :D)

(Trying w/o the JIT to confirm).

**Comment by NiLuJe** [comment]
e.g.,
```
Thread 1 "reader.lua" received signal SIGSEGV, Segmentation fault.
0x000055de6c1c6fab in ?? ()
(gdb) bt full
#0  0x000055de6c1c6fab in ?? ()
No symbol table info available.
#1  0x0000000000000008 in ?? ()
No symbol table info available.
#2  0x000000000000000d in ?? ()
No symbol table info available.
#3  0x00007f3ca7c1fb20 in ?? ()
No symbol table info available.
#4  0x0000000000000000 in ?? ()
No symbol table info available.
```

Which appears to be smack in the middle of the mcode area, IIRC:

```
┌─(niluje@ahsoka:pts/17)───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(/var/tmp/niluje/koreader/koreader-emulator-x86_64-pc-linux-gnu-debug/koreader)─┐
└─(0.03:18%:03:09:%)── cat /proc/$(pidof luajit)/maps                                                                                                                                                                                                                                                                                                  ──(Wed, Jul 12)─┘
55de33ad3000-55de33adb000 r--p 00000000 00:21 1269620                    /var/tmp/niluje/koreader/base/build/x86_64-pc-linux-gnu-debug/luajit
55de33adb000-55de33b39000 r-xp 00008000 00:21 1269620                    /var/tmp/niluje/koreader/base/build/x86_64-pc-linux-gnu-debug/luajit
55de33b39000-55de33b53000 r--p 00066000 00:21 1269620                    /var/tmp/niluje/koreader/base/build/x86_64-pc-linux-gnu-debug/luajit
55de33b53000-55de33b55000 r--p 00080000 00:21 1269620                    /var/tmp/niluje/koreader/base/build/x86_64-pc-linux-gnu-debug/luajit
55de33b55000-55de33b56000 rw-p 00082000 00:21 1269620                    /var/tmp/niluje/koreader/base/build/x86_64-pc-linux-gnu-debug/luajit
55de35aa0000-55de36b4f000 rw-p 00000000 00:00 0                          [heap]
55de6c1c0000-55de6c230000 r-xp 00000000 00:00 0 
7f3c9c000000-7f3c9c021000 rw-p 00000000 00:00 0 
```

**Comment by NiLuJe** [comment]
Yup, definitely a JIT issue, works fine w/o it. (`-joff`).

**Pull request merged**
