### PR TITLE
Gesture intervals spinwidgets - do not show default value in info-text

### PR DESCRIPTION
**Pull request by hius07**
Default value is shown in the SpinWidget default button, no need to show it in the info-text.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8488)

### CODE REVIEW

**Comment by hius07** [comment]
Side question: what are the reasons to declare local spinwidgets in each menu item (7 times)?
https://github.com/koreader/koreader/blob/372dd9e36bad836946b8ebfddb59edabc6f791f1/plugins/gestures.koplugin/main.lua#L474-L479

In the meantime there is at the beginning
https://github.com/koreader/koreader/blob/372dd9e36bad836946b8ebfddb59edabc6f791f1/plugins/gestures.koplugin/main.lua#L12
for a widget used only once.

Is there a general rule, where to declare widgets in the modules?

**Comment by hius07** [comment]
A point to discuss: in the DoubleSpinWidget default button **applies** default values immediately
https://github.com/koreader/koreader/blob/372dd9e36bad836946b8ebfddb59edabc6f791f1/frontend/ui/widget/doublespinwidget.lua#L204-L210
in a special way, with nil arguments (the historical reason is that DSW has been made of `hyphenationlimits` module).

Regarding SpinWidget, since we see the default value in the button, maybe it is useful to rename this button to
`Apply default value`
with immediate action too?

**Comment by poire-z** [comment]
> Side question: what are the reasons to declare local spinwidgets in each menu item (7 times)?
> Is there a general rule, where to declare widgets in the modules?

No real reason, and no rule.
Sometimes, I add some in a callback because it feels I just need it there (ie. TextViewer) and there's no real need to load it at the top with the module if it will rarely be used (and save a few microseconds and kB or RAM wasted).
Then, it gets copy/pasted as we add menu and dialogs ;)
No objection if you feel like moving the commonly used ones to top.

> Since we see the default value in the button, maybe it is useful to rename this button to Apply default value with immediate action too?

Dunno. Some of these with CRE documents if applied immediately would re-render the document. I think there are situations when one could use default to just reset the spin values to some "middle" values (instead of having to tap tap tap tap +/-), and continue tweaking from there (ie. just one unit + or - from the defaults).

**Review by poire-z — APPROVED** [review]

**Comment by poire-z** [comment]
If you're done with it, feel free to merge when you wake up, so it ends in next nightly.

Another note about merging: the more PRs we can group and merge on a same day (vs. merging one PR each day), the longer old nightlies stay at http://build.koreader.rocks/download/nightly/ - which might occasionally help when bisssecting issues that affect devices only.

**Pull request merged**
