### PR TITLE
progressbar(fix): persist progressbar visibility

### LINKED ISSUE #1995: Status Bar state is not remembered
* KOReader version:koreader-nightly-20160427
* Device:BOOX C67ML

#### Issue
I open a book. I enable the status bar. I read the book for a while. When I open the book next time the status bar is not there, I have to renabled it everytime I start reading.

#### Steps to reproduce
Read above

### PR DESCRIPTION
**Pull request by houqp**
fix #1995

### CODE REVIEW

**Comment by houqp** [comment]
Oh god, my dear tests, why are you failing :(

**Comment by Frenzie** [comment]
```
[1mReaderLink module should be able to go back after link jump in pdf in scroll mode[0m
spec/front/unit/readerlink_spec.lua:102: Expected objects to be the same.
```

Hm, looks like the heigh and y values are minutely different. Could it be that it didn't show the status bar previously and it should simply be adjusted or is there an actual issue?

**Comment by houqp** [comment]
Likely, what I don't understand is why I cannot produce the failure locally.

**Comment by houqp** [comment]
Fixed, still no idea why it works in local unit tests ;P

**Pull request merged**
