### PR TITLE
FileManagerHistory: remove harmful deletion code and turn it into a feature

### LINKED ISSUE #2477: Don't keep removed files in the history
If a file (that appears in the history) is removed through the long press file dialog, then it will still be present in the history.

### PR DESCRIPTION
**Pull request by Frenzie**
Fixes the problem introduced in 51327911f2fbea00258717d7b284e061ad31832e and turns it into a feature that should fix #2477

## New button
screenshot_2017-02-25_19-09-42

### CODE REVIEW

**Comment by Frenzie** [comment]
Hold off on merging, I seem to have missed something even though it seemed to be working before.

**Comment by retrue** [comment]
I see a problem with the user interface here.
You long press on a single book to bring a contextual menu that let you do things to that single book (get information and/or removing it from history) and that let you do things to the whole history (clear history of all deleted files in history). It is confusing at least. The user could think that it is deleting the history of that single book only and only if that book was deleted.
Imho "Clear history of delete files" should appear on the new hamburger menu under "History".

**Comment by Frenzie** [comment]
I think it should appear nowhere at all. :-P

You're right of course that it's not the best place, but the fact that you press it and the list updates itself is very valuable direct visual feedback. I don't think decoupling it is the solution. Anyway, I fixed the error.

**Comment by retrue** [comment]
What about a permanent button on a corner of the History window? Same way that you get the X to close History, you could have a button with an icon on another corner that popped up a window saying:
"Clear the history of all the deleted files?"
"Yes"     "No"

**Comment by Frenzie** [comment]
Well sure, but that's a lot harder. The harmful code must go, so the alternative from my perspective is to just kill it without keeping it as a feature if this interim solution is unacceptable.

**Comment by Frenzie** [comment]
Oh wait, there's one thing I hadn't noticed.

@poire-z wrote:
> But I'd like it if there is a (default'ly unset) 'autoremove_deleted_items_from_history' setting that will make the current auto-cleaning still happen for those who like it :)

I'll toss in something like this:
```lua
local autoremove_deleted_items_from_history = G_reader_settings:readSetting("autoremove_deleted_items_from_history") or false
```

**Comment by poire-z** [comment]
I find it acceptable :)
You could add a "ALL" in "Clear the history of ALL deleted files" to make it more striking.
If that's not enough, wrap it in a ConfirmBox.
In any case, please let that `ReadHistory:clearMissing()` in the code.

Indeed, a top left button with ♲ (U+2672 '\xe2\x99\xb2' UNIVERSAL RECYCLING SYMBOL) or ♻ (U+267b '\xe2\x99\xbb' BLACK UNIVERSAL RECYCLING SYMBOL) could be nice, but that needs extending/subclassing menu.lua's Menu.

> I'll toss in something like this:

Thanks!

**Comment by poire-z** [comment]
Regarding autoremove_deleted_items_from_history , you may wish to do some more things for consistency:

In 'Purge .sdr' action https://github.com/koreader/koreader/blob/master/frontend/apps/filemanager/filemanager.lua#L173
I decided to remove also the item from history, for my convenience - but deleting from history is unrelated to purging .sdr. So you may make that a conditional of this setting (even if its name is unrelated, well people who put that setting on like i will may expect agressive cleaning...)

In 'Delete' action https://github.com/koreader/koreader/blob/master/frontend/apps/filemanager/filemanager.lua#L202
If autoremove_deleted_items_from_history , you may do there what I did in 'Purge .sdr'. That would solve #2477 OP expected behaviour.

**Comment by Frenzie** [comment]
I reckon that should about do it.

**Comment by poire-z** [comment]
Just tested these 3 commits, and it works fine and as discussed and expected, without and with this new setting.

We should have a wiki page documenting the available settings that are not manageable thru menus (i added quite a few these last months).

**Comment by Frenzie** [comment]
If you run a quick `grep -r "G_reader_settings:readSetting"` the number doesn't look that horrible. But there must be a way to automate this somehow — I mean not just getting the settings, but documenting what they do. I'm just not entirely sure how off the top of my head.

**Pull request merged**
