### PR TITLE
InputContainer: consistent input type in onInput()

### PR DESCRIPTION
**Pull request by hius07**
Closes https://github.com/koreader/koreader/issues/11990.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12012)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Not sure we if we really want to change the variable name (mainly for backwards compat, especially with 3rd-party plugins) ;).

Good idea to clean this up, though, thanks!

**Comment by hius07** [comment]
> backwards compat, especially with 3rd-party plugins

They would get the main (letters) layer of the keyboard instead of the numeric (symbol) layer, that's it, not a big issue I believe.

**Review by poire-z — APPROVED** [review]

**Review by Frenzie — APPROVED** [review]

**Review by NiLuJe — APPROVED** [review]

**Comment by Biep** [comment]
Just updated a minute ago, but still have issue #11990, so I suppose I still got a nightly from before the update.  Will try again tomorrow.

**Comment by NiLuJe** [comment]
Yup, the merge came juuuust after the nightly build (~6AM GMT) ;).

**Comment by Biep** [comment]
Hmm..  I just now checked, and got "KOReader is up to date" - but the keyboard issue persists.

**Comment by benoit-pierre** [comment]
It missed the deadline for the nightly, try tomorrow.

**Pull request merged**
