### PR TITLE
add Basic Authentication for OPDS catalog

### LINKED ISSUE #1001: feature request: authentication in OPDS catalog
Hi

I am trying to test calibre integration on Linux version. It works, i can login to my local calibre and browse however it is complaning that the file cant be saved to "/sdcard", other folders do not work either. 

Is this a limitation or similar issue to I bugged about calibre download fails on Kobo?

thanks

### PR DESCRIPTION
**Pull request by chrox**
use coroutine to support ad-hoc callback in login button so that when
the username/password is incorrect it will retry automatically
currently tested with COPS on apache
This should fix #1001.

### CODE REVIEW

**Comment by KenMaltby** [comment]
"All checks have failed" and all the little red "x"s,  does that mean the code won't be added or won't work? Is it just a warning for something you are aware of and safely discount?  I've been seeing this a lot lately.

**Comment by Frenzie** [comment]
What you see under details is more important. There's one check in the unit tests that's currently not working out and needs to be updated, perhaps because of [this change](https://github.com/koreader/koreader-base/commit/3d9bd2aa6a5794a9114f3273a01382be606765c3). It's to help against inadvertently breaking something.

**Comment by chrox** [comment]
@Frenzie The failed test in `readersearch_spec` :
```
stack traceback:
    spec/front/unit/readersearch_spec.lua:61: in function <spec/front/unit/readersearch_spec.lua:50>
```
``` lua
            for i = 1, 5, 1 do
                rolling:gotoPage(i)
                local words = search:searchFromStart("Verona")
                assert(words == nil)
            end

```
which tests full text search from the beginning of a book to current page for EPUB format. So it's definitely cannot be affected by https://github.com/koreader/koreader-base/commit/3d9bd2aa6a5794a9114f3273a01382be606765c3 which only changed the scale in PDF/DjVu reflowing.

**Comment by Frenzie** [comment]
My bad, I hadn't investigated but the PR said "update crengine" and the
title sounded relevant.

**Comment by chrox** [comment]
Never mind, I didn't notice that PR had a crengine update which might have something to do with this. Will look into this tonight.

**Pull request merged**
