### PR TITLE
Progresswidget: invert read chapter marks

### PR DESCRIPTION
**Pull request by hius07**
Closes https://github.com/koreader/koreader/issues/8191.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8195)

### CODE REVIEW

**Comment by poire-z** [comment]
Tested, and it works in RTL too.

But for small progress bars like in the footer, when it is crowded, making the past ticks white make it feel like no longer a progresss bar :/

Before:
image

After:
image
**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^ this footer bar**

Dunno how to avoid that... Do it only for wide bars ? Calculate the average tick density and see if it is ok to switch to white ? :/

**Comment by hius07** [comment]
Maybe add a setting `Status bar - Progress bar - Style - Invert chapter markers`?
Or just allow a user to reduce Progress bar ToC depth for a certain book.

**Comment by poire-z** [comment]
> Or just allow a user to reduce Progress bar ToC depth for a certain book.

One can already do that. But having to do that because something that used to look good enough does look bad now... feels like not the right solution :)

> Maybe add a setting Status bar - Progress bar - Style - Invert chapter markers?

If it's global like all the other footer settings, not the solution either - you'd need to toggle it for every other book because your progress bar looks like not a progress bar - just so you can get white ticks for books with a small toc. Users will probably not enable that option and keep what we have.
And if it's per-document, well, will need some human action to decide about it on every new book.... not worth the hassle to make one footer setting a per-document setting I think.

So, either abandon the idea, or let @offset-torque come up with a sliding window algorithm to compute the average density of ticks vs. not-ticks on the past progress width, and decide of a threshold where it will be ok for the human eye to switch to white while having some overall grey that will make it look like a progress bar :)

**Comment by offset-torque** [comment]
To be honest in poire-z's example, **BEFORE** version doesn't look like a progress bar too. There's no way to show chapter boundaries when 65 chapters squeezed into 2 cm of screen space. That bar in the image can only show percentage reliably, not position relative to chapters. At that point why even use chapter marks if they join together as a black block.

Current implementation is extremely poor regarding UX guidelines about contrast.

This is the contrast ratio on LCD:
contrast ratio

And this is on e-ink:
contrast ratio eink

**Comment by poire-z** [comment]
> To be honest 

Please try to be :) It still looks enough like a progress bar, even if you don't see the chapter boundaries. There are cases when everything is too crowded and all seems filled, but it should be better than white ticks in a lot more cases.

@hius07 : may be just try to not use white, but some other kind of gray, so the past width will not have white at all. Then, it would be just a matter of finding the right gray values for filling, past ticks and future ticks.
(I don't understand much about these contrast screenshots, hope others do.)

**Comment by offset-torque** [comment]
Yours is a strawman argument. I have books with over 100 chapters. How will they look if I try to use your tiny example with a full ToC depth ? You may have eagle eyes but see below to see what a proper UI should prioritize:

> I don't understand much about these contrast screenshots, hope others do.

Web Content Accessibility Guidelines (WCAG) 2.1 covers a wide range of recommendations for making Web content more accessible. Following these guidelines will make content more accessible to a wider range of people with disabilities, including accommodations for blindness and low vision, deafness and hearing loss, limited movement, speech disabilities, photosensitivity, and combinations of these, and some accommodation for learning disabilities and cognitive limitations; but will not address every user need for people with these disabilities. These guidelines address accessibility of web content on desktops, laptops, tablets, and mobile devices. Following these guidelines will also often make Web content more usable to users in general.

**Success Criterion 1.4.3 Contrast (Minimum) 
The visual presentation of text and images of text has a contrast ratio of at least 4.5:1**

2.8 is really bad. 1.8 is awful.

**Comment by hius07** [comment]
COLOR_LIGHT_GRAY

<kbd></kbd>

<kbd></kbd>

<kbd></kbd>

**Comment by poire-z** [comment]
> COLOR_LIGHT_GRAY

Looks good enough to me :) On eInk too ?

> Yours is a strawman argument. I have books with over 100 chapters. How will they look if I try to use your tiny example with a full ToC depth ?
You may have eagle eyes but see below to see what a proper UI should prioritize:

As on the screenshots above, like something that ressemble a progress bar filled from the left ?
Again, that's for the default look, that should be "ok" (a progress overview bar, too bad if the chapter boundaries make it dirty and it's not super clean, but it should at least look like it's progressing).
If you have 100 chapters and you care about more than just the overall progress, the options are there: limits ticks levels, smaller tick widths, wide progress bar above or below the other info.

After that, do try to do good UI in 3 cm :) We can't aim at good UI, but we can aim at a progress bar that looks like it's progressing :)

**Comment by Frenzie** [comment]
NB There's also a BB.COLOR_GRAY_E.

**Comment by poire-z** [comment]
> > COLOR_LIGHT_GRAY

> Looks good enough to me :) On eInk too ?

Well, thinking again about gray, might not be too wonderful for some people/devices :)

On my GloHD, anything gray cause some little distracting animations when appearing or getting back to black or white, so I expect my footer to go crazy distracting :) (Can't test right now.) I'll probably patch this out in my own patch.
But I think our main customer for this @offset-torque too is sensitive to that, so not sure he'll like the gray solution :)
But in principle, it's probably good.

**Comment by hius07** [comment]
The best view is with WHITE and reasonable ToC depth.
Changing to GRAY (GRAY_E is lighter and close to WHITE) worsens the view with reasonable ToC depth (lower contrast), but makes acceptable the view with increased ToC depth.
Taking into account that overcrowded progress bar looks poor in any case (that inspired this great setting of reducing ToC depth), I would prefer to have the perfect view with reasonable ToC depth, i.e. white.

**Comment by poire-z** [comment]
> I expect my footer to go crazy distracting 

Hold on, but we already have the past background gray, aren't we ? :) So, it was already happening - but I didn't find it distracting then :/

> Taking into account that overcrowded progress bar looks poor in any case (that inspired this great setting of reducing ToC depth), I would prefer to have the perfect view with reasonable ToC depth, i.e. white.

So, you'd have to do the density computation to see if you can switch to white. Or find some other solution, because we just can't have it looking like this by default:

image

**Comment by hius07** [comment]
> density computation to see if you can switch to white

I'd propose just 50 ticks threshold.

**Comment by Frenzie** [comment]
> I'd propose just 50 ticks threshold.

Discrimination. :-P
Screenshot_20210908_171226

**Comment by hius07** [comment]
Need testing in different books
`bar_not_crowded = self.tick_width * #self.ticks / bar_width < 0.2`

**Comment by hius07** [comment]
<kbd></kbd>

<kbd></kbd>

**Comment by poire-z** [comment]
> bar_not_crowded = self.tick_width * #self.ticks / bar_width < 0.2

Yes, something like this, at minima.
May be you could do this for only the "past ticks" over the "past bar width" (so, needs to be down on each drawing, unlike yours which you could do once). because it can happen (it feels I've often seen that) that you have many chapters at start and none at end (ie. large section of footnotes).
You can also have many overlapping ticks (or does the code that give us the tick list takes care of that?), so this average density is not really accurate. But I believe that if it's the case, you'll just be not switching to white bars, so it will stay black and filled and ok.

(Or may be we can have some other idea, like making a 2nd border on the past bar, so it feels bolder even with white ticks ?)

**Comment by hius07** [comment]
> You can also have many overlapping ticks (or does the code that give us the tick list takes care of that?), so this average density is not really accurate. But I believe that if it's the case, you'll just be not switching to white bars, so it will stay black and filled and ok.

Encountered that when switched chapter marker width to thick (so, many overlaps).
That caused the bars to be black, while the progress bar didn't look overcrowded.

I think the threshold can be increased to 30%. Hard to test, because I do not have many books with various ToC levels.

**Comment by poire-z** [comment]
> because I do not have many books with various ToC levels.

Wikipedia lookup EN or RU, lookup countries like Russia or Ukraine, or History of Ukraine, Save as EPUB, and you should have quite crowded TOCs with various levels :)

**Comment by poire-z** [comment]
Btw, why not just keep all ticks black, and just use a lighter gray for the "past"/"filled" background ?
We don't need high contrast for filled-black vs remaining-white, but we need one for past-ticks vs past background.

**Comment by hius07** [comment]
> many chapters at start and none at end

Half of the book is read, the bar is overcrowded

<kbd></kbd>

Reading more, the bar is not overcrowded (as intended)

<kbd></kbd>

Seems to work.

**Comment by poire-z** [comment]
^ not sure what you meant, aren't the ticks white on both screenshots ? I would have expected with the later code that if on the first screenshot, it is overcrowded as you say, they would stay black.

**Comment by hius07** [comment]
> aren't the ticks white on both screenshots ?

They are white in skimwidget (with narrow ticks). Look at the status bar (medium width ticks).

**Comment by hius07** [comment]
Changing ToC level

<kbd></kbd>

<kbd></kbd>

**Comment by hius07** [comment]
Black ticks

rectdim = 1/3

<kbd></kbd>

rectdim = 0.2

<kbd></kbd>

**Comment by poire-z** [comment]
OK, got it, bottom bar :)

Dunno about the change of color, on your latest "with white" screenshot, it feels white could still work. But there'll be always cases where our decision/threshold/computation turned out to take not the best decision :/
Also, you'll have to check how it works with "alt" (non-linear flow) and may be tweak it too :/

----

Thanks for the rectdim screenshots. Of course it looks less nice than with white ticks, but well, I guess I'll be ok with it as it solves the issue of not seeing ticks, while being consistent and avoiding the risk of switching colors and taking not the best decision (and/or needing to do more maths :)

0.15 feels a bit light on your screenshots, but anything above 0.2 looks fine with me.

Not sure why we currently use bb:lightenRect(), we could have used paintRec with a proper bb.COLOR_XYZ_GRAY to be nice with the eInk palete (@NiLuJe ?).

**Comment by hius07** [comment]
The pictures differ from e-ink screen.
On e-ink rectdim=0.3 is perfect with black ticks. Nothing more is needed imo.

**Comment by Frenzie** [comment]
@poire-z 
> Btw, why not just keep all ticks black, and just use a lighter gray for the "past"/"filled" background ?
We don't need high contrast for filled-black vs remaining-white, but we need one for past-ticks vs past background.

That was basically what I meant by mentioning that there are lighter grays.

@hius07 
> On e-ink rectdim=0.3 is perfect with black ticks. Nothing more is needed imo.

Unless there's a good reason not to we should explicitly use one of the E Ink colors.
https://github.com/koreader/koreader-base/blob/ac9a8757de78769150c3ac084170cb6744183435/ffi/blitbuffer.lua#L2173-L2180

Color x looks better on LCD/OLED and turns into nearby E Ink color y could be a good reason, though it might be better to make it more explicit in that case.

**Comment by hius07** [comment]
Currently it is coded
https://github.com/koreader/koreader/blob/ecf378067d17b5a5eb3686c6c04bfdcadfef1abb/frontend/ui/widget/progresswidget.lua#L47

**Comment by Frenzie** [comment]
New since https://github.com/koreader/koreader/pull/6847

Anyway, if it's not a real change then sounds good. ;-)

**Comment by hius07** [comment]
bb:paintRect with COLOR_LIGHT_GRAY or COLOR_GRAY for filling looks good.

**Comment by Frenzie** [comment]
Better. ^_^

**Comment by poire-z** [comment]
> New since #6847

Well, bb:paintRect() was changed to bb:lightenRect() with the non-linear flows PR... so, hard to just revert it and not worry :) pinging @Jellby for opinions/whys/alternative ideas.

**Comment by NiLuJe** [comment]
Am I the only one actually finding the *current* status quo to be the least worse looking option of everything that's been tried so far? ;o).

**Comment by NiLuJe** [comment]
I'd possibly be inclined to simply shift the "filled" color one gray tone lighter (same question about the effect of that on the flows stuff as above, though), but, again, I'm perfectly fine with the current contrast ratio.

**Comment by Frenzie** [comment]
> Am I the only one actually finding the current status quo to be the least worse

Nope, I oppose this change. It's a progressbar.

**Comment by poire-z** [comment]
Since https://github.com/koreader/koreader/pull/8195#issuecomment-915511064, I think we all agree about forgetting white ticks, and that keeping black ticks is saner, and switching to a lighter gray for the background "past" area.
The remaining point is about which gray, and using :lightenRect with a factor vs :paintRect and a COLOR, and how it behaves with non-linear flows.
Not much time to put my mind on it, just showing what we currently get (any FB2 with footnotes get to have `[ ] Hide non-linear fragments`):

image

image

**Comment by hius07** [comment]
I propose rectdim = 0.3 for :lightenRect or COLOR_GRAY for :paintRect.
To decide it needs to see on the device, not on screenshots.

**Comment by poire-z** [comment]
> I propose rectdim = 0.3 for :lightenRect **or** COLOR_GRAY for :paintRect.

"or" ? good :)
So, rectdim = 1/3 instead of current 2/3 ? So not much code and logic change and we don't have to ask ourselves more questions about gray. I like it :)

Tried on my GloHD:
- 1/3 feels a bit light, especially with footer's small (3cm) progres bar, when many ticks, you hardly see progress
- 2/5 tad better
- 1/2 even better (I do see progress on busy small bar), and everything is visible
- 2/3 (current) is really bad, ticks and even non linear flows are hard to grasp

Needs tests on other devices and people eyes :)

**Comment by hius07** [comment]
> "or"

Depending on choice of :lightenRect / :paintRect which is out of my scope of knowledge yet.

Agree with 1/2.

**Comment by offset-torque** [comment]
> But I think our main customer for this offset-torque too is sensitive to that, so not sure he'll like the gray solution :)

@poire-z

contrast_demo

**Comment by hius07** [comment]
@offset-torque, can you try to change
https://github.com/koreader/koreader/blob/e16d36d5da658c18871789bbb300f95d835c7bb1/frontend/ui/widget/progresswidget.lua#L47
to 1/2 and restart the program. Is it a good contrast?

**Comment by offset-torque** [comment]
> Is it a good contrast?

@hius07 

Definitely better. I think considering the raised objections, this solution is a good compromise.
Position in chapter can be detected with a glance, which was the main issue.

This is how it looks like on a Kobo Libra (indoors / sunny day):
pb_contrast

**Comment by Frenzie** [comment]
@offset-torque 
> contrast_demo

Is that supposed to be a "this is what green and red look like to color blind people" type picture? Because on my H2O it's rather significantly more readable than that if I make the background the same gray as the progress bar. ;-) The contrast is just a bit suboptimal, not utterly awful.

But anyway, that's besides the point. I'm much more on board with your suggestion made in jest to remove them altogether.

This is a progressbar first and foremost. Everything else is secondary. 

With the current design, you have the choice between detrimental to all or not advantageous to all. My pick under those constraints is the latter. But I'm certainly not attached to the specific look the statusbar has! For example, if you get rid of the border and draw those chapter markings at double height you get something like this:

Before:
Screenshot_20210910_105019

After:
Screenshot_20210910_105019

I hope I can go back to lurking on the statusbar issue now. ;-)

**Comment by offset-torque** [comment]
@Frenzie
> I'm much more on board with your suggestion made in jest to remove them altogether.

I am misunderstood it seems. I said that from the perspective of a user, not as a suggestion of "removing marks from the bar".

I meant:
 "Under some width, chapter marks has to join together and they become useless (DPI limitation) because no space left between. This user CAN switch to **THIN PROGRESS BAR** version because he already can't see the chapter boundaries. Full depth ToC with that many chapters makes sense if progress bar is at a sensible width."

And I liked your AFTER version more actually. Minimalistic and even more visible !

**Comment by Frenzie** [comment]
> And I liked your AFTER version more actually. Minimalistic and even more visible !

Right, my point is that I think the current solution is (more or less) the best we can do under those specific design constraints. But I don't really understand why the entire discussion didn't bring up any alternative to said constraints.

**Pull request merged**
