### PR TITLE
[fix] Add current location to location stack from follow link popup

### PR DESCRIPTION
**Pull request by Frenzie**
See https://github.com/koreader/koreader/pull/3190#issuecomment-328332771

@robert00s Does this also solve the other issue you noticed?

### CODE REVIEW

**Comment by robert00s** [comment]
I think you mean @poire-z :)

**Comment by poire-z** [comment]
:)
Nope, it doesn't.
But the simple fix for this other issue is to replace (just before `self.ui.link:onGotoLink()`) your `UIManager:close(self) `with `self:onClose() `(which calls `UIManager:close(self) `+ clear the highlight).

(Confirmed the first issue is solved.)

**Comment by poire-z** [comment]
Oups, just noticed there's another one that need similar treatment:
https://github.com/koreader/koreader/blob/731093721919659d57417c60c211d8c8f253faa2/frontend/apps/reader/modules/readerhighlight.lua#L393
to be replaced with: `self:onClose()`

**Comment by Frenzie** [comment]
Thanks! :-)

**Pull request merged**
