### PR TITLE
News downloader manual

### PR DESCRIPTION
**Pull request by mwoz123**
To be merged  after  #4126

### CODE REVIEW

**Comment by poire-z** [comment]
I don't think that your news-downloader-manual.odt (419KB) and news-downloader-manual.epub (241KB) can be accepted.
There is nothing like that in koreader currently: they are big, binary-blobs, and can't be easily edited/fixed/updated and we'll not be able to diff the update changes.
Your best luck is to go like the Quickstart guide with markdown, and eventually images on the side (#2761, #2737).
Or documenting that on the Wiki, like everything else.

But the best would be that it's obvious enough that it doesn't need any specific documentation :)

**Comment by mwoz123** [comment]
I was  so sure quickstart guide is epub that I didn't check it. sorry..
ok I replaced epub and odt files with html. Is it ok now?

**Comment by poire-z** [comment]
I'm not sure such a manual is needed. You're saying and showing hardly much more than what the user can see on the screen... An introduction about Atom/RSS in an InfoMessage would feel enough...
And I don't like making koreader size greater with screenshots of koreader in koreader...
(What you wrote would find its place on the Wiki thus.)

Well, let's wait for others' opinions.

**Comment by mwoz123** [comment]
I assume some kind of help is always useful.
Maybe at the moment it's not the best, but it can develop in feature. 
I think couple sentences is InfoMessage is too small.
For sure I think manual/howto is needed for Send2Ebook, and planned to write it.

I could remove (most obvious?) the images, but thought they're ok as they're also are stored in `koreader/resources`.
I did heavily compressed them to average 10-15kbs and thought so small would be fine.

I know News downloader requires internet, so they could be somewhere on server but requiring internet to read manual /display images IMHO is not the best idea.

For the same reason having manual only on wiki pages is not what I like.
You may want to read it on your ebook reader and with wiki you need at least a phone/PC (bear for someone who wanted to  search that on eink reader;) and I bet much more users (not devs) read manual/howto when it's in program then when it's somewhere in github pages.

**Comment by KenMaltby** [comment]
The .epub or .HTML could just be another document that the plugin's help links to.  To keep from affecting KOReader's size, such manuals could be provided as separate downloads.

**Comment by mwoz123** [comment]
Does .html file (with or without images) would make difference? 

Sized compared:

Koreader:
- Freshed cloned KOReader git repo (before build) is  53 MB( `$ du -sh koreader 53M     koreader`) ~ **53 000 kb**
- After build (on my PC) it  takes 8,3 GB ~ 8300 MB ~ **8300 0000 kb** (see screenshot at bottom)
- Android apk package 35,8MB ~ **35 000 KB**

 My .html "manual" :
- is **<5 kb ((five! kilobites)** (assuming images are available only when wifi is on:( )
- with images **121,4 kb**
 
Is it really too big for thousands (or millions) kilobytes project?

If you really want to decrease size you could use [code minification](https://en.wikipedia.org/wiki/Minification_(programming)) but I'm not sure it's a good idea.

zrzut ekranu z 2018-08-07 21-10-11

**Comment by NiLuJe** [comment]
Hard to diff.

(Hence Markdown for the QS guide).

**Comment by poire-z** [comment]
It's not so much the size of *your* manual (to compare to the 32M zips we build), but when 10 plugin authors decide, like you, to do the same, or not nearly the same (you decided for HTML when we have not a single html file, they could decide for PDF, or plain txt), it will be a mess of different styles:

- your images are already obsolete (pathchooser changed, editor changed this weekend)
- when 10 plugin authors makes 10 manuals, we'll have obsolete screenshots made on 10 different window manager and different colored borders and title bars, and we'll be a colorfull patchwork of obsolete/never updated images and text.
- your HTML is not translatable, or there is no translation infrastructure in place for that - while koreader tries to do that for every user facing stuff.
The quickstart guide uses the existing translation infrasctructure, and must be 1 or 2KB of text.
https://github.com/koreader/koreader/blob/637abfdf84fb1125e05952bc73e41f80a612cb46/frontend/ui/quickstart.lua#L20-L23

(And, for me, you don't really say much more that what the user can already see and experience... "tap on this and you'll see that" - there's a few hints, but I thing you already put most of them in comments in the feed_config file, so that's a lot of duplicated stuff...)

**Comment by Frenzie** [comment]
@NiLuJe 
> (Hence Markdown for the QS guide).

Also for translations. Both to use the existing tools and so that translators don't need to know markup languages like HTML. I still can't think of a better option.

@mwoz123 
> I thought user experience is much more important.

Both better documentation/discoverability (mainly in-program, imo) and smaller filesize improve user experience. The user experience is precisely the contention here. :-)

> Is it really too big for thousands (or millions) kilobytes project?

By that reasoning almost nothing is ever "too big". All of KOReader front is 2.6 MB, including in-program documentation and [dev docs](http://koreader.rocks/doc/). All the plugins together are 774 kB. The biggest plugin is 168 kB of useful Lua code. So within its proper context you're talking about some 5% or 16% of the total size of the program, not the less than half percent you imply.

> If you really want to decrease size you could use code minification but I'm not sure it's a good idea.

Indeed, that would be a nightmare scenario. Also it would barely do anything at all since we're talking about precisely those parts of the program that compress very well. The images put together are roughly the same size as all plugins compressed (i.e., 100% instead of 16%).

As an aside, this PNG made lossy with `pngquant --quality 5` is the same size as your screenshots.

screenshot_2018-08-07_22-50-07-fs8

I'm not particularly in favor of adding screenshots, but if any were added they should preferably look more like that (and without any window decorations!). That's more of a generic wiki remark. Also see https://fransdejonge.com/2017/03/image-optimization-guide/#optimizing-png

As an aside, block-level elements don't go inside other block-level elements. What you get is:

```html
<p>
<!-- HTML auto-closes the <p> element -->
<h1>bla</h1>
</p><!-- dangling </p>, ignored -->
```

Fairly harmless, but still ugly.

**Comment by Frenzie** [comment]
1. If you mean Markdown, then yes, that's preferable for the various reasons mentioned above.
2. I really don't see any added value there I'm afraid.

**Comment by mwoz123** [comment]
2. Any free recommended/preferred servers for images hosting?

**Comment by Frenzie** [comment]
The GH wiki?

**Comment by Frenzie** [comment]
Note that my comment about added value was about putting in a full screenshot documentary of what's right there in front of you. On the wiki that's different, although even there I'd try to stick a little more to the essentials.

**Comment by mwoz123** [comment]
Too bad, so none  of the engines will show images (when online) event if it's in html file? :(

So there should be also function that downloads images, and manipulates html DOM to replace images url to local stored. 
We don't have anything like that actually in Koreader, right?

And GH wiki markup doesn't have an option to export to PDF nor Epub right?

**Comment by Frenzie** [comment]
> So there should be also function that downloads images, and manipulates html DOM to replace images url to local stored.
We don't have anything like that actually in Koreader, right?

That's pretty much exactly what the Wikipedia to EPUB functionality by @poire-z does.

> And GH wiki markup doesn't have an option to export to PDF nor Epub right?

See #1371.

**Comment by pazos** [comment]
Updated https://github.com/koreader/koreader/wiki/News-downloader

**Pull request closed without merging**
