### PR TITLE
Some rather critical Kobo networkmgr fixes

### PR DESCRIPTION
**Pull request by NiLuJe**
Again, to avoid potential USBMS issues on Kobos.

Depends on [base/335](/koreader/koreader-base/pull/335).

### CODE REVIEW

**Comment by NiLuJe** [comment]
That's not my workflow, so this is a question: should we try to kill wpa_supplicant & the dhcp client on exit when we're running without nickel?

**Comment by NiLuJe** [comment]
Meh, added PW3 handling while I was there ;p.

**Comment by Frenzie** [comment]
Seems like more trouble than it's worth. For on-device telnet debugging you'd probably want a switch to disable such behavior, for example, and also people might be used to the current behavior for other reasons.

**Comment by NiLuJe** [comment]
@Frenzie: Good point, thanks :).

**Pull request merged**
