### PR TITLE
Always close filemanger before open document

### PR DESCRIPTION
**Pull request by robert00s**
See comments:
https://github.com/koreader/koreader/pull/3933#issuecomment-386879892
https://github.com/koreader/koreader/pull/3933#issuecomment-386899058

### CODE REVIEW

**Comment by Frenzie** [comment]
To be sure though, did you test various failure scenarios? Also I worry that unless you put it a little further down (closer to `UIManager:show(reader)`)you'll just make showing the file manager in case of error take longer without a tangible benefit.

NB That's just a quickie; don't have time to really think about it atm and also I have a pretty heavy cold so my brain's not running at full speed. :-P

**Comment by robert00s** [comment]
I tested various scenarios. Open documents from history, opds catalog, from find a book, last document. I also try open damaged file. No problem. Everything looks like it works.

**Comment by Frenzie** [comment]
Same for putting it after the potential showFileManager() calls? Shouldn't `FileManager.instance:reinit()` be faster than `FileManager:showFiles()`?

**Comment by robert00s** [comment]
Can you say something more? I don't really know what and where to change :)

**Comment by Frenzie** [comment]
I mean somewhere underneath these lines instead of right above them:

https://github.com/koreader/koreader/blob/e3b7524d9c85ac810f8084d538df2ef3bbf8e2c7/frontend/apps/reader/readerui.lua#L449-L467

Otherwise you make these lines useless:

https://github.com/koreader/koreader/blob/e3b7524d9c85ac810f8084d538df2ef3bbf8e2c7/frontend/apps/reader/readerui.lua#L376-L380

You're kind of making them useless anyway because now it'll be slower to open the FileManager from ReaderUI, but at least if ReaderUI actually loaded properly it's for a good cause. (The menu not being in sync issue you mentioned.)

But actually it should go after `UIManager:show(reader)` (unless there's a good reason for it to go before), so as not to hold up showing the reader with closing actions.

**Comment by poire-z** [comment]
I've had that on my kobo since yesterday: no problem noticed.
Anything preventing merging after this last change?

**Pull request merged**
