### PR TITLE
Add explanation for shorten home folder

### PR DESCRIPTION
**Pull request by Frenzie**
Cf. <https://www.mobileread.com/forums/showthread.php?p=4098071#post4098071>.

----------

I'm not quite sure, thoughts?

Screenshot_2021-02-28_11-39-00

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7365)

### CODE REVIEW

**Comment by poire-z** [comment]
We have `help_text = "..."` to avoid having to do `UIManager:show(InfoMessage:new...)`.

No opinion about the info and wording, looks ok (even if Kobo specific).
But more help_text is always good :)

**Comment by Frenzie** [comment]
I don't think talking about other possible home folders like I did on the
forum would add much other than verbosity.

I'll update it to help text, but I think there are still many outdated menu
items then.

**Comment by NiLuJe** [comment]
I'd be inclined to use an actual Linux example (e.g., /home/$USER ^^), but it may or may not be any more helpful, so, eh' ^^.

In any case, +1 ;).

**Comment by NiLuJe** [comment]
Actually, we can pull the actual platform-specific from Device.home_dir? (may be nil, though).

**Comment by Frenzie** [comment]
> Actually, we can pull the actual platform-specific value from Device.home_dir? (may be nil, though).

The thought crossed my mind, but it might make localization harder.

**Comment by hius07** [comment]
The help text is clear.

It would be nice if the path in the header changes to `Home` immediately after setting the home folder via long-press on the home icon or via the "+" menu.
`Set as HOME folder` in the "+" menu might be greyed if we are in the Home folder.

**Pull request merged**
