### PR TITLE
ConfigDialog improvements 2

### PR DESCRIPTION
**Pull request by robert00s**
+ Fix height for ToggleWidget
+ Able ToggleWidget width more than half of width of screen

### CODE REVIEW

**Comment by Frenzie** [comment]
Curious.

> [  FAILED  ] spec/front/unit/readhistory_spec.lua @ 363: ReadHistory module should not automatically remove deleted items from history if setting has been set to false

That seems unlikely to be related to this.

**Comment by poire-z** [comment]
It seems in some cases (Screen DPI: Auto as on this screenshot, and that's actually how it looks on my Kobo), the ToggleSwitches are really wide and some margin may be missing:

<kbd>itemalign095</kbd>

I see you applied a factor of 0.95 as part of https://github.com/koreader/koreader/pull/3463/files#diff-aedbf40026b37bd6245e58e96bbed9a2R402 to make it a bit less wide.

0.85 in this case on the emulator looks a bit nicer (but 0.75 or 0.65 would too :) :

<kbd>itemalign085</kbd>

but I'm not sure it's the right way to "fix" that, as it may eat some space for text in other cases/DPI/Languages...
The ConfigDialog code is a bit intimidating for me to look more :|

**Comment by Frenzie** [comment]
Agreed that it looks a bit wide on my Kobo H2O as well. Not immediately sure what the most elegant way around it would be.

**Comment by robert00s** [comment]
Right, it looks wide. 
We can back to that:
https://github.com/robert00s/koreader/commit/198c15112558f327aebd6721ee30918d42fae09e#diff-aedbf40026b37bd6245e58e96bbed9a2L400
or change like @poire-z said to 0.85.

**Comment by poire-z** [comment]
Tested both 
`local max_toggle_width = Screen:getWidth() * 0.5`
and
`local max_toggle_width = Screen:getWidth() * item_align * 0.85`

And I prefer the old `* 0.5` with its smaller toggles like what we were used to.
But `* item_align * 0.85` is nicer with large screen DPI, mostly on the PDF right cluttered panel.
Still not sure which one to choose, so you both decide :)

**Comment by Frenzie** [comment]
I generally prefer the looks of smaller but I think if there's only one size it has to be slightly larger.

Visually using random values wouldn't be pretty but maybe we could make it automatically pick between small or large depending on content? Just brainstorming, mind you.

**Pull request merged**
