### PR TITLE
HTMLViewer: do not refresh footer

### PR DESCRIPTION
**Pull request by mergen3107**
Solves Item 2 (extra) in #9979

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10043)

### CODE REVIEW

**Comment by mergen3107** [comment]
I tested this on my Onyx device.

**Comment by NiLuJe** [comment]
That's `TextViewer` in its entirety, which might be a tad overkill (and completely wrong if it applies to not fullscreen DocxtQuickLookup, for instance).

**Comment by mergen3107** [comment]
Ok, what’s the HTML viewer only then?

**Comment by poire-z** [comment]
The HTML viewing is provided by TextViewer, and so is the CSS viewing and the Book description viewing.
These various instances of this TextViewer could be sized differently (even if I think they currently all get the default size).
Your change would have affected a small half-screen-sized TextViewer shown at top of the screen.
So, best to see what @NiLuJe can come up with to detect if top widgets really cover or not de footer.

**Comment by mergen3107** [comment]
OK, thank you!

**Pull request closed without merging**
