### PR TITLE
Cloud storage: add Dropbox short-lived tokens

### PR DESCRIPTION
**Pull request by hius07**
Long-lived tokens are not generated anymore, some old tokens are still valid though.

Short-lived tokens live 4 hours. To generate new access token you will need the refresh token and <APP_KEY>:<APP_SECRET> string Base64 encoded.
EDIT: Base64 encoding is not required.

More on Dropbox changes:
https://dropbox.tech/developers/migrating-app-permissions-and-access-tokens

Dropbox API endpoint to generate access token:
https://www.dropbox.com/developers/documentation/http/documentation#oauth2-token

Good instruction how to get APP_KEY, APP_SECRET and refresh token (you will need Postman or curl):
https://www.ibm.com/docs/en/app-connect/containers_cd?topic=type-dropbox-account-details#localconn_dropbox__locatevalues

Encode the <APP_KEY>:<APP_SECRET> (note the inbetween colon) string:
https://www.base64encode.org/

My old long-lived token is valid, I can get access to my Dropbox storage with both methods.

Discussed in https://github.com/koreader/koreader/pull/2424#issuecomment-729377952.
Initial implementation by @Baitinq in https://github.com/koreader/koreader/pull/9131.
Closes https://github.com/koreader/koreader/issues/8571.
Edit: also closes https://github.com/koreader/koreader/issues/8349.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9496)

### CODE REVIEW

**Comment by matthewt03194** [comment]
Sorry in advance for my English!
I'm almost done with this, but at the last step I get stuck on Base64 encode.
Unfortunately, I don't fully understand... I tried using the duck guard symbols, but I also tried without them: in both cases I received a code and entered it in KOReader, but none of them were accepted. It still won't let you connect to Dropbox.

Please help me where I can go wrong. As I wrote, I have the refresh token and everything, but I still can't connect to the folder. Could you make a slightly more detailed description that even such inexperienced can understand like me.
Thank you for helping!

**Comment by matthewt03194** [comment]
> Long-lived tokens are not generated anymore, some old tokens are still valid though.
> 
> Short-lived tokens live 4 hours. To generate new access token you will need the refresh token and <APP_KEY>:<APP_SECRET> string Base64 encoded.
> 
> More on Dropbox changes: https://dropbox.tech/developers/migrating-app-permissions-and-access-tokens
> 
> Dropbox API endpoint to generate access token: https://www.dropbox.com/developers/documentation/http/documentation#oauth2-token
> 
> Good instruction how to get APP_KEY, APP_SECRET and refresh token (you will need Postman or curl): https://www.ibm.com/docs/en/app-connect/containers_cd?topic=type-dropbox-account-details#localconn_dropbox__locatevalues
> 
> Encode the <APP_KEY>:<APP_SECRET> (note the inbetween colon) string: https://www.base64encode.org/
> 
> My old long-lived token is valid, I can get access to my Dropbox storage with both methods.
> 
> 
> 
> 
> 
> 
> 
> Discussed in [#2424 (comment)](https://github.com/koreader/koreader/pull/2424#issuecomment-729377952). Initial implementation by @Baitinq in #9131. Closes #8571. Edit: also closes #8349.
> 
> This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9496)



Sorry in advance for my English!
I'm almost done with this, but at the last step I get stuck on Base64 encode.
Unfortunately, I don't fully understand... I tried using the duck guard symbols, but I also tried without them: in both cases I received a code and entered it in KOReader, but none of them were accepted. It still won't let you connect to Dropbox.

Please help me where I can go wrong. As I wrote, I have the refresh token and everything, but I still can't connect to the folder. Could you make a slightly more detailed description that even such inexperienced can understand like me.
Thank you for helping!

**Comment by hius07** [comment]
Go to https://www.base64encode.org/ and enter the following string into the input window:

your APP_KEY, then the colon sign `:`,  then your APP_SECRET, all without any spaces

then press Encode button. Save the result string.

I would recommend to save your Dropbox cloud storage with dummy strings, then open koreader/settings/cloudstorage.lua in text editor and copy/paste the actual strings to avoid misprints.
Refresh token must be saved to the "password" field, encoded string must be saved to the "address" field.

**Comment by matthewt03194** [comment]
Thank you!! It works!!!!!!
But: I entered dummy things in vain. The address option did not appear in the file, I had to enter that line myself. Why is this? That's probably why it wasn't good when I did it on the reader, because it didn't save the address.

**Comment by hius07** [comment]
> The address option did not appear in the file

Thank you, the bug is fixed.

**Comment by hius07** [comment]
It is ready.

**Comment by mergen3107** [comment]
@matthewt03194 
Is your directory correct? Recently I had a stupid mistake when I had old Kindle’s directory /mnt/us/ instead of /storage/emulated/0/ on Android. (Previously I copied all Kindle settings to Android for KOReader)

**Comment by matthewt03194** [comment]
In my kindle: /mnt/us/Könyvek (in english: Books) I install the koreader today. It doesn't work from the first minute.
In my kobo:  /mnt/onboard/Könyvek (in english: Books)  The download was working a few days ago. It doesn't work today.
What could be the problem? Actually, I don't understand why it doesn't work on kobo, because it's been a few days

**Comment by matthewt03194** [comment]
> @matthewt03194
> Is your directory correct? Recently I had a stupid mistake when I had old Kindle’s directory /mnt/us/ instead of /storage/emulated/0/ on Android. (Previously I copied all Kindle settings to Android for KOReader)

You really had a problem with the library on your kindle. The books are already saved in the folder created in /mnt/base-us.
There was a problem with the book on kobo, I tried to download the incorrect/faulty file.

**Comment by Baitinq** [comment]
Although maybe we should strive to get this basic functionality for this release and then improve the UX for next releases?

**Comment by hius07** [comment]
@matthewt03194, after KOReader update, please reenter your APP_KEY:APP_SECRET string without encoding.

**Comment by matthewt03194** [comment]
> @matthewt03194, after KOReader update, please reenter your APP_KEY:APP_SECRET string without encoding.

Okay, thank you for this information!

**Comment by phamchin** [comment]
> 

I installed [KOReader 2022.10 "Muhara"](https://github.com/koreader/koreader/releases/tag/v2022.10) on my Kobo and stuck at adding Dropbox Cloud storage.
I entered dummy information in the fields and edited by notpad
"password" field = refresh token
"address" field = app_key:app_secret

Should I use UPERCASE of app_key and app_secret?

**Comment by Frenzie** [comment]
If they were in uppercase. The app key stuff is something you can get from the Dropbox website.

**Comment by phamchin** [comment]
> If they were in uppercase. The app key stuff is something you can get from the Dropbox website.
Has “address” field is encoded anymore?

**Comment by hius07** [comment]
> Has “address” field is encoded anymore?

No, just plain key:secret.

**Comment by phamchin** [comment]
> > Has “address” field is encoded anymore?
> 
> No, just plain key:secret.

image
Above is my configuration but I still get notice "Can not fetch list of .. Please check your configuration or network connection"

**Comment by hius07** [comment]
Refresh token (field "password") cannot start with `sl.`.

**Comment by phamchin** [comment]
> Refresh token (field "password") cannot start with `sl.`.

It was generated in OAuth2 dropbox app Settings. After click generate button in Generated access token, I found that string has "sl." included. 
Was I get password a wrong way ?

**Comment by hius07** [comment]
This is your short-lived token, valid for 4 hours only.
You can check it - remove app_key:app_secret from the settings.

Look at the first post to get a link to the instruction how to get the refresh token.

**Comment by phamchin** [comment]
> This is your short-lived token, valid for 4 hours only. You can check it - remove app_key:app_secret from the settings.
> 
> Look at the first post to get a link to the instruction how to get the refresh token.
Hey hius07
I'm following the link in first post "https://www.ibm.com/docs/en/app-connect/containers_cd?topic=type-dropbox-account-details#localconn_dropbox__locatevalues" and using Postman.com to get  refresh token like below pictures
image
After that, I config like below 
image
Is that right way?

**Comment by hius07** [comment]
Looks okay, try to connect.

**Comment by phamchin** [comment]
> Looks okay, try to connect.

Hey hius07, I attempt to connect to dropbox and still get an error
Respond
When long press and see configuration, tried to press Info 
long press
 And surprise It shows my account information correctly
Info
I have no idea now.
Should I del the app dropbox and create a new one from scratch?

**Comment by hius07** [comment]
> Should I del the app dropbox and create a new one from scratch?

No, your credentials are good, you can see account info.

Please check permissions at the Permissions tab of the app console:
https://www.dropbox.com/developers/apps

**Comment by phamchin** [comment]
> > Should I del the app dropbox and create a new one from scratch?
> 
> No, your credentials are good, you can see account info.
> 
> Please check permissions at the Permissions tab of the app console: https://www.dropbox.com/developers/apps

Thank you Hius07
I add more keys to give permission
image
Now I can access my dropbox folder!

**Comment by toanle8816** [comment]
thank you 
it work well

**Comment by zenminimalist** [comment]
I'm I reading and interpreting this correctly that it is now not possible to use Dropbox sync without going through the "rigmarole" of generating and inputting a new token (and doing the whole base64 thing) every 4 hours?

If so, what are the alternatives of syncing folders?

**Comment by hius07** [comment]
You can generate refresh token just once, no base64 encoding required.
Please read the first post.

**Comment by zenminimalist** [comment]
Maybe it's my bad understanding, but if I refresh the token in my DB account, set it all up and then sync all my stuff today. Then tomorrow the token and sync will not be available as the token has expired, no?.

**Comment by hius07** [comment]
You should not "refresh the token", but generate the so called "refresh token".
Refresh tokens do not expire.

**Comment by zenminimalist** [comment]
Thanks for clarifying. 
Am I seeing this correctly that the cloud storage implementation of Dropbox in KOtreader only pulls down files (not folders) and does **not** do a 2-way sync?

**Comment by zenminimalist** [comment]
Will this be implemented in the next version or so? I just seen [this](https://github.com/koreader/koreader/blob/master/frontend/apps/cloudstorage/dropboxapi.lua) here and it seems the Dropbox functionality is being expanded, but I can't judge myself if this included bi-directional sync.

**Comment by nmaupu** [comment]
Hey, I had a hard time figuring this out, here is a gist to make things clearer I hope:
https://gist.github.com/nmaupu/c00c7d4b3f45bdc9e4ddd72d48e269bf

**Comment by hius07** [comment]
Nice, thank you!

**Pull request merged**
