### PR TITLE
PdfDocument: Unbreak highlights

### LINKED ISSUE #7456: Crash when deleting a highlight
* KOReader version: **2021.03**
* Device: **PB632** (PocketBook Touch HD 3), **AppImage**

#### Issue

Every time I delete a highlight, KOReader crashes. It worked fine with 2021.02.

#### Steps to reproduce

* Open EPUB file (haven't tested with other files)
* Highlight some text
* Delete highlight

##### `crash.log` (if applicable)

[crash.log](https://github.com/koreader/koreader/files/6217639/crash.log)

```
03/28/21-18:30:18 INFO  event times are real clock time: no adjustment needed
g_mkdir failed: No such file or directory
./luajit: frontend/document/pdfdocument.lua:198: attempt to call method '_checkIfWritable' (a nil value)
stack traceback:
    frontend/document/pdfdocument.lua:198: in function 'deleteHighlight'
    frontend/apps/reader/modules/readerhighlight.lua:1448: in function 'deleteHighlight'
    frontend/apps/reader/modules/readerhighlight.lua:561: in function 'callback'
    frontend/ui/widget/button.lua:347: in function 'handleEvent'
    frontend/ui/widget/container/inputcontainer.lua:263: in function 'handleEvent'
    frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
    frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
    frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
    frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
    frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
    frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
    ...
    frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
    frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
    frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
    frontend/ui/uimanager.lua:1106: in function 'sendEvent'
    frontend/ui/uimanager.lua:51: in function '__default__'
    frontend/ui/uimanager.lua:1541: in function 'handleInputEvent'
    frontend/ui/uimanager.lua:1609: in function 'handleInput'
    frontend/ui/uimanager.lua:1655: in function 'run'
    ./reader.lua:268: in main chunk
    [C]: at 0x00013f31
Segmentation fault
!!!!
Uh oh, something went awry... (Crash n°1: 03/28/21 @ 18:30:28)
Attempting to restart KOReader . . .
!!!!
```

(This is the log from the PocketBook, the traceback from the AppImage is identical)

### PR DESCRIPTION
**Pull request by NiLuJe**
Regression since #7411
Fix #7456

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7457)

### CODE REVIEW

**Comment by NiLuJe** [comment]
(Not actually tested yet, but this seemed fairly obvious).

**Comment by NiLuJe** [comment]
Err, wait, that's not it.

It's just that the implementation is PDF-specific, but getting called in other engines, too.

**Comment by NiLuJe** [comment]
(dinner break)

**Comment by poire-z** [comment]
I fail to notice a change in `PdfDocument:_checkIfWritable()` - feels like you just moved it around ?
And I also fail to notice what was the issue in #7456 with them being methods vs local, can you explain a bit?

**Comment by Frenzie** [comment]
At a glance I don't really see what's supposed to be different here?

**Comment by NiLuJe** [comment]
That was a brainfart. Don't switch from C to Lua without a break ;p.

(The assumption was a scoping issue, which doesn't make sens,e because this is a class, so everything goes through the __index meta, which defeats lexical scoping issues).

**Comment by NiLuJe** [comment]
Was just a typo: the method was being attached to the super class (Document) instead of the engine class (PdfDocument), and as such stomping on the stub implementation, and being used from other engines, because DocumentRegistry loads *all* the implementations in the FM ;).

**Comment by poire-z** [comment]
OK :) That explains it all.
Do you want to keep all your other changes/moving around ?

**Comment by NiLuJe** [comment]
The move to a module-locale function for one of them *does* require re-ordering because of scoping issue, so, yeah ;).

**Pull request merged**
