### PR TITLE
[plugin] Wallabag: different timeouts for API calls vs file downloads

### PR DESCRIPTION
**Pull request by Frenzie**
Fixes <https://github.com/koreader/koreader/issues/7650>.

@mredaelli @matejdro Could you please verify this works around the issue for you?

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7668)

### CODE REVIEW

**Review by NiLuJe — APPROVED** [review]

**Comment by mredaelli** [comment]
Not really (or not entirely: I got 3 more items, which I'm not sure if they are new or old but failed; but still 10 failed).

Trying to get the epub for this: https://acoup.blog/2019/07/12/collections-the-lonely-city-part-i-the-ideal-city/

which seems to take about 15 seconds if done manually in the browser:

image

it still fails (and an empty file is still created).

Can I turn debug logging on to see what is actually failing?

**Comment by Frenzie** [comment]
Debug logging can be enabled in the file browser top menu → tools → more tools → developer options.

Generating that 2.9 MB EPUB takes about 6-7 seconds for me.

```
05/12/21-20:40:36 DEBUG Wallabag: processing article ID:  2389925
05/12/21-20:40:36 DEBUG Wallabag: DOWNLOAD: id:  2389925
05/12/21-20:40:36 DEBUG Wallabag: DOWNLOAD: title:  Collections: The Lonely City, Part I: The Ideal City
05/12/21-20:40:36 DEBUG Wallabag: DOWNLOAD: filename:  /home/frans/src/kobo/koreader/test/wallabag/[w-id_2389925] Collections: The Lonely City, Part I: The Ideal City.epub
05/12/21-20:40:36 DEBUG Wallabag: URL      https://framabag.org/api/entries/2389925/export.epub
05/12/21-20:40:36 DEBUG Wallabag: method   GET
05/12/21-20:40:43 DEBUG Wallabag: file downloaded to /home/frans/src/kobo/koreader/test/wallabag/[w-id_2389925] Collections: The Lonely City, Part I: The Ideal City.epub
```

More than 15 seconds probably still triggers the larger block timeout. That should show up in the debug logs, but you can also test it by replacing that `socketutil.FILE_BLOCK_TIMEOUT` with a larger value like 20 or 30.

**Comment by mredaelli** [comment]
All I get is
```
05/12/21-22:02:17 DEBUG Wallabag: processing article ID:  12
05/12/21-22:02:17 DEBUG Wallabag: DOWNLOAD: id:  12
05/12/21-22:02:17 DEBUG Wallabag: DOWNLOAD: title:  Collections: The Lonely City, Part I: The Ideal City
05/12/21-22:02:17 DEBUG Wallabag: DOWNLOAD: filename:  /mnt/onboard/_Walla/[w-id_12] Collections_ The Lonely City_ Part I_ The Ideal City.epub
05/12/21-22:02:17 DEBUG Wallabag: URL      https://walla.typish.io/api/entries/12/export.epub
05/12/21-22:02:17 DEBUG Wallabag: method   GET
05/12/21-22:02:32 DEBUG Wallabag: Server error:  wantread
05/12/21-22:02:32 DEBUG Wallabag: processing article ID:  11
```

So it was a server problem. I went to the logs, and indeed there was a php timeout.

So I increased that, and now in the nginx log I see a 499 errors for the epub request by Koreader. So let's see the Koreader log again.

Hmm no. Same error, `Server error:  wantread`.

So I tried putting a hardcoded `120` in the timeouts, but still no luck.

Now I wonder... this is the nginx log:
```
46.126.41.64 - - [12/May/2021:22:41:29 +0200] "POST /oauth/v2/token HTTP/1.1" 200 275 "-" "KOReader/2021.04 (https://koreader.rocks/) LuaSocket/3.0-rc1"
46.126.41.64 - - [12/May/2021:22:41:29 +0200] "GET /api/entries.json?archive=0&page=1&perPage=30 HTTP/1.1" 200 1549414 "-" "KOReader/2021.04 (https://koreader.rocks/) LuaSocket/3.0-rc1"
46.126.41.64 - - [12/May/2021:22:41:30 +0200] "GET /api/entries.json?archive=0&page=2&perPage=30 HTTP/1.1" 404 56 "-" "KOReader/2021.04 (https://koreader.rocks/) LuaSocket/3.0-rc1"
46.126.41.64 - - [12/May/2021:22:41:45 +0200] "GET /api/entries/12/export.epub HTTP/1.1" 499 0 "-" "KOReader/2021.04 (https://koreader.rocks/) LuaSocket/3.0-rc1"
```

I was assuming the 404 in the pagination was not a problem, but... maybe it is? The successive request starts 15 seconds later, so maybe at that point php crashed or something due to that request, and that's the reason for the 499?

BTW, I tried setting the fetch size to 60, which is larger than the total amount of entries in my server, but that doesn't fix it (it still looks for page two :/ )

**Comment by Frenzie** [comment]
> BTW, I tried setting the fetch size to 60, which is larger than the total amount of entries in my server, but that doesn't fix it (it still looks for page two :/ )

That's the only way to know there's nothing left.

**Comment by Frenzie** [comment]
> So I tried putting a hardcoded 120 in the timeouts, but still no luck.

I'm seeing 15 seconds in your log. Did you restart the program?

**Comment by mredaelli** [comment]
I think so... I also introduced an error in one try, and the menu entry disappeared, so I'm assuming it's being picked up :)

**Comment by mredaelli** [comment]
Now I replaced that code with
```
 if page > 1 then 
     break
 end 
```
and it works.

This is, it is still doing *two* pagination requests. Can it be it picks up the second to last version of the file ^_^ ?

**Comment by Frenzie** [comment]
Sorry, the second to last version of what file?

**Comment by Frenzie** [comment]
Oh, the main.lua. :-P

**Comment by mredaelli** [comment]
yep. I'm happy (it works) but confused (no idea why).

Let me reboot ^_^

**Comment by Frenzie** [comment]
That particular break is after the callAPI().

You'd have to put the break before this line (or comment out the while altogether).
https://github.com/koreader/koreader/blob/a20cac6904955516d7f1352306bee52c80f3d79c/plugins/wallabag.koplugin/main.lua#L416

**Comment by mredaelli** [comment]
Of course, sorry :(

So anyway, let me try to go back to your MR once more and see if it works after plenty reloading and possibly rebooting

**Comment by Frenzie** [comment]
Your browser screenshot above suggests it's skirting around 15 seconds. Simply doing it in 14.5 seconds one time might've sufficed to avoid a timeout… however, if you put in a higher value that shouldn't matter either way, that's the weird part.

**Comment by mredaelli** [comment]
I tried with multiple ones and they all either failed or worked, so it shouldn't be a threshold problem.

So anyway, here it works only with:
```
    if filepath ~= "" then
        request.sink = ltn12.sink.file(io.open(filepath, "w"))
        socketutil:set_timeout(120, 120)
    else
        request.sink = ltn12.sink.table(sink)
        socketutil:set_timeout(120, 120)
    end
```
In **both** file and network.

My todo:
- read up on the meaning of those two parameters
- maybe add a break to the loop in case pagination returns less than `self.articles_per_sync` (should save an extra request most of the time, right?)
- find out why that 404

**Comment by Frenzie** [comment]
> maybe add a break to the loop in case pagination returns less than self.articles_per_sync (should save an extra request most of the time, right?)

You mean like this? ;-) (And yes, it works.)

https://github.com/koreader/koreader/blob/a20cac6904955516d7f1352306bee52c80f3d79c/plugins/wallabag.koplugin/main.lua#L436-L439

**Comment by Frenzie** [comment]
Sorry, misread. But no, you don't know what pagination is.

**Comment by mredaelli** [comment]
> Edit: sorry, misread slightly. But just because you ask for a perPage doesn't mean the server will give it to you, does it?

Not sure I follow. I'm saying that if it doesn't, it means there are not enough, so it means we don't need to ask yet more.

**Comment by Frenzie** [comment]
If you ask for 30 and the server gives 20, you don't know if it's giving you 20 because that's all it has or because it's all it wants to give you at once.

**Comment by Frenzie** [comment]
Like this:
https://github.com/wallabag/wallabag/blob/691746e8d96bf2d668cb62f254898aa7afbd6243/src/Wallabag/UserBundle/Controller/ManageController.php#L155

**Comment by mredaelli** [comment]
I am not entirely sure that path is used for the REST api (see [here](https://github.com/wallabag/wallabag/search?q=setMaxPerPage), and in any case, if it's [not documented](https://app.wallabag.it/api/doc#get--api-entries.{_format}) that there's a hard limit at 50, IMHO that's a bug :P ), but in any case turns out the point is moot, because the API [returns the total](https://doc.wallabag.org/en/developer/api/methods.html), so that would probably be the best way to do it.

**Comment by Frenzie** [comment]
I was talking about the principle, not being specific.

> the API returns the total

That must be new.

**Comment by Frenzie** [comment]
But let me put it another way: if I give someone access that doesn't mean I want them to call 5000 per page on my server

**Comment by mredaelli** [comment]
That was a nice dive into sockets and Lua :)

So, yeah, seems like the 15s block for files is still too small for Wallabag. Pending their fixing that issue I linked, my preference would be a `defaults.lua` in the plugin directory, affecting only the plugin and `require`d only if existing (or however that's done in Lua) and otherwise defaulting to the current values, so that it's stable between upgrades (actually I never upgraded yet, so I'm not sure if a file in that folder would be kept :) ).

But not a problem for me to just patch it every time.

Either way, should we add something about this in the wiki?

What I would suggest (should I make separate tickets?) though:
- if the download failed, I get an empty file, which is good so I know which one failed. But I'd suggest that on the next sync it should try it again. Right now I have to delete it manually.
- that 404 pagination problem on the second page - I wonder if it's a wallabag installation problem on my part, or expected behaviour when asking for a non-existing page, ans thus would be fixed by using the `total`.

**Comment by matejdro** [comment]
It is weird that there is a server timeout error on kobo, but browser downloading works fine. Maybe kobo sends something different?

**Comment by Frenzie** [comment]
@mredaelli 
NB Here's the reason why: `https://github.com/wallabag/wallabag/pull/3096` It wasn't overlooked; it was unusable.

@matejdro 
Browsers use a longer timeout (something like 90 s by default) while they don't block the UI. That's not easily changed.

**Comment by matejdro** [comment]
Okay maybe I misunderstood. As "server timeout" you don't mean timeout caused by server, right? Because browser/koreader timeout has nothing to do with the server.

**Comment by Frenzie** [comment]
I'm not sure what you're referring to. I think @mredaelli may have said something about his server timing out? By default PHP has a maximum execution time of 30 seconds if I'm not mistaken.

**Comment by matejdro** [comment]
What I'm saying is that if browser works, then issue cannot be on the PHP side.

**Comment by Frenzie** [comment]
I'm just not sure what you're responding to. :-) Anyway, merging this one for the moment.

**Comment by poire-z** [comment]
(Unrelated, but CI on the main https://github.com/koreader/koreader/commits/master?after=341d6ac660e590a129ae3e8681167aa1dae0075a+34&branch=master fails in the "Docs and coverage" part since ~ Apr 22.
Similar issues in the past: https://github.com/koreader/koreader/issues?q=%22Failed+to+generate+documents%22
Can't figure out what causes this.

**Comment by Frenzie** [comment]
It's a security issue I haven't gotten around to tackling, apologies.

**Comment by Frenzie** [comment]
Oh never mind, what you linked is something else still. If it *did* succeed there, then... etc. >_>

**Comment by Frenzie** [comment]
@poire-z That's because when CircleCI doesn't run properly on a PR we tend to miss its absence. (At least I hope people don't normally merge when CircleCI gives a big fat red X. ;-) )

**Comment by poire-z** [comment]
What's the rule ? A file can't start with:
`-- plugin for saving a cover image to a file and scale it to fit the screen`
?
It needs either no comment (directly some code), or some comment with:
`--[[--`
or really much more like:
```
--[[--
@module koplugin.wallabag
```
?

**Comment by Frenzie** [comment]
Multiline vs single-line comment makes no difference. The issue is indeed that you're giving a module description where it can't be auto-derived because it's outside of `frontend`.

Some (slightly unclear) docs here: http://stevedonovan.github.io/ldoc/manual/doc.md.html#Module_Tags

**Pull request merged**
