### PR TITLE
Fix unit tests after crengine update

### PR DESCRIPTION
**Pull request by poire-z**
Fix unit tests failures after https://github.com/koreader/koreader/pull/3992.
See https://github.com/koreader/koreader/pull/3992#issuecomment-394071949

Hopefully related only to getting rid of some blank pages, thanks to https://github.com/koreader/crengine/pull/201 (already bumped into koreader).

### CODE REVIEW

**Comment by Frenzie** [comment]
Not just that, I suppose. /whistles

**Comment by NiLuJe** [comment]
Yeah, that was also my gut feeling when interpreting the output of the tests without being familiar neither with the tests nor with the code in question ;o).

**Comment by Frenzie** [comment]
@poire-z Is that part of libc? If so you might be able to grab it from one of the Debian packages: https://packages.debian.org/wheezy/libc6 (they're just zip files)

Dunno if that helps, but that's how I tend to get my ARM binaries like evtest.

**Comment by poire-z** [comment]
I just tried the one from https://packages.debian.org/stretch/libc6-armhf-cross, but I get:
```
ERROR: ld.so: object '/mnt/onboard/.adds/misc/libSegFault.so' from LD_PRELOAD cannot be preloaded: ignored.
```
(even if I put it into /tmp/)

**Comment by Frenzie** [comment]
Stretch is the newest and likely too recent; that's why I linked to the oldest. ;-)

(Probably won't help here, but I'd say it's worth a quick try.)

**Comment by NiLuJe** [comment]
I don't ship it because it's indeed an user-facing bit of glibc, and I'm assuming this is sane on the target system ;p.

But it's still there in my TC's sysroot, so, [here you go](http://files.ak-team.com/niluje/mrpub/Kobo/catchsegv-kobo-glibc-2.15.tar.gz) ;).

Out of curiosity, what's the difference between using catchsegv instead of gdb? (Because I do ship a full gdb install ;p).

**Comment by poire-z** [comment]
@Frenzie : oups, sorry, didnt even see your link - no error with the wheezy one, but still no backtrace.

@NiLuJe : thanks, gonna try it (the difference between catchsegv and gdb is: catchsegv is simple, and I don't know how to use gdb, and I don't want to learn :)

**Comment by poire-z** [comment]
@NiLuJe : working, but still no backtrace, even after a reboot :| And no backtrace either in /tmp/segv_output.Veyb5u if I exit before the addr2line stuff.

**Comment by NiLuJe** [comment]
@poire-z : I've never used it, so I can't begin to understand what might be going wrong ;).

I do have experience running KOReader under gdb, though... :D.

**Comment by poire-z** [comment]
Thanks for the quick tutorial :)
gdb didn't give me a full backtrace, but it pointed to the function where it happens:
```
Program received signal SIGSEGV, Segmentation fault.
0x2d28e3cc in LVFormatter::processParagraph(int, int) ()
   from /mnt/onboard/.adds/koreader/./libs/libcrengine.so
(gdb) bt full
#0  0x2d28e3cc in LVFormatter::processParagraph(int, int) ()
   from /mnt/onboard/.adds/koreader/./libs/libcrengine.so
No symbol table info available.
#1  0x0000000c in ?? ()
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) backtrace
#0  0x2d28e3cc in LVFormatter::processParagraph(int, int) ()
   from /mnt/onboard/.adds/koreader/./libs/libcrengine.so
#1  0x0000000c in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) c
Continuing.

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
(gdb) q
```
That's the complex lvtextfm.cpp ... will see if there's something non determistic involved in that function.
(I'll see at building again koreader for kobo (did that once last year) if needed - will let you know if I don't manage, thanks :)

**Comment by poire-z** [comment]
OK, with a debug build, I get more information:
```
Program received signal SIGSEGV, Segmentation fault.
LVFormatter::getAdditionalCharWidth (maxpos=<optimized out>,
    pos=<optimized out>, this=0x7effed78)
    at koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvtextfm.cpp:486
486     koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvtextfm.cpp: No such file or directory.
(gdb) bt
#0  LVFormatter::getAdditionalCharWidth (maxpos=<optimized out>,
    pos=<optimized out>, this=0x7effed78)
    at koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvtextfm.cpp:486
#1  LVFormatter::processParagraph (this=0x7effed78, start=0,
    end=<optimized out>)
    at koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvtextfm.cpp:1212
#2  0x2d2181f0 in LVFormatter::splitParagraphs (this=0x7effed78)
    at koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvtextfm.cpp:1239
#3  LVFormatter::format (this=0x7effed78)
    at koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvtextfm.cpp:1267
#4  LFormattedText::Format (this=<optimized out>, width=width@entry=963,
    page_height=page_height@entry=1363)
    at koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvtextfm.cpp:1302
#5  0x2d18eb04 in ldomNode::renderFinalBlock (this=this@entry=0x3b4b78,
    frmtext=..., fmt=fmt@entry=0x7effeeb8, width=963)
    at koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvtinydom.cpp:11753
#6  0x2d2202e2 in DrawDocument (drawbuf=..., enode=0x3b4b78, x0=x0@entry=36,
---Type <return> to continue, or q <return> to quit---
    y0=y0@entry=36, dx=dx@entry=1000, dy=dy@entry=1358,
    doc_x=<optimized out>, doc_x@entry=0, doc_y=82, doc_y@entry=-451,
    page_height=page_height@entry=1448, marks=marks@entry=0x37c1e4,
    bookmarks=bookmarks@entry=0x37c1f0)
    at koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvrend.cpp:2777
#7  0x2d220248 in DrawDocument (drawbuf=..., enode=0x3b4940, x0=x0@entry=36,
    y0=y0@entry=36, dx=dx@entry=1000, dy=dy@entry=1358,
    doc_x=<optimized out>, doc_x@entry=0, doc_y=-451, doc_y@entry=-42982,
    page_height=page_height@entry=1448, marks=marks@entry=0x37c1e4,
    bookmarks=bookmarks@entry=0x37c1f0)
    at koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvrend.cpp:2726
#8  0x2d220248 in DrawDocument (drawbuf=..., enode=0x3c5248, x0=x0@entry=36,
    y0=y0@entry=36, dx=dx@entry=1000, dy=dy@entry=1358,
    doc_x=<optimized out>, doc_x@entry=0, doc_y=-42982, doc_y@entry=-43321,
    page_height=page_height@entry=1448, marks=marks@entry=0x37c1e4,
    bookmarks=bookmarks@entry=0x37c1f0)
    at koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvrend.cpp:2726
#9  0x2d220248 in DrawDocument (drawbuf=..., enode=0x3c5210, x0=x0@entry=36,
    y0=y0@entry=36, dx=dx@entry=1000, dy=dy@entry=1358,
    doc_x=<optimized out>, doc_x@entry=0, doc_y=doc_y@entry=-43321,
---Type <return> to continue, or q <return> to quit---q
page_heightQuit
(gdb) bt full
#0  LVFormatter::getAdditionalCharWidth (maxpos=<optimized out>,
    pos=<optimized out>, this=0x7effed78)
    at koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvtextfm.cpp:486
        font = 0x707f506
        glyph = {blackBoxX = 123 '{', blackBoxY = 0 '\000',
          originX = 0 '\000', originY = 0 '\000', width = 12 '\f'}
        delta = <optimized out>
        font = <optimized out>
        glyph = <optimized out>
        delta = <optimized out>
#1  LVFormatter::processParagraph (this=0x7effed78, start=0,
    end=<optimized out>)
    at koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvtextfm.cpp:1212
        lastNormalWrap = <optimized out>
        lastMandatoryWrap = <optimized out>
        normalWrapWidth = <optimized out>
        wrapPos = 164
        lastnonspace = <optimized out>
        spaceReduceWidth = <optimized out>
        wordpos = <optimized out>
        unusedPercent = <optimized out>
---Type <return> to continue, or q <return> to quit---
        needReduceSpace = <optimized out>
        endp = 165
        downSkipCount = <optimized out>
        upSkipCount = <optimized out>
        dw = <optimized out>
        x = <optimized out>
        w0 = 2588
        lastDeprecatedWrap = <optimized out>
        lastHyphWrap = <optimized out>
        i = <optimized out>
        firstCharMargin = 0
        deprecatedWrapWidth = <optimized out>
        unusedSpace = <optimized out>
        para = 0x345b78
        i = <optimized out>
        preFormattedOnly = <optimized out>
        lfFound = <optimized out>
        interval = 16
        maxWidth = 963
        visualAlignmentEnabled = false
        visualAlignmentWidth = <optimized out>
        pos = 162
        upSkipPos = -1
---Type <return> to continue, or q <return> to quit---
        indent = 0
#2  0x2d2181f0 in LVFormatter::splitParagraphs (this=0x7effed78)
    at koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvtextfm.cpp:1239
        start = <optimized out>
        i = 13
        prevRunIn = <optimized out>
        start = <optimized out>
        i = <optimized out>
        prevRunIn = <optimized out>
#3  LVFormatter::format (this=0x7effed78)
```
https://github.com/koreader/crengine/blob/e626ba86731384a7fd17fb828f546d7c56a542eb/crengine/src/lvtextfm.cpp#L486

I guess that's a font slot mis-initialized that points to something that's not a font.

**Comment by poire-z** [comment]
OK, I may become friend with gdb :) thanks for making all these binaries available.
Fixed my crash in https://github.com/koreader/crengine/pull/202 (more of a workaround than a real fix thus).

**Comment by NiLuJe** [comment]
Happy to help ;).

**Pull request merged**
