### PR TITLE
Implement Dictionary plugin

### PR DESCRIPTION
**Pull request by Hzj-jie**
So we can look up dictionaries without opening a book.

### CODE REVIEW

**Comment by houqp** [comment]
Is this for dictionary lookup in filemanager?

**Comment by retrue** [comment]
Thanks. This is a feature I was going to request. I have studied languages and this is very handy because it turns the device into a dictionary without needing to open a book first. Paper dictionaries are bulky and expensive.
Will be the same feature added for the Wikipedia too?

**Comment by Hzj-jie** [comment]
Yes.
For Wikipedia, I believe it also can be achieved by a simple wrapper like this.

**Comment by houqp** [comment]
Can we either move readerdictionary itself into a plugin or implement similar module within filemanager? It feels a little bit hacky to have it loaded as a regular module for reader but a plugin for filemanager. Ideally, it should be one module shared by both apps.

**Comment by Hzj-jie** [comment]
I am happy to do so. IMO, a module should be better, considering it highly couples with reader. I cannot quite tell how should a module be involved by file manager, I really do not like to copy and paste the logic. But a plugin is more like an optional component. Though we won't crash, highlighting words won't take any effect without dictionary, which is a broken user experience.
That's indeed the reason I chose this hack solution, a simple wrapper of dictionary module as a plugin.

Do you happen to have any suggestion?

Also, I think plugins can be used not only in reader and file manager, but also other apps, say OPDS catelog, as long as they also load plugins.

**Comment by houqp** [comment]
I totally understand why you ended up with this solution :) The code for readerdictionary was not designed as a standalone module that can be shared by multiple components from the beginning, which is not your fault at all.

Depends on how much effort you want to put into this, I think we can do this in 3 steps:

1. Just reuse readerdictionary for now in filemanager and potentially other components. It can be done with only two lines of LUA:

```lua
local ReaderDictionary = require("apps/reader/modules/readerdictionary")

function FileManager:init()
    -- ...
    table.insert(self, ReaderDictionary:new{ ui = self.ui })
    -- ...
end
```

2. Move readerdictonary out of reader into its own app. This requires changing the require path for dictionary in reader and filemanager. It also means readerdictonary will be turned into a thin sub class for the new dictionary app which does extra setting handling for doc_settings.

3. Turn dictionary app into a plugin. This requires minor tweaks in readerhighlight so the plugin can add the "Dictionary" button in the highlight modal at runtime.

I am cool with us just do the first step for now.

> Also, I think plugins can be used not only in reader and file manager, but also other apps, say OPDS catelog, as long as they also load plugins.

Agree, if we will have more apps in the future, plugin is probably the right way to go. For now, I would prefer at least manually and explicitly add the dictionary module in each app's `init` method. Adding a magic flag `exclusive_in_reader` seems a bit over kill at this point. Implicit code is harder to follow so I suggest we only do this when it can reduce a non-trivia amount of duplicate code.

**Comment by Hzj-jie** [comment]
Sounds good. I will work on the first solution, and then the second improvement.

**Comment by houqp** [comment]
Looks good to me, l am happy to merge this in its current state. Do you still want to move dictionary into its own app?

**Comment by Hzj-jie** [comment]
No, I prefer to do it in a separated change. I am trying to trigger the checks.

**Comment by Hzj-jie** [comment]
CMake Error at zlib-stamp/download-zlib.cmake:27 (message):
  error: downloading 'http://zlib.net/zlib-1.2.8.tar.gz' failed

zlib has been upgraded to 1.2.9.

**Comment by houqp** [comment]
I have fixed the build error. You can restart the build from travis UI directly, there is a restart button at the top right corner.

**Pull request merged**
