### PR TITLE
android: fix dict overrides

### PR DESCRIPTION
**Pull request by pazos**
Fix for https://www.mobileread.com/forums/showpost.php?p=4058592&postcount=1

- User overrides marked as `false` were not checked
- Actions without app were skipped.

It seems that I forgot to check app picker settings :P

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/6887)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by norbi24** [comment]
Hi guys, wouldn't it make sense along with this change to add thise generic dict lines to the dicts array in device.lua like this:
dicts = {
    { "Aard2", "Aard2", false, "itkach.aard2", "aard2" },
    ...
    { "QuickDic", "QuickDic", false, "de.reimardoeffinger.quickdic", "quickdic" },

    { "Send", "Choose Dict by App picker (send action)", true, nil, "send" },
    { "Search", "Choose Dict by App picker (search action)", true, nil, "search" },
    { "Text", "Choose Dict by App picker (text action)", true, nil, "text" }, 
}

so that everyone could use his own dictionary app which he has installed on Android ?
Yes I know this behaves in a little different from pre-configured dict apps, but I think everyone who would select one of this
generic options, would then immediately see how it works ...

**Comment by pazos** [comment]
@norbi24: Actually we cannot enforce `Choose Dict by App picker` inside the app. The intent will be handled by the system and the app picker will be shown only if the user didn't set a default for a given action.

It can be implemented within the program, somehow like CC is doing for each filetype, but I think the current implementation works fine. Anyhow the building blocks are there, so PR welcome against https://github.com/koreader/android-luajit-launcher.

And probably the nº of users that use 3rd party dicts outside defaults can be counted with the fingers of one hand :smile:

**Comment by norbi24** [comment]
Thanks for the explanation, understood, but I assume that I will still be able to add those generic picker lines into my override
dictionaries.lua, right ?
And yes,  originally I thought this could be a breaking feature making usage of good dictionaries from known editorials possible,
but it really looks that no one needs this ...

**Comment by pazos** [comment]
> I assume that I will still be able to add those generic picker lines into my override dictionaries.lua, right ?

Of course. That's the point. **Made for power users** :tm:

**Pull request merged**
