### PR TITLE
vocabbuilder.koplugin: allow manually adding new words

### PR DESCRIPTION
**Pull request by weijiuqiao**
This PR makes the following changes:
- allowing users to opt to add words manually to the vocabulary builder per #9486
- due time for review will be based on the streak count of GOT IT's than review count
- minor update of the zh_keyboard character deletion logic

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9582)

### CODE REVIEW

**Comment by poire-z** [comment]
Best to not mix zh keyboard and vocab builder updates.
Either another PR, or rebase the commits of this PR (when it's ready) to make 2 individual commits, that we can merge as-is.

**Comment by weijiuqiao** [comment]
Checked a couple times, shouldn't need more change. Squashed commits to 2 ones.

**Comment by poire-z** [comment]
May be prefix the commit titles with what they are about:
```
Chinese keyboard: ...
Vocabulary builder: ...
```
so our grandchildren looking at git log won't have to guess :)

**Comment by weijiuqiao** [comment]
Done. Lucky grandchildren ;)

**Pull request merged**
