### PR TITLE
Legacy Kindle: Actually handle (system) power events

### LINKED ISSUE #7333: Kindle Keyboard 3G US - No screensaver on sleep
* KOReader version: 2021.02
* Device: Kindle Keyboard 3G US

#### Issue
I'm not sure if it's supposed to, but when I flip the switch to sleep the device while koreader is open, there is zero indication that the device is asleep. I can tell that it *is* asleep because none of the buttons work until I hit the switch again, but I would've expected some indication of sleep to happen. I've tried checking every option under Screen->Screensaver to no avail.
#### Steps to reproduce
Freshly install KOReader, start it from KUAL, sleep the device with the switch. Expect to see indication that sleep is enabled, but nothing comes.

### PR DESCRIPTION
**Pull request by NiLuJe**
Otherwise, ScreenSaver handling doesn't work, duh'.
I have no idea how I managed to get that working the last time I tested
it :?.
Possibly I tested the final code on a K4 and not a K3?

Fix #7333

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7336)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
There's no doubling with the fakes?

**Comment by NiLuJe** [comment]
@Frenzie: What ado you mean, exactly?

**Comment by Frenzie** [comment]
I mean that on my phone I missed that this only applies to three specific devices, so I was in effect wondering if on a PW2 or something you wouldn't get both "real" and "fake" events.

**Comment by NiLuJe** [comment]
Oh, FWIW, the effect is fairly similar to other platforms, only the implementation differs: it just generates custom input events for Charging/Discharging/PowerPress/PowerRelease events, so we effectively *always* want it ;).

**Pull request merged**
