### PR TITLE
Kobo: Unbreak automagic_sysfs on the Libra 2

### PR DESCRIPTION
**Pull request by NiLuJe**
Regression since #9902, because I'd forgotten that the default Kobo block *does* set those...

Reported by @ptrm on Gitter, thanks!

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9998)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Wait, that doesn't work, forgot that this is a real class with inheritance. Argh.

**Comment by NiLuJe** [comment]
There, learned my lesson: don't try to be cute ;p.

**Comment by ptrm** [comment]
Checked the new `frontend/device/kobo/device.lua` with `v2022.11-77-gb3a7d32d_2023-01-05` on Libra 2, and Clara 2e just in case, and it works, thanks :)
Libra 2 battery level


As a side note, which is probably something different, Libra 2 in USBMS mode was showing battery level correctly all the time, while Clara 2e shows it's at 0% (though 2e wasn't affected by the `kobo/device.lua` bug):
2e usbms

**Comment by NiLuJe** [comment]
@ptrm: Yup, I'd forgotten the Clara 2E bits in the USBMS tool ;o).

**Pull request merged**
