### PR TITLE
Calibre: Allow authors/title metadata browse/searches

### PR DESCRIPTION
**Pull request by NiLuJe**
c.f., https://www.mobileread.com/forums/showthread.php?t=352142

This adds dedicated "browse by" buttons for authors & tags, and adds series & tags to the search settings for the meta "Search books" button.

---

This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10113)

### CODE REVIEW

**Comment by NiLuJe** [comment]
csearch

**Comment by NiLuJe** [comment]
Writing the above, I'll see how annoying it would be to add the missing options to the generic find to allow searching series or tags there...

**Comment by NiLuJe** [comment]
> might be trivial,

Yup, done ;p.

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/10113)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NiLuJe)

**Review by pazos — APPROVED** [review]
LGTM!

@NiLuJe: previous actions have paired shortcuts in dispatcher, handled by [these events](https://github.com/koreader/koreader/blob/master/plugins/calibre.koplugin/main.lua#L28-L43)

I don't know if you want the new search actions to have them too.

**Comment by NiLuJe** [comment]
Oh, good point!

**Pull request merged**
