### PR TITLE
Extend frontlight widget

### PR DESCRIPTION
**Pull request by dengste**
frontlightwidget: Add widgets for changing 'warmth' where available

This is to further improve natural light support on the Kobo Aura One (see #2285).

### CODE REVIEW

**Comment by dengste** [comment]
Screenshot:

frontlightwidget_warmth

**Comment by Frenzie** [comment]
Thanks!

**Comment by gerhaher** [comment]
Toggle?

**Comment by Frenzie** [comment]
True, it could make sense to have some kind of toggle between "custom" and "default" warmth as an addition. Or just a reset/default?

**Comment by dengste** [comment]
I did not implement 'toggle' because I didn't think it makes much sense. Note that for 'brightness', the 'min' button will set brightness to '1', whereas 'toggle' will set it to '0', turning the frontlight completely off. This makes sense, because when you are actually reading in the dark, you don't want 'min' to turn off the light completely. So the 'toggle' button is actually meant to be "toggle between on/off", not so much between previous/current value. For 'warmth' however, I think that this distinction between '0' and '1' doesn't make sense, so 'min' will take you directly to '0'.
Of course, it's not like I'm dead set against having 'toggle' for warmth. If people find it useful, I can add that. I would however like to keep the behavior that 'min' takes you directly to '0'.

**Comment by Frenzie** [comment]
I wrote that based on the assumption that 0 is "calibrated" overly blue, much like Sony phones. I say that primarily due to the regular frontlight on my H2O. I suppose the idea is to make the slightly grayish E Ink look whiter, except especially in the dark when you might be using the frontlight in the first place that's not exactly desirable. It's the ereader's equivalent of Samsung's Look How the Colors Pop in the Store™ oversaturation.

Judging by this video it's not much different for the One, except that you can achieve a more properly neutral color with a slight warmth https://youtu.be/w8_2FP3J3cI?t=20s

Based on that reasoning the warmth reset or toggle would go to a default somewhere between 10 and 30. Preferably measured, but since that's hard without special equipment you can also eye it next to a factory-calibrated monitor or phone.

Mind you, I haven't seen one in real life. But I hope that explains why the general idea makes sense to me. ;-)

**Comment by dengste** [comment]
I doubt the KA1 hardware is good enough to guarantee consistent light for a certain warmth value across different devices.  In fact, I think my KA1 is way more "orange" for maximum warmth than the one seen in the video (though that may be a recording issue). So I think that 'toggle' should be a toggle between "no warmth" and the current value. Toggling to some value like '15' would only confuse people, IMHO.

**Comment by Frenzie** [comment]
> I doubt the KA1 hardware is good enough to guarantee consistent light for a certain warmth value across different devices.

I think it's reasonably safe to assume they're all too blue. If so then `10` (to be safe) or `15` (your suggestion) is arguably a much better default.

> Toggling to some value like '15' would only confuse people, IMHO.

Perhaps, but no one said it should be *called* `15`. ;-) Or <kbd>Toggle</kbd> for that matter. I already explicitly mentioned <kbd>Default</kbd>, or one could combine those suggestions into <kbd>Toggle default</kbd>. With a long press on default to set it to the current value, for example. Or even two: `default` and `vivid` (because the maximum you'd realistically want to use on a regular basis is likely nowhere in the vicinity of 100). But that aside. You just write whatever you want to write. :-)

(I suspect you still want to create some kind of f.lux-style auto-curve since you said "see this issue" in the OP, not "fixes"?)

**Pull request merged**
