### PR TITLE
Add Russian Wiktionary dictionary

### PR DESCRIPTION
**Pull request by Vuizur**
This adds a Russian-Russian dictionary that I created, extracted from Wiktionary.

The download/lua code is untested, so if someone would want to test it I have a random public domain Russian ebook:
[Гавриилиада_(Пушкин).zip](https://github.com/koreader/koreader/files/9568714/_.zip)

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9517)

### CODE REVIEW

**Comment by NiLuJe** [comment]
How does this differ from https://github.com/BoboTiG/ebook-reader-dict?

(We currently don't bundle any of those, BTW, so I would possibly suggest directing your efforts over there ;)).

**Comment by Frenzie** [comment]
> (We currently don't offer any of those, BTW, so I would possibly suggest directing your efforts over there ;)).

Oh yeah, those releases could easily be added to the list.

**Comment by Vuizur** [comment]
> How does this differ from https://github.com/BoboTiG/ebook-reader-dict?
> 
> (We currently don't offer any of those, BTW, so I would possibly suggest directing your efforts over there ;)).

Mine works by parsing the entire 40 GB HTML dump, I think the ebook-reader-dict project parses the XML dumps - which is faster, but that way you cannot get all inflections that are available in the HTML (because you have to rely on (not exhaustive) redirects and cannot access the inflection tables directly because those are dynamically generated). I think the approaches are too different to fuse together.

In general I think it is a good idea to integrate various Wiktionary-dictionaries: The BoboTiG repo has good monolingual dictionaries, [Wikidic-gen](https://github.com/karlb/wikdict-gen) has good dictionaries with exotic language pairings built on the DBnary Wiktionary parser, and my repo [Wiktionary-Dictionaries ](https://github.com/Vuizur/Wiktionary-Dictionaries), built on the Wiktextract parser data, has dictionaries in 40 or so languages with English definitions and pretty good inflection support. For my repo it is also on my TODO-List to open a pull request.

**Comment by Frenzie** [comment]
40 GB down to a mere 40 MB? Impressive difference. :-)

**Pull request merged**
