### PR TITLE
"Page turns" menu development

### PR DESCRIPTION
**Pull request by hius07**
List of changes:
1. `Taps and gestures` - `Page turns` menu is available in reader only.
2. `Invert page turn taps and swipes` submenu item moved here from Navigation.
The duplicated code in readerpaging.lua and readerrolling.lua removed from both.
3. Added standard "star" for default RTL.
4. `Invert page turn buttons` submenu item moved here from Navigation.

<kbd></kbd>

<kbd></kbd>

<kbd></kbd>

<kbd></kbd>

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8022)

### CODE REVIEW

**Comment by poire-z** [comment]
You made `Active menu > [ ] Taps / [ ] Swipes` yesterday.

For consistency, you might want to make them similar (less negative than `[ ] Disable taps / [ ] Disable swipes`)

**Comment by hius07** [comment]
> you might want to make them similar

https://github.com/koreader/koreader/pull/7572#issuecomment-835966676

**Comment by poire-z** [comment]
All these have no meaning with File browser ? Were there working inside file browser?
We tap on chevrons, so no need to disable taps - dunno if people were disabling Swipe in file browsers and menu (but there's no real other purpose for swipes I can think ok).
Dunno if "Invert..." worked in File browser. These should be inverted when the UI language is RTL - dunno if people would want inverted with another language - but I guess if this worked, it was luck, and not something we have to keep.

**Comment by hius07** [comment]
> All these have no meaning with File browser ?

Yes, we have discussed that and you've decided it had no meaning with File browser.

**Comment by hius07** [comment]
If you mean inverting in FB - it never existed via this menu.

**Comment by poire-z** [comment]
> 
> 
> > you might want to make them similar
> 
> [#7572 (comment)](https://github.com/koreader/koreader/pull/7572#issuecomment-835966676)


Not convinced :)
The constraints are dealt with by your checkboxes logic.
As for _the general request for those is "how can I disable <swipes/taps>", not the other way around ;)._, we default them all to be enabled (so, all checked), don't we ? so, we go to the menu to disable/uncheck stuff.

Btw, shouldn't there be here also buttons (no idea if disabling buttons is implemented):

```
Page turns>
  [x] Taps
  [x] Swipes
  [x] Buttons
```

**Comment by NiLuJe** [comment]
> Btw, shouldn't there be here also buttons (no idea if disabling buttons is implemented):

IIRC, it isn't ;).

**Comment by poire-z** [comment]
> 
> 
> > All these have no meaning with File browser ?
> 
> Yes, we have discussed that and you've decided it had no meaning with File browser.
> [#7572 (comment)](https://github.com/koreader/koreader/pull/7572#issuecomment-829978757)

Too many discussions, to little memory :(
But ok, looks like I had given it some thoughts in the past - so I guess I'll stick with their conclusions, and agree with what you did :)

**Comment by hius07** [comment]
<kbd></kbd>

<kbd></kbd>

I'm fine with both, so up to your decision.

**Comment by poire-z** [comment]
I prefer the ones with Taps/Swipes to those with "Disable".
@NiLuJe ? @Frenzie ?

**Comment by hius07** [comment]
Activate menu

<kbd></kbd>

**Comment by NiLuJe** [comment]
The usual request for page-turns is usually to *disable* one form or the other, but it's ultimately not a big deal which way its presented, as long as it's clear ;).

And on that note, a minor advantage of the "Disable" variant is that it's clearer even out of context. If you somehow trip your way inside that menu, the lack of context around the Tap/swipe variant is mildly more confusing. (Unlikely scenario, though).

**Comment by poire-z** [comment]
> And on that note, a minor advantage of the "Disable" variant is that it's clearer even out of context. If you somehow trip your way into that menu, the lack of context around the Tap/Swipe variant is mildly more confusing. (Unlikely scenario, though).

But this remarks is as pertinent (and as minor :) for the current "Activate menu" submenu.
I'm just for consistency: either negative "Disable taps/swipes" in both, Or positive "Taps/Swipes" - with a minor++ preference for the positive tone (for consistency too).
And if the positive is too small and unclear in this unlikely scenario, then some longer "Activate menu/page turns with taps/swipe" - but well, unlikely/too long :)

**Comment by Frenzie** [comment]
The checkmark indicates enable/disable. I'm not sure what the word "enable" or "disable" would add.

**Comment by Frenzie** [comment]
Do they ensure one is always active? Don't want to lock people out. ;-)

**Comment by hius07** [comment]
> Do they ensure one is always active?

Activate menu: one is always active, initial install: both active.
Invert page turn taps and swipes: none can be active (device with buttons), initial install: both active.

**Comment by hius07** [comment]
Single or plural (see screenshots)?

**Comment by mergen3107** [comment]
> Single or plural (see screenshots)?

Maybe we should call the entry `Activate menuS` and inside use `By Tap`, `By Swipe`? Or without “By”

**Comment by hius07** [comment]
> Single or plural

I mean `Tap` or `Taps`.
Historically it was `Only tap` in Activate menu and `Disable taps` in Page turns.

**Comment by Frenzie** [comment]
Perhaps both singular then, but the singular/plural distinction does make a lot of sense.

**Comment by poire-z** [comment]
> the singular/plural distinction does make a lot of sense

Which distinction/sense ?

No opinion about singular/plural - but yes, may be "By tap/taps" or "With tap/taps" make it a little bit longer and hint at previous context better than just "Tap/taps".

**Comment by hius07** [comment]
<kbd></kbd>
<kbd></kbd>

**Comment by poire-z** [comment]
If _With_ in "With taps" is correct english grammar, I like these :)

**Comment by Frenzie** [comment]
@poire-z 
> Which distinction/sense ?

You open the menu with a tap.

You turn pages with taps. 

Of course you also turn the page with a tap, but it's very, very few (if not necessarily singular) vs very, very many.

In any case, active menu with tap*s* just sounds wrong. That should be with a tap/swipe. ;-) While page turns are something you do with taps/swipes. Otherwise it should be something like `turn the page`.

**Comment by poire-z** [comment]
Thanks, got it.
I guess I'd be fine if we have "With taps" in one menu, and "With a tap" in the other (would "With tap" singular without a "a" work ?)
(I guess someone/some translators may think this is a bug/inconsistency :)

**Comment by hius07** [comment]
If the RTL mode is enabled for a book, should we enable the reverse order for Status bat progress bar and SkimToWidget progress bar? See https://github.com/koreader/koreader/issues/7917.

**Comment by poire-z** [comment]
No opinion. Pinging immersive manga reader @mergen3107 (there must be others, @Galunid ?) and Hebrew reader with an English UI @yparitcher

**Comment by mergen3107** [comment]
@hius07 
This would be great!

**Comment by hius07** [comment]
A small fix is required to avoid appearing Page turns in the filemanager menu, I'll make it soonest.

**Comment by Zeyadas** [comment]
> If the RTL mode is enabled for a book, should we enable the reverse order for Status bat progress bar and SkimToWidget progress bar? See #7917.

That would be great, I second this.. I read mostly Arabic texts both pdf and epub..

**Comment by poire-z** [comment]
@Zeyadas : with the UI language set to Arabic or some other LTR language ?

If set to Arabic, you should already have them RTL - don't you ?

image

**Comment by poire-z** [comment]
And if not having a RTL language UI: wouldn't it feel odd to have the progress bar inverted, but not the buttons (ie, unlike previous screenshot, buttons would move the progress bar in the other direction).

**Comment by hius07** [comment]
> the progress bar inverted, but not the buttons

<kbd>skim</kbd>

**Comment by Galunid** [comment]
@poire-z While I do read manga, I don't use RTL mode, so no opinion from me

**Comment by hius07** [comment]
> avoid appearing Page turns in the filemanager menu

Fixed.

**Comment by hius07** [comment]
> would "With tap" singular without a "a" work ?

Waiting for the doctor.

**Comment by Frenzie** [comment]
> While I do read manga, I don't use RTL mode, so no opinion from me

I also read manga (rarely) and I just use the normal UI. The text on the page flows the other way around, that's all.

**Comment by poire-z** [comment]
Doctors @Frenzie @NiLuJe (you set a :+1: but dunno if this was an answer to that question :), there's a question for you just above :) https://github.com/koreader/koreader/pull/8022#issuecomment-886163565

```
With tap
With swipe
```
vs
```
With a tap
With a swipe
```

**Comment by NiLuJe** [comment]
Definitely with an article in front ;).

**Comment by poire-z** [comment]
Looks like I can get both `[ ] With taps/swipes` unchecked (on the emulator, no button) - which makes it at it says : I can't turn pages. (But OK, I can still access the menu to fix that.)
Is this wanted ?

**Comment by Frenzie** [comment]
People with buttons might want that, and of course even if you disable that you can still assign tap actions to the corner zones. So while it does seem a bit silly, possibly, since it's not a dangerous lockout situation it seems like there's no reason not to allow for it.

**Comment by NiLuJe** [comment]
I vaguely remember thinking whether I should guard that behind some kind of cap check, and came to the same conclusion ;).

**Comment by NiLuJe** [comment]
Locking page turns on button less devices might even be seen as a weird corner case might come in handy feature ;p.

**Comment by poire-z** [comment]
Ok.
(Another use case would be in scroll mode and you'd want just scrolling/swipe up/down, and not our current taps & swipe left/right cause you're nervous and play drums on your screen a lot)

**Pull request merged**
