### PR TITLE
Allow i18n in KoboUSBMS

### PR DESCRIPTION
**Pull request by NiLuJe**
(... at least in theory ;p)

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/6566)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Pending actual support in the version we use ;p.

@Frenzie: How would this work, actually? Because I'd need the .po at build time, and then compile them properly so they end up in the tarball...

On the upside, the in-repo test with a French translation works, so, there's that.

**Comment by Frenzie** [comment]
You mean including it in the big file might be problematic? In that case I guess we'd have to go with the new module option.

**Comment by NiLuJe** [comment]
Yeah, it's a dedicated domain.

In practice, that means moving the repo to the org, a new weblate component, and either weblate pushing to the repo or a new l10n subrepo or something?

And then a crapload of Makefile magic to hide the mess?

Can Weblate ship compiled .mo files for us, or am I hoping for too much? ^^.

**Comment by Frenzie** [comment]
> In practice, that means moving the repo to the org, a new weblate component, and either weblate pushing to the repo or a new l10n subrepo or something?

Pretty much, yes. subrepo vs just the repo depends on if you're okay with some noise.

There's an addon to generate `.mo` files.

**Comment by NiLuJe** [comment]
@Frenzie: Okay, transfer is done ;).

in-repo is fine by me for such a small tool. And yes please for the .mo add-on ;).

**Comment by oldman63** [comment]
> Yeah, it's [a dedicated domain](https://github.com/NiLuJe/KoboUSBMS/compare/v0.9.1...master).
> 
> In practice, that means moving the repo to the org, a new weblate component, and either weblate pushing to the repo or a new l10n subrepo or something?

The Hungarian translation is ready ...
Where can I upload the po file?

**Comment by Frenzie** [comment]
@oldman63 You should be able to use "upload file" in https://github.com/koreader/KoboUSBMS to create a PR.

**Comment by Frenzie** [comment]
@NiLuJe I dropped them an e-mail. Depending on how busy they are + covid and whatnot I don't know how long it'll take since we're not paying for anything, and of course paying customers come first. ;-)

**Comment by NiLuJe** [comment]
@Frenzie: Cool, thanks ;).

**Comment by Frenzie** [comment]
@NiLuJe I just noticed you pushed exit to page 2. This'll need a bit more thought. ;-)

**Comment by NiLuJe** [comment]
@Frenzie: Ah, didn't notice, it's still on page 1 w/ my set of plugins...

**Comment by NiLuJe** [comment]
Err, actually, there are no plugins in that list, AFAICT?

o_O

**Comment by Frenzie** [comment]
System stats is a plugin.

**Comment by Frenzie** [comment]
But also I was looking in the reader, I think it has more menu items. ;-)

**Comment by NiLuJe** [comment]
Ah, okay, good point, I hadn't checked the Reader ;).

(I do have system stats enabled ;)).

**Comment by NiLuJe** [comment]
I admit that if the UI code wasn't already there, my first reflex would have been to put it inside the Exit > menu (because it's technically an exit state).

Then again, I kind of like it as a top-level option.

But I don't really see anything that could be moved out of the way in the Reader...

https://github.com/koreader/koreader/blob/06bce655c527735d1b331b71889e79124dfb31b4/frontend/ui/elements/reader_menu_order.lua#L160-L177

**Comment by NiLuJe** [comment]
Or, hmm, maybe moving Help after Exit?

**Comment by poire-z** [comment]
> maybe moving Help after Exit?

Not very standard, Exit is the last mostly everywhere I guess.
You could move system_statistics elsewhere, or in a submenu with other stuff.
I wouldn't mind ota_update, help and version in a submenu (as that's not something one would use when reading) but how to name it?

**Comment by Frenzie** [comment]
> I admit that if the UI code wasn't already there, my first reflex would have been to put it inside the Exit > menu (because it's technically an exit state).

The exit menu itself is already questionable for new users. :-P

**Comment by NiLuJe** [comment]
> 
> 
> > maybe moving Help after Exit?
> 
> Not very standard, Exit is the last mostly everywhere I guess.
> You could move system_statistics elsewhere, or in a submenu with other stuff.
> I wouldn't mind ota_update, help and version in a submenu (as that's not something one would use when reading) but how to name it?

I like both these ideas ;p.

Say, punt off device statistics to the fancy new "I don't know where to put this" 'More tools' menu, and then at *least* move Version inside the Update menu?

**Comment by poire-z** [comment]
> The exit menu itself is already questionable for new users. :-P

Yes... (in my own patch, I moved it into Help>, and just have Restart KOReader and Exit)

> Say, punt off device statistics to the fancy new "I don't know where to put this" 'More tools' menu, and then at least move Version inside the Update menu?

Fine with me. (System statistics could go to Hellp> :)
For what it's worth, I also have:
```diff
 common_info.version = {
-    text = _("Version"),
+    text = T(_("Version: %1"), version),
```
(which I think might be truncated with some DPI settings, but if it does not appear in the main first panel, it could be fine)

**Comment by Frenzie** [comment]
> Fine with me. (System statistics could go to Hellp> :)

Yup, makes sense.

**Comment by Frenzie** [comment]
> Yes... (in my own patch, I moved it into Help>, and just have Restart KOReader and Exit)

Something like that might not be a bad idea either. I kinda of like what Windows does, although I don't know how that tested with focus groups. (Well enough, one imagines). You have the big exit/shutdown button and if you click on the right side of it you get the options like sleep/suspend and restart.

**Pull request merged**
