### PR TITLE
[chore] Deprecate TapForward/TapBackward

### PR DESCRIPTION
**Pull request by Frenzie**
Also fix previous page action in gesture manager.

### CODE REVIEW

**Comment by poire-z** [comment]
2 things:
1) if you rename the ids `id = "tap_forward"`, you need to update a few other places that reference them:
```
frontend/apps/reader/modules/readerfooter.lua:            overrides = {
frontend/apps/reader/modules/readerfooter.lua:                'tap_forward', 'tap_backward', 'readerconfigmenu_tap',

frontend/apps/reader/modules/readerconfig.lua:            overrides = { 'tap_forward', 'tap_backward', },

frontend/apps/reader/modules/readerhighlight.lua:            overrides = { 'tap_forward', 'tap_backward', 'readermenu_tap', 'readerconfigmenu_tap', },
```
But I'm not sure we should use rel_forward in these - it's clearer to see the event has been mapped to a **tap**_forward elsewhere.

2) If the handler/event is made more generic by renaming `Tap` to `Rev`, well, it should accept an argument (a positive value, default to 1 - to be translated to -1 by the Backward handler).

So, not sure this is the right thing to do. (Might as well add new onSomething - and don't touch the onTap ones).

**Comment by Frenzie** [comment]
> If the handler/event is made more generic by renaming Tap to Rev, well, it should accept an argument (a positive value, default to 1 - to be translated to -1 by the Backward handler).

Those already exist. You have `PagingRel` and `GotoViewRel`. I'm not sure why the names differ.

These TapForward/Backward events seem to be intended as a (perhaps unnecessary) convenience for the most common use case.

So in that case, those particular event handlers should just be stripped out and replaced by the renamed generic handlers.

**Comment by Frenzie** [comment]
@poire-z How about this? It deprecates those two redundant events and renames PagingRel to GotoViewRel for consistency and calling simplicity.

**Comment by poire-z** [comment]
Yep, looks fine to me.

**Pull request merged**
