### PR TITLE
bump crengine: italic correction, alpha colors, fixes

### PR DESCRIPTION
**Pull request by poire-z**
Includes:
- https://github.com/koreader/crengine/pull/473 : 
- Fonts: fix hinting with synthesized weight inconsistencies
- Drawing: fix glyphs at top/bottom possibly truncated
- CSS vertical-align set on final blocks should not apply
- Text: correct glyph overlap at text node boundaries
- https://github.com/koreader/crengine/pull/474 : 
- Use #define for keyword color values
- lvdrawbuf: handle text and background colors with alpha

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8972)

### CODE REVIEW

**Comment by poire-z** [comment]
Mhhh, there's a few unrelated (possibly from some recent PRs, I remember reading something about _self) luachek warnings in the ci/circleci:build output. Dunno if it's the recent PR, or some luacheck upgrades, that is the cause of them.

**Comment by Frenzie** [comment]
Wait, why is it downloading any of that stuff in the first place?

Anyway, you can change this line:
https://github.com/koreader/koreader/blob/6ba481cd27250413acc8d2eff8b9382004ead18a/.ci/helper_luarocks.sh#L17

```
travis_retry luarocks --local install luacheck 0.25.0-1
```

**Comment by Frenzie** [comment]
https://github.com/lunarmodules/luacheck/releases/tag/v0.26.0
> Add "unused hint" flag
Function arguments that start with a single underscore get an "unused hint".
Leaving them unused doesn't result in a warning.
Using them, on the other hand, is a new warning (№ 214).

**Comment by poire-z** [comment]
Does that mean we could get rid of all our `-- luacheck: no unused` ?
(Although we use _ to indicate privateness/internalness, so I'd like to know if there are really unused if I added some and ended up not needing them).

Should I let the 2nd commit in and merge it with this ?

**Comment by Frenzie** [comment]
No, it means we either disable the new check, change our convention for avoiding variable collision or change luacheck. I'm currently leaning toward the latter.

**Comment by Frenzie** [comment]
> Should I let the 2nd commit in and merge it with this ?

Yes, please do.

**Pull request merged**
