### PR TITLE
Auto save book metadata: use SpinWidget

### PR DESCRIPTION
**Pull request by zwim**
Certainly not the most important improvement, but an improvement nonetheless.

Using a SpinWidget seems to be more sensible, than a submenu with restricted possibilities.

IMHO this solution also looks smarter and more modern as a submenu, but I will honor the consensus here.
As always, wording improvements are welcomed.

grafik

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9946)

### CODE REVIEW

**Comment by NiLuJe** [comment]
I don't recall how it currently looks, but this certainly makes sense ;).

**Comment by zwim** [comment]
Currently it looks like this (and the menu entry is misleading, as suspend end exit are missing :( ):
grafik

And the submenu looks like that:
grafik

**Comment by NiLuJe** [comment]
Missing in what sense?

**Comment by zwim** [comment]
The original menu entry states: "only on close". 
In the beginning of using KOReader, as a naive user I believed everything written ;-) I thought, oh well only on close, but what about suspend? So I set the value to 1 to be safe not loosing any reading progress (esp. during suspend). Now I know better.

To be serious: If we write "only" this is wrong as we already save on exit, close and suspend. But the user has no chance to realize this (only after studying the code). This PR will also fix this unclear text.

**Comment by NiLuJe** [comment]
That might actually be a bug and/or a regression, because doing that on suspend sounds pretty sensible to me (and I'm the one who lobbied to keep that behavior, so if it doesn't even work as I thought it did, oopsie? :D).

**Comment by NiLuJe** [comment]
Oh, wait, I'm super tired. I thought you meant it didn't actually save on suspend, but you're just talking about the inconsistency in the wording between the drilled/undrilled menu, right?

**Comment by hius07** [comment]
I would avoid ambiguity and set the minimum interval to 1.
Disable with a button only.

**Comment by NiLuJe** [comment]
> I would avoid ambiguity and set the minimum interval to 1.
> Disable with a button only.

Agreed. (Even if that happens to mean the setting is set to 0).

**Comment by poire-z** [comment]
I think this is one setting that does not need a spin widget nor more choices, and that people don't need and won't be happier with being able to chose 7 minutes or 17 minutes or 37 minutes.
And that an enumerated list of sensible values, plus an explicite "on close, suspend and exit" is just better (and if we need to offer more sensible values, we have room for 4 more) - than having the user in front of less explicit spin widget saying "use 0 for 'on close, suspend and exit'" :)

**Comment by NiLuJe** [comment]
No strong feeling on this one (besides the obvious inconsistency about the wording mentioned above), but, while not terribly useful in practice, it does feel less clunky than a list of preset to me?

**Comment by zwim** [comment]
> I would avoid ambiguity and set the minimum interval to 1. Disable with a button only.

Agreed; and I would set the minimum to 5 min.

As the `value_step` is 5 min, the user gets a grid (5, 10, 15 ... 60 min) to select from. 
A more advanced user can tap on the value and enter any value from the interval 5-60min. (An even more experienced user might use the colon operator on value input and get any value :) )

> than having the user in front of less explicit spin widget saying "use 0 for 'on close, suspend and exit'" :)

Agreed to; therefore I have removed the 0min option now.

**Comment by poire-z** [comment]
> but an improvement nonetheless
> while not terribly useful in practice, it does feel less clunky than a list of preset to me?

It still does feel more clunky to me, and not an improvement:

Pros:
- allows selecting any intermediate interval (which is not super useful in practice)

Cons:
- no explicite suggestions: the user is in front of a spinwidget allowing 5 to 60 minutes, for a really technical setting, with no real help. The list of presets at least gives the idea that any of these values are just fine.
- the wording as a menu item is clearer
- the following menu item (not shown on the screenshot above as not shown on the emulator, but shown on my Kobo), is now only available as a help_text on long-press - while at the time, we thought it deserves to be a really visible menu item:
https://github.com/koreader/koreader/blob/180cebe7ee7005328cc98dd493302ea23091c8d7/frontend/ui/elements/common_settings_menu_table.lua#L475-L481
https://github.com/koreader/koreader/blob/180cebe7ee7005328cc98dd493302ea23091c8d7/frontend/ui/elements/common_settings_menu_table.lua#L526-L532
- (getting rid of the submenu won't allow adding other tweaks, like "also auto save when adding a bookmark/highlight")

**Comment by NiLuJe** [comment]
That's a fair couple of points ;).

**Comment by zwim** [comment]
@poire-z : I am not d'accord with the clunky statement, but your argument with other auto-save options (bookmarks or similar) convinced me.

I will suggest a rewording of the misleading wording of the menu entry (https://github.com/koreader/koreader/pull/9946#issuecomment-1364588746) maybe next week.

**Comment by poire-z** [comment]
Thanks.

> I will suggest a rewording of the misleading wording of the menu entry ([#9946 (comment)](https://github.com/koreader/koreader/pull/9946#issuecomment-1364588746))

> The original menu entry states: "only on close".
In the beginning of using KOReader, as a naive user I believed everything written ;-) I thought, oh well only on close, but what about suspend? So I set the value to 1 to be safe not loosing any reading progress (esp. during suspend). Now I know better.
To be serious: If we write "only" this is wrong as we already save on exit, close and suspend. But the user has no chance to realize this (only after studying the code).

We need something smaller, and "on close" evokes these other kind of "closing stuff" that are "suspend" and "exit", so this is not an issue for me.

**Pull request closed without merging**
