### PR TITLE
fix end of book detection for crengine

### PR DESCRIPTION
**Pull request by houqp**
This should fix https://github.com/koreader/koreader/issues/1975

### CODE REVIEW

**Comment by Frenzie** [comment]
*sigh* stupid segmentation faults

**Comment by houqp** [comment]
Nice... looks like it caught a reproducible bug with gcc in travis-ci.... I will try to reproduce on my side.

**Comment by houqp** [comment]
I am an idiot, I forgot to check in the sample txt file ;)

**Comment by N46AN** [comment]
Thanks for taking time to fix this issue!

**Comment by houqp** [comment]
@N46AN thanks for providing us a really good test case ;)

**Pull request merged**
