### PR TITLE
[autowarmth, plugin] use date time widget, optimize

### PR DESCRIPTION
**Pull request by zwim**
An update: Use `datetimewidget` and optimize speed (30%) and accuracy.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8502)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Improve speed you mean profiling performance or is that something you can actually notice?

**Comment by zwim** [comment]
I mean profiling performance. I have not noticed any change on my device. 
(Performance is not a big point here, as this is only calculated once at startup and then shortly after midnight.)

**Comment by poire-z** [comment]
Feel free to merge if you're done with it (too many maths for me to give any review :)

**Comment by poire-z** [comment]
CircleCI :
```
Warning: possible improperly tagged todo, fixme or warning detected.
         use --- followed by @todo, @fixme or @warning.
plugins/autowarmth.koplugin/suntime.lua:377:        return asin(val) - eod -- todo self.eod is a bit to small

```

**Pull request merged**
