### PR TITLE
imageview add night mode support. only background support.

### PR DESCRIPTION
**Pull request by greatyingzi**
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9846)

### CODE REVIEW

**Comment by NiLuJe** [comment]
I don't even remember how ImageViewer handles nightmode (or not), what is this trying to achieve?

**Comment by NiLuJe** [comment]
After having checked on devices both with and without HW nightmode, I see the current behavior as working as intended, so, yeah, confused as to what this is trying to solve ;).

**Comment by greatyingzi** [comment]
> 

@NiLuJe While mode of system is night_mode,Theme color is black. User try view a small image ,The bg of ImageView is white, A sudden Theme color change from black to white. Uncomfortable.

**Comment by NiLuJe** [comment]
The reverse would be true, a black background would be jarring for most
other use-cases ;).

It would also set an unwanted precedent, code-wise (of arbitrary color
changes in night mode).

**Comment by greatyingzi** [comment]
> The reverse would be true, a black background would be jarring for most other use-cases ;). It would also set an unwanted precedent, code-wise (of arbitrary color changes in night mode).
> […](#)

@NiLuJe Maybe the method of my implementation isn’t better.But the thought is reasonable like most other apps .

**Comment by NiLuJe** [comment]
It's more the principle of the thing, I do understand your reasoning (even if I don't agree with it): it would effectively make the widget behave differently in nightmode than in daymode by "framing" the image. Since we don't actually invert images in nightmode, this doesn't make sense, the background is intended to be white, as that's the most sensible default for  a background color[*], and breaks consistency between the two modes.

Thankfully, if this bothers you so much, it's trivial enough that it should be fairly easy to deal with via an [user patch](https://github.com/koreader/koreader/wiki/User-patches) ;).

[*] I *would*, on the other hand, be open to a dynamic background color based on the most prevalent shade in the image (IIRC, the usual way to compute those is to squash the image to a 1x1 square with bi-linear blending and use the resulting color).

**Comment by poire-z** [comment]
> [*] I _would_, on the other hand, be open to a dynamic background color based on the most prevalent shade in the image

I don't think I would like that. Seeing straight white (or black in nightmode with this PR) is often a good hint about the image size and aspect ratio. Seeing some random color filling, that may or not follow the edge pixels color, would kill/degrade this early hint.
And any algo would probably not choose the right color for most images.

No real opinion about this PR (not using nightmode, but I checked on my device, after reading the first post, if this was actually the case - and I was indeed a bit surprised by the white filing. But I had read the first post :) Dunno if I would have been surprised if I hadn't read it).

**Comment by NiLuJe** [comment]
> I don't think I would like that. Seeing straight white (or black in nightmode with this PR) is often a good hint about the image size and aspect ratio. Seeing some random color filling, that may or not follow the edge pixels color, would kill/degrade this early hint.
> And any algo would probably not choose the right color for most images.

I wouldn't really like it personally either, FWIW, but it could sorta make sense as an optional setting somewhere is more what I was trying to convey ;).

**Comment by Frenzie** [comment]
What about gray for both?

**Comment by NiLuJe** [comment]
That's usually also a viable alternative, although that one might not play well on eInk ;).

**Comment by poire-z** [comment]
> What about gray for both?

You should know my GloHD by now :)

I guess I would be fine with the idea, generically, using 0x80, middle gray, and I would be happy with the final result, .
But on eInk, dunno if others still get the transitionning refresh white>black>gray (may be less stongly than on my GloHD), it feels not having any transition/animation on the outside of the image could give a hint of what is the size of the image, having only it getting these transitions, instead of the whole screen.

**Comment by Frenzie** [comment]
> That's usually also a viable alternative, although that one might not play well on eInk ;).


Is it all that bad given that the image itself is a big mixture of grays?

**Pull request closed without merging**
