### PR TITLE
Dummy

### PR DESCRIPTION
**Pull request by hius07**
Sorry, zero changes, just to synchronize the fork.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8632)

### CODE REVIEW

**Comment by hius07** [comment]
Didn't help, still my fork "This branch is 5 commits ahead of koreader:master."

**Comment by Galunid** [comment]
Try
```
git checkout master
git pull upstream master  # upstream is koreader/koreader
git push -f origin master  # origin is hius07/koreader
```

You'll lose the 5 commits that you're ahead

**Comment by poire-z** [comment]
No idea how to solve this from the web UI.
In command line git, that would be `git reset --hard HEAD~5`.
As you don't have any other branch (with work you would not want to lost) than master, I think you could just delete/remove your fork, and fork again.

**Comment by hius07** [comment]
Yes, I am in the web browser and cannot find any buttons to remove these commits. Thanks.

**Pull request merged**
