### PR TITLE
[RTL UI] Bidi-wrap filenames, paths, urls, metadata

### LINKED ISSUE #1426: File names in file browser do not respect RTL
I have some files where the filename is in Hebrew.
Using the latest Android release, in the file browser, those names are displayed backwards.

### PR DESCRIPTION
**Pull request by poire-z**
Follow up to #5667 and #5694. Discussion in https://github.com/koreader/koreader/issues/5359#issuecomment-566959691.

This also helps displaying correctly RTL and bidi filenames and directories in a LTR UI.
Not tested, may have typo and parens errors :)
The Bidi._path and co at the bottom of bidi.lua and the aliasing will need some tuning.

I hardcoded Bidi.ltr() for IP adresses and IP:port combo. Dunno if they need some other kind of wrapping, or if `192.0.0.1:433` could really be displayed `443:1.0.0.192` in RTL :)

Also fix UI mirroring of SortWidget that I forgot in #5667.
Closes #1426.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/5696)

### CODE REVIEW

**Comment by poire-z** [comment]
> Seems like that %1 - %2 should just be part of the string so that it can be freely positioned by the translator. Not just for RTL purposes but also so you can say something like:
Minimal size left: %1 Minimal size right: %2

Yes, but this one is a menu item text, and I think most of them showing some parameters have a fixed text on the left, and the the selected param/option on the right, either after a `:` or inside parenthesis.
Free positionning is fine in other contexts, but may be for menu, it's better to have a rather contant look.
That menu item may also have an alternate text: 
```
Left/right minimal sizes: 3 - 2
Left/right minimal sizes: language defaults
```
So, dunno if we should have 2 translatable strings, one with free positionnning, that could make them really different.

**Comment by Frenzie** [comment]
Your translation app of choice will normally show you similar strings, so it should be a conscious choice to deviate. And in any case, there would be no deviation whatsoever if the translation were:

```
Right/left minimal sizes: %2 - %1
Right/left minimal sizes: language defaults
```

**Comment by yparitcher** [comment]
looks good to me so far :)
i have not tested all the corner cases though

**Comment by poire-z** [comment]
(Last force-push is just a rebase to master - no change related to this PR.)

**Comment by poire-z** [comment]
Updated to fix the issue mentionned at https://github.com/koreader/koreader/issues/5359#issuecomment-567671590 - will need a base bump for https://github.com/koreader/koreader-base/pull/1025 too.
TextBoxWidget: fix some issue (line.width not updated when adding the ellipsis) which caused the ellipsis to not be displayed when right align, because we were shifting x too much (no issue in LTR where we left align).
BD.auto() for title, author(s).... some rework of CoverBrowser bits, that I haven't all tested - but well, they looks logical.
(Getting a bit fed up with Bidi...)

**Comment by Frenzie** [comment]
Just take a break from bidi if it's getting too much. It's already working great if you ask me! ;-)

**Comment by poire-z** [comment]
I just don't want a break! I want it behind me, done and gone forever ! :)
Should be over soon when this one is merged (except for the possible edge case bugs...).
Might still be some stuff to fix with time and durations, depending on how they should be in AR/HE.

**Comment by poire-z** [comment]
OK, merging this one, so we get feedback and fixes sooner, and be done with it.

(I didn't do the replacements of the existing `file:match("([^/]+)$")` & co with `util.splitFilePathName()` - there were already too much changes.)

Possibly something to try to do: when displaying book metadata (title, authors...), provide the
language from the book metadata to TextWidgets/XText.

**Pull request merged**
