### PR TITLE
VirtualKeyboard: delete word on backspace swipe west

### PR DESCRIPTION
**Pull request by hius07**
Closes https://github.com/koreader/koreader/issues/11831.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11843)

### CODE REVIEW

**Comment by hius07** [comment]
Word delimiters, discussable:
https://github.com/koreader/koreader/blob/775e8410d6eed01f1fae15bd9e7c172c39d7d7a5/frontend/ui/widget/inputtext.lua#L768

**Comment by poire-z** [comment]
If I have the cursor in the middle of a word, ie `this repo|sitory should`, does this deletes the full word (and I end up with `this |should`) or just the part of the word before the cursor (ending up with `this |sitory should`) ?

**Comment by Frenzie** [comment]
On Android it's the last one, which seems more intuitive but perhaps also less useful?

**Review by Frenzie — APPROVED** [review]

**Comment by hius07** [comment]
It deletes the full word (between delimiters) under the cursor.

**Comment by poire-z** [comment]
I also feel deleting just the part before the cursor is more intuitive, at least what I would expect.
But given how hard it is to precisely position the cursor with our fat fingers, deleting the full word might be fine, once we are used to that behaviour.

> And deletes an extra space, if needed.

You mean the cursor is at the immediate end of the previous word, and I need to input a space before typing my new word?
I would expect to not have to type that space, but may be this behaviour is needed to a new backspace swipe can delete another previous word, and we can easily do that in sequence?

**Comment by hius07** [comment]
> may be this behaviour is needed to a new backspace swipe can delete another previous word, and we can easily do that in sequence?

Yes, I thought it was convinient.

**Comment by Frenzie** [comment]
So would we rather only left of cursor or whole word?

**Comment by hius07** [comment]
Added dashes as word delimiters.
Swipe west deletes part of the word left to cursor.
Swipe north deletes the whole word.

**Review by Frenzie — APPROVED** [review]
sounds good to me

**Review by poire-z — APPROVED** [review]
Let's merge and see how it works.

**Comment by mergen3107** [comment]
Just to be clear, we now have FOUR backspaces?
1) Just tap backspace to delete a character. 
2) Long-tap to delete a whole line
3) Swipe west to delete a part of the word until a dash
4) Swipe north to delete a whole word.

Shouldn't it be easier if (1) stays, but 2-4 are put into a popup menu that opens with a long tap?

**Comment by Frenzie** [comment]
I don't know, it's roughly the same as on most other mobile keyboards. :-)

I don't think we've implemented ctrl+backspace on keyboard yet.

**Comment by poire-z** [comment]
Just a note, not sure it needs fixing and if it would be simple:
When using swipe west multiple times to delete words, actually to delete faster a bunch of CSS properties (so, words, minus, %, colons...) in a style tweak, only the first swipe west does something, the next ones don't and I need to tap backspace to move a bit and be able to have the next swipe west work.

Actually, it feels it doesn't even work after a first swipe west, even in regular text:
image
After backspace swipe west:
image
and then we're stuck: next backspace swipe west do nothing.
Did it used to work @hius07 ? Is this some regression from the latest NT/keyboard tweaks?

**Comment by hius07** [comment]
Swipe north deletes a word together with a space.

**Comment by hius07** [comment]
> swipe north still gets me stuck with that:

Yes, it's a word delimiter that belongs to the previous word, we go from right to left and stop on it.
https://github.com/koreader/koreader/blob/698fc35c3f1a10233cf69085a87fb912e2f79841/frontend/ui/widget/inputtext.lua#L831

**Comment by hius07** [comment]
For example, in "one,two" if cursor stands between coma and t (there is no space between, bad formatting) - swipe north deletes "two", that is good.

**Comment by hius07** [comment]
To fix the last issue, we can check if the word is empty, and find the next (to the left) word to delete.

**Comment by poire-z** [comment]
Sounds good.

**Comment by hius07** [comment]
Can you try if it is the desired behaviour. Please note that normally we do not delete the punctuation mark together with a word. So the fix deletes **the punctuation mark** when the word under the cursor is empty.
```diff
--- a/inputtext.lua
+++ b/inputtext.lua
@@ -913,6 +913,7 @@ function InputText:delWord(left_to_cursor)
         return
     end
     local start_pos, end_pos = self:getStringPos(true, left_to_cursor)
+    start_pos = math.min(start_pos, end_pos)
     for i = end_pos, start_pos, -1 do
         table.remove(self.charlist, i)
     end

```

**Comment by poire-z** [comment]
This works well for me, with both swipe west or north (with swipe north being a bit more turbo delete :) avoiding the swipes needed to remove the spaces, that we have to do with swipe west).

**Pull request merged**
