### PR TITLE
use new `ffi.loadlib` helper

### PR DESCRIPTION
**Pull request by benoit-pierre**
To load our native libraries.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12545)

### CODE REVIEW

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/12545)* status: all files reviewed, 2 unresolved discussions (waiting on @benoit-pierre)

___
*[`frontend/device/pocketbook/device.lua` line 246 at r1](https://reviewable.io/reviews/koreader/koreader/12545#-O7U0jRhAm0LoGivrQWS:-O7U0jRhAm0LoGivrQWT:b-f1cnyh) ([raw file](https://github.com/koreader/koreader/blob/295ef3930352c263a66b37503107b29b2914e453/frontend/device/pocketbook/device.lua#L246)):*
> ```Lua
>     -- NOTE: This is the odd one out actually calling input.open as a *method*,
>     --       which the imp supports to get access to self.input.raw_input
>     if (not self.input.raw_input) or (not pcall(self.input.open, self.input, self.input)) then
> ```

That was already a method call, no need to pass `self.input` twice ;).

(The actual sig is `function input:open()`, so it doesn't take any extra args).
___
*[`spec/unit/device_spec.lua` line 58 at r1](https://reviewable.io/reviews/koreader/koreader/12545#-O7U1KCC1euzps9fHrs4:-O7U1KCC1euzps9fHrs5:b-rlasqn) ([raw file](https://github.com/koreader/koreader/blob/295ef3930352c263a66b37503107b29b2914e453/spec/unit/device_spec.lua#L58)):*
> ```Lua
>         package.unload("ui/uimanager")
>         package.unload("apps/reader/readerui")
>         mock_input.force_sdl = false
> ```

You got rid of that `force_sdl` stuff in a previous refactor, or am I mixing stuff up?

**Comment by benoit-pierre** [comment]
> > Reviewed 21 of 21 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/koreader/koreader/12545)_ status: all files reviewed, 2 unresolved discussions (waiting on @benoit-pierre)
> 
> _[`frontend/device/pocketbook/device.lua` line 246 at r1](https://reviewable.io/reviews/koreader/koreader/12545#-O7U0jRhAm0LoGivrQWS:-O7U0jRhAm0LoGivrQWT:b-f1cnyh) ([raw file](https://github.com/koreader/koreader/blob/295ef3930352c263a66b37503107b29b2914e453/frontend/device/pocketbook/device.lua#L246)):_
> 
> > ```lua
> >     -- NOTE: This is the odd one out actually calling input.open as a *method*,
> >     --       which the imp supports to get access to self.input.raw_input
> >     if (not self.input.raw_input) or (not pcall(self.input.open, self.input, self.input)) then
> > ```
> 
> That was already a method call, no need to pass `self.input` twice ;).

But `Input.open` wasn't: the goal is to pass `self.input` to the underlying input implementation open call so `raw_input` can be accessed, no? The first `self.input` become `self` in `Input:open`, then the second one is passed as `path` and forwarded to `self.input`, which is itself a method.

> (The actual sig is `function input:open()`, so it doesn't take any extra args).
> 
> _[`spec/unit/device_spec.lua` line 58 at r1](https://reviewable.io/reviews/koreader/koreader/12545#-O7U1KCC1euzps9fHrs4:-O7U1KCC1euzps9fHrs5:b-rlasqn) ([raw file](https://github.com/koreader/koreader/blob/295ef3930352c263a66b37503107b29b2914e453/spec/unit/device_spec.lua#L58)):_
> 
> > ```lua
> >         package.unload("ui/uimanager")
> >         package.unload("apps/reader/readerui")
> >         mock_input.force_sdl = false
> > ```
> 
> You got rid of that `force_sdl` stuff in a previous refactor, or am I mixing stuff up?

Good catch, updated in #12486.

**Review by NiLuJe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/12545)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @benoit-pierre)

___
*[`frontend/device/pocketbook/device.lua` line 246 at r1](https://reviewable.io/reviews/koreader/koreader/12545#-O7U0jRhAm0LoGivrQWS:-O7V3q-h8as8SWaH4VKv:bcxlsjt) ([raw file](https://github.com/koreader/koreader/blob/295ef3930352c263a66b37503107b29b2914e453/frontend/device/pocketbook/device.lua#L246)):*
<details><summary><i>Previously, benoit-pierre (Benoit Pierre) wrote…</i></summary><blockquote>

> > ```lua
> >     -- NOTE: This is the odd one out actually calling input.open as a *method*,
> >     --       which the imp supports to get access to self.input.raw_input
> >     if (not self.input.raw_input) or (not pcall(self.input.open, self.input, self.input)) then
> > ```
> > 

> 
> That was already a method call, no need to pass `self.input` twice ;).
> 

But `Input.open` wasn't: the goal is to pass `self.input` to the underlying input implementation open call so `raw_input` can be accessed, no? The first `self.input` become `self` in `Input:open`, then the second one is passed as `path` and forwarded to `self.input`, which is itself a method.


> (The actual sig is `function input:open()`, so it doesn't take any extra args).
> 
> 
</blockquote></details>

Oh, right, I forgot the the backend calls in `Input:open` weren't method calls (i.e., I was going on the assumption that `Input:open` basically did `self.input:open`, which it doesn't ;p).

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/12545)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Frenzie, @pazos, and @poire-z)

**Review by Frenzie — APPROVED** [review]

**Pull request merged**
