### PR TITLE
CoverBrowser: fix cover cache check #2

### PR DESCRIPTION
**Pull request by hius07**
Related issue https://github.com/koreader/koreader/issues/11375.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11380)

### CODE REVIEW

**Comment by poire-z** [comment]
Looking at the changes, it seems you want cover_w/h even when not get_cover or has_cover ? In what situations ?

**Comment by hius07** [comment]
https://github.com/koreader/koreader/blob/30e39a7d30c40e7b87e6c852ddc089a5b546b88b/plugins/coverbrowser.koplugin/bookinfomanager.lua#L879-L884
Line 879, call without `true` as the 2nd arg.
`cover_w` and `cover_h` are used by `isCachedCoverInvalid`.

**Comment by poire-z** [comment]
OK, you could also have just moved the 2 lines just before the `if not get_cover then break`:
```lua
                bookinfo["cover_w"] = tonumber(row[num])
                bookinfo["cover_h"] = tonumber(row[num+1])
            if not get_cover then
                -- don't bother making a blitbuffer
                break
            end

```
to avoid the 3 string comparisons on each column `if col == "pages" or col == "cover_w" or col == "cover_h" then`.

Btw, does this all work fine if, started from an empty bookinfo cache, having `Mosaic with text covers` (so, I gues no cover fetch), getting some stuff cached, and then switching to a mode with cover images?

**Comment by hius07** [comment]
Yes, works fine with that case.

**Review by poire-z — APPROVED** [review]

**Pull request merged**
