### PR TITLE
experimental port to Mac OSX

### PR DESCRIPTION
**Pull request by chrox**
Currently it can open cre-based docs and Djvu docs
It still has some problems with PDF docs and the touch input.

screen shot 2016-04-15 at 1 13 52 am

### CODE REVIEW

**Comment by houqp** [comment]
This is super awesome!

**Comment by houqp** [comment]
@chrox , can you rebase?

**Comment by chrox** [comment]
Sure, I will give it a try.

**Comment by chrox** [comment]
This unit test failed:
```
[1mReadersearch module search API for EPUB documents should find all occurrences[0m
spec/front/unit/readersearch_spec.lua:93: Expected objects to be equal.
Passed in:
(number) 14
Expected:
(number) 13
```
Does recent crengine patch have anything to do with this? The EPUB document should have 13 occurrences of the word "Verona" indeed.
screen shot 2016-04-22 at 9 00 03 pm

**Comment by houqp** [comment]
I can confirm that https://github.com/koreader/crengine/commit/2d468b5216e886bd5f4dab68a02d8939cc6eb8fb broke this test. @frankyifei any insight? It looks weird an image render change breaks the search test.

**Comment by chrox** [comment]
I fixed the failed unit test. It's actually a bug in the unit test code. We search the occurrence of a word from the beginning to the end but if multiple occurrences are returned by `searchFromCurrent` we will soon count that word again because we will only move our cursor to the first found word. koreader/crengine@2d468b5 just makes this happen and triggers the bug.

**Comment by houqp** [comment]
Nice! Thanks @frankyifei for uncovering a bug in the unit test ;)

**Pull request merged**
