### PR TITLE
[UX] Add paragraph whitespace/indent style tweaks

### PR DESCRIPTION
**Pull request by Frenzie**
Requested on the forum, and it makes a lot of sense.

https://www.mobileread.com/forums/showthread.php?p=3777972#post3777972

### CODE REVIEW

**Comment by KenMaltby** [comment]
Note that the MR poster wasn't familiar with CSS yet was willing to work with Frenzie,  The plain options provided make it much easier (and more likely to be tried) by the average user.  

I wonder if the new CSS entries could be displayed, on hold perhaps, for those learning the effects of the CSS instructions.  Perhaps with an ability to tweak the values used?

Luck;
Ken

**Comment by Frenzie** [comment]
They already are, automatically. :-) See the original screenshots in #3944.

I don't think tweaking is currently a direct option.

**Comment by KenMaltby** [comment]
Oh yes, those examples in #3944 are about perfect.

**Comment by poire-z** [comment]
cr3.css shouldn't be looked at (dunno if it is really used, or read earlier and overriden), it's epub.css that matters.
And in it, you have our default for P:
```css
p {
    text-align: justify;
    text-indent: 1.2em;
    margin-top: 0;
    margin-bottom: 0;
}
```
Your tweaks use `p + p`, so they only override the 2nd++ paragraphs.
I thought this was your aim (I've seen such texts I think, with only the first paragraph indented).
But as I prefer _indent every parapgraph_, I can't say much about what those who don't want...

**Comment by Frenzie** [comment]
My aim was to override only p+p because I assumed p wasn't indented in the first place. :-)

**Comment by poire-z** [comment]
> Are there some known conflicts with other options

Not that I know of.
Except may be if the embedded stylesheet use themselves `!important`. You may try if it works better if you turned off Enbedded styles (bottom config menu, right most item).
Also, select a few words spanning parapgraphs, and use `View HTML` in the popup menu to see what's happening there (may be your paragraphs are not P but DIV :)
Otherwise, your user style may be invalid. Try with a unit just in case: `p { text-indent: 0em !important; }`

**Comment by avsej** [comment]
@poire-z yes, you was right, it was for my current book only. Seems like it has weird layout. For other books the tweaks work. Thanks

**Comment by poire-z** [comment]
> Your tweaks use p + p, so they only override the 2nd++ paragraphs.
> I thought this was your aim (I've seen such texts I think, with only the first paragraph indented).
> But as I prefer indent every parapgraph, I can't say much about what those who don't want...

> My aim was to override only p+p because I assumed p wasn't indented in the first place. :-)

So, should we replace `p + p` with just `p` in: ?
https://github.com/koreader/koreader/blob/e30bfd34e69a30cf41f89cdadf715f8b247250fb/frontend/ui/data/css_tweaks.lua#L133-L138

I guess it still makes sense to keep the `p + p` in those:
https://github.com/koreader/koreader/blob/e30bfd34e69a30cf41f89cdadf715f8b247250fb/frontend/ui/data/css_tweaks.lua#L149-L160

Also, I think this one should just use `margin-top: 0` and `margin-bottom: 0`:
https://github.com/koreader/koreader/blob/e30bfd34e69a30cf41f89cdadf715f8b247250fb/frontend/ui/data/css_tweaks.lua#L161-L166

(I'll PR some other tweaks soon, so I can include these "fixes" in.)

**Comment by Frenzie** [comment]
Yes, that seems right.

**Comment by poire-z** [comment]
Found a situation where I needed another style tweak:
Calibre | KOReader

<kbd>image</kbd>

I can get the Calibre layout by chosing `Style>html5.css`, but that's not what I want :)
I just needed another tweak: `p:first-child {text-indent: 0 !important; }` to get (with, strangely, no unwanted side effect on that book - all other paragraphs without a dropcap get their indent):

<kbd>image</kbd>

Is it worth to be added to the `Paragraph>` subsection of style tweaks? Or just kept as a user style tweak?
If the former, I guess we could add (we have room) the counterpart that you've had initially used in the first iteration of this PR:
`p+p {text-indent: 0 !important; }`

So:
`p:first-child {text-indent: 0 !important; }` `No indentation on first paragraph`
`p+p {text-indent: 0 !important; }` `No indentation on non-first paragraphs` (? :( )

Any better idea for the wording?
Would some others I can't think of make sense in yet other contexts?

**Comment by Frenzie** [comment]
Isn't `p:first-child, p+p` just a really convoluted way of just `p` with `!important`?

**Comment by poire-z** [comment]
Sorry?
Well, "just p with !important" won't allow setting something different for the first paragraph in a BODY vs the other ones :/
Oh, but these are 2 separate tweaks :) Of course, if you enable both, well, then, yes :)

**Comment by Frenzie** [comment]
My bad, I thought it was one tweak.

The CSS-like way of putting it would be something like `No indentation on adjacent paragraphs` but that sounds weird… I'd probably go with something like `No indentation on following paragraphs`. That's a bit cryptic taken by itself, but it should be a lot clearer when it's right underneath `No indentation on first paragraph`.

Shorter but probably less clear:
* Suppress first indent
* Suppress following indents

**Pull request merged**
