### PR TITLE
fix cannot login to Evernote

### LINKED ISSUE #2231: Koreader crashes when login to Evernote
- KOReader version: 20160823
- Device: KPW3
#### Issue

Koreader crashes when login to Evernote
#### Steps to reproduce

Login to evernote.

### LINKED ISSUE #2332: Error while logging in to Evernote
* KOReader version:
* Device: KA1

#### Issue
Logging in to Evernote, I get the following error:
```
An error occurred while logging in:
plugins/evernote.koplugin/EvernoteOAuth.lua:210: closed
```

I have a basic Evernote account. No devices are associated with this account yet.

#### Steps to reproduce

### LINKED ISSUE #2387: can not login evernote
can not login evernote while the evernote account using two-step-verification

### LINKED ISSUE #2452: can not login evernote: plugins/evernote.koplugin/EvernoteOAuth.lua:210:closed
* KOReader version: koreader-nightly-20161120
* Device:kindle paperwhite3

#### Issue
can not login evernote: plugins/evernote.koplugin/EvernoteOAuth.lua:210:closed
#### Steps to reproduce
when you login evernote ,it will show code like plugins/evernote.koplugin/EvernoteOAuth.lua:210:closed

### PR DESCRIPTION
**Pull request by chrox**
This should fix #2231, fix #2332, fix #2387 and fix #2452.

### CODE REVIEW

**Comment by KenMaltby** [comment]
Four in one shot!!

**Comment by Frenzie** [comment]
Is this the right base update? https://github.com/koreader/koreader-base/pull/478 doesn't include thirdparty/lj-wpaclient/CMakeLists.txt

**Comment by houqp** [comment]
@chrox the bug slayer ;)

Your base branch is behind master for one commit, the latest commit should be 26bfa43e1d7580a63b4fe4021c23334f9cf2ca62.

**Comment by chrox** [comment]
@Frenzie The `thirdparty/lj-wpaclient/CMakeLists.txt` change was in `koreader-base` master but not picked up in `koreader` master. In this pull request `koreader` will include the latest `koreader-base` thus will include koreader/koreader-base#476 and koreader/koreader-base#478.

**Comment by chrox** [comment]
@houqp Updated. The commit hash is overridden after being merged with the "Rebase and merge" option.

**Pull request merged**
