### PR TITLE
Refine docsettings, does not write history folder if it's not necessary

### PR DESCRIPTION
**Pull request by Hzj-jie**
This change eventually resolves two issues,
1. When a file has been renamed, it's sidecar file won't be renamed.
2. We are still writing to legacy history folder.

To the first issue, I have updated sidecar folder from file-name-without-suffix.sdr to file-name-with-suffix.sdr, and sidecar file name from file-name-with-suffix.lua to .lua. So we won't need to rename the sidecar file anymore, simply renaming the sidecar folder is enough.
To the second issue, I disallow writing to legacy history folder if writing to sidecar file succeeded.

### CODE REVIEW

**Comment by houqp** [comment]
Nice refactor for the candidate sorting :+1: .

Regarding to the renaming:

1. I suggest we change the name from `.lua` to `settings.lua` or something like that.
2. we should probably keep the old name for the sdr folders to keep it consistent with the native kindle reader. Otherwise, kindle users will ended up having two sdr folders for each book.

**Comment by Hzj-jie** [comment]
Hold on, reader.settings.lua won't be able to be updated.

**Comment by Hzj-jie** [comment]
I believe the original design considers the scenario that, two files with only different suffixes. We will eventually write to a same file. I do not think Kindle is doing a correct thing for this scenario.
To avoid this issue, we can also use file suffix as the setting file name. I.e. setting of a.pdf would be a.sdr/pdf.lua.

**Comment by houqp** [comment]
> I believe the original design considers the scenario that, two files with only different suffixes. We will eventually write to a same file. I do not think Kindle is doing a correct thing for this scenario.

I agree Kindle is doing the wrong thing and your approach is better. It sucks that we have to be compatible with a bad design. Amazon probably expects everyone to use their proprietary mobi format, which is very scary.

Then again, two files having the same name but different suffixes is an edge case that's easy for users to manually work around.

> To avoid this issue, we can also use file suffix as the setting file name. I.e. setting of a.pdf would be a.sdr/pdf.lua.

Oh Yes, I was about to mention that :) Although I still think it's more user friendly to add `settings` or `metadata` into the file name so people know what's inside.

**Comment by Hzj-jie** [comment]
OK, we use metadata.{file-suffix}.lua. I will update the CL.

**Comment by houqp** [comment]
Looks good to me. Could you squash them into one commit?

**Comment by Hzj-jie** [comment]
Done.

**Comment by houqp** [comment]
Another nice to have feature is a migration clean up scan, which can be used to remove legacy settings files and configs.

**Comment by Hzj-jie** [comment]
it looks simple, i.e. we can remove any legacy files after line 97 of docsettings.lua.

**Comment by houqp** [comment]
I meant a full scan of all files ;) Maybe something we do automatically by checking previous installed version on startup or make it a button in the menu so users can choose to manually clean up/healthcheck after an upgrade if they want.

**Pull request merged**
