### PR TITLE
InputDialog: insert TitleBar

### PR DESCRIPTION
**Pull request by hius07**
InputDialog, MultiInputDialog, OpenWithDialog, LoginDialog

(1)

(2)

(3)

(4) Before - After

(5)

(6)

(7)

(8)

(9)

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8695)

### CODE REVIEW

**Review by poire-z — APPROVED** [review]

**Comment by poire-z** [comment]
I remember you mentionned some other widgets that could be taller than screen height.
KeyboardLayoutDialogs was one of them, and we fixed this with the new ScrollableContainer.
So, if you remember about others, they could also benefit from it.

**Comment by hius07** [comment]
It is MultiInputDialog in landscape mode (eg Add FTP cloud storage).
The keyboard overlaps ok/cancel buttons, so we need to hide it to press.
Can InputDialog be placed into the ScrollableContainer? Will it be convenient to drag it, having several input boxes?

**Comment by hius07** [comment]
I think the keyboard will go hidden while dragging, so no benefits of the ScrollableContainer.

**Comment by poire-z** [comment]
> Can InputDialog be placed into the ScrollableContainer?

The layout would need to be reworked.
A quick ugly try (not reducing the width of the inner stuff, so the bottom scrollbar) would give this:
image

> Will it be convenient to drag it, having several input boxes?

Drag/scroll doesn't work if you hit inside a inputtext - but it's possible when you long press in between, or if you use the scrollbar.

It's main benefit is that you can ensure the bottom Cancel|OK buttons stays visible and you can reach them when the keyboard is hidden. (I think we wouldn't want it to have the Cancel|OK buttons above the keyboard, otherwise there's not much room to show the inner content, and we would get scrollbars even in portrait.)
And well, people won't see what they type in the bottom inputttexts, while they type. But could go verify after hiding the keyboard.
Well, not that much interested in working on these dialogs I never see :/

**Pull request merged**
