### PR TITLE
Kobo: Overengineer the manual CLOEXEC logic in the Wi-Fi scripts

### LINKED ISSUE #12043: KOReader crashes due to httpinspector when port is already in use
* KOReader version: 2024.04 (latest)
* Device: Kobo Libra 2

Koreader crashes when using [httpinspector plugin](https://github.com/koreader/koreader/pull/11457)

1. Turn on her httpinspector plugin server ( under more tools )
2. Press the power button to sleep the device
3. Press the power button to wake up
4. try to go to the file browser menu from the top panel
--- CRASH ---

##### `crash.log` 
```
06/17/24-16:19:06 DEBUG HttpInspector: Starting server... 
./luajit: frontend/ui/message/simpletcpserver.lua:27: attempt to index field 'server' (a nil value)
stack traceback:
	frontend/ui/message/simpletcpserver.lua:27: in function 'start'
	plugins/httpinspector.koplugin/main.lua:103: in function 'start'
	plugins/httpinspector.koplugin/main.lua:29: in function 'action'
	frontend/ui/uimanager.lua:1012: in function '_checkTasks'
	frontend/ui/uimanager.lua:1460: in function 'handleInput'
	frontend/ui/uimanager.lua:1580: in function 'run'
	./reader.lua:280: in main chunk
	[C]: at 0x000140cd
!!!!
Uh oh, something went awry... (Crash n°1: 06/17/24 @ 16:19:07)
Running FW 4.38.21908 on Linux 4.1.15-00866-g3a75628c73c (#96 SMP PREEMPT Thu Nov 17 14:25:47 CST 2022)
Attempting to restart KOReader . . .
```

### PR DESCRIPTION
**Pull request by NiLuJe**
So it catches non-CLOEXEC sockets properly...

Fix #12043

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12045)

### CODE REVIEW

**Comment by NiLuJe** [comment]
I love dealing with old busybox quirks. -_-".

**Comment by NiLuJe** [comment]
This properly handles #12043 without the LuaSocket-side fix from https://github.com/koreader/koreader-base/pull/1827

```
06/17/24-21:37:00 INFO  Kobo Wi-Fi: enabling Wi-Fi 
[enable-wifi.sh] Left fd 10 -> /mnt/onboard/.adds/koreader/enable-wifi.sh open
[enable-wifi.sh] Left fd 3 -> /proc/8509/fd/3 => pipe:[87178] (temporary?) open
[enable-wifi.sh] Closed fd 9 -> socket:[71402]
```

**Comment by arpanghosh8453** [comment]
@NiLuJe, I tested this ( replaced the 2 changed files in .adds/koreader directory ) and it seems to fix the problem with the port hijacking by wpa_supplicant on my kobo libra 2. The server resumes fine and works as expected. Hopefully this gets merged soon.

Thank you @NiLuJe for fixing this!

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/12045)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @NiLuJe)

**Pull request merged**
