### PR TITLE
send2ebook: fix corrupted files after download

### PR DESCRIPTION
**Pull request by mwoz123**
~~Replace invalid method name~~

pinging @robert00s:
There's an issue opening files downloaded by send2ebook (use ftpApi)
It seems to be fine before refactor https://github.com/koreader/koreader/commit/9e67c5a614121cf6e787f47eca4905f442d5915e#diff-88b29b8ee77109c92f183b724ec7b1be

The sample ebook file downloaded directly from ftp (with nautilus) is 0,2kb bigger (valid zip file) than by send2ebbok (ftpApi), can't open it even using zip.

The same ebook:
[direct download from ftp.epub.zip](https://github.com/koreader/koreader/files/2173065/direct.download.from.ftp.epub.zip) 7,1kb (using nautilus)
[downloaded by send2ebook.epub.zip](https://github.com/koreader/koreader/files/2173066/downloaded.by.send2ebook.epub.zip) 6,9kb

Attachments are epub files but had to add .zip extensions, because git doesn't allow epub files upload. 

@robert00s  Can you help? Any ideas?

### CODE REVIEW

**Comment by mwoz123** [comment]
I'd to replace FtpApi with low level ftp to get rid of corrupted files after download.

**Comment by NiLuJe** [comment]
Never used this, so I can't really say, but this looks benign enough, and apparently can't be worse than before, so, LGTM ;p.

**Comment by mwoz123** [comment]
It's useful when you found (long) article on phone and would like to send it to your ebook reader.

@NiLuJe I'm happy to commend it to you;) 
All you need is [android-send2ebook](https://github.com/koreader/android-send2ebook/tree/master/repo) and [free ftp host](https://www.google.com/search?num=30&client=firefox-b-ab&ei=NBZGW5GqOY_VwQLLrYegDA&q=free+ftp+hosting&oq=free+ftp+hosting&gs_l=psy-ab.3..0i203k1l5j0i22i30k1l5.2004.3042.0.3333.8.5.0.3.3.0.190.688.0j5.5.0....0...1c.1.64.psy-ab..1.7.532...0j0i67k1.0.7UtNZmDwGdI).

I'm thinking about re-writing sender to Javascript so it could be also available to send from PC browsers (plug-in).

**Comment by mwoz123** [comment]
Any other comments on those 2 changed lines?

**Comment by mwoz123** [comment]
thanks

**Pull request merged**
