### PR TITLE
ButtonDialogTitle: remove

### PR DESCRIPTION
**Pull request by hius07**
Not used anymore.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12394)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
There is some risk of affecting the larger ecosystem by messing with widgets, but in this case it should be a very quick fix if any plugins do.

**Comment by hius07** [comment]
koreader/contrib doesn't use it.

**Review by poire-z — APPROVED** [review]

**Comment by Frenzie** [comment]
> koreader/contrib doesn't use it.

We'll automatically give less (if any) attention to plugins not in there through sheer ignorance, and realistically regardless if we want to we're quite limited in how much we could or should care, but many do exist.

But more important, koreader/contrib does actually use it, now that you mention it: https://github.com/zwim/calculator.koplugin/blob/a190773a6c3471a782c93a50aacb5e3bfcfd8fbd/calculatorconvertdialog.lua#L5

Also quick and dirty see [`ButtonDialogTitle language:lua NOT is:fork`](https://github.com/search?q=ButtonDialogTitle+language%3Alua+NOT+is%3Afork&type=code).

**Comment by Frenzie** [comment]
Pinging @zwim, besides https://github.com/xdHampus/ereolen.koplugin I think the rest is just noise.

**Comment by Frenzie** [comment]
That sounds like a good idea. If that works I'd also add a `logger.warn` and call it a day.

**Pull request merged**
