### PR TITLE
add static analysis for Lua

### PR DESCRIPTION
**Pull request by houqp**
First time running static analysis against our code base (only frontend) and I was able to get a lot of interesting feedbacks :)

Most of the errors from luacheck are minor cosmetic stuff. But it did reveal couple real logic errors that can only be caught at runtime. There are still around 300 errors/warnings left unfixed, so if you are interested in cleaning up the code, please go ahead do it. If we were able to get to 0 error someday, luacheck can be added to travis build to guard against regressions. For now,  I suggest every time you make change to a Lua file, run luacheck on it.

### CODE REVIEW

**Comment by chrox** [comment]
This PR needs houqp/koreader#1 to fix unit test of readerbookmark.

**Comment by chrox** [comment]
I tried the `make static-check` and it's really cool! :p

**Comment by hwhw** [comment]
Interesting tool!

**Comment by houqp** [comment]
running it on base/ffi also returns some legit bugs, so we should enable it for koreader-base too :P

**Pull request merged**
