### PR TITLE
Profiles: more auto-exec triggers 2

### PR DESCRIPTION
**Pull request by hius07**
(1) on showing folder
(2) on book opening: if book is in collections
(3) on book closing - same conditions as for opening

On showing folder

On book opening

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12691)

### CODE REVIEW

**Comment by jonnyl2** [comment]
Had a quick test with multiple book opening/closing conditions and it appears that only one of the conditions has to apply for the auto-execution to trigger? As a user I would expect all of them having to apply (e.g., in a collection _and_ a specific path, or in all selected collections, if >1). If only one of them should apply I could just create separate profiles for each criterion.

**Comment by hius07** [comment]
Yes, logical OR is used everywhere.
For "on rotation" and for comma separated patterns it's obvious. For other conditions - made for consistency.

**Comment by hius07** [comment]
Several comma separated patterns can be used in all "if contains" conditions.
Another hint: long-pressing on an item in any level clears entire underlying branch.

**Comment by hius07** [comment]
> An idea for auto-execution: add 'Show as QuickMenu' (e.g., below 'Ask to execute'). Then, a user could be automatically shown the QuickMenu and he could just pick one of the options, or dismiss the QuickMenu.

What's the difference of checking the profile "Show as QM" in the action list?

**Comment by jonnyl2** [comment]
Nothing, I guess. Didn't think about that :/

**Pull request merged**
