### PR TITLE
luasettings: backup previous file and auto-recover

### PR DESCRIPTION
**Pull request by poire-z**
Similar to what was done for docsettings in #3093 (will apply to settings.reader.lua, but also to plugins' own settings).
Had it since after my early MuPDF 1.12 kobo crashes, and it has recovered once when I had wrongly manually edited settings.reader.lua.

### CODE REVIEW

**Comment by poire-z** [comment]
I see on mobileread people having lost their settings.reader.lua on crash.
This PR was supposed to help on that - the previous is saved as .old - and recovered if the main one is corrupted.
And I guess it does help - cause i had no loss for over a year.

But it happened to me last week (cpuloop, before jit.opt tweaks) that both .lua and .lua.old must have been screwed. Possibly because I tried to suspend and resume and suspend, so both were written in a small time span and didn't get flushed to disk.
I don't know if we can do fsync() from lua - or force the kernel to write and sync without delay (would it hurt general usage on SDCards ?)
Or may be we shouldn't recycle the .lua to .lua.old if the .lua has not aged enough. Assuming that the previous .lua is say 3mn old, it must have been flushed to disk - and we can rename it to .lua.old.
Or may be it's just these renames and the directory entries list that get screwed up - and both the settings files would not be found anyway.

Better lose 3mn of settings changes than a lifetime of them :)
What do you think?

**Comment by NiLuJe** [comment]
FAT32 not being journaled, I'm not sure there's actually a silver bullet.

(Note that the reports on MR are somewhat quirkier, because the situation is much more complex on Kindle, where the filesystem we interact with is actually a fuse proxy. Inconsistencies between the fuse proxy and the underlying FS are easy to reproduce, especially when overwriting an existing file).

**Comment by NiLuJe** [comment]
In any case, much like we use & abuse `sync` in startup scripts, that's also exported by the glibc, so it'd be trivial to FFI. Might not help much, though.

**Comment by poire-z** [comment]
Again in #5663.
I'm not sure I understand what's specific about FAT32.
But with linux on ext3+, the content we write might be flushed to disk after 10/20s, while the open/rename of the file in the inode directory is remembered in the journal.
So, if we happen to flush/saveSettings 2 times in these 10s, and have a hard crash/hang, there will be no content to reader after the reboot, as there will be 2 files of 0 size.
https://github.com/koreader/koreader/blob/e8f91ab3997adbdfdbc645be46d51c62b8c8013e/frontend/luasettings.lua#L180-L195

So, on ext2+, a solution would be to use fsync, or to just not touch/rotate that settings to .old if the file we are moving is not older than 1 minute (so we know it has been flushed/synced by Linux) - by just adding a timestamp check on line 183:
- if settings.reader.lua has been modified less than 1 mn ago, keep writting to the same settings.reader.lua - keep the previous older .old as-is
- it settings.reader.lua has not been saved less than 1mn ago, move it to settings.reader.lua.old, and create a new settings.reader.lua with the content

With FAT32, if the diretory items rename is not journalized and if not remembered in case of hang, we might still find the older settings.reader.lua.old.
On ext3, we'll also still get a valid settings.reader.lua.old.

https://github.com/koreader/koreader/blob/e8f91ab3997adbdfdbc645be46d51c62b8c8013e/frontend/luasettings.lua#L27-L41

What do you think?

**Comment by poire-z** [comment]
Or, `os.execute("sync")` at the end of this `LuaSettings:flush()` :)

**Comment by Frenzie** [comment]
> I'm not sure I understand what's specific about FAT32.

Nothing, except as you mentioned it's one of the only non-journaling filesystem still in active use. Add a weird FUSE layer like Kindle apparently does and you've got a recipe for data corruption. With something like ext2/3/4 or NTFS the amount of potential issues is vastly reduced.

> a solution would be to use fsync

Does that do anything in practice that `:flush()` and/or `:close()` don't?

**Comment by poire-z** [comment]
Our :flush() / :close() only do the open()/write()/close() syscalls.
The fsync syscall blocks and only returns when it's written to disk.

```
DESCRIPTION
       fsync() transfers ("flushes") all modified in-core data of (i.e., modi-
       fied  buffer cache pages for) the file referred to by the file descrip-
       tor fd to the disk device (or other permanent storage device)  so  that
       all  changed information can be retrieved even if the system crashes or
       is rebooted.  This includes writing through or flushing a disk cache if
       present.   The  call  blocks until the device reports that the transfer
       has completed.

       As well as flushing the file data, fsync() also  flushes  the  metadata
       information associated with the file (see inode(7)).

       Calling  fsync()  does not necessarily ensure that the entry in the di-
       rectory containing the file has also reached disk.   For  that  an  ex-
       plicit fsync() on a file descriptor for the directory is also needed.
```
Otherwise, Linux delays the flush of what we do with open/write/close, and that can be tuned with:
https://www.kernel.org/doc/Documentation/sysctl/vm.txt
```
dirty_writeback_centisecs

The kernel flusher threads will periodically wake up and write `old' data
out to disk.  This tunable expresses the interval between those wakeups, in
100'ths of a second.
```
(at least, that's what I played with +10 years ago when I wanted to prevent bzzzzz the night when Linux was flushing its own stuff to some noisy laptop rotating hard drive :)

**Comment by NiLuJe** [comment]
The last of bit of the fsync ma page (fsync'ing the directory) is key, and may be non-trivial to actually achieve.

I'm not sure it'll help with FAT32 being a giant POS, but it'll probably be better ;). 

I don't have the code on hand, but making sure to use atomic operations on both sides would help, too: write the new config to a temp file, rename current to backup, rename temp to current. Note that rename cannot cross FS boundaries, so that temp file might need an extra copy to the same FS first, or being created there in the first place.

**Comment by poire-z** [comment]
OK, with https://github.com/koreader/koreader-base/pull/1021, may be we can go with:
```diff
 --- Writes settings to disk.
 function LuaSettings:flush()
     if not self.file then return end
+    local directory_updated = false
     if lfs.attributes(self.file, "mode") == "file" then
-        os.rename(self.file, self.file .. ".old")
+        -- As an additional safety measure (to the ffiutil.fsync* calls
+        -- used below), we only backup the file to .old when it has
+        -- not been modified in the last 60 seconds. This should ensure
+        -- in the case the fsync calls are not supported that the OS
+        -- may have itself sync'ed that file content in the meantime.
+        local mtime = lfs.attributes(self.file, "modification")
+        if mtime < os.time() - 60 then
+            os.rename(self.file, self.file .. ".old")
+            directory_updated = true -- fsync directory content too below
+        end
     end
     local f_out = io.open(self.file, "w")
     if f_out ~= nil then
         os.setlocale('C', 'numeric')
         f_out:write("-- we can read Lua syntax here!\nreturn ")
         f_out:write(dump(self.data))
         f_out:write("\n")
+        ffiutil.fsyncOpenedFile(f_out) -- force flush to the storage device
         f_out:close()
     end
+    if directory_updated then
+        -- Ensure the file renaming is flushed to storage device
+        ffiutil.fsyncDirectory(self.file)
+    end
     return self
 end
```

**Comment by poire-z** [comment]
> write the new config to a temp file, rename current to backup, rename temp to current

A clever _write to temp file and rename_ might shuffle the directory inodes more than just writting to the same file - and add more risk. I'd rather keep it simple, and limit the number of fsync.
I'm not even sure if the `ffiutil.fsyncDirectory()` is really needed, and if it's not adding some uneeded risk.

Just imagining what can happen on a crappy FS like FAT32, as I have no idea how fsync would work on them - so, keeping a "stale" .old, or rotating to it a "stale" settings.reader.lua feels like it would be a more natural solution in case fsync() don't deliver.
(I remember losing settings when my touch layer was not responding, but not the system: no real hang, the power button worked - so I tried to get me out of it with that power button that put me into screensaver, which flush settings - do that a few times, and if it hangs or if you long-press that power button, you may have all 0-bytes settings.)

I dunno if the one or two blocking fsync() above, so 2 or 4 when we'll sync the settings.reader.lua and the book.metadata.lua on quit or document switch can be noticable on really crappy devices - and if we should have an option for people who prefer snappiness to security.

**Comment by poire-z** [comment]
We could also use another default for this:
https://github.com/koreader/koreader/blob/55f3575a10a07dd0c9a70154c901a1f160efba3c/defaults.lua#L197-L198

I use 10. It can be reset to nil in defaults.persistent.lua for those who like risk.
https://github.com/koreader/koreader/blob/55f3575a10a07dd0c9a70154c901a1f160efba3c/frontend/apps/reader/modules/readerview.lua#L923-L940

**Comment by NiLuJe** [comment]
I'd strongly advocate for keeping this to nil by default ;).

**Comment by NiLuJe** [comment]
And, instead, maybe do a sneaky flush during some other user-interaction, like, say, opening the top-menu?

**Comment by poire-z** [comment]
> I'd strongly advocate for keeping this to nil by default ;).

Please do (explain why, that is :)

**Comment by NiLuJe** [comment]
Because I'd prefer it to either not happen at all, or happen during something not reading related.

In 99.99% of the cases, it's going to be overkill.

**Comment by poire-z** [comment]
99.99% overkill like all the fsync we're going to do :)
And even if you and I must often access the menu (I still would not want these fsync to happen each time I open the menu!), some people with an abusive OOM killing Kindle could be immersed in their book, read 100 pages, make many highlights (without ever opening a menu) - and what I'd want to do here will not have done anything (but ok, the docsettings.lua before these 100 pages ago won't be 0-bytes :)

> happen during something not reading related

Why ? I think it's the less intrusive moment to do it :)
(Tested on my Kobo, and these fsync are not noticable.)

It's also done there on nextTick(), not certain if it's before or after the painting and refresh:
https://github.com/koreader/koreader/blob/55f3575a10a07dd0c9a70154c901a1f160efba3c/frontend/apps/reader/modules/readerview.lua#L787-L792

**Comment by NiLuJe** [comment]
True, but, in context, the fsync's make sense.

here, we'r ejust saying, hmm, let's flush the settings.... *now*, more or less on a whim ;).

**Comment by NiLuJe** [comment]
In short, If the default were to be changed, I'd *definitely* want this available and prominently visible in the GUI somewhere.

**Comment by poire-z** [comment]
But why would you want that to be disabled / disable'able ?
Seriously, tell me your reason/thoughts, cause I have no idea :)
- snappiness (I don't notice anything, but could it be noticable on crappy devices?)
- SD/NAND wear (would these 1 or 2 KB writes once every 2 mn have an impact?)
- something else I don't think of?

I don't think it should even be proposed in the GUI, it's not like cosmetics UI flashs, or font size - it's just a matter of avoiding shit and data loss :)
`[x] don't do too much to not lose my settings` ? :)
Was thinking about tweaking that code so it's not done every N pagings, but rather when 5mn has ellapsed since last save - then, you could browse/skim without forcing a save.

**Comment by Frenzie** [comment]
@NiLuJe But an event like ReaderReady is a sneaky one, isn't it? It's the kind of event used for preloading the next page after the current one has finished drawing, so that going to the next page will be snappier. I don't see any difference with closing the menu in that regard.

**Comment by poire-z** [comment]
(`onReaderReady` is just called once, when the book is loaded when the first page is displayed (or about to be) - there, it just setups the `self.autoSaveSettings` function, that will be called at each `onPageUpdate`)

**Comment by poire-z** [comment]
I also tested this on my Android phone: got initially a feeling that switching books was slower - but reverting and back again and reverting - it was not coherent (slower sometimes without the fsync... and snappy with them... so... Android...)
Some timing of these fsync on my android 6 phone shows each fsync takes from 7ms to 15ms.
So, when quick switching books, with the 3 (+2 if rename to .old) fsync, that would make 25ms to 50ms added time blocking on these syscalls. (which always feels a bit sad for something 99.99% useless :)

Also, I feel that on Android it might not really be needed, there's less chance that it hangs or crashs, and we can recover finely if koreader is stuck without needing a hard reboot. So, should these be conditionnal. Or don't bother?

**Comment by Frenzie** [comment]
Emphasis on *like*. ;-)

**Comment by NiLuJe** [comment]
>     * snappiness (I don't notice anything, but could it be noticable on crappy devices?)
> 
>     * SD/NAND wear (would these 1 or 2 KB writes once every 2 mn have an impact?)
> 
>     * something else I don't think of?

A mix of all of the above? ;p.
I just don't like doing stuff for "nothing".
Also, I'm going by the overly optimistic assumption that we shouldn't crash, and if the crash is not ours, but the system's, there's a vague chance this'll actually make it worse.

> Was thinking about tweaking that code so it's not done every N pagings, but rather when 5mn has ellapsed since last save - then, you could browse/skim without forcing a save.

I like it in theory, in practice, eeeh, depends on where exactly it happens ^^.

**Comment by NiLuJe** [comment]
In fact, it's mostly the `onPageUpdate` aspect of this that I object to.

I do agree that ensuring our settings actually make it to disk is A Good Thing. So, y'know, why don't we just flush soon-ish after actually *touching* a setting (or a highlight, or a note, or a bookmark, or whatever).

With an unschedule/schedule dance do that in the next 30 or so second (or something), in order to only ever actually do a single flush in case multiple things are modified in a short time.

AFAICT, that would only leave the reading position as potentially stale, which I'm personally okay with. If that's not okay, just leave the current optional "every n page" madness in for those paranoid people ;).

**Comment by Frenzie** [comment]
Makes more sense to me than writing it continuously.

**Comment by poire-z** [comment]
OK, letting that idea rest for a while.
But continuing arguing for the sake of discussion :) and eventually finding a clever solution.

> Here, we're just saying, hmm, let's flush the settings.... _now_, more or less on a whim ;).

Well, because any crash/hang could happen at _now+1_, _more or less on a whim_ too :)

> I just don't like doing stuff for "nothing". Especially I/O. Especially write I/O.

I'm with you on that. I mean: I am paranoid like you :) And I heavily consider that in all my tech projects.
(When I got my first SSD, with their notion of max writting cycles, I was worried, made calculations, estimated they would serve 4-5 years at my usual rate of things - exagerrated a bit in my calculations - but 4 years later, my 2 SSDs says Health/Life left: 99% and 100%.)

> AFAICT, that would only leave the reading position as potentially stale, which I'm personally okay with. If that's not okay, just leave the current optional "every n page" madness in for those paranoid people ;).

Who is paranoid? Those who don't care about IO write, but just want settings to survive, including the current page they were on when a hang happened - or those who care so much about saving any little IO write possible, because SD/eMMC wear... while being blindly optimistic that shit doesn't happen? :)

We see a crash/hang/settings lost issue every 1 or 2 month - for causes that are probably not ours.
I'd rather not see them, and see once every 5 years a user report: _my SD card failed (or even worse: my soldered eMMC memory died, so my Forma is dead): that's because that stupid KOReader was writting 4KB each 5mn over these 5 years!_ :)

And our Android phones must write to eMMC/SD every minute much more than we could - and nobody really worry (does Android has something internal or in their API to manage/limit that - or is it left to the Apps developers, and so... probably not cared about?)

> Makes more sense to me than writing it continuously.

4KB every 5mn or 10 pages, is that _continuously_? Assuming the current position is something of some value (even if less than a highlight) and that it's worth saving.

> So, y'know, why don't we just flush soon-ish after actually touching a setting (or a highlight, or a note, or a bookmark, or whatever).

Yes, that sounds logical. Unfortunaly, our setting is just a table, that can contain subtables (that we can assign directly), so we can't intercept all "touches".
And I have over the years given advices in PR reviews that `:saveSettings()` costs nothing, it is just assiging a thing to a table, it does not flush, no need to do any complex checks/tests to avoid it (like checking we're not assigning the same value, which we should if we want to avoid an unneeded flush).
So, that would need much work all around, to intercept cleverly, or change the API for saving settings properly, or let code that saveSettings() or assign directly to subtables do call another function to declare a flush is worth it, or set a weight to their setting change (so, need to check if new value != old value) so the flush happen when it's weighty enough (w=1 for page change, w=100 for highlight added or edited...). Not fun, and ugly to add that kind of stuff all around.

> With an unschedule/schedule dance to do that in the next 30 or so seconds (or something), in order to only ever actually do a single flush in case multiple things are modified in a short time.

But the more things are modified in a short time, the more memory has been used, the more things have been shuffled, written,... the more risk of a crash/hang :) So, you're delaying the safeguard while increasing the risk of needing it. But ok, at least, you'll reboot with safe settings from when things were sane :)

So, not easy to intercept, and boring and tedious and not worth it to optimize it that much to save some IOs.
We already flush on book switch/leave, and on sleep/resume, which is fine enough.
I just think a contract like _we do auto-save (even your reading position) every N minutes_, even 15 minutes, _so you won't lose more than N minutes of work/position_, would be nice to have.
I'm personally fine with `DAUTO_SAVE_PAGING_COUNT=10` (and I don't even care much about my book settings :) I just backup my G_reader_settings once in a while).
I understand you're fine with `DAUTO_SAVE_PAGING_COUNT = nil`, and that you trust your device :)
But an other default or behaviour than `nil` is probably best, for users to trust KOReader.

(My GloHD still loses its touch screen twice a month - possibly not our issue, might be some hardware issue, there's some report of that with Nickel too in mobiread - but still, when that happens, I have to be careful to long press power to suspend - and wait 20s for the real sleep to happen - then power press to get it all back. Before I figured that, power pressing multiple times without waiting did not make touch reword, so I ended up very-long-press to power off, and I did lose my settings, 0-bytes files - this would at least _may be_ be prevented with the fsync we're adding.)

**Comment by NiLuJe** [comment]
I don't have the code on hand, but couldn't we simply get by with a dirty
bit somewhere, saying "this table is dirty, flush it when we flush
settings", and clear that bit on flush?

**Comment by poire-z** [comment]
Not automagically.
You'll have to explicitely _say it_ by adding in every method that may or does modify stuff something like `self.ui.dirty_settings = true`, and pass it (or a callback that will do that) to sub  widgets so they do it (or not pass it, and use a global).
Much work and noise, and risk to forget some (and risk for long discussions of what setting is considered important and which are not...) for something that would never or rarely happen :|
(Rather some minor added IO writes than days of our dev time...)

I won't paraphrase the code, but just follow `self.bookmarks` in readerbookmark.lua (where `:onSaveSetting()` is a no-op, as `self.bookmarks` is the same (same reference) table as `self.ui.doc_settings.data["bookmarks"]` - so `self.ui.doc_settings:saveSetting("bookmarks", self.bookmarks)` does nothing.
Unlike scalars like `self.xpointer` in readerrolling.lua (and others boolean/integer settings everywhere) that is a value, and needs `self.ui.doc_settings:saveSetting("last_xpointer", self.xpointer)` to actually be copied into docsettings.

**Comment by poire-z** [comment]
Other idea: have dump.lua output a consistent setting-serialized-as-a-string (currently, it does not, things can be randomly re-ordered), or make it build a consistent hash, with a list of keys to ignore (last_xpointer, ...), so we can store and compare strings or hashes before going on a IO writes minor fiesta :)
(and the question becomes: how often to compute that hash and waste cpu cycles :)

**Comment by Frenzie** [comment]
> 4KB every 5mn or 10 pages, is that continuously?

Every few pages is not, or at least not exactly, but every 5 minutes no matter what is indeed continuously.

**Comment by poire-z** [comment]
Also, I'm quite certain many long time users (that have been using KOReader for more than 3 years) do have DAUTO_SAVE_PAGING_COUNT overriden in their default.persistent.lua, because:
- KOReader used to crash more often 3 years ago than it does now, so people had more chance to have met some crash, lose some settings, and found that solution to reduce the risk (only to some extent, but better than nothing)
- 3 years ago, we had many options not available thru menus, and people were pointed to the options to override in defaults.persistent..lua more than they are now, and they looked at what's available in defaults.lua - and when skimming thru the options, seeing that auto-save option might have been a quite obvious one to change, because why not? :)

So, it may be only new users, that have not changed it, than have more risk than old users to lose stuff.
(But my real point is that we are many that have been IO writting every 10 or N pages for more than 3 years, and have not complained of SD wears or lack of snappiness, or losing settings :)

**Comment by NiLuJe** [comment]
The other, obviously simpler solution, is to simply make saveSetting *always* flush ;).

It's not necessarily a good idea, but it should be doable and simple ;p.

Or postpone until #4951, because SQLite would handle all of that mess for us ;).

**Comment by poire-z** [comment]
> The other, obviously simpler solution, is to simply make saveSetting always flush ;).

Not a solution: most `saveSetting()` happen only when we trigger it via `onSaveSettings`, either when switching documents, going back to FM, suspending, exiting, but mostly never while reading.
Most of the time, we don't `saveSetting()`, and just manipulate copies/references we store in each module. (I had suggested in the past stuff about [readSetting](https://github.com/koreader/koreader/pull/3589#discussion_r160784586) and [saveSetting](https://github.com/koreader/koreader/pull/3304#discussion_r143027716), but that's not really relevant.)

> Or postpone until #4951 and/or hell freezes over, because SQLite would handle all of that mess for us ;).

And it's as non-trivial as the other considered "solutions".
And I'm quite sure you would complain if we had SQLite save a 4KB block/page every page turn to commit last_xpointer or last_page - and we'd get into the same discussion of what's important or not, and think about adding kludge to avoid some IO writes - and we'll be at the same point :)

But OK, we have reached the point of the Godwin's law, now that you have invoked #4951 ! :)
So enough with the technical discussion.

**Comment by NiLuJe** [comment]
FWIW, a properly setup WAL makes the I/O aspect fairly interesting: you can push many things to memory instead of disk, to the extent of being able to push [the complete WAL journal](https://sqlite.org/tempfiles.html#tempstore) to memory ;).

Again, not necessarily a fantastic idea, but interesting ^^.

**Comment by poire-z** [comment]
> The other, obviously simpler solution, is to simply make saveSetting always flush ;).

_Obviously_, you haven't looked at the code, and that's fine. Both of us either have little interest in touching our settings handling, and/or are persuaded there is no simple trivial solution.

> Or postpone

And that's the key point: we're postponing, possibly indefinitely. (And personally, I hope we don't touch anything.)

So, **in the meantime**, do we agree to do nothing and :

- keep the default of `DAUTO_SAVE_PAGING_COUNT = nil`, because it's a sane one: new users (literally _losers_) may _lose_ 50 pages of highlights, but we won't be responsible for wearing their device precious SD/eMMC storage.
- continue getting reports like #5563, #5577, #5663, #5676, ignore the lost settings part, and keep adressing only the crash/hang part, shamelessly tagging these issues as "not our bug" and "won't fix" :)

Do we ? :)

(I dunno how much #5678 will really help limiting that kind of issues - but some of them are aggravated because of `DAUTO_SAVE_PAGING_COUNT = nil`.)

**Comment by NiLuJe** [comment]
I'm concerned having it as anything else would make hard-crashes considerably *more* dangerous, because FAT32 is terrible.

Some of the linked issues also happen to be compounded by the fuse insanity on Kindle, for which we can't do much anyway.

That said, I'd be okay with a big fat warning and a GUI toggle, no matter the default.

**Comment by poire-z** [comment]
How would you spell that warning?

**Comment by NiLuJe** [comment]
This made me think of the way this kind of thing is implemented in an Office suite (i.e., auto-save every n minutes), so I'll check how it's worded over there, but basically something along the line of "Rewrite metadata settings to disk every N page. May help prevent losing *new* settings/sidecar data after a software crash, but may cause filesystem corruption and *complete* data loss after a *hardware* crash."

The "hardware crash" part should be platform-specific, as it doesn't apply on basically anything that isn't an eInk eReader (i.e., anything that uses a decent FS, and not FAT32).

**Comment by NiLuJe** [comment]
To recap, I kinda like the current behavior, and I view it as a design decision. It just ought to be documented, as does the fact that it can be overriden. Making that setting visible in the GUI with the proper explanation would address both of those things.

No matter the backend, I *do* wish we'd be a bit more rigorous when handling reading/writing settings, but that's admittedly a much more complex issue ;).

**Comment by poire-z** [comment]
> It just ought to be documented, as does the fact that it can be overriden. Making that setting visible in the GUI with the proper explanation would address both of those things.

OK, you get me, thanks. And I get you :)
I think it should be in minutes rather than N pages: Never / Every 5mn / 15mn / 1 hour - with a sane default of 15mn.
It would still be checked/done in onPageUpdate, so if you stay idle for hours, nothing happens.

I don't mind adding a warning, but that "_may exacerbate the potential for filesystem corruption and complete data loss after a hardware crash_" part of your suggestion sounds quite dramatic :)
Given that we do it at document close / FM opening and at suspend, times where more things happen, and so more chances of bad luck - than once every N minutes in a peaceful reading session :)
(Although it'll fit in a help_text where we can be verbose - but I'll concede on the warning for a default other than Never :)

**Comment by NiLuJe** [comment]
Well, it *is* dramatic when it actually happens ;p.

That said, I've never managed to *actually* trash a FAT32 FS ;).

In the few cases of hard crashes during reading, I've only ever lost the current session's *new* settings (i.e., reading position). Meaning everything working as intended for `DAUTO_SAVE_PAGING_COUNT = nil` ;).

**Pull request merged**
