### PR TITLE
Screensaver: for poweroff, use menu settings with added overlay message

### LINKED ISSUE #3591: Screensaver request
* KOReader version: koreader-nightly-20180110
* Device: All

#### Issue
This is not an issue, more of a feature request

There are some new options for the screensaver which are very nice, but I could not find a way to achieve what I really want.
I 'm trying to have the book's cover as screensaver when the reader is suspended and also when the reader is powered off.
Ideally, it would be very nice to also have a message overlaid stating its state.
As the things are now (I think) I can have options for the suspended state but nothing for the powered off state, where I get a message only.
With the previous release I had the cover as screensaver also when I powered off.
There is also not an option for the cover with a message overlay.
Any thoughts?

### LINKED ISSUE #3610: Sreensaver when I power off doesn't work anymore
* KOReader version: v2015.11-1465-gd201c04
* Device: KA1

#### Issue
I use last book's cover as screensaver. 
It works fine when I put the device to sleep.

But when I power off the device, instead it looks like I get the "Leave screen as it is"-alternative with the "Powered off"-popup window.

### PR DESCRIPTION
**Pull request by poire-z**
Followup to #3572 to have a better default for poweroff/reboot instead of `message`: use the same settings as chosen in menu for Sleep/Suspend, and add to it a small overlay message, so the user can distinguish between suspend (no message) and poweroff (overlay message). (does not work when "Leave screen as is", as we took the shortcut of returning early and not displaying any widget at all).
See https://github.com/koreader/koreader/issues/3610#issuecomment-358059678 (and https://github.com/koreader/koreader/pull/3535#issuecomment-353461264 for the overlay idea,)
Closes #3591. Closes #3610.

Since I made these screenshots, I moved the message to the top right, so it does not hide the bottom widget parts:
<kbd>screensaver1</kbd> <kbd>screensaver2</kbd> <kbd>screensaver3</kbd>

### CODE REVIEW

**Comment by poire-z** [comment]
Use `file_do_cache = false` as we did [before](https://github.com/koreader/koreader/blob/cfaa119c356f43eabe12ea2d04959b70c8d82ed9/frontend/ui/screensaver.lua#L30-L33).
Avoids:
`WARN  too much memory claimed for image|/mnt/onboard/.adds/screensaver_off/Eteint.png|1072|1448`

**Comment by poire-z** [comment]
It has been at 2Mb for years I guess, and it's mostly useful for caching rendered icons from files (which are a few Kb each - on the emulator: 1.2Kb for each top menu icons, 2.3Kb for each chevron). Covers, book images, wiki images are not rendered from files and are not cached. And screensaver images used to have `file_do_cache = false`, and they will get it back with this.
It's also a cache in memory, so we don't want it to become too big.
Don't really know if it needs some increase for higher dpi, guess the icons sizes above could be x9 with extreme scaleByDpi that gives x3, and 100 of them would still fit in.

**Comment by Frenzie** [comment]
> It's also a cache in memory, so we don't want it to become too big.

True, although out of the 512 MB on my device it's a rare occasion that I even approach 200. Perhaps these things should be user-configurable to some degree. For example, I've been thinking about upping my Evince cache limit to 5 GB or so: https://fransdejonge.com/2017/10/fix-minuscule-zoom-limit-in-evince/ Obviously 5 GB couldn't work on my laptop which has a mere 4 GB RAM.

In case you're curious about my proper computer:

screenshot_2017-11-01_21-58-25-fs8

(Actually I'm on kernel 4.14 now, in case it matters.)

If you want to have some fun, run this:

```
for f in /usr/share/neofetch/ascii/distro/*; do neofetch --ascii $f; done
```

**Comment by poire-z** [comment]
I'll add a commit once tested to fix another thing: random dir images are stretched because of a bug in imagewidget, and when solved, the filling of the remaining space is white and should be black (I didn't see that before because on my kobo, I had resized all my images to have the device aspect ratio, so stretching was invisible).

**Comment by poire-z** [comment]
The ImageWidget:new() combination with height and width provided, and a scale_factor = 0 (not nil, for fit to screen keeping aspect ratio) wasn't working: the image was stretched to fit not keeping A/R.
(This combination does not happen anywhere else - it could happen with IconButton, but its users don't do that combination. This change shouldn't have side effects of fixing things that didn't look bogus then :)

Now, just wondering about that `Current book cover settings > Stretch book cover to fit screen` that I insist on keeping (even if I'm not using it):
Shouldn't we make it a generic setting `Screensaver > Settings > Stretch covers and images to fit screen`, so we can move the now single `Exclude this book's cover from screensaver` up a level, and have it replace `Current book cover settings` so it's more easily reachable (I use this one often, when the cover of a wikipedia article sucks).

**Comment by poire-z** [comment]
Last commit is opened for review and removal.

Change `White background in message` to `White background behind message and images`:
With message: unchecked: let book text visible - checked: hide book text with white background
With cover or random image (now that random images are no more streched by default): unchecked: use black bars around image - checked: used white bars (may be preferened depending on the kind of cover/images the user has put into screensaver_dir).

Change per-book setting `Stretch book cover to fit screen` to a global `Stretch covers and images to fit screen`, that applies to cover and random images.
Previous commits fixed bug of random images being always stretched, and they are now with aspect ratio kept by default. This new option would allow a user to get the previous behaviour.

And move `Exclude this book's cover from screensaver` to top screensaver menu, as this is now the only per-book setting.

(I'll rebase the whole thing with a proper commit message in any case)

**Comment by Frenzie** [comment]
I assume the booleans and the settings are correct; no objections to the strings. :-)

**Comment by poire-z** [comment]
OK, properly rebased and ready for merge.

Noticed a small problem (already there before my changes):
https://github.com/koreader/koreader/blob/dd00417bc8ef038ea215be1fa9a93462954e0724/frontend/apps/reader/modules/readermenu.lua#L129-L141
https://github.com/koreader/koreader/blob/dd00417bc8ef038ea215be1fa9a93462954e0724/frontend/apps/reader/modules/readermenu.lua#L185-L190

This trick to populate the main `menu_items.screensaver` make it _carry references_ to `document` and `doc_settings`. When you quit reader and go to filemanager, these are still there (and you can toggle the thing in doc_settings). I guess they will be free'd when you open a new book and the previous item is removed from `menu_items.screensaver` and replaced with a new one with references to the new book's `document` and `doc_settings`. (Not sure if the document is properly closed and freed before that and the reference is nil, or if because of that, we keep the document opened...)
I have no real idea on how to make that cleaner.

**Comment by robert00s** [comment]
I also have problem with that :(
Look that `Exclude this book's cover from screensaver` is greyed out in Filemanager menu because that `not (self.ui == nil or self.ui.document == nil)` is false

**Comment by poire-z** [comment]
Well, there was simple solution: just let ReaderMenu remove what it added in its onCloseDocument.
So, it's no more visible in FileManager menu, and references are cleaned.

**Comment by robert00s** [comment]
Great :+1:

**Pull request merged**
