### PR TITLE
Gesture to show only config menu

### PR DESCRIPTION
**Pull request by robert00s**
In some cases config menu is hidden by reader menu. 

screenshot 2017-08-04 12-47-10

Useful should be gesture to show only config menu. I implemented it
When we swipe from down to up in menu zone we get config menu.

screenshot 2017-08-04 14-08-28

### CODE REVIEW

**Comment by Frenzie** [comment]
Code-wise I think adding just a couple of lines is quite elegant but UX-wise I wonder if it might be better to add this gesture at the bottom?

**Comment by robert00s** [comment]
Gesture at the bottom sounds good but adding new tap zone complicated settings.
In my opinion it is better to leave as it is :)

**Comment by Frenzie** [comment]
Maybe some second opinions? Pinging @Eduardomb22 @KenMaltby

**Comment by KenMaltby** [comment]
Well, it has been established that the down flick from the top of the screen brings down the top menu.  It seems consistent if the bottom menu could be pulled up by a flick from the bottom of the screen.  In both cases the affected area of the screen would have coexisting tap and slide gestures.  The top menu would have to rise to make more room for the expanded bottom menu.  Consistency helps foster an intuitive/expected feeling for the user controls.  {end of pontification}

Luck;
Ken

**Comment by Frenzie** [comment]
I definitely agree with that. Swipe from the bottom to bring up stuff from the bottom, from the left to bring in stuff from the left, etc.

**Comment by robert00s** [comment]
So I will use DTAP_ZONE_CONFIG. I'll change default values to:
DTAP_ZONE_CONFIG = {x = 1/8, y = 7/8, w = 3/4, h = 1/8}

**Comment by Frenzie** [comment]
Sounds okay but I haven't checked in the code. :-)

**Comment by Frenzie** [comment]
This PR addresses a complaint lodged in this video review (hat tip @ersi)
https://youtu.be/i2oSOeAnD10?t=1m20s

**Comment by Frenzie** [comment]
@robert00s While using this I noticed that panning still occurs. Cf. #2809.

**Comment by Frenzie** [comment]
Another thing, could also you make it so that swipe down on the bottom menu closes it? Also see what I did for the top menu: https://github.com/koreader/koreader/pull/2761/files#diff-200e39a7a76e64783d1d2c16a6d7c01eR592

**Pull request merged**
