### PR TITLE
HTML dict: enable color rendering and per-dict user fix html func

### PR DESCRIPTION
**Pull request by poire-z**
- Enable Mupdf color rendering in HtmlBoxWidget.
- Fix possibility of crash in HtmlBoxWidget:free() (I don't think a crash can happen with the current master code, but I have some work in progress that uses more free() to prevent memleaks and I had some crashes there, so let's fix it now).
- Allow for user's hooks for HTML dict to tweak/fix the bad HTML of some dicts, by allowing users to put a LUA function in some file named as the .ifo with a .lua extension (https://github.com/koreader/koreader/pull/3573#issuecomment-355848649)

With a painfully crafted [PetitRobert2007_1.1.lua](https://github.com/koreader/koreader/files/1615366/PetitRobert2007_1.1.lua.txt), I managed to turn this:
robert2007bof
(the HTML returned is really really bad, full of errors and inconsistencies)

into:
robert2007html

Too bad I won't be using it, as it turns out this PetitRobert2007 does not return all definitions (ie, you get `2. Critique`, the 2nd definition for word critique, that suggest to go see `1. Critique`, but you never get it in the results...) edit: just realized the PetitRobert2003 returns the `1. Critique` but not any `2. Critique` ... so it's either a bug when these 2 dicts were made, or something in sdcv...
edit: ok, it's a sdcv bug already reported in https://github.com/Dushistov/sdcv/issues/30

(The collect/serialize to fix HTML tags balance I used in this file seems OK, but there's many chances that it won't work as is and need individual tweaks - so I don't think we can and should make use of it as an alternative to htmltidy by default for all HTML output that Mupdf woudln't like).

(@Frenzie : you can release this morning's builds without this with no problem.)

### CODE REVIEW

**Comment by Frenzie** [comment]
I'm not entirely sure that I can just yet. :-P

On my H2O I found I wasn't able to scroll, even though it's working on the emulator.

**Comment by poire-z** [comment]
Confirmed: scrolling with swipe does not work in scrollhtmlwidget (I scroll with tap mostly). It does not scroll for me either in the emulator.
Small typo (a natural/visual half-conscious corretion I guess). Easy to fix:
```
     if Device:isTouchDevice() then
         self.ges_events = {
-            SwipeScrollText = {
+            ScrollText = {
                 GestureRange:new{
```

**Comment by Frenzie** [comment]
I suppose a separate quickie is better for history.

**Comment by Frenzie** [comment]
Another crash that I figure should theoretically be avoided is the error throwing, i.e., sticking it behind an `if dbg.is_on then` and doing something a little more user-friendly otherwise.

https://github.com/koreader/koreader/blob/8c897a086f88fa5e7d00ef51d5f65cc942479202/frontend/ui/widget/htmlboxwidget.lua#L52-L54

But that's more of a hypothetical thing. Since I'm not completely sure what the best friendly thing to do is, other than not closing the program[1] I won't throw in a quickie for that one and I won't let it hold up anything tomorrow. ;-)

[1] Retry yet again with known good HTML saying something about an error? Close the widget and show some kind of InfoMessage instead? Leave it white with an InfoMessage? Some other option?

**Comment by poire-z** [comment]
I don't really know.
But I assume that with the html to plain text conversion just done before, there's no real reason for it to fail (except for other things like not enough memory, etc...), so we should be fine.

**Comment by poire-z** [comment]
Sharing the html fix funcs I made for the 3 HTML french dicts I have (to be put alongside the .ifo and renamed as it with a .lua extension instead of .ifo):
[PetitRobert2007_1.1.lua.txt](https://github.com/koreader/koreader/files/1673134/PetitRobert2007_1.1.lua.txt)
[PetitRobert2003_v4.lua.txt](https://github.com/koreader/koreader/files/1673135/PetitRobert2003_v4.lua.txt)
[XMLittre.lua.txt](https://github.com/koreader/koreader/files/1673136/XMLittre.lua.txt)

**Comment by poire-z** [comment]
Yes, some XML which is not fully HTML. For example, in my .lua:
```
    html = html:gsub('<big>', '<span style="font-weight: bold; font-size: 1.1em">')
    html = html:gsub(' foreground="', ' style="color: ')
```
(+ some other cosmetics changes for my taste, like replacing colors with smaller italic fonts, etc...)
(But I'm not not sure I didnt explicitely changed `sametypesequence=x` to `sametypesequence=h` - so it may by default displays as text.)

**Comment by Frenzie** [comment]
Hm, how old is that dictionary? It's being continuously corrected, although it looks like it remains an XML version of ye olde Littré, see [here](https://bitbucket.org/Mytskine/xmlittre-data/commits/branch/master).

Is there a script somewhere that automates the conversion from the XML Littré source to stardict? There's https://bitbucket.org/Mytskine/xmlittre-web but I'm not seeing any XSLT in that repo.

https://www.littre.org/faq

Anyway, just something that one could consider as a lunch or breakfast project. :-P

**Comment by poire-z** [comment]
Oh, didn't know that. Files in mine are dated from 2006 :)

**Comment by Frenzie** [comment]
Those curious could investigate whether https://github.com/leafo/web_sanitize could be of any use. Although its purpose is to sanitize (i.e., from scripts and styles), it seems to handle unclosed inner tags. It's a fair bit smaller than libtidy. :-P

It depends on LPeg, but we already include that for lua-Spore.

**Comment by mtlive** [comment]
Note that MuPDF support for xhtml is limited.
For example it doesn't display some items nested in <table>, even though validated by tidy.

**Comment by mtlive** [comment]
I write a lua script to [test if it is possible to] correctly render persian/arabic strings in definitions, but per my tests koreader even doesn't load my script. May you help me please?
[persian.lua.txt](https://github.com/koreader/koreader/files/3108196/persian.lua.txt)

**Comment by Frenzie** [comment]
MuPDF should already do that?

If you're talking about the KOReader GUI elements they don't, but I'd probably look into leveraging HarfBuzz.

https://github.com/luapower/harfbuzz
https://github.com/luapower/harfbuzz/blob/a4fa5884950166248b78d768eb806bb413ef4cdf/harfbuzz_demo.lua#L162-L163

(Also: https://github.com/ufyTeX/luaharfbuzz)

> per my tests koreader even doesn't load my script

You didn't say what you're trying to load and use it.

**Comment by mtlive** [comment]
> MuPDF should already do that?
No it doesn't. Letters are seperated and left to right.
Currently I'm working on fixing dictionary results. But regarding rendering books, harfbuzz and mupdf are painfully slow and generated results aren't useful. 
I'll post more details tomorrow.

**Comment by Frenzie** [comment]
> No it doesn't.

What exactly is it that it doesn't do in what scenario? See, e.g., https://github.com/koreader/koreader/issues/1426#issuecomment-371469777

**Comment by mtlive** [comment]
I found the reason, the script is run only when the dictionary .ifo has sametypesequence=h . But unforunately MuPDF displays persian characters as ▯, while without MuPDF at least characters are displayed.
> What exactly is it that it doesn't do in what scenario? 
Here are the screenshots:
Plain text dictionary: 
farsi-plain
HTML dictionary:
farsi-html

**Comment by Frenzie** [comment]
That could be an issue somewhere in how we build or use MuPDF. I'm reasonably sure it's supposed to fall back to Noto.

**Comment by mtlive** [comment]
I even tried to set the font explicitly through css but it seems that MuPDF doesn't respect the font-family attribute at all. (verified on PC)

**Comment by Frenzie** [comment]
Setting it where and how? If you're testing MuPDF I would stick to the basics (e.g., a simple XHTML file) without complicating matters through the dictionary. ;-)

If you want to test the dictionary, see, e.g.:

https://github.com/koreader/koreader/blob/812e595608fcb4d7d6e7ac87fb221942fc15af8b/frontend/ui/widget/dictquicklookup.lua#L173-L184

Which makes it really weird that we're seeing undefined characters; maybe it's actually some issue in the sdcv output or how it's passed on?

It definitely listens to the font there, because otherwise you'd be seeing some serif typeface instead of Noto Sans. :-)

**Comment by NiLuJe** [comment]
My guess is that output is plain garbage, and not MuPDF failing to display farsi ;).

**Comment by mtlive** [comment]
tried a css with ```
@page { 
             margin: 0; 
             font-family: freeserif; 
         } 
```
Now farsi characters are displayed as free space (or nothing!). I'm sure that characters are there, because when I touch and hold on them koreader will seek for their definition and displays them there.

**Pull request merged**
