### PR TITLE
Enable Cover-Image on Remarkable and PocketBook

### PR DESCRIPTION
**Pull request by zwim**
Please see https://github.com/koreader/koreader/issues/6899 and https://github.com/koreader/koreader/issues/6899#issuecomment-732664106

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/6906)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Oh, cool, thanks for taking care of that ;).

Would you mind folding https://github.com/koreader/koreader/issues/6899#issuecomment-732664106 in there?

**Comment by NiLuJe** [comment]
I meant the actual code ^^.

**Comment by zwim** [comment]
@NiLuJe: I did not want to include "your" code in my commit.

**Comment by NiLuJe** [comment]
It's trivial enough, and I would have said so if it bothered me (it doesn't), but thanks ;).

**Comment by zwim** [comment]
> It's trivial enough, and I would have said so if it bothered me (it doesn't), but thanks ;).

So is the `and not Device.isRemarkable()` ;-)

**Review by NiLuJe — APPROVED** [review]

**Comment by zwim** [comment]
Also enable on PocketBook, as bmp-support is ready now.

**Pull request merged**
