### PR TITLE
WIP: Kindle Scribe hardware rotation

### PR DESCRIPTION
**Pull request by mergen3107**
Trying to re-implement fixes discussed in https://github.com/koreader/koreader/issues/11269#issuecomment-1998736063

Work in Progress. I mainly created this PR to be able to quickly show and ask about steps I tried.

Maybe this PR will become a good one in future?

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11809)

### CODE REVIEW

**Comment by mergen3107** [comment]
Didn't achieve much progress today. To be continued :D

**Comment by mergen3107** [comment]
I played around yesterday with Kindle Scribe Init and KindleTouch:Exit(), but I found out that Generic Device Init is in the way.

My goal with these optimization is to force Kindle SW and HW rotation to canonical upright Portrait ("0" in SW, "3" in HW) upon every cold start. This will make sure that the swipe directions are setup correctly each time.

However, Generic Device Exit saved the last rotation upon exit or restart which Generic Device Init then restore to upon fresh start or restart. 

1) Is there a way to let Generic Device Init know that this is a restart and not a fresh start? This has worked great to pass through between Generic Device Exit and KindleTouch Exit, but I couldn't make it work between Generic Exit and Generic Init.

2) If so, may I guard that code with "if not restart" so that it doesn't restore rotation if it's a fresh start?

If the answer is no and you guys wouldn't like to change Device Init (because it is common for all devices), then that's probably OK. I am happy as long as my end result doesn't have touch and UI rotations misaligned.

Thanks!

**Comment by mergen3107** [comment]
(Commits aren't up to date with my experiments yet, so please don't review yet)

**Comment by mergen3107** [comment]
Same as here:
https://github.com/koreader/koreader/issues/11265#issuecomment-2146234697

**Comment by Frenzie** [comment]
Any relation to https://github.com/koreader/koreader-base/pull/1719

**Comment by mergen3107** [comment]
@Frenzie 
Sort of :D I close that one too, because I got a Kindle Scribe case that enforces `U` orientation.

**Pull request closed without merging**
