### PR TITLE
Fix stats in cre scroll mode

### PR DESCRIPTION
**Pull request by poire-z**
Too-quick fix in #3304, corrected. Thanks @robert00s !

### CODE REVIEW

**Comment by robert00s** [comment]
Guys you are so fast :)
I think we need add something like that to prevent addin the same page in row eg 45 > 45 > 46 > 48:

```
function ReaderStatistics:onPosUpdate(pos, pageno)
    if self.curr_page ~= pageno then
        self:onPageUpdate(pageno)
    end
end
```
I prepare fix soon...

**Comment by Frenzie** [comment]
Apologies, I thought you previously said that wasn't an issue. :-)

**Comment by robert00s** [comment]
I notice it today :)
It's not bug but we don't need save row pages in DB.

**Comment by poire-z** [comment]
Could this happen in page mode too ?
Btw (I'm not a heavy stats watcher), how does it deal with geometry/font/styles changes, when for example you increase font size, and you jump from being on page 42/120 to being on page 47/135? Are the stats bad, or it doesn't matter as it just counts page, whatever the size or number?

**Comment by robert00s** [comment]
> Could this happen in page mode too ?

Not unless you changegeometry/font/style

> Btw (I'm not a heavy stats watcher), how does it deal with geometry/font/styles changes, when for example you increase font size, and you jump from being on page 42/120 to being on page 47/135? Are the stats bad, or it doesn't matter as it just counts page, whatever the size or number?

Stats are "bad" (but only pages). It's difficult to recalculate pages.
It's like a book in the middle suddenly had a larger/smaller font.

**Pull request merged**
