### PR TITLE
Filemanager: enhance file operations dialogs

### PR DESCRIPTION
**Pull request by hius07**
Discussion and screenshots: https://github.com/koreader/koreader/issues/7554

Wordings;
Distinguish ffiles and folders;
Deny blank input.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7582)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
lgtm

**Review by poire-z — APPROVED** [review]

**Comment by Frenzie** [comment]
Whoops, I overlooked that this is breaking some tests. I'll take a look at it this weekend but feel free to beat me to it.

**Comment by NiLuJe** [comment]
@Frenzie: Unrelated, that's just the usual random Gutenberg timeouts :/.

**Comment by NiLuJe** [comment]
I'll see if I can fudge the timeouts in the test suite, actually.

**Pull request merged**
