### PR TITLE
Don't pass a NULL to SetSubtaskInfo

### PR DESCRIPTION
**Pull request by Grubuntu**
Fixes a blocking problem when closing Koreader on some older pocketbook devices : https://github.com/koreader/koreader/issues/8053#issuecomment-897496109

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8087)

### CODE REVIEW

**Comment by NiLuJe** [comment]
If someone can actually dig up even a beginning of documentation for that particular InkView function, that would be neat; otherwise, I have no idea what this is even supposed to do, so, I guess I'll take potentially breaking that over crashing?

----

(Test failure is unrelated: OPDS timeout again).

**Comment by Grubuntu** [comment]
I haven't found any documentation about "SetSubtaskInfo" :(

If I remove this line in device.lua :  _inkview.SetSubtaskInfo(inkview.GetCurrentTask(), 0, title and (title .. " - koreader") or "koreader", fn or "[nil]")_  after switching off the device , at the next boot Koreader is not directly launched (unlike the usual behaviour). 

On Pocketbook, there is a task manager, I think "SetSubtaskInfo" write this task in memory for run it at the next boot. 

But I don't know if you should write:
or "[nil]"
or "nil"
or any other syntax...

the first one works (--or "[nil]"--) on my device but I don't know which LUA syntax is better.

**Comment by NiLuJe** [comment]
> But I don't know if you should write:
> or "[nil]"
> or "nil"
> or any other syntax...
> 
> the first one works (--or "[nil]"--) on my device but I don't know which LUA syntax is better.

It's irrelevant as long as it's not an actual Lua `nil`, but a string instead. (i.e., I'd wager `"nil"` would do just as well, or, hell, even an empty string: `""`).

**Comment by Frenzie** [comment]
> the first one works (--or "[nil]"--) on my device but I don't know which LUA syntax is better.

None of those are Lua; it's just a string. ;-)

**Comment by Grubuntu** [comment]
You are right, I guess it's better to replace string "[nil]"  by ""

inkview.SetSubtaskInfo(inkview.GetCurrentTask(), 0, title and (title .. " - koreader") or "koreader", fn or "")

**Comment by Frenzie** [comment]
@Grubuntu Did you change your mind?

**Comment by Grubuntu** [comment]
I think it is perhaps better to delete only the line 756 in reader.lua, because  SetSubtaskInfo function doesn't accept NULL
https://github.com/ezdiy/arm-pocketbook-linux-gnueabi/blob/master/sysroot/usr/include/inkview.h
`int SetSubtaskInfo(int task, int subtask, const char *name, const char *book);`

https://github.com/koreader/koreader/blob/611a5311b69b0633ed6dfc7202244f42f93a7d33/frontend/apps/reader/readerui.lua#L753-L759

Is this syntax correct ? : 'Device:notifyBookState(nil, nil)' , I don't believe it.
I don't know how this function could work as the parameters are NULL in this case.

There is another line with this function which works fine because the parameters are passed correctly:
https://github.com/koreader/koreader/blob/611a5311b69b0633ed6dfc7202244f42f93a7d33/frontend/apps/reader/readerui.lua#L630-L638

Removing this line works on my device but more pocketbook owners need to test this change.

**Comment by NiLuJe** [comment]
The fact that the function takes a pointer to constant string data doesn't necessarily means that it doesn't handle NULL pointers.

Now, the truth is, many standard `<string.h>` do indeed explicitly forbid passing a NULL pointer as a source string. On modern systems, that's made explicit thanks to GCC's `nonnull` function attribute.

----

Now, obviously removing the InkView call works, but it also breaks the functionality (whatever it actually is ;p).

Someone with a PB and a recent device will just have to check what happens when we pass a non-NULL bogus book  as the final argument (e.g., "" or "nil" as mentioned earlier).

**Comment by Grubuntu** [comment]
As the function "Device:notifyBookState(nil, nil) " is not use with the goods parameters, there are several ways to solve the problem:


-1) replace line 267 in koreader/frontend/device/pocketbook/device.lua 
`inkview.SetSubtaskInfo(inkview.GetCurrentTask(), 0, title and (title .. " - koreader") or "koreader", fn)` by `inkview.SetSubtaskInfo(inkview.GetCurrentTask(), 0, title and (title .. " - koreader") or "koreader", fn or "")` 
to avoid to pass the forbidden NULL value...

OR
-2) remove the call to  function `"Device:notifyBookState(nil, nil)"` in koreader/frontend/apps/reader/readerui.lua, it simply avoid crash but also remove function...

OR
-3) switch local variables "document" and and "title" to global variables : 
line 603 : replace `local document = DocumentRegistry:openDocument(file, provider)`  by `document = DocumentRegistry:openDocument(file, provider)`
line 630 : replace `local title = reader.document:getProps().title` by `title = reader.document:getProps().title`
and correct `"Device:notifyBookState(nil, nil)"`  by ` "Device:notifyBookState(title, document)"`  on line 756 in koreader/frontend/apps/reader/readerui.lua  

In this case the function works (in the same way as line 638 in readerui.lua), it return File and Title when we close Koreader...

Which would be the best ?

**Comment by NiLuJe** [comment]
Definitely 1; we just need someone with a supported PB to see whether it breaks anything else.

**Pull request closed without merging**
