### PR TITLE
[lang] Rename 'Scroll Mode' to 'Continuous'

### PR DESCRIPTION
**Pull request by Frenzie**
The current name causes people to think of scrolling, which is slightly awkward on E Ink. For example, see <https://github.com/koreader/koreader/issues/5166#issuecomment-517771475>.

> But this on LCD, not E-ink where the lag is unbearable, especially if you want to correct any scrolling over/undershoot.

Scroll mode is a misnomer. It should be renamed continuous. I use "scroll mode" as the default, but I seldom or never scroll. Conversely, you can still scroll in paged mode if a page is longer than the screen. As far as I'm concerned if you're scrolling (panning) you may be doing it wrong, but to anyone reading: you do you. ;-)

## Slightly more awkward alternatives
E.g., the wordier `continuous mode` or `continuous display`.

PS I quoted myself from [here](https://www.mobileread.com/forums/showthread.php?p=3803924#post3803924).

### CODE REVIEW

**Comment by poire-z** [comment]
No alternate solution with names for each part of the toggle instead of `on | off`?
(Like `scroll | page` in cre, that I'm glad you didn't change :)
`continuous | paged` ?

**Comment by Frenzie** [comment]
Good suggestion! So then it becomes something like:

`Display: continuous | paged`
`View: continuous | paged`

**Comment by Frenzie** [comment]
> (Like scroll | page in cre, that I'm glad you didn't change :)

Also that's an accident. I didn't realize it was using different words for the same thing. ;-)

**Comment by Frenzie** [comment]
I never minded the `scroll mode` name, but it seems to be a not infrequent misunderstanding that scroll mode implies scrolling. I believe some variation of `continuous` is used by Adobe Acrobat and Evince.

**Comment by poire-z** [comment]
Fine with me.
`continuous` instead of `scroll` is clearer even for cre, except may be for newcomers to follow the code :)
(Adds a bit of unbalance to the buttons' texts' widths, the large `continuous` vs the small `page`.)
I don't really like "paged", but you kept "page" so I'm fine - but `adjective | name` feels ok?

**Comment by Frenzie** [comment]
It could also be `per-page` or something.

**Comment by NiLuJe** [comment]
`paginated`?

**Comment by poire-z** [comment]
> `paginated`?

I prefer the unbalance to that one :)

**Comment by NiLuJe** [comment]
Fair enough, both are fine with me ;).

**Pull request merged**
