### PR TITLE
Add spaces to Letters time format when non-compact, remove lead 0s

### PR DESCRIPTION
**Pull request by melyux**
Implements previous discussion at https://github.com/koreader/koreader/pull/9924#issuecomment-1435166341 by adding spaces between the days, hours, minutes, and seconds (@poire-z). When using the `compact` argument, the spaces will not be used.

In addition, noticed that the "removing leading zeros" contract of the `compact` argument is not met by the Letters format, and leading 0s don't look good anyway with this format (`1h 03m 27s` vs `1h 3m 27s`), so I removed these leading zeros entirely when using this format.

Previously: `1d03h38m`
Now: `1d 3h 38m` normally, `1d3h38m` when compact

Previously: `1d03h38m05s`
Now: `1d 3h 38m 5s` normally, `1d3h38m5s` when compact

Added unit tests, as well as unit tests for the existing `withDays` functionality. Also made the `d` letter for "days" into a translatable string like `h` `m` and `s` already were.

--

I can't confirm if the unit tests pass; running the `front` tests gives me this error in the Docker development environment:
```
[----------] Running tests from ./spec/front/unit/datetime_spec.lua
SDL2 not loaded:	libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
frontend/device.lua:58: Could not find hardware abstraction for this platform. If you are trying to run the emulator, please ensure SDL is installed.

stack traceback:
	frontend/device.lua:58: in function 'probeDevice'
	frontend/device.lua:61: in main chunk

[----------] 0 tests from ./spec/front/unit/datetime_spec.lua (12.59 ms total)
```

I thought I ran this a few months ago without trouble. Looks like I have to emulate a device while running the frontend tests? Is there a way to do that?

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10141)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by poire-z** [comment]
> and leading 0s don't look good anyway with this format (`1h 03m 27s` vs `1h 3m 27s`), so I removed these leading zeros entirely when using this format.

I'm not sure I agree :) but I won't insist.
ie. keeping the 0 would somehow keep the parts vertically aligned when in a KeyValuePage (although not using a monospace font, there's already a possible little shifts).

Btw, have you tried using half space, or something ? I fear a regular space can make it harder to read, mostly when it's used in a sentence like the statisitcs plugin (i) popup.

**Comment by mergen3107** [comment]
Yeah, I agree that leading zeros are life savers when: 1) font is monospace; and 2) things need to be row-by-ro, so these values can be vertically aligned. 

So why not getting leading zeros back and making key-value page’s values in monospace?

**Comment by Frenzie** [comment]
> making key-value page’s values

I hope you only mean for this highly specific type of value. ;-)

**Comment by mergen3107** [comment]
Yes, only where it makes sense to have things aligned (e.g., Book statistics)

**Comment by poire-z** [comment]
> Yeah, I agree that leading zeros are life savers when: 1) font is monospace; and 2) things need to be row-by-ro, so these values can be vertically aligned.
So why not getting leading zeros back and making key-value page’s values in monospace?

Because we're not _that_ row-by-row :) There may be 3 dutations on top of one another, but the other fields are plain counts, and sometimes words - so monospace if a bit excessive :)
The `:` or `'` or the spacing added by this PR should be enough to read easily most of these durations.

**Comment by melyux** [comment]
For the key value pages, the 0s do align them a bit, but at the same time I don't want them in the footer status bar and screensaver. On its own, `2h 9m` looks better than `2h 09m`. Personally don't think the alignments are worth sacrificing the aesthetics of the base case, but if there's a way to have both, that would work... And I just thought of one

What if we used half spaces + padded the numbers with half spaces instead of 0s? Keep the alignment without the ugly leading 0. Going to try it

**Comment by mergen3107** [comment]
> so monospace if a bit excessive :)

If you say so :) I only thought that after this PR (#9904) when things got aligned on right, it is only a matter of time to apply monospace font.

**Comment by poire-z** [comment]
> What if we used half spaces + padded the numbers with half spaces instead of 0s? Keep the alignment without the ugly leading 0. Going to try it

I don't think I'll like that, we'll get inconsistent spacing, which will be more confusing than aligning :)

**Comment by melyux** [comment]
> > What if we used half spaces + padded the numbers with half spaces instead of 0s? Keep the alignment without the ugly leading 0. Going to try it
> 
> I don't think I'll like that, we'll get inconsistent spacing, which will be more confusing than aligning :)

Yeah I tried it, and while it looks more or less okay, the half space being smaller than a digit makes it not really do what I was hoping for

times

Alignment's cool and all, but the current code also messes it up whenever the seconds or minutes are 0 (like above) by only giving them one digit 0 and not padding it like 00 like we do with other single digit numbers like 07. Plus we're not using monospace anyway. I do get the nicety of the alignment in some contexts, but not as much as I dislike the leading 0 in most of the contexts

**Comment by poire-z** [comment]
It's _your_ new "letters" format, so go with how you like it.
I can always revert to "classic" if I really get bothered by not seeing 0s.
(Or you'll be asked to add a l0tt3rs mode.)

**Comment by melyux** [comment]
@poire-z No harm in having trillions of formats :)

Btw any help with running the frontend tests? See the end of the first post

**Comment by Frenzie** [comment]
Did you already try `kodev activate` first (or some of the commands therein)?

**Comment by melyux** [comment]
I did try `./kodev activate` first, but same error with and without it. Here's the workflow:

```bash
$ git clone https://github.com/melyux/koreader.git
$ sudo docker run -v $(pwd)/koreader:/home/ko/koreader -it koreader/kokindle:0.2.3 bash
~$ cd koreader && ./kodev fetch-thirdparty
~$ ./kodev activate
$ ./kodev test front
```

Output after that:
```
fatal: No names found, cannot describe anything.
************ CMAKE_MAKE_PROGRAM: "/usr/bin/ninja" **********
fatal: No names found, cannot describe anything.
```
etc.

Then the error in the first post

**Comment by Frenzie** [comment]
>  koreader/kokindle:0.2.3 bash

That doesn't contain the test tools. You'd need to use something based on koreader/kobase:0.3.0 or the old koreader/koappimage:0.1.8.

**Comment by poire-z** [comment]
There are 2 occurences of "hairline" in the comments, where you probably meant "hair space" :)
Good to go ?
Any more detailed single commit title (and message?) than 
`Duration format: add spaces to Letters format when non-compact, remove lead 0s`
(`lead 0s` ? or `lead zeros` ? 0s can read as "0 seconds" :)

**Comment by melyux** [comment]
Done, I think I was trying to describe the process as making it "hairline", but clarified it accordingly

How about for title `Duration format: Add spaces, remove lead zeros for Letters`?

For the message, we could say:
* Add spaces between d/h/m/s
* Remove lead zeros
* Make letter `d` for days translatable
* Make thinspace into hairspace when compact
* Adjust unit tests for new formatting
* Add unit tests for compact
* Add unit tests for days (`withDays` = true) in all duration formats
* Fix descriptor of `secondsToHClock()` unit tests

**Comment by poire-z** [comment]
Thanks (I trimmed the unit tests details, cause not really interesting when browsing commits).

**Pull request merged**
