### PR TITLE
Add missing urw fonts and fix unit test

### PR DESCRIPTION
**Pull request by chrox**

### CODE REVIEW

**Comment by chrox** [comment]
Someone who watches Travis success of this PR could merge this, otherwise the OTA server will spread broken update for all platforms in 8 hours.

**Comment by houqp** [comment]
Are we using the script from koreader-misc to build release in OTA server?

**Comment by NiLuJe** [comment]
@houqp: I'm assuming not exactly, since the copy in the repo doesn't build anything for PB devices ;).

But that's basically it in general terms, I think, yeah, if I remember what @chrox tolds us the ast time that came up w/ the OTA mirrors talk.

**Comment by houqp** [comment]
Good point. I am thinking of adding unit test check on OTA build to prevent from releasing broken builds.

**Comment by chrox** [comment]
Unit test on nightly build server solves this problem perfectly. :+1:

**Pull request merged**
