### PR TITLE
(Hopefully) minor Kobo tweaks

### PR DESCRIPTION
**Pull request by NiLuJe**
* Pixel-perfect H2O viewport
* Kobo startup scripts cleanups (supercedes #1503) [cf. that issue for my rant about the nickel issue worked-around w/ 6c1681b, I'm open to ideas]

And, because it's been a while since I've broken stuff on that front:
* Switch a few widgets to the "ui" refresh type, to behave better on REAGL devices.

Depends on base#322

Tested on a PW2 & a H2O

### CODE REVIEW

**Comment by NiLuJe** [comment]
Keep in mind that I don't use KSM nor advboot, so if someone can check that the startup scripts don't utterly obliterate something in those cases, please do ;).

**Comment by NiLuJe** [comment]
Okay, no idea if switching to a less-stupid-in-this-circumstance SSH over USB session (instead of SSH over WiFi), or the latets few tweaks did it: but restarting nickel works properly on my device. Wheee.

**Comment by chrox** [comment]
Nice! Merging this now...

**Comment by Markismus** [comment]
Man, this is a lot. I quit reading after `minor pass of cleanup of the Kobo scripts`. Lot of work done, nice!

**Pull request merged**
