### PR TITLE
Fontlist: disable/enable some Kindle fonts

### PR DESCRIPTION
**Pull request by hius07**
Some Kindle system fonts cannot be registered and cause errors in crash.log.
Disabling them, and enabling one good font.
Tested on PW4, Voyage, Oasis.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8233)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Can't judge, looks sane.

**Comment by hius07** [comment]
Also https://github.com/koreader/koreader/issues/8228#issuecomment-922335608.

**Comment by NiLuJe** [comment]
The helvetica ban was necessary, but it's a bit weirder as it only applies to a certain range on FW versions, IIRC.

**Comment by hius07** [comment]
> helvetica ban was necessary

What are the reasons? It was asked by a user at 4pda, and works fine on Voyage and Oasis.

**Comment by NiLuJe** [comment]
> but it's a bit weirder as it only applies to a certain range of FW versions, IIRC.

;p.

Might be a FW range best experienced by PW1 users, but I wouldn't bet my life on it, it's been a while ;).

**Pull request merged**
