### PR TITLE
Fix translator, enable selected text translation

### PR DESCRIPTION
**Pull request by poire-z**
Update translator.lua to use a still working google translate API (while it works, it may break or be forbidden at any moment - calling that url with `curl` returns 403 forbidden...)
Add a method to show translations (main and alternates) in a TextViewer.
Re-enable "Translate" button in text selection/highlight buttons dialog (the big diff in the buttons setup is just because of indentation, I only replaced `Follow link` with `Translate`, and moved `Follow link` in a conditional below).
Target language can be set with a manually added setting `translator_target_language = "fr"` and will fallback to the UI language (we could have a `Translation settings>` below the Dict and Wikipedia ones if needed - but that would be for another PR).

<kbd>image</kbd>

To get a slot for it, I made the `Follow link` button being added only when it is needed:
<kbd>image</kbd>

<kbd>image</kbd>

<kbd>image</kbd>

### CODE REVIEW

**Comment by AlanSP1** [comment]
It would be enough to use Set target and source language, as you get idea from translate menu, in my opinion.

**Comment by Frenzie** [comment]
Yes, that wording is fine. Depending on the specifics perhaps the simpler `Translate to` and `Translate from` could work?

**Comment by poire-z** [comment]
Thanks, Translate from/to: sounds nice and obvious.

<kbd>image</kbd>

<kbd>image</kbd>

<kbd>image</kbd>

(I put the 104 language names in `_("")` if one wants to translate them - dunno if that will flood transiflex'ers.)
(The languages are ordered by language code - I hesitated giving some "level" to them to make the most popular ones line English, Portuguese... appear first - but who am I to judge ?  so I decided to not discriminate against minorities so we avoid getting some buzz on twitter with a worldwide #MyLanguageToo wave !)

Also removed the target language name in the title, to make room for larger source language names:
<kbd>image</kbd>

**Comment by Frenzie** [comment]
> dunno if that will flood transiflex'ers.)

It would, but personally I'll just do a couple a day. :-P

**Comment by Frenzie** [comment]
I'll add a note on Transifex that they can all be found pre-translated here: https://nl.wikipedia.org/wiki/Lijst_van_ISO_639-codes

**Pull request merged**
