### PR TITLE
Add .codespellrc

### PR DESCRIPTION
**Pull request by Frenzie**
Mostly just a quick test right now. Excluding `ges` (which it thinks should be `guess`) takes care of most false positives. A few files (like Asian keyboards) might need to be excluded completely.

References https://github.com/koreader/koreader/pull/12579#issuecomment-2388916322

<details>

```
frontend/depgraph.lua:117: lenghty ==> lengthy
frontend/httpclient.lua:29: fullfilled ==> fulfilled
frontend/persist.lua:89: clen ==> clean, clan
frontend/persist.lua:90: clen ==> clean, clan
frontend/persist.lua:90: clen ==> clean, clan
frontend/persist.lua:100: clen ==> clean, clan
frontend/gettext.lua:38: overriden ==> overridden
frontend/languagesupport.lua:213: co-ordinates ==> coordinates
frontend/device/gesturedetector.lua:90: persistance ==> persistence
frontend/device/gesturedetector.lua:809: wthout ==> without
frontend/device/input.lua:188: overidden ==> overridden
frontend/device/input.lua:1496: evalutation ==> evaluation
frontend/device/wakeupmgr.lua:141: successfuly ==> successfully
frontend/device/sysfs_light.lua:69: writting ==> writing
frontend/device/sdl/device.lua:188: inital ==> initial
frontend/device/kindle/device.lua:75: theres ==> there's
frontend/device/kindle/powerd.lua:245: fuctions ==> functions
frontend/device/pocketbook/device.lua:55: orientiation ==> orientation
frontend/device/pocketbook/device.lua:173: orientiation ==> orientation
frontend/device/pocketbook/device.lua:284: fo ==> of, for, to, do, go
frontend/device/pocketbook/device.lua:285: fo ==> of, for, to, do, go
frontend/device/pocketbook/device.lua:286: fo ==> of, for, to, do, go
frontend/device/pocketbook/device.lua:287: fo ==> of, for, to, do, go
frontend/device/generic/device.lua:99: corresponting ==> corresponding
frontend/device/remarkable/device.lua:128: proccess ==> process
frontend/document/document.lua:26: orignal ==> original
frontend/document/document.lua:504: exercize ==> exercise
frontend/document/credocument.lua:56: glyphes ==> glyphs
frontend/document/credocument.lua:172: extention ==> extension
frontend/document/credocument.lua:177: compatiblity ==> compatibility
frontend/document/credocument.lua:1064: resetted ==> reset
frontend/document/credocument.lua:1206: wheter ==> whether
frontend/document/credocument.lua:1619: implicitely ==> implicitly
frontend/document/credocument.lua:1908: reseting ==> resetting
frontend/document/credocument.lua:1914: reseting ==> resetting
frontend/document/koptinterface.lua:1382: mached ==> matched
frontend/ui/uimanager.lua:770: suprised ==> surprised
frontend/ui/uimanager.lua:1152: mutiple ==> multiple
frontend/ui/uimanager.lua:1674: re-use ==> reuse
frontend/ui/trapper.lua:182: Resurect ==> Resurrect
frontend/ui/trapper.lua:400: uneeded ==> unneeded, unheeded, needed
frontend/ui/trapper.lua:420: outputing ==> outputting
frontend/ui/trapper.lua:551: ser ==> set
frontend/ui/trapper.lua:603: outputing ==> outputting
frontend/ui/screensaver.lua:690: prevously ==> previously
frontend/ui/bidi.lua:16: aligment ==> alignment
frontend/ui/bidi.lua:65: independantly ==> independently
frontend/ui/bidi.lua:130: fuction ==> function
frontend/ui/wikipedia.lua:57: informations ==> information
frontend/ui/wikipedia.lua:70: informations ==> information
frontend/ui/wikipedia.lua:349: exlude ==> exclude, exude
frontend/ui/wikipedia.lua:388: discreet ==> discrete
frontend/ui/wikipedia.lua:585: othewise ==> otherwise
frontend/ui/wikipedia.lua:1420: usally ==> usually
frontend/ui/wikipedia.lua:1445: existant ==> existent
frontend/ui/viewhtml.lua:311: targetting ==> targeting
frontend/ui/font.lua:32: synthetized ==> synthesized
frontend/ui/font.lua:36: explicitely ==> explicitly
frontend/ui/font.lua:36: synthetized ==> synthesized
frontend/ui/font.lua:171: explicite ==> explicit, explicitly
frontend/ui/font.lua:189: Synthetized ==> Synthesized
frontend/ui/font.lua:229: synthetized ==> synthesized
frontend/ui/font.lua:299: re-use ==> reuse
frontend/ui/font.lua:389: synthetized ==> synthesized
frontend/ui/font.lua:390: synthetized ==> synthesized
frontend/ui/font.lua:416: synthetized ==> synthesized
frontend/ui/font.lua:417: synthetized ==> synthesized
frontend/ui/font.lua:435: synthetized ==> synthesized
frontend/ui/font.lua:441: appropritate ==> appropriate
frontend/ui/rendertext.lua:246: didnt ==> didn't
frontend/ui/translator.lua:147: te ==> the, be, we, to
frontend/ui/translator.lua:714: Ist ==> Is, It, Its, It's, Sit, List
frontend/ui/translator.lua:714: ist ==> is, it, its, it's, sit, list
frontend/ui/translator.lua:774: Ist ==> Is, It, Its, It's, Sit, List
frontend/ui/translator.lua:774: ist ==> is, it, its, it's, sit, list
frontend/ui/translator.lua:795: Ist ==> Is, It, Its, It's, Sit, List
frontend/ui/translator.lua:795: ist ==> is, it, its, it's, sit, list
frontend/ui/language.lua:39: Nam ==> Name
frontend/ui/renderimage.lua:172: explicitely ==> explicitly
frontend/ui/renderimage.lua:254: explicitely ==> explicitly
frontend/ui/time.lua:2: arithmetics ==> arithmetic
frontend/ui/time.lua:229: substract ==> subtract
frontend/ui/time.lua:285: Attemped ==> Attempted
frontend/ui/elements/menu_keyboard_layout.lua:231: apperance ==> appearance
frontend/ui/elements/font-test-sample-default.template:1: ser ==> set
frontend/ui/elements/font-test-sample-default.template:59: prefered ==> preferred
frontend/ui/network/manager.lua:547: succesful ==> successful
frontend/ui/data/onetime_migration.lua:81: algortihm ==> algorithm
frontend/ui/data/onetime_migration.lua:447: excuted ==> executed
frontend/ui/data/koptoptions.lua:668: diretions ==> directions
frontend/ui/data/isolanguage.lua:121: tha ==> than, that, the
frontend/ui/data/isolanguage.lua:153: dum ==> dumb
frontend/ui/data/isolanguage.lua:156: fro ==> for, from
frontend/ui/data/isolanguage.lua:263: fo ==> of, for, to, do, go
frontend/ui/data/isolanguage.lua:336: te ==> the, be, we, to
frontend/ui/data/isolanguage.lua:338: tha ==> than, that, the
frontend/ui/data/creoptions.lua:557: chararacters ==> characters
frontend/ui/data/dictionaries.lua:679: versio ==> version
frontend/ui/data/dictionaries.lua:687: versio ==> version
frontend/ui/data/dictionaries.lua:2000: dum ==> dumb
frontend/ui/data/dictionaries.lua:2120: fro ==> for, from
frontend/ui/data/dictionaries.lua:2512: tha ==> than, that, the
frontend/ui/data/css_tweaks.lua:192: overriden ==> overridden
frontend/ui/data/css_tweaks.lua:687: heigh ==> height, high
frontend/ui/data/css_tweaks.lua:1022: explicitely ==> explicitly
frontend/ui/data/css_tweaks.lua:1124: loosing ==> losing
frontend/ui/data/keyboardlayouts/zh_stroke_data.lua:3: LIK ==> LIKE, LICK, LINK
frontend/ui/data/keyboardlayouts/ja_keyboard_keys.lua:21: hSa ==> has
frontend/ui/data/keyboardlayouts/fr_keyboard.lua:28: espace ==> escape
frontend/ui/data/keyboardlayouts/vi_telex_data.lua:2: aas ==> ass, as
frontend/ui/data/keyboardlayouts/vi_telex_data.lua:2: ans ==> and
frontend/ui/data/keyboardlayouts/vi_telex_data.lua:2: ans ==> and
frontend/ui/data/keyboardlayouts/vi_telex_data.lua:2: inh ==> in
frontend/ui/data/keyboardlayouts/vi_telex_data.lua:2: inh ==> in
frontend/ui/data/keyboardlayouts/vi_telex_data.lua:2: ois ==> is
frontend/ui/data/keyboardlayouts/vi_telex_data.lua:2: ois ==> is
frontend/ui/data/keyboardlayouts/vi_telex_data.lua:2: ons ==> owns
frontend/ui/data/keyboardlayouts/vi_telex_data.lua:2: ons ==> owns
frontend/ui/data/keyboardlayouts/vi_telex_data.lua:2: ot ==> to, of, or, not
frontend/ui/data/keyboardlayouts/vi_telex_data.lua:2: ot ==> to, of, or, not
frontend/ui/data/keyboardlayouts/vi_telex_data.lua:2: thur ==> their
frontend/ui/data/keyboardlayouts/vi_telex_data.lua:2: thur ==> their
frontend/ui/data/keyboardlayouts/vi_telex_data.lua:2: unx ==> unix
frontend/ui/data/keyboardlayouts/vi_telex_data.lua:2: unx ==> unix
frontend/ui/data/keyboardlayouts/vi_telex_data.lua:2: wass ==> was
frontend/ui/data/keyboardlayouts/vi_telex_data.lua:2: yur ==> your
frontend/ui/data/keyboardlayouts/vi_telex_data.lua:2: yur ==> your
frontend/ui/data/keyboardlayouts/ja_keyboard.lua:217: hSa ==> has
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:1: rime ==> rhyme
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: beng ==> being
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: bu ==> by, be, but, bug, bun, bud, buy, bum
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: fo ==> of, for, to, do, go
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: te ==> the, be, we, to
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: nin ==> inn, min, bin, nine
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: bale ==> able, bail
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: bage ==> bag
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: biyou ==> bayou
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: buda ==> buddha
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: paide ==> paid
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: meida ==> media
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: muti ==> multi
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: daming ==> damning, damping, gaming, doming
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: dake ==> take
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: daita ==> data
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: didi ==> did
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: tese ==> these, tease, terse
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: nane ==> name
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: neice ==> niece, nice
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: lama ==> llama
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: guage ==> gauge
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: geting ==> getting
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: gere ==> here, gear
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: hashi ==> hash
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: hanle ==> handle
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: hese ==> these
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: jumo ==> jump
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: juni ==> june
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: juli ==> july
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: juge ==> judge
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: chatou ==> château
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: chache ==> cache
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: changge ==> change
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: shange ==> change
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: sheming ==> scheming, shaming
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: shiping ==> shipping
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: relie ==> rely, relies, really, relief
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: rende ==> render, rend
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: ziping ==> zipping
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: sate ==> state
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: songling ==> singling, dongling
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: sudu ==> sudo
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: ede ==> edge
frontend/ui/data/keyboardlayouts/zh_pinyin_data.lua:3: ouer ==> outer
frontend/ui/widget/spinwidget.lua:63: speficied ==> specified
frontend/ui/widget/imagewidget.lua:287: explicitely ==> explicitly
frontend/ui/widget/imagewidget.lua:333: strech ==> stretch
frontend/ui/widget/imagewidget.lua:586: backgound ==> background
frontend/ui/widget/imagewidget.lua:597: explicitely ==> explicitly
frontend/ui/widget/focusmanager.lua:211: manger ==> manager
frontend/ui/widget/doublespinwidget.lua:65: speficied ==> specified
frontend/ui/widget/footnotewidget.lua:26: upppercase ==> uppercase
frontend/ui/widget/footnotewidget.lua:41: pannel ==> panel
frontend/ui/widget/footnotewidget.lua:122: overriden ==> overridden
frontend/ui/widget/pagebrowserwidget.lua:243: noticable ==> noticeable
frontend/ui/widget/pagebrowserwidget.lua:681: paiting ==> painting
frontend/ui/widget/pagebrowserwidget.lua:690: explicitely ==> explicitly
frontend/ui/widget/pagebrowserwidget.lua:1082: noticable ==> noticeable
frontend/ui/widget/pagebrowserwidget.lua:1468: splitted ==> split
frontend/ui/widget/imageviewer.lua:440: re-use ==> reuse
frontend/ui/widget/imageviewer.lua:831: re-use ==> reuse
frontend/ui/widget/listview.lua:54: itmes ==> items, times
frontend/ui/widget/bookmapwidget.lua:42: positionning ==> positioning
frontend/ui/widget/bookmapwidget.lua:43: positionning ==> positioning
frontend/ui/widget/bookmapwidget.lua:154: positionning ==> positioning
frontend/ui/widget/bookmapwidget.lua:354: noticable ==> noticeable
frontend/ui/widget/bookmapwidget.lua:362: noticable ==> noticeable
frontend/ui/widget/bookmapwidget.lua:548: explicitely ==> explicitly
frontend/ui/widget/bookmapwidget.lua:552: explicitely ==> explicitly
frontend/ui/widget/bookmapwidget.lua:560: positionning ==> positioning
frontend/ui/widget/bookmapwidget.lua:575: explicitely ==> explicitly
frontend/ui/widget/bookmapwidget.lua:604: boomarks ==> bookmarks
frontend/ui/widget/bookmapwidget.lua:697: explicite ==> explicit, explicitly
frontend/ui/widget/bookmapwidget.lua:748: noticable ==> noticeable
frontend/ui/widget/bookmapwidget.lua:750: noticable ==> noticeable
frontend/ui/widget/bookmapwidget.lua:993: noticable ==> noticeable
frontend/ui/widget/bookmapwidget.lua:1435: noticable ==> noticeable
frontend/ui/widget/bookmapwidget.lua:1466: substract ==> subtract
frontend/ui/widget/bookmapwidget.lua:1475: substract ==> subtract
frontend/ui/widget/bookmapwidget.lua:1801: explicitely ==> explicitly
frontend/ui/widget/inputtext.lua:633: seemlessly ==> seamlessly
frontend/ui/widget/inputdialog.lua:63: sucess ==> success
frontend/ui/widget/inputdialog.lua:615: visiblity ==> visibility
frontend/ui/widget/infomessage.lua:14: hight ==> height, high
frontend/ui/widget/buttondialog.lua:125: shrinked ==> shrunk, shrank
frontend/ui/widget/trapwidget.lua:120: initialiazed ==> initialized
frontend/ui/widget/menu.lua:1146: paramter ==> parameter
frontend/ui/widget/menu.lua:1470: overriden ==> overridden
frontend/ui/widget/menu.lua:1473: overriden ==> overridden
frontend/ui/widget/touchmenu.lua:307: seperators ==> separators
frontend/ui/widget/touchmenu.lua:310: asign ==> assign
frontend/ui/widget/touchmenu.lua:787: everytime ==> every time
frontend/ui/widget/touchmenu.lua:1095: overriden ==> overridden
frontend/ui/widget/touchmenu.lua:1227: animaton ==> animation
frontend/ui/widget/keyvaluepage.lua:289: aligment ==> alignment
frontend/ui/widget/textwidget.lua:30: synthetized ==> synthesized
frontend/ui/widget/textwidget.lua:31: synthetized ==> synthesized
frontend/ui/widget/textwidget.lua:215: synthetized ==> synthesized
frontend/ui/widget/titlebar.lua:33: dependant ==> dependent
frontend/ui/widget/titlebar.lua:162: allright ==> all right, alright
frontend/ui/widget/titlebar.lua:227: positionning ==> positioning
frontend/ui/widget/dictquicklookup.lua:866: Re-use ==> Reuse
frontend/ui/widget/dictquicklookup.lua:872: Re-use ==> Reuse
frontend/ui/widget/dictquicklookup.lua:909: positionning ==> positioning
frontend/ui/widget/dictquicklookup.lua:1340: querried ==> queried
frontend/ui/widget/dictquicklookup.lua:1345: positionned ==> positioned
frontend/ui/widget/datetimewidget.lua:268: trailling ==> trailing, trialling, trilling
frontend/ui/widget/textboxwidget.lua:44: synthetized ==> synthesized
frontend/ui/widget/textboxwidget.lua:45: synthetized ==> synthesized
frontend/ui/widget/textboxwidget.lua:104: alignemnt ==> alignment
frontend/ui/widget/textboxwidget.lua:407: splitted ==> split
frontend/ui/widget/textboxwidget.lua:411: reprensent ==> represent
frontend/ui/widget/textboxwidget.lua:463: splitted ==> split
frontend/ui/widget/textboxwidget.lua:482: splitted ==> split
frontend/ui/widget/textboxwidget.lua:859: synthetized ==> synthesized
frontend/ui/widget/textboxwidget.lua:1244: re-usable ==> reusable
frontend/ui/widget/textboxwidget.lua:1677: ouside ==> outside
frontend/ui/widget/textboxwidget.lua:1714: overriden ==> overridden
frontend/ui/widget/textboxwidget.lua:1942: separtor ==> separator
frontend/ui/widget/textboxwidget.lua:2027: re-use ==> reuse
frontend/ui/widget/buttonprogresswidget.lua:151: discreet ==> discrete
frontend/ui/widget/iconwidget.lua:38: overriden ==> overridden
frontend/ui/widget/container/alphacontainer.lua:24: re-use ==> reuse
frontend/ui/widget/container/movablecontainer.lua:33: reseting ==> resetting
frontend/ui/widget/container/movablecontainer.lua:417: explicitely ==> explicitly
frontend/ui/widget/container/scrollablecontainer.lua:48: disctinction ==> distinction
frontend/apps/reader/readerui.lua:309: overriden ==> overridden
frontend/apps/reader/readerui.lua:769: explicitely ==> explicitly
frontend/apps/reader/modules/readerfont.lua:430: everytime ==> every time
frontend/apps/reader/modules/readerfont.lua:748: defaut ==> default
frontend/apps/reader/modules/readertypeset.lua:158: compatiblity ==> compatibility
frontend/apps/reader/modules/readerstyletweak.lua:231: appened ==> append, appended, happened
frontend/apps/reader/modules/readerstyletweak.lua:402: wihout ==> without
frontend/apps/reader/modules/readerstyletweak.lua:721: globaly ==> globally
frontend/apps/reader/modules/readerdictionary.lua:117: Seaching ==> Searching, Reaching, Teaching
frontend/apps/reader/modules/readerdictionary.lua:652: funcion ==> function
frontend/apps/reader/modules/readerdictionary.lua:816: outputing ==> outputting
frontend/apps/reader/modules/readerthumbnail.lua:517: targetted ==> targeted
frontend/apps/reader/modules/readerkoptlistener.lua:26: compatability ==> compatibility
frontend/apps/reader/modules/readerrolling.lua:98: transitionning ==> transitioning
frontend/apps/reader/modules/readerrolling.lua:844: backgroud ==> background
frontend/apps/reader/modules/readerrolling.lua:1151: innacurate ==> inaccurate
frontend/apps/reader/modules/readerrolling.lua:1244: independant ==> independent
frontend/apps/reader/modules/readerrolling.lua:1684: explicitely ==> explicitly
frontend/apps/reader/modules/readerrolling.lua:1916: independant ==> independent
frontend/apps/reader/modules/readertypography.lua:154: outputing ==> outputting
frontend/apps/reader/modules/readertypography.lua:765: overriden ==> overridden
frontend/apps/reader/modules/readerlink.lua:697: witdh ==> width
frontend/apps/reader/modules/readerlink.lua:1295: substract ==> subtract
frontend/apps/reader/modules/readerlink.lua:1358: classe ==> class, classes
frontend/apps/reader/modules/readerpagemap.lua:251: buid ==> build
frontend/apps/reader/modules/readerpagemap.lua:277: advertized ==> advertised
frontend/apps/reader/modules/readerpaging.lua:665: caculate ==> calculate
frontend/apps/reader/modules/readertoc.lua:786: acount ==> account
frontend/apps/reader/modules/readeruserhyph.lua:14: hypenation ==> hyphenation
frontend/apps/reader/modules/readeruserhyph.lua:111: formated ==> formatted
frontend/apps/reader/modules/readersearch.lua:355: occurences ==> occurrences
frontend/apps/reader/modules/readersearch.lua:370: occurence ==> occurrence
frontend/apps/reader/modules/readercropping.lua:106: availble ==> available
frontend/apps/reader/modules/readerscrolling.lua:12: additionnally ==> additionally
frontend/apps/reader/modules/readerscrolling.lua:58: advertizes ==> advertises
frontend/apps/reader/modules/readerhandmade.lua:261: dependant ==> dependent
frontend/apps/reader/modules/readerhandmade.lua:285: dependant ==> dependent
frontend/apps/reader/modules/readerhandmade.lua:329: overriden ==> overridden
frontend/apps/reader/modules/readerhandmade.lua:361: fieds ==> fields, fiends
frontend/apps/filemanager/filemanagermenu.lua:511: objet ==> object
frontend/apps/filemanager/filemanagersetdefaults.lua:71: entires ==> entries
```

</details>

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12582)

### CODE REVIEW

**Comment by poire-z** [comment]
Typos jump out quite quickly when reading a PR. I fear having to fight that codespell thing anytime we name willingly a variable with a possible strange name that makes sense in our context (ie. `clen`, chars length).

**Comment by Frenzie** [comment]
I had much the same thought. I suppose the main question is if it would be helpful to add a configuration file if it isn't run regularly.

**Comment by Frenzie** [comment]
I'll drop the idea but note that https://github.com/koreader/koreader/actions/runs/11146736427/job/30979382405?pr=12582 lists a some amount of genuine typos.

**Comment by poire-z** [comment]
> lists a some amount of genuine typos

It feels half of them comes from my fingers :/ :)

**Comment by mergen3107** [comment]
@Frenzie 
Can codespell be configured so that it only targets comments?

Going manually through the error log above with all those typos revealed that it mainly did focus on comments with a few exceptions

**Comment by Frenzie** [comment]
It doesn't look that way but might depend on what you mean precisely.

**Pull request closed without merging**
