### PR TITLE
Profiles: auto-execute on events

### PR DESCRIPTION
**Pull request by hius07**
Added opening and closing document so far.

Automation usage examples:
-show ToC on opening a document
-set different frontlight levels for FM and Reader
-disable touch input in Reader for devices with page-turn buttons and enable it in FM

Further possible development:
-add more events
-extend `ReaderReady` event to handle doc props, for example, execute different profiles depending on doc language.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12564)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by hius07** [comment]
We can remove all Start with... options, except "file browser" and "last book".
History, Favorites, Collections, anything can be called on start by a profile.

**Comment by Frenzie** [comment]
At the very least I'd keep history available. Otherwise you'd be forcing users into something much more complicated for something that should be simple.

**Comment by mergen3107** [comment]
Other possible scenarios for this PR might be one or a few of these:
1) Revert to single-column arrangement if orientation has been changed to `Portrait` or `Inverted Portrait`.
2) The same but opposite, switch to double-column if rotated to `Landscape` or `Inverted Landscape`

Other things to consider:
- Set specific brightness/warmth settings if on home/office network.
For example, at work I can only use `eduroam` Wi-Fi, and in the office we have fixed bright lighting that we can't adjust. At home, I have home Wi-Fi, and would prefer to have lights dimmer.

Also, can this plugin track time? If so, then brightness/warmth can be adjusted with this PR too :D

**Comment by hius07** [comment]
Thanks, "on rotation" looks interesting.

**Comment by onatbas** [comment]
Can this be made to work with all event triggers? I know it sounds farfetched but someone may find a use for an auto-triggered event on each "ToggleBookmark" event. Furthermore, It would open this functionality up to plugin developers (like me).

**Comment by mergen3107** [comment]
@hius07 
I got several more ideas of triggers:
- on device wake
- by current time check
- on device wake + current time check.

An example for the last one: https://github.com/koreader/koreader/issues/11920
Here can be a profile to auto-set low brightness after device wake, but only if time is between, say 19:00 and 7:00.

**Comment by Frenzie** [comment]
On device wake might potentially be a bit iffy wrt unintended wake, scheduled wake and stuff like that.

> by current time check

You mean schedule at a specific time?

> Here can be a profile to auto-set low brightness after device wake, but only if time is between, say 19:00 and 7:00.

Isn't that a bad example in that there's already a plugin for that?

**Comment by mergen3107** [comment]
Is that AutoWarmth plugin? 

I am not using it for quite long time. 

All I need is to lower brightness.

**Comment by Frenzie** [comment]
I thought that was one of the things it could do anyway? I don't know, I don't use the frontlight except to turn it on at just about the lowest setting late at night. The whole warmth stuff is also lost on me.

**Pull request merged**
