### PR TITLE
BookStatusWidget, ReaderProgress: insert TitleBar

### PR DESCRIPTION
**Pull request by hius07**
---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8766)

### CODE REVIEW

**Comment by hius07** [comment]
3 close buttons remained:
-FronLightWidget (I do not have warmlight and cannot see it the full widget)
-ReaderProgress and CalendarView in the statistics plugin

**Comment by poire-z** [comment]
> CalendarView in the statistics plugin

I did the switch to TitleBar - I just forgot to remove the now unused CalendarTitle that was using CloseButton. Feel free to clean it.

**Comment by hius07** [comment]
I'll do ReaderProgress here too.

**Review by poire-z — APPROVED** [review]

**Comment by Frenzie** [comment]
This all looks more or less identical in the result? Code looks fine in any case. ;-)

**Comment by hius07** [comment]
Absolutely the same, just a new close button.

**Pull request merged**
