### PR TITLE
bump crengine: various fixes, updated russian hyphenation

### LINKED ISSUE #11594: No bottom border for <div>s
* KOReader version:2024.03.1
* Device: Fedora Linux 39 (Flatpak)

Also:
* KOReader version:2023.10
* Device: Kindle Voyage

#### Issue
A book I'm reading has block-quotes surrounded by horizontal lines, which are implemented as `<div>`s. These lines should have equal spacing above and below, as shown in Calibre:
image

However, in KOReader, the lines are bottom-aligned instead of centered:
image

Here is the html snippet used to create each line:
```html
<div style="border-bottom: 1pt solid black; margin-top: 1em; margin-bottom: 1em;"/>
```

As a workaround, I found this book-specific style tweak fixed the issue:
```css
div {
    border-top: 1pt solid white !important;
}
```
image

It has the side-effect of introducing 1pt of extra space per horizontal line, but otherwise it looks like correct behavior.

#### Steps to reproduce
Open affected book in KOReader. Reproduced with a fresh install, default settings and with style tweaks disabled.

### LINKED ISSUE #11623: fb2 image centering doesn't work anymore
* KOReader version: v2023.03.1-39
* Device: Kindle Scribe

#### Issue
Image centering doesn't work anymore in fb2 books.
I noticed this in my book that started reading on v2023.03.1 - where all images are centered OK even without my tweaks.
But on -39 all images are aligned to the left.

In another fb2 book, I did it by hand:
```
image + p {
    text-align: center !important;
    font-size: 0.8rem
}
```
but in -39 it doesn't work.

Maybe it was broken recently, not necessarily in -39, during the fb2 style tweaks overhaul? @poire-z ?

I am on mobile now, but I can provide the book and logs later.

I hope it is easily reproducible. 

Thanks!

### PR DESCRIPTION
**Pull request by poire-z**
Includes:
- https://github.com/koreader/crengine/pull/561 :
- Russian hyphenation: allow hyphens after Russian "не" prefix
- https://github.com/koreader/crengine/pull/560 :
- EPUB: add "identifiers" to doc props
- https://github.com/koreader/crengine/pull/563 :
- EPUB: avoid crash when '@font-face' in <head><style>
- FB2: fix block images sizing and centering
  Closes #11623.
- lvrend: fix positioning of bottom border on empty block elements
  Closes #11594.

Also includes:
- cre: add 'identifiers' to doc props https://github.com/koreader/koreader-base/pull/1758
- build and ci: various tweaks:
https://github.com/koreader/koreader-base/pull/1759
https://github.com/koreader/koreader-base/pull/1762
https://github.com/koreader/koreader-base/pull/1763
https://github.com/koreader/koreader-base/pull/1764

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11637)

### CODE REVIEW

**Comment by poire-z** [comment]
macos build:
```
Error: lua@5.1 has been disabled because it is deprecated upstream!
Error: lua@5.1 has been disabled because it is deprecated upstream!
```
Not in previous koreader-base merges.
Should we bother? @benoit-pierre ?

**Comment by Frenzie** [comment]
It's unrelated to this bump, see the log on previous commits. But the bothering may be the fastest means of getting it fixed. 😆

**Comment by poire-z** [comment]
`Too long with no output (exceeded 10m0s): context deadline exceeded`

**Comment by Frenzie** [comment]
I think it's an OOM issue. The process limit should then be reduced slightly for CI. I'm not sure why we didn't already see this in base though.

```
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[6]: *** [Makefile:2753: libharfbuzz_la-hb-ot-font.lo] Error 1
make[6]: *** Waiting for unfinished jobs....
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[6]: *** [Makefile:3068: main-main.o] Error 1
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[6]: *** [Makefile:2627: libharfbuzz_la-hb-aat-layout.lo] Error 1
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[6]: *** [Makefile:2781: libharfbuzz_la-hb-ot-layout.lo] Error 1
make[6]: Leaving directory '/home/ko/project/base/thirdparty/harfbuzz/build/x86_64-linux-gnu/harfbuzz-prefix/src/harfbuzz/src'
make[5]: *** [Makefile:3934: all-recursive] Error 1
make[5]: Leaving directory '/home/ko/project/base/thirdparty/harfbuzz/build/x86_64-linux-gnu/harfbuzz-prefix/src/harfbuzz/src'
make[4]: *** [Makefile:2031: all] Error 2
make[4]: Leaving directory '/home/ko/project/base/thirdparty/harfbuzz/build/x86_64-linux-gnu/harfbuzz-prefix/src/harfbuzz/src'
make[3]: *** [Makefile:511: all-recursive] Error 1
make[3]: Leaving directory '/home/ko/project/base/thirdparty/harfbuzz/build/x86_64-linux-gnu/harfbuzz-prefix/src/harfbuzz'
make[2]: *** [Makefile:443: all] Error 2
make[2]: Leaving directory '/home/ko/project/base/thirdparty/harfbuzz/build/x86_64-linux-gnu/harfbuzz-prefix/src/harfbuzz'
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile.third:32: build/x86_64-linux-gnu/libs/libharfbuzz.so.0] Error 1
make[1]: Leaving directory '/home/ko/project/base'
make: *** [Makefile:134: base/build/x86_64-linux-gnu/luajit] Error 2
```

**Comment by Frenzie** [comment]
Actually https://github.com/koreader/koreader-base/commit/3da62cb54209c558e326e386cbab900c339fe655 has some special overrides in the CI build script. If you copy them here it'll probably be okay.

**Comment by benoit-pierre** [comment]
I think I know why: it needs the same detection as for the base CI script: https://github.com/koreader/koreader-base/blob/master/.ci/build_script.sh#L15.

**Comment by benoit-pierre** [comment]
Any other scripts that need to be similarly updated? Maybe it would make more sense to do that in `Makefile.defs` if `$(CI)` is set?

**Comment by benoit-pierre** [comment]
Let me make a PR to base to factorize this stuff.

**Comment by Frenzie** [comment]
I think GitLab CI is closer to 4 GB vs 2 GB here so there's a decent chance it'll work as is. But I see a new reply was just posted, so let's just wait. ^_^

**Comment by Frenzie** [comment]
With https://github.com/koreader/koreader-base/pull/1764 it should work now.

**Comment by poire-z** [comment]
Mhhh, updated tihs morning (haven't since 3 weeks ago).

Something strange just happened: I was reading, having read a few pages, and when turning to the next page, the font (the face, or the size, not sure) changed... I don't think I hit by error some setting, at least I couldn't find something changed, the `Font>` still showed my main font checked, and nothing in the log except a "inhibiting user input"/"restoring user input"... Reopening the document cause "Style hash mismatch", and after the rerendering, everything was ok again.
Tried turning pages on a few other books, no issue noticed.

I'm not sure what happened, never seen that before. Feels like some crengine (or my device memory?) corruption.
Dunno if it is due to the recent changes brought by this PR - but looking at it, I see nothing complex enough to cause this.
Except may be that I didn't bump `CACHE_FILE_FORMAT_VERSION` (see https://github.com/koreader/crengine/pull/560#discussion_r1554159265), and having that new item ("identifier") in docProps, and maybe expecting it from the cache, may cause some shifts in adresses. And may be I witnessed it only way later after the update because I was transitionning chunks in my previously made cache...?

Anyway, if anybody else notices something as strage as this, please tell it here, and I'll bump that `CACHE_FILE_FORMAT_VERSION` just to be sure.

**Comment by Frenzie** [comment]
Fwiw I was reading a book yesterday that I'd first opened a couple of months ago and I didn't notice anything weird.

**Pull request merged**
