### PR TITLE
[feat] Implement fulltext search direction

### PR DESCRIPTION
**Pull request by Frenzie**
Closes <https://github.com/koreader/koreader/issues/5054>.

### CODE REVIEW

**Comment by poire-z** [comment]
Wouldn't `backward | forward` sound nicer than `previous | next` in this context (as there is no hit yet, that could have a previous or a next hit) ?

**Comment by Frenzie** [comment]
Or just the same ⯈ type arrows as in the dictionary? I didn't really pay attention but the search is also grossly abusing `<` `>` there instead of something slightly nicer.

PS It's not that specific ⯈ character but a "white triangle" or something.

**Comment by poire-z** [comment]
Yep, those symbols would look fine there too :)

**Comment by Frenzie** [comment]
Not quite there yet. It needs a different `|`-like character.

Screenshot_20190830_130543
Screenshot_20190830_130556

**Comment by Frenzie** [comment]
I think left/right one eighth block look pretty decent.

Screenshot_20190830_131325

**Comment by poire-z** [comment]
Kinda thick, but so are front and back covers :) so fine with me.

**Pull request merged**
