### PR TITLE
Dispatcher: add word spacing & expansion

### PR DESCRIPTION
**Pull request by yparitcher**
Noticed at https://github.com/koreader/koreader/pull/10080#issuecomment-1427819762
lightly tested.

Now the only ones that are not included are
```
font_fine_tune
cjk_width_scaling
kopt_rotation_mode
```
`font_fine_tune` is covered by the regular font
`cjk_width_scaling` does not have an actual toggle, it is a extension of word_expansion
`kopt_rotation_mode` is covered by cre `rotation_mode`

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10118)

### CODE REVIEW

**Comment by poire-z** [comment]
Seems to work for me: I see them in the action list, and they are applied.
Moreover, the profiles I created yesterday from document settings now show these 2 settings, with the value they had when I created them :) So, I guess there's nothing else to do on the profile plugin side, as these settings were already managed and saved - just not shown. Pinging @hius07 to confirm there's nothing else to do.

**Comment by hius07** [comment]
I've looked into the future
https://github.com/koreader/koreader/blob/91ff6ce2d81c299153d99fe0eba7f4bfa9d742b7/plugins/profiles.koplugin/main.lua#L310-L311

**Review by poire-z — APPROVED** [review]

**Comment by yparitcher** [comment]
@hius07 
https://github.com/koreader/koreader/blob/237f44deda72d5dec1458a9831c702f464d7e323/plugins/profiles.koplugin/main.lua#L327
https://github.com/koreader/koreader/blob/237f44deda72d5dec1458a9831c702f464d7e323/plugins/profiles.koplugin/main.lua#L347-L348
contradict. cre has `rotation_mode` kopt has `kopt_rotation_mode` we just don't add it to dispatcher because they are duplicates. You might want to special case it below.

**Comment by hius07** [comment]
So what's an issue? It now works for cre and pdf.

**Comment by yparitcher** [comment]
In kopt you chop off the first 5 letters to account for the prefix, `rotation_mode` does not have a prefix so it will be truncated to ` ion_mode`

**Comment by hius07** [comment]
But then I do
https://github.com/koreader/koreader/blob/da841f3d8744a052cfde0a24549771d87f8048fc/plugins/profiles.koplugin/main.lua#L361

**Comment by yparitcher** [comment]
So then just this line is extra
https://github.com/koreader/koreader/blob/da841f3d8744a052cfde0a24549771d87f8048fc/plugins/profiles.koplugin/main.lua#L327

**Comment by hius07** [comment]
`document_settings` is used as order of the profile.

**Pull request merged**
