### PR TITLE
TitleBar: new options, update ImageViewer to TitleBar

### LINKED ISSUE #8643: "Book map" explanation not found for translation
* KOReader version: v2021.12.1-41
* Device: PB 628

#### Issue
Explanation text for "Book map" can't be found in Weblate to be translated.

### PR DESCRIPTION
**Pull request by poire-z**
#### Style tweaks: add "Ignore publisher line-break restrictions"

See https://github.com/koreader/crengine/pull/423#issuecomment-1008271069

#### KeyValuePage, Sortwidget: fix RTL mirrored layout

KeyValuePage: the return arrow was staying on the left as in LTR; make it go to the right, added a mirrored `back.top.rtl.svg`.
SortWidget: items were staying aligned to the left (with checkboxes in the middle of screen); make them properly left aligned.

#### BookMap, PageBrowser: make help_text translatable

Closes #8643.
Minor wording update. See https://github.com/koreader/koreader/pull/8613#issuecomment-1008333230
Add a larger and thicker info.svg for their top left icon.

#### TitleBar: new options for subtitle and icon rotation

Discussed at https://github.com/koreader/koreader/pull/8639#discussion_r780814132. Gives more flexibility for future works.

#### ImageViewer: update to TitleBar widget

Rewrite widget layout building and update logic. It was quite a mess, but it was my mess, one of my first high level widget :)
I initially tried to just update it so it _looks_ like TitleBar, but it ended up impossible and even more kludgy. So, rewrote :init() / :update() so that they look a bit more like some of our more recent high level widgets.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8640)

### CODE REVIEW

**Comment by hius07** [comment]
`KOReader` in file manager and title in Menu by default are shown with "smalltfont".
Maybe add default `fullscreen = true` to KVP too?

**Comment by poire-z** [comment]
> Maybe add default fullscreen = true to KVP too?

Done.

**Comment by hius07** [comment]
We are now so free in titles design! What about the cross in small textviewer windows?





Or add the cross to the InputDialog title (for consistency)?
(InputDialog hasn't got new TitleBar yet)

**Comment by poire-z** [comment]
Dunno, no real preference.
Haven't looked yet at all the other widgets that build their specific title bar without a CloseButton (that I guess could also be migrated to TitleBar, just for font and padding and height consistency).
Are there all mostly InputDialog ?

Some have rather long titles (Enter a word to lookup, Enter letter or page number), so adding the close button have more risk of truncating them.

**Comment by hius07** [comment]
> Are there all mostly InputDialog ?

InputDialog, MultiInputDialog, OpenWithDialog, KeyboardLayoutDialog, (Double)SpinWidget, RadioButtonWidget, DateTimeWidget.

**Comment by poire-z** [comment]
If you're ok with this PR (at least TitleBar), I can merge it so you can merge #8639.

**Comment by hius07** [comment]
All good.

**Comment by hius07** [comment]
And we have FileManager with its own title bar
https://github.com/koreader/koreader/blob/71172253b752fe518cda9ce1f5feb6216fe0e9f1/frontend/apps/filemanager/filemanager.lua#L148-L177

**Comment by poire-z** [comment]
Btw, should I make the `(i)` icon larger ? It feels thin vs. the close icon:
image

Tweaking the viewport= in the SVG like @hius07 did for some others makes it a bit better (larger, but still thin, although I don't mind it like this, it's less intrusive):
```diff
    width="48"
    height="48"
-   viewBox="0 0 48 48"
+   viewBox="4 4 40 40"
```
image

I could do that to notice-info.svg and name the result info.svg.
Unless you can think of an other better icon for this ? (I used notice-info.svg because it was just there :)

**Comment by poire-z** [comment]
> The info icon is intended for larger display size normally, isn't it? That is, you should probably duplicate it if you want a version optimized to be smaller?

Not sure I get you :)
Our icons are SVG and scale, we have nothing "intended for this or that display size" I think.
We have notice-info.svg, that is used only by InfoMessage, which adds it on the left of the text, so it's good it has a bit of padding on the side.
We don't have any info.svg yet, but I proposed to copy notice-info.svg as info.svg with less padding, so it can be used as a TitleBar icons with the same size as others. By removing the padding, we would get the same size, ~~but it would still be too thin~~ damned, it's SVG, I can just increase the stroke-width :) So, this would give this:
image

Unless you have a better idea for such a "help/info" top left button, that this dump circled-i.

**Comment by hius07** [comment]
Aren't any more actions for this button?
I haven't used Book map a lot yet, but think it might be some actions that are made with swipes on left and bottom sides.

**Comment by poire-z** [comment]
> Aren't any more actions for this button?
I haven't used Book map a lot yet, but think it might be some actions that are made with swipes on left and bottom sides.

Well, I didn't have any need for any more actions (swipes are just fine, no real need for more dialogs that would clutter what you see), but if we ever need some, we can think about it later :)
(We could have our icon callback show a popdown menu from that button the day we need that kind of submenu.)

**Comment by poire-z** [comment]
Unless you thought about using the <kbd>+</kbd> icon and show a ButtonTable ?
Well, for now, I don't see any other button to add alongside a "How to use this".
So, either we use this <kbd>+</kbd> which shows the help InfoMessage (which feels a bit strange), or I add my info.svg (I don't see any of our other top or bottom menu icon that could be better).

**Comment by Frenzie** [comment]
You can see how the X was designed to be smaller (i.e., with thicker lines).

**Comment by poire-z** [comment]
> Yes, and as I wrote a while back you can even do that dynamically. You don't necessarily need to make a new file. But you do have to do it. ;-)

Yes, I remember, and it was fun.
But making a new file is easier than having to make some new code (and a new module, if we'd want to reuse this dynamically tweaked icon) that would anyway need dedicated per-source icon string substitutions that would not work on any other icon :)
Going with a larger and thicker icon.svg, as we got no real other idea for that top left icon.

**Pull request merged**
