### PR TITLE
[Android] Enable CoverBrowser

### PR DESCRIPTION
**Pull request by Frenzie**
I was reminded by @KenMaltby that this is disabled on Android.

https://www.mobileread.com/forums/showthread.php?p=3586162#post3586162

@poire-z Is there anything specific I should try to see if this is problematic? It seems to work just fine.

### CODE REVIEW

**Comment by poire-z** [comment]
Oh, nice! Well, one just had to try it :) Wasn't sure fork() would be working on android with its security/limitation features.

You need to try to see processes (ps on android?), and if the forked processes are really cleaned and not stay zombies (waitpid), and can be killed (the 2 next functions in xutils.lua).
When you go to next page, and some indexing needs to be done for this page, the previous fork/indexing, started on previous page and still ongoing, should be killed, waitpid()'ed, and a new one started.

**Comment by Frenzie** [comment]
It might be possible with adb somehow.

https://codeseekah.com/2012/10/21/android-shell-tricks-ps/

**Comment by Frenzie** [comment]
Fantastic, Android `ps` doesn't take options like `f`. Not sure how I'm going to get useful info out of that one…

**Comment by Frenzie** [comment]
Okay, ultimately that wasn't too hard with `ps | grep 19319` (where `19319` happened to be my `org.koreader.launcher` PID). It  looked like they were launching and closing correctly so I'll go ahead and merge this.

**Comment by poire-z** [comment]
I tried this morning for the first time KOReader on my android phone, and I'm impressed! It is cute (1), super fast (2), battery friendly, and working well (I'm so proud of us! :)

Any reason (or setting I missed) images are still greyscale: covers, images in wikipedia epub ? I checked that, for such an epub created with koreader, FBReader (my _former_ reader app) displays images in color. The emulator displays them in color, so it's not a hard limitation.

(1) it looks good, and really usable, on a small screen - I wonder how the recent dpi/size rescaling helped in that
(2) kobo eink feels slow and laggy after playing with koreader on android, so I won't abuse of android - I hardly ever read on my phone, but well, I now have a good reader app on my phone just in case :)

**Comment by Frenzie** [comment]
> Any reason (or setting I missed) images are still greyscale: covers, images in wikipedia epub ? I checked that, for such an epub created with koreader, FBReader (my former reader app) displays images in color. The emulator displays them in color, so it's not a hard limitation.

Maybe it helped save memory and CPU power on the original Kindle? My instinct would be just to toss all the colors at the display driver and to let that thing deal with the whole shebang. I guess on some combination of hardware and software that must've been problematic or at least suboptimal. 

But yes, setting aside the fact that KOReader won't load properly on my Zenfone 2, I'd never consider using it over Bubbles as long as it doesn't do color.

> The emulator displays them in color, so it's not a hard limitation.

That's one way of putting it. Sure, there are colors present in some contexts… >_> (I'm not really sure why they're reversed.)

screenshot_2017-09-29_12-52-21

**Comment by zivilyyyn** [comment]
It seems that the cover cannot be shown if the file name of the image in the epub file is in Chinese.

**Comment by Frenzie** [comment]
Is there a testing file available? Part of me fears this might be related to FAT32 but one can hope.

**Comment by poire-z** [comment]
Or how the filename was encoded in the zip/epub, and how crengine decodes it, and how it is encoded in the content.opf. Guess if there is any mismatch, the cover would not be found in the epub.
If I understand correctly its really the filename *in* the epub - so, it's not coverbrowser specific, but crengine : does it fail too if you open the book, go to Book information, and _Tap to display_ cover image?

**Comment by zivilyyyn** [comment]
Yes, it fails too if I open the book, the cover cannot be shown in book information. A testing file is uploaded below.
[test.epub.zip](https://github.com/koreader/koreader/files/1385472/test.epub.zip)

**Comment by poire-z** [comment]
Looks like the things pointing to the cover image are wrong in your epub.
I can't find real specs about cover specifications in epub, but the way crengine finds it, and https://wiki.mobileread.com/wiki/Ebook_Covers, would say the problem in your epub is in `OEBPS/content.opf` :
```
    <meta name="cover" content="墓畔回忆录.jpg" />
    <item href="Images/cover.jpeg" id="cover" media-type="image/jpeg" />
```
The `content` should not reference a filename, but one of the `item`'s `id`.
Change it to:
```
    <meta name="cover" content="cover" />
    <item href="Images/cover.jpeg" id="cover" media-type="image/jpeg" />
```
and the cover is found and displayed.

Would be nice to know how other epub readers deal with it: do they show this badly specified cover or not (is it a common error, or an alternate specification, that is workarounded and supported?)

**Comment by Frenzie** [comment]
@poire-z I'm slightly confused by the XHTML you quoted since `Images/墓畔回忆录.jpg` and `Images/cover.jpeg` are two completely different files?

**Comment by poire-z** [comment]
Oh, right, there's an other `item` with this `id` at the end of the item list (i didn't scroll down enough :)
`    <item href="Images/%E5%A2%93%E7%95%94%E5%9B%9E%E5%BF%86%E5%BD%95.jpg" id="墓畔回忆录.jpg" media-type="image/jpeg" />`

If i change it to:
`    <item href="Images/cover.jpeg" id="墓畔回忆录.jpg" media-type="image/jpeg" />`
the image cover.jpeg is used, so chinese in `id` is ok.
If i rename 墓畔回忆录.jpg to cover.jpeg , it is used, so the 墓畔回忆录.jpg image is valid.
If i use:
`    <item href="Images/墓畔回忆录.jpg" id="墓畔回忆录.jpg" media-type="image/jpeg" />`
it is not displayed.
So, first guess above is probably right, about encoding of filenames in the zip being the problem.

**Pull request merged**
