### PR TITLE
SortWidget: sort alphabetically

### PR DESCRIPTION
**Pull request by hius07**
- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11705)

### CODE REVIEW

**Comment by jonnyl2** [comment]
Thanks for adding this. Had a quick test and what stood out was that it is case sensitive; a-z comes after A-Z. Should probably be case insensitive?

**Comment by Frenzie** [comment]
I think that's @NiLuJe's cue. xD

(See https://en.wikipedia.org/wiki/Natural_sort_order for some background.)

**Comment by hius07** [comment]
Case insensitive (actually depends on the default global `DALPHA_SORT_CASE_INSENSITIVE` that is truthy).

**Comment by NiLuJe** [comment]
> I think that's @NiLuJe's cue. xD

:D

IIRC, we do have a natsort-ish variant in the FM sorting hat, so while it usually didn't really matter in SortWidget, the one example being shown here (e.g., Collections), it... might ;).

**Comment by hius07** [comment]
> we do have a natsort-ish variant in the FM sorting hat

Exactly, let's reuse it:
https://github.com/koreader/koreader/blob/cae7e8bfec91aad16d9470add1ab8d59c714f85f/frontend/ui/widget/sortwidget.lua#L528-L529

**Comment by Commodore64user** [comment]
Would it not be better to have just two choices (a to z and natural sort) and a reverse sorting option? It would be more in-line with the way it works on file browser.

**Comment by Frenzie** [comment]
(As well as file managers in general.)

**Comment by Commodore64user** [comment]
In fact, why not **just** have the natural sorting one?

**Comment by Frenzie** [comment]
Performance. The dumb one is significantly faster.

**Comment by hius07** [comment]
> Wouldn’t it be better to have just two choices (a to z and natural sort) and a reverse sorting option?

It's a one-time operation, not a long-lasting setting like in FM.
I press one button and get the result.

**Pull request merged**
