### PR TITLE
MultiInputDialog: do not refresh full screen on show

### PR DESCRIPTION
**Pull request by hius07**
Fix ugly full screen flashing on show.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8760)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by NiLuJe** [comment]
Note to self: check the blame, I vaguely recall that there was a reason for this ;).

**Comment by hius07** [comment]
> check the blame

https://github.com/koreader/koreader/pull/4541/files#diff-ec760af17116d6a9eb1ebd6cfcb2a3dd5ecf8d242af8cb2b061cdec5dbac583dL125

**Comment by NiLuJe** [comment]
Okay, so, progress!

Why would it be flashing, though? (`ui` doesn't).

**Comment by hius07** [comment]
Before (screen goes black)

https://user-images.githubusercontent.com/62179190/152105885-aaa46938-513e-4199-b534-2b71b74bd109.mp4

After

https://user-images.githubusercontent.com/62179190/152105897-e440561d-5e9c-40d4-9f31-9aac0d40770c.mp4

**Comment by Frenzie** [comment]
On the downside, I think I might find the second more distracting. (Don't pay any attention to that though, they're both perfectly alright by me.)

**Comment by NiLuJe** [comment]
Oh, the first variant happen to gets merged with the VK refresh on your device.

I'll probably want to check what's really happening myself over the week-end ;).

**Comment by Frenzie** [comment]
@NiLuJe My H2O behaves the same.

**Comment by NiLuJe** [comment]
Good to know, thanks ;).

The change definitely makes more sense, I'd just like to check what exactly made the driver merge it before (I suspect it's because it ends up being full-screen) ;).

**Comment by poire-z** [comment]
> before (I suspect it's because it ends up being full-screen) ;)

Looks like it nearly is: it is in a CenterContainer that takes all the space above the keyboard.
Code in master with the original setDirty:
https://github.com/koreader/koreader/blob/035b24bb812488ce5506ca01eadf25844f51d7eb/frontend/ui/widget/multiinputdialog.lua#L199-L207

**Review by NiLuJe — APPROVED** [review]
Thanks for doing the detective work for me, guys ;).

**Pull request merged**
