### PR TITLE
Notification are displayed too short

### PR DESCRIPTION
**Pull request by robert00s**
I think the notification messages are displayed too short (eg. `Line spacing set to...`, `Font size set to...`). I changed from 1 second to 2.
I also fixed the problem with blocking the UI when displaying the message. Now notification box is closed after taping anywhere (like InfoMessage).

### CODE REVIEW

**Comment by poire-z** [comment]
I'm often a bit annoyed when testing and changing things quickly (font size, margin), that my second tap is used to dismiss the Notification (that now displays for 2 seconds), so I have to tap a third time to have that tap processed by the thing I tap on :)

May be we could make the `Notification:onTapClose()` and `Notification:onAnyKeyPressed()` just never `return true`, so the same second Tap is used to dismiss the Notification, but still propagates to some other widget that will do its thing?

**Comment by poire-z** [comment]
I don't think we have any Notification that last longer than a few seconds.
Previous to this PR, Notification didn't have any gesture support: they didn't need to: they were displayed for usually 1 second, and disappeared (via scheduleIn), and did not interfere with the next gestures.
With this PR, that increase their duration to 2 seconds, support for gesture was added, so they can be dismissed before the 2 seconds have elapsed. But by doing so, you need to tap once more to change page.
But unlike InfoMesage that sticks longer, I think the dismiss should still dismiss, but it should not stop the propagation of the Tap.
We would just need to remove these lines:
https://github.com/koreader/koreader/blob/901a1e46da8720ed4c02b3e93df183483febcf6d/frontend/ui/widget/notification.lua#L102-L104

**Comment by Frenzie** [comment]
Ok, sounds good.

**Comment by robert00s** [comment]
Maybe we should add `readonly = true` to Notification call? E.g:

```
    UIManager:show(Notification:new{
        text = T( _("Font size set to %1."), self.font_size),
        timeout = 2,
        readonly = true,
    })

```

**Comment by poire-z** [comment]
That would make many changes outside notification.lua, and I think it should be solved in notification.lua.
I don't think we get any Notification with `readonly=true`, but if `readonly=true` means that it should not react to gestures (= should not be dismissed with tap as it is readonly), it should probably be:
```lua
function InfoMessage:onTapClose()
    if self.readonly ~= true then
        self.dismiss_callback()
        UIManager:close(self)
    end
end
```
so it always propagate (so one could tap on some other close button, which it will be its job to close all the readonly widgets).

**Comment by robert00s** [comment]
I didn't know about `dissmiss_callback()` and I think is probably requires changing the logic in trapper.lua :(

**Comment by poire-z** [comment]
Oups, sorry, wrong cut & pasting :) (I was looking at InfoMessage to compare). No need for dismiss_callback with Notification, and no support for Notification with trapper, no real need for that.
So, would that cause problem with how you envision Notification & readonly?
```lua
function Notification:onTapClose()
    if self.readonly ~= true then
        UIManager:close(self)
    end
end
```

**Comment by robert00s** [comment]
My idea was that:
1. `readonly ~= true` (default) - tap anywhere -> close only notification window
2. `readonly == true` - tap anywhere -> close notification window + next action (eg. close bottom menu, next page turn...)
But we can remove readonly option like you suggested here: https://github.com/koreader/koreader/pull/3962#issuecomment-397111990. I don't mind :)

**Comment by poire-z** [comment]
> But we can remove readonly option like you suggested

OK, thanks :). We'll then re-add `readonly` when we have a use-case for a _readonly_ behaviour.
(I'll remove it in a bump crengine PR later today, if you don't beat me with a PR till then :)

(Your idea was logical - it's just the combination of notification being displayed at top of screen, but most often triggered by the configdialog at bottom of screen, so I often just dont see there's a notification - and _my_ medium reaction time to decide if some parameter is too much or not enough being around 2 seconds too :) so if I react and tap on another button at 1.9s, my tap would be eaten - but if I tap at 2.1s it would work :)

**Comment by poire-z** [comment]
Mhhh, may be your original behaviour would make sense when there is no timeout.

When there is a timeout (all our Notifications in our code has one, 1s or 2s), the tap should propagate so the behaviour stays consistent when you tap at 1.9s or 2.1s.

Where there is no timeout (but we don't have a single case of that in our code), the tap should just close the notification and not propagate - so that a user that is used to timeouting notifications, when waiting for 10s and not seeing it disappear, could tap to make it go without triggering a page change.

**Pull request merged**
