### PR TITLE
make: factorize code for generating release updates

### PR DESCRIPTION
**Pull request by benoit-pierre**
Instead of splitting remove / exclusion of unwanted files in 2-3 places (`all` rule, `update` rule, and update script in some cases), install the same files in debug & release builds, and exclude unwanted stuff when generating the update.

This should finally fix the CI issue with OCR tests (since we don't remove the `data/dict` & `data/tessdata` directories on release build anymore).

Concrete differences for each target:

- `android`: 
```diff
-fonts/nerdfonts/LICENSE
-fonts/noto/LICENSE
-fonts/urw/LICENSE
-l10n/LICENSE
-plugins/newsdownloader.koplugin/lib/LICENSE_LuaXML
-plugins/SSH.koplugin/*
-resources/icons/mdlight/icons-license.txt
-resources/icons/mdlight/LICENSE-SIL-OFL-1.1.md
-resources/icons/mdlight/license.txt
```

- `appimage`
```diff
-clipboard
-data/NOTES.txt
-jit/.gitignore
-l10n/.git
-l10n/.github/*
-l10n/templates/*
-plugins/SSH.koplugin
-plugins/SSH.koplugin/main.lua
-plugins/SSH.koplugin/_meta.lua
-resources/fonts/*
-screenshots
-tools/*
```

- `cervantes`:
```diff
-koreader/clipboard/
-koreader/data/NOTES.txt
-koreader/frontend/device/kobo/device.lua.orig
-koreader/jit/.gitignore
-koreader/l10n/.git
-koreader/l10n/.github/*
-koreader/l10n/templates/*
-koreader/screenshots/
-koreader/tools/*
```

- `kindlepw2`:
```diff
-koreader/clipboard/
-koreader/data/NOTES.txt
-koreader/jit/.gitignore
-koreader/l10n/.git
-koreader/l10n/.github/*
-koreader/l10n/templates/*
+koreader/ota/
-koreader/screenshots/
-koreader/tools/*
```

- `kobo`:
```diff
-koreader/clipboard/
-koreader/data/NOTES.txt
-koreader/jit/.gitignore
-koreader/l10n/.git
-koreader/l10n/.github/*
-koreader/l10n/templates/*
-koreader/screenshots/
-koreader/tools/benchmark.lua
-koreader/tools/diffreleases.sh
-koreader/tools/eink_cmap.gif
-koreader/tools/fbplay.sh
-koreader/tools/graph_memory.sh
-koreader/tools/ja_keyboard_generate.py
-koreader/tools/logcat.py
-koreader/tools/mk7z.sh
-koreader/tools/trace_require.lua
-koreader/tools/update-metadata.lua
-koreader/tools/valgrind_amd.supp
-koreader/tools/wbuilder.lua
```

- `linux`:
```diff
+lib/koreader/common/turbo/3rdparty/middleclass/MIT-LICENSE.txt
-lib/koreader/data/dict/*
-lib/koreader/data/tessdata/*
-lib/koreader/ev_replay.py
+lib/koreader/fonts/droid/NOTICE
+lib/koreader/fonts/nerdfonts/LICENSE
+lib/koreader/fonts/noto/LICENSE
+lib/koreader/fonts/README.md
+lib/koreader/fonts/urw/LICENSE
+lib/koreader/l10n/LICENSE
+lib/koreader/l10n/README.md
-lib/koreader/l10n/templates/*
+lib/koreader/plugins/japanese.koplugin/README.md
+lib/koreader/plugins/newsdownloader.koplugin/lib/LICENSE_LuaXML
+lib/koreader/README.md
+lib/koreader/resources/icons/mdlight/icons-license.txt
+lib/koreader/resources/icons/mdlight/LICENSE-SIL-OFL-1.1.md
+lib/koreader/resources/icons/mdlight/license.txt
```

- `macos`:
```diff
-KOReader.app/Contents/koreader/data/NOTES.txt
-KOReader.app/Contents/koreader/jit/.gitignore
-KOReader.app/Contents/koreader/l10n/.github/*
+KOReader.app/Contents/koreader/l10n/LICENSE
+KOReader.app/Contents/koreader/l10n/README.md
```

- `pocketbook`:
```diff
-applications/koreader/clipboard/
+applications/koreader/common/turbo/3rdparty/middleclass/MIT-LICENSE.txt
+applications/koreader/fonts/README.md
-applications/koreader/jit/.gitignore
-applications/koreader/l10n/.git
-applications/koreader/l10n/.github/*
+applications/koreader/l10n/README.md
-applications/koreader/l10n/templates/*
+applications/koreader/plugins/japanese.koplugin/README.md
+applications/koreader/README.md
+applications/koreader/resources/icons/mdlight/icons-license.txt
+applications/koreader/resources/icons/mdlight/LICENSE-SIL-OFL-1.1.md
+applications/koreader/resources/icons/mdlight/license.txt
-applications/koreader/screenshots/
-applications/koreader/tools/*
```

- `remarkable`:
```diff
-koreader/clipboard/
-koreader/data/NOTES.txt
-koreader/jit/.gitignore
-koreader/l10n/.git
-koreader/l10n/.github/*
-koreader/l10n/templates/*
-koreader/plugins/SSH.koplugin/*
-koreader/screenshots/
-koreader/tools/*
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12655)

### CODE REVIEW

**Comment by benoit-pierre** [comment]
Note: I kept `tool/kobo_touch_probe.lua` for `kobo` targets, but I don't know if it's wanted / still work.

**Comment by benoit-pierre** [comment]
For `kobo` targets, the `zip` release includes `koreader.png`, but not the `targz` (or the OTA manifest), why?

Similarly, the `poocketbook` `zip` includes `system/bin/koreader.app`, but not the `targz` (or OTA manifest), why?

**Comment by benoit-pierre** [comment]
The `macos` release excludes some plugins: `SSH`, `autofrontlight`, `hello`, and `timesync`.

I did the same for the `android`, `appimage`, and `remarkable` targets: the `SSH` plugin is excluded.

Are there other plugins that should be excluded on some targets? Should the `hello` example plugin be excluded for all targets?

**Comment by Frenzie** [comment]
I don't know if `tools` necessarily wants to be removed from the AppImage. Some people use it to hack Lua with `--appimage-extract` and particularly wbuilder can be quite useful for that.

> For kobo targets, the zip release includes koreader.png, but not the targz (or the OTA manifest), why?

The OTA only updates the /koreader folder. That image file is only for setup. (Same for PB.)

> Are there other plugins that should be excluded on some targets?

* AutoFrontlight is only for Kindle, but it's deprecated already.
* AutoStandby is (currently) only for PB, but making that part of the build system may potentially be overcomplicating matters. (Concretely, to some extent hiding its existence from hackers on other platforms.)
* Timesync doesn't make any sense in the desktop or Android builds. (Perhaps it makes a certain type of sense on Android but it would never work as written.)

> Should the hello example plugin be excluded for all targets?

I wouldn't; see the remark about `tools` above.

**Comment by Frenzie** [comment]
That is, the reason `hello` doesn't make sense on Android and macOS is because you effectively can't hack there.

**Comment by benoit-pierre** [comment]
> > For kobo targets, the zip release includes koreader.png, but not the targz (or the OTA manifest), why?
> 
> The OTA only updates the /koreader folder. That image file is only for setup. (Same for PB.)

But only because we don't include those in the OTA manifest: the archive is unpacked from `koreader`'s parent directory, so there's no reason `koreader.png`, or `system/bin/koreader.app` on PB, could not be updated (similar to how `extensions/koreader/…` is on kindle), no?

Which would slightly simplify things.

**Comment by Frenzie** [comment]
I don't think it's a given that someone wants koreader.png "polluting" their Nickel books. I can't speak for PB.

**Comment by benoit-pierre** [comment]
> I don't think it's a given that someone wants koreader.png "polluting" their Nickel books.

Why include it then? What's its purpose?

**Comment by Frenzie** [comment]
It's for use with KFMon. Pinging @NiLuJe

**Comment by NiLuJe** [comment]
Yup, it's a one-time only kind of things, and if it needs to be updated, excluding it from the OTA is actually a feature, because you never know how Nickel might evolve/react if we were to update an indexed file behind its back.

**Review by Frenzie — APPROVED** [review]

**Comment by benoit-pierre** [comment]
Note: with the removal of `koreader/screenshots`, should be merged after #12750.

Can the removal of `koreader/clipboard` be problematic too?

**Comment by benoit-pierre** [comment]
> Can the removal of `koreader/clipboard` be problematic too?

I don't see any code to ensure the destination directory exists before creating the file in the different exporter plugin's implementations.

**Comment by Frenzie** [comment]
> Note: with the removal of koreader/screenshots, should be merged after https://github.com/koreader/koreader/pull/12750.

That's not necessary, see https://github.com/koreader/koreader/blob/24f983b580a059f40c730b05d6eee15000a1b633/datastorage.lua#L72-L96 (but there was no reason not to merge it first)

**Comment by Frenzie** [comment]
> I don't see any code to ensure the destination directory exists before creating the file in the different exporter plugin's implementations.

Pinging @pazos

**Comment by benoit-pierre** [comment]
I see, so there's only an issue if the default can be and is changed, and the directory does not exists.

**Pull request merged**
