### PR TITLE
Virtual keyboard: Scandinavian layouts (Norwegian, Swedish & Danish)

### PR DESCRIPTION
**Pull request by cookiebit**
Added Norwegian keyboard layout with the "æ", "ø", and "å" keys with some extra symbols for layer 3 and 4 (bullet points, arrows, checkmarks).

I also changed the language name for `nb_NO` from "Norsk" to "Norsk bokmål", since there are two written standards for the Norwegian language (bokmål and nynorsk), while there is only one Norwegian keyboard layout. This means that the UI and dictionaries could be in either "Norsk bokmål" or "Norsk nynorsk", but it makes no sense to call the keyboard layout anything besides "Norsk" ("Norwegian").

letters

symbols

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11365)

### CODE REVIEW

**Comment by Frenzie** [comment]
Very nice!

> I also changed the language name for `nb_NO` from "Norsk" to "Norsk bokmål", since there are two written standards for the Norwegian language (bokmål and nynorsk), while there is only one Norwegian keyboard layout. This means that the UI and dictionaries could be in either "Norsk bokmål" or "Norsk nynorsk", but it makes no sense to call the keyboard layout anything besides "Norsk" ("Norwegian").

Note that this does have the disadvantage that it won't be automatically selected when switching languages. There's currently no mechanism in place for anything other than a one to one relationship.

**Comment by cookiebit** [comment]
> Note that this does have the disadvantage that it won't be automatically selected when switching languages. There's currently no mechanism in place for anything other than a one to one relationship.

I see, I was not aware of that, so thanks for the info! Then I guess I'll change it so that the keyboard layout is tied to `nb_NO` instead of `no`, so that the keyboard layout is selected if the interface language is selected. This shouldn't be problematic or unintuitive as long as there is no "Norsk Nynorsk" translation for the interface yet anyway, and the majority of norwegians use the Bokmål standard. If/when there is a Nynorsk translation in place down the line, it's also possible to tie that to the same keyboard layout (even though the keyboard layout would have a "duplicate" entry in the layout list, which is suboptimal).

**Comment by Frenzie** [comment]
> Then I guess I'll change it so that the keyboard layout is tied to `nb_NO` instead of `no`, so that the keyboard layout is selected if the interface language is selected.

Yes, I think that's best in the short term.

**Comment by cookiebit** [comment]
> Yes, I think that's best in the short term.

Agreed. I'll consider adding Swedish and Danish keyboard layouts as well, since those are quite similar to the Norwegian one, and should therefore be relatively easy to implement.

**Review by Frenzie — APPROVED** [review]
Still draft on purpose?

**Comment by cookiebit** [comment]
> Still draft on purpose?

I'm fairly new to this, but it should be ready now. Think there's a couple of commits that could be omitted (sync), but I'm not sure if possible, or how.

**Comment by Frenzie** [comment]
git rebase -i followed by force push, but don't worry about it, I'll just squash them.

**Comment by cookiebit** [comment]
> git rebase -i followed by force push, but don't worry about it, I'll just squash them.

That seems to do the trick, yes. Thanks! I think I'll not push it now though, since I don't know how or if that will affect the pull request in any way in it's current state. The end result should be the same, just with a cleaner history.

**Comment by Frenzie** [comment]
I also recently learned about `git commit --fixup <SHA of commit to be fixed up>` from @wfdewith, which will automatically be squashed together during rebase. But not on GitHub! Only locally.

**Pull request merged**
