### PR TITLE
Reserve last good docsettings

### PR DESCRIPTION
**Pull request by Hzj-jie**
In case of any failure when writing docsettings, this change reserves the last good docsettings file.

### CODE REVIEW

**Comment by poire-z** [comment]
How should `Purge .sdr` behave with these `metadata.epub.lua.old` ?
Currently, they are not removed, and so neither is the .sdr/ directory. Which may be ok as the .old is a backup in case the user regrets purging it.
But there is now a ConfirmBox, and I added this Purge .sdr option mainly to clean these .sdr directories :)

**Comment by Frenzie** [comment]
Could add one of 'em CheckButtons[1] like on my phone.

screenshot_20170817-224443

[1] Coming whenever I find the time to do some finishing touches on #3088.

**Comment by poire-z** [comment]
I'm going to make a PR to remove the .old too on _Purge .sdr_.
Because if we _Purge .sdr_ to reset document settings, and if the .old, is still there, it is used (as the last good docsetting file) when we re-open the document :) and so we can no more really reset document settings :)

**Comment by poire-z** [comment]
Something I noticed thanks to the logs of this PR: when exiting reader (quiting, or switching to filemanager), `ReaderUI:saveSettings()` is called 2 times (so settings.reader.lua and metadata.lua are saved 2 times, and metadata.lua and metadata.lua.old end being the same).
https://github.com/koreader/koreader/blob/63241a20ea8e29860581300377d2e1466670b66f/frontend/apps/reader/readerui.lua#L553-L560

https://github.com/koreader/koreader/blob/63241a20ea8e29860581300377d2e1466670b66f/frontend/ui/uimanager.lua#L218-L226

https://github.com/koreader/koreader/blob/63241a20ea8e29860581300377d2e1466670b66f/frontend/apps/reader/readerui.lua#L516-L518

May be ce could remove the `self:saveSettings()` on readerui.lua:555, but I'm not sure.

**Comment by Hzj-jie** [comment]
Yes, saving settings in onClose() seems not right.

**Pull request merged**
