### PR TITLE
Add rename function for filemanager

### PR DESCRIPTION
**Pull request by Hzj-jie**
This change uses newly pushed commit 74e57274ab8d21b99e614bcf4c050e32f407feee @ koreader-base to implement rename function in filemanager.
This new feature proposal is discussed @ https://github.com/koreader/koreader/issues/1838

### CODE REVIEW

**Comment by houqp** [comment]
Thanks!

**Comment by KenMaltby** [comment]
The Rename function needs some way to navigate the file name, so that words other than at the end can be changed, without having to reenter existing text.

**Comment by Frenzie** [comment]
You should be able to tap where you want the cursor to be.

**Comment by poire-z** [comment]
Mentionning some edge case situation with file rename: when renaming the file extension.
e.g. renaming `LaTeX.EN.epub` to `LaTeX.EN.epubZZZ`:
```
/bin/mv: cannot move '/test/Wikipedia/LaTeX.EN.sdr'
    to a subdirectory of itself,
                     '/test/Wikipedia/LaTeX.EN.sdr/LaTeX.EN.sdr'
```
because their `.sdr/` dir are the same, and it would need renaming inside it the file `metadata.epub.lua` to `metadata.epubZZZ.lua`.

**Pull request merged**
