### PR TITLE
GestureDetector: Full refactor for almost-sane(TM) MT gesture handling

### LINKED ISSUE #9447: crash after increasing font size by gesture on the android device
* KOReader version: v2022.07
* Device: Google Pixel 4a(5G)
* Operating System: Android 13

#### Issue
I cannot change the font size on my pixel.

#### Steps to reproduce
Open any book and zoom out the font size by the gesture.

##### `crash.log` (if applicable)

[crash.log](https://github.com/koreader/koreader/files/9374055/crash.log)
[crash_1.log](https://github.com/koreader/koreader/files/9374054/crash_1.log)

### PR DESCRIPTION
**Pull request by NiLuJe**
The original idea, which stemmed from testing the base PR on Android, which revealed that everything was terrible, namely that we handled MT gestures on a first come, first served approach, *wihtout* keeping track of the *other* involved slot, which essentially led to either doubled gestures, wrong detection, nothing, or all of the above.

My initial, naive approach, which I sunk 4 days on, was to keep track of the MT pairing, and only act on an MT gesture once *both* involved slots had been lifted. In practice, this meant that the lifetime of a Contact became all wonky, because you couldn't destroy it on lift, and it ended up requiring an insane amount of brittle heuristics to somehow behave properly on all my devices.
(I also got sidetracked along the way by dealing with the Lua LSP server and Kate's handling of it, which ended up being resolved by a ["shut up, don't autocomplete empty space, you moron, let me use tab to indent empty space"](https://gist.github.com/NiLuJe/790d394dbc6fc4a32eca0c9ee115b61f) quick'n dirty patch, but it's actually pretty damn cool once it's no longer getting in your way ;))

So, the current approach is instead to only keep track of the MT pairing itself, of reacting on the first slot we see, *but* of inhibiting the paired slot from doing (almost) anything else but destroy itself on lift.
This turned out to require far fewer gymnastics, *except* for rotate handling, because it requires both slots to be in different states (one hold pivot, and a pan trigger), which severely complicates things (basically all the ugly things left are solely because of rotate, the rest of the trickiness involves dealing with inverted lifts, but that's simple enough as every other gesture requires both contacts to be in the same state).

* Depends on https://github.com/koreader/koreader-base/pull/1512 for proper Android support, (should fix #9447).
* Made contact points first-class objects, and made that object at the center of all the things. A contact is created on first down, and destroyed on lift (... *aaaaalmooost* every time, double-tap handling requires minor trickery there).
* Created a bunch of new MT gestures while I was in there (two_finger_hold & two_finger_hold_pan; with their release counterpart). Fun fact: this revealed that hold_pan had no specific hold_pan_release gesture, and instead sent a hold_release. As this behavior is relied on by existing code, I kept the (IMHO) bug as-is.
* UIManager: Simplified the weird-ass EventHook system used to plug into the InputEvent event, and made sure it would only dispatch *once* per input frame (because a 5 slot input frame would otherwise dispatch 5 times, ugh).
* Because rotate now actually works, I plugged it into GestureManager, dammit :D (and added a CCW rotation action to dispatcher, which mysteriously only add a CW one :?).
* The other new MT gestures have *NOT* been plugged into GestureManager (yet?). Mostly because I think the existing two-finger ones had minimal presence there to begin with? (Not a huge GestureManager user myself).
* Got rid of DCHANGE_WEST_SWIPE_TO_EAST & its buddy defaults, as we've been able to invert pageturns for a while now.
* Slightly lowered the pan threshold, because it helped accuracy when discriminating rotate from pinch/spread (and, well, actual pans, too, I guess? :D).
* Unified a few bits of code that were being precious snowflakes instead of using `Screen:scaleByDPI`
* Input: Simplified the timer callback handling, because the new Contact design ensures cleanup safety.
* ImageWidget: Make the zoom in/out somewhat more consistent, by ensuring the extrema can actually be reached in a non-confusing manner.
* Probably other things I've forgotten ;).

----

Don't, err, look at the amount of commits, this'll be a squash affair, those are just for documenting the nightmare ;D.
Draft because there's a crapload of debug logging that'll go poof before merge, but this iteration feels good (tested on a H2O, a Forma, an Elipsa, and a OnePlus 6, which should hopefully cover *most* of the input craziness out there).

The diff for gesturedetector is quite likely wholly unreadable, I'd just assume it's been entirely rewritten and take it from the top ;).

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9463)

### CODE REVIEW

**Comment by NiLuJe** [comment]
I fully expect to have entirely wreaked the useless gesturedetector testsuite. if so, that'll be "fixed" later.

**Comment by NiLuJe** [comment]
For shit'n giggles, the final state of the intermediate design would be https://github.com/koreader/koreader/pull/9463/commits/4bd7a9292bae89705118061cf0826b49e8bd4fbc ;).

**Comment by poire-z** [comment]
Indeed a bit too big to get into and review seriously :/ but it feels it will be easier to grasp with the reorg and your comments the day I have to put my nose in it again :)

Some thoughts about things to possibly verify they still work (that I remember I had to look at GestureDetector to understand a bit more of this stuff works):
- stuff using MovableContainer, that the various swipe, hold, pan (long press at start then move vs. short press and move and long hold before release) work as before - also especially DictQuickLookup, which forward some of these events
- the various scrolling options (classic, turbo, on-release, inertial), on slow eInk and on fast Android
- text selection in cre across page (selectin up to top left or bottom right corners)
- TextEditor, scrolling on the text and with tap/pan on the scrollbars

(Probably off-topic, and probably not a bug: I noticed recently that if you quickly do a tap followed by another _distant_ tap, that second tap is not considered a bounce and so is handled. Happens when holding the device and having to lose the balance by using a finger to tap, and quickly recovering the balance with another tap :) But it's also helpful when I want to quickly page forward without getting slowed down by my anti-bounce tap interval :)

**Comment by NiLuJe** [comment]
>     * stuff using MovableContainer, that the various swipe, hold, pan (long press at start then move vs. short press and move and long hold before release) work as before - also especially DictQuickLookup, which forward some of these events
> 

What's the expected behavior, FWIW? Because I'm not sure I ever got it to work as intended, ;o).



> * the various scrolling options (classic, turbo, on-release, inertial), on slow eInk and on fast Android

I wouldn't expect any issue on that front, as it's mostly ST, but good point, I'll check that on Monday (out tomorrow ;)).



> * text selection in cre across page (selectin up to top left or bottom right corners)

Ditto.

>     * TextEditor, scrolling on the text and with tap/pan on the scrollbars
> 
 
Ditto.




> I noticed recently that if you quickly do a tap followed by another _distant_ tap, that second tap is not considered a bounce and so is handled.

So, to be perfectly clear: two taps closely following each other in time, but physically (i.e., coordinates) far apart, right?

That.. possibly makes sense, I remember being surprised at exactly *when* the previous tap is saved and moving that a bit, and at a quick glance right now, it's still possibly not entirely kosher ;) (e.g., a bounce doesn't update the saved tap, not does a double tap).

**Comment by poire-z** [comment]
> What's the expected behavior, FWIW? Because I'm not sure I ever got it to work as intended, ;o).

It handles all these events:
https://github.com/koreader/koreader/blob/615072c7771ca801bbc1d70154956fac1d1b4b61/frontend/ui/widget/container/scrollablecontainer.lua#L76-L89
Just so that:
- swipe (quick touch and release): move in 90° directions only
- the others allow moving in any angle

> I wouldn't expect any issue on that front, as it's mostly ST

Yes, I was also not sure how much you've been touching :) If all this is mostly about the other events that nobody has been using because they worked badly , yes :) (I remember before multiswipes, I was using 2-fingers-swipe for Toc, and was often angry :)

> So, to be perfectly clear: two taps closely following each other in time, but physically (i.e., coordinates) far apart, right?

Right.

> for a bounce to be detected as such, it needs both to be in close proximity in time and coordinates 

Yes, I get that, seen that again when looking at this PR - so, probably normal.

**Comment by NiLuJe** [comment]
Fixed the tests, I'll deal with the extra debugging tomorrow, after doing some more testing re: previous comments ;).

**Comment by NiLuJe** [comment]
Mmkay, rebased, logging nerfed, this should be good :}.

(For 2022.09, that is ;p).

**Comment by NiLuJe** [comment]
(Merge was cleaner than a rebase because of intermediate commits that I don't want to mangle ;). Not an issue since this will ultimately be squashed).

**Comment by poire-z** [comment]
Just mentionning something I somehow just noticed when playing with ImageViewer: when using 2 fingers pinch/spread, 90% of the time, the bottom buttons row is toggled - which could mean that a Tap is somehow happening in there and processed.
Not investigating, but may be this will somehow be solved by this PR (?) (or it's just my Kobo GloHD IR touch layer that shows its crapiness...)

**Comment by NiLuJe** [comment]
> Just mentionning something I somehow just noticed when playing with ImageViewer: when using 2 fingers pinch/spread, 90% of the time, the bottom buttons row is toggled - which could mean that a Tap is somehow happening in there and processed. Not investigating, but may be this will somehow be solved by this PR (?) (or it's just my Kobo GloHD IR touch layer that shows its crapiness...)

This does fix a host of similar issues, yeah ;).

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 14 of 16 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/9463)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Frenzie, @pazos, and @poire-z)

**Comment by NiLuJe** [comment]
Let's unleash the Kraken ;o).

**Pull request merged**
