### PR TITLE
Adds a default.lua config for word gap

### PR DESCRIPTION
**Pull request by cramoisi**
@Frenzie @poire-z @robert00s  : any objection with that ? I find myself better with 65% than 75% and I don't want to maintain a branch just for that :grin:

### CODE REVIEW

**Comment by cramoisi** [comment]
@poire-z, ok, where do I have to define my variable ? :)

**Comment by poire-z** [comment]
Looks fine.
I think that's the right way to define available values (settings.reader.lua just stores the current default value).
Dunno if the variables would better be named DCREREADER_CONFIG_SPACE_CONDENSING_SMALL & co, so we see the setting name they map to, Word Gap being just a UI pretty name.

These allowed global variables are listed in:
https://github.com/koreader/koreader/blob/d8e58a08fd5c5039dc169028befeca1c3c5bcef4/.luacheckrc#L67-L72

**Comment by cramoisi** [comment]
Soo, it was just that :) I was thinking about something a lot more complicated... Thanks !

**Comment by poire-z** [comment]
Welcome to the fabulous world of unit tests fixing :)
(Mostly just some count number to increase by 3 cause you added 3 globals).

**Comment by cramoisi** [comment]
@poire-z it's not spec/front/unit/defaults_spec.lua  which need adaptation ?

**Comment by cramoisi** [comment]
```
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] spec/front/unit/defaults_spec.lua @ 9: defaults module should load all defaults from defaults.lua
[  FAILED  ] spec/front/unit/defaults_spec.lua @ 15: defaults module should save changes to defaults.persistent.lua
[  FAILED  ] spec/front/unit/defaults_spec.lua @ 91: defaults module should delete entry from defaults.persistent.lua if value is reverted back to default

```

**Comment by poire-z** [comment]
`spec/unit/defaults_spec.lua` (as it is named in the koreader repos, without the `front` part).

**Comment by cramoisi** [comment]
great :/ i will need help on this... I don't have any idea why there is some values and not the other

**Comment by poire-z** [comment]
https://github.com/koreader/koreader/blob/d8e58a08fd5c5039dc169028befeca1c3c5bcef4/spec/unit/defaults_spec.lua#L9-L13


You added 3 variables, so I guess that 74 (the previous nb of variables) should go to 77.
The CircleCI output can help, and it indeed says for that test:
```
spec/front/unit/defaults_spec.lua:11: Expected objects to be the same.
Passed in:
(number) 74
Expected:
(number) 77
```
(sometimes/always, the meaning of Passed in and Expected seems the reverse...)

https://github.com/koreader/koreader/blob/d8e58a08fd5c5039dc169028befeca1c3c5bcef4/spec/unit/defaults_spec.lua#L26
Same as previous one, but it will probably fail again after once you fixed this one, like the next one:
https://github.com/koreader/koreader/blob/d8e58a08fd5c5039dc169028befeca1c3c5bcef4/spec/unit/defaults_spec.lua#L15-L32
For this one, the setting are adressed by their number (I guess they are alphabetically sorted). So I guess the 3 you added have shifted some of them. So you may have to increase by 3 some of them.

https://github.com/koreader/koreader/blob/d8e58a08fd5c5039dc169028befeca1c3c5bcef4/spec/unit/defaults_spec.lua#L91-L125

I guess the `DHINTCOUNT = 2` that we want deleted is no more at index 25 (it could be at index 28).

I went thru the exact same tests with #3737, where I removed 3 variables:
https://github.com/koreader/koreader/commit/c93bbec40d4e5d6a229672e4985303fdb11900cd#diff-ac5ea444fdd0fd1f5ad122d441b4d4f8
So, you may just have to unchanged what I changed there :)

For testing, you can either run the unit tests locally (I never set it up, so I can't help), or keep pushing commits and have CircleCI tests them (that's my curse).

**Comment by cramoisi** [comment]
@poire-z Thanks (I figure it out just before you post the answer ;-) )

**Comment by cramoisi** [comment]
In fact I looked at your last commit to deduce how you work with the test unit...

**Comment by cramoisi** [comment]
ok, it's not +3 then...

**Comment by cramoisi** [comment]
only one fail left, perhaps I miss one +3

**Comment by cramoisi** [comment]
>For this one, the setting are adressed by their number (I guess they are alphabetically sorted). So I guess the 3 you added have shifted some of them. So you may have to increase by 3 some of them.

it's so messy  why everything doesn't want to be the same ? :D

**Comment by poire-z** [comment]
You can try adding just before something like:
```lua
for i=1, #Defaults.defaults_name do
  require("logger").warn(i, Defaults.defaults_name[i])
end
```
so you'll see the content in the CircleCI output.

**Comment by cramoisi** [comment]
@poire-z : the number of variables in defaults is more than 77 (it's 79 with mines) , so why the thing is at 74 to begin with ?

do we have any clue on the func which generate this array ?

**Comment by poire-z** [comment]
If `assert.is_same(#Defaults.defaults_name, 77)` doesn't failt, it's 77 in CircleCI, period :)
Why it would be 79 on your side, I dunno :)

> do we have any clue on the func which generate this array ?

you'd have to follow the code from the unit test
https://github.com/koreader/koreader/blob/c93bbec40d4e5d6a229672e4985303fdb11900cd/spec/unit/defaults_spec.lua#L3-L5
then
https://github.com/koreader/koreader/blob/d8e58a08fd5c5039dc169028befeca1c3c5bcef4/frontend/apps/filemanager/filemanagersetdefaults.lua#L59-L78

**Comment by cramoisi** [comment]
when ordered alphabetically, the variables are like this (which make sense if I removed the first line and reorder the small - medium - large in this order (and not alphabetically) 

ANDROID_FONT_DIR = "/system/fonts;/sdcard/koreader/fonts"
DALPHA_SORT_CASE_INSENSITIVE = true
DAUTO_SAVE_PAGING_COUNT = nil
DBACKGROUND_COLOR = 0
DCHANGE_EAST_SWIPE_TO_WEST = false
DCHANGE_WEST_SWIPE_TO_EAST = false
DCREREADER_CONFIG_DEFAULT_FONT_SIZE = 22    -- default font size
DCREREADER_CONFIG_FONT_SIZES = {12, 16, 20, 22, 24, 26, 28, 30, 34, 38, 44}  -- option range from 12 to 44
DCREREADER_CONFIG_LINE_SPACE_PERCENT_LARGE = 120
DCREREADER_CONFIG_LINE_SPACE_PERCENT_MEDIUM = 100
DCREREADER_CONFIG_LINE_SPACE_PERCENT_SMALL = 90
DCREREADER_CONFIG_MARGIN_SIZES_LARGE = {20, 20, 20, 20}
DCREREADER_CONFIG_MARGIN_SIZES_MEDIUM = {10, 15, 10, 15}
DCREREADER_CONFIG_MARGIN_SIZES_SMALL = {5, 10, 5, 10}
DCREREADER_CONFIG_WORD_GAP_LARGE = 100
DCREREADER_CONFIG_WORD_GAP_MEDIUM = 75
DCREREADER_CONFIG_WORD_GAP_SMALL = 50
DCREREADER_PROGRESS_BAR = 1
DCREREADER_TWO_PAGE_THRESHOLD = 7
DCREREADER_VIEW_MODE = "page"
DDICT_FONT_SIZE = 20
DDOUBLE_TAP_ZONE_NEXT_CHAPTER = {x = 6/8, y = 0, w = 2/8, h = 2/8}
DDOUBLE_TAP_ZONE_PREV_CHAPTER = {x = 0, y = 0, w = 2/8, h = 2/8}
DFULL_SCREEN = 1
DGLOBAL_CACHE_FREE_PROPORTION = 0.4
DGLOBAL_CACHE_SIZE_MAXIMUM = 1024*1024*60
DGLOBAL_CACHE_SIZE_MINIMUM = 1024*1024*10
DGLOBALGAMMA = 1.0
DHINTCOUNT = 1
DKOPTREADER_CONFIG_AUTO_STRAIGHTEN = 0    -- range from 0 to 10
DKOPTREADER_CONFIG_CONTRAST = 1.0        -- range from 0.2 to 2.0
DKOPTREADER_CONFIG_DEFAULT_WORD_SPACING = -0.2            -- range from (+/-)0.05 to (+/-)0.5
DKOPTREADER_CONFIG_DEFECT_SIZE = 1.0    -- range from 0.0 to 3.0
DKOPTREADER_CONFIG_DETECT_INDENT = 1    -- 1 = enable, 0 = disable
DKOPTREADER_CONFIG_DOC_DEFAULT_LANG_CODE = "eng"          -- that have filenames starting with the language codes
DKOPTREADER_CONFIG_DOC_LANGS_CODE = {"eng", "chi_sim"}    -- language code, make sure you have corresponding training data
DKOPTREADER_CONFIG_DOC_LANGS_TEXT = {"English", "Chinese"}
DKOPTREADER_CONFIG_FONT_SIZE = 1.0        -- range from 0.1 to 3.0
DKOPTREADER_CONFIG_JUSTIFICATION = 3    -- -1 = auto, 0 = left, 1 = center, 2 = right, 3 = full
DKOPTREADER_CONFIG_LINE_SPACING = 1.2    -- range from 0.5 to 2.0
DKOPTREADER_CONFIG_MAX_COLUMNS = 2        -- range from 1 to 4
DKOPTREADER_CONFIG_PAGE_MARGIN = 0.10    -- range from 0.0 to 1.0
DKOPTREADER_CONFIG_RENDER_QUALITY = 1.0    -- range from 0.5 to 2.0
DKOPTREADER_CONFIG_TEXT_WRAP = 0        -- 1 = on, 0 = off
DKOPTREADER_CONFIG_TRIM_PAGE = 1        -- 1 = auto, 0 = manual
DKOPTREADER_CONFIG_WORD_SPACINGS = {0.05, -0.2, 0.375}    -- range from (+/-)0.05 to (+/-)0.5
DLANDSCAPE_CLOCKWISE_ROTATION = true
DMINIBAR_CONTAINER_HEIGHT = 14  -- Larger means more padding at the bottom, at the risk of eating into the last line
DMINIBAR_FONT_SIZE = 14
DMINIBAR_HEIGHT = 7             -- Should be smaller than DMINIBAR_CONTAINER_HEIGHT
DMINIBAR_TOC_MARKER_WIDTH = 2   -- Looses usefulness > 3
DOUTER_PAGE_COLOR = 0
DOVERLAPPIXELS = 30
DRCOUNTMAX = 6
DRENDER_MODE = 0 -- 0 is COLOUR
DSCROLL_MODE = 1
DSHOWHIDDENFILES = false
DSHOWOVERLAP = false
DTAP_ZONE_BACKWARD = {x = 0, y = 0, w = 1/4, h = 1}
DTAP_ZONE_BOOKMARK = {x = 7/8, y = 0, w = 1/8, h = 1/8}
DTAP_ZONE_CONFIG = {x = 1/8, y = 7/8, w = 3/4, h = 1/8}
DTAP_ZONE_FLIPPING = {x = 0, y = 0, w = 1/8, h = 1/8}
DTAP_ZONE_FORWARD = {x = 1/4, y = 0, w = 3/4, h = 1}
DTAP_ZONE_MENU = {x = 1/8, y = 0, w = 3/4, h = 1/8}
DTAP_ZONE_MINIBAR = {x = 0, y = 15/16, w = 1, h = 1/16}
DUSE_TURBO_LIB = false
FOLLOW_LINK_TIMEOUT = 0.5
FRONTLIGHT_SENSITIVITY_DECREASE = 2
KOBO_LIGHT_ON_START = -2
KOBO_SYNC_BRIGHTNESS_WITH_NICKEL = true
NETWORK_PROXY = nil
SEARCH_AUTHORS = true
SEARCH_CASESENSITIVE = false
SEARCH_LIBRARY_PATH  = ""
SEARCH_LIBRARY_PATH2 = ""
SEARCH_PATH = true
SEARCH_SERIES = true
SEARCH_TAGS = true
SEARCH_TITLE = true

**Comment by poire-z** [comment]
Because those with `= nil` are just like they are not there. 79 -2 'nil' = 77.
(to delete an item in lua, you use `table[that_item] = nil`)

**Comment by cramoisi** [comment]
thanks ! I guess I begin to sort things out

**Comment by cramoisi** [comment]
YEAGHHHHHHFDHSFQHSH !

**Comment by poire-z** [comment]
Welcome to the fabulous and glorious world of unit tests fixing :)

**Comment by cramoisi** [comment]
huhu :D at least now I understand the way this file do its thing (thanks to you :+1: )

**Comment by cramoisi** [comment]
It was so painful that I kind of regret I have to delete it ;p

**Pull request merged**
