### PR TITLE
BookMap: fix help text wording

### PR DESCRIPTION
**Pull request by poire-z**
See https://github.com/koreader/koreader/pull/10530#discussion_r1217635869.

@Frenzie: please have a look at the new strings appearing in weblate, that I didn't miss/mess anything else :)

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10544)

### CODE REVIEW

**Comment by Frenzie** [comment]
A bit hard to tell. It seems to have been broken since #10492.

**Comment by poire-z** [comment]
> A bit hard to tell. It seems to have been broken 

What "it" ?
Weblate and our translations abilities are broken?

**Comment by Frenzie** [comment]
Not Weblate, but that PR broke the tests and the underlying assumption I
put in there is that we don't want to bother translators with something
that may be reverted because it's broken.

**Comment by poire-z** [comment]
Not really following you :/
Was just wondering if my split of long help texts into 2 or 3 bits was ok, ie. translators are able to notice that, reuse the previous longer single text as the suggestion for the 2 or 3 bits, etc...
Anyway, is this PR good to go ?

**Comment by Frenzie** [comment]
https://github.com/koreader/koreader/runs/13993281963 fails, so docs and translation are blocked from running.

**Pull request merged**
