### PR TITLE
OPDS: Don't needlessly setup Basic auth

### PR DESCRIPTION
**Pull request by NiLuJe**
InputDialog returns empty strings, not nil. Explicitly nil username ~~& password~~ when they're empty to avoid enabling authentication.

Also, re #7370, explicitly request no compression. Doesn't fix the actual issue because the server doesn't obey, breaking the RFC. Most servers were already assuming no Accept-Encoding header meant that we really didn't want gzip data ;p.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7372)

### CODE REVIEW

**Comment by hius07** [comment]
> Doesn't fix the actual issue

Maybe some workarounds especially for this server?
flibusta.is is blocked in Russia, this is the working mirror for them.

**Comment by NiLuJe** [comment]
PRs welcome to handle `Content-Encoding: gzip` ;o).

**Comment by hius07** [comment]
On that server I cannot even get the books list, OPDS browser gives a message 'Catalog not found'.

**Comment by NiLuJe** [comment]
Yep, because it's serving gzip data instead of plaintext ;).

**Pull request merged**
