### PR TITLE
ListMenu: correct access to doc settings

### PR DESCRIPTION
**Pull request by hius07**
Self-explained

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10119)

### CODE REVIEW

**Review by poire-z — APPROVED** [review]

**Comment by NiLuJe** [comment]
:lgtm:

If you're feeling bored, a quick grep reveals other contenders:

```
frontend/ui/widget/filechooser.lua
frontend/apps/filemanager/filemanagerutil.lua
plugins/wallabag.koplugin/main.lua
plugins/coverbrowser.koplugin/mosaicmenu.lua
```

;o).

**Comment by NiLuJe** [comment]
Oh, may conflict with #9939 ;).

**Comment by poire-z** [comment]
Hijacking a random Detailed list issue to share my thoughts about https://www.mobileread.com/forums/showthread.php?t=352630:

> Do you need a setting to disable this feature in the Detailed list mode? 

That's the wrong question to ask :)
The right question is: do you really want to see "No coracao do mar: A..." ?!
And even if this user answers yes, I'm pretty certain he will not like it and will end up not using that new setting.

**Comment by hius07** [comment]
He insists as you can see.

**Comment by poire-z** [comment]
But we don't have to give in :)
He would have to explain _why_ he wants a fixed font size with the obvious side effect that lots of titled will be truncated (and what about authors where they are multiple?).
The only reason I can imagine is some kind of psychorigidness, and the will to have everything tidy and aligned - but in our book browser context, is has no real sense:
- it's a tool to help you see your library and select the next book - it's not something you contemplate for minutes to appreciate how nice and fixed the font size is ! You want the info, and that's what we give. (In classic mode, I think at first we had a fixed font size + truncation, and we added "shrink..." because it was obvious seeing the full filename is better.
- would he write to a paperbook publisher, complainig that books in the same collection don't have all their titles on the spine in a same font size - and that he prefers the title on the spine truncated, but with all those in the collection with the same font size, because it would look nicer on my shelves, and, you know, if I want to read the full book title, I can just pick the book out of the shelve and read the full title on the cover ! :)

I could understand that mind, but I don't think we have to propose that - unless I hear a better reason for that.
I think it would be best left to a user-patch, but contemplating listmenu.lua, I don't see a simple way to user patch all that :/

**Pull request merged**
