### PR TITLE
Allow use reserved characters in FTP username and FTP password 

### PR DESCRIPTION
**Pull request by robert00s**
Close: #3641 
Should fix this problem: Cloud storage (FTP) doesn't work when password contains "@" #3641
FTP username and password are now encoding that allow use reserved characters:
!  *  '  (  )  ;  :  @  &  =  +  $  ,  /  ?  #  [  ]
See: https://en.wikipedia.org/wiki/Percent-encoding

### CODE REVIEW

**Comment by robert00s** [comment]
I tested with this page: https://www.url-encode-decode.com/
More information is also on wikipedia: https://en.wikipedia.org/wiki/Percent-encoding
Look that `!` (exclamation mark) and `*` (asterisk) should also be encoded as `%21` and `%2A`.
Space is coded as `%20` or sometimes as `+`. I used `+` but I can change to `%20` if you want.
In my cases (parse ftp url) important is to encode/decode `@` `:` and `/`.

**Comment by Frenzie** [comment]
That page presumably uses PHP's [urlencode()](https://secure.php.net/manual/en/function.urlencode.php) function, which is not RFC 3986 compliant.

> Returns a string in which all non-alphanumeric characters except -_. have been replaced with a percent (%) sign followed by two hex digits and spaces encoded as plus (+) signs. It is encoded the same way that the posted data from a WWW form is encoded, that is the same way as in application/x-www-form-urlencoded media type. This differs from the » RFC 3986 encoding (see rawurlencode()) in that for historical reasons, spaces are encoded as plus (+) signs.

**Comment by robert00s** [comment]
Now should be better - I hope

**Comment by Frenzie** [comment]
Seems okay. :-)

**Pull request merged**
