### PR TITLE
[UX] ReaderGesture: More gestures (suspend, history, rotation)

### PR DESCRIPTION
**Pull request by Frenzie**
References  #4333.

### CODE REVIEW

**Comment by Frenzie** [comment]
@poire-z Any comments on this one? It's also very simple. ;-)

**Comment by poire-z** [comment]
None, simple indeed :)

**Comment by AlanSP1** [comment]
Only for wiki purposes, can someone mention all gestures we have at the moment, including gestures that can be managed within gesture manager?

I'm not sure if wiki is complete on this and I can't read code to see what we have and have not

**Comment by Frenzie** [comment]
All gestures is a bit difficult, unless you mean in generalities. The current wiki page is basically still accurate. https://github.com/koreader/koreader/wiki/KOReader-Gestures

https://github.com/koreader/koreader/blob/333f8658bb3aeef8e75ce9a744a6dacd73e9c9a9/frontend/device/gesturedetector.lua#L6-L23

The full list of actions available in Gesture Manager atm is here:

https://github.com/koreader/koreader/blob/1623acc007d9c864771e2df8e3a1a04615268b90/frontend/apps/reader/modules/readergesture.lua#L64-L80

I also have a local branch with a never finished idea about multidirection gestures, but that was pre-gesture manager. Now that the gesture manager exists the part I didn't really want to tackle just might be a relatively minor effort…

```diff
diff --git a/frontend/device/gesturedetector.lua b/frontend/device/gesturedetector.lua
index 5eb63dcb..d857997b 100644
--- a/frontend/device/gesturedetector.lua
+++ b/frontend/device/gesturedetector.lua
@@ -72,6 +72,8 @@ local GestureDetector = {
     -- latest feeded touch event in each slots
     last_tevs = {},
     first_tevs = {},
+    -- for multiswipe gestures
+    multiswipe_directions = {},
     -- detecting status on each slots
     detectings = {},
     -- for single/double tap
@@ -162,9 +164,11 @@ end
 --[[--
 Compares `last_pan` with `first_tev` in this slot.
 
+The second boolean argument `simple` results in only four directions if true.
+
 @return (direction, distance) pan direction and distance
 --]]
-function GestureDetector:getPath(slot)
+function GestureDetector:getPath(slot, simple)
     local x_diff = self.last_tevs[slot].x - self.first_tevs[slot].x
     local y_diff = self.last_tevs[slot].y - self.first_tevs[slot].y
     local direction = nil
@@ -172,8 +176,9 @@ function GestureDetector:getPath(slot)
     if x_diff ~= 0 or y_diff ~= 0 then
         local v_direction = y_diff < 0 and "north" or "south"
         local h_direction = x_diff < 0 and "west" or "east"
-        if math.abs(y_diff) > 0.577*math.abs(x_diff)
-            and math.abs(y_diff) < 1.732*math.abs(x_diff) then
+        if not simple
+           and math.abs(y_diff) > 0.577*math.abs(x_diff)
+           and math.abs(y_diff) < 1.732*math.abs(x_diff) then
             direction = v_direction..h_direction
         elseif (math.abs(x_diff) > math.abs(y_diff)) then
             direction = h_direction
@@ -212,6 +217,10 @@ function GestureDetector:switchState(state_new, tev, param)
     return self[state_new](self, tev, param)
 end
 
+function GestureDetector:clearMultiSwipeDirections()
+    self.multiswipe_directions = {}
+end
+
:...skipping...
diff --git a/base b/base
--- a/base
+++ b/base
@@ -1 +1 @@
-Subproject commit c80f1a842573839328601eb55c09fe87e5e52fbc
+Subproject commit c80f1a842573839328601eb55c09fe87e5e52fbc-dirty
diff --git a/frontend/device/gesturedetector.lua b/frontend/device/gesturedetector.lua
index 5eb63dcb..d857997b 100644
--- a/frontend/device/gesturedetector.lua
+++ b/frontend/device/gesturedetector.lua
@@ -72,6 +72,8 @@ local GestureDetector = {
     -- latest feeded touch event in each slots
     last_tevs = {},
     first_tevs = {},
+    -- for multiswipe gestures
+    multiswipe_directions = {},
     -- detecting status on each slots
     detectings = {},
     -- for single/double tap
@@ -162,9 +164,11 @@ end
 --[[--
 Compares `last_pan` with `first_tev` in this slot.
 
+The second boolean argument `simple` results in only four directions if true.
+
 @return (direction, distance) pan direction and distance
 --]]
-function GestureDetector:getPath(slot)
+function GestureDetector:getPath(slot, simple)
     local x_diff = self.last_tevs[slot].x - self.first_tevs[slot].x
     local y_diff = self.last_tevs[slot].y - self.first_tevs[slot].y
     local direction = nil
@@ -172,8 +176,9 @@ function GestureDetector:getPath(slot)
     if x_diff ~= 0 or y_diff ~= 0 then
         local v_direction = y_diff < 0 and "north" or "south"
         local h_direction = x_diff < 0 and "west" or "east"
-        if math.abs(y_diff) > 0.577*math.abs(x_diff)
-            and math.abs(y_diff) < 1.732*math.abs(x_diff) then
+        if not simple
+           and math.abs(y_diff) > 0.577*math.abs(x_diff)
+           and math.abs(y_diff) < 1.732*math.abs(x_diff) then
             direction = v_direction..h_direction
         elseif (math.abs(x_diff) > math.abs(y_diff)) then
             direction = h_direction
@@ -212,6 +217,10 @@ function GestureDetector:switchState(state_new, tev, param)
     return self[state_new](self, tev, param)
 end
 
+function GestureDetector:clearMultiSwipeDirections()
+    self.multiswipe_directions = {}
+end
+
 function GestureDetector:clearState(slot)
     self.states[slot] = self.initialState
     self.detectings[slot] = false
@@ -455,6 +464,8 @@ function GestureDetector:handlePan(tev)
         return self:handleTwoFingerPan(tev)
     else
         local pan_direction, pan_distance = self:getPath(slot)
+        local simple_pan_direction = self:getPath(slot, true)
+
         local pan_ev = {
             ges = "pan",
             relative = {
@@ -474,6 +485,15 @@ function GestureDetector:handlePan(tev)
             y = self.last_tevs[slot].y,
             w = 0, h = 0,
         }
+
+        if #self.multiswipe_directions == 0
+           or self.multiswipe_directions[#self.multiswipe_directions][1] ~= simple_pan_direction then
+            self.multiswipe_directions[#self.multiswipe_directions+1] = {
+                [1] = simple_pan_direction,
+                [2] = pan_ev,
+            }
+        end
+
         return pan_ev
     end
 end
@@ -557,6 +577,7 @@ function GestureDetector:handlePanRelease(tev)
     else
         logger.dbg("pan release detected in slot", slot)
         self:clearState(slot)
+        self:clearMultiSwipeDirections()
     end
     return pan_ev
 end
```

**Comment by AlanSP1** [comment]
OK, if it is still accurate, then there's no need to edit it.

Also, by look of the page, it will also look pretty complex, to mention all gestures and what they do in all possible situations...

**Pull request merged**
