### PR TITLE
frontlight on kobo: a few fixes

### LINKED ISSUE #2974: Frontlight flashes then turns off upon launching; KOReader↔Nickel frontlight sync broken
* KOReader version: v2015.11-1064-gbd92d68
* Device: Kobo Glo HD

#### Issue
Another bug introduced by #2941.
1. Current frontlight value is no longer synced to Nickel's config file.
    (if `KOBO_SYNC_BRIGHTNESS_WITH_NICKEL = true`(default))
2. `KOBO_LIGHT_ON_START` is completely ignored.
    KOReader always starts with the frontlight on, intensity 20.
    * This happens regardless of the value in `KOBO_LIGHT_ON_START`

Expected behavior: (`defaults.lua`)
```
KOBO_LIGHT_ON_START = -2           -- -1, -2 or 0-100. -1 leaves light as it
                                   -- is, -2 uses 'Kobo eReader.conf', other
                                   -- sets light on start/wake up
KOBO_SYNC_BRIGHTNESS_WITH_NICKEL = true  -- Save brightness set in KOreader
                                         -- with nickel's 'Kobo eReader.conf'
```

This issue appeared in `v2015.11-1059-g63f2284`

### PR DESCRIPTION
**Pull request by poire-z**
Closes #2974.
I modified Kobo frontlight code to not update `Kobo eReader.conf` on every frontlight change, and never if `KOBO_SYNC_BRIGHTNESS_WITH_NICKEL = false`.
So, I reintroduced the global settings `frontlight_intensity` and `is_frontlight_on` that were removed in june to keep level and state across koreader sessions.

I hope this fix most of the remaining issues on kobo light, and I think it should answer the unresolved problems in #2974 (and hopefully, won't introduce new ones...)
Also ensure settings are saved when needed.
Also fixed: any settings set while in File Browser were not saved when rebooting/powering off from File browser.

The only changes from the advertised behaviour (in `default.lua`) are:
- setting KOBO_LIGHT_ON_START=-1 saves level and state only in `settings.reader.lua`, and restores light across koreader sessions (dunno how was previous behaviour, as we couldn't guess values for "let light as it"). If there is sense to keep this -1 behaviour, i'll introduce a -3 to save only in koreader settings.
- for people who set KOBO_LIGHT_ON_START to a number >= 0: when suspending and resuming, light is set how it was before suspend (and no more to this KOBO_LIGHT_ON_START value - that seems more natural to me, even if setting a fixed value for light on start seems not :).

I've tested that with different values for the KOBO_* settings, and it works fine.
I haven't tested it on firmware versions that set `FrontLightState` in `Kobo eReader.conf`, but from what I understood, it should work fine.

@Hzj-jie : could you check if these changes are faithful to your work on frontlight from last june ?
@djalma2k @a-kohout : if you're able to backup/patch a PR on your device, could you check if this PR solves your issues (@djalma2k: without and with the `FrontLightState=` you added manually to your `Kobo eReader.conf`)

There's a thing that may be a possible bug (that was not noticed on kobo before this change, probbly because of the way state was saved in nickelconf) in BasePowerd:
https://github.com/koreader/koreader/blob/568e8f667a42ba80dd519c7471e4c4b78b7c58aa/frontend/device/generic/powerd.lua#L130-L132
It looks to me `self:_decideFrontlightState()` should be called after `self:_setIntensity(self.fl_intensity)` so that frontlight state (`is_fl_on`) is accurate if we set some intensity > 0 when we were toggled off.
Could someone on Kindle (@robert00s ?) test the following:
frontlight widget > set some positive level > toggle Off > use +1 or set some positive level from the bar
Are the values and progress bar updated correctly then, or does it need a second set or toggle?
If it's fine on Kindle, i'll remove my comment and let that second call for kobo only. Otherwise, i'll fix that in `generic/powerd.lua`.

### CODE REVIEW

**Comment by poire-z** [comment]
(Hold on, changes I made for the unit test that failed have side effects)

**Comment by poire-z** [comment]
OK, should be good now (for units tests, and for real devices that have a kobolight.open() that works).

**Comment by robert00s** [comment]
@poire-z 

> It looks to me self:_decideFrontlightState() should be called after self:_setIntensity(self.fl_intensity) so that frontlight state (is_fl_on) is accurate if we set some intensity > 0 when we were toggled off.
> Could someone on Kindle (@robert00s ?) test the following:
> frontlight widget > set some positive level > toggle Off > use +1 or set some positive level from the bar
> Are the values and progress bar updated correctly then, or does it need a second set or toggle?

It works fine on Kindle.

**Comment by poire-z** [comment]
Thanks for the test.
Comment updated in the code (and 2nd call to self:_decideFrontlightState() only for Kobo).

**Comment by a-kohout** [comment]
I've noticed the following problems with `KOBO_LIGHT_ON_START = -2` and `KOBO_SYNC_BRIGHTNESS_WITH_NICKEL = true`

* Toggle (Widget and one-finger gesture) does not work when `FrontLightLevel` == 0 (in `Kobo eReader.conf`)

  Idea:
  * If `FrontLightLevel` == 0 (in `Kobo eReader.conf`) AND `frontlight_intensity` == 0 (in `settings.reader.lua`)
      * Raise light value to 1, leave light off.
         (This is probably equivalent to `fl_min=1`)
  * if `FrontLightLevel` == 0 (in `Kobo eReader.conf`)
      * Restore `frontlight_intensity` (from `settings.reader.lua`), leave light off.

  This would conveniently restore the light back to its previous level upon pressing toggle.


* I've also noticed a minor UI issue with the light representation bar in the frontlight widget.
  When the light is off, one block is filled, same as light levels 1-4.
  Instead, all blocks should be empty when the light is off.

**Comment by poire-z** [comment]
Good catch, implemented your suggestion. Can I assume everything else is working fine ? :)

> I've also noticed a minor UI issue with the light representation bar in the frontlight widget. When the light is off, one block is filled, same as light levels 1-4. Instead, all blocks should be empty when the light is off.

Yes, I noticed that too. But i'll let that for another frontlightwidget PR :)
It's not obvious: il you have 0-10 light levels, il makes 11 blocks, so one can tap on the 1st to set zero: should this 1st block be black ? If not, tapping on it would behave differently from others blocks.
If we had only 10 blocks, taping on the 1st would set light to 1, and 0 wouldn't be accessible from the bar.

**Comment by djalma2k** [comment]
I have checked this PR against c24d75f and so far so good. All is working as it should with and without "FrontLightState=".
But please take in account what I said here: https://github.com/koreader/koreader/pull/3143#issuecomment-326335471 
(I had to add the "FrontLightState=" parameter because of  #1902 bug, but this don't happen rightnow. In fact, with "FrontLightState=" parameter present, I currently """"catch a bug""" that consist in when you turn off the light in koreader pressing the toggle button, and then you go to nickel, you got the light is on, which indicate that nickel 3.19 really don't take account the  "FronLightState=" parameter and finally I guess that for my device the safest setting is delete it.I don't know if any other firmwares/devices need it in anyway... (maybe devices with a specific hardware button ?¿?))

> I've also noticed a minor UI issue with the light representation bar in the frontlight widget.
> When the light is off, one block is filled, same as light levels 1-4.
> Instead, all blocks should be empty when the light is off.

Yep, this happen since
`Change fl_min = 1 to fl_min = 0`
anyway in previous versions with fl_min = 1, you can set negative values and the light bar did weird things in those cases...

Regards.

**Comment by poire-z** [comment]
Thanks for the tests.

> But please take in account what I said 

Yes, I understood. But as you did add it, some other people may have done the same thing, so I just wanted to be sure it would be fine for these (probably rare) persons too: that the bug you caught would not happen anymore, without any manual removal of the once added FrontLightState.

(About the minor UI issue : highlighted block at 0, I guess it must be there on Kindle too, as all devices now have fl_min=0.)

**Comment by a-kohout** [comment]
I didn't realize that by tapping the first block the light can be turned off.
Since there's the "toggle" button, I don't think that this is needed.
There are 21 blocks on my Kobo Glo HD.
I would propose for 20 blocks, so touching the first block would turn the light to 1.
When the light is off all blocks should be white.

Now the light handling is perfect :-) 👍

**Comment by Frenzie** [comment]
@poire-z Is this ready to be merged? It seems to behave okay to me but I'm not exactly an expert light tester. :-P

**Comment by poire-z** [comment]
I think so, My tests + 2 positive reports + yours now = good to go :)

**Pull request merged**
