### PR TITLE
Fix: truncateTextByWidth() should respect kerning and bold

### PR DESCRIPTION
**Pull request by robert00s**
It is not useful at this time, but it will be used by me in the future.

### CODE REVIEW

**Comment by poire-z** [comment]
There is (only) one place that is currently using the 4th parameter:
https://github.com/koreader/koreader/blob/1ab2a542dd31fb899d670370b23654390036c8c6/frontend/ui/widget/keyvaluepage.lua#L158
So after your change or orderning, this one there will not get a prepended space.

**Comment by robert00s** [comment]
You're right, I did not notice it.

**Comment by poire-z** [comment]
Or may be keep your original order (so it mirrors the one of getSubTextByWidth(), with an additional `prepend_space` parameter, and change keyvaluepage.lua to use 
```
self.show_value = RenderText:truncateTextByWidth(self.value, self.cface, frame_internal_width - key_w_rendered,
   false, false, true)
```
Not sure.

**Comment by robert00s** [comment]
Ok. It sounds better :)

**Pull request merged**
