### PR TITLE
Frontlight warmth gesture fixed step

### LINKED ISSUE #11220: FR: Kindle - Gestures - Equal steps for warmth
**Does your feature request involve difficulty completing a task? Please describe.**
Can we please have an option to increment frontlight warmth by a fixed and equal amount?

Currently, "Decrease warmth by 1" is doing 5%, "Increase warmth by 1" is doing 4%. 

I understand that this might because of the ceiling/floor roundings, and because there are 24 levels in Kindle, and 100/24 = 4.16 :D 

However it is very distracting when I want to compare before and after of the screen warmth by swiping up and down the right edge. 

Currently I am just using a gesture to call the whole frontlight dialog.

### PR DESCRIPTION
**Pull request by mergen3107**
Fixes #11220 

It works great on Kindle Scribe when `Increase/Decrease frontlight warmth` is set to `1` in gesture manager.

However, `3` and higher again gives inconsistent results.

Do you guys have a better suggestion for `round` function? There is no built-in regular `round` function, that rounds to lower value if decimal <0.5, and to higher value if >=0.5.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11225)

### CODE REVIEW

**Comment by NiLuJe** [comment]
I'd just keep the increment as-is and apply it in the native scale.

You should be able to finaggle somethign together with `powerd:fromNativeWarmth` / powerd:toNativeWamth` (c.f., frontend/ui/widget/frontlightwidget.lua)

**Comment by NiLuJe** [comment]
This should also be using `powerd:frontlightWarmth()` instead of poking at `powerd.fl_warmth` directly.

**Comment by NiLuJe** [comment]
And be a dedicated function for the increment dispatcher actions, leaving the edge swipe alone as-is.

**Comment by mergen3107** [comment]
Thanks @NiLuJe !
I'll try to convert increment to natural scale, so that unit = %

**Comment by poire-z** [comment]
> There is no built-in regular round function

There is a round function, in the Math module (there is another non-builtin `Math` module with more functions than in the `math` builtin which has floor/ceil):
```lua
local Math = require("optmath")
Math.round(num)
```

**Comment by mergen3107** [comment]
Thanks @poire-z !

I'll convert this PR to a draft, with hopes to gather enough experience to convert it to a user patch :D 

I don't wanna break someone else's gesture habits

**Comment by mergen3107** [comment]
(Couldn't turn it to a draft from mobile, closed for now)

**Comment by mergen3107** [comment]
Thanks @poire-z ! I tested `Math.round(num)` and it resulted in having consistent 4% up and down.
More refined than 5% I had before.

However, this whole "jerry rig" in now not required - thanks to NiLuJe who fixed all that stuff in #11226

**Pull request closed without merging**
