### PR TITLE
Minor changes of gesture manager

### PR DESCRIPTION
**Pull request by robert00s**
* Fix name: Table of contents
* Extend full refresh

### CODE REVIEW

**Comment by Frenzie** [comment]
Odd, the changes in this PR are giving me a strong sense of déjà vu. :)

**Comment by poire-z** [comment]
Oups, my bad, I suggested "Table of content" singular. And we indeed have it written plural in the TOC title.
(I must have never really looked at that title :) but it sounds strange to me, I would still write it singular. Isn't it that kind of word that you mentionned already a few times, like "info", that is written singular even if it means multiple? I thought it would be like that: we have some content, some text, some info, even if we have many of each :)

**Comment by poire-z** [comment]
OK, I guess I got my wrong feeling from the french _contenu_ which is most often singular.

**Comment by Frenzie** [comment]
@poire-z Just came across the same issue in frontend/apps/filemanager/filemanagermenu.lua:118

**Pull request merged**
