### PR TITLE
Autostandby: Fix variable ref.

### PR DESCRIPTION
**Pull request by ezdiy**
Since circleci decided to ignore everything I spam around until it's too late for some reason, I'll run luacheck manually from now on, pinky promise.

(./kodev is unfortunately badly broken on archlinux, so have to go a little blind wrt testing)

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/6612)

### CODE REVIEW

**Comment by pazos** [comment]
> kodev is unfortunately badly broken on archlinux

can you open an issue? I hope is not too hard to fix it.

**Comment by ezdiy** [comment]
Will do if it turns out to be indeed problem on koreader end (it seems more like just my desktop build env being kinda janky).

**Comment by Frenzie** [comment]
I don't know what you did but it looks like you sabotaged it. ;-)
Screenshot_2020-09-01_07-47-18

**Comment by yparitcher** [comment]
> (./kodev is unfortunately badly broken on archlinux, so have to go a little blind wrt testing)

works fine on my archlinux, i have this in my .bashrc to setup the paths.
```bash
# add kindle TC and lua tools to PATH
PATH=$PATH:~/x-tools/arm-kindlepw2-linux-gnueabi/bin:~/.luarocks/bin

# export lua library paths
export LUA_PATH='/usr/share/lua/5.1/?.lua;/usr/share/lua/5.1/?/init.lua;/usr/lib/lua/5.1/?.lua;/usr/lib/lua/5.1/?/init.lua;./?.lua;./?/init.lua;/home/USER/.luarocks/share/lua/5.1/?.lua;/home/USER/.luarocks/share/lua/5.1/?/init.lua'
export LUA_CPATH='/usr/lib/lua/5.1/?.so;/usr/lib/lua/5.1/loadall.so;./?.so;/home/USER/.luarocks/lib/lua/5.1/?.so'
```

**Comment by ezdiy** [comment]
@yparitcher Any idea how to make everything lua default to 5.1? I have everything ranging from 5.4 to 5.2 (luarocks, busted) with hardcoded library versions it seems, but that's just naive pacman install that barely works with manual invocation. Stock arch doesn't seem to have useable 5.1 runtime, aside doing everything by hand.

**Comment by yparitcher** [comment]
> @yparitcher Any idea how to make everything lua default to 5.1? I have everything ranging from 5.4 to 5.2 (luarocks, busted) with hardcoded library versions it seems, but that's just naive pacman install that barely works with manual invocation. Stock arch doesn't seem to have useable 5.1 runtime, aside doing everything by hand.

do you have the lua51 and luarocks packages installed?

**Comment by yparitcher** [comment]
also make sure to relplace `USER` in the path i attached before with your username

**Pull request merged**
