### PR TITLE
VirtualKeyboard: add option to initialize keyboard with height

### PR DESCRIPTION
**Pull request by roygbyte**
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8561)

### CODE REVIEW

**Comment by roygbyte** [comment]
Sorry about those other commits being dragged into this. Still haven't got the hang of cherry picking... But I have the git manual on my reading table so I hope to be catching up soon :')

**Comment by hius07** [comment]
Is this new feature going to be used anywhere?
(Together with the mysterious background in TextBoxWidget?)

**Review by Frenzie — APPROVED** [review]
lgtm in principle, but it is a bit unclear to me what kind of integer values you want to pass in there. :-)

**Comment by poire-z** [comment]
In a [crossword user-plugin](https://github.com/roygbyte/crossword.koplugin). There's been a bit of discussion in https://gitter.im/koreader/koreader (may be you'll have some idea about his virtualkeyboard issue).

I merged [_the mysterious background in TextBoxWidget_](https://github.com/koreader/koreader/pull/8559) because it seems to me it was the only solution to get text on a non-white background (unlike TextWidget which allows it) - even if nothing core needs it currently, it's good to have.

And I'd rather have this unused-by-core keys_height in here, than having to make this crossword plugin a core plugin :)
But I'd rather wait and let this open so @roygbyte can add any other thing he needs - and we'll merge all this unused-by-core stuff at the end (or not if this plugin ends up being abandonned).

**Comment by hius07** [comment]
Cool, thanks!
Are there any mockups to view an idea?

**Comment by roygbyte** [comment]
@hius07 Here is a recent screenshot. kocrossword_wip

**Comment by roygbyte** [comment]
I'm going to ship the plugin with it's own keyboard module, a slimmed down version of `virtualkeyboard`.

**Pull request closed without merging**
