### PR TITLE
set scroll mode as default

### PR DESCRIPTION
**Pull request by houqp**
close https://github.com/koreader/koreader/issues/2157
relies on https://github.com/koreader/koreader-base/pull/445

### CODE REVIEW

**Comment by houqp** [comment]
ha, scroll mode broke some of the tests

**Comment by chrox** [comment]
Good, that is the beauty of CI.

**Comment by houqp** [comment]
bed time for me, i will update those tests tomorrow :)

**Comment by chrox** [comment]
Looks great.

**Comment by houqp** [comment]
Did a last minute push, found a real bug, hehe :)

**Comment by houqp** [comment]
missed https://github.com/koreader/koreader-base/pull/445?

**Pull request merged**
