### PR TITLE
Another round of tweaks

### PR DESCRIPTION
**Pull request by NiLuJe**
Mostly centered around ExternalKeyboard ;).

Namely, navigation now works as expected in the FM & Reader.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9717)

### CODE REVIEW

**Comment by NiLuJe** [comment]
(Rebase me).

(Also, fix commit messages typos)

**Comment by NiLuJe** [comment]
(Why the macOS build succeeds in base but fails in front is anyone's guess ;o)).

**Comment by Frenzie** [comment]
Base uses 11 (which produces broken binaries) and front uses 10.5.

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/9717)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NiLuJe)

**Comment by NiLuJe** [comment]
Okay, this should be ready now :].

**Review by poire-z — APPROVED** [review]
Ok about the frontend/apps changes (can't say about the rest).
(A bit noisy though to have to have to duplicate the event names in the `if / elseif not init`. Couldn't we get some generic stuff to iterate and remove all `self.key_events` values in the super class ?)

**Comment by NiLuJe** [comment]
> Couldn't we get some generic stuff to iterate and remove all `self.key_events` values in the super class ?

That's an interesting thought, I'll look into it :}.

**Comment by NiLuJe** [comment]
> Couldn't we get some generic stuff to iterate and remove all `self.key_events` values in the super class ?)

Yup, much nicer that way ;).

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 21 of 21 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/9717)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NiLuJe)

**Review by poire-z — APPROVED** [review]

**Pull request merged**
