### PR TITLE
Bump base/crengine for SVG images support

### LINKED ISSUE #2668: EPUB doesn't support SVG images
* KOReader version: lastest 
* Device: ppw3

#### Issue

Some images in few epubs doens´t open...I ´ve attached screens with a mobi and the epub into pc, I can see the image in both files, but if I open the epub in koreader I only see a blank image

this one is on PC (" 11.1.5 PECULATO")
epub-pc

Mobi at kindle (" 11.1.5 PECULATO")
p_20170321_143717

Epub with koreader (" 11.1.5 PECULATO")

p_20170321_144355

#### Steps to reproduce
Download the epub and try at ppw3
https://www.dropbox.com/s/dtc5vdw4him9cek/DIREITO%20PENAL%20-%20PARTE%20ESPECIAL%20-%20ESQUEMATIZADO%20-%202016.epub?dl=0

### PR DESCRIPTION
**Pull request by poire-z**
Parsing and rasterisation provided by nanosvg (some svg tags like text, span and images are not supported).
Only svg images included as files in the .epub are supported (embedded svg tags in html are not).
Holding on svg image shows it 4x zoomed in ImageViewer.
Closes #2668 (with the above limitations)

### CODE REVIEW

**Comment by poire-z** [comment]
koreader travis build failed because there was no -DNANOSVG_INCLUDE_DIR= in the cmake command line for crengine build. There was no problem on the koreader-base travis build (and my local build).
Does it need something more for travis build ?

**Comment by Frenzie** [comment]
It says it's using cached submodules, except that shouldn't happen because base has changed.

https://github.com/koreader/koreader/blob/773e24fc79c8cbf6dcf48e3678237861149aabef/.ci/install.sh#L12-L21

I think it's probably either the `--ignore-submodules=dirty` or my later addition of `git fetch --unshallow` is interfering somehow? https://github.com/koreader/koreader/blob/773e24fc79c8cbf6dcf48e3678237861149aabef/.ci/before_install.sh#L17

Unfortunately I don't really have time to test this for the next two weeks. :( Anyway, so I'd recommend giving it a quick try without `--ignore-submodules=dirty`but if that doesn't work it could be a little more complicated.

**Comment by houqp** [comment]
Yeah, it's weird that it's still using the cached base dir. I am curious what's the output of `git status --ignore-submodules=dirty --porcelain` there. @poire-z can you help tweak the install.sh to get more info out of it? Another useful thing we can do is set `set -o xtrace` at the top of install.sh.

**Comment by poire-z** [comment]
```
+git status --ignore-submodules=dirty --porcelain
++git status --ignore-submodules=dirty --porcelain
+'[' '' ']'
+echo -e '\033[32;1mUsing cached submodules.'
```

**Comment by houqp** [comment]
Weird, it's indeed returning empty string, what about just `git status`?

**Comment by poire-z** [comment]
```
+git status --ignore-submodules=dirty --porcelain
+git status --porcelain
 M base
++git status --ignore-submodules=dirty --porcelain
+'[' '' ']'
```

**Comment by Frenzie** [comment]
Alright, definitely get rid of the `--ignore-submodules=dirty` then, although as long as base has changed output should always look something like this (this is on my computer):

```
$ git status --ignore-submodules=dirty --porcelain
 M base
 M platform/android/luajit-launcher
?? koreader-android-arm-linux-androideabi-v2015.11-976-ge8c01274.tgz
?? sort
```

**Comment by houqp** [comment]
I wish we are using circleci, which supports logging into the build with a web shell to investigate build issues :( @poire-z try adding a `./kodev fetch-thirdparty` before the `git status` call.

**Comment by Frenzie** [comment]
>  logging into the build with a web shell to investigate build issues 

That would make life so much easier.

**Comment by houqp** [comment]
Let's migrate to circleci! Our build scripts are actually very portable ;)

**Comment by houqp** [comment]
removing ` --ignore-submodules=dirty` will probably cause it to always reinitialize base, which is probably fine? Does `deinit` remove the whole directory?

**Comment by houqp** [comment]
```
HEAD detached at 19337772
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
	modified:   base (modified content)
```

Base is not updated at all? Can you do a `git diff` to show which commit the base is at?

**Comment by Frenzie** [comment]
Yes, the whole idea is that base can be cached, including dirty, but toss it all out if something actually changes. That way you only have the full 16+ minute build time every once in a while.

@poire-z Could you remove the git fetch --unshallow from where it is in before_install.sh and move it to underneath the git status stuff as a quick test?

**Comment by poire-z** [comment]
```
+git diff
diff --git a/base b/base
--- a/base
+++ b/base
@@ -1 +1 @@
-Subproject commit b7d41fac1165b053a5110156f9d5543cbbf9338e
+Subproject commit b7d41fac1165b053a5110156f9d5543cbbf9338e-dirty
```
The same before and after `./kodev fetch-thirdparty`
Now trying with moving git fetch --unshallow

**Comment by poire-z** [comment]
Mhhh, but b7d41f is the expected commit hash with my changes.

**Comment by houqp** [comment]
oh... you know what? When travis clones the git repo, it already did the submodule update for us: `git submodule update --init --recursive`.

**Comment by houqp** [comment]
@poire-z lets' just change it to always redo the base from scratch for now if you don't want to waste time digging into this. I am happy merging it as is. I can help look a look later this weekend. There is probably also an issue with the build dependency, with the latest base checked out, `make` should automatically build your nanosvg target too because crengine depends on it. I am not sure why this is not happening.

**Comment by Frenzie** [comment]
@houqp The cached `base` overwrites checked out `base`. In my local testing that all worked exactly as expected; it didn't think it was at the same commit. Maybe Travis submodule initialization can be disabled?

**Comment by poire-z** [comment]
Same after moving `git fetch --unshallow`.
Reseting the .ci scripts and trying again (in case cache has been updated), the builds failed because of the set -o xtrace.

**Comment by Frenzie** [comment]
@poire-z If you're not fed up by this yet, perhaps you could run a test with this in .travis.yml?

```
git:
  submodules: false
```

**Comment by poire-z** [comment]
Another kind of failure at the end of before_install.sh, dunno if it's because of the travis.yml mod.
I'm away for a bit, I'll be back on it in a few hours.

**Comment by Frenzie** [comment]
Yes, it's because it's fetching on uninitialized submodules. I just remembered I explicitly tested with the exact command Travis uses.

Anyway, just get rid of `--ignore-submodules=dirty` and/or comment out the base cache. We'll just have to live with more than double the build time for a bit. ;-)

**Comment by retrue** [comment]
A comment, once that support for svg is added inside epubs i guess it can be added too to the file manager.
Does this PR include that option or will it be added later?

**Comment by Frenzie** [comment]
Not yet. :)

**Comment by poire-z** [comment]
> svg support can be added too to the file manager

You mean displaying standalone .svg files in directories ? If you have such .svgs, you may try first to embed them in some epub, to see if the result is correct enough (nanosvg has some limitations, text, embedded images...).
That would have to be dealt with by picdocument.lua (tried once looking at pictures, it was not a pleasant experience).
And it would need to have a shared library with nanosvg code, and a ffi wrapper (or just export that convertSVGtoPNG function in libkoreader-cre.so, so nanosvg only needs to be linked in libcrengine).

**Comment by poire-z** [comment]
> just get rid of --ignore-submodules=dirty 

Ok, worked, took 16mn.
(No urged merging for me, if you want that as a base to work on this cache problem)

**Comment by houqp** [comment]
@Frenzie now that I think about it, it's very likely due to the initial submodule update from travis. Travis will first clone the repo and do a recursive submodule update, then unpack the cache files. After the cache file is unpacked, it only overwrites the content within base directory, but the metadata in git still have base pointed to the latest base due to the initial submodule update. So that if check will only work when base is not included in the cache. I will migrate our CI to circleci this weekend hopefully and implement this check in another way.

@poire-z congarts on getting the svg support merged :)

**Comment by poire-z** [comment]
There's been no nightly build since this was merged. The last one (v2015.11-1023-g773e24f) was juste before this.
Could it be there's also this problem (base not updated, cache used, build failed) for the nightly build, and some other script that need to be updated somewhere ?

**Comment by Frenzie** [comment]
If anything I'd suspect that a submodule change isn't registered as a "real" change.

**Comment by poire-z** [comment]
Still no nightly build (at http://build.koreader.rocks/download/nightly/) in spite of yesterday's 2 pure koreader commits. Any log one can look at ?

**Comment by Frenzie** [comment]
I restarted the relevant process in case something went wrong.

**Comment by houqp** [comment]
Looks like it's because gitlab mirror is lagging behind :(

**Comment by houqp** [comment]
see: https://gitlab.com/koreader/koreader

**Comment by houqp** [comment]
I have manually requested a mirror update on gitlab. The next build should pick up the latest commit. I will change the nightlybuild pipeline to do git clone from github instead.

**Comment by poire-z** [comment]
Thanks.
There was a 1025 build yesterday, and a 1028 today.
I noticed the 1028 kobo zip was 500k smaller than the 1025, and 1028 is indeed missing languages directories in koreader/l10n/ subdir.

**Comment by houqp** [comment]
ok, let me purge that build. I am looking into it now.

**Comment by houqp** [comment]
https://gitlab.com/koreader/nightly-builds/builds/15798227/raw

from the beginning of the log, looks like we are getting auth error from transifex :(

**Comment by houqp** [comment]
Looks like an intermediate auth issue from transifex, some other builds was able to fetch the translation with the same token. And I definitely haven't changed that part of the code. It's working for kobo now after I regenerated a new token: https://gitlab.com/koreader/nightly-builds/builds/15808491

I will update the code so the build fails immediately if it's not able to fetch translations.

**Comment by poire-z** [comment]
Thanks, looks fine now :)

**Pull request merged**
