### PR TITLE
Fix issues #6362 - ftp corruption of binary files

### PR DESCRIPTION
**Pull request by clach04**
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/6363)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Obvious question is obvious: what happens for plain-text content?

They make the trip bit-exact, too?

(What does the default test mode does? OS-specific line-ending mangling?)

**Comment by clach04** [comment]
> Obvious question is obvious: what happens for plain-text content?
> 
> They make the trip bit-exact, too?

* Before fix they get "changed" (corrupted is misleading) and KOreader displays them fine.
* With fix they do not get changed/corrupted and are exact-copies of the source -  and KOreader displays them fine.

> (What does the default test mode does? OS-specific line-ending mangling?)

Can you explain this more? I'm not sure what test mode is? I only ran this on a K3 device manually, I did not run any test suite (not sure how to do that).

**Comment by NiLuJe** [comment]
Your first bullet-point answered my final question, thanks ;).

**Comment by Frenzie** [comment]
@NiLuJe Was this one good to go?

**Comment by NiLuJe** [comment]
It certainly makes sense, so I'd say yes, but I don't use the feature myself ;).

**Pull request merged**
