### PR TITLE
Bump base

### PR DESCRIPTION
**Pull request by NiLuJe**
https://github.com/koreader/koreader-base/pull/1331
https://github.com/koreader/koreader-base/pull/1333
https://github.com/koreader/koreader-base/pull/1335
https://github.com/koreader/koreader-base/pull/1334

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7437)

### CODE REVIEW

**Comment by NiLuJe** [comment]
(Gutenberg is down, hence the test failure).

**Comment by SteadyQuad** [comment]
Gutenberg.org is working but really slow, probably timing out in the test.

btw this is on gutenberg.org frontpage:

> Planned service change In April 2021, www.gutenberg.org plans to remove unencrypted access (http), and will only offer https. The collection remains available from mirrors, as well as via unencrypted ftp and rsync.

There's several gutenberg url's in the sourcecode that use http instead of https, worth creating an issue for?

**Comment by NiLuJe** [comment]
IIRC, they're all in the hilariously outdated OPDS tests, but, yeah, at least this'll help tracking it.

**Comment by Frenzie** [comment]
> There's several gutenberg url's in the sourcecode that use http instead of https, worth creating an issue for?

Probably, yes, but cf. https://github.com/koreader/koreader/issues/7007#issuecomment-749726860 as to why that wasn't the case.

**Pull request merged**
