### PR TITLE
Update bundled fonts

### PR DESCRIPTION
**Pull request by NiLuJe**
* Minor FreeFont update
* Noto Sans CJK downgrade to fix a number of issues w/ the git version
* Initial import of Noto Naskh Arabic

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/6242)

### CODE REVIEW

**Comment by NiLuJe** [comment]
@poire-z: Should I add Naskh to a fallback list somewhere?

**Comment by poire-z** [comment]
For CRE, possibly just a matter of _replacing_ Noto Sans Arabic by the new one in:
https://github.com/koreader/koreader/blob/9c4e246038a30a405957b3f537c8c1c27d4a872b/frontend/document/credocument.lua#L47-L55

**Comment by NiLuJe** [comment]
@Frenzie: This *is* front? ;o).

**Comment by Frenzie** [comment]
@NiLuJe Ho, hum, so it is. >_>

**Pull request merged**
