### PR TITLE
Unbreak all the things ;o)

### PR DESCRIPTION
**Pull request by NiLuJe**
https://github.com/koreader/koreader-base/pull/1634

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10687)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Nope, it failed dependency resolving when loading CRe because it has a DT_NEEDED on the webp stuff; not *quite* sure why that doesn't fail on CIs.

(Probably the same reason it didn't fail on the emu: it looks up the system's instead?).

**Comment by Frenzie** [comment]
> It failed dependency resolving when loading CRe because it has a DT_NEEDED on the webp stuff; not quite sure why that doesn't fail on CIs.

Hm, that's still surprising. I start on history, but perhaps some cover wasn't generated yet.

> (Probably the same reason it didn't fail on the emu: it looks up the system's instead?).

On *my* system, sure, whatever, but not on the Docker image.

**Comment by Frenzie** [comment]
> On my system, sure, whatever, but not on the Docker image.

I take that back actually. My system has 0.6.1 and 1.2.4. Not 1.3.x.

```
/usr/lib/x86_64-linux-gnu/libwebp.so.7
/usr/lib/x86_64-linux-gnu/libwebp.so.7.1.5
```

**Comment by Frenzie** [comment]
D'oh, wrong system. I have three I regularly use. Ignore the above. ;-)

**Comment by Frenzie** [comment]
Hm, no problem on this system either though. If it's getting libwebp itself from the system that might be slightly bothersome.

**Comment by NiLuJe** [comment]
I don't recall how/if we set an LD_LIBRARY_PATH for the CI runs (and/or how the DT_RPATH are set), but, yeha, that might be a possibility.

**Comment by Frenzie** [comment]
But I repeat, the CI doesn't have a libwebp other than the one it just built.

**Comment by NiLuJe** [comment]
Oh.

New idea, then: Shitty libtool build-time rpaths making it through the final binaries, meaning they'll go looking in the build directory for the deps (and, well, find it)?

**Comment by Frenzie** [comment]
That sounds more plausible, still weird & unexpected though.

**Comment by yparitcher** [comment]
You might need to update the mac ci script. See https://github.com/koreader/koreader/commit/f588edd9b1d47fe59ed5d144016b704dec9438f5

**Comment by NiLuJe** [comment]
> That sounds more plausible, still weird & unexpected though.

Yup!

```
  75   │ Dynamic section at offset 0x34ef8 contains 29 entries:
  76   │   Tag        Type                         Name/Value
  77   │  0x00000001 (NEEDED)                     Shared library: [libsharpyuv.so.0]
  78   │  0x00000001 (NEEDED)                     Shared library: [libm.so.6]
  79   │  0x00000001 (NEEDED)                     Shared library: [libpthread.so.0]
  80   │  0x00000001 (NEEDED)                     Shared library: [libc.so.6]
  81   │  0x0000000e (SONAME)                     Library soname: [libwebp.so.7]
  82   │  0x0000000f (RPATH)                      Library rpath: [/builds/koreader/nightly-builds/koreader/base/thirdparty/libwebp/build/arm-kobo-linux-gnueabihf/libwebp-prefix/src/libwebp-build/lib]
```

Which means we probably a fancy $ORIGIN rpath in there to fool-proof this...

**Comment by Frenzie** [comment]
I'm not sure if I should do anything to any Docker images this month (or at least this week) so as not to interfere with the big Android upgrade, but could there also be a chance it's an issue fixed in newer libtool? I had intended to do some more work on 18.04 → 20.04 in July 2023 since 18.04 is officially EOL now.

**Comment by NiLuJe** [comment]
Oh, no, it's been like this *forever* ;o).

One very quick way to confirm that is to use the amazing slibtool to build webp instead:

```
 130   │ Dynamic section at offset 0xb4d60 contains 28 entries:
 131   │   Tag        Type                         Name/Value
 132   │  0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 133   │  0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 134   │  0x000000000000000e (SONAME)             Library soname: [libwebp.so.7]
 135   │  0x000000000000000c (INIT)               0x3000
```

I'm not terribly inclined to hack around this now, given that this will be a non-issue with meson ;).

**Comment by NiLuJe** [comment]
(The missing DT_NEEDED on libsharpyuv is perhaps a prime example of the fact that slibtool isn't a magical cure-all, though ;p)

**Comment by NiLuJe** [comment]
Supposedly, things have gotten better since 1.5.2 (c.f., https://wiki.debian.org/RpathIssue), but that's pretty damn old by now, and I've *always* seen libtool do this, except when drastic measures are taken (i.e., Portage patches libtool to murder that insanity).

**Comment by NiLuJe** [comment]
> (The missing DT_NEEDED on libsharpyuv is perhaps a prime example of the fact that slibtool isn't a magical cure-all, though ;p)

Correction: I must have been doing it wrong that time, I'm getting proper DT_NEEDED entries with slibtool now (with `LIBTOOL=rlibtool` at least, which isn't how I originally tested).

**Pull request merged**
