### PR TITLE
ReaderHighlight: adjustable "Edit highlight" dialog position

### PR DESCRIPTION
**Pull request by hius07**
Follows the "Highlight" dialog position settings.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12599)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by Commodore64user** [comment]
thanks @hius07, this is an improvement however it still falls short. I've added a screenshot because an image is worth 1000 words.

<p align="center">
 

</p>

screenshot 1 is using the dynamic mode that depends on where you started the selection, when one is near the bottom of the screen it will just plaster the dialogue on top regardless, and the second screenshot is a quirk after one deletes a highlight, a word remains highlighted until one refreshes the screen again.

if you feel generous, the repositioning (with key_events) would reallymake this even better.

**Comment by hius07** [comment]
The dialog is rather thin, so I tend not to complicate it for highlights ending close to the bottom, it overlaps them.

**Comment by Commodore64user** [comment]
> The dialog is rather thin, so I tend not to complicate it for highlights ending close to the bottom, it overlaps them.

Could it not just be on top of them?

**Comment by hius07** [comment]
It can, but then we must check if there is enough room above, and decide where to show the dialog. That is what I mean "to complicate" for rare cases when the highlight end is close to the bottom.

**Comment by mergen3107** [comment]
> It can, but then we must check if there is enough room above, and decide where to show the dialog. 

This is exactly how it works on K3/K4NT in Kindle Reader when you select words to lookup in dictionary by the way :D 
But it only decides between very top or very bottom window location

**Comment by Commodore64user** [comment]
> It can, but then we must check if there is enough room above, and decide where to show the dialog. That is what I mean "to complicate" for rare cases when the highlight end is close to the bottom.

in my humble opinion, it would be better if it did. I mean, unless you are highlighting the entire page, the dialogue box should never overlap the selected text.

> and decide where to show the dialog.

the exact opposite to the behaviour if the highlight was at the top of the screen, i.e right below the last line of the highlight. So if we reverse that, right above the first line of the selected line.

**Comment by hius07** [comment]
Changes: try to show dialogs **below** the highlight even if we are panning backward (new highlight), or if pos0 and pos1 are unsorted (existing highlight in pdf).

**Comment by Commodore64user** [comment]
highlights at the top and middle of the screen look amazing, bottom... 😕. I suppose statistically speaking we can make adjustments 2/3 times.

<p align="center">
 

</p>

**Pull request merged**
