### PR TITLE
OPDSParser: Attempt to preserve data from content tags *without* breaking luxl

### PR DESCRIPTION
**Pull request by NiLuJe**
Now that we can actually use it, thanks to #7767 ;).

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7768)

### CODE REVIEW

**Comment by NiLuJe** [comment]
e.g., when I mentioned, that, ironically, calibre stores all kinds of interesting stuff in there:

calibre_opds

**Review by Frenzie — APPROVED** [review]
I may have said this before, but what about that other parser over in https://github.com/koreader/koreader/blob/b8d658b922404974ac5acd20a8843e665133d3c3/plugins/newsdownloader.koplugin/lib/xml.lua ?

**Comment by NiLuJe** [comment]
@Frenzie: That would involve a rewrite, in which case I'd probably prefer biting the bullet and switch to a real big-boy parser (e.g., expat or libxml2).

**Comment by NiLuJe** [comment]
> @Frenzie: That would involve a rewrite, in which case I'd probably prefer biting the bullet and switching to a real big-boy parser (e.g., expat or libxml2).
> 
> That said, haven't actually looked at which is saner and/or easier to deal with of the two existing pure-Lua parsers we have vs. said ffi/binding approach ;).

And now that I think about it, I may indeed have looked into that the last time. I vaguely remember thinking about OPDS and namespaces and libxml2 and whichever binding I tried, and the namespace thing being annoying to deal with.

Oh, well.

**Pull request merged**
