### PR TITLE
Dispatcher: fix dynamically built menu

### PR DESCRIPTION
**Pull request by hius07**
Applicable for `Set font` and `Set highlight action` actions.
Closes https://github.com/koreader/koreader/issues/10077.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10080)

### CODE REVIEW

**Comment by hius07** [comment]
Just for reference: https://github.com/koreader/koreader/pull/8555#discussion_r770326918

**Review by yparitcher — APPROVED** [review]
Thanks

**Comment by poire-z** [comment]
Hijacking a random Dispatcher PR:
is there a reason for Word Spacing and Word Expansion to not be available in Dispatcher action ? Or did we just forget to add them ? :)
(and if it's just that, can someone familiar with all that add them ? Thanks.)

Just got around to enabling the Profiles plugin with the recent "Profile for document settings" and make myself gestures to swith 1-2 columns with buddy settings tweaks, and these were missing. I like how long-press on an action is really quick to get rid of the settings I don't want in :)
There's also a bit annoying Notification about the font size, and only the font size - I can get rid of it by disabling "Notif from gestures and profiles", but is it right that otherwise we show only the font size ? I guess it might be from the font fine tuning bottom menu showing font size notifications as there is no other feedback.

**Comment by poire-z** [comment]
> There's also a bit annoying Notification about the font size, and only the font size - I can get rid of it by disabling "Notif from gestures and profiles", but is it right that otherwise we show only the font size ? I guess it might be from the font fine tuning bottom menu showing font size notifications as there is no other feedback.

I see/remember that not all settings get a notification - and which get some or none is probably appropriate in the context of changing them in the bottom menu.
So, with profiles/gestures and changing 7 settings, you may get only 3 notifications.
How do you users of this feature bear that ? :) Do you disable "Notif from gestures" ? But if I do that, I don't get to see the frontlight level when swiping along the left edge (which I'd still like to see).
(I'm a bit confused, as a new user :)

**Comment by yparitcher** [comment]
No clue, i don't use profiles.

**Comment by mergen3107** [comment]
I think I turned off most of notifications and it is OK for me :D I don’t need ones to understand whether the setting I am trying to apply actually applied. 

Also, with gestures I get 4 stacked notifications out of 5 actions: font size, font face, line spacing, font weight, kerning (this one is not shown).

**Pull request merged**
