### PR TITLE
Input: Followup tweaks to #7415

### LINKED ISSUE #7472: Bq Cervantes 4 : koreader doesn't start after updating to the latest dev. version
Hi,
Yesterday evening, I updated my bq Cervantes 4 to the latest developper version of Koreader (I cannot remember the version number but I think it ended with a 6).
The update operation went fine but when Koreader restarted it entered into an infinite loop. The little dots scroll endlessly at the bottom of the screen but nothing happens. 
I restarted my device but it didn't solve the problem.
I also tried to connect to the device by Telnet in order to downgrade koreader manually. I followed the instructions found here : http://web.archive.org/web/20200720044821/https://blog.bq.com/es/bq-ereaders-developers-program/. I used Putty, chose Telnet, entered 192.168.4.1 as IP address and 23 as Port, but the connection was refused. I'm not sure that I proceeded correctly (I don't understand for example "Set your computer usb0 interface with another ip address in that range and you would be able to telnet it through USB interface".
So right now I'm stucked and I don't know how to solve the problem. 
Did I miss something ? Or can I force the device to launch the bq software instead of koreader ? Or is there another way than Telnet to access to the device ?
Any help highly appreciated :-)
Bruno

### PR DESCRIPTION
**Pull request by NiLuJe**
* Actually load librt properly on old Linux systems (fix #7472)
* Made sure SDL & Android honored timeouts properly in some edgy (or not so edgy, in SDL's case) cases (c.f., https://github.com/koreader/koreader-base/pull/1343).
* Try harder not to consume a timer callback when the timerfd backend is in use and `select` timed out *not* because of a timerfd expiring. This would take some particularly heinous timing to reproduce (e.g., a timerfd set, but a task deadline expiring *before* it). May or may not help with #7473.
* Decode `BTN_` KEY codes in verbose debug logs.
* Fix MultiTouch on the H2O (GestureDetector was hard-coding the two slots as 0 & 1, but the H2O kernel is a special snowflake that doesn't use slot 0, instead switching to slot 1 & 2).

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7478)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Requires https://github.com/koreader/koreader-base/pull/1342

**Review by poire-z — APPROVED** [review]
(Well, I reviewed what I could: I just followed the 0/1 > s1/s2 changes, they're fine :)

**Comment by NiLuJe** [comment]
Something isn't, as it broke scheduled tasks on the emu ;).

**Review by Frenzie — COMMENTED** [review]
whoa whoa whoa I'll need to read this in more detail later

**Comment by NiLuJe** [comment]
Quick test-case for the SDL timeout thing: Move to a FM page w/ thumbnails to generate, and keep moving your mouse around inside the KOReader window.

It won't ever refresh until you stop moving, because SDL keeps spitting a single event that we weren't doing anything with, and never exiting the loop.

I'd *vaguely* noticed something weird originally (which is what made me dig inside runInSubProcess), and I knew that the weird forever loop was weird, but I hadn't quite made the link until last night, where it happened much more reliably because of a gamepad stick being jittery ;).

**Pull request merged**
