### PR TITLE
NT: add Hot swapping dictionaries button and edit button into FocusManager's layout

### LINKED ISSUE #11783: Hot swapping dictionaries unavailable on NT devices
* KOReader version: Sourdough
* Device: kindle 4 (Applies to all non-touch devices)

#### Issue
Hamburger menu in the dictionary lookup/wiki pop up box inaccessible to non-touch users.
When using the dictionary, this option allows the user to quickly hot swap dictionaries.

#### Steps to reproduce
Select a word to bring up dictionary, press up/down to cycle through the menu. Suffer in silence as the menu loops back without ever reaching the burger. Cry.

### PR DESCRIPTION
**Pull request by comphilip**
fix #11783

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11803)

### CODE REVIEW

**Comment by Frenzie** [comment]
Thanks!

**Comment by Commodore64user** [comment]
Blimey! This was swift and unexpected. Thanks!

**Comment by jospalau** [comment]
Hello,
When looking for a word in the dictionary, it gets hanged in Searching dictionary for: ...

Not sure if it is my configuration though but it works removing this change.

**Comment by Frenzie** [comment]
Are you sure you don't have the version from 2 or 3 days ago?

**Comment by jospalau** [comment]
I updated to the last nightly to test, it is showing 2024.04-48

I could have something mangled here in any case if this should be working

**Comment by Frenzie** [comment]
No, it doesn't seem to finish on my Kobo. I'd quickly tested on Android before, but I guess it registers as hasDPad.

**Pull request merged**
