### PR TITLE
[chore] Fix a few luacheck errors

### PR DESCRIPTION
**Pull request by Frenzie**
Inadvertently introduced in <https://github.com/koreader/koreader/pull/8432> and <https://github.com/koreader/koreader/pull/8445>.

This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8460)

### CODE REVIEW

**Comment by poire-z** [comment]
CircleCI is again not running on PRs ?! :/

**Comment by Frenzie** [comment]
It ran, but I guess it's failing to show status?

**Comment by hius07** [comment]
It doesn't run when I make a PR. I've tried some settings but no success.

**Comment by hius07** [comment]
That was the first check started:
https://app.circleci.com/pipelines/github/koreader/koreader/3646/workflows/fec7dc04-1dd5-4e9c-a40c-1f67716cd77f/jobs/7445

**Pull request merged**
