### PR TITLE
OPDSbrowser refactoring

### PR DESCRIPTION
**Pull request by hius07**
Refactoring:
-removed duplicated code
-removed passing of username/password through all the modules
-logical order of the methods
-some optimizing and drying
-comments

New features:
-subcatalog link can be saved to the list of servers (eg: direct link to the catalog of books by an author)
-more book information can be fetched and shown (<kbd>Book information</kbd>)
-fixed access to the Standard library (by @KGKopli, closes https://github.com/koreader/koreader/issues/9372)

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9703)

### CODE REVIEW

**Comment by hius07** [comment]
```Lua
-- Builds the root list of catalogs
function OPDSBrowser:genItemTableFromRoot()

-- Shows dialog to edit properties of the new/existing catalog
function OPDSBrowser:addEditCatalog(item, is_calibre)

-- Shows dialog to add a subcatalog to the root list
function OPDSBrowser:addSubCatalog(item_url)

-- Saves catalog properties from input dialog
function OPDSBrowser:editCatalogFromInput(fields, item, no_init)

-- Saves calibre properties from input dialog
function OPDSBrowser:editCalibreFromInput(fields)

-- Deletes catalog from the root list
function OPDSBrowser:deleteCatalog(item)

-- Fetches feed from server
function OPDSBrowser:fetchFeed(item_url, headers_only)

-- Parses feed to catalog
function OPDSBrowser:parseFeed(item_url)

-- Generates link to search in catalog
function OPDSBrowser:getSearchTemplate(osd_url)

-- Generates menu items from the fetched list of catalog entries
function OPDSBrowser:genItemTableFromURL(item_url)
function OPDSBrowser:genItemTableFromCatalog(catalog, item_url)

-- Requests and shows updated list of catalog entries
function OPDSBrowser:updateCatalog(item_url, paths_updated)

-- Requests and adds more catalog entries to fill out the page
function OPDSBrowser:appendCatalog(item_url)

-- Shows dialog to search in catalog
function OPDSBrowser:searchCatalog(item_url)

-- Shows dialog to download / stream a book
function OPDSBrowser:showDownloads(item)

-- Returns user selected or last opened folder
function OPDSBrowser.getCurrentDownloadDir()

-- Downloads a book (with "File already exists" dialog)
function OPDSBrowser:downloadFile(filename, remote_url)

-- Streams a book (OPDS-PSE Page Streaming Extension)
function OPDSBrowser:streamPages(remote_url, count, continue)

-- Shows a page number dialog for page streaming
function OPDSBrowser:jumpToPage(viewer)

-- Menu action on item tap (Download a book / Show subcatalog / Search in catalog)
function OPDSBrowser:onMenuSelect(item)

-- Menu action on item long-press (dialog Edit / Delete catalog)
function OPDSBrowser:onMenuHold(item)

-- Menu action on return-arrow tap (go to one-level upper catalog)
function OPDSBrowser:onReturn()

-- Menu action on return-arrow long-press (go to the catalog home page)
function OPDSBrowser:onHoldReturn()

-- Menu action on next-page tap (request and show more entries from the catalog)
function OPDSBrowser:onNext()
```

**Review by NiLuJe — COMMENTED** [review]
Nothing jumps out at me at a quick glance ;).

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/9703#-:-NFVYWgs6TMYEa4blZF7:b4nwjqr)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hius07)

**Review by Frenzie — APPROVED** [review]
Same wrt the glance thing. Did you also browse around a few of the preset OPDS catalogs? I don't think the test covers everything.

**Comment by CrazyCoder** [comment]
Getting a crash on the clean install of KOReader:

```
 [*] Version: v2022.10-50-g4d8e2f0e_2022-10-29
./luajit: plugins/opds.koplugin/opdsbrowser.lua:100: bad argument #3 to 'format' (number expected, got nil)
stack traceback:
	[C]: in function 'format'
	plugins/opds.koplugin/opdsbrowser.lua:100: in function 'genItemTableFromRoot'
	plugins/opds.koplugin/opdsbrowser.lua:86: in function 'init'
	frontend/ui/widget/widget.lua:46: in function 'new'
	plugins/opds.koplugin/opdscatalog.lua:18: in function 'init'
	frontend/ui/widget/widget.lua:46: in function 'new'
	plugins/opds.koplugin/opdscatalog.lua:66: in function 'showCatalog'
	plugins/opds.koplugin/main.lua:34: in function 'showCatalog'
	plugins/opds.koplugin/main.lua:46: in function 'callback'
	frontend/ui/widget/touchmenu.lua:876: in function 'onMenuSelect'
	frontend/ui/widget/touchmenu.lua:212: in function 'handleEvent'
	...
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/uimanager.lua:858: in function 'sendEvent'
	frontend/ui/uimanager.lua:51: in function '__default__'
	frontend/ui/uimanager.lua:1383: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1481: in function 'handleInput'
	frontend/ui/uimanager.lua:1528: in function 'run'
	./reader.lua:302: in main chunk
	[C]: at 0x000140bd
!!!!
Uh oh, something went awry... (Crash n°1: 10/30/22 @ 17:56:20)
Running FW 4.34.20097 on Linux 4.1.15-00838-g349fbf5767c (#90 SMP PREEMPT Thu Sep 15 15:12:23 CST 2022)

```

**Comment by hius07** [comment]
Thank you, shall fix soonest.
As a temporary workaround the following entry should be added to koreader/settings.reader.lua:
```Lua
["calibre_opds"] = {
        ["host"] = "192.168.1.1",
        ["port"] = "8080",
},
```

**Pull request merged**
