### PR TITLE
Bump base & android-luajit-launcher

### PR DESCRIPTION
**Pull request by NiLuJe**
https://github.com/koreader/koreader-base/pull/1472
https://github.com/koreader/koreader-base/pull/1473
https://github.com/koreader/android-luajit-launcher/pull/364

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8962)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by NiLuJe** [comment]
Added a few commits to see if it helps w/ https://www.mobileread.com/forums/showthread.php?t=345985

Ping @zwim for feedbac, especially for that last one ;).

(This is thoroughly untested so far ^^).

**Comment by zwim** [comment]
@NiLuJe Concerning the crashes of "Uncle Robin". 
I cannot reproduce the crash on my device (which seems to be the same as Uncle Robin's). On mobileread I have requested his settings.

In his log there are a lot of lines like
`03/13/22-13:16:26 WARN  Error when loading plugins/terminal.koplugin/main.lua`.

Where do they come from? Should we ask for a full debug log?

I would want to wait with [1ecb625](https://github.com/koreader/koreader/pull/8962/commits/1ecb6256113387dd8175b73523cff9bbd417937a) until we know what is going on there.

**Comment by NiLuJe** [comment]
Huh, yeah, the Terminal plugin failing to load on a Sage is weird. I'll see if I can repro, as I don't actually have it enabled anywhere ;p.

**Comment by NiLuJe** [comment]
(Punted off the WIP stuff to another branch).

**Pull request merged**
