### PR TITLE
exclude those broken kindle system fonts

### PR DESCRIPTION
**Pull request by frankyifei**
these fonts can not be used by freetype and will cause hang up.
This will fix https://github.com/koreader/koreader/issues/1577

### CODE REVIEW

**Comment by Frenzie** [comment]
Are these Kindle-exclusive fonts that are always broken or are they fonts that happen to be broken on Kindle? I wonder if it would be a good idea to add a check for `isKindle` just in case.

**Comment by frankyifei** [comment]
these font are broken on any platform, they contain some information for CJK font vertical positioning used by amazon and no glyphs in there. see the screenshot from my ubuntu vm here https://github.com/koreader/koreader/issues/1577. 
These fonts only exist on kindle. But I think it is possible someone want to exclude more fonts in the future or on other device.

**Comment by NiLuJe** [comment]
AFAICT, only the specific versions shipped on the Kindle are broken w/ mainline FT, so wrapping that in a isKindle block is not a bad idea ;).

**Comment by frankyifei** [comment]
ok

**Comment by NiLuJe** [comment]
Minor nitpicking: I'd maybe go with a more descriptive function name, but that's just me ;).

As for your idea of extending this facility to other devices, sure, in that case, just wrap the list of fonts in an isKindle block, not the whole thing ;).

**Comment by Frenzie** [comment]
Agreed, `checkfont` is rather cryptic (nor is it in compliance with the [style guide](https://github.com/koreader/koreader-base/wiki/Coding-style#naming)).

**Comment by Frenzie** [comment]
Agreed, `checkfont` is rather cryptic (nor is it in compliance with the
[style guide](
https://github.com/koreader/koreader-base/wiki/Coding-style#naming)).

**Comment by chrox** [comment]
@frankyifei A little refactoring in https://github.com/frankyifei/koreader/pull/2, please check it out.

**Pull request merged**
