### PR TITLE
[Kobo] Unbreak Wi-Fi on FW >= 4.23

### LINKED ISSUE #6500: Wi-Fi not working after Kobo 4.23.15505 update.
* KOReader version: 2020.07.1
* Device: Kobo Forma sw ver 4.23.15505

#### Issue
After upgrading to latest sw ver for Kobo 4.23.15505, when I click on Enable Wi-Fi in KOReader I get the message:
Cannot initialize network control client. Failed to connect to wpa_supplicant control socket: /var/run/wpa_supplicant/eth0.

#### Steps to reproduce
Open KOReader. Tap on Wi-Fi connection / Enable Wi-Fi connection. After prompt asks for confirmation to enable wi-fi, the message described above appears.

### PR DESCRIPTION
**Pull request by NiLuJe**
Fix #6500 

(I'm back! :)).

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/6522)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Haven't looked into the USBMS thingy I mentioned in #6500 yet.

Hopefully the random `nickel.sh` weaks will help. In any case, I was already half of a mind to handle USBMS with a small external tool àla Cervantes anyway, so, eh.

**Comment by NiLuJe** [comment]
Okay, can't reproduce USBMS issues on the H2O with the latest tweaks.

I'll double-check on the Forma later ;).

**Comment by NiLuJe** [comment]
(This *probably* warrants a 08.1?)

**Comment by Frenzie** [comment]
Possibly slightly risky with https://github.com/koreader/koreader/pull/6521 just merged, but works for me. We'll just wait a couple of days.

**Comment by NiLuJe** [comment]
Can't reproduce USBMS issues anymore on the Forma, either. Yay.

**Comment by poire-z** [comment]
Just curious: did Kobo put back `WIFI_MODULE_PATH ` with FW 4.23.15548  ? (meaning they would read around and care a little bit about the ecosystem - or not at all :)

**Comment by NiLuJe** [comment]
> Just curious: did Kobo put back `WIFI_MODULE_PATH ` with FW 4.23.15548 ? (meaning they would read around and care a little bit about the ecosystem - or not at all :)

No ^^.

**Comment by NiLuJe** [comment]
They did fix a minor annoyance I had with the DHCP setup when USBNet was enabled, though: http://trac.ak-team.com/trac/changeset/17720/niluje \o/

(Possibly as early as the original 4.23 release, I just stumbled on it today ;)).

**Pull request merged**
