### PR TITLE
bump HarfBuzz, cURL, libjpeg-turbo, crengine

### PR DESCRIPTION
**Pull request by poire-z**
- Update to HarfBuzz 3.1.1 https://github.com/koreader/koreader-base/pull/1432
- Update to cURL 7.80.0
- Update to libjpeg-turbo 2.1.2 https://github.com/koreader/koreader-base/pull/1433
- bump crengine: allows to open files from rclone mounts on Linux https://github.com/koreader/koreader-base/pull/1430

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8463)

### CODE REVIEW

**Comment by poire-z** [comment]
CircleCI build does not want to succeed :/
```
  CXX      libharfbuzz_la-hb-ot-shape-complex-use.lo
  CXX      libharfbuzz_la-hb-ot-shape-normalize.lo
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:2257: recipe for target 'libharfbuzz_la-hb-ot-shape-complex-thai.lo' failed
make[6]: *** [libharfbuzz_la-hb-ot-shape-complex-thai.lo] Error 1
make[6]: *** Waiting for unfinished jobs....
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:2159: recipe for target 'libharfbuzz_la-hb-ot-map.lo' failed
make[6]: *** [libharfbuzz_la-hb-ot-map.lo] Error 1
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:2026: recipe for target 'libharfbuzz_la-hb-aat-layout.lo' failed
make[6]: *** [libharfbuzz_la-hb-aat-layout.lo] Error 1
Makefile:2131: recipe for target 'libharfbuzz_la-hb-ot-color.lo' failed
make[6]: *** [libharfbuzz_la-hb-ot-color.lo] Error 1
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:2194: recipe for target 'libharfbuzz_la-hb-ot-shape-complex-arabic.lo' failed
make[6]: *** [libharfbuzz_la-hb-ot-shape-complex-arabic.lo] Error 1
In file included from hb-ot-shape-complex-use.cc:33:0:
hb-ot-shape-complex-use-machine.rl: In instantiation of ‘machine_index_t<Iter>::machine_index_t(const machine_index_t<Iter>&) [with Iter = hb_zip_iter_t<hb_iota_iter_t<unsigned int, unsigned int>, hb_filter_iter_t<hb_filter_iter_t<hb_zip_iter_t<hb_iota_iter_t<unsigned int, unsigned int>, hb_array_t<hb_glyph_info_t> >, find_syllables_use(hb_buffer_t*)::<lambda(const hb_glyph_info_t&)>, const<anonymous struct>&, 0u>, find_syllables_use(hb_buffer_t*)::<lambda(hb_pair_t<unsigned int, const hb_glyph_info_t&>)>, const<anonymous struct>&, 0u> >]’:
hb-ot-shape-complex-use-machine.rl:252:7:   required from here
hb-ot-shape-complex-use-machine.rl:197:3: warning: base class ‘struct hb_iter_with_fallback_t<machine_index_t<hb_zip_iter_t<hb_iota_iter_t<unsigned int, unsigned int>, hb_filter_iter_t<hb_filter_iter_t<hb_zip_iter_t<hb_iota_iter_t<unsigned int, unsigned int>, hb_array_t<hb_glyph_info_t> >, find_syllables_use(hb_buffer_t*)::<lambda(const hb_glyph_info_t&)>, const<anonymous struct>&, 0u>, find_syllables_use(hb_buffer_t*)::<lambda(hb_pair_t<unsigned int, const hb_glyph_info_t&>)>, const<anonymous struct>&, 0u> > >, hb_pair_t<unsigned int, hb_pair_t<unsigned int, hb_glyph_info_t&> > >’ should be explicitly initialized in the copy constructor [-Wextra]
   machine_index_t (const machine_index_t& o) : it (o.it) {}
   ^
make[6]: Leaving directory '/home/ko/project/base/thirdparty/harfbuzz/build/x86_64-linux-gnu/harfbuzz-prefix/src/harfbuzz/src'
Makefile:2969: recipe for target 'all-recursive' failed
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory '/home/ko/project/base/thirdparty/harfbuzz/build/x86_64-linux-gnu/harfbuzz-prefix/src/harfbuzz/src'
Makefile:1560: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/home/ko/project/base/thirdparty/harfbuzz/build/x86_64-linux-gnu/harfbuzz-prefix/src/harfbuzz/src'
Makefile:524: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/ko/project/base/thirdparty/harfbuzz/build/x86_64-linux-gnu/harfbuzz-prefix/src/harfbuzz'
Makefile:456: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/ko/project/base/thirdparty/harfbuzz/build/x86_64-linux-gnu/harfbuzz-prefix/src/harfbuzz'
ninja: build stopped: subcommand failed.
Makefile.third:26: recipe for target 'build/x86_64-linux-gnu/libs/libharfbuzz.so.0' failed
make[1]: *** [build/x86_64-linux-gnu/libs/libharfbuzz.so.0] Error 1
make[1]: Leaving directory '/home/ko/project/base'
Makefile:128: recipe for target 'base/build/x86_64-linux-gnu/luajit' failed
make: *** [base/build/x86_64-linux-gnu/luajit] Error 2

Exited with code exit status 2

CircleCI received exit code 2
```

Possibly related: `https://github.com/harfbuzz/harfbuzz/issues/2972`.
New mess with HB3.1.1, or CircleCI caprice, I have no idea :/ Pinging @NiLuJe @Frenzie .

**Comment by Frenzie** [comment]
The same already happened in base: https://app.circleci.com/pipelines/github/koreader/koreader-base/1090/workflows/a571ba84-396e-4290-ad37-8ece10b9f42f/jobs/9891

**Comment by NiLuJe** [comment]
Old GCC is broken :o}.

**Comment by Frenzie** [comment]
The one here in front still uses GCC 5.something for the moment but the one in base is 8.4, yes.

**Comment by poire-z** [comment]
So, what should we do ?
- revert the HB bump in base ?
- leave this PR open as is because you have the time to try upgrading GCC on our various system setups/images ?

**Comment by Frenzie** [comment]
Better to revert it; Android presumably won't work either.

**Comment by poire-z** [comment]
Or we can disable this warning being considered as a failure ?
as in `https://github.com/openjdk/jdk/pull/3873#issuecomment-833275591`, but dunno how we should do that on our side.

**Comment by poire-z** [comment]
But it's not only this warning, but the `g++: internal compiler error: Killed (program cc1plus)` which is more serious :/

**Comment by Frenzie** [comment]
If @NiLuJe is correct that it's not supposed to work on <5 regardless then keep in mind Android is using 4.9.0.

**Comment by Frenzie** [comment]
Sidnote, there are initiatives like https://forum.xda-developers.com/t/gcc-toolchain-eva-gcc-calling-all-kernel-devs.4221409/

**Comment by NiLuJe** [comment]
> If @NiLuJe is correct that it's not supposed to work on <5 regardless then keep in mind Android is using 4.9.0.

Gah, forgot about that ;/. I'll roll back to the version that builds later tonight (iirc 3.0.0).

**Comment by NiLuJe** [comment]
> Sidenote, there are initiatives like https://forum.xda-developers.com/t/gcc-toolchain-eva-gcc-calling-all-kernel-devs.4221409/

That one is bare metal (no libc), though, can't build anything else than a kernel ;).

**Comment by Frenzie** [comment]
That's very easy to change — a lot easier than making it all work with Clang. >_>

(But I suspect Android wants it all very… custom/weird. :-P)

**Comment by Frenzie** [comment]
Easier still; it's pretty much just a stripped down version of https://github.com/USBhost/build-tools-gcc/blob/52b4c23d325d4e2b67e33e44da5b8d432ac58ce7/build#L619-L646

**Comment by poire-z** [comment]
Btw, about the warning, there was this PR `https://github.com/harfbuzz/harfbuzz/pull/2973` whose commit has been overwritten by a possibly automated regeneration of the file https://github.com/harfbuzz/harfbuzz/commit/5898a9618cf6004d51c6fa2b34212c0ee61df3b0#diff-fe0bfddaa39eb13f48a8a647e6be678f3cc11fdc484d0c83dc749a0ce6217f63 from `https://github.com/harfbuzz/harfbuzz/pull/3205`

**Comment by poire-z** [comment]
Btw, it builds fine with my old `arm-linux-gnueabihf-g++ (Debian 8.3.0-2) 8.3.0`. I do get this same warning (`should be explicitly initialized in the copy constructor [-Wextra]`), but it does not prevent it from continuing building. So, I guess there is no need to fight this warning by resurrecting the old upstream fix.

**Comment by Frenzie** [comment]
Continued in https://github.com/koreader/koreader-base/pull/1434

**Pull request merged**
