### PR TITLE
DocSettings: Minor cleanup following #10861

### PR DESCRIPTION
**Pull request by NiLuJe**
Made a few private functions actually private ;).

Also bumps base & android for minor third-party updates.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10868)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
I'm fine with _ as a convention for private ftr. (Though in this case it didn't really seem to make much sense.)

**Comment by Frenzie** [comment]
The latter isn't private, lol.

**Comment by poire-z** [comment]
Beware things maybe getting complicated for @hius07 (using github web UI) if this one is merged before #10866.

(Not bothering about these methods getting to be local functions - but don't abuse that as local functions are hard to override from user-patches, and limit what we can fix&close this way :)

**Comment by Frenzie** [comment]
That's a great point actually. Making things private limits moddability for better and for worse.

**Pull request merged**
