### PR TITLE
bump crengine: support for inline margin/border/padding

### LINKED ISSUE #8156: crengine: border style not applied to inline elements
* KOReader version: v2021.05
* Device: Pixel 2

#### Issue
CSS rules essential to the text are not applied. 

#### Steps to reproduce

Opening the book in EPUB format "The Joy of Syntax" by June Casagrande

Here is how it looks in KOReader

Screenshot_20210830-195951

And this is the same page in Calibre

Source code from Calibre
```
<p class="ulf">The icing is <span class="u">on</span> <span class="strk">the cake</span>.</p>
<p class="ul">They gave the promotion <span class="u">to</span> <span class="strk">Claire</span>.</p>		
<p class="ul">He served <span class="u">with</span> <span class="strk">honor</span>.</p>
<p class="ul">They are <span class="u">from</span> <span class="strk">South Carolina</span>.</p>
<p class="ul">You’re <span class="u">in</span> <span class="strk">trouble</span>.</p>
<p class="ul">It’s somewhere <span class="u">over</span> <span class="strk">the rainbow</span>.</p>
<p class="ul">Glenn is <span class="u">on</span> <span class="strk">the phone</span>.</p>
<p class="ul">They were talking <span class="u">about</span> <span class="strk">me</span>.</p>
<p class="ull">This is just <span class="u">between</span> <span class="strk">us</span>.</p>
```

You can see the formatting is added with the "u" and "strk" classes.
An embedded css.css style sheet contains the following attributes:

```
span.strk {
	border-bottom:.25em solid #808183;
	}
span.strk-3 {
	border-bottom:.25em solid #333334;
	}
span.u {
	border-bottom:.25em solid #dbdcde;
	}

```
The Issue could be related to the CoolReader engine. I have tried many readers from Google Play store  (Moon+, Prestigio, Librera, EbookDroid, AlReader, FBreader...) and Lithium was the only reader that rendered the formatting correctly.

### PR DESCRIPTION
**Pull request by poire-z**
Includes:
- https://github.com/koreader/crengine/pull/477
  - lvtext: tweak object flags implementation
  - lvtext: rename LTEXT_WORD_IS_OBJECT to LTEXT_WORD_IS_IMAGE
  - lvtext: add LTEXT_OBJECT_IS_EMBEDDED_BLOCK
  - Text: support for inline margin/border/padding.
  Closes #8156.
- https://github.com/koreader/crengine/pull/478
  - PageMap: allow building synthetic pages numbers

cre: add synthetic page map functions. These are not yet used, it will need some thinking to address #9020 (if we really want to) - but the functions are there so we can experiment.

Also:
`ReaderPageMap: fix page labels in 2-columns mode`
Page labels on the right page could have some bad y position (they were never above the last page label on the left page).

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9072)

### CODE REVIEW

**Comment by hius07** [comment]
> add synthetic page map functions

@poire-z can you please look at it:

For synthetic labels, `self.ui.document:getPageMap()` returns `page = 1` for every label.

(I'm adding synthetic pagemap to the core)

**Comment by poire-z** [comment]
I will.
First observation: all page numbers are 1 in ref page number list. When you change font size and let the book reload, they are then ok.
I had a hard time resetting stuff to get back the list of 1s... not sure why. Then, changing Word spacing and letting the book reload still gave me a list of 1s.
Possibly just missing recomputing the page numbers on the first synthetic building. I'll need to get familiar again on how that is done.

**Comment by poire-z** [comment]
Ok, it's possible that the m_pagemap object gets to be sufficiently initialized - empty and page numbers computed (even if no page to compute) - before we call buildSyntheticPageMap().
When we call it, the fact that they were computed stays - so they are not recomputed.
This seems to solve it, and looks innocuous:
```diff
--- a/crengine/src/lvtinydom.cpp
+++ b/crengine/src/lvtinydom.cpp
@@ -20948,14 +20948,15 @@ void ldomDocument::buildAlternativeToc()
 void ldomDocument::buildSyntheticPageMap( int chars_per_synthetic_page )
 {
     m_pagemap._is_document_provided = false;
     if ( m_pagemap._chars_per_synthetic_page == chars_per_synthetic_page ) {
         return; // already done
     }
     m_pagemap.clear();
+    m_pagemap.invalidatePageInfo();
     if ( chars_per_synthetic_page <= 0 ) {
         m_pagemap._chars_per_synthetic_page = 0;
         return;
     }
     printf("CRE: building synthetic page map (%d)\n", chars_per_synthetic_page);
```
Do you need this quickly into frontend ? Or can you still work on your stuff if it's not there yet ?

**Comment by hius07** [comment]
Thanks, no rush, I can continue.

**Pull request merged**
