### PR TITLE
[UX] Allow keyboard layout selection

### PR DESCRIPTION
**Pull request by Frenzie**
Fixes <https://github.com/koreader/koreader/issues/3998>.

This is an unpolished quickie but I've been letting this slip for too
long due to fancier keyboard interaction concepts.

Screenshot_2019-09-04_21-33-41
Screenshot_2019-09-04_21-33-49
Screenshot_2019-09-04_21-33-56

### CODE REVIEW

**Comment by poire-z** [comment]
The order of the items is random (not the same in the file vs your screenshot) ?
Any chance to get them in some order (with may be en/default at first place)?
Would it make sense to give the menu item better names than these few letters? Or is that the classic naming for keyboards?
(Alternative, the 6 first letters of the keyboard, `qwerty`, `azerty`, `ㅃㅉㄸㄲㅆㅛ`, `あかさたなは`.)

**Comment by Frenzie** [comment]
That's part of what I mean by unpolished. ;-)

But sure, I can probably polish it at least a little tomorrow.

**Comment by Frenzie** [comment]
Screenshot_20190905_215814

**Comment by Frenzie** [comment]
@poire-z Do you think it's acceptable now for a first pass?

**Comment by noembryo** [comment]
Just saw this and I wonder, should I change the `el_keyboard.lua` to make it that the Greek characters are default?

**Comment by Frenzie** [comment]
@noembryo If that's what people expect from a Greek keyboard then that's probably a good idea. Judging by [this](https://en.wikipedia.org/wiki/Keyboard_layout#Greek) it looks like it should be delta for D, etc.?

**Comment by noembryo** [comment]
Yeap..
I'll try a PR (I did one already from the browser, maybe I'll try one from inside my IDE ;o)

**Pull request merged**
