### PR TITLE
WIP: Add gemini.koplugin

### PR DESCRIPTION
**Pull request by ziz57**
This plugin adds support for the gemini protocol.

This is not ready for merge as-is. I am creating this PR now to ask for advice on how to proceed. I developed this as a pure plugin which can be dropped on top of a vanilla KOReader installation. It has been available for a few months on gemini in that form, and it has a few users who seem happy with it. However, developing it as a pure plugin involved a few hacks involving accessing internals of KOReader modules which are meant to be private, so it will take a little more work to make it suitable for merge. I'm happy to do that, if it would then be merged.

My opinion is that gemini, as a lightweight text-first protocol, is very well suited to ebook readers, so I would consider this PR in-scope for the KOReader project. But it is a non-trivial chunk of code which goes beyond core reader functionality, so I would understand if the consensus ends up being that it shouldn't go in mainline KOReader, and then I'd submit it to contrib as-is.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12272)

### CODE REVIEW

**Comment by poire-z** [comment]
Cross-ref #7206 (if it is the same thing).

I don't know anything about that gemini thing, and I don't know the possible user base.
But as a member of the developer base, I'm not too keen on having that in the main/core koreader, because if it is, we won't think about it, and we will break it when making changes elsewhere, and we'll have to fix it (or not, and it will end up like the newsdownloader.koplugin, something we won't care about, and that someone dared rewriting and probably made it better - but it was a whole complex beast we didn't want to accept and maintain).

Also, there is a lot of text that we will bother translators with - it feels like an app of its own, which probably deserves to be one with a life (and a commits history) of its own :)

**Comment by Frenzie** [comment]
Do the custom link overrides largely predate the handledSchemes you added recently? If not handlers should be able to register themselves or something along those lines. :-)

I'm inclined to agree with @poire-z that it's perhaps slightly too adjacent to be included in the core (and crucially, to be maintained thereafter), even if it's about reading. 

Just a quick note, it looks like it crashes if you empty the input field and accidentally press backspace another time.
```
./luajit: plugins/gemini.koplugin/identities.lua:27: attempt to index local 'purl' (a nil value)
stack traceback:
        plugins/gemini.koplugin/identities.lua:27: in function 'normaliseIdentUrl'
        plugins/gemini.koplugin/identities.lua:78: in function 'get'
        plugins/gemini.koplugin/client.lua:1372: in function 'update_buttons'
        plugins/gemini.koplugin/client.lua:1576: in function 'edit_callback'
        frontend/ui/widget/inputtext.lua:563: in function 'initTextBox'
        frontend/ui/widget/inputtext.lua:862: in function 'delChar'
        frontend/ui/widget/inputtext.lua:600: in function 'handleEvent'
        frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
        frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
        frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
        frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
        ...
        frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
        frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
        frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
        frontend/ui/uimanager.lua:947: in function 'sendEvent'
        frontend/ui/uimanager.lua:53: in function '__default__'
        frontend/ui/uimanager.lua:1438: in function 'handleInputEvent'
        frontend/ui/uimanager.lua:1538: in function 'handleInput'
        frontend/ui/uimanager.lua:1582: in function 'run'
        ./reader.lua:280: in main chunk
        [C]: at 0x5e3658f157ab
```

**Comment by ziz57** [comment]
I understand the concerns about maintenance. I would aim to follow development and look out for anything which could affect the plugin -- I'll be doing that whether it's in core or not. If I can get rid of the ugly hacks which access widget internals, I don't think there should be so much room for accidental breakage, but of course there'll be some.

@Frenzie Thanks for the crash report. Fixed. The handledSchemes were to allow for following gemini links from a document opened in readerUI as usual.

**Comment by ziz57** [comment]
Even if this isn't merged, would you consider PRs which add little bits of functionality, even if currently the only user would be this plugin? Main things would be setting edit and enter callbacks in (Multi)InputDialog, adding buttons to MultiInputDialog, and a way to override onEndOfBook.

**Comment by Frenzie** [comment]
It slightly depends on the implementation specifics of course, but definitely.

**Comment by poire-z** [comment]
> Even if this isn't merged, would you consider PRs which add little bits of functionality, even if currently the only user would be this plugin?

Fine with that.

> Main things would be setting edit and enter callbacks in (Multi)InputDialog, adding buttons to MultiInputDialog, and a way to override onEndOfBook.

Fine with that too. We already have some for the highlight dialog, for the link dialog (yours I guess), for the dict ('Add to vocabulary builder"), and I guess any new one should try to follow the API/semantic/whatever of the existing ones.

**Comment by ziz57** [comment]
I should try to explain why I think the benefits of this plugin would outweigh the maintenance costs. Why would KOReader users want to access Gemini?

The fundamental point is that Gemini is a version of the web which is perfectly suited to ebook readers. A full web browser would obviously be out of scope for this project, massively dwarfing the existing codebase, whereas here we have a fully-featured Gemini client in fewer lines of code than e.g. the coverbrowser or statistics plugins. A web browser wouldn't even be so useful, given how little of the modern web consists of static content suitable for a e-ink display, whereas Gemini is designed to only serve static files, with interaction happening in a constrained way (via CGI) which we can handle perfectly with a few dialog boxes.

So what would Gemini on KOReader be good for? Primarily, accessing reading material. Examples of existing resources include a wikipedia mirror "Gemipedia" (preferable in some ways to KOReader's inbuilt wikipedia support), mirrors of many new sites such as The Guardian, a browsable version of the CIA World Factbook, as well as a large and expanding array of material published exclusively on Gemini (mostly personal blogs). Currently there aren't many collections of copyright-free books, but e.g. a Gutenberg mirror/proxy would be very feasible. There are also a number of interactive word games which could appeal to KOReader users and which are playable via this plugin, e.g. Spellbinding (a clone of NYT's Spelling Bee), as well as various interactive forums and such.

It's also possible for a user to set up a general http->gemini proxy, allowing access to static parts of the web (including e.g. Gutenberg), although that's currently a little fiddly.

OK, that's my pitch. I think the power-to-weight ratio of this plugin is rather large -- it lets the user do a lot with relatively little code to maintain.

**Comment by Commodore64user** [comment]
> So what would Gemini on KOReader be good for? Primarily, accessing reading material. Examples of existing resources include a wikipedia mirror "Gemipedia" (preferable in some ways to KOReader's inbuilt wikipedia support), mirrors of many new sites such as The Guardian, a browsable version of the CIA World Factbook, as well as a large and expanding array of material published exclusively on Gemini (mostly personal blogs). Currently there aren't many collections of copyright-free books, but e.g. a Gutenberg mirror/proxy would be very feasible. There are also a number of interactive word games which could appeal to KOReader users and which are playable via this plugin, e.g. Spellbinding (a clone of NYT's Spelling Bee), as well as various interactive forums and such

Unfamiliar with Gemini, so what you are saying is that you have access to the internet but not quite. I can’t really access NYT directly or The Guardian, or even Wikipedia. Well that just lost all its appeal to me, but i can see why others might like it.

my dream is to read PressReader (directly) on eink, looks like this isn’t it. I might just have to get one of those android ones.

**Comment by poire-z** [comment]
For reference: https://en.wikipedia.org/wiki/Gemini_(protocol)

> OK, that's my pitch. I think the power-to-weight ratio of this plugin is rather large -- it lets the user do a lot with relatively little code to maintain.

Thanks for the pitch :)
But having your plugin available in contrib or in your own repo, and maintained by you (with your little needed extensions to core we're ready to accept) will still allow these users to get that high power-to-weight ratio :)

My bias is that I never ever heard about Gemini (except in that other issue I linked to).
It may be popular and a revolution among its early adopters users base, but it's not something mainstream.
From your description, it feels like it is reinveting [Gopher](https://en.wikipedia.org/wiki/Gopher_(protocol)) :)
May be it will have some success, may be it will fail in a few years.

You may say that having it in core will contribute to its success - but we don't need to follow this orthogonal adventure. One of my fear is that, it there's some enthusiastic community, and KOReader becomes THE eInk/Android software that is the best for reading Gemini, that this enthusiastic community will invade us :) (our github, our thoughts, our energy) and we'll get tons of issues related to Gemini, and more invastion of koreader core to support new features and ideas.
But that's just me :)

**Comment by ziz57** [comment]
@poire-z OK, fair enough.

It is indeed reinventing Gopher, it was specifically envisioned as an updated version of Gopher. There are already a few Android clients, including the excellent Lagrange -- but for ebook readers there isn't really any other client, so your fears aren't groundless.

**Comment by NiLuJe** [comment]
Should this be closed, given https://github.com/koreader/contrib/pull/24?

**Comment by Commodore64user** [comment]
that was brutal. Fatality right there.

**Comment by hius07** [comment]
BTW, the link to the plugin in contrib is broken.

**Comment by Frenzie** [comment]
The link is to `https://repo.or.cz/gemini.koplugin.git`. GitHub does something weird with that.

**Pull request closed without merging**
