### PR TITLE
Bump base for better BB8 performance and bitness FFI stuff

### PR DESCRIPTION
**Pull request by Frenzie**
* Leave bitness-dependent types alone in FFI stuff https://github.com/koreader/koreader-base/pull/825 @NiLuJe
  Required for #4629.
* A few blitting changes for better BB8 performance https://github.com/koreader/koreader-base/pull/816 @NiLuJe

### CODE REVIEW

**Comment by Frenzie** [comment]
@NiLuJe I'm guessing/hoping this is failing because it doesn't have your change? :-)

**Comment by Frenzie** [comment]
Damn the torpedoes. :-)

**Comment by poire-z** [comment]
My rebuilt emulator is failing too with this base bump.
```
./luajit: ./ffi/SDL2_0_h.lua:817: size of C type is unknown or too large at line 587
stack traceback:
        [C]: in function 'cdef'
        ./ffi/SDL2_0_h.lua:817: in main chunk
        [C]: in function 'require'
        ./ffi/SDL2_0.lua:17: in main chunk
        [C]: in function 'require'
        ./ffi/framebuffer_SDL2_0.lua:2: in main chunk
        [C]: in function 'require'
        frontend/device/sdl/device.lua:66: in function 'init'
```
Removing the 2 added lines in `union SDL_Event {...}` makes it work again.
(Do I have too old SDL libraries? or @NiLuJe have too recent ones?)

**Comment by Frenzie** [comment]
Hm, why didn't the CI here give the proper error message like that? That would've been tremendously helpful. :-/

**Comment by Frenzie** [comment]
@poire-z The problem is much simpler. We simply never define those structs properly.

**Comment by Frenzie** [comment]
Last time I added this kind of thing manually @NiLuJe had some complaints, but these are the ones you need from SDL_events.h.

```c
/**
 *  \brief Sensor event structure (event.sensor.*)
 */
typedef struct SDL_SensorEvent
{
    Uint32 type;        /**< ::SDL_SENSORUPDATE */
    Uint32 timestamp;   /**< In milliseconds, populated using SDL_GetTicks() */
    Sint32 which;       /**< The instance ID of the sensor */
    float data[6];      /**< Up to 6 values from the sensor - additional values can be queried using SDL_SensorGetData() */
} SDL_SensorEvent;
```

```c
/**
 *  \brief Display state change event data (event.display.*)
 */
typedef struct SDL_DisplayEvent
{
    Uint32 type;        /**< ::SDL_DISPLAYEVENT */
    Uint32 timestamp;   /**< In milliseconds, populated using SDL_GetTicks() */
    Uint32 display;     /**< The associated display index */
    Uint8 event;        /**< ::SDL_DisplayEventID */
    Uint8 padding1;
    Uint8 padding2;
    Uint8 padding3;
    Sint32 data1;       /**< event dependent data */
} SDL_DisplayEvent;
```

Like so:

```diff
diff --git a/ffi/SDL2_0_h.lua b/ffi/SDL2_0_h.lua
index 0cce1e6..53f221b 100644
--- a/ffi/SDL2_0_h.lua
+++ b/ffi/SDL2_0_h.lua
@@ -558,6 +558,24 @@ struct SDL_DropEvent {
   char *file;
   Uint32 windowID;
 };
+struct SDL_SensorEvent
+{
+    Uint32 type;        /**< ::SDL_SENSORUPDATE */
+    Uint32 timestamp;   /**< In milliseconds, populated using SDL_GetTicks() */
+    Sint32 which;       /**< The instance ID of the sensor */
+    float data[6];      /**< Up to 6 values from the sensor - additional values can be queried using SDL_SensorGetData() */
+} SDL_SensorEvent;
+struct SDL_DisplayEvent
+{
+    Uint32 type;        /**< ::SDL_DISPLAYEVENT */
+    Uint32 timestamp;   /**< In milliseconds, populated using SDL_GetTicks() */
+    Uint32 display;     /**< The associated display index */
+    Uint8 event;        /**< ::SDL_DisplayEventID */
+    Uint8 padding1;
+    Uint8 padding2;
+    Uint8 padding3;
+    Sint32 data1;       /**< event dependent data */
+} SDL_DisplayEvent;
 union SDL_Event {
   Uint32 type;
   struct SDL_CommonEvent common;
```

**Comment by poire-z** [comment]
Indeed, that makes it work again! :)

**Comment by Frenzie** [comment]
Anyway, I'll wait for @NiLuJe to fix it (and also to tell me exactly what the proper procedure actually is). :-D

It has something to do with ffi-cdecl, presumably coupled with manual cleanup?

**Comment by NiLuJe** [comment]
I added new entries to a struct without the required typedefs, right?

Going out for a while, i'll take  alook at it ;).

**Pull request merged**
