### PR TITLE
Bump base & android

### LINKED ISSUE #12128: USB session start bug
*KOReader version: 202404000209
*Device: Kobo Libra 2

#### Koreader in 2 out of 3 times will not start USB session when connecting to MacBook Air and sometimes can't end the session with error "Could not end USBMS session device will restart in 90s".

I need to connect my device several times to make koreader start USB session, doesn't matter what cable I use. The same problem occurred with previous koreader versions. Crashlog down below.

IMG_0839

[crash.log](https://github.com/user-attachments/files/16042209/crash.log)

### LINKED ISSUE #12178: Kindle 2 joystick not working after 2024.07 update
* KOReader version: 2024.07
* Device: Kindle 2

#### Issue

After updating to 2024.07 on my Kindle 2, the five-way joystick does not function at all in KOReader. The other buttons seem to work normally, but I can't navigate through the menus. I couldn't figure out how to exit KOReader without the joystick, so I had to hard reset to get back to the Kindle UI. I tried doing a clean reinstall of KOReader, and the joystick still did not work.

### PR DESCRIPTION
**Pull request by NiLuJe**
Fix #12178
Fix #12128

This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12184)

### CODE REVIEW

**Comment by Frenzie** [comment]
There's a conflict of sorts with #12085
```
frontend/document/koptinterface.lua:213: bad argument #2 to 'getPagePix' (number expected, got no value)
```

**Comment by benoit-pierre** [comment]
Yes, #12085 should be merged first.

**Comment by NiLuJe** [comment]
Also the macOS runner is whining about its age ;).

**Comment by benoit-pierre** [comment]
> Also the macOS runner is whining about its age, but that's less of an immediate concern ;).

Where?

**Comment by NiLuJe** [comment]
> > Also the macOS runner is whining about its age, but that's less of an immediate concern ;).
> 
> Where?

`Makefile.defs:2: *** your version of make is too old: 3.81, need at least 4.1.  Stop.`

**Comment by benoit-pierre** [comment]
> > > Also the macOS runner is whining about its age, but that's less of an immediate concern ;).
> > 
> > 
> > Where?
> 
> `Makefile.defs:2: *** your version of make is too old: 3.81, need at least 4.1. Stop.`

I have an incoming PR for that particular issue, to be merged between #12085 and this one.

**Comment by benoit-pierre** [comment]
If you're wondering why the macOS jobs are not restoring a fallback cache: #12188…

**Comment by pazos** [comment]
@NiLuJe: could you include https://github.com/koreader/android-luajit-launcher/commit/fe0b70952dccfcccd972fd043a50a75a845e4285 in your bump?

**Comment by NiLuJe** [comment]
> @NiLuJe: could you include [koreader/android-luajit-launcher@fe0b709](https://github.com/koreader/android-luajit-launcher/commit/fe0b70952dccfcccd972fd043a50a75a845e4285) in your bump?

Done ;).

**Pull request merged**
