### PR TITLE
Quickstart guide kindle illustrations

### PR DESCRIPTION
**Pull request by Commodore64user**
### what's new

* we pick up where we left off, #12426, and finish the job. bish bash bosh.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12577)

### CODE REVIEW

**Comment by benoit-pierre** [comment]
FWIW, here's my in progress attempt at making a SVG version for the Kindle 4:
kindle4
(best viewed with a white background)

**Comment by Frenzie** [comment]
I'd presumably prefer an SVG, mainly on the assumption that it's sharper and smaller. But that's not super important.

**Comment by Commodore64user** [comment]
Well, these are supposed to be temporary innit (as offtorque said he's working on the real deal already), furthermore they take 70-80KB which is a relatively small size. And they look nice, although i might be biased though.

**Comment by Frenzie** [comment]
Could you replace them with these? I wrung them through pngquant.

[kindle.zip](https://github.com/user-attachments/files/17214235/kindle.zip)

**Comment by Commodore64user** [comment]
should be 2024.10 now ;)

**Pull request merged**
