### PR TITLE
kodev: add run android convenience shortcut

### PR DESCRIPTION
**Pull request by Frenzie**

### CODE REVIEW

**Comment by Frenzie** [comment]
@poire-z Btw, what's your opinion on gdb. Run target (`./kodev run gdb  --gdb-related-arg=nemiver`) or argument (`./kodev run --gdb=nemiver`)?

Except my intent is actually more like this:
```
GDB=$(which gdb)
if GDB
  if nemiver
  nemiver
  elif ddd
  ddd
  elif cgdb
  cgdb
  elif
  gdb -tui
fi
```

**Comment by poire-z** [comment]
Why not, but can't say much (I dont even have gdb installed, tried it a few times, never found my way in, so, I debug with printf statements...)

**Comment by Frenzie** [comment]
I probably intend to add it in anyway (executable docs) but which syntax do you suppose makes more sense or is clearer?

**Comment by poire-z** [comment]
The simpler `./kodev run --gdb=nemiver` , with simple form `./kodev run --gdb` to use gdb or the first one found. Or both :) `./kodev run gdb`

**Comment by Frenzie** [comment]
Yes, I mean run gdb vs run --gdb. The latter probably makes more sense as it's the default emulator target.

Any thoughts on the Android thing btw?

**Comment by poire-z** [comment]
> Any thoughts on the Android thing btw?

Good idea too, and nice monkey trick. (hoping i'll never have the need to install the whole android stuff).

**Comment by Frenzie** [comment]
All you need to do is `./kodev build android`, `./kodev release (--ignore-translation) android` or `./kodev run android` and it'll pull in everything automatically. Or near-automatically. You might need to set NDKABI=14 because NDK 15 doesn't support any lower. 

I already included this in luajit-launcher; I should add it to kodev with a 14.
https://github.com/koreader/android-luajit-launcher/blob/19779beabfbd6f8195efcaa998a739f39742c71e/mk-luajit.sh#L14

**Pull request merged**
