### PR TITLE
minor - clean up gettext

### PR DESCRIPTION
**Pull request by robert00s**

### CODE REVIEW

**Comment by robert00s** [comment]
But how to do that?
I tried to add a "__" in  `read_globals` but it doesn't work.

**Comment by Frenzie** [comment]
Adding something like `--ignore 21/_.*` to the invocation should work. But you should stick that in luacheckrc instead, see https://luacheck.readthedocs.io/en/stable/cli.html#patterns and https://github.com/koreader/koreader-base/blob/10d3aa43753d36e6449d54609a949524b7bd1959/.luacheckrc#L25-L28

**Comment by Frenzie** [comment]
Pardon, I just noticed my docs link explicitly mentions our example here. So it's probably best to just use the pattern from the docs, not my guess at it. ;-)

**Comment by Frenzie** [comment]
Sounds good to me. :-)

**Comment by poire-z** [comment]
>ignore = {"631",
          "211/_.*",
}

with comments please, so we know what these obscur numbers mean :) Or just a link to https://luacheck.readthedocs.io/en/stable/module.html above.

And do we really want to not be warned when `_private_variable` is unused ?
`__*` would be enough to ignore `_` `__` `___` `____` `_____`

**Comment by Frenzie** [comment]
> with comments please, so we know what these obscur numbers mean :) Or just a link to https://luacheck.readthedocs.io/en/stable/module.html above.

Just do both. 211 means this, see luacheck.etc for full deets.

> And do we really want to not be warned when _private_variable is unused ?

Good point.

**Pull request merged**
