### PR TITLE
[fix] Don't crash when trying to go to deleted folders

### LINKED ISSUE #4107: Appimage crash
Trying to load a pdf file.

* KOReader version:
koreader-appimage-x86_64-linux-gnu-v2015.11-1735-g14e7730_2018-06-02.AppImage

* Device:
Debian x64

#### Issue
```
 [*] Version: v2015.11-1735-g14e7730_2018-06-02

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load: SDL2
SDL: no gamecontrollers connected
ffi.load: libs/liblodepng.so
07/25/18-11:56:12 WARN  ./ffi/SDL2_0.lua:386: /tmp/.mount_koreadGZIBDy/libs/libSDL2.so: undefined symbol: SDL_CreateRGBSurfaceWithFormatFrom
ffi.load: gtk-3
ffi.load: gtk-3
07/25/18-11:56:12 INFO  initializing for device SDL
07/25/18-11:56:12 INFO  framebuffer resolution: {
    ["h"] = 800,
    ["w"] = 600
}
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
07/25/18-11:56:12 INFO  Loading plugins from directory: plugins
07/25/18-11:56:12 INFO  Plugin  plugins/SSH.koplugin/main.lua  has been disabled.
07/25/18-11:56:12 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
ffi.load: sqlite3
ffi.load: z
ffi.load: sqlite3
07/25/18-11:56:12 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
07/25/18-11:56:12 INFO  Plugin  plugins/timesync.koplugin/main.lua  has been disabled.
07/25/18-11:56:12 INFO  FM loaded plugin AutoSuspend at plugins/autosuspend.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin batterystat at plugins/batterystat.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin coverbrowser at plugins/coverbrowser.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin evernote at plugins/evernote.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin goodreads at plugins/goodreads.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin keepalive at plugins/keepalive.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin kobolight at plugins/kobolight.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin newsdownloader at plugins/newsdownloader.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin perception_expander at plugins/perceptionexpander.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin send2ebook at plugins/send2ebook.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin statistics at plugins/statistics.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin systemstat at plugins/systemstat.koplugin
07/25/18-11:56:12 INFO  FM loaded plugin terminal at plugins/terminal.koplugin
./luajit: frontend/util.lua:176: attempt to index local 'text' (a nil value)
stack traceback:
	frontend/util.lua:176: in function 'utf8Reverse'
	frontend/apps/filemanager/filemanager.lua:52: in function 'truncatePath'
	frontend/apps/filemanager/filemanager.lua:162: in function 'onPathChanged'
	frontend/ui/widget/filechooser.lua:290: in function 'changeToPath'
	plugins/coverbrowser.koplugin/main.lua:415: in function 'refreshFileManagerInstance'
	plugins/coverbrowser.koplugin/main.lua:505: in function 'action'
	frontend/ui/uimanager.lua:597: in function '_checkTasks'
	frontend/ui/uimanager.lua:818: in function 'handleInput'
	frontend/ui/uimanager.lua:904: in function 'run'
	./reader.lua:195: in main chunk
	[C]: at 0x00404fe0

```

### PR DESCRIPTION
**Pull request by Frenzie**
Fixes #4107.

### CODE REVIEW

**Comment by poire-z** [comment]
Isn't that fixing the problem a bit too down?
(This function expects a string to work on it, it's ok for it to crash it no string -  it means we have a bug somewhere up where we thought we had a string but had a nil. This could mask other bugs I guess.)

**Comment by poire-z** [comment]
Dunno if we should keep just fixing that directory abbreviating.
With abbreviation disabled: some quick test with a non existant lastdir and home_dir have classic filemanager show zero file and a non-existant path (coverbrowser crashes because it tries to do something more with that I guess).
Going up a directory lead to something still bad. Going up lead to me being back in koreader own dir.

Dunno if we shoudn't instead just answer : what to do when the directory we want to go in does not exist? Should we fake its existence and allow going up till we meet an existing one (/ possibly), or should we switch to the default dir or koreader own dir.

**Comment by Frenzie** [comment]
> With abbreviation disabled: some quick test with a non existant lastdir and home_dir have classic filemanager show zero file and a non-existant path (coverbrowser crashes because it tries to do something more with that I guess).

Yes, that's the behavior I expect. The introduction of the abbreviation thingy introduced this crashing bug. So from my perspective I'm fixing the "new" bug.

**Comment by poire-z** [comment]
I think it all (abbreviate + truncate which uses utf8reverse) starts to go wrong there:
https://github.com/koreader/koreader/blob/60a6d5f542908a2a4a457fa05a868276bdd32572/frontend/ui/widget/filechooser.lua#L281-L283
which returns path=nil when realpath is given a non-existing dir.

**Comment by Frenzie** [comment]
I think nil is the right value because it properly indicates that there is no value. In my view it's one of the functions further down that doesn't deal with nil properly that's the problem.

**Comment by Frenzie** [comment]
Admittedly in this highly specific case of a path nil and "" are equal. It's more of a generic coding style POV.

**Comment by poire-z** [comment]
Well, you can get rid of the issue that way (I prefer if you put the nil tests more where we're dealing with a path, rather than in the utf8Reverse that is a plain string function):
```lua
diff --git a/frontend/apps/filemanager/filemanager.lua b/frontend/apps/filemanager/filemanager.lua
index 74294a11..9d11c1be 100644
--- a/frontend/apps/filemanager/filemanager.lua
+++ b/frontend/apps/filemanager/filemanager.lua
@@ -46,6 +46,7 @@ local function restoreScreenMode()
 end

 local function truncatePath(text)
+    if not text then return "" end
     local screen_width = Screen:getWidth()
     local face = Font:getFace("xx_smallinfofont")
     -- we want to truncate text on the left, so work with the reverse of text (which is fine as we don't use kerning)
diff --git a/frontend/apps/filemanager/filemanagerutil.lua b/frontend/apps/filemanager/filemanagerutil.lua
index 567943bd..8fb9289d 100644
--- a/frontend/apps/filemanager/filemanagerutil.lua
+++ b/frontend/apps/filemanager/filemanagerutil.lua
@@ -21,6 +21,7 @@ function filemanagerutil.getDefaultDir()
 end

 function filemanagerutil.abbreviate(path)
+    if not path then return "" end
     local home_dir_name = G_reader_settings:readSetting("home_dir_display_name")
     if home_dir_name ~= nil then
         local home_dir = G_reader_settings:readSetting("home_dir") or filemanagerutil.getDefaultDir()

```

But I'm ok with that just because it seems everything works (including CoverBrowser) with just that :), even if they display crap (Classic FileManager more, CoverBrowser modes seems to get back to some existing directory for some reason I haven't checked).

(But if there would have been more problems beyond that, I would have insisted on ensuring path is never nil: don't fix 10 things to work with the improable `path=nil` when the first thing in a system/process/... life is to have a valid current working directory: just make sure 1 time we have a valid current working directory, and you don't have to fix the 10 things. But may be in the future, new stuff will be introduced that assume path is naturally a valid string, that will fail 6 months later when a person try it on Appimage.)

**Comment by Frenzie** [comment]
Well yes, I already agreed with that. :-P I'll rebase to make it so.

In changeToPath I believe a proper fix would be something more along these lines (and not using an empty string).

```diff
diff --git a/frontend/ui/widget/filechooser.lua b/frontend/ui/widget/filechooser.lua
index 593368df..c1901c90 100644
--- a/frontend/ui/widget/filechooser.lua
+++ b/frontend/ui/widget/filechooser.lua
@@ -280,7 +280,7 @@ end
 
 function FileChooser:changeToPath(path, focused_path)
     path = util.realpath(path)
-    self.path = path
+    self.path = path or lfs.currentdir()
 
     if focused_path then
         self.focused_path = focused_path
```

**Comment by poire-z** [comment]
`self.path = path or lfs.currentdir()` looks nice and obvious :)

Or use `self.path = path or self.path` (if by chance, something previously has already set a correct and valid self.path and it's just this `last_dir` processing that moves away from this first path - haven't checked).
Or `self.path = path or self.path or lfs.currentdir()` :)
(With possibly a log.warn() so we know from the crash.log what it was without having to ask the user.)

**Pull request merged**
