### PR TITLE
Bump base: crengine update

### PR DESCRIPTION
**Pull request by Frenzie**
* crengine: return description and keywords metadata
  Only available for EPUB documents for now. @poire-z
* crengine: css related improvements, fix crash, better handling of gif @frankyifei

### CODE REVIEW

**Comment by Frenzie** [comment]
@Hzj-jie I don't know quite what to make of this error.
```
Failure → spec/front/unit/readhistory_spec.lua @ 196
ReadHistory module should be able to remove two items
spec/front/unit/readhistory_spec.lua:37: Expected objects to be the same.
Passed in:
(string) 'a'
Expected:
(string) 'd'

stack traceback:
	spec/front/unit/readhistory_spec.lua:37: in function 'assert_item_is'
	spec/front/unit/readhistory_spec.lua:209: in function <spec/front/unit/readhistory_spec.lua:196>
```

**Comment by Hzj-jie** [comment]
It looks like the test case itself is not robust, once two files are created in different seconds, it will fail.
I will update the test case later. But after a retry, the test should pass.

**Comment by Hzj-jie** [comment]
The reader link spec may be impacted by crengine change.

**Comment by Frenzie** [comment]
It was but that was expected. :-)

**Comment by Frenzie** [comment]
Fixes #2840 and #2849.

**Pull request merged**
