### PR TITLE
bump crengine: HTML and rendering fixes

### PR DESCRIPTION
**Pull request by poire-z**
Includes:
- Fix getting xpointer to current page https://github.com/koreader/crengine/pull/195
- epub.css cleanup https://github.com/koreader/crengine/pull/194
- fb2def.h update https://github.com/koreader/crengine/pull/196
- Fix a few edge-case rendering issues https://github.com/koreader/crengine/pull/197
- Fix border being drawn in spite of 'border-width: 0' https://github.com/koreader/crengine/pull/198

Also update Wikipedia epub.css stylesheets regarding recent HTML fixes and enhancements.
Remove "Remove all borders" workaround tweak, as it's now fixed.

Some class name based styles have been removed from epub.css, mostly some stuff related to the FB2 format that was probably the first format supported by Cool Reader. For those nostalgic of these added styles, here's a file with them that can be put in `koreader/styletweaks `and applied via `User style tweaks`:
[CoolReader epub additions.css.txt](https://github.com/koreader/koreader/files/2064916/CoolReader.epub.additions.css.txt)

### CODE REVIEW

**Comment by poire-z** [comment]
I'm off to bed. @NiLuJe , if you're not :) , and you agree with the above, feel free to merge this one if you want to go on with yours. Or else, we'll work that out tomorrow.

**Comment by NiLuJe** [comment]
I'm in absolutely no hurry to get #3983 in, so, everyone take your time, I'll re-bump base in #3983 once everything's okay. I'll squash it anyway (and it's in a branch on my end, so the history can stay fully available, for science!), so, not a problem ;).

**Comment by poire-z** [comment]
But if I bump a new crengine in base and want to bump it in this PR, this will carry your merged `Proper REAGL handling on Kobo Aura (#676)` with it.
https://github.com/koreader/koreader-base/commits/master
Will that work bumped into koreader if your #3983 is not (no brekage to the existing framebuffer API)?

**Comment by NiLuJe** [comment]
It shouldn't, it only adds and fixes stuff. The trickiest thing might be the BGR stuff, but the missing bits should evaluate to nil and default to RGB as before.

The (base) CI passed cleanly without the KO bits, so that shouldn't be a worry either ;).

luacheck *might* complain about some stuff, but that's the extent of it ;).

**Comment by poire-z** [comment]
Mhhh, about this blank first page on juliet.epub...
Quite tough to understand why a change happened, but here's what I got.
Built DOM from the first 2 fragments:
```html
<?xml version="1.0"?>
<body>
  <DocFragment id="_doc_fragment_0">
    <body>
      <div style="text-align: center">
        <img src="OPS/images/cover.png" alt="Cover" style="display:inline"/>
      </div>
    </body>
  </DocFragment>
  <DocFragment StyleSheet="OPS/css/title.css" id="_doc_fragment_1">
    <body>
      <div class="body">
        <div class="logo"><img src="OPS/images/logo-feedbooks-tiny.png" alt="Feedbooks" title="Feedbooks"/>some text that I added to check</div>
        <h1>Romeo and Juliet</h1>
        <h2><span/>William Shakespeare</h2>
      </div>
      <div class="infos"><br/><b>Published:</b> 1597<br/> <b>Categorie(s):</b> Fiction, Drama, Romance<br/> <b>Source:</b> http://shakespeare.mit.edu</div>
    </body>
  </DocFragment>
</body>
```

Before my change mentionned above, we got:
Page 1: cover image
Page 2: blank page
Page 3: Feedbooks NEWLINE some text that I added to check
Page 4: Romeo and Juliet

Some logs:
```
60 1 1 1 1   img inline
  no clear newline flag
16 2 0 1 1    div block
  clear newline flag
Resize image (520x800) max 580x578 block
2Resize image (520x800) max 580x578 arbitrary  *1 => w=375 h=577
Resize image (520x800) max 580x578 block
2Resize image (520x800) max 580x578 arbitrary  *1 => w=375 h=577
```

After my change:
Page 1: blank page
Page 2 cover image
Page 3: blank page
Page 4: Feedbooks NO_NEWLINE some text that I added to check
Page 5: Romeo and Juliet

Some logs:
```
60 1 1 1 1    img inline
  clear newline flag 1 > 0
16 2 0 1 1    div block
  clear newline flag 2 > 0
Resize image (520x800) max 580x578 inline
2Resize image (520x800) max 580x578 integer  *1 => w=375 h=578
Resize image (520x800) max 576x578 inline
2Resize image (520x800) max 576x578 integer  *1 => w=375 h=578
```

I get the exact same flags stuff for the cover image and the Feedbooks image, so I guess my change is valid to solve the NEWLINE if image first child followed by some text.
Which is also what happens with the first image: the spaces in the HTML make for some text after the cover image. If I remove all the spaces to get:
`  <body><div style="text-align: center">Cover</div></body>`
I get no blank page at start.

Anyway, the thing is that (not even sure, as all this code is quite complicated and I don't yet grasp all of it)
- before my change: image and following text on 2 lines => image is alone and some code in lvtextfm.cpp check for the nb of source fragments to decide (that seems wrong) if it is inline or block, and which image zooming option to use => it choose block/arbitraty (as the image is alone), which made an image of size 577.
- after my change: image and following text on same line  => image is not alone and some code in lvtextfm.cpp check for the nb of source fragments to decide (that seems wrong) if it is inline or block, and which image zooming option to use => it choose inline/integer (as it must be inline, if it is not alone), which made an image of size 578.

Then, I guess, the lvpagesplitter code has some block of 578+1px+1px because of this in our epub.css:
```css
div {
    margin: 1px;
}
```
580 does not fit on a page, and [some code I added months ago](https://github.com/koreader/crengine/pull/119) decides to push that on the next page.
When the image is 577px + 1px + 1px, 578 or 579 fits on first page, so it let it be there.

I guess the lvpagesplitter code needs some tweak: if that block has a height larger than screen height and there's nothing before it: no need to push that on next page where it will be spliced anyway: just do that on current page.

BUT, a quick solution which fixes this problem is just to remove the `div { margin: 1px; }` from epub.css (I hesitated doing that last week, as it seems unnecessary and may cause small alignments problems when multiple imbricated DIV).
Without that added 1px (or 2) to the DIV containing the image, the block fits on the first page, and there's not more blank pages

With my change and no `div { margin: 1px; }`, we would get:
Page 1 cover image
Page 2: Feedbooks NO_NEWLINE some text that I added to check
Page 3: Romeo and Juliet

So, should I just do that: remove `div { margin: 1px; }` and solve another blank page bug?

**Comment by poire-z** [comment]
@frankyifei : do you remember why you added `margin: 1px;` to DIV in https://github.com/koreader/crengine/pull/40 ?

**Comment by poire-z** [comment]
OK, I get many unit test failure while bringing @NiLuJe base with me:
```
ffi/framebuffer.lua:363: attempt to call method 'hasBGRFrameBuffer' (a nil value)

stack traceback:
	ffi/framebuffer.lua:363: in function 'shot'
	spec/front/unit/readerhighlight_spec.lua:89: in function <spec/front/unit/readerhighlight_spec.lua:87>
```
I guess for that, and for coherency/cleanness of the koreader+base bumps, it's cleaner to:
1) bump this PR with only the original commit, with 3 unit tests failures
2) bump @NiLuJe #3983 with its base => still my 3 unit tests failures
3) I go on with bumping crengine and fixing these unit tests

**Comment by NiLuJe** [comment]
Yeah, that's the one I was worried about, sorry about that -_-".

**Pull request merged**
