### PR TITLE
Style tweaks: reorganize menu, add in-page footnotes helper tweaks

### LINKED ISSUE #9281: Some pictures doesn't show
* KOReader version:v2022.06
* Device:Android Tablet

#### Issue
Some pictures in this file doesn't show.
the pictures in page number 4.5.6.7.14 and there's is more
#### Steps to reproduce
https://drive.google.com/file/d/16pDW_IWipH_4R35GCFGKgy54D7VCT2FQ/view

### LINKED ISSUE #9297: crash when reading epub file generated by wallabag
* KOReader version:v2022.06
* Device:sp9832e_1h10_gofu_osll

#### Issue
crash when reading the last page of epub file generated by wallabag.
but the version v2020.11 is ok.
##### `crash.log` (if applicable)

07-05 16:10:02.890 19351 19367 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 19367 (Thread-174), pid 19351 (reader.launcher)
07-05 16:10:02.969 19372 19372 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-05 16:10:02.969 19372 19372 F DEBUG   : Native Crash TIME: 135187238
07-05 16:10:02.969 19372 19372 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-05 16:10:02.970 19372 19372 F DEBUG   : Build fingerprint: 'SPRD/sp9832e_1h10_gofu_osll/sp9832e_1h10_go:8.1.0/SC801a.V91/21310:user/release-keys'
07-05 16:10:02.970 19372 19372 F DEBUG   : Revision: '0'
07-05 16:10:02.970 19372 19372 F DEBUG   : ABI: 'arm'
07-05 16:10:02.970 19372 19372 F DEBUG   : pid: 19351, tid: 19367, name: Thread-174  >>> org.koreader.launcher <<<
07-05 16:10:02.970 19372 19372 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
07-05 16:10:02.970 19372 19372 F DEBUG   : Cause: null pointer dereference
07-05 16:10:02.971 19372 19372 F DEBUG   :     r0 00000001  r1 81e27640  r2 8886333c  r3 878fe598
07-05 16:10:02.971 19372 19372 F DEBUG   :     r4 878fe59c  r5 883cdb80  r6 00000000  r7 00000001
07-05 16:10:02.971 19372 19372 F DEBUG   :     r8 00000000  r9 878fe598  sl 00000000  fp 00000000
07-05 16:10:02.972 19372 19372 F DEBUG   :     ip 8b4d7738  sp 8b4d7620  lr 81e27640  pc 887287f2  cpsr 80000030
07-05 16:10:02.988 19372 19372 F DEBUG   :
07-05 16:10:02.988 19372 19372 F DEBUG   : backtrace:
07-05 16:10:02.988 19372 19372 F DEBUG   :     #00 pc 001147f2  /data/data/org.koreader.launcher/files/libs/libcrengine.so
07-05 16:10:02.988 19372 19372 F DEBUG   :     #01 pc 00114b45  /data/data/org.koreader.launcher/files/libs/libcrengine.so
07-05 16:10:02.988 19372 19372 F DEBUG   :     #02 pc 00114bcd  /data/data/org.koreader.launcher/files/libs/libcrengine.so
07-05 16:10:02.988 19372 19372 F DEBUG   :     #03 pc 00091287  /data/data/org.koreader.launcher/files/libs/libcrengine.so
07-05 16:10:02.989 19372 19372 F DEBUG   :     #04 pc 0012bb93  /data/data/org.koreader.launcher/files/libs/libcrengine.so
07-05 16:10:02.989 19372 19372 F DEBUG   :     #05 pc 0014e03d  /data/data/org.koreader.launcher/files/libs/libcrengine.so
07-05 16:10:02.989 19372 19372 F DEBUG   :     #06 pc 0015da29  /data/data/org.koreader.launcher/files/libs/libcrengine.so
07-05 16:10:02.990 19372 19372 F DEBUG   :     #07 pc 0015d7fb  /data/data/org.koreader.launcher/files/libs/libcrengine.so
07-05 16:10:02.990 19372 19372 F DEBUG   :     #08 pc 0015d7fb  /data/data/org.koreader.launcher/files/libs/libcrengine.so
07-05 16:10:02.990 19372 19372 F DEBUG   :     #09 pc 0015d7fb  /data/data/org.koreader.launcher/files/libs/libcrengine.so
07-05 16:10:02.990 19372 19372 F DEBUG   :     #10 pc 0015d7fb  /data/data/org.koreader.launcher/files/libs/libcrengine.so
07-05 16:10:02.991 19372 19372 F DEBUG   :     #11 pc 0015d7fb  /data/data/org.koreader.launcher/files/libs/libcrengine.so
07-05 16:10:02.991 19372 19372 F DEBUG   :     #12 pc 0013d88b  /data/data/org.koreader.launcher/files/libs/libcrengine.so
07-05 16:10:02.991 19372 19372 F DEBUG   :     #13 pc 0013db79  /data/data/org.koreader.launcher/files/libs/libcrengine.so
07-05 16:10:02.991 19372 19372 F DEBUG   :     #14 pc 0013dc09  /data/data/org.koreader.launcher/files/libs/libcrengine.so
07-05 16:10:02.991 19372 19372 F DEBUG   :     #15 pc 00011b0f  /data/data/org.koreader.launcher/files/libs/libkoreader-cre.so
07-05 16:10:02.991 19372 19372 F DEBUG   :     #16 pc 00007890  /data/app/org.koreader.launcher-j22ZV2VGt2Yi63bm_t1TTA==/lib/arm/libluajit.so
07-05 16:10:02.991 19372 19372 F DEBUG   :     #17 pc 000490eb  /data/app/org.koreader.launcher-j22ZV2VGt2Yi63bm_t1TTA==/lib/arm/libluajit.so
07-05 16:10:02.991 19372 19372 F DEBUG   :     #18 pc 00007890  /data/app/org.koreader.launcher-j22ZV2VGt2Yi63bm_t1TTA==/lib/arm/libluajit.so
07-05 16:10:02.991 19372 19372 F DEBUG   :     #19 pc 000490eb  /data/app/org.koreader.launcher-j22ZV2VGt2Yi63bm_t1TTA==/lib/arm/libluajit.so
07-05 16:10:02.991 19372 19372 F DEBUG   :     #20 pc 00007890  /data/app/org.koreader.launcher-j22ZV2VGt2Yi63bm_t1TTA==/lib/arm/libluajit.so
07-05 16:10:02.991 19372 19372 F DEBUG   :     #21 pc 00048221  /data/app/org.koreader.launcher-j22ZV2VGt2Yi63bm_t1TTA==/lib/arm/libluajit.so (lua_pcall+20)
07-05 16:10:02.992 19372 19372 F DEBUG   :     #22 pc 00001657  /data/app/org.koreader.launcher-j22ZV2VGt2Yi63bm_t1TTA==/lib/arm/libluajit-launcher.so (android_main+298)
07-05 16:10:02.996 19372 19372 F DEBUG   :     #23 pc 0000232d  /data/app/org.koreader.launcher-j22ZV2VGt2Yi63bm_t1TTA==/lib/arm/libluajit-launcher.so
07-05 16:10:02.997 19372 19372 F DEBUG   :     #24 pc 00046f7b  /system/lib/libc.so (__pthread_start(void*)+22)
07-05 16:10:02.997 19372 19372 F DEBUG   :     #25 pc 0001a2a7  /system/lib/libc.so (__start_thread+32)
07-05 16:10:03.838   655   766 E WifiNetworkMonitor: Not any Obervers!!!
07-05 16:10:04.197   440   440 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_00
07-05 16:10:04.261   655   747 E InputDispatcher: channel 'bd4b03 org.koreader.launcher/org.koreader.launcher.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-05 16:10:04.425   260   344 E SWTCON  : swtcon_request_output
07-05 16:10:04.425   260   344 E SWTCON  : sSwtcon::start
07-05 16:10:04.569   260   348 E SWTCON  : Flip snum = 1, has_next = 1
07-05 16:10:05.440   260   348 E SWTCON  : Flip snum = 77, has_next = 0

### PR DESCRIPTION
**Pull request by poire-z**
#### bump crengine: style tweaks helpers, other fixes

Includes https://github.com/koreader/crengine/pull/485 :
- CSS: add "-cr-hint: late" to increase selectors specificity
- CSS: add a few non-static "-cr-only-if:" values
- getStyledImageSize(): fix missing images when gRenderDPI=0
  Closes #9281
- Text: fix possible crash with floats and `<br/>`
- LVImg: fix crash on GIF images without color table
  Closes #9297

Discussion, decisions and screenshots at https://github.com/koreader/koreader/pull/5863#issuecomment-1154234889 and follow ups.

#### Style tweaks: reorganize menu items

Make them a bit more logically grouped by topic.  Update a few priorities.
There should be no wording/css change (except for duplicating some paragraph horizontal margin one).
I made "In-page footnotes" be a first level menu (it was in Misc, thought about moving it into Page and margins, but well, it's probably one of the most often accessed, so let it be there).

#### Style tweaks: handle conflicting/redundant tweaks

Disable redundant or incompatible tweaks when enabling some.
This makes the menu more dynamic to show what's impacted, save some re-renderings, and may avoid the user trying combinations that would have no effect.

#### Style tweaks: add In-page footnote font size and fix-up tweaks

Should help fixing many footnotes text size and layout issues without having to hack a Book style tweak.
See https://github.com/koreader/koreader/pull/5863#issuecomment-1173097714 (but I probably did some rewording after).
image
image
image

Rewording suggesions welcome (including for each `description`, not screenshoted above).

#### TouchMenu: add swipe south to go back to parent menu
https://github.com/koreader/koreader/pull/5863#issuecomment-1175578046

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9300)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
The conflicts stuff is pretty clever. :-)

**Comment by poire-z** [comment]
(Thanks for having me look at it again, and see that I had a bug, after a too quick code reorg :/ so, I had again a quick code reorg to test my luck :)

**Comment by mergen3107** [comment]
```
Style tweaks: add "Reset main text font size"
```
@poire-z 
Thank you super so much especially for this tweak! It saved all my tailored profiles used in epubs :D (many, way too many epub books have some arbitrary font-size rescale of the body font, like 86.9999%. Why, oh why, oh well)

**Comment by Frenzie** [comment]
Such strange numbers aren't entirely arbitrary, though I do think they can often be a bit misguided.

The basic idea is that the default font size is normally 16px, so a value like 87.5% would come to 14px, and 75% to 12px. I suspect you made up 86.9999% at random, but if not it might date back to some kind of rounding/flooring in browsers from 20 years ago that necessitated not going for the obvious value as a workaround.

Using a value 14px will scale the same way in modern rendering engines, but in old IE only percentage/em type values would scale while pixels would always be pixels.

**Comment by mergen3107** [comment]
@Frenzie 
Oh, thanks for the insight! Yes, I tried to remember the value from the top of my head. Now looked up again, it is actually `font-size: 0.88889em;`, so that looks like `16/18` ratio.

It just seems very strange to me, having the **body** font not at 100% scale. Shouldn't the body text be the main attraction in a book? :D and everything else around should just scale based on its font size (heading, sub/super scripts, etc).

**Comment by Frenzie** [comment]
> It just seems very strange to me, having the body font not at 100% scale. Shouldn't the body text be the main attraction in a book? :D and everything else around should just scale based on its font size (heading, sub/super scripts, etc).

That's what I meant by misguided. Effectively book/website authors assume users don't know how to set their default fontsize _and_ that they'll prefer it smaller just like they do. The latest frameworks like Bootstrap 4/5 have moved away from that and now default to 1rem instead of 0.875rem.

**Comment by Frenzie** [comment]
> Disable redundant or incompatible tweaks when enabling some.
This makes the menu more dynamic to show what's impacted, save some re-renderings, and may avoid the user trying combinations that would have no effect.

I think `conflicts_with = function(id) return util.stringStartsWith(id, "footnote-inpage_") end,` broke enabling all three types of footnotes at once. I'm not a fan of that change and it feels unintentional.

**Comment by poire-z** [comment]
It was intentional on my part :) and you live with it for 4 years :)

I get that maybe you'd want to have Wikipedia auto enabled on Wikipedia articles (it makes no sense on other books). And we enable EPUB foonotes by default - Classic classnames is too risky to enable by default, and I think it should be enabled only manually when EPUB footnotes does not work.

**Comment by Frenzie** [comment]
> and you live with it for 4 years

That's true, but that's because I have both EPUB and Wikipedia enabled by default from the time it was still possible. I only noticed this issue when I just enabled classic classname footnotes for apparently the first time in over four years, which then killed the other two.

**Comment by Frenzie** [comment]
Oh wait, you can still long press and enable them by default. That explains how I never noticed previously because I think I only got my Libra 2 after 2022 (and I didn't copy over my settings, only my books).

**Comment by Frenzie** [comment]
So… never mind, even if that inconsistency seems surprising. :-)

**Pull request merged**
