### PR TITLE
Move to archive on end

### PR DESCRIPTION
**Pull request by grasegger**
Followup to #6164 

This Pull Request introduces:

* A way to add new action to the popup that opens after a document end is reached
* The "move to archive" plugin using that way to provide a quick way to move files to the archive
* Fixed a bug where a old state of the movetoarchive settings was held in memory
* A setting to "move to archive" that allows you to skip the popup after a move
* A setting for the default action when movetoarchive shows no popup

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7598)

### CODE REVIEW

**Comment by NiLuJe** [comment]
I'd be inclined to drop all the ugliness from readerstatus, add an event handler in the plugin, and send an event, and plugin or no plugin loaded be damned.

(That's a rather strong veto on the whole readerstatus shenanigans there ^^).

**Comment by grasegger** [comment]
@NiLuJe I get what you are saying, but that definitely is out of scope for the PR for me. I am happy to take on a bug report that formalises all of this in another PR though. (Just can't make promises about a delivery date ;) )

**Comment by grasegger** [comment]
Ok, so I figured out how to place the action in the "default actions after end", but I can't figure out how to load the plugin there ... 

Also that made me painfully aware of the lack of a proper api ... :D But for now it's possible to use it via the popup, maybe I should work on the automatic end stuff in another PR, what do you think?

**Comment by grasegger** [comment]
I didn't mean to take credit for @mwoz123's work, but my rebase knowledge made me somehow coauthor. Hope that's ok.

**Comment by NiLuJe** [comment]
I can whip up the PluginLoader bit if that's the holdup, because I'm extremely not a fan of this approach ;).

**Comment by grasegger** [comment]
> I can whip up the PluginLoader bit if that's the holdup, because I'm extremely not a fan of this approach ;).

That would be fantastic.

**Comment by NiLuJe** [comment]
c.f., https://github.com/koreader/koreader/pull/7607#issuecomment-826986379 for a cleaner way forward.

**Comment by grasegger** [comment]
@NiLuJe Nice! I will open another PR with the things I added on top of that. Thank you so much for you work!!!!

**Comment by sorenpeter** [comment]
Was this ever implemented? I can't seem to find the option to "Move to Archive plugin" for the "end-menu"...

**Pull request closed without merging**
