### PR TITLE
PW5: SwipeAnimations: fix follow link marker

### PR DESCRIPTION
**Pull request by yparitcher**
https://github.com/koreader/koreader/pull/8974#issuecomment-1154563325 and following

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9245)

### CODE REVIEW

**Comment by yparitcher** [comment]
Should be safe to merge before the release.

**Comment by yparitcher** [comment]
for completeness sake. this bug can be triggered without koreader via `fbink -K direction=LEFT,steps=12 -g file=1.png` 
with either of the attached files (black or white). but something like `fbink -K direction=LEFT,steps=12 "|"` does not.

**Review by Frenzie — APPROVED** [review]
@NiLuJe ?

**Comment by NiLuJe** [comment]
Looks fine for now ;). We might want to add a more generic workaround that disables animations for "small" refreshes in the future?

**Comment by yparitcher** [comment]
Proper fix in koreader/koreader-base#1494

The MTK Driver will crash if given a area smaller than the number of steps. If direction is L/R and w is smaller or if it is U/D and h is smaller Being as one generally will only want animations on a larger area, and I am too lazy to test for direction, disable animations when w or h is less than steps.

**Comment by yparitcher** [comment]
BTW the animations work nicely on small areas of text (bigger than `steps`) giving a interesting marquee look ;)

**Pull request closed without merging**
