### PR TITLE
input: drop use of `ffi/input`

### PR DESCRIPTION
**Pull request by benoit-pierre**
In preparation of koreader/koreader-base/pull/1929.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12486)

### CODE REVIEW

**Comment by Frenzie** [comment]
I suppose, but it seems to make the naming less predictable next to isAndroid, isKobo, isKindle, isPocketbook, etc. Presumably your counterargument would be that the equivalent would be something closer to isLinux and isMac. Unless there's another reason?

**Comment by benoit-pierre** [comment]
The main reason is to get rid of the duplication: `haveSDL2` and `isSDL`, keeping only one. We can keep `isSDL` instead, if you prefer.

**Comment by Frenzie** [comment]
Unless there is an underlying reason for `have`, I would indeed prefer `is` for uniformity.

**Comment by benoit-pierre** [comment]
IMHO, `have` is more logical, since a device can have SDL, but not be a SDL device (we don't use it), as evidenced by `noSDL`. But maybe that's what should be changed: the only user of `haveSDL2` is `base/ffi/input.lua`, which does not seem logical, instead of using `device:isSDL()`.

**Comment by Frenzie** [comment]
The underlying purpose of the haveSDL and isSDL distinction was because SDL could be either 1 or 2, so if not haveSDL2 it could still haveSDL1, both resulting in isSDL. Iirc I left this basic construct in place to minimize the diff and because SDL 3 was (and still is) upcoming, but I know leaving scaffolding is something you're never fond of.

In any case, haveSDL but we don't use it strikes me as at least equally useless scaffolding for some undefined future purpose. ;-)

**Comment by benoit-pierre** [comment]
OK, so not a minor cleanup anymore: get rid of the weird interaction between between device implementations, `ffi.util` (`isSDL`, `noSDL`) and the device input code: each device knows if it's using SDL or not, so rely on that to load the right underlying input implementation.

`ffi/input` is gone, so are `isSDL` & `noSDL` in `ffi/util`.

**Review by NiLuJe — COMMENTED** [review]
LGTM (besides that weird SDL leftover that prooobably dates back to SDL 1.x) ;).

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/12486#-:-O7LcCaA4Hh43HXZj08o:bjg9596)* status: all files reviewed, 1 unresolved discussion (waiting on @benoit-pierre, @Frenzie, @pazos, and @poire-z)

___
*[`frontend/device/input.lua` line 231 at r1](https://reviewable.io/reviews/koreader/koreader/12486#-O7LbZPoENAt5zF1mvrq:-O7LbZPoENAt5zF1mvrr:b2z2ub4) ([raw file](https://github.com/koreader/koreader/blob/62d5b71859879a32d01a98e2cf9705610481c04f/frontend/device/input.lua#L231)):*
> ```Lua
>             return self.input.gameControllerRumble(left_intensity, right_intensity, duration)
>         end
>         self.file_chooser = self.input.file_chooser
> ```

This doesn't seem to be used anymore?

(` self.file_chooser = self.input.file_chooser` I mean)

(Ping @Frenzie for 7019ff15bd)

**Comment by benoit-pierre** [comment]
> LGTM (besides that weird SDL leftover that prooobably dates back to SDL 1.x) ;).
> 
> _[`frontend/device/input.lua` line 231 at r1](https://reviewable.io/reviews/koreader/koreader/12486#-O7LbZPoENAt5zF1mvrq:-O7LbZPoENAt5zF1mvrr:b2z2ub4) ([raw file](https://github.com/koreader/koreader/blob/62d5b71859879a32d01a98e2cf9705610481c04f/frontend/device/input.lua#L231)):_
> 
> > ```lua
> >             return self.input.gameControllerRumble(left_intensity, right_intensity, duration)
> >         end
> >         self.file_chooser = self.input.file_chooser
> > ```
> 
> This doesn't seem to be used anymore?
> 
> (`self.file_chooser = self.input.file_chooser` I mean)
> 
> (Ping @Frenzie for [7019ff1](https://github.com/koreader/koreader/commit/7019ff15bd4b36c4f9200dae9b82d98e97e2ed5e))

Since 94c0d7854fb0cc336c18f08e3c3d0a16f485bc0a.

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/12486)* status: all files reviewed, 1 unresolved discussion (waiting on @Frenzie, @pazos, and @poire-z)

___
*[`frontend/device/input.lua` line 231 at r1](https://reviewable.io/reviews/koreader/koreader/12486#-O7LbZPoENAt5zF1mvrq:-O7LhaPHDhut9NR5iStn:b81rzsy) ([raw file](https://github.com/koreader/koreader/blob/62d5b71859879a32d01a98e2cf9705610481c04f/frontend/device/input.lua#L231)):*
<details><summary><i>Previously, benoit-pierre (Benoit Pierre) wrote…</i></summary><blockquote>

Since 94c0d7854fb0cc336c18f08e3c3d0a16f485bc0a.
</blockquote></details>

Then we can probably drop it altogether ;).

**Review by NiLuJe — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/12486)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Frenzie, @pazos, and @poire-z)

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/12486)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Frenzie, @pazos, and @poire-z)

**Review by Frenzie — APPROVED** [review]

**Comment by benoit-pierre** [comment]
Another OCR test failure…

**Comment by NiLuJe** [comment]
Huh. Curious what exactly is upsetting it (I assume that's failing somewhere in stdio-land in tesseract's `LoadDataFromFile` in `src/ccutil/serialis.cpp`...

Should we checksum the downloaded training data to rule that out?

**Comment by benoit-pierre** [comment]
> Huh. Curious what exactly is upsetting it (I assume that's failing somewhere in stdio-land in tesseract's `LoadDataFromFile` in `src/ccutil/serialis.cpp`...
> 
> Should we checksum the downloaded training data to rule that out to begin with?

It [already](https://github.com/koreader/koreader-base/blob/master/Makefile#L150) [is](https://github.com/koreader/.koreader-base/blob/master/Makefile.defs#L272).

**Comment by benoit-pierre** [comment]
Maybe some conditional jump on uninitialized memory. Quite a few errors reported by valgrind.

Bumping libk2pdfopt to get [this fix](https://github.com/koreader/libk2pdfopt/pull/57) will take care of most of them.

There's also this one:
```
[ RUN      ] spec/front/unit/readerhighlight_spec.lua:121: Readerhighlight module highlight for EPUB documents should response on tap gesture
==354150== Conditional jump or move depends on uninitialised value(s)
==354150==    at 0x6FEB06E: ldomXPointer::getRect(lvRect&, bool, bool) const (lvtinydom.cpp:10424)
==354150==    by 0x6FEB2F8: ldomXPointer::toPoint(bool) const (lvtinydom.cpp:9866)
==354150==    by 0x6F240B4: getPosFromXPointer(lua_State*) (cre.cpp:984)
==354150==    by 0x16DCA5: lj_BC_FUNCC (buildvm_x86.dasc:857)
==354150==    by 0x1648E7: lua_pcall (lj_api.c:1151)
==354150==    by 0x1109C4: docall (luajit.c:122)
==354150==    by 0x110FE7: dostring (luajit.c:176)
==354150==    by 0x1115D9: runargs (luajit.c:458)
==354150==    by 0x111898: pmain (luajit.c:546)
==354150==    by 0x16DCA5: lj_BC_FUNCC (buildvm_x86.dasc:857)
==354150==    by 0x164A8B: lua_cpcall (lj_api.c:1179)
==354150==    by 0x111A00: main (luajit.c:581)
==354150==  Uninitialised value was created by a stack allocation
==354150==    at 0x6FE9C3B: ldomXPointer::getRect(lvRect&, bool, bool) const (lvtinydom.cpp:9879)
==354150==
09/22/24-20:52:10 INFO  Preparing to quit UIManager
[       OK ] spec/front/unit/readerhighlight_spec.lua:121: Readerhighlight module highlight for EPUB documents should response on tap gesture (4732.54 ms)
```
@poire-z: ^

**Comment by poire-z** [comment]
Dunno, quickly looking at line 10424 `if ( rect.right <= rect.left )` and what's before it, it feels both right & left end up always initialized.

**Comment by benoit-pierre** [comment]
The default constructor for `lvRect` initialize all the fields to 0, so one of the assignments / calculations must be using something allocated on the stack of that function that is not initialized.

**Comment by poire-z** [comment]
And valgrind can't be more precise and tell us which it is ? 
Because I can't guess looking around.

**Comment by benoit-pierre** [comment]
Looks like I had already [fixed it](https://github.com/benoit-pierre/koreader/commit/2bc09f27814810ccf69e0d064829e8b4ba5e30b0) on my meson branch.

**Comment by benoit-pierre** [comment]
> And valgrind can't be more precise and tell us which it is ? Because I can't guess looking around.

No, the way I go about it is to add some `printf(…)` of the suspects, one value per line, as the printing code will result in conditional jumps that will trigger valgrind. So for example, to first determine which field of the rect is uninitialized:
```c
printf("%d\n", rect.left);
printf("%d\n", rect.right);
if ( rect.right <= rect.left )
    rect.right = rect.left + 1;
```

**Review by NiLuJe — APPROVED** [review]
> Reviewed 14 of 14 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/12486)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pazos and @poire-z)

**Pull request merged**
