### PR TITLE
Update device.lua, to add PB-Verse_(PB629) and PB-Verse Pro_(PB634)

### PR DESCRIPTION
**Pull request by ElimGarak1**
Update device.lua, to add PB-Verse_(PB629) and PB-Verse Pro_(PB634)

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10938)

### CODE REVIEW

**Comment by ElimGarak1** [comment]
Since I currently don't have Basic Lux 4, Verse or Verse Pro, I unfortunately can't test whether KOReader starts on them. So if anyone has one or more of the listed PocketBook devices on hand, it would be helpful to let us know if KOReader supports these devices initially.

**Comment by NiLuJe** [comment]
@gutegeschmack: Thus should be functionally identical to what you did in #10913, so, I'd try again from scratch?

(e.g., with https://github.com/koreader/koreader/raw/fd28f986ddd4a38e586ff372a2d46c71369a1576/frontend/device/pocketbook/device.lua)

**Comment by ElimGarak1** [comment]
> doesn't work on PB629 [crash.log](https://github.com/koreader/koreader/files/12708521/crash.log)
KOReader v2023.06 copied from Era (PB700) to Verse (PB629) and a current device.lua into it. 
This doesn't have to work.

**Review by Frenzie — COMMENTED** [review]
I'm slightly reticent to merge the untested ones. What's the source for the codenames?

**Comment by ElimGarak1** [comment]
> What's the source for the codenames?

https://fccid.io/2AUVWPB618 (Basic Lux 4)
https://fccid.io/2AUVWPB629 (Verse)
https://fccid.io/2AUVWPB634 (Verse Pro)

https://fccid.io/2AUVW

**Comment by Frenzie** [comment]
That's what I was afraid of. :sweat_smile: 

I'm not sure if that kind of thing will match what's in the code, and if it doesn't it'll become confusing if it turns out not to work. Did they change it internally, did it never work, that kind of thing.

So I'd rather limit the PR to just the Verse, unless @rjd22 has a different opinion.

**Comment by rjd22** [comment]
No different opinion. It's a bad idea to merge settings for untested devices. If someone has a device he can request it to be added.

This way we can test with that user what settings are appropriate.

**Comment by ElimGarak1** [comment]
Yes, practice must continually confirm or refute a theory. 

You should wait to add the devices until someone who owns them can validate the corresponding codenames and also confirm that they are running KOReader.

**Comment by Frenzie** [comment]
Could you please adjust the PR so we can merge it? ^_^

**Comment by Sonnenfee** [comment]
Since Friday I'm using a PocketBook Verse Pro (PB634) and added the below already on Friday to the device.lua and KOReader works with it:

}

-- PocketBook Verse Pro (PB634)
local PocketBookPB634 = PocketBook:extend{
model = "PB634",
display_dpi = 300,
isAlwaysPortrait = yes,
usingForcedRotation = landscape_ccw,
hasNaturalLight = yes,
}

elseif codename == "PB634" or codename == "PocketBook 634" then
    return PocketBookPB634

**Comment by Frenzie** [comment]
@Sonnenfee Could you please confirm if it works with only `codename == "PB634"`? And without forced rotation the screen is upside down?

**Comment by Sonnenfee** [comment]
@Frenzie the first one: "Could you please confirm if it works with only codename == "PB634"?" 
I can confirm this works:
elseif codename == "PB634" then
    return PocketBookPB634

**Comment by Sonnenfee** [comment]
@Frenzie the other one "And without forced rotation the screen is upside down?"
I can't confirm. When I start KOReader there is no rotation for the screen necessary and the screen isn't upside down. I don't know if there is maybe a default setting which did the screen forced rotation automatically.
My basic KOReader version is 2023.08 from github.

**Comment by Frenzie** [comment]
> I can't confirm.

So to be clear, you mean that if you remove this line that was in what you pasted everything is still fine? 'cause it's better without if it's not necessary. ;-)
```
usingForcedRotation = landscape_ccw,
```

**Comment by Sonnenfee** [comment]
> So to be clear, you mean that if you remove this line that was in what you pasted everything is still fine? 'cause it's better without if it's not necessary. ;-)
> 
> ```
> usingForcedRotation = landscape_ccw,
> ```

I didn't remove the above line, but I can check it out what will happen, if I do ;-)

**Comment by Sonnenfee** [comment]
The line "usingForcedRotation = landscape_ccw," isn't necessary, it works without the line and everything is still fine right now. 

-- PocketBook Verse Pro (PB634)
local PocketBookPB634 = PocketBook:extend{
model = "PB634",
display_dpi = 300,
isAlwaysPortrait = yes,
hasNaturalLight = yes,
}

**Comment by gutegeschmack** [comment]
> The line "usingForcedRotation = landscape_ccw," isn't necessary, it works without the line and everything is still fine right now.
> 
> -- PocketBook Verse Pro (PB634) local PocketBookPB634 = PocketBook:extend{ model = "PB634", display_dpi = 300, isAlwaysPortrait = yes, hasNaturalLight = yes, }

can confirm for PB629: 

-- PocketBook Verse (PB629)
local PocketBookPB629 = PocketBook:extend{
model = "PB629",
display_dpi = 212,
isAlwaysPortrait = yes,
hasNaturalLight = yes,
}

**Comment by Frenzie** [comment]
@ElimGarak1 Alright, please only remove the PB618 from this PR. 👍

**Comment by ElimGarak1** [comment]
.... done.

**Comment by Frenzie** [comment]
Thanks!

**Comment by ElimGarak1** [comment]
Go to https://github.com/koreader/koreader/pull/10987 to add the new device PB-Basic Lux 4 (PB618).

**Pull request merged**
