### PR TITLE
ci(fix): ignore 631 warnings from luacheck

### PR DESCRIPTION
**Pull request by houqp**

### CODE REVIEW

**Comment by Frenzie** [comment]
Is there a sensible way to combine max line width and translation?

**Comment by houqp** [comment]
Yes, but not directly from luacheck, it needs to be implemented as a custom linter script that we run in our ci builds. It's actually very easy to do since we already have a script that parses all translatable strings out of all lua files: https://github.com/koreader/koreader-misc/blob/master/gettext/lua_xgettext.py.

We can adapt it to do the word count instead of outputting gettext templates. We can also rewrite it using LEPG, which would be faster and easier to maintain.

**Comment by Frenzie** [comment]
> do the word count

I meant that there should be no such restrictions. No need for word count. :-)

**Comment by houqp** [comment]
Oh, haha, sorry I misunderstood your question. In that case, the only easy way I can think of is to use inline annotation to tell luacheck ignore this line.

**Comment by Frenzie** [comment]
An example came by just the other day, btw: https://github.com/koreader/koreader/pull/2603/files#diff-51ff299e54e94be47715def007acd34aR100

**Pull request merged**
