### PR TITLE
Use the appropriate character for the ellipsis

### PR DESCRIPTION
**Pull request by baskerville**

### CODE REVIEW

**Comment by Frenzie** [comment]
I assume you mean guillemet rather than ellipsis?

**Comment by baskerville** [comment]
I meant that we shall use `…`, not `>>` or `»`.

**Comment by Frenzie** [comment]
Could you add before and after screenshots to these kinds of things?

**Comment by baskerville** [comment]
Before:
```
This filename is too long to  >>  13.7 MB
```
After:
```
This filename is too long to fi…  13.7 MB
```

**Comment by Frenzie** [comment]
Fine by me, but I'd make the commit message a bit more descriptive. Something like:

> FileManager: replace arrows by ellipsis to indicate cut-off long filenames

Btw, also see #1147.

Before:
screenshot_2017-02-20_20-43-55

After:
screenshot_2017-02-20_20-44-59

**Comment by houqp** [comment]
Thanks! Squash merged with @Frenzie 's commit message.

**Pull request merged**
