### PR TITLE
[minor] ReaderHighlight: normalize more spelling of PDF

### PR DESCRIPTION
**Pull request by Frenzie**
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12732)

### CODE REVIEW

**Comment by Commodore64user** [comment]
Question: what did I do wrong so that you now get a message about me pushing a commit that references this pull request, and a few other ones? I was trying to merge origin with my local copy of a branch (which apparently were out of sync) and all this came about.

Also, I suppose all these late commits still mean no new stable coming this week, I hope I am wrong. 😑

**Comment by benoit-pierre** [comment]
A stray rebase?

**Comment by Commodore64user** [comment]
> A stray rebase?

Mmm what's a stray rebase? A rebase gone rogue? ;) seriously i tried searching for that and nothing came up

**Comment by benoit-pierre** [comment]
You rebased instead of merging, or rebased too much.

**Pull request merged**
