### PR TITLE
Time reader with normal time format v2

### PR DESCRIPTION
**Pull request by robert00s**
Oh, I completely forgot about it.
Now we have read timer like in #3032.

### CODE REVIEW

**Comment by Frenzie** [comment]
Maybe I'm weird, but I like to use it with values like `5.5` which is something that wouldn't be possible this way.

**Comment by robert00s** [comment]
In this version it is not possible...

**Comment by Frenzie** [comment]
Right, that's what I'm saying. I kind of like the way "minutes from now" works right now. But maybe it's just me. :-)

Pinging @Hzj-jie @Eduardomb22.

**Comment by Eduardomb22** [comment]
I really don´t use time read, so I can´t give a good opinion. However, I think this new version is some kind more useful.

**Comment by embryo10** [comment]
Just a suggestion.
It would be nice if the dialog that is displayed _after_ setting the timer show not only the time the timer is set (we saw that in the timer dialog already) but the HH:MM from now till then.

**Comment by embryo10** [comment]
Never mind.
Just noticed that this info exist in the menu...

**Pull request merged**
