### PR TITLE
bump android-luajit-launcher

### PR DESCRIPTION
**Pull request by pazos**
Related to https://github.com/koreader/koreader/issues/8482

Changes:

- New light driver for Onyx devices that should work on modern ones. Thanks to @bb010g!
- Onyx Nova 2 migrated to the new driver.

Added devices:

- iReader r6800
- Onyx Magicbook
- Onyx Note Air 2
- Onyx Nova Air C
- Sony DPT-CP1

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9290)

### CODE REVIEW

**Comment by liujixu1984** [comment]
There are devices added here. Do you need to wait until the next software version is updated?

**Comment by mergen3107** [comment]
@liujixu1984 
Wait one day and then update to current nightly

**Comment by pazos** [comment]
It is already available in http://build.koreader.rocks/download/nightly/?C=M&O=D

**Comment by liujixu1984** [comment]
> It is already available in http://build.koreader.rocks/download/nightly/?C=M&O=D


I have updated to this version. koreader-android-arm-v2022.06-14-g05c586c4_2022-07-04.apk There is also a full refresh option in the settings, but it does not take effect. There is no response to using gestures to completely refresh. After entering the test program, click the button, and the screen will still flash and refresh

**Comment by liujixu1984** [comment]
> @liujixu1984: there's nothing we can do here.
> 
> The test activity uses an android view hierarchy and, even when we actually call proper device methods, simulating a refresh is just a matter of calling on the view.`invalidate`
> 
> The KO activity is native and by default doesn't belong to a view hierarchy. We do hook in one if the epd driver needs a view to work:
> 
> https://github.com/koreader/android-luajit-launcher/blob/760f2ca442e135f3244e38a17f123480b396cde6/app/src/main/java/org/koreader/launcher/MainActivity.kt#L115-L123
> 
> That's all we can do: the Nook driver requires a view, we create one and request the refreshes. If they don't happen I'm afraid there's nothing we can do without the device in hand.
> 
> Feel free to open a ticket in https://github.com/koreader/android-luajit-launcher if you want to investigate yourself and need some hints in the process.
> 
> It will probably require a new driver.

ok thanks!

**Pull request merged**
