### PR TITLE
Version log and (limited) infomessage log

### PR DESCRIPTION
**Pull request by zwim**
Follow up to: #10128

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10160)

### CODE REVIEW

**Comment by zwim** [comment]
Ups. Was not wanted.

**Review by NiLuJe — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/10160)* status: all files reviewed, 5 unresolved discussions (waiting on @zwim)

___
*[`frontend/logfile.lua` line 21 at r1](https://reviewable.io/reviews/koreader/koreader/10160#-NPYK27I0e9QpU7_1q6E:-NPYK27I0e9QpU7_1q6F:bmifg3u) ([raw file](https://github.com/koreader/koreader/blob/bb7bace6adace3f3320aeeb537f53c85e712adad/frontend/logfile.lua#L21)):*
> ```Lua
>             table.insert(log_lines, next_line)
>             next_line = log_file:read("*line")
>         end
> ```

there's a `lines()` iterator function that'll do that for you, no need to reinvent the wheel ;).

Something along the lines (ha!) of `for line in log_file:lines() do`...



_Code quote:_
```Lua
        local next_line = log_file:read("*line")
        while next_line do
            table.insert(log_lines, next_line)
            next_line = log_file:read("*line")
        end
```
___
*[`frontend/logfile.lua` line 33 at r1](https://reviewable.io/reviews/koreader/koreader/10160#-NPYKVIk5qyrs-uiA-9E:-NPYKVIk5qyrs-uiA-9F:bkj2wqq) ([raw file](https://github.com/koreader/koreader/blob/bb7bace6adace3f3320aeeb537f53c85e712adad/frontend/logfile.lua#L33)):*
> ```Lua
>             for i = #log_lines - max_nb_log_lines + 1, #log_lines do
>                 new_file:write(log_lines[i], "\n")
>             end
> ```

You can also do something like `log_lines[max_nb_log_lines + 1] = nil`, then just a single `new_file:write(table.concat(log_lines, "\n"))` call ;).

EDIT: Err, nope, that would truncate from the head, you want to start at the tail, never mind me ;o).



_Code quote:_
```Lua
            for i = #log_lines - max_nb_log_lines + 1, #log_lines do
                new_file:write(log_lines[i], "\n")
            end
```
___
*[`frontend/logfile.lua` line 52 at r1](https://reviewable.io/reviews/koreader/koreader/10160#-NPYJ4JD0yKRM3aTQ7f_:-NPYJ4JD0yKRM3aTQ7fa:b28x99k) ([raw file](https://github.com/koreader/koreader/blob/bb7bace6adace3f3320aeeb537f53c85e712adad/frontend/logfile.lua#L52)):*
> ```Lua
> function LogFile:append(path, text, max_nb_log_lines)
>     max_nb_log_lines = max_nb_log_lines or math.huge
>     if not self.log_files or not self.log_files[path] or self.log_files[path] > max_nb_log_lines then
> ```

The first nil guard is superfluous, `self.log_files` a module locale, it'll always be there.
___
*[`frontend/logfile.lua` line 63 at r1](https://reviewable.io/reviews/koreader/koreader/10160#-NPYJsTqCD4qfo8A2fWC:-NPYJsTr22k4jJmN7lv8:b-dp8lmz) ([raw file](https://github.com/koreader/koreader/blob/bb7bace6adace3f3320aeeb537f53c85e712adad/frontend/logfile.lua#L63)):*
> ```Lua
>     log_file:close()
> 
>     local _, nb_new_lines = text:gsub("\n","")
> ```

nit: space after comma is the `gsub` call
___
*[`frontend/ui/elements/screen_notification_menu_table.lua` line 83 at r1](https://reviewable.io/reviews/koreader/koreader/10160#-NPYLUtk3I6gvmNc_zPm:-NPYLUtk3I6gvmNc_zPn:bliboih) ([raw file](https://github.com/koreader/koreader/blob/bb7bace6adace3f3320aeeb537f53c85e712adad/frontend/ui/elements/screen_notification_menu_table.lua#L83)):*
> ```Lua
>         {
>             text = _("Show past notifications"),
>             help_text = _("Show the text of past Notifications."),
> ```

nit!: I can't remember if we usually end `help_text` strings with a period?

**Review by zwim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/10160)* status: all files reviewed, 5 unresolved discussions (waiting on @NiLuJe)

___
*[`frontend/logfile.lua` line 21 at r1](https://reviewable.io/reviews/koreader/koreader/10160#-NPYK27I0e9QpU7_1q6E:-NPcu9AZ58o-1HMdD5Wr:b-8fx2u7) ([raw file](https://github.com/koreader/koreader/blob/bb7bace6adace3f3320aeeb537f53c85e712adad/frontend/logfile.lua#L21)):*
<details><summary><i>Previously, NiLuJe (NiLuJe) wrote…</i></summary><blockquote>

there's a `lines()` iterator function that'll do that for you, no need to reinvent the wheel ;).

Something along the lines (ha!) of `for line in log_file:lines() do`...
</blockquote></details>

:+1: 
___
*[`frontend/logfile.lua` line 52 at r1](https://reviewable.io/reviews/koreader/koreader/10160#-NPYJ4JD0yKRM3aTQ7f_:-NPcuEwD11kz6mUO_0le:b-8fx2u7) ([raw file](https://github.com/koreader/koreader/blob/bb7bace6adace3f3320aeeb537f53c85e712adad/frontend/logfile.lua#L52)):*
<details><summary><i>Previously, NiLuJe (NiLuJe) wrote…</i></summary><blockquote>

The first nil guard is superfluous, `self.log_files` a module locale, it'll always be there.
</blockquote></details>

:+1: 
___
*[`frontend/logfile.lua` line 63 at r1](https://reviewable.io/reviews/koreader/koreader/10160#-NPYJsTqCD4qfo8A2fWC:-NPcuIIu4Va0C0GDz5v2:b-8fx2u7) ([raw file](https://github.com/koreader/koreader/blob/bb7bace6adace3f3320aeeb537f53c85e712adad/frontend/logfile.lua#L63)):*
<details><summary><i>Previously, NiLuJe (NiLuJe) wrote…</i></summary><blockquote>

nit: space after comma is the `gsub` call
</blockquote></details>

:+1: 
___
*[`frontend/ui/elements/screen_notification_menu_table.lua` line 83 at r1](https://reviewable.io/reviews/koreader/koreader/10160#-NPYLUtk3I6gvmNc_zPm:-NPcu_9L4NNUazrgYHhB:bhkfa13) ([raw file](https://github.com/koreader/koreader/blob/bb7bace6adace3f3320aeeb537f53c85e712adad/frontend/ui/elements/screen_notification_menu_table.lua#L83)):*
<details><summary><i>Previously, NiLuJe (NiLuJe) wrote…</i></summary><blockquote>

nit!: I can't remember if we usually end `help_text` strings with a period?
</blockquote></details>

A quick `grep -R help_text frontend` shows, that all `help_text` messages have a period at the end.  (IMHO a sentence should end with a period.)

**Comment by zwim** [comment]
I have a problem with pushing commits to this PR (as I have accidentally deleted the fork).
Is there an (easy) gh solution to do this, or shall I open a new PR.

**Comment by Frenzie** [comment]
What if you create a new branch with the same name? (Keeping a backup too just in case)

**Comment by zwim** [comment]
I have tried this now and voila :-( we have two similar PR now.
I think it might be best to close the older one and put a reference in the older one to the new one.

**Comment by zwim** [comment]
Please excuse the inconvenience.

**Pull request closed without merging**
