### PR TITLE
Fix some characters in el_popup.lua

### PR DESCRIPTION
**Pull request by jimman2003**
Doing a favour to @ichnilatis-gr
P.S there is a contribute button on the top of a branch that deviates from master

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7930)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by poire-z** [comment]
> Doing a favour to @ichnilatis-gr

_give a man a fish and you feed him for a day; teach a man to fish and you feed him for a lifetime_ :)

**Comment by jimman2003** [comment]
Doesn't have to be one of the two :)

**Comment by Frenzie** [comment]
Phish Request?

**Comment by ichnilatis-gr** [comment]
> 
> 
> > Doing a favour to @ichnilatis-gr
> 
> _give a man a fish and you feed him for a day; teach a man to fish and you feed him for a lifetime_ :)

I learn slowly... Unfortunately, I do not have enough time to deal with github. And it seems so complicated to me... 😃 
Thanks to all of you

**Pull request merged**
