### PR TITLE
Bookmarks dogear: fix position with CRe top status bar

### PR DESCRIPTION
**Pull request by poire-z**
Draw it below the CRe top status bar rather than over it.
It is ugly on the screenshot of first post of #7311. Should look better this way:

image

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7312)

### CODE REVIEW

**Comment by hius07** [comment]
I do not use alt status bar, just a couple of screenshots taken after changing alt status bar font size.
After reloading the book all looks well.

**Comment by poire-z** [comment]
@zwim: mentionning this as a bit related to your #8501 : 
This one is actually a case of the rendering being done outside of where we want it to happen (ReaderRolling:onUpdatePos()) - actually, that's my (wrong, too quick) doing :) https://github.com/koreader/koreader/commit/062bb6833
```
12/05/21-12:02:17 DEBUG adjusted ges: tap
12/05/21-12:02:17 DEBUG AutoTurn: onInputEvent
12/05/21-12:02:17 DEBUG update battery state
12/05/21-12:02:17 DEBUG CreDocument: set battery state 0
12/05/21-12:02:17 DEBUG ReaderCoptListener.headerRefresh rescheduled
12/05/21-12:02:17 DEBUG setDirty via a func from widget table: 0x7f59ac4239c0
12/05/21-12:02:17 DEBUG _refresh: Enqueued ui update for region 0 0 600 610
12/05/21-12:02:17 DEBUG setDirty ui from widget ReaderUI w/ NO region
12/05/21-12:02:17 DEBUG setDirty via a func from widget table: 0x7f59a3cea488
12/05/21-12:02:17 DEBUG setDirty via a func from widget table: 0x7f59a3cea488
12/05/21-12:02:17 DEBUG painting widget: ReaderUI
12/05/21-12:02:17 DEBUG CreDocument: goto page 120 flow 0
   rendering happening
12/05/21-12:02:19 DEBUG refresh on physical rectangle 0 36 200 7
[...]
12/05/21-12:02:27 DEBUG refresh on physical rectangle 0 36 200 7
12/05/21-12:02:27 DEBUG painting widget: table: 0x7f59a3cbc6d8
12/05/21-12:02:27 DEBUG _refresh: Enqueued ui update for region 0 0 600 610
12/05/21-12:02:27 DEBUG _refresh: Enqueued ui update for region 0 0 600 610
12/05/21-12:02:27 DEBUG _refresh: Enqueued ui update for region 0 0 600 610
12/05/21-12:02:27 DEBUG refresh on physical rectangle 0 0 600 610
```

When toggling alt status bar, we get the more correct flow of action:
```
12/05/21-11:59:54 DEBUG CreDocument: set status line property 1
12/05/21-11:59:54 WARN  ReaderDogear:onUpdatePos
12/05/21-11:59:54 WARN  ReaderRolling:onUpdatePos
  rendering happening via getCurrentPos()
12/05/21-11:59:56 DEBUG refresh on physical rectangle 0 36 200 7
CRE WARNING: table rows/thead/tfoot re-ordered
12/05/21-12:00:04 DEBUG refresh on physical rectangle 0 36 200 7
12/05/21-12:00:04 WARN  ReaderRolling:onUpdatePos getCurrentPos() done
  more stuff happening after rendering:
12/05/21-12:00:04 DEBUG rendering hash changed: 24704122 > 351159547
12/05/21-12:00:04 DEBUG CreDocument: goto page 112 flow 0
12/05/21-12:00:04 DEBUG _refresh: Enqueued partial update for region 0 0 600 610
12/05/21-12:00:04 DEBUG setDirty partial from widget ReaderUI w/ NO region
12/05/21-12:00:04 DEBUG validateAndFixToc(): quick scan
12/05/21-12:00:04 DEBUG validateAndFixToc(): TOC is fine
12/05/21-12:00:04 DEBUG ReaderStatistics: Pagecount change, flushing volatile book statistics
12/05/21-12:00:04 DEBUG _refresh: downgraded regional partial refresh to ui
12/05/21-12:00:04 DEBUG _refresh: Enqueued ui update for region 0 0 600 610
12/05/21-12:00:04 DEBUG setDirty partial from widget ReaderUI w/ NO region
12/05/21-12:00:04 WARN  ReaderRolling:onUpdatePos done
  all done
```
Just replacing this actually does _not_ solve the issue :/
```diff
--- a/frontend/apps/reader/modules/readercoptlistener.lua
+++ b/frontend/apps/reader/modules/readercoptlistener.lua
@@ -341,8 +341,9 @@ function ReaderCoptListener:getAltStatusBarMenu()
                             -- we keep open, no need to handle this case.
                             self:setAndSave("cre_header_status_font_size", "crengine.page.header.font.size", spin.value)
                             if touchmenu_instance then touchmenu_instance:updateItems() end
+                            self.ui:handleEvent(Event:new("UpdatePos"))
                             -- Repaint the whole page, as changing this should cause a re-rendering
-                            UIManager:setDirty(self.view.dialog, "ui")
+                            -- UIManager:setDirty(self.view.dialog, "ui")
                         end
                     }
                     UIManager:show(size_spinner)
```
I'm continuing investigating and trying to understand what is and what should be happening.

**Comment by poire-z** [comment]
Took a few hours trying to understand what was happening.
I think it was a crengine issue: after setting status bar font size (or font face), the font itself wasn't updated straight away, so there was a small time window (during which I issue UpdatePos above) where it wasn't updated and no re-rendering felt needed. 
And it was actually in our drawCurrentPage() call from frontend, that call Render() which does some re-check if rendering is needed) where the font object is updated and so, the re-rendering was actually happening when we were painting the page.
And so, the dogear never gets the current header height.

This, with the above "naive" patch to plug in a `self.ui:handleEvent(Event:new("UpdatePos"))` where we feel a re-rendering might be happening, seems to solve the issue:
```diff
 void LVDocView::setStatusFontSize(int newSize) {
        LVLock lock(getMutex());
        int oldSize = m_status_font_size;
        m_status_font_size = newSize;
        if (oldSize != newSize) {
                propsGetCurrent()->setInt(PROP_STATUS_FONT_SIZE, m_status_font_size);
+               m_infoFont = fontMan->GetFont(m_status_font_size, 400, false,
+                       DEFAULT_FONT_FAMILY, m_statusFontFace);
         REQUEST_RENDER("setStatusFontSize")
        }
        //goToBookmark(_posBookmark);
 }
 void LVDocView::setStatusFontFace(const lString8 & newFace) {
        m_statusFontFace = newFace;
+       m_infoFont = fontMan->GetFont(m_status_font_size, 400, false,
+                       DEFAULT_FONT_FAMILY, m_statusFontFace);
     REQUEST_RENDER("setStatusFontFace")
 }
```

There is still a minor thing: the cre re-rendering progress bar is drawn at the "new" height position (the same we want the futur dog ear to be positionnned), while it's still the old page (with the old header height) that is displayed.
@zwim: it feels we had dicussed this at the time you make font size update to the alt status bar.
Ok, found it, in #7667. This was using the old/not-updated header height, and is not longer working now that we update the header height earlier. So, it will need some tweaks too...
(Somehow, I see the cre progress bar is not render at the right position already with v2021.09 appimage...)

**Comment by poire-z** [comment]
> There is still a minor thing: the cre re-rendering progress bar is drawn at the "new" height position (the same we want the futur dog ear to be positionnned), while it's still the old page (with the old header height) that is displayed.

Somehow, I can't reprocuce this. So, I guess it was caused by the various debugging crap I had at the time of trying to understand.
The only changed need on frontend side should be:
```diff
--- a/frontend/apps/reader/modules/readercoptlistener.lua
+++ b/frontend/apps/reader/modules/readercoptlistener.lua
@@ -340,9 +340,8 @@ function ReaderCoptListener:getAltStatusBarMenu()
                             -- still displayed. But as all this is covered by this menu that
                             -- we keep open, no need to handle this case.
                             self:setAndSave("cre_header_status_font_size", "crengine.page.header.font.size", spin.value)
+                            self.ui:handleEvent(Event:new("UpdatePos")) -- this change should need a re-rendering
                             if touchmenu_instance then touchmenu_instance:updateItems() end
-                            -- Repaint the whole page, as changing this should cause a re-rendering
-                            UIManager:setDirty(self.view.dialog, "ui")
                         end
                     }
                     UIManager:show(size_spinner)
```

**Pull request merged**
