### PR TITLE
FileChooser: Sort by date

### PR DESCRIPTION
**Pull request by hius07**
As discussed, "access" and "change" dates are useless.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10627)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Review by poire-z — APPROVED** [review]

**Review by NiLuJe — APPROVED** [review]

**Comment by snelg** [comment]
`access` ("last read date") is NOT useless, and is in fact the one that I use. Every time I open a file, its `access` date is updated, but `modified` is not. I *want* the most recently opened file to appear at the top of the list.
I'll make a new PR myself, but I just wanted this notification here so there's not a question of why I'm partially undo-ing this PR.

**Comment by NiLuJe** [comment]
On which platform? (atime being left alone is *extremely* common).

**Comment by snelg** [comment]
Tried on Kobo Elipsa, Kobo Forma, Remarkable 2, and Ubuntu Desktop.

  1. Sort by "date modified" (since "last date read" is now gone)
  2. Open any file that's not the first one on the list (and maybe even flip through a few pages...)
  3. Return to the file browser
  4. The file does *not* move to the top of the file list, but remains in the same position in the list
 
On all those platforms (i.e. all the ones I have conveniently available), with the now-missing "last date read" sort option, at step 4 the file would jump to the top of the list, which is the behavior I want.

**Comment by poire-z** [comment]
> On which platform (and filesystem, and mount options)? (atime being left alone is extremely common).

We explicitely set atime (via `lfs.touch()`) when we open a file:
https://github.com/koreader/koreader/blob/e1ed3a71c5d1a25d5868f0ed89d3e1a42ce7c9ec/frontend/readhistory.lua#L253-L263
so, we somehow make us have a valid atime on all platforms (?).

Forgot about that when we removed other "time" sortings :/
(I just noticed that behaviour a few days ago when vim was too often complaining when I edited and saved a test.html file after open/quit in KOReader with: `WARNING: The file has been changed since reading it` - setting "access time" also updates "change time", but not "modified time" - dunno if vim behaviour on that has changed between debian 11 and 12, as I didn't get that the past years.)

**Comment by NiLuJe** [comment]
> Forgot about that when we removed other "time" sortings :/

Yup, we all did back when we discussed the thing and we all went "oh, yeah, atimes are useless" ;D.

**Pull request merged**
