### PR TITLE
Kobo Aura ONE: no viewport adjustments needed

### LINKED ISSUE #2372: The Viewport of the Kobo Aura ONE is wrong
A test image can be created with:
```
convert -size 1404x1872 canvas:black black.png
```

You'll notice the white borders present around the image within *koreader*.

### PR DESCRIPTION
**Pull request by baskerville**
Test image:
https://cloud.githubusercontent.com/assets/159419/20651651/5e344d1c-b4e9-11e6-8450-6fb165c792db.png

Fixes #2372.

### CODE REVIEW

**Comment by Frenzie** [comment]
I note that in #2251 @MMihelic stated the viewport definition may not be 100% correct, although I'm confused why it was added in the first place if it wasn't necessary at all. :-)

**Comment by baskerville** [comment]
In #2235, @MMihelic solved a touch issue with `touch_probe_ev_epoch_time = true`, he initially thought it had something to do with the view port… and forgot to re-evaluate its assumption.

**Comment by MMihelic** [comment]
Good morning.

At the moment, I am unable to make a test on my device so all I can put down is what I can recollect. Someone suggested enabling the night mode on a test image to see if the entire viewport is covered - there should be no bright line on the sides of the image. From what I recollect I had a bright line at the border, so I decreased a bit the viewport to make it disappear. The truth is that I wasn't sure that this made any sense at all, hence my note about it.

@Frenzie: Perhaps you could repeat the same test, enabling the night mode, with your test image? If the inverted image displays fully and with no bright lines, then that it ;).

Regards, Matej.

**Comment by Frenzie** [comment]
Unfortunately I don't have that device or I'd take a look for myself. :-)

**Comment by baskerville** [comment]
Well I've made some tests before submitting the pull request…

And the steps to reproduce the problem are given in #2372!

**Comment by Frenzie** [comment]
I know, I know! ;-)

**Pull request merged**
