### PR TITLE
Kobo: Don't leak fds in isWifiOn

### PR DESCRIPTION
**Pull request by NiLuJe**
io.lines only closes the fd when the loop is exited sanely, not by a control flow keyword (i.e., no break or return allowed).

Regression since #8169

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8261)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Huh, I figured it would be closed in that scenario.

**Comment by poire-z** [comment]
(too lazy to go search for it in the docs...) what's the "e" in "re" and "we" ?

**Comment by NiLuJe** [comment]
> Huh, I figured it would be closed in that scenario.

It's *possible* it's left to the GC in this instance, but even if that's the case, it's less than ideal ;).

**Comment by NiLuJe** [comment]
> (too lazy to go search for it in the docs...) what's the "e" in "re" and "we" ?

It's `CLOEXEC` ;). Not in the Lua docs, though, check `man fopen` ;).

**Comment by Frenzie** [comment]
> It's possible it's left to the GC in this instance, but even if that's the case, it's less than ideal ;).

Quite true.

**Pull request merged**
