### PR TITLE
[fix] Empty directory path and crash on TextWidget

### PR DESCRIPTION
**Pull request by robert00s**
PR fix prevent empty path in filemanager.

obraz

Step to reproduce:
1. Create two folders:
+ /home/koreader/test
+ /home/koreader/test1
2. Set folder `/home/koreader/test` as home folder in KO
3. Set option `Shorten home directory` (Other settings -> Shorten home directory)
4. Go to folder in fm to `/home/koreader/test1`

### CODE REVIEW

**Comment by poire-z** [comment]
@robert00s just a quick note. We added something this weekend https://github.com/koreader/koreader/pull/5598#discussion_r346903243 - so TextWidget will crash (on the emulator only) when it doesn't get a string for `text =` - a number for example.
I pinpoint up to now a single place that needs a fix:
```diff
--- a/frontend/ui/widget/bookstatuswidget.lua
+++ b/frontend/ui/widget/bookstatuswidget.lua
@@ -138,5 +138,5 @@ end
 function BookStatusWidget:getStatDays()
     if stats_book.days then
-        return stats_book.days
+        return tostring(stats_book.days)
     else
         return _("N/A")
```
(feel free to add this quick one to this PR).
There's much of your code/widgets that I don't usually visit (but Reading statictics seems ok), so, if you can have a quick check that nothing else crashes, that'd be nice :)

**Comment by robert00s** [comment]
@poire-z 
I also notice a few minutes ago a problem with BookStatusWidget. I'll add your patch soon.
I have a quick check too.

**Comment by robert00s** [comment]
Ok, I found crash on ReadingProgress. PR soon.

**Comment by poire-z** [comment]
(Just pointing another one I found - not opening another PR, if you can add it here, hope that's ok :)
```diff
--- a/frontend/apps/reader/skimtowidget.lua
+++ b/frontend/apps/reader/skimtowidget.lua
@@ -187,3 +187,3 @@ function SkimToWidget:init()
     self.current_page_text = Button:new{
-        text = self.curr_page,
+        text = tostring(self.curr_page),
         bordersize = 0,
```

**Comment by poire-z** [comment]
Thanks, and sorry, another one in that same file:
```diff
--- a/frontend/apps/reader/skimtowidget.lua
+++ b/frontend/apps/reader/skimtowidget.lua
@@ -367,3 +367,3 @@ function SkimToWidget:update()
     self.progress_bar.percentage = self.curr_page / self.page_count
-    self.current_page_text:setText(self.curr_page, self.current_page_text.width)
+    self.current_page_text:setText(tostring(self.curr_page), self.current_page_text.width)
 end
```

**Comment by robert00s** [comment]
No problem :)

**Pull request merged**
