### PR TITLE
fix keyvaluepage to truncate long text

### PR DESCRIPTION
**Pull request by houqp**
Thanks for @apletnev 's bug report.

### CODE REVIEW

**Comment by houqp** [comment]
BTW, anyone who likes HTML/CSS/JS and wants to help build KOReader's landing page, please feel free to send PR to https://github.com/koreader/koreader.github.io. I have other higher priority tasks at hand, so not likely to have time to work on it soon.

**Comment by Frenzie** [comment]
I'll work on it.

**Comment by houqp** [comment]
@Frenzie Thanks for offering the help!

BTW, can someone merge https://github.com/koreader/koreader-base/pull/378 too? This PR actually relies on that one ;)

**Comment by poire-z** [comment]
There was some code added in this PR for truncation and adding an ellipsis, that has later been moved into rendertext by #2322. 
The code from here, and also where it ends, adds a space after the ellipsis (if we don't specify `prepend_space=true`) - which in some context might feel unwelcome (when aligning the truncated text to the right).
Is there any typographic reason to add a space after an ellipsis? Or should we get rid of this idea of prepending or appending a space in this RenderText:truncateTextByWidth - and have the caller sites do that if they really need it?

(Currently trying to cleanup in various widgets some sizeUtf8  > truncateUtf8 > textwidget as textwidget as a max_width parameter that will have it just do that - and I'm stumbling on having it right in KeyValuePage :)

**Pull request merged**
