### PR TITLE
[RFC] Switch ConfigDialog's rotation toggle to custom icons

### PR DESCRIPTION
**Pull request by NiLuJe**
As discussed previously in... a few places, most recently #7304

----

I'm not entirely happy with the UR/UD icons, but I don't really know how to make it any better/clearer?
Stick a 'K' inside the screen, maybe?

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7306)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Before:

arrows

After:

icons2

**Comment by poire-z** [comment]
Feels a lot better.
Curious to see how it would look with a `Ko` written inside.

(But it will feel odd on a PC screen or on an Android TV :)

**Comment by NiLuJe** [comment]
The two options for a letter inside (with a minor preference for the second, which is reminiscent of how the (old, old) Kindle UI did it:

icons_k

icons_k2

**Comment by NiLuJe** [comment]
With a few graphical snafus fixed:

icons_k3

**Comment by hius07** [comment]
The second picture (without k) is absolutely Okay.
The icon shows how should I hold the device to read the text.
Icons with k inside are confusing.

**Comment by NiLuJe** [comment]
@hius07: I'd tend to agree. It's prettier, but potentially confusing.

**Comment by hius07** [comment]
Menu item might be changed to `Orientation` (as in Kindle)

**Comment by NiLuJe** [comment]
I'm not entirely opposed to it for the user-facing boot of UI, but the code
makes a distinction between orientation and rotation: orientation for
portrait/landscape (inverted or not), and rotation for the four possible
rota.

A strong contender for keeping that distinction is the "lock gyro rotation
to current orientation" option, for instance.

**Comment by poire-z** [comment]
> with a minor preference for the second, which is reminiscent of how the (old, old) Kindle UI did it 

I don't get at all the second one (k not rotating inside the device, following the device): it just means to me nothing on screen is rotating :) you're just yourself rotating the device:
image

----

The "k always being horizontal" (first picture) is a good indicator of how the image will be on the screen after - and may help people who have a different way to think about that:
image

----

Without the "k" is fine too, you get an idea of the text/menu orientation with the surrounding menu itself - but may be the "k" makes the mind gymnastic easier.
image

**Comment by Frenzie** [comment]
> a lowercase o is completely useless in this context, because it looks the same no matter which way you look at it ^^

In most typefaces it's slightly taller than it is wide. /nit

Wrt orientation vs rotation, note that the string `Orientation` is currently not translated and they're basically synonyms.

I prefer the cleaner look without the k.

**Comment by hius07** [comment]
> they're basically synonyms

Okay, I'd say, Rotation is an action, Orientation is a pose.
Since we have arrows in the icons, Rotation is better.
Kindle icons show just a screen (device) pose, so it is Orientation.

**Comment by poire-z** [comment]
> Rotation is an action, Orientation is a pose.
Since we have arrows in the icons, Rotation is better.

That's the main issue, for me: using/expressing actions: it works only in initial portrait mode.

Once you have it rotated 90°:
image
To get back to "normal" mode, you'll hit the button in yellow - which does not indicate an action (or the action to move your device up :) - while the landscape icons indeed show an action.

Showing a state/pose (the current, or the future one) would be the least confusing solution, if we can find one :)

Note that these icons work for a device - but not at all with a PC screen - and for the one with the "k" not always being horizontal, it's actually the reverse of what will happen:
<kbd>image</kbd> would have highlighted: image

**Comment by NiLuJe** [comment]
Can't have context-aware icons in ConfigDialog, AFAIK?

(And, admittedly, having the icons magically move around/change depending on the current orientation might be *moire* confusing?)

**Comment by poire-z** [comment]
> Can't have context-aware icons in ConfigDialog, AFAIK?

Depends on the context:
Static device type: use `item_icons = Device:isHandheld() and { first set } or {second set}`
Dynamic like orientation/rotation: wouldn't be too hard to implement `items_icons_func` :)

I'm fine with your current state of icons (with or without the "k"), showing a device: it's clear enough with the thicker device bottom - for PC and TVs, I guess people don't need this toggle as much as we do on devices, so it's ok if it's a bit less clear.

**Comment by NiLuJe** [comment]
Okay, so, settling on the letter-less variant for now, with a few minor grid-fitting tweaks since the original version:

icons_k6

**Comment by poire-z** [comment]
For the portrait icon, the device being not centered on the underline feels a bit odd :) May be the device frame should be centered in the icon (doesn't matter if there's a big blank area on its left in the icon, and the arrow is near the right)?

image

**Comment by NiLuJe** [comment]
icons_k7

(The Landscape ones were already horizontally centered).

**Pull request merged**
