### PR TITLE
do not link cache dir as it may already exist

### PR DESCRIPTION
**Pull request by yparitcher**
closes koreader/koreader#6357

thanks @Frenzie

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/6358)

### CODE REVIEW

**Comment by yparitcher** [comment]
it passes the tests locally, 
as usual i cant see the circleci logs so i cant know exactly what broke, but i wonder if it is caused by the ci cacheing the builds?

**Comment by Frenzie** [comment]
@yparitcher `base` is cached so it doesn't have to do the full 15-minute build for every PR, but that's prior to running tests for basically exactly that reason.

**Comment by yparitcher** [comment]
I figured it out.
[!cache] matches `c` or `a` or `h` or `e` as the first letter not `cache` as a word. there is no way is sh to not match a word and `[!c]*` as you suggested would also match clipboard & common :(

**Comment by Frenzie** [comment]
@yparitcher I believe that in Bash you can do `!(cache)` although depending on Bash is potentially problematic. Pinging @NiLuJe who knows more about various shells.

**Comment by NiLuJe** [comment]
We could *probably* enforce using Bash, but it's mildly annoying in Make (it involves pointing SHELL to the right place, IIRC?).

**Comment by NiLuJe** [comment]
Barring that, moving away from shell globs to a filtered find might do the trick?

**Comment by Frenzie** [comment]
Or just `bash -c` in that case? It's only one line.

**Comment by yparitcher** [comment]
fixed

**Pull request merged**
