### PR TITLE
Various minor tweaks and fixes (ToC, Search, HttpInspector)

### LINKED ISSUE #11674: Incorrect chapter shown in status bar
* KOReader version: 2024.03.1-55 (Kobo) and ..1-62 (Android)
* Device: Kobo/Android

#### Issue

When located on a page before the TOC chapters begin, the status bar will  already show the name of the first chapter. Correct would be an empty field.

**Location in Book map:**

image

**Incorrect chapter name in status bar:**

image

I am quite sure this must be due to a recent change, as I have never seen this happen before.

Thank you all for your help and dedication.

### PR DESCRIPTION
**Pull request by poire-z**
#### HttpInspector: allow browsing global variables

I felt the need for that when working on https://github.com/koreader/koreader-base/pull/1766.

#### ReaderStyleTweak: reword CSS suggestions info text

Argued at https://github.com/koreader/koreader/pull/11533#issuecomment-2041526924 and follow ups.

#### ReaderToc: fix issues when on a page before first Toc Item

When on a page before the first ToC item (the first chapter), that first chapter title may be shown in the footer instead of a more correct blank title.
This bug might still have had other small effect elsewhere.
Closes #11674.

#### Statistics: handle correctly page change when reading paused

As currently we only handle ReadingPaused/Resumed on suspend and resume, no page change should happen while paused, so there is no current issue to fix. But let's get ready for other use cases (which may be brought in by user patches, ie. pausing while the SkimWidget is displayed, and obviously triggers page changes).
See https://github.com/koreader/koreader/issues/11486#issuecomment-2046980127.

#### ReaderSearch: delay adding to location stack until we change page

Search may highlight matches on the current page, and if there are no others in the book, we would stay there and resume reading; but we would get a spurious previous location (ie. in Book map) that we would not expect keeping, and we may accidently go back to previous location, losing our reading position.
Avoid this by only adding current page to location stack when actually leaving the current page.
Because of complications with other reading modes, this is currently only enabled for CRE document when in page mode.
Discussed at https://github.com/koreader/koreader/issues/11203#issuecomment-2002559300, thought it may feel a bit inconsistent, but feedback at https://github.com/koreader/koreader/issues/11203#issuecomment-2042886575 and my use case welcomes it. We'll see.

(Still very busy with other things, just offloading stuff I had waiting for weeks, hard to get back into it, I hope I'm not messing up too much :/)

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11746)

### CODE REVIEW

**Comment by poire-z** [comment]
Any idea why CI is not using any cache, and rebuilding the world ?
Something with the recent CI tweaks ? Or just some random bad luck ?
Or CI on master branch for yesterdays's merged commits has its own cache - and proposed PRs have a different one and don't reuse the master main one - and this is the first PR proposed after some base bumps ?
@benoit-pierre ?

**Comment by Frenzie** [comment]
It should just be bad luck causing some mismatch. The caching hasn't changed.

**Comment by benoit-pierre** [comment]
I have some incoming changes that do improve CI caching.

**Comment by benoit-pierre** [comment]
Still, it's weird, if you look at the latest successful CI build of master ([3 days ago](https://app.circleci.com/pipelines/github/koreader/koreader/9813/workflows/adf3d2e4-9890-40d2-b139-fe1d12faf540/jobs/14982)):
```
Skipping cache generation, cache already exists for key: build-arch1-linux-amd64-6_85-XtAzxaIav9BGK5cUJQecxFrDwd2tJ43oF_hugyDHVRg=
Found one created at 2024-04-30 20:42:38 +0000 UTC
```
And yet your run:
```
No cache is found for key: build-arch1-linux-amd64-6_85-XtAzxaIav9BGK5cUJQecxFrDwd2tJ43oF_hugyDHVRg=
```

**Comment by benoit-pierre** [comment]
Maybe it got evicted?

**Comment by benoit-pierre** [comment]
I triggered a run on master, and [a cache was restored from the same key with no issue](https://app.circleci.com/pipelines/github/koreader/koreader/9834/workflows/30bf3ae8-d366-4063-bd0c-15e2629d48ad/jobs/15004/parallel-runs/0/steps/0-104).

**Comment by benoit-pierre** [comment]
But your 2 parallel jobs, @poire-z, ended up storing each a new cache with the same key: [job 1](https://app.circleci.com/pipelines/github/koreader/koreader/9833/workflows/f461b921-e25a-49ca-b675-92c591858904/jobs/15003/parallel-runs/0/steps/0-108) & [job 2](https://app.circleci.com/pipelines/github/koreader/koreader/9833/workflows/f461b921-e25a-49ca-b675-92c591858904/jobs/15003/parallel-runs/1/steps/1-108)!

**Comment by benoit-pierre** [comment]
Yeah, I don't understand what's happening… I triggered another run of your PR, it restored cache from the previous run (`Found a cache from build 15003 at build-arch1-linux-amd64-6_85-XtAzxaIav9BGK5cUJQecxFrDwd2tJ43oF_hugyDHVRg=`. Re-triggered a run on master, and it keep picking up a cache created 4 days ago (`Found a cache from build 14976 at build-arch1-linux-amd64-6_85-XtAzxaIav9BGK5cUJQecxFrDwd2tJ43oF_hugyDHVRg=)`. Same keys. ¯\\_(ツ)_/¯

**Review by Frenzie — APPROVED** [review]

**Comment by poire-z** [comment]
Just rebased to current master (your base bump from yesterday), just to see if its cache would be re-used - but still not.

**Comment by benoit-pierre** [comment]
Yeah, caching is completely different from Github Actions, and not in a good way, IMHO. The source of the PR determine where the cache is stored, so every PR to this repo from a fork can't reuse the cache from master…

And in that particular case, the cache is keyed on the base revision, so after rebase with a base bump, you have to rebuild from scratch again.

I have some improvements, but I'm waiting for the Linux generic package stuff to avoid conflicts.

**Pull request merged**
