### PR TITLE
Restart Koreader if last instance crashed

### PR DESCRIPTION
**Pull request by Hzj-jie**
This change is to restart Koreader if last instance crashed.
Recently I found Koreader may crash randomly in suspend.sh (usually segmentation fault), and return to KSM, which is annoying. So this change adds two pieces of logic in koreader.sh. 1. Execute a user defined script (before_koreader.sh) if it exists. 2. Restart Koreader if last instance crashed and user does not suppose to preserve crash log.
You can still enable crash log by export PRESERVE_CRASH_LOG to any nonempty strings by using before_koreader.sh file. But crash log seems not be valuable to normal users, they may not even know how to find the crash.log file.

### CODE REVIEW

**Comment by Frenzie** [comment]
Didn't look at it yet but is there any provision to prevent endless crash
loops?

**Comment by lgeek** [comment]
It seems rather unwise to throw away the crash log by default. Even if the user is not going to debug koreader themselves, it would still be useful to be able to provide the log if they get around to asking for help. Maybe the script could at least rename crash.log to crash.log.1 if it already exists? Or alternatively, it could append to the log, but I guess that might grow large over time, especially in case of a crash loop as mentioned by @Frenzie.

**Comment by KenMaltby** [comment]
We might want to avoid KOReader's own "Sickel".

**Comment by NiLuJe** [comment]
What @Frenzie & @lgeek said ;).

Huge nope as is, sorry ;).

**Comment by Frenzie** [comment]
Oh, when I needed better tools I simply tossed a Debian chroot on my device. Although I dunno how well that'd work with gdb, lol.

**Comment by houqp** [comment]
@Hzj-jie were you able to find a way to consistently reproduce it? I am not able to run into this anymore after one crash a long time ago with an old build. Also, how are you compiling the build? I have switched to @NiLuJe 's toolchain recently, so maybe it's related to that.

If you were able to reproduce it, can you enable coredump and upload somewhere? Getting multiple coredumps should help us figure out whether it's a specific code path causing the segfault or the kernel is killing us.

**Comment by Hzj-jie** [comment]
The crash seems randomly, it may crash once per several days. The call stack won't help too much, the suspend stopped unexpectedly, then a segmentation fault.

@houqp and @NiLuJe Is there a guide to use new toolchain?

**Comment by houqp** [comment]
@Hzj-jie https://github.com/koreader/koxtoolchain. It's slightly different from @NiLuJe 's toolchain. Also for kobo toolchain, you need to comment out `CT_ARCH_ARM_TUPLE_USE_EABIHF=y`. I still don't know why this option breaks the build though since it's just appending `hf` to the binaries... Also, you will want to change Makefile.defs in base to point to the compiled toolchain.

**Comment by houqp** [comment]
A backtrace from coredump might give us some hints on where the crash is coming from so we know where to look at. According from your comment, the crash happens during suspend not resume?

**Comment by NiLuJe** [comment]
Brownie points if you actually manage to get the Kobo to *generate* coredumps. I failed miserably the last time I tried...

**Comment by houqp** [comment]
@NiLuJe do you know what's preventing it from generating the coredump? I also tried last night and failed >_<.

**Comment by NiLuJe** [comment]
Missing kernel support maybe? (
http://cateee.net/lkddb/web-lkddb/ELF_CORE.html)
In which case this is going to get tricky...

**Comment by NiLuJe** [comment]
Nope, not it.

```zcat /proc/config.gz | ag CORE
CONFIG_ELF_CORE=y
# CONFIG_CORE_DUMP_DEFAULT_ELF_HEADERS is not set```

And anyway... Trying to generate coredumps manually via gcore isn't going so well...

```
┌─(ROOT@(none):pts/0)───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(/mnt/onboard/.niluje/misc)─┐
└─(0.74:50%:07:26:73%:#)── gcore $$                                                                                                                                                                                                                         ──(Fri, May 13)─┘
warning: Could not load shared library symbols for 8 libraries, e.g. lib/libdl.so.2.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?
0x2ab9e276 in ?? ()
warning: Memory read failed for corefile section, 28672 bytes at 0x2aacd000.
warning: Memory read failed for corefile section, 28672 bytes at 0x2ab7e000.
warning: Memory read failed for corefile section, 32768 bytes at 0x2ac5b000.
warning: Memory read failed for corefile section, 28672 bytes at 0x2ac82000.
warning: Memory read failed for corefile section, 28672 bytes at 0x2ac8f000.
warning: Memory read failed for corefile section, 28672 bytes at 0x2aca5000.
warning: Memory read failed for corefile section, 28672 bytes at 0x2acb7000.
warning: Memory read failed for corefile section, 28672 bytes at 0x2acc8000.
Saved corefile core.1253
┌─(ROOT@(none):pts/0)───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(/mnt/onboard/.niluje/misc)─┐
└─(0.74:51%:07:26:73%:#)── gdb core.1253                                                                                                                                                                                                                    ──(Fri, May 13)─┘
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-kobo-linux-gnueabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
"/mnt/onboard/.niluje/misc/core.1253": not in executable format: File format not recognized
(gdb) q
```

According to my backlog, I stopped fighting and ended up attaching to the luajit process and waiting for a crash...

```gdb -p $(pidof reader.lua)```

**Comment by NiLuJe** [comment]
Stick that gdb session in a tmux session for a cheap-ass workaround?

**Comment by houqp** [comment]
gdb cannot recognize the core dump? This is very weird... I will give it a try tomorrow to see if I can find anything interesting...

**Comment by Hzj-jie** [comment]
Sorry for the late response, since you have concern about this change, I would close it.

**Comment by houqp** [comment]
@Hzj-jie have you tried the new toolchain? Does it help with the segfault issue?

**Comment by houqp** [comment]
@Hzj-jie based on the discussion in https://github.com/koreader/koreader/issues/1974#issuecomment-223848281, can you try the suspend script in version 195(6c8bbfd) to see if it fixes the segfault?

**Comment by Hzj-jie** [comment]
Oh, you are still updating this thread.
I have not tried new toolchain, neither suspend script in old versions these days. I have got one 'killed' error several days before. But I have not seen a segfault recently, which makes this issue even hard to debug.

**Comment by houqp** [comment]
At this point, looks like it's not a toolchain issue. And seems that it's harder to reproduce on AuraHD than H2O. At least I am not able to crash mine on suspend at all >_<

**Comment by NiLuJe** [comment]
Whee, coredump update: turns out I'm stupid, and I don't know how to use ZSH's ```ulimit``` builtin...

```ulimit -HS -c unlimited``` properly allows stuff to coredump :).

That was the good news. The bad news is, my GDB build still can't make heads or tails of those coredumps...

**Comment by houqp** [comment]
Yeah, executable is always required for gdb to read coredump :)

But I also tried `ulimit -c unlimited`! How come it's not working for me? Did you get the coredump from the current working directory?

**Comment by NiLuJe** [comment]
Admittedly, I only tried to coredump random stuff by sending SIGQUIT signals, but, yeah, that appeared to work? And yeah, it dumps in the PWD of the process.

**Pull request closed without merging**
