### PR TITLE
Some more Kobo scripts tweaks

### PR DESCRIPTION
**Pull request by NiLuJe**
Because it'd been a while :D.

This unfortunately doesn't fix the broken zforce resume I'm seeing, so that workaround is still in place.

### CODE REVIEW

**Comment by tigran123** [comment]
This makes `suspend.sh` functionally equivalent to what I am running and I am quite happy with it --- no crashes or battery drainage so far (and I've been using my Aura H2O heavily for the past two days). So, I approve it, but leave it for @houqp or @chrox to merge, if they agree.

**Comment by Frenzie** [comment]
I must've missed when this wakeup count thing was added. Besides that (and the sickel thing) there's really no difference anyway, is there?

**Comment by houqp** [comment]
Yeah, according to the release kernel source, wakeup count really should have no impact on the suspend/resume behavior. So maybe the released kernel is not the one that's actually shipped?

**Comment by NiLuJe** [comment]
@houqp: That's always been bothering me. At the *very least* the prod one is built with funky extra config switches.

**Comment by KenMaltby** [comment]
The "WakeUp Count" thing never made sense to me (But I just thought it was something you guys thought up that was over my head) and Sickel only survived for a couple of firmware releases before Kobo abandoned it, as I recall.  

+one to the idea of disabling the wakeup count, for Kobos.

Luck;
Ken

**Pull request merged**
