### PR TITLE
Fake battery status in readerfooter_spec to succeed on devices with batteries

### PR DESCRIPTION
**Pull request by Frenzie**
Cf. <https://github.com/koreader/koreader/pull/6370#issuecomment-662382487>.

@pazos No spies/stubs necessary here. ^_^

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/6417)

### CODE REVIEW

**Comment by pazos** [comment]
Oh! It seems that we don't need the workaround in https://github.com/koreader/koreader/blob/master/frontend/device/sdl/powerd.lua#L8-L9

**Comment by Frenzie** [comment]
@pazos Oh, -1 is what SDL returns on desktops? It was something like 60% on my laptop when I looked at this.

**Comment by Frenzie** [comment]
@pazos I don't know, doesn't that look a bit weird? 
Screenshot_2020-07-22_18-02-05

**Comment by pazos** [comment]
>  doesn't that look a bit weird?

Yeah, just a bit :p. I really don't care about -1% vs 0%, but the comment in the code is no longer true.

**Pull request merged**
