### PR TITLE
Device:Android: wait until lights dialog is closed

### PR DESCRIPTION
**Pull request by hasezoey**
before trying to read return status

like i had said in #10722 i dont really like this implementation, but i am not experienced enough to add a callback into the JNI

re #10722

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10726)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Feel free to go back down to 250ms, that shouldn't change much in the grand scheme of things, while being significantly less annoying for the user ;).

**Comment by hasezoey** [comment]
> Feel free to go back down to 250ms

if you mean changing `FFIUtil.sleep(1)` to `FFIUtil.sleep(250)`, then i dont think it is a good idea , because at first while i first tried this i had it ad `FFIUtil.sleep(100)` and got ANR'd for quite some time (i dont full know what unit `sleep` is using: usec, msec or seconds? while testing it felt like seconds)

**Comment by Frenzie** [comment]
> FFIUtil.sleep(1) to FFIUtil.sleep(250)

usleep(250)

**Comment by hasezoey** [comment]
updated and tested, works fine at 250

**Review by pazos — APPROVED** [review]

**Pull request merged**
