### PR TITLE
Assorted minor tweaks

### LINKED ISSUE #4472: Wifi status not updated, cannot disable wifi on kindle
* KOReader version: v2018.12
* Device: Kindle Paperwhite 3

#### Issue
It seems network status in the menu is not updated and wifi cannot be disabled.
#### Steps to reproduce
Go to wifi tab on kindle, tap Wi-Fi connection

### PR DESCRIPTION
**Pull request by NiLuJe**
* WiFi handling on Kindle (fix #4472)
* Crappy attempt at handling key repeat for the Forma pageturn buttons
* Fix long-standing OTA inconsistencies on Kindle so that OTAManager picks the right binaries (Massive oversight on my part there -_-") (re #4497).
   * Use the proper binaries (kindle5 -> kindle) on the K4
   * Use the proper binaries (kindlepw2) on every Kindle since the PW2.

### CODE REVIEW

**Comment by pazos** [comment]
@NiLuJe: not sure if I understand *handling key repeat for the Forma pageturn buttons*. Do you want to avoid them or to react to them as key press/release?

**Comment by pazos** [comment]
Pseudocode
```
function Input:morph(ev)
    if ev.type == EV_KEY and ev.code == (buttons) then
        ev.value = 1 -- replace repeat for release
    end
end
```

**Comment by pazos** [comment]
> This reacts to them, and treats them as KeyPress, as long as that's coming from a pageturn button. All other repeats are ignored.

ok, updated the example. It can be installed as an event hook for kobos.

**Comment by NiLuJe** [comment]
@pazos:

I'd tend to agree with you in theory, except here:

* It's generic enough to make sense in the common code. Only the crappy staggering bit is potentially device-speciifc, and i'm already not happy with it ;).
* I'd *really* like to keep a separate KeyRelease event, because ideally I would actually like to handle it differently than a Press: namely, making repeat pageturn force A2 refresh mode, while a release after a string of repeat would be a forced flashing GC16.

**Pull request merged**
