### PR TITLE
Android: Don't mark the platform as should_restrict_JIT

### PR DESCRIPTION
**Pull request by NiLuJe**
And see how much stuff breaks \o/

Depends on https://github.com/koreader/android-luajit-launcher/pull/278 (to hopefully break less/more stuff :D).

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7024)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
I'm mainly worried about the Android 4 ereaders but damn the torpedoes, full speed ahead! ;-)

**Comment by NiLuJe** [comment]
Yeah, if push comes to shove, we can limit this to Android >= 6 or something as mentioned on Gitter ;).

**Comment by Frenzie** [comment]
Careful, I'll put Android 4 back on my old phone just to complain. :-p

**Comment by ptrm** [comment]
Not sure it's connected, but after upgrading from a15106f to gb2b9b49 Koreader fails to get activated after having started once. It show document loading info nd crashes (not sure how to find the logs). Closing the task and starting anew usually helps. That's on Android 10 on Onyx Boox Nova 3.

Reporting here due to the "And see how much stuff breaks \o/" part ;)

**Comment by NiLuJe** [comment]
I did manage to hit something like that when I was chaining test builds,
but I can't actually reproduce it anymore (after a clean install, i.e.,
uninstall first).

**Comment by NiLuJe** [comment]
Okay, writing that jinxed it ;p. It does start up fine on the second try,
though. Can't look at adb right now, but from what I recall, it was
something about failing to load some bundled libraries...

**Comment by ptrm** [comment]
Yeah, 21af94 still does that. Repro path that works most of time is: launch koreader with book open -> switch to another task -> cloe Koreader task -> launch koreader -> crash. Will try to post a log in a separate issue if I manage to find one.

**Pull request merged**
