### PR TITLE
Update base

### PR DESCRIPTION
**Pull request by NiLuJe**
Depends on [base #347](/koreader/koreader-base/pull/347).

### CODE REVIEW

**Comment by houqp** [comment]
can you update the base :P

**Comment by NiLuJe** [comment]
I did ;).

**Comment by chrox** [comment]
Seems the master branch of luajit breaks Koreader:
```
./luajit: ./ffi/blitbuffer.lua:158: bad argument #1 to 'rshift' (number expected, got cdata)
stack traceback:
	[C]: in function 'rshift'
	./ffi/blitbuffer.lua:158: in function 'div255'
	./ffi/blitbuffer.lua:200: in function 'blend'
	./ffi/blitbuffer.lua:621: in function 'setter'
	./ffi/blitbuffer.lua:711: in function 'blitFrom'
	./ffi/blitbuffer.lua:752: in function 'colorblitFrom'
	frontend/ui/rendertext.lua:173: in function 'renderUtf8Text'
	frontend/ui/widget/textwidget.lua:51: in function 'paintTo'
	frontend/ui/widget/verticalgroup.lua:36: in function 'paintTo'
	frontend/ui/widget/verticalgroup.lua:36: in function 'paintTo'
	frontend/ui/widget/container/framecontainer.lua:51: in function 'paintTo'
	frontend/ui/widget/container/inputcontainer.lua:64: in function 'paintTo'
	frontend/ui/uimanager.lua:403: in function '_repaint'
	frontend/ui/uimanager.lua:468: in function 'handleInput'
	frontend/ui/uimanager.lua:544: in function 'run'
	./reader.lua:145: in main chunk
	[C]: at 0x00404270
```

Since we has been using the v2.1 branch for a long time, @NiLuJe could we stay with that? And the new commits in the master branch has already been merged to v2.1. As I tested the latest v2.1 branch works fine with Koreader.

**Comment by NiLuJe** [comment]
Unless I was *really* tired, that was supposed to be a checkout of the v2.1 branch >_<".

I'll triple-check, fix it and/or roll-back to the previous state.

**Comment by NiLuJe** [comment]
Yeeeaaah, I messed up (twice!).

Sleep is good for you, people!

My bad :/.

**Comment by NiLuJe** [comment]
[base #348](/koreader/koreader-base/pull/348) should put things to right...

**Pull request merged**
