### PR TITLE
ImageViewer: Followup to #9529

### PR DESCRIPTION
**Pull request by NiLuJe**
* ImageViewer: Minor code cleanups
* GestureDetector: Fix the `distance` field of `two_finger_pan` & `two_finger_swipe` gestures so that it's no longer the double of the actual distance traveled. Get rid of existing workarounds throughout the codebase that had to deal with this quirk.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9544)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Commit history includes the "snap to" experiment from #9533 ;).

(For archeological purposes only: this'll be a squash).

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/9544)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NiLuJe)

**Comment by zwim** [comment]
Also in `readerlink.lua` there are some `math.pow(xx, 2)` which can be optimized, if you want  to :)

Similar to:
https://github.com/koreader/koreader/blob/a3fda69dd4628ec1b354ebe47b77e2ba83cc8da7/frontend/apps/reader/modules/readerlink.lua#L892

lines might be:
```
frontend/apps/reader/modules/readerlink.lua:892:                local start_dist = math.pow(link.x0 - pos_x, 2) + math.pow(link.y0 - pos_y, 2)
frontend/apps/reader/modules/readerlink.lua:893:                local end_dist = math.pow(link.x1 - pos_x, 2) + math.pow(link.y1 - pos_y, 2)
frontend/apps/reader/modules/readerlink.lua:982:                            segment_dist = math.pow(segment.y0 - pos_y, 2)
frontend/apps/reader/modules/readerlink.lua:984:                            segment_dist = math.pow(pos_y - segment.y1, 2)
frontend/apps/reader/modules/readerlink.lua:990:                            segment_dist = segment_dist + math.pow(segment.x0 - pos_x, 2)
frontend/apps/reader/modules/readerlink.lua:992:                            segment_dist = segment_dist + math.pow(pos_x - segment.x1, 2)
frontend/apps/reader/modules/readerlink.lua:1015:                    local start_dist = math.pow(link.start_x - pos_x, 2) + math.pow(link.start_y - pos_y, 2)
frontend/apps/reader/modules/readerlink.lua:1016:                    local end_dist = math.pow(link.end_x - pos_x, 2) + math.pow(link.end_y - pos_y, 2)
frontend/apps/reader/modules/readerlink.lua:1052:        if max_distance and selected_distance2 and selected_distance2 > math.pow(max_distance, 2) then
```

**Comment by NiLuJe** [comment]
Yeah, I left a few as-is, will probably clean those up in another PR ;).

**Comment by zwim** [comment]
@NiLuJe  Another word on optimizing (totally unrelated to the PR here): You have introduced an rshift in 
https://github.com/koreader/koreader/blob/a3fda69dd4628ec1b354ebe47b77e2ba83cc8da7/frontend/ui/uimanager.lua#L257

Well _it works_, but I don't really understand why it works (although I understand the intention). The safe way would be to write it as:
```
            p = math.floor((e + s)/2) -- Not necessary to use (s + (e -s) / 2) here! 
```

Would you mind, to change this back, or explain the exact function to me (and why the shift works only for int values < 32 bit)? 

(lua number=double;  a bitshift shifts the exponent and mantissa; as the exponent in a double is offsetted by 1023 a bitshit will shift also the bit pattern of the exponent; I am lost here, and I don't really have the time and the willing to dig into this as this seems to be a feature of luajit).

**Comment by NiLuJe** [comment]
@zwim: The input range is low enough that we should be in the clear ;).

As for why this works, it's because the BitOp module doesn't actually work on the double, it coerces to integer types first (c.f., all the gory details here: https://bitop.luajit.org/semantics.html).

I assume that's what you meant, and now why left shifts can be used instead of power-of-two multiplications, and right shift instead of power-of-two divisions?

**Pull request merged**
