### PR TITLE
FileChooser: "percent - unopened - finished last" consider status "on hold" as 0%

### PR DESCRIPTION
**Pull request by Commodore64user**
adds instruction for files labelled "on hold" to sorting function `percent - unopened - finished last`

`90% > 50% > 0% or on hold > unopened > 100% or finished`

continuation from #11524, #11472 and #11369

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11542)

### CODE REVIEW

**Comment by Commodore64user** [comment]
@hasezoey any chance you could offer a helping hand with https://github.com/koreader/koreader/pull/11524#issuecomment-1984110990 

I have tried doing number 2) but I seem to be missing something.

**Comment by hasezoey** [comment]
> I have tried doing number 2) but I seem to be missing something.

to my understanding it should be as easy as replacing all instances of `item.percent_finished` with `item.precent_sorting` (or `item.sorting_percentage` or any other property name) in the following lines:
https://github.com/koreader/koreader/blob/dd618a4e426e4f2d73d740f3ee8f780e18cec13c/frontend/ui/widget/filechooser.lua#L214-L250
or maybe some special case for the `== "completed"` check to also display it as 100% (if wanted).

or am i missing something?

**Comment by Frenzie** [comment]
That's all I meant in any case. :-)

**Comment by Commodore64user** [comment]
> to my understanding it should be as easy as replacing all instances of `item.percent_finished` with `item.precent_sorting` (or `item.sorting_percentage` or any other property name) in the following lines:

I tried that already, that crashes the application. That’s why i was hoping you could have a look. I think i am now blind to why it wont work. 

> That's all I meant in any case. :-)

That being…?

**Comment by Frenzie** [comment]
What @hasezoey said.

**Comment by hasezoey** [comment]
made a commit changing it to a extra property, i dont know if the maintainers want a PR for it though:
https://github.com/hasezoey/koreader/commit/f77d1321f87ddf7af606fa3597aed6b15eb9eb0a

**Comment by Frenzie** [comment]
> i dont know if the maintainers want a PR for it though

As opposed to what? xD Or do you mean as a separate PR vs in this PR. Either way is fine by me.

**Comment by Commodore64user** [comment]
@hasezoey i can implement it here if all the same to you. Also i can add the “on hold” bit and see what i was missing. Thanks btw.

**Comment by hasezoey** [comment]
> As opposed to what? xD Or do you mean as a separate PR vs in this PR. Either way is fine by me.

just meant if it is still wanted to be changed that way, to me it just seemed trivial and not doing much, so i didnt know if it was worth it to create a PR.

though now it is created as #11592

**Comment by Commodore64user** [comment]
Will close this PR as soon as https://github.com/koreader/koreader/pull/11592 is merged.

**Pull request closed without merging**
