### PR TITLE
Bump base for a few dependencies

### PR DESCRIPTION
**Pull request by Frenzie**
* Bump FBInk to v1.20.3
* Bump LodePNG to 11/20/19
* Minor ffi.util cleanups (koreader/koreader-base#1015)
* thirdparty/libffi v3.3 (koreader/koreader-base#1017)

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/5636)

### CODE REVIEW

**Comment by pazos** [comment]
Fixes #5648

**Comment by poire-z** [comment]
(Frenzie: you may want to trigger a CircleCI re-build now that the GNU site seems ok - strangely, I'm not allowed to do it)

**Comment by Frenzie** [comment]
Have you "connected" GH and CircleCI? Sometimes it also forgets about it for some reason.

**Comment by poire-z** [comment]
I usually just log-in to CircleCI with my github account, and I can act on our stuff there..
For example, I can on #5647, which points to https://circleci.com/gh/koreader/koreader/3976.
But I can't on this PR, which strangely points to https://circleci.com/gh/Frenzie/koreader/1504 (`Frenzie/koreader`, not `koreader/koreader`, dunno why :)

**Comment by Frenzie** [comment]
Oh, it's because I have CircleCI enabled on my own repo. It allows me to test CI stuff without creating a messy PR bothering everyone with experiments.

It's also pretty useful in that the CI starts when I push, so by the time I open a PR it's already almost done. I believe it may also help to reduce the load, by running it off my quota rather than KOReader's.

I didn't realize it meant other people couldn't restart the build (within the context of a PR). I'm pretty sure I always create my PRs in the GH default way that enables anybody with write access to push to the branch in question.

**Pull request merged**
