### PR TITLE
[feat, UX] Add multiswipe recorder

### PR DESCRIPTION
**Pull request by Frenzie**

### CODE REVIEW

**Comment by NiLuJe** [comment]
Obligatory Konami code reference. :D

**Comment by Frenzie** [comment]
Haha, it does look a bit like it! :D

**Comment by poire-z** [comment]
(Many multiswipe PRs, don't really know where to put my comments :) so putting them in the related PR even if one single place would may be better).

When recording/adding a new gesture, one needs to restart koreader to see it in the menu and be able to assign some action to it.
Not really bothering, but might need some InfoMessage inviting to do so if that can't be workarounded.

**Comment by Frenzie** [comment]
It's easy enough to work around, but I was hoping there was something more proper in place, see #4651.

```diff
diff --git a/frontend/apps/reader/modules/readergesture.lua b/frontend/apps/reader/modules/readergesture.lua
index 45f75eff..a180b776 100644
--- a/frontend/apps/reader/modules/readergesture.lua
+++ b/frontend/apps/reader/modules/readergesture.lua
@@ -55,6 +55,15 @@ function ReaderGesture:initGesture()
     G_reader_settings:saveSetting(self.ges_mode, gesture_manager)
 end
 
+function ReaderGesture:genMultiswipeSubmenu()
+    return {
+        text = _("Multiswipe"),
+        sub_item_table = self:buildMultiswipeMenu(),
+        enabled_func = function() return self.multiswipes_enabled end,
+        separator = true,
+    }
+end
+
 function ReaderGesture:addToMainMenu(menu_items)
     menu_items.gesture = {
         text = _("Gesture manager"),
@@ -71,7 +80,7 @@ function ReaderGesture:addToMainMenu(menu_items)
             {
                 text = _("Multiswipe recorder"),
                 enabled_func = function() return self.multiswipes_enabled end,
-                callback = function()
+                callback = function(touchmenu_instance)
                     local multiswipe_recorder
                     multiswipe_recorder = InputDialog:new{
                         title = _("Multiswipe recorder"),
@@ -92,6 +101,8 @@ function ReaderGesture:addToMainMenu(menu_items)
                                         if not recorded_multiswipe then return end
                                         logger.dbg("Multiswipe recorder detected:", recorded_multiswipe)
                                         custom_multiswipes:addTableItem("multiswipes", recorded_multiswipe)
+                                        -- TODO implement some nicer method in TouchMenu than this ugly hack for updating the menu
+                                        touchmenu_instance.item_table[3] = self:genMultiswipeSubmenu()
                                         UIManager:close(multiswipe_recorder)
                                     end,
                                 },
```

> even if one single place would may be better

I think just opening a new issue would be easier to keep track of. :-)

**Pull request merged**
