### PR TITLE
UIManager: Optimize binary insert

### PR DESCRIPTION
**Pull request by zwim**
This change speeds up the binary insert by 10%.
Some additional tests have to be done (for `tickAfterNext` and `nextTick`).

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9600)

### CODE REVIEW

**Comment by NiLuJe** [comment]
> As long as insertion order is preserved, it should more or less behave?

e.g., possibly the rightmost insertion variant as described in https://rosettacode.org/wiki/Binary_search?

**Comment by zwim** [comment]
Yep, should work. If a new scheduled function uses an already scheduled time, the new function is inserted _after_ the existing function (for fairness).

Functions was tested conscientious with different test data, PR was shortly tested on a device.

**Comment by zwim** [comment]
> e.g., possibly the rightmost insertion variant as described in https://rosettacode.org/wiki/Binary_search?

yes but only by chance, as I created this from scratch :)

**Comment by NiLuJe** [comment]
> yes but only by chance, as I created this from scratch :)

Except this looks closer to the first variant,j except using low instead of mid?

**Comment by hius07** [comment]
Can sched_time be **between** the existing values of self._task_queue?
If so, the binary insertion index requires additional shift.

**Comment by NiLuJe** [comment]
> Can sched_time be **between** the existing values of self._task_queue? If so, the binary insertion index requires additional shift.

Yup:

schedulein(20)
scheduleIn(5)
scheduleIn(10)

**Comment by zwim** [comment]
I have added some additional tests to `uimanager_spec.lua` to check the behavior of `schedule`, `nextTick` and `tickAfterNext`.

**Comment by NiLuJe** [comment]
Ideally, that sort of test should also stress-test what happens in case of collisions (ideally, a *lot* of collisions) to confirm thyat insertion order is preserved ;).

**Comment by NiLuJe** [comment]
> > yes but only by chance, as I created this from scratch :)
> 
> Except this looks closer to the first "standard" variant, except returning low instead of mid?

I'm still confused re: this, too ;).

**Comment by zwim** [comment]
@NiLuJe I hope, I can follow you.

I have done millions insertion tests with random numbers in my originary/private test suite (and there are massive  collisions). Should I include them in 'uimanager' bench or spec?

Logically they would have to be in spec, but then the test time would significanty increase. Or would it be sufficient to put them in bench?

**Comment by NiLuJe** [comment]
Yep, bench sounds good ;).

**Comment by NiLuJe** [comment]
I would also definitely switch to a `while` construct, which will allow us to get rid of the dumb "array is empty" special-case; as well as, possibly, switch to slightly descriptive variable names (I went with lo/mid/hi in the following snippet):

```diff
diff --git a/frontend/ui/uimanager.lua b/frontend/ui/uimanager.lua
index 20a80c594..4c1b6777d 100644
--- a/frontend/ui/uimanager.lua
+++ b/frontend/ui/uimanager.lua
@@ -227,35 +227,23 @@ end
 
 -- Schedule an execution task; task queue is in ascending order
 function UIManager:schedule(sched_time, action, ...)
-    local p, s, e = 1, 1, #self._task_queue
-    if e ~= 0 then
-        -- Do a binary insert.
-        repeat
-            p = bit.rshift(e + s, 1) -- Not necessary to use (s + (e -s) / 2) here!
-            local p_time = self._task_queue[p].time
-            if sched_time > p_time then
-                if s == e then
-                    p = e + 1
-                    break
-                elseif s + 1 == e then
-                    s = e
-                else
-                    s = p
-                end
-            elseif sched_time < p_time then
-                if s == p then
-                    break
-                end
-                e = p
-            else
-                -- For fairness, it's better to make sure p+1 is strictly less than p.
-                -- Might want to revisit that in the future.
-                break
-            end
-        until e < s
+    local lo, hi = 1, #self._task_queue
+    while lo <= hi do
+        -- NOTE: We should be (mostly) free from overflow here, thanks to LuaJIT's BitOp semantics.
+        --       For more fun details about this particular overflow,
+        --       c.f., https://ai.googleblog.com/2006/06/extra-extra-read-all-about-it-nearly.html
+        -- NOTE: For more fun reading about the binary search algo,
+        --       c.f., https://reprog.wordpress.com/2010/04/19/are-you-one-of-the-10-percent/
+        local mid = bit.rshift(lo + hi, 1)
+        local mid_time = self._task_queue[mid].time
+        if sched_time >= mid_time then
+            lo = mid + 1
+        else
+            hi = mid - 1
+        end
     end
 
-    table.insert(self._task_queue, p, {
+    table.insert(self._task_queue, lo, {
         time = sched_time,
         action = action,
         argc = select("#", ...),
```

(Also includes refs to tonight's reading ;p).

It took me a gooood long while to grok the differences between the Wikipedia implementations (which uses an exclusive upper bound, which is quite likely less readable in Lua), the Rosetta code one and yours. If I understood right, the only difference is the direction in which you chop on a perfect match?

**Comment by NiLuJe** [comment]
> It took me a gooood long while to grok

As in, it took writing some Python ;p. (Mostly because LuaJIt's shell is impossible to work in).

```py
def wikipedia(array, val):
    lo = 0
    hi = len(array)
    while lo < hi:
        mid = (lo + hi) >> 1
        if array[mid] > val:
            hi = mid
        else:
            lo = mid + 1
    return hi - 1

def rosetta(array, val):
    lo = 0
    hi = len(array) - 1
    while lo <= hi:
        # invariants: val >= array[i] for all i < lo
        #             val < array[i] for all i > hi
        mid = (lo + hi) >> 1
        it += 1
        if array[mid] > val: # val < array[mid]
            hi = mid - 1
        else:               # val >= array[mid]
            lo = mid + 1
    return lo

def zwim(array, val):
    lo = 0
    hi = len(array) - 1
    while lo <= hi:
        mid = (lo + hi) >> 1
        it += 1
        if val >= array[mid]: # array[mid] <= val
            lo = mid + 1
        else:                 # array[mid] > val
            hi = mid - 1
    return lo
```

**Comment by Frenzie** [comment]
Iirc the Debian-compiled LuaJIT shell is significantly less impossible so we may have some slightly incorrect option or something.

**Comment by NiLuJe** [comment]
> Iirc the Debian-compiled LuaJIT shell is significantly less impossible so we may have some slightly incorrect option or something.

That was my native Gentoo build, too, FWIW ;).

I can't see anything relevant in the Debian sources: https://packages.debian.org/source/sid/luajit

**Review by NiLuJe — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/9600)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zwim)

**Comment by Frenzie** [comment]
The current version on Ubuntu 22.04 also seems to be weird about arrow keys, but I'm pretty sure it used to be different. Maybe it was just that old Debian stable had a really old version for example and it broke upstream sometime in the past 5 years or so.

**Comment by Frenzie** [comment]
PS Normally I'd quickly give that a go in some Docker container or something but I'm not going to waste a couple hundred MB of bandwidth for that right now. ;-)

**Comment by Frenzie** [comment]
Nope, definitely not. I frequently use the regular Lua shell and I was explicitly surprised to find that the LuaJIT shell didn't necessarily act completely weird when pressing arrow keys. But I might be thinking of a different LuaJIT shell, for example the one from https://github.com/torch/luajit-rocks

**Comment by zwim** [comment]
fwiw my luajit shell also has problems with the arrow keys, lua's has not. (I am on Gentoo)

**Comment by Frenzie** [comment]
There are some kind of readline inserting utilities you can use btw.

**Comment by zwim** [comment]
Solved with using `rlwrap luajit` see https://github.com/LuaJIT/LuaJIT/issues/369

**Comment by NiLuJe** [comment]
Huh, that's neat! Thanks!

**Pull request merged**
