### PR TITLE
fix missing glyphs by packaging freefonts again.

### PR DESCRIPTION
**Pull request by pazos**
Also disable battery completely from defaults/option in desktop linux as it always return 0%

Background in #6210

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/6218)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Ah, yeah, we're shipping freefont svn, the latest release is hilariously old ;).

**Comment by pazos** [comment]
lintian outputs
```
W: koreader: opentype-font-wrong-filename usr/lib/koreader/fonts/freefont/FreeSans.ttf
W: koreader: opentype-font-wrong-filename usr/lib/koreader/fonts/freefont/FreeSerif.ttf
```

are they otf?

**Comment by NiLuJe** [comment]
Yeah, they're OTF renamed as TTF to avoid having to change seven billion references, most notably in the mupdf patches.

**Comment by poire-z** [comment]
(Oh, allright, so that was the icons from FreeSerif that were missing, and not the ones from nerdfonts like I too quickly assumed :/)

**Comment by JasonInOttawa** [comment]
I built and installed a deb and the status bar looks great:

Screenshot from 2020-06-01 19-56-30

**Pull request merged**
