### PR TITLE
bump base

### LINKED ISSUE #9422: PocketBook: Crash when connecting to an OPDS server via HTTPS
* KOReader version: 2022.07
* Device: pocketbook touch lux 4 PB627

#### Issue

Koreader crashes when I try to open any ODPS library.
But it works with local odps-calibre library.

#### Steps to reproduce

open the ODPS menu and select eg. standard ebooks

[crash.log](https://github.com/koreader/koreader/files/9290870/crash.log)

### LINKED ISSUE #11055: Pocketbook cannot update koreader
* KOReader version: 2023.08
* Device: Pocketbook Inkpad Color 2

#### Issue
Koreader detects a new version is available (2023.10), tries to download, but it says that "Koreader couldn't be updated." and asks to retry. If I choose retry, it says it downloads a full package, but this fails as well after a couple of minutes, then asks to delete temporary files.
Wi-Fi is on.

I activated verbose logging and you can see the full crash.log here (and also an abridged version containing only the logs from the download step)

[crash.log](https://github.com/koreader/koreader/files/13209814/crash.log)
[brief.log](https://github.com/koreader/koreader/files/13209815/brief.log)

### PR DESCRIPTION
**Pull request by benoit-pierre**
- https://github.com/koreader/koreader-base/pull/2010 (close #9422, close #11055)

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12956)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by NiLuJe** [comment]
The commit hash seems wrong?

i.e., it's actually `9c75c5ad685b47d4b5195cad8d715f060e880d79` in koreader/koreader-base, but this points to `922973f2e11610fb0548dc091e1ba4843a0ce975` (your own tree?).

This leads to git rightfully failing to update the submodule:

```
fatal: transport 'file' not allowed
fatal: Fetched in submodule path 'base', but it did not contain 922973f2e11610fb0548dc091e1ba4843a0ce975. Direct fetching of that commit failed.
```

**Comment by Frenzie** [comment]
I noticed it was wrong the other date (a little too late), but it still worked out for me at the time so I ignored it in favor of the next natural base bump.

E.g., this is my local base after updating the submodule a few days ago:
```
commit 922973f2e11610fb0548dc091e1ba4843a0ce975 (HEAD)
Author: Benoit Pierre <benoit.pierre@gmail.com>
Date:   Thu Dec 12 17:10:19 2024 +0100

    [TMP] workflow dispatch

commit 9c75c5ad685b47d4b5195cad8d715f060e880d79 (origin/master, origin/HEAD)
Author: Benoit Pierre <benoit.pierre@gmail.com>
Date:   Wed Dec 25 10:43:18 2024 +0100

    drop openssl in favor of libressl
```

**Comment by Frenzie** [comment]
I have git 2.45.2.

**Comment by NiLuJe** [comment]
Huh. Doesn't resolve on my end (git 2.47.0), but I probably don't have @benoit-pierre's remote setup in my front chechout.

(I assume if I had, it would automagically figure it out).

**Comment by Frenzie** [comment]
Neither do I though, on this particular laptop:

```
$ git remote -v
frenzie git@github.com:Frenzie/koreader-base.git (fetch)
frenzie git@github.com:Frenzie/koreader-base.git (push)
origin  https://github.com/koreader/koreader-base.git (fetch)
origin  https://github.com/koreader/koreader-base.git (push)
```

Which would suggests it's not related to git at all, but rather to GitHub, in which case it's most likely this (probably coupled with an x-hour undo functionality):
image

**Comment by benoit-pierre** [comment]
Damn, sorry about that… That's a commit I have on my master branch to be able to test workflow dispatching on derived branches.

**Pull request merged**
